Non-validating notaries can see all inputs
corda/corda pull request #1307
Opened 2017-08-23 09:27 UTC by kchalkias

In order to make sure non-validating notaries can verify they see all inputs, a model with a sub Merkle tree for inputs states is implemented. There was a security issue to be handled, according to which one could hide all inputs from a filtered tx, and thus the sub Merkle tree was not enough (actually not visible at all). To circumvent the aforementioned problem, we always set the leftmost leaf in the Merkle tree to be `oneHash` (similar to `zeroHash`, but all bits are set to one).
![inputssubmerkletree](https://user-images.githubusercontent.com/25659162/29608526-4dcfdf6e-87ec-11e7-8790-f4d2ec06d83d.jpg)

Here is a visual partial tree representation for a filtered tx sent to a non-validating notary.
![non-validatingnotariesseeallinputs](https://user-images.githubusercontent.com/25659162/29608948-94b5d590-87ed-11e7-9a2c-362b30be6ddf.jpeg)

Bear in mind that the sub Merkle tree model has been selected between 3 candidate approaches, after various discussions as the most elegant solution:
[AWG-Numberofinputsvisibletonon-validatingnotaries-230817-1020.pdf](https://github.com/corda/corda/files/1244840/AWG-Numberofinputsvisibletonon-validatingnotaries-230817-1020.pdf)

2017-08-23 10:03 UTC, mikehearn commented
A few quick questions before I dig into the code:

* Why introduce a new special hash when we already have the zero hash defined?
* Why treat the inputs list specially, vs using sub-levels for all lists?

2017-08-23 10:06 UTC, kchalkias commented
> Why introduce a new special hash when we already have the zero hash defined?

partial merkle trees do not allow zero hashes

> Why treat the inputs list specially, vs using sub-levels for all lists?

yes (unless there is a reason to do for every component, but I didn't find any yet)

2017-08-23 10:11 UTC, mikehearn commented
Is it hard to do for every list-like component?

Is the issue with zero hashes in PMT is that that's a token used for padding to ensure the tree is binary?

2017-08-23 10:25 UTC, kchalkias commented
> Is it hard to do for every list-like component?

Actually, there is some added complexity to have a sub tree per component-list
a) We might add unnecessary zeroHashes per subTree, resulting bigger tx size
b) The aforementioned security issue (hiding all components in a particular list) may apply to the rest of the lists as well; I feel we might need a special hash (like `oneHash`) per component or I cannot distinguish (count) what is missing or not. If everything was zeroHash (how can I tell what belongs to what?)
c) Current approach takes advantage of the fact that we only handle 1 sub-tree and due to ordering it happens to be the first leaf. Not sure what would be the solution if we needed to have knowledge on the number of Components per list. I tried to come up with a generic solution, but still no luck. Except if we don't care about the knowledge of how many components there are per list and there is another reason behind the sub tree splitting (I am still not aware of any). 

> Is the issue with zero hashes in PMT is that that's a token used for padding to ensure the tree is binary?

I guess so, my sense is it will become confusing to use the same flag for everything and maybe there are secret attacks we still didn't think of. In fact there is a `require(zeroHash !in includeHashes) { "Zero hashes shouldn't be included in partial tree." } in pmt build (probably for duplication check (you may have more than one) and the fact that they don't represent a real component.

2017-08-23 10:34 UTC, mikehearn commented
Size of the Merkle tree doesn't affect size of the transaction, right?

Can we just include counts in the signature metadata alongside the Merkle tree root?

Agree on the zero vs one hash.

2017-08-23 10:38 UTC, mikehearn commented
In your diagram something isn't clear - you picked 4 inputs for the example, so the result is a binary tree. But what if we had 5 inputs?

2017-08-23 10:39 UTC, kchalkias commented
@mikehearn there are other candidate solutions as well, in the initial PR comment (attached pdf),  but the rule is not enforced automatically/inherently as with the sub trees; you have to request for the clear wtx afterwards (eg when asked by a regulator) to ensure no cheating.

> Size of the Merkle tree doesn't affect size of the transaction, right?

But you need to send the additional PMTs on filtered transactions. Yes the wtx is not affected, but the filteredTx does.

> Can we just include counts in the signature metadata alongside the Merkle tree root?

This is similar to the ComponentMapper element in the pdf attached. But again attaching it on a signature doesn't mean the rule is applied automatically, the signer may cheat.

2017-08-23 10:41 UTC, kchalkias commented
> you picked 4 inputs for the example

Which example? in the diagram there are 3 inputs and a zero hash to make it binary. If there were 5 we would need another 3 zeros. It's a standard Merkle tree

2017-09-05 10:29 UTC, mikehearn requested changes

2017-09-05 10:29 UTC, mikehearn commented on core/src/main/kotlin/net/corda/core/crypto/PartialMerkleTree.kt
> +        if (hashesToCheck.groupBy { it } != usedHashes.filter { it != SecureHash.oneHash }.groupBy { it })
This groupBy itself logic is kind of weird. What's it really doing here? Is this some attempt to do an order-insensitive compare?

2017-09-05 10:29 UTC, mikehearn commented on core/src/main/kotlin/net/corda/core/crypto/PartialMerkleTree.kt
> +    fun rootAndUsedHashes(node: PartialTree, usedHashes: MutableList<SecureHash>): SecureHash {
Is it intentional that this is no longer private? Could it be internal?

2017-09-05 10:29 UTC, mikehearn commented on core/src/main/kotlin/net/corda/core/crypto/PartialMerkleTree.kt
> +    fun leftMostLeaf(node: PartialTree): SecureHash {
Could this be internal?

2017-09-05 10:29 UTC, mikehearn commented on core/src/main/kotlin/net/corda/core/transactions/MerkleTransaction.kt
> +            val pmt = if (!filteredLeaves.inputs.isEmpty()) {
use `if (filteredLeaves.inputs.isNotEmpty())` as it reads more naturally in English.

2017-09-05 10:29 UTC, mikehearn commented on core/src/main/kotlin/net/corda/core/transactions/MerkleTransaction.kt
> +                PartialMerkleTree.build(merkleTree, listOf(inputsMerkleTree!!.hash)
An NPE in the case of a malformed transaction isn't ideal. Can you cast away the nullity with a more specific exception here?

2017-09-05 10:29 UTC, mikehearn commented on core/src/main/kotlin/net/corda/core/transactions/MerkleTransaction.kt
> +            } else if (!wtx.inputs.isEmpty()) {
ditto, use isNotEmpty

2017-09-05 10:29 UTC, mikehearn commented on core/src/main/kotlin/net/corda/core/transactions/MerkleTransaction.kt
> +            val inputsPmt = if (!filteredLeaves.inputs.isEmpty()) {
extract this repeated subexpression into a value

2017-09-05 10:29 UTC, mikehearn commented on core/src/main/kotlin/net/corda/core/transactions/MerkleTransaction.kt
> +        return if (!filteredLeaves.inputs.isEmpty()) {
ditto

2017-09-05 10:29 UTC, mikehearn commented on core/src/main/kotlin/net/corda/core/transactions/WireTransaction.kt
> +     * Builds the input states sub Merkle tree. This is required so non-validated notaries can see
typo, non-validating

2017-09-05 10:29 UTC, mikehearn commented on core/src/main/kotlin/net/corda/core/transactions/WireTransaction.kt
> +    val inputsMerkleTree: MerkleTree? by lazy { inputStatesMerkleTree() }
Does this need to be public API at all?

2017-09-05 10:29 UTC, mikehearn commented on core/src/main/kotlin/net/corda/core/transactions/WireTransaction.kt
> +        return if (!inputs.isEmpty()) {
if (inputs.isNotEmpty())

2017-09-05 10:29 UTC, mikehearn commented on core/src/main/kotlin/net/corda/core/transactions/WireTransaction.kt
> +        return if (!inputs.isEmpty()) {
ditto

2017-09-05 10:29 UTC, mikehearn commented on core/src/test/kotlin/net/corda/core/crypto/PartialMerkleTreeTest.kt
> +    fun `verify Partial Merkle Tree - less leaves failure`() {
the original grammar was more correct: maybe `insufficient leaves fails` is better still.

2017-09-05 10:29 UTC, mikehearn commented on core/src/test/kotlin/net/corda/core/crypto/PartialMerkleTreeTest.kt
> +    fun `verify all inputs are visible Partial Merkle Tree`() {
visible _in the_ PMT?

2017-09-05 10:29 UTC, mikehearn commented on node/src/main/kotlin/net/corda/node/services/transactions/NonValidatingNotaryFlow.kt
> +                    it.verifyAndAllInputsVisible()
It seems from unit tests that this returns false, not throwing an exception. But here the return value isn't used. Is that really correct? It looks like the feature is buggy but the unit tests aren't catching it, because there's no test that tries to trick the actual non validating notary flow.

Overall I **STRONGLY** dislike methods called verify() that return booleans for this sort of reason. It's always better to throw an exception. Even if you believe verification will fail frequently, the JVM knows how to optimise exceptions-that-aren't-exceptional. Checked exceptions would be even better for this sort of thing, but at least with an exception you know the caller can't forget to handle the error.

2017-09-05 10:29 UTC, mikehearn commented on core/src/main/kotlin/net/corda/core/transactions/MerkleTransaction.kt
> +     */
It both throws an exception _and_ returns a boolean? Which is it? The docs don't say what the return value means or when the exception is thrown.

2017-09-05 10:29 UTC, mikehearn commented on core/src/main/kotlin/net/corda/core/transactions/MerkleTransaction.kt
>       */
It both throws an exception _and_ returns a boolean? Which is it? The docs don't say what the return value means or when the exception is thrown.

2017-09-11 23:04 UTC, kchalkias commented
Thanks for the feedback @mikehearn. Based on our discussion the other day, I will probably merge the logic from this PR into [1481](https://github.com/corda/corda/pull/1481) which is the more generalised version of sub-Merkle trees per component group and not just the inputs. Thus, we could avoid (as you correctly noticed) the "weird" handling of the leftmost leaf.

2017-09-11 23:08 UTC, kchalkias commented on node/src/main/kotlin/net/corda/node/services/transactions/NonValidatingNotaryFlow.kt
> +                    it.verifyAndAllInputsVisible()
You are right, I remember you suggesting something similar when building the Crypto api; this example again highlights the necessity to follow the `throw` approach, especially for critical boolean functions.

2017-09-15 14:42 UTC, mikehearn commented
OK, so shall we close this?

2017-09-15 14:43 UTC, closed without merging