CORDA-696: Create separate transaction types for contract upgrade transactions
corda/corda pull request #1927
Opened 2017-10-23 14:48 UTC by adagys

Removed the ContractUpgrade command and created new restricted ContractUpgrade(Wire/Ledger)Transaction types. @mikehearn I'm still not entirety convinced that this is the right approach :)

Modified UpgradedContract to include a contract constraint for the legacy contract.

Created a new vault update type for contract upgrade related changes.

Note that this PR doesn't address the encumbrances issue properly.

2017-10-26 09:09 UTC, kchalkias commented on core/src/main/kotlin/net/corda/core/transactions/ContractUpgradeTransactions.kt
> +        val privacySalt: PrivacySalt = PrivacySalt()
Should we use privacySalt in the MTree construction? Now, it seems to be a redundant property.

2017-10-26 09:12 UTC, kchalkias commented on core/src/main/kotlin/net/corda/core/transactions/ContractUpgradeTransactions.kt
> +data class ContractUpgradeWireTransaction(
Are we interested in backwards compatibility for the new tx_types?

2017-10-26 09:24 UTC, kchalkias commented on core/src/main/kotlin/net/corda/core/transactions/ContractUpgradeTransactions.kt
> +    private val hiddenComponentHash: SecureHash get() = serializedHash(outputs + legacyContractAttachment + upgradedContractAttachment)
It would be better and more secure to apply either an HMAC or double hashing (as we do in `WireTransaction`) to protect against length extension attacks. FYI, SHA-256 (our default hash algorithm) is vulnerable against the aforementioned attack.

2017-10-26 14:26 UTC, adagys commented on core/src/main/kotlin/net/corda/core/transactions/ContractUpgradeTransactions.kt
> +        val privacySalt: PrivacySalt = PrivacySalt()
Good catch! forgot to actually include it

2017-10-26 14:27 UTC, adagys commented on core/src/main/kotlin/net/corda/core/transactions/ContractUpgradeTransactions.kt
> +    private val hiddenComponentHash: SecureHash get() = serializedHash(outputs + legacyContractAttachment + upgradedContractAttachment)
Ok, will change to double hashing

2017-10-26 14:28 UTC, adagys commented on core/src/main/kotlin/net/corda/core/transactions/ContractUpgradeTransactions.kt
> +data class ContractUpgradeWireTransaction(
I suspect we are

2017-10-26 14:32 UTC, kchalkias commented on core/src/main/kotlin/net/corda/core/transactions/ContractUpgradeTransactions.kt
> +data class ContractUpgradeWireTransaction(
Nice, we should define what is considered backwards compatibility. If a new property is added, do we care if the old client can still construct the MTree?

2017-10-30 16:32 UTC, rnicoll reviewed
I'm unclear why this would be the wrong approach, but a separate transaction type makes sense for notary change transactions? It feels to me that the same structure applies to both.

2017-10-30 16:32 UTC, rnicoll commented on core/src/test/kotlin/net/corda/core/node/VaultUpdateTests.kt
> +    private val noUpdate = Vault.Update(emptySet(), emptySet())
Not sure why you're adding a new `noUpdate` value?

2017-10-30 16:32 UTC, rnicoll commented on core/src/main/kotlin/net/corda/core/internal/ResolveTransactionsFlow.kt
> +        val attachments = downloads.flatMap {
Might be a little cleaner as `val attachments = downloads.coreTransaction.flatMap { coreTransaction ->`

2017-10-30 16:54 UTC, mikehearn requested changes

2017-10-30 16:54 UTC, mikehearn commented on core/src/main/kotlin/net/corda/core/transactions/ContractUpgradeTransactions.kt
> +    private val legacyContractName: ContractClassName = inputs.first().state.contract
OK, so the inputs must have a consistent constraint - that should be in the docs.

2017-10-30 16:54 UTC, mikehearn commented on core/src/main/kotlin/net/corda/core/transactions/ContractUpgradeTransactions.kt
> +        val upgradedContract = when (upgradedContractTry) {
Why is the logic that loads the contract outside the verify function? That isn't obvious and if really required should have a comment explaining it. Otherwise I'd lose the Try and use a plain old fashioned try/catch.

2017-10-30 16:54 UTC, mikehearn commented on core/src/main/kotlin/net/corda/core/transactions/ContractUpgradeTransactions.kt
> +        inputs.forEachIndexed { index, stateAndRef ->
This is probably better written as `for ((index, stateAndRef) in inputs.indexed()) { .. }` - intellij can auto-convert between forms.

2017-10-30 16:54 UTC, mikehearn commented on core/src/main/kotlin/net/corda/core/transactions/NotaryChangeTransactions.kt
> +        get() = throw IllegalStateException("NotaryChangeWireTransaction does not contain output states, " +
UnsupportedOperationException

2017-10-30 16:54 UTC, mikehearn commented on core/src/main/kotlin/net/corda/core/transactions/SignedTransaction.kt
> -    val notaryChangeTx: NotaryChangeWireTransaction get() = transaction as NotaryChangeWireTransaction
This isn't backwards compatible.

2017-10-30 16:54 UTC, mikehearn commented on node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt
> +            if (batch.isNotEmpty() && tx::class.java != batch.last()::class.java) {
not `.javaClass`?

2017-10-30 16:54 UTC, mikehearn commented on node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/Kryo.kt
> +        kryo.writeClassAndObject(output, obj.inputs)
Does this pass the AMQP CI gate?

2017-10-30 16:54 UTC, mikehearn commented on node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt
> +    /** Groups adjacent transactions into batches to generate separate net updates per transaction type. */
Does this new implementation emit things in the same order as before, or did it change?

2017-10-30 16:56 UTC, mikehearn commented
I think Andrius didn't like the separate tx approach last time either :) It's me who's pushing for that style.

I quite like how the upgrade code is looking now.  The main areas I'm unsure about and are triggering comments are:

* Compatibility
* The interaction with constraints
* To what extent we should be pushing this mechanism on users vs just using relaxed code signature constraints

It's good that we have a protocol with this level of control, but I suspect in practice - at least in the early days - nobody will be using really immutable contracts. They'll be happy to let third parties patch the code on the fly. But we'll see.

2017-10-30 16:58 UTC, rnicoll commented
After discussion with @adagys I think the upgrade transaction shouldn't include outputs (as per notary change); this means resolving a transaction chain includes rebuilding the upgraded states. However as verifying the transaction chain would require rebuilding them anyway, this doesn't seem unduly expensive.

2017-10-30 17:02 UTC, mikehearn commented
Good point.

2017-10-30 17:04 UTC, adagys commented on core/src/test/kotlin/net/corda/core/node/VaultUpdateTests.kt
> +    private val noUpdate = Vault.Update(emptySet(), emptySet())
I removed the old one from the public API – a "no update" update is an implementation detail and shouldn't really be something that the vault emits

2017-10-30 17:08 UTC, adagys commented on core/src/main/kotlin/net/corda/core/contracts/Structures.kt
> +    val legacyContractConstraint: AttachmentConstraint
Hmm, true, but this more of a security fix really

2017-10-30 17:13 UTC, adagys commented on core/src/main/kotlin/net/corda/core/node/services/TransactionVerifierService.kt
> +    fun verify(transaction: FullTransaction): CordaFuture<*>
I thought we don't yet provide ABI stability?

2017-10-30 17:15 UTC, adagys commented on core/src/main/kotlin/net/corda/core/transactions/ContractUpgradeTransactions.kt
> +        val upgradedContract = when (upgradedContractTry) {
As in `LedgerTransaction` the whole `verify()` method is/will be run with blacklisting enabled, so we need to do the contract loading beforehand. Will add a comment

2017-10-30 17:18 UTC, adagys commented on core/src/main/kotlin/net/corda/core/transactions/SignedTransaction.kt
> -    val notaryChangeTx: NotaryChangeWireTransaction get() = transaction as NotaryChangeWireTransaction
In practice this is (or should be) internal API, I don't think we should maintain it forever just for the sake of it.

2017-10-30 17:20 UTC, adagys commented on node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt
> +    /** Groups adjacent transactions into batches to generate separate net updates per transaction type. */
It does, the old approach didn't scale well to more than two types so I had to rewrite it.

2017-10-30 17:21 UTC, adagys commented on core/src/main/kotlin/net/corda/core/transactions/NotaryChangeTransactions.kt
> +        get() = throw IllegalStateException("NotaryChangeWireTransaction does not contain output states, " +
I'm especially uncomfortable about this part

2017-10-30 17:23 UTC, adagys commented on core/src/main/kotlin/net/corda/core/internal/ContractUpgradeUtils.kt
> +            TransactionState(newState, upgradedContractClass.name, it.notary, it.encumbrance, upgradedContractConstraint)
Not exactly sure what you mean (?)

2017-10-30 17:25 UTC, adagys commented on core/src/main/kotlin/net/corda/core/flows/NotaryFlow.kt
> +                    session.sendAndReceiveWithRetry(filteredTransaction)
That's a good question, I also suspect it won't be

2017-10-30 17:26 UTC, adagys commented on node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/Kryo.kt
> +        kryo.writeClassAndObject(output, obj.inputs)
Probably not :(

2017-10-31 10:38 UTC, adagys commented on core/src/main/kotlin/net/corda/core/internal/ResolveTransactionsFlow.kt
> +    // TODO: This could be done in parallel with other fetches for extra speed.
I pulled it out since it made it seem like it applied to the specific line below

2017-10-31 10:42 UTC, adagys commented on core/src/main/kotlin/net/corda/core/internal/ResolveTransactionsFlow.kt
> +        val attachments = downloads.flatMap {
do you mean something like `downloads.map { it.coreTransaction }.flatMap { coreTransaction -> .. }?

2017-11-10 14:32 UTC, andr3ej commented
having discussed with @adagys i've added a commit that fixes the circular dep between NodeVaultService and ServiceHub

2017-11-13 14:34 UTC, rnicoll commented on core/src/main/kotlin/net/corda/core/internal/ResolveTransactionsFlow.kt
> +        val attachments = downloads.flatMap {
I misread the code, but yes lets go with your revised version :)

2017-11-13 14:42 UTC, rnicoll commented on core/src/main/kotlin/net/corda/core/contracts/Structures.kt
> +    val legacyContractConstraint: AttachmentConstraint
I'm inclined that we force them to add the new property; we can't support the old interface in actual transactions, so keeping it for recompiling seems less friendly than saying "Either add this property or remove the interface".

2017-11-13 15:26 UTC, rnicoll commented on core/src/main/kotlin/net/corda/core/transactions/SignedTransaction.kt
> -    val notaryChangeTx: NotaryChangeWireTransaction get() = transaction as NotaryChangeWireTransaction
I've re-added with an `@Deprecated` annotation in the next version, so in the highly unlikely event someone has compiled against it, they'll have some warning it's going to disappear.

2017-11-20 14:39 UTC, rnicoll commented
@mikehearn Okay, I think this is ready for re-review. Aware we have API functions removed, I can put them back with stubs/exception throwing versions, but realistically I think everything removed shouldn't have been public and is of limited/no value to CorDapps :-/

2017-11-22 16:46 UTC, mikehearn commented
OK, this is on my review queue again, sorry for being slow ...

2017-11-24 17:59 UTC, rnicoll commented
Quick reminder, Mike

2017-11-27 16:38 UTC, mikehearn commented
I had not forgotten. I do actually have a todo list, this is currently in 7th place (about the middle).

2017-11-29 14:27 UTC, Clintonio requested changes
Not much to say - the changes to the areas I've worked on seem fine.

2018-01-29 17:33 UTC, mikehearn requested changes

2018-01-29 17:33 UTC, mikehearn commented on core/src/main/kotlin/net/corda/core/transactions/ContractUpgradeTransactions.kt
> +     * [ContractUpgradeLedgerTransaction] and applying the notary modification to inputs.
"applying the notary modification" seems like a copy/paste error.

2018-01-29 17:33 UTC, mikehearn commented on core/src/main/kotlin/net/corda/core/transactions/ContractUpgradeTransactions.kt
> +    fun resolve(stateLoader: StateLoader, attachments: AttachmentStorage, sigs: List<TransactionSignature>): ContractUpgradeLedgerTransaction {
Does this need a kdoc?

2018-01-29 17:33 UTC, mikehearn commented on core/src/main/kotlin/net/corda/core/transactions/ContractUpgradeTransactions.kt
> +        val legacyContractClassName = resolvedInputs.first().state.contract
Do we need to check consistency here?

2018-01-29 17:33 UTC, mikehearn commented on core/src/main/kotlin/net/corda/core/transactions/ContractUpgradeTransactions.kt
> +        this::class.java.classLoader.loadClass(upgradedContractAttachment.contract).
This needs a TODO to load it from the CorDapp classloader (and eventually the sandboxing classloader).

And we should really centralise this code as it's so critical.... can we refactor the existing codepath that creates the contract object so this code can use it?

Also this is lazy, but then there's a parameter below that eagerly resolves it - seems the lazyness is pointless.

2018-01-29 17:33 UTC, mikehearn commented on core/src/main/kotlin/net/corda/core/transactions/ContractUpgradeTransactions.kt
> +            "Legacy contract constrain does not satisfy the constraint of the input states"
typo: constrain->constraint

2018-01-29 17:33 UTC, mikehearn commented on core/src/main/kotlin/net/corda/core/transactions/NotaryChangeTransactions.kt
> +    @Deprecated("Exists purely for binary compatibility, the more generic version based on StateLoader should be used instead")
Yep. Could even use the kotlin `@ReplaceWith` annotation in this case as it's so trivial.

2018-01-29 17:33 UTC, mikehearn commented on core/src/main/kotlin/net/corda/core/transactions/SignedTransaction.kt
> +    /** TODO */
???

2018-01-29 17:33 UTC, mikehearn commented on core/src/main/kotlin/net/corda/core/transactions/SignedTransaction.kt
>       * TODO: Verify contract constraints here as well as in LedgerTransaction to ensure that anything being deserialised
I wonder if this TODO is still relevant.

2018-01-29 17:33 UTC, mikehearn commented on core/src/main/kotlin/net/corda/core/transactions/SignedTransaction.kt
> +    fun resolveBaseTransaction(stateLoader: StateLoader, attachments: AttachmentStorage): BaseTransaction {
I guess you could use `@JvmOverloads` with a default argument. At any rate, please copy the Kdoc so all public members are documented.

2018-01-29 17:33 UTC, mikehearn commented on core/src/main/kotlin/net/corda/core/transactions/SignedTransaction.kt
> +    fun resolveContractUpgradeTransaction(stateLoader: StateLoader, attachments: AttachmentStorage): ContractUpgradeLedgerTransaction {
kdoc

2018-01-29 17:33 UTC, mikehearn commented on node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt
> +    /** Groups adjacent transactions into batches to generate separate net updates per transaction type. */
Is there a quick way to get the old ordering, accepting the bad scaling, with the new code still present but `if (false)`d out so we can gate it behind targetVersion once that's implemented? Then apps can opt in to the new faster code.

2018-01-30 15:26 UTC, adagys commented on core/src/main/kotlin/net/corda/core/transactions/ContractUpgradeTransactions.kt
> +        val legacyContractClassName = resolvedInputs.first().state.contract
The check is done later in the ContractUpgradeLedgerTransaction. I think it's easier to keep all checks in one place

2018-01-30 16:01 UTC, adagys commented on node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt
> +    /** Groups adjacent transactions into batches to generate separate net updates per transaction type. */
Sorry I meant it doesn't scale in terms of code structure 😄 The ordering is still the same

2018-02-01 11:39 UTC, adagys commented
@mikehearn this is ready for another look. The API checker still reports 2 issues, but I don't see a way around them

2018-02-08 14:20 UTC, mikehearn commented
It's reporting one issue, right?

[11:36:27][Step 5/10] -@net.corda.core.DoNotImplement public interface net.corda.core.node.services.TransactionStorage extends net.corda.core.node.StateLoader
[11:36:27][Step 5/10] +@net.corda.core.DoNotImplement public interface net.corda.core.node.services.TransactionStorage

So TransactionStorage no longer extends StateLoader. How comes?

2018-02-08 14:21 UTC, mikehearn commented on core/src/main/kotlin/net/corda/core/node/services/TransactionStorage.kt
> -    @Throws(TransactionResolutionException::class)
Why does this need to be removed?

2018-02-08 15:02 UTC, adagys commented
Well `TransactionStorage` has been recently refactored to extend `StateLoader`, which made sense at the time, but with contract upgrade transactions it now needs access to `AttachmentStorage` and later potentially `CordappProvider`, which means we have to wire it up in all constructors of implementations (there are multiple), and that gets messy. Maybe @andr3ej has any suggestions?

2018-02-08 15:03 UTC, adagys commented
And the other issue is 
`+  @org.jetbrains.annotations.NotNull public abstract net.corda.core.contracts.AttachmentConstraint getLegacyContractConstraint()`

2018-02-09 17:10 UTC, gendal commented
Any docs?

2018-02-09 17:21 UTC, gendal commented
Question: if this did not go in to 3.0, what would be the consequence? ie would subsequently implementing this break wire/api/abi compat in some way?

2018-02-09 17:27 UTC, adagys commented
It would break backwards compatibility if someone were to start using the contract upgrade mechanism – which doesn't fully work at the moment. We _may_ be able to maintain compatibility, but that would be extremely painful.

2018-02-12 12:04 UTC, andr3ej commented
StateLoader stuff looks fine

2018-02-12 15:00 UTC, mikehearn requested changes
Looking really close now. Have you tried using it with a sample app, like an end user would? Like running a network with demobench and seeing the upgrade go through.

2018-02-12 15:00 UTC, mikehearn commented on core/src/main/kotlin/net/corda/core/contracts/Structures.kt
> +    val legacyContractConstraint: AttachmentConstraint
Hm, so, let's think about this a bit. That would be an API break, albeit an understandable one given the half baked nature of what shipped previously here. Can we provide a non-stupid default here, that at least matches the prior behaviour (even if slightly broken)? I'm thinking specifically of converting this interface to Java and then making this getter have a default implementation that returns AlwaysAcceptAttachmentConstraint. WDYT?

2018-02-12 15:00 UTC, mikehearn commented on core/src/main/kotlin/net/corda/core/internal/ContractUpgradeUtils.kt
> +        val legacyContractAttachmentId = services.cordappProvider.getContractAttachmentID(stateAndRef.state.contract)!!
Are we guaranteed to never get a null here? If not can we throw a better exception than NPE?

2018-02-12 15:00 UTC, mikehearn commented on core/src/main/kotlin/net/corda/core/node/services/TransactionStorage.kt
> -    @Throws(TransactionResolutionException::class)
Ping? Isn't this an API break from 1.0?

2018-02-12 15:00 UTC, mikehearn commented on core/src/test/kotlin/net/corda/core/flows/ContractUpgradeFlowTest.kt
> +        override val legacyContractConstraint = object : AttachmentConstraint {
This is the same as `get() = AlwaysAcceptAttachmentConstraint`, but if we make that the default impl, this can go away.

2018-02-12 16:34 UTC, mikehearn commented on core/src/main/kotlin/net/corda/core/node/services/TransactionStorage.kt
> -    @Throws(TransactionResolutionException::class)
OK, had a chat with Andrius, it's not because this API change is a revert of something that never shipped in 1.0/2.0

2018-02-12 16:38 UTC, mikehearn commented on core/src/main/kotlin/net/corda/core/contracts/Structures.kt
> +    val legacyContractConstraint: AttachmentConstraint
OK, had a catchup with Andrius about this.

Here's what we agreed -

1. Move this interface into a Java file so we can use Java 8 default interface methods.
2. Make getLegacyContract() automatic: it should just use reflection to figure out the name of the current class, which is a good default guess
3. Make getLegacyContractConstraint() return WhitelistedByNetworkParametersAttachmentConstraint, which is being added in PR #2474 by Tudor. This constraint is the only one we can provide without any context that isn't a security hole, as AcceptAllAttachmentConstraint would be, and is a non-terrible default that lets us dig developers out of a hole if they make one for themselves. In future versions of the platform we can use targetVersion of the calling app to change the default to a code signing constraint, initialised to the same signer as the calling app. So in all cases there's a sane set of defaults for these methods.

That requires Andrius to wait for Tudor to go into master and then 3.0, and then Andrius follows close behind, but that's OK because Andrius still needs to do some end-user testing and documentation writing. So there's a bit of time left on this PR before it can go in anyway.

2018-02-16 14:14 UTC, adagys commented
One other assumption the new contract upgrade transactions make is that the contract attachment will also contain the state code. Is that safe to assume?

2018-02-16 16:45 UTC, adagys commented
@tudor-malene see my above comment

2018-02-16 16:51 UTC, adagys commented on core/src/main/kotlin/net/corda/core/contracts/Structures.kt
> +    val legacyContractConstraint: AttachmentConstraint
So I tried moving the interface to Java, but that now breaks existing Kotlin implementations that override the `legacyContract` with a property, you need to change
`override val legacyContract = ...` into `override fun getLegacyContract(): String { ... }`

2018-02-16 16:53 UTC, adagys commented on core/src/main/kotlin/net/corda/core/contracts/Structures.kt
> +    val legacyContractConstraint: AttachmentConstraint
To your second point, `getLegacyContract()` should point to the class it's upgrading, and not the current one (which we assume will have a different name), so making it automatic is tricky

2018-02-16 16:59 UTC, tudor-malene commented
Q: One other assumption the new contract upgrade transactions make is that the contract attachment will also contain the state code. Is that safe to assume?

A: For 3.0, definitely, CorDapps need to be fat jars, otherwise the whitelist/hash based security we have in place is useless

2018-02-16 17:13 UTC, adagys commented
Right, but do we need to add support for potential other attachments containing states only? In the future

2018-02-16 17:33 UTC, tudor-malene commented
I think @mikehearn said that we'll keep the fatjars until we upgrade to java 9, which has built-in support for dependencies.

2018-02-21 09:31 UTC, adagys commented
Continuing on #2589

2018-02-21 09:31 UTC, closed without merging