Fix VaultUpdate filtering in trackBy
corda/corda pull request #2225
Opened 2017-12-11 11:29 UTC by exFalso

This PR fixes the update filtering.

Previously when a user tracked UNCONSUMED states, updates with nothing produced were filtered out, making a local view of UNCONSUMED states inconsistent as updates that only consumed were swallowed.

Imo the reason for this inconsistency stems from using `VaultUpdate`s for two separate purposes:
1. As a datastructure describing what states were consumed and produced
2. As a datastructure describing *the diff between two vault query results*

I think 2 should be a different datastructure, e.g.
```kotlin
data class QueryResultDiff {
  val rowsAdded
  val rowsRemoved
}
```

The above would clarify what's going on. When the user `track`s, the stream should contain `QueryResultDiff`s rather than `VaultUpdate`s. The property of consumedness/producedness is orthogonal to a row being removed/added to a query result.
For example if the user queries CONSUMED states the diffs would always have `rowsRemoved` empty, as the set of CONSUMED states always grows.
If the user queries UNCONSUMED states then both `rowsAdded` and `rowsRemoved` may be non-empty, as the set of UNCONSUMED states may both grow and shrink.

Unfortunately the above would imply an API break, so in this PR I used `VaultUpdate`s as these diffs.
In the case of UNCONSUMED/ALL queries the updates are modified to only contain states of the queried type, but other than that the update stays the same.
In the case of CONSUMED queries the updates are additionally modified by clearing the `produced` set.

I left the old `containsType` function as is because it's public API (even though it isn't used by the filtering anymore).

2017-12-11 11:47 UTC, josecoll commented
Please make this new behaviour - as described above in the PR description - very clear in the Vault Query Corda documentation.

2017-12-11 11:57 UTC, josecoll commented
I would also recommend adding JUnit tests to clearly cover the scenarios this PR is attempting to address. 
eg. 
Consider the following scenario:
```Alice issues 2 dollars
Alice moves 1 dollar to Bob
Bob moves 1 dollar to Alice
```
The `CordaRPCOps.vaultTrackBy()` API returns the following updates for Alice for the above:
```0 consumed, 2 produced
1 consumed, 1 produced
0 consumed, 1 produced
```


Makes sense, so far so good. Now consider the following scenario:
```Alice issues 1(!) dollar
Alice moves 1 dollar to Bob
Bob moves 1 dollar to Alice
```
`CordaRPCOps.vaultTrackBy()` now returns something unexpected for Alice (well, imo):
```0 consumed, 1 produced
0 consumed, 1 produced
```
Alice now thinks she has 2 dollars, even though she only has 1! :open_mouth: What's the cause of this?

2017-12-12 18:01 UTC, rick-r3 commented
@josecoll the state types will default to `UNCONSUMED` in the the `trackBy` and thus you will see all updates (consumed and produced).  Produced states are only filtered out if asking for only `CONSUMED`.  I'm correct there @exFalso ?

Thus your example is

2017-12-12 18:20 UTC, josecoll commented
I was just suggesting we update the documentation to clearly highlight the behaviour as illustrated by @exFalso original examples.

2017-12-13 16:30 UTC, mikehearn commented
This looks like the kind of behaviour change that targetVersion is useful for. We can keep the old behaviour for old apps and change it for newer apps. At least, if we know what client version the invoker of the API is .... which we should have for CorDapps but we may not have for RPC clients? We can add targetVersion to RPC in a backwards compatible way though.

2017-12-14 15:11 UTC, exFalso commented
Currently writing tests for this, I noticed that the original code has a proper bug in it as well. It doesn't filter out states from the update that aren't of the queried type, *but it casts those all the same*. So if an update happens to include Cash and something else, that something else will be case to Cash

2017-12-14 15:53 UTC, exFalso commented
@colljos added tests and a paragraph on the behaviour.
@rick-r3 yes that's correct

2017-12-14 16:51 UTC, josecoll requested changes

2017-12-14 16:51 UTC, josecoll commented on docs/source/api-vault-query.rst
> +3. In case ``TrackBy`` is used the filters are applied to the initial query and subsequent updates will reflect the
In the case where ``TrackBy`` is used, ``QueryCriteria`` filters are only applied to the initial snapshot query. Subsequent updates reflect all changes since that initial filtered query.

2017-12-14 16:51 UTC, josecoll commented on docs/source/api-vault-query.rst
> +   diffs between such filtered queries. Note that this means that if a ``trackBy`` queries UNCONSUMED states the
For example, if a ...

2017-12-14 16:51 UTC, josecoll commented on docs/source/api-vault-query.rst
> +   states related to the change in case a previously UNCONSUMED state got consumed.
It's non obvious to the reader why you would want both.
Illustrating your example with the 2 spending scenarios would really clarify the reason for this behaviour.

2017-12-14 16:56 UTC, josecoll commented on node/src/integration-test/kotlin/net/corda/node/services/VaultServiceTest.kt
> +class VaultServiceTest {
feels like these tests should be in either `VaultQueryTests` or `VaultWithCashTests`.

2017-12-14 17:01 UTC, josecoll commented
@exFalso can you point our where the bug you mention above is fixed.

Afaik there has always been an explicit check for the correct Class Type:
```
        /** Checks whether the update contains a state of the specified type and state status */
        fun <T : ContractState> containsType(clazz: Class<T>, status: StateStatus) =
                when (status) {
                    StateStatus.UNCONSUMED -> produced.any { clazz.isAssignableFrom(it.state.data.javaClass) }
                    StateStatus.CONSUMED -> consumed.any { clazz.isAssignableFrom(it.state.data.javaClass) }
                    else -> consumed.any { clazz.isAssignableFrom(it.state.data.javaClass) }

```

2017-12-15 11:24 UTC, exFalso commented
@josecoll So in the old code that function is a simple check, it doesn't filter the update itself.

For example if I have a VaultUpdate that contains `consumed = [Cash, Obligation], produced = [Cash]` then the old filtering function returns true when `Cash` is queried, but doesn't filter out the `Obligation` state, the `VaultUpdate<ContractState>` is simply cast to `VaultUpdate<Cash>`. This doesn't throw on the server because of erasure, it will only throw on the client when they will try to use the state as Cash.

In the new code the filtering function actually does filtering (`filterTo`), it's not just a predicate

2017-12-15 11:30 UTC, exFalso commented on node/src/integration-test/kotlin/net/corda/node/services/VaultServiceTest.kt
> +class VaultServiceTest {
Those are unit tests, this is an integ test.. perhaps better naming is due?

2017-12-15 11:42 UTC, rick-r3 commented on docs/source/api-vault-query.rst
> +3. In case ``TrackBy`` is used the filters are applied to the initial query and subsequent updates will reflect the
Yeah, perhaps worth re-surfacing the fact that the only filters currently applied to the updates are by contract state type and status.  We may improve the filtering later for those with an updated "target version" for their app.

2017-12-15 11:42 UTC, rick-r3 reviewed
A couple of changes to the docs is worthwhile.

2017-12-15 13:20 UTC, exFalso commented
@josecoll updated docs, back to you

2017-12-21 12:04 UTC, josecoll requested changes
This PR still needs a changelog entry to describe the behavioural change.

2017-12-21 12:05 UTC, josecoll commented on node-api/src/main/kotlin/net/corda/nodeapi/ArtemisTcpTransport.kt
> +                    TransportConstants.REMOTING_THREADS_PROPNAME to (if (nodeSerializationEnv != null) -1 else 1)
Why is this change in this PR?

2018-01-25 14:55 UTC, mikehearn commented
How much work to rebase this and get it merged? Would be good to fix it!

2018-08-20 17:23 UTC, closed without merging