CORDA-353 Large Attachments
corda/corda pull request #2239
Opened 2017-12-13 11:48 UTC by cburlinchon

2017-12-14 10:31 UTC, mikehearn commented
This PR has no reviewers assigned. Please assign some or close it until it's ready.

2017-12-15 10:43 UTC, exFalso requested changes
Couple of things

2017-12-15 10:43 UTC, exFalso commented on node-api/src/main/kotlin/net/corda/nodeapi/RPCApi.kt
> +                            serialisedArguments = if (message.isLargeMessage) kotlin.ByteArray(0) else message.getBodyAsByteArray(),
instead of doing this i'd suggest defining something like this:
```kotlin
sealed class RpcRequestPayload {
  data class Regular(val serialisedArguments: ByteArray) : RpcRequestPayload()
  data class Streamed(val stream: InputStream) : RpcRequestPayload()
}
```
replace both `serialisedArguments` and `bodyInputStream` with one of the above and use `when` to decide what to do. This way there is no ambiguity and no need for the empty bytarray

2017-12-15 10:43 UTC, exFalso commented on node-api/src/main/kotlin/net/corda/nodeapi/RPCApi.kt
> +                            val tempFile = Files.createTempFile("pre", null).toFile()
I'm wary of this leaking files. `deleteOnExit` may or may not be called depending on how the jvm terminates and whether the file is being streamed to at the time of shutdown. Furthermore if we delay the deletion until jvm shutdown the client will just keep creating new files while it's running
Two alternatives:
- I wonder whether we can pipe the stream to the user instead? iirc this requires another modification in artemis as the stream is aborted when the handler finishes. Hmm, perhaps not now
- Stream to a file but create a wrapper around the returned `FileInputStream` so that the file is cleaned up once the stream finishes or the wrapper is finalised.

2017-12-15 10:43 UTC, exFalso commented on node/src/integration-test/kotlin/net/corda/node/services/persistence/NodeAttachmentServiceTest.kt
> +        val file = File.createTempFile("NodeAttachmentServiceTest", null)
use `@Rule` and `TemporaryFolder` instead

2017-12-15 10:43 UTC, exFalso commented on node/src/integration-test/kotlin/net/corda/node/services/persistence/NodeAttachmentServiceTest.kt
> +                    it.proxy.uploadAttachment(FileInputStream(largeAttachment()))
Actually scratch that, use `RepeatingBytesInputStream` instead of a file. Then do a roundtrip stream through the node and check whether the returned bytes are the same.

Please also add a test that does this several times in parallel

2017-12-15 10:43 UTC, exFalso commented on node/src/main/kotlin/net/corda/node/services/messaging/RPCServer.kt
> +                    val tempFile = Files.createTempFile("pre", null).toFile()
Same thing applies as before, except in this case we *can* hand over the stream to the RPC handler without modifying artemis as the rpc is run within the message handler. So we don't need any intermediate fs buffering

2017-12-15 10:43 UTC, exFalso commented on node/src/main/kotlin/net/corda/node/services/persistence/NodeAttachmentService.kt
> +            AttachmentImpl(contentHash, { bytes }, checkAttachmentsOnLoad)
This reads everything into memory again... is this correct? Can verify by doing the roundtrip test

2017-12-15 10:43 UTC, exFalso commented on node/src/main/kotlin/net/corda/node/services/persistence/NodeAttachmentService.kt
> +            rereadAttachment.contentHash = contentHash.toString()
This is racy.. is it fine if we end up with duplicates?

2017-12-15 12:08 UTC, jamesbr3 commented on node-api/src/main/kotlin/net/corda/nodeapi/RPCApi.kt
> +                            val tempFile = Files.createTempFile("pre", null).toFile()
Couple of things worth mentioning about temp-file creation. The general recommendation is to:
* Never create temp files in a shared directory (i.e. somewhere that other users on the system may have access to)
* Aim to create & open temp file as an atomic operation
* Always use 'secure' random filename - i.e. that isn't guessable by an attacker. I *think* Files.createTempFile will do this automatically in Java (6+???), but not sure otoh

The aim is to avoid TOCTOU (time-of-creation, time-of-use) attacks - i.e. a race-condition where there is a small time window between file creation, and the point where you open the file for what you hope is exclusive write-access.

I'd advise double-checking where this temp-file is going to be created. And double-check the permissions on the directory to make sure it's only the corda-node user that has access.

Is Files.createTempFile.toFile() atomic? Is File.createTempFile preferable because it (I assume) keeps the file open as it returns thje File object back to you?

2018-03-02 16:11 UTC, closed without merging