CORDA-941 contract verification - WIP
corda/corda pull request #2474
Opened 2018-02-06 17:46 UTC by tudor-malene

WIP!

https://r3-cev.atlassian.net/browse/CORDA-941

2018-02-08 16:08 UTC, mikehearn requested changes

2018-02-08 16:08 UTC, mikehearn commented on testing/test-utils/src/main/kotlin/net/corda/testing/services/MockAttachmentStorage.kt
> +            files[id] = Pair(ContractAttachment(object : AbstractAttachment({ bytes }) {
This would be a bit clearer if broken up into named sub-expressions.

2018-02-08 16:44 UTC, tudor-malene commented on core/src/main/kotlin/net/corda/core/node/services/AttachmentStorage.kt
> +    fun importContractAttachment(contractClassNames: List<ContractClassName>, jar: InputStream): AttachmentId
I kept this mostly for performance reasons.
The CorDappLoader scanned the jar already and knows what contracts are in it, when it imports it. So, if using the normal import function, we'd have to rescan, which would add up for all the tests

2018-02-08 16:45 UTC, tudor-malene commented on core/src/main/kotlin/net/corda/core/transactions/LedgerTransaction.kt
> -            // Ordering of attachments matters - if two attachments contain the same named contract then the second
Aren't we enforcing a no-overlap rule on classloader building? 
So if 2 attachment have the same contract, it would fail when building the classloader

2018-02-08 17:06 UTC, tudor-malene commented on node-api/src/main/kotlin/net/corda/nodeapi/internal/network/NetworkBootstrapper.kt
> +            val arg = args.singleOrNull()
I probably reformatted, and didn't realise that something else was changed.

2018-02-08 18:07 UTC, tudor-malene commented on core/src/test/kotlin/net/corda/core/crypto/PartialMerkleTreeTest.kt
> +        testLedger = MockServices(listOf("net.corda.finance.contracts.asset"), rigorousMock<IdentityServiceInternal>().also {
Cool, I didn't know about that ``getCallerPackage`` method.

It's necessary because we use the contracts a bit earlier now. When the transaction is built.

2018-02-08 18:09 UTC, tudor-malene commented on core/src/main/kotlin/net/corda/core/utilities/whitelistAllContractsForTest.kt
> + * This sequence can be used for test/demos
Oops, I forgot to clean up this bit.
Unfortunately it can't live in a test module because it has to be used in the core.

2018-02-08 20:02 UTC, tudor-malene commented on core/src/main/kotlin/net/corda/core/contracts/AttachmentConstraint.kt
> +data class WhitelistedByZoneAttachmentConstraint(val whitelistedContractImplementations: Set<SecureHash>) : AttachmentConstraint {
You're right, 
I rushed this, and didn't think it through properly.
Capturing the whitelist snapshot is clearly pointless.

Actually what we want this Constraint to do, is answer this question:

*"Is the classloader I'm using to verify the current transaction valid?
More precisely: For each transaction state, is the hash of the Jar file which provides the Contract implementation (and was used to form the classloader) whitelisted in the network parameters? "*

For 3.0, if we assume that all states are created with ``WhitelistedByZoneAttachmentConstraint``, and any contract and state changes are backward compatible, then we can keep using the existing CordappClassloader for the time being, and each time verify that the installed cordapps are whitelisted.

2018-02-09 19:56 UTC, tudor-malene commented
Back to you @mikehearn .

I changed the approach so that it can be used with the current classloader.
1) I added a global flag: useWhitelistedByZoneAttachmentConstraint
2) On startup, if the flag is true, each deployed cordapp is checked against the whitelist ( and the node is failed if it’s invalid. Is this ok?)
3) if the flag is true, when building transactions, by default the ``WhitelistedByZoneAttachmentConstraint`` is used, instead of the ``HashAttachmentConstraint``
4) when creating the wire transaction, the attachment hashes of the current relevant cordapps are added to the Transaction.attachments ( as they are no longer in the HashAttachmentConstraint)
5) when verifying a transaction, the transaction attachment hashes are checked agains the current network whitelist 
6) based on the fact that we agreed that contracts are backwards compatible, the current installed cordapp should be able to verify any states coming from older transactions

Outstanding work: 
- add support to load the whitelist in the NetworkBootstrap 
- change the cordform gradle plugin to use the changed NetworkBootstrap
- document.

2018-02-12 17:21 UTC, mikehearn requested changes
Yep this is looking much better.

2018-02-12 17:21 UTC, mikehearn commented on core/src/main/kotlin/net/corda/core/node/services/AttachmentStorage.kt
> +    fun importContractAttachment(contractClassNames: List<ContractClassName>, jar: InputStream): AttachmentId
That's fair enough but I'd rather not complicate the API and open the possibility of new user mistakes, just to micro-optimise the unit test speed. We can add a backdoor later for testing purposes, that's internal API.

2018-02-12 17:21 UTC, mikehearn commented on core/src/main/kotlin/net/corda/core/transactions/LedgerTransaction.kt
> +     * In case the transaction was created on this node then the attachments will contain the hash of the current cordapp jars
Full stop at end of this sentence.

2018-02-12 17:21 UTC, mikehearn commented on core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
> +        fun getContractAttachmentId(state: TransactionState<ContractState>) = services.cordappProvider.getContractAttachmentID(state.contract)
This function could be inlined, right? Seems odd to name it.

2018-02-12 17:21 UTC, mikehearn commented on docs/source/example-code/src/test/java/net/corda/docs/java/tutorial/testdsl/CommercialPaperTest.java
> +    private final MockServices ledgerServices = new MockServices(Arrays.asList("net.corda.finance.contracts"), MEGA_CORP);
Why is this change needed? Looks like maybe a merge conflict? The default c'tor is supposed to auto discover the package name.

2018-02-12 17:21 UTC, mikehearn commented on docs/source/example-code/src/test/kotlin/net/corda/docs/tutorial/testdsl/TutorialTestDSL.kt
> +    private val ledgerServices = MockServices(listOf("net.corda.finance.contracts"), rigorousMock<IdentityServiceInternal>().also {
Ditto  - seems unrelated to the PR

2018-02-12 17:21 UTC, mikehearn commented on finance/src/test/java/net/corda/finance/contracts/asset/CashTestsJava.java
> +        transaction(new MockServices(asList("net.corda.finance.contracts.asset"), identityService, MEGA_CORP.getName()), DUMMY_NOTARY, tx -> {
ditto: why have these all changed and is the auto-discovery sufficient?

2018-02-12 17:21 UTC, mikehearn commented on gradle-plugins/cordformation/src/main/kotlin/net/corda/plugins/Baseform.kt
> +            //create a list of all cordapps used in this network and pass it to the bootstrapper
Space after //, capital letters and full stop please.

2018-02-12 17:21 UTC, mikehearn commented on node-api/src/main/kotlin/net/corda/nodeapi/internal/network/NetworkBootstrapper.kt
> +            val arg = args.firstOrNull()
Can you give `arg` a better name whilst you're here?

2018-02-12 17:21 UTC, mikehearn commented on node-api/src/main/kotlin/net/corda/nodeapi/internal/network/NetworkBootstrapper.kt
> +            .map { (contract, attachmenIds) ->
typo, attachmentIds is missing the t

2018-02-12 17:21 UTC, mikehearn commented on node-api/src/main/kotlin/net/corda/nodeapi/internal/network/NetworkBootstrapper.kt
> +                contract to (attachmenIds.split(",").map { SecureHash.SHA256(it.parseAsHex()) })
SecureHash.parse is easier

2018-02-12 17:21 UTC, mikehearn commented on node/src/integration-test/kotlin/net/corda/node/services/BFTNotaryServiceTests.kt
> +        mockNet = MockNetwork(listOf("net.corda.testing.contracts"))
likewise - you should be able to use a no-args c'tor here

2018-02-12 17:21 UTC, mikehearn commented on node/src/main/kotlin/net/corda/node/internal/cordapp/CordappProviderImpl.kt
> +            //verify that the installed cordapps are whitelisted
comment style.

2018-02-12 17:21 UTC, mikehearn commented on node/src/main/kotlin/net/corda/node/internal/cordapp/CordappProviderImpl.kt
> +                    if (attch.id !in contractWhitelist) IllegalStateException("Contract ${contractClassName} in attachment ${attch.id} is not whitelisted")
Can I have a better exception type than ISE please? Also I wonder if maybe a better solution is to log a warning or error rather than throw.

2018-02-12 17:21 UTC, mikehearn commented on node/src/main/kotlin/net/corda/node/services/persistence/NodeAttachmentService.kt
> +                    foreignKey = ForeignKey(name = "FK__ctr_class__attachments"))
Do fk names have to be very short for some reason? This name seems kind of ugly but I don't know db conventions well. Also how comes there are two underscores between some words but not others?

2018-02-12 17:21 UTC, mikehearn commented on testing/node-driver/src/main/kotlin/net/corda/testing/node/MockNode.kt
> +//        override fun retrieveNetworkParameters(trustRoot: X509Certificate) = super.retrieveNetworkParameters(trustRoot).copy(whitelistedContractImplementations = whitelistAllContractsForTest)
?

2018-02-12 18:13 UTC, tudor-malene commented on node/src/main/kotlin/net/corda/node/services/persistence/NodeAttachmentService.kt
> +                    foreignKey = ForeignKey(name = "FK__ctr_class__attachments"))
Yes, Oracle 11 has a 30 character identifier hard limit.

2018-02-12 22:22 UTC, shamsasari requested changes

2018-02-12 22:22 UTC, shamsasari commented on node-api/src/main/kotlin/net/corda/nodeapi/internal/network/NetworkBootstrapper.kt
> +    fun bootstrap(directory: Path) = bootstrap(directory, null)
Is anything using this overload?

2018-02-12 22:22 UTC, shamsasari commented on node-api/src/main/kotlin/net/corda/nodeapi/internal/network/NetworkBootstrapper.kt
> +            installNetworkParameters(notaryInfos, nodeDirs, if (cordapps != null) generateWhitelist(cordapps) else null)
`cordapps?.let { generateWhitelist(it) }` to be a bit more concise

2018-02-12 22:22 UTC, shamsasari commented on node-api/src/main/kotlin/net/corda/nodeapi/internal/network/NetworkBootstrapper.kt
> +        val tempFile = Files.createTempFile("whitelist", ".txt")
Perhaps I'm missing something, but couldn't you directly create the mapping without writing to this temp file? `readContractWhitelist` parses what you've created here.

2018-02-12 22:22 UTC, shamsasari commented on node/src/main/kotlin/net/corda/node/internal/cordapp/CordappProviderImpl.kt
> +import net.corda.core.internal.GlobalProperties.networkParameters
ditto

2018-02-12 22:22 UTC, shamsasari commented on testing/node-driver/src/main/kotlin/net/corda/testing/node/MockServices.kt
> +            GlobalProperties.networkParameters = testNetworkParameters(emptyList())
What prompted this? A failing test? AbstractNode sets this on startup.

2018-02-12 22:22 UTC, shamsasari commented on testing/test-utils/src/main/kotlin/net/corda/testing/services/MockAttachmentStorage.kt
> +    private fun _importAttachment(jar: InputStream, contractClassNames: List<ContractClassName>? = null): AttachmentId {
`importAttachmentInternal`?

2018-02-12 22:22 UTC, shamsasari commented on testing/test-utils/src/main/kotlin/net/corda/testing/services/MockAttachmentStorage.kt
> +        return f.first
You can simplify this method further to just `files[id]?.first`

2018-02-12 22:22 UTC, shamsasari commented on testing/test-utils/src/main/kotlin/net/corda/testing/services/MockAttachmentStorage.kt
> +        if (!files.containsKey(sha256)) {
You can use the `in` operator here

2018-02-13 10:24 UTC, tudor-malene commented on core/src/main/kotlin/net/corda/core/contracts/AttachmentConstraint.kt
> +    override fun isSatisfiedBy(attachment: Attachment) = networkParameters.whitelistedContractImplementations!!.let { whitelist ->
@shamsasari, 
it needs to be nullable because of serialisation backward compatibility.

2018-02-13 10:45 UTC, tudor-malene commented on node-api/src/main/kotlin/net/corda/nodeapi/internal/network/NetworkBootstrapper.kt
> +        val tempFile = Files.createTempFile("whitelist", ".txt")
You're right, it's not necessary for our standard cordform use case.

I chose this approach as I was planning to reuse this generate function for the network operator tool to help setup the network parameters.
( Network admin would would take a list of cordapps and generate this whitelist, and then store it and use the tool again to append hashes and contracts to it. And use said whitelist when generating the parameters. Basically decoupling )

@shamsasari 
Does this make sense?

2018-02-13 10:51 UTC, tudor-malene commented on core/src/main/kotlin/net/corda/core/internal/GlobalProperties.kt
> +    //todo - is this a reasonable approach?
I think that's a good idea.

2018-02-13 10:53 UTC, tudor-malene commented on core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
> +        fun getContractAttachmentId(state: TransactionState<ContractState>) = services.cordappProvider.getContractAttachmentID(state.contract)
Yes, I think initially it was used in multiple places.

2018-02-13 10:55 UTC, tudor-malene commented on core/src/main/kotlin/net/corda/core/contracts/AttachmentConstraint.kt
> +object WhitelistedByZoneAttachmentConstraint : AttachmentConstraint {
Is it different from the other ``AttachmentConstraint(s)``?

2018-02-13 11:01 UTC, tudor-malene commented on node-api/src/main/kotlin/net/corda/nodeapi/internal/network/NetworkBootstrapper.kt
> +    fun bootstrap(directory: Path) = bootstrap(directory, null)
I kept it, in case it's used via reflection by some gradle plugin that I couldn't find.
But, now that I think about it, it's better it fails now during testing, so we spot the problem.

2018-02-13 13:27 UTC, exFalso commented
@mikehearn I haven't read the full PR, but from the relevant parts and the discussion we had the other day with @tudor-malene it seems to me that this way of doing the whitelisting poses a security threat.

In particular the whitelisting constraint's current definition doesn't include the *signing identity of attachment hashes*, which means Alice's signature over a transaction cannot be used to establish whether Alice trusts the signing identity. In other words this way of whitelisting makes the integrity of the ledger rely on trust that's not verifiable cryptographically based on the ledger alone.

The whitelisting-of-attachments problem mirrors the whitelisting-of-mrenclaves in sgx:
We must burn the whitelisting identity into the enclave in order to ensure that secrets are only revealed to whitelisted enclaves.
Similarly in this case we must burn the signing identity (the doorman or whatever pubkey) *into the transaction* (or rather the constraint) in order to ensure that only whitelisted contracts can spend the transaction's states.

If we don't do this then a signature over a transaction won't actually specify what whitelisting identity we trust.

So instead of the current design I'd suggest decoupling the constraint definition from the network map, the constraint should contain a pubkey, and the satisfiability check should simply check a signature of that identity over the attachment hash (or some whitelist datastructure). We would still need to figure out how to pass in the signature and the whitelist of course, perhaps we can slap it on the passed in Attachment?

2018-02-13 15:18 UTC, tudor-malene commented on docs/source/example-code/src/test/java/net/corda/docs/java/tutorial/testdsl/CommercialPaperTest.java
> +    private final MockServices ledgerServices = new MockServices(Arrays.asList("net.corda.finance.contracts"), MEGA_CORP);
It is needed because we need the cordapps now to add them to the WireTransaction.attachments.

Previously these tests, that were using the Transaction DSL, were wired with the ``AlwaysAcceptAttachmentConstraint``  constraint ( see ``TransactionDSL.input`` ), and thus the attachment hash was never needed.

AutoScanning cordapps only works if they are in the same package as the test and nothign is passed to the ``MockServices``. We usually pass in ``emptyList()``

2018-02-13 15:26 UTC, tudor-malene commented on core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
> +    internal fun toLedgerTransactionWithContext(services: ServicesForResolution, serializationContext: SerializationContext) =
It is long a one-liner.

2018-02-13 15:31 UTC, tudor-malene commented on testing/node-driver/src/main/kotlin/net/corda/testing/node/MockServices.kt
> +            GlobalProperties.networkParameters = testNetworkParameters(emptyList())
This line was added by @patrickkuo .
It's needed because networkParameters are global .

( In case you are wondering what @patrickkuo 's commits are doing here, it's because I merged from his branch before he pushed to master, to be able to refactor and use the GlobalProperties he introduced)

2018-02-13 17:28 UTC, tudor-malene commented
@mikehearn , @shamsasari,
Back to you.

2018-02-14 10:43 UTC, mikehearn commented
@exFalso I think your point is a specific case of a more general question, which is should transactions specify the CZ to which they belong? In this case the identity of the signer over the list of whitelisted hashes is the identity of the CZ operator, so it's always 'clear' unless you have transactions that cross zones. 

It _does_ mean that a transaction using this feature does not fully encapsulate the state, and a transaction could cease being valid if the zone operator ever removes a whitelisting entry, which is one reason I don't really love this feature. But we have the same issue with notaries: if a notary is removed from the network parameters, then that also breaks the validity of old transactions. Solution: don't do that.

Now, should a tx include e.g. the hash of a network parameters document in it? It could. But in effect it already does via the notary pointers. As a notary cluster can belong to only a single zone at once, the notary a state is controlled by implicitly selects a set of network parameters too.

2018-02-14 10:58 UTC, exFalso commented
@mikehearn 
> But in effect it already does via the notary pointers. As a notary cluster can belong to only a single zone at once, the notary a state is controlled by implicitly selects a set of network parameters too.
But that's not a chain of trust we can check during verification!
I'll rephrase: how can we check this constraint inside SGX? The enclave would need to be supplied with the whitelist that's signed with a trusted identity, but we can't check whether that identity is trusted! A malicious host can easily sign a malicious attachment hash, there's nothing in the transaction that specifies the signing identity to check against!

2018-02-14 11:17 UTC, shamsasari commented on core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
> +    internal fun toLedgerTransactionWithContext(services: ServicesForResolution, serializationContext: SerializationContext) =
Sure it's long for one line. What I'm saying is use a code block (`{ ... }`) instead of just moving to the next line.

2018-02-14 11:20 UTC, shamsasari commented on testing/node-driver/src/main/kotlin/net/corda/testing/node/MockServices.kt
> +            GlobalProperties.networkParameters = testNetworkParameters(emptyList())
So if you were to rebase onto master (or merge from master) this should go away?

2018-02-14 12:07 UTC, mikehearn requested changes
Nearly there now.

2018-02-14 12:07 UTC, mikehearn commented on node/src/main/kotlin/net/corda/node/services/persistence/NodeAttachmentService.kt
> +                    foreignKey = ForeignKey(name = "FK__ctr_class__attachments"))
What's up with the double underscores?

2018-02-14 12:07 UTC, mikehearn commented on testing/node-driver/src/main/kotlin/net/corda/testing/node/MockServices.kt
> +            GlobalProperties.networkParameters = testNetworkParameters(emptyList())
Can you rebase now Patrick's work is in master?

2018-02-14 12:12 UTC, mikehearn commented
@exFalso Right but does it matter?

In SGX integrity mode, where we're checking the contents of a tx chain given to us by a remote peer, we're consuming the statement of validity ourselves. We have no incentive to supply the enclave with the wrong network parameters.

In SGX privacy mode, whereby we trust the remote attestation of a remote enclave to tell us that the transaction is valid, the attack you suggest is a real concern. But the enclave can include more than just the hash of the tx it checked in its statement of validity. It could sign a general purpose data structure that states "I checked tx of hash A using network parameters of hash B" using a key established during previous remote attestation which implicitly covered "... using enclave version C implicitly incorporating Corda platform version D with CPU of security version level E".

So the enclave ends up asserting multiple facts in its response, one of which can be the network parameters that were used to check the transaction. This fact _could_ also be in the tx, but only at the cost of bloating every single transaction with knowledge that is usually implicit in the execution environment.

2018-02-14 12:30 UTC, tudor-malene commented on node/src/main/kotlin/net/corda/node/services/persistence/NodeAttachmentService.kt
> +                    foreignKey = ForeignKey(name = "FK__ctr_class__attachments"))
It's the convention we came up to for Foreign keys: FK__from_table__to_table
To differentiate from the underscores in the table names

2018-02-14 12:34 UTC, kchalkias commented
Had a discussion with @exFalso, his claims make some sense, but we might live with that.
a) One of the arguments that sounds interesting is: _Imagine you receive a copy of the ledger and you need to verify it's valid. As valid hashes are not reflected in the ledger, how do you know that at the time each tx was notarised the contract hash was indeed signed by the network map?_

The argument here is we trust the notary had the correct updated version at the time of check. As long as we trust the notary, we trust its clock, its updated whitelist etc.

BTW, there are a few other things we have to consider here, for example we don't check that NetworkMap params are signed by the NetworkMap entity itself (a Doorman's signature would also be accepted, do we want that?)

2018-02-14 12:35 UTC, shamsasari requested changes

2018-02-14 12:35 UTC, shamsasari commented on node-api/src/main/kotlin/net/corda/nodeapi/internal/network/NetworkBootstrapper.kt
> +        val tempFile = Files.createTempFile("whitelist", ".txt")
As discussed offline the bootstrapper can simply read the old network-parameters file to get the existing whitelist.

2018-02-14 12:37 UTC, tudor-malene commented on node-api/src/main/kotlin/net/corda/nodeapi/internal/ClassloaderUtils.kt
> + * @return: found contract class names or null if none found
Funnily, we use both.
@return ~ 300 times
@returns ~ 1000 times

2018-02-14 12:38 UTC, shamsasari commented
@kchalkias No, it is checked. See `net.corda.nodeapi.internal.network.NetworkMapKt#verifiedNetworkMapCert`

2018-02-14 12:46 UTC, tudor-malene commented on node-api/src/main/kotlin/net/corda/nodeapi/internal/ClassloaderUtils.kt
> +    val contracts = (scanResult.getNamesOfClassesImplementing(Contract::class.qualifiedName) + scanResult.getNamesOfClassesImplementing(UpgradedContract::class.qualifiedName)).distinct()
That's a good point. I took this code from the CordappLoader and assumed there was a reason for it.
I'll investigate

2018-02-14 14:13 UTC, kchalkias commented
@shamsasari great, so @exFalso we check against the cert role `CertRole.NETWORK_MAP`, no X500, no pubKey, no TLS assumptions. That said, this whitelist has passed the required signature verification tests before being stored. Due to this, the only hardcoded value is this NETWORK_MAP role and the ROOT_CERT in the truststore.
@mikehearn I am not sure if we've clarified if enclaves are CordaNetwork specific (thus root key is hardcoded) or they can work for any network, which might mean that the aforementioned keys/certs should be sent along with every tx as @exFalso mentioned.

2018-02-14 17:51 UTC, exFalso commented
@kchalkias @mikehearn To summarise the discussion and what we discussed offline:

1. Trust in the whitelist identity in the non-sgx use case is covered implicitly by the verifying notary signature, which should have the correct key in their truststore.
2. In the sgx case we have two designs, one catered for privacy of the backchain, one for integrity
 - Privacy use case: in this case the host may provide a malicious whitelist to the enclave, but there's no incentive to do so. Although come to think of it the host can use this to fish for information, i.e. pass different whitelists to reveal what attachments are used in the backchain.
 - Integrity use case: in this case we must establish the trust some other way inside the enclave. One way @mikehearn proposed is to require the certificate chain of the notary to be passed in, which should have the same root as the whitelist's signature. 
Another way that would cover both cases would be to burn the root key into the enclave itself, similarly to how we'll burn the enclave whitelisting key. This would piggyback on MRENCLAVE and tie each enclave image to the corresponding CZ. Which I think is fine.

2018-02-14 18:10 UTC, kchalkias commented
IMO the first "same-chain" suggestion cannot provide the required guaranties, eg. I can sign with a Node's key that share the same cert path with the notary. We should ensure it is indeed the NETWORK_MAP entity... atm, we do this:
```
fun <T : Any> SignedDataWithCert<T>.verifiedNetworkMapCert(rootCert: X509Certificate): T {
    require(CertRole.extract(sig.by) == CertRole.NETWORK_MAP) { "Incorrect cert role: ${CertRole.extract(sig.by)}" }
    X509Utilities.validateCertificateChain(rootCert, sig.by, rootCert)
    return verified()
}
```
Thus, first check the ROLE
Then check if I am one level away from the ROOT
I have my concerns on this as well (due to the inflexibility on adding intermediate levels, but we can tolerate that).
All in all, I am leaning towards burning the root key into the enclave.

2018-02-15 12:47 UTC, mikehearn commented on core/src/main/kotlin/net/corda/core/contracts/AttachmentConstraint.kt
> +object WhitelistedByZoneAttachmentConstraint : AttachmentConstraint {
I'm going to side with Tudor here - it'd be weird if you could explore a public data structure (WireTransaction) and encounter internal-only objects in that graph. Are you even allowed to do `is` testing on such an object to ignore it? Perhaps not, as the object type could move or be renamed! This class is conceptually simple so I hope it isn't going to change after this PR goes in, so it should stay public.

2018-02-21 16:42 UTC, mikehearn commented
This PR was superseded by a different one against v3, and then another PR that brings it back to master. Closing.

2018-02-21 16:42 UTC, closed without merging