Deterministic JVM
corda/corda pull request #3386
Opened 2018-06-15 13:18 UTC by tlil

### Introduction

The code in the DJVM module has not yet been integrated with the rest of the platform. It will eventually become a part of the node and enforce deterministic and secure execution of smart contract code, which is mobile and may propagate around the network without human intervention.

**NOTE**: Currently, it stands alone as an evaluation version. We want to give developers the ability to start trying it out and get used to developing deterministic code under the set of constraints that we envision will be placed on contract code in the future.

### Documentation

For details around the concept, implementation, ruleset, scope, etc., please refer to the documentation site: [docs/source/key-concepts-djvm.rst](https://github.com/corda/corda/blob/068240c6540636e4714c9b7cfd58c311b2b36ee2/docs/source/key-concepts-djvm.rst)

2018-06-15 16:23 UTC, chrisr3 requested changes
I'm going to have do work through this in "bite-sized" chunks.

2018-06-16 15:52 UTC, tlil commented on djvm/shell/djvm
> +#!/usr/bin/env bash
Yes, this is intended to run in a Bash shell. I've not provided any equivalents for Windows as it's still possible to run through Cygwin, MinGW or similar environments. 🐧

2018-06-16 16:06 UTC, tlil commented on djvm/build.gradle
> +    ext.asm_version = '6.2'
Yes, you're right. Good points. It was an oversight on my part as I moved it out of the experimental section. Will fix.

2018-06-16 16:12 UTC, tlil commented on djvm/src/main/kotlin/net/corda/sandbox/source/JarInputStreamIterator.kt
> +    override fun close() {
yeah, a bit shorter, innit :) nice one

2018-06-16 16:13 UTC, tlil commented on djvm/build.gradle
> +
Nope, don't need it. Was lingering from the experimental module. Will remove.

2018-06-16 16:18 UTC, tlil commented on djvm/src/main/kotlin/net/corda/sandbox/analysis/ClassResolver.kt
> +                Regex("^(\\[+)L(.*);$").replace(name) {
Indeed - oversight on my end. Fixed one in `ClassModule` as well.

2018-06-16 16:54 UTC, tlil commented on djvm/build.gradle
> +    compile "org.slf4j:slf4j-nop:$slf4j_version"
Not yet - @exFalso, want to file a follow-up story to add logging? Or add to scope of this PR?

2018-06-18 07:43 UTC, chrisr3 commented on djvm/build.gradle
> +    ext.asm_version = '6.2'
ASM 5.0.4 is a transitive dependency of Kryo. ClassCarpenter also uses ASM, but that's home-grown code and so can be updated (if necessary).

2018-06-18 09:10 UTC, chrisr3 submitted a review, later dismissed
Now for round two :grin:.
- Nice to see lots of unit tests :smile:. Have you also tested with Kotlin-specific "package" classes, i.e. a `*Kt.class` file that doesn't actually contain a `class` definition?
- Are you still using the static version of the deterministic `rt.jar` that I sent you a while back? Because if so, you can now move to the
```
net.corda:deterministic-rt:${deterministic_rt_version}:api
```
JAR that's been uploaded to the artifactory.

2018-06-18 09:10 UTC, chrisr3 commented on djvm/src/test/kotlin/net/corda/sandbox/TestBase.kt
> +
Do we need a `TestBase` class? Aren't there alternatives to using inheritance, e.g. JUnit `@Rule` and `@ClassRule` for shared code, or even just simple helper classes?

2018-06-18 09:27 UTC, chrisr3 commented on docs/source/key-concepts-djvm.rst
> +versions, this whitelist will be trimmed down to the bare minimum needed, essentially a subset of ``java.lang``, so
Surely a subset of `java.*` rather than `java.lang.*`? Maybe even some `javax.*` classes too? There's a fair bit of useful functionality in `java,util`, and even `java.io` contains things like `ByteArray{Input|Output}Stream`, `Closeable`, `FileNotFoundException` etc that we might want to use. And then there's `java.security.` ...

2018-06-18 09:31 UTC, chrisr3 commented on docs/source/key-concepts-djvm.rst
> +
We're going to need _some_ native methods for e.g. array handling. Nor am I convinced that we can remove classes like `sun.misc.Unsafe`, although we should obviously prevent them from being invoked _directly_ from contract code.

2018-06-18 09:34 UTC, chrisr3 commented on docs/source/key-concepts-djvm.rst
> +execute. Method size can be limited and jumps count towards the budget, so such a strategy is guaranteed to eventually
Boldly splitting infinitives that no-one has split before... :vulcan_salute:

2018-06-18 09:36 UTC, chrisr3 commented on docs/source/key-concepts-djvm.rst
> +high overhead. A more sophisticated design would be to statically calculate byte code costs as much as possible ahead of
"... to calculate byte code costs statically..." :vulcan_salute:

2018-06-18 09:57 UTC, exFalso commented on djvm/build.gradle
> +    ext.asm_version = '6.2'
One way we could circumvent this is to make the djvm a standalone project and include it with `includeBuild` instead of `include` in settings.gradle. See https://docs.gradle.org/current/userguide/composite_builds.html

2018-06-18 10:00 UTC, exFalso commented on djvm/build.gradle
> +    from(configurations.compile.collect { it.isDirectory() ? it : zipTree(it) }) {
Also, we started using a very convenient project to do the fatjaring, see for example https://github.com/corda/corda/blob/141d45c39df69591f33fbc15aeb67fd2f77672bd/experimental/avalanche/build.gradle#L40, perhaps worth switching to this

2018-06-18 10:29 UTC, tlil commented on docs/source/key-concepts-djvm.rst
> +execute. Method size can be limited and jumps count towards the budget, so such a strategy is guaranteed to eventually
Copy-pasta from the tech whitepaper... Will rework this section a bit

2018-06-18 10:33 UTC, tlil commented on docs/source/key-concepts-djvm.rst
> +
Will clarify :+1:

2018-06-18 10:42 UTC, tlil commented
Re:

>Nice to see lots of unit tests 😄. Have you also tested with Kotlin-specific "package" classes, i.e. a *Kt.class file that doesn't actually contain a class definition?

Good point - I haven't so will address that.

>Are you still using the static version of the deterministic rt.jar that I sent you a while back? Because if so, you can now move to the net.corda:deterministic-rt:${deterministic_rt_version}:api. JAR that's been uploaded to the artifactory.

It's a generated whitelist based on an older version of `deterministic-rt.jar`, so I will update this to reflect the latest API from Artifactory (and make it update dynamically in the process).

2018-06-18 10:43 UTC, tlil commented on docs/source/key-concepts-djvm.rst
> +versions, this whitelist will be trimmed down to the bare minimum needed, essentially a subset of ``java.lang``, so
Yeah, can update - the scope of the actual whitelist will have to be determined. The thinking was to have as much as possible also be checked by DJVM regardless of whether it exists in `rt-deterministic.jar` or not. Will update to clarify.

2018-06-18 11:05 UTC, tlil commented on djvm/build.gradle
> +    from(configurations.compile.collect { it.isDirectory() ? it : zipTree(it) }) {
Done

2018-06-18 14:58 UTC, exFalso reviewed
Not done yet, just flushing a batch of commetns

2018-06-18 14:58 UTC, exFalso commented on djvm/src/main/kotlin/net/corda/sandbox/tools/Utilities.kt
> +    }
Perhaps use `Files.createTempDirectory` instead, that will work on Windows too

2018-06-18 14:58 UTC, exFalso commented on djvm/src/main/kotlin/net/corda/sandbox/tools/cli/BuildCommand.kt
> +class BuildCommand : CommandBase() {
I like this picocli library

2018-06-18 14:58 UTC, exFalso commented on djvm/src/main/kotlin/net/corda/sandbox/rules/implementation/AlwaysInheritFromSandboxedObject.kt
> +        if (instruction is MemberAccessInstruction &&
I wonder whether it'd be beneficial to use something like `javassist` to ease bytecode reading/writing

2018-06-18 14:58 UTC, exFalso commented on djvm/src/main/kotlin/net/corda/sandbox/code/EmitterModule.kt
> +    var emitDefaultInstruction: Boolean = true
Is this essentially a global variable used while emitting code? The semantics are a bit unclear to me, it refers to emitting a "default instruction", but the use cases seem to indicate that this effects calls into superclass visitors

2018-06-18 14:58 UTC, exFalso commented on djvm/src/main/kotlin/net/corda/sandbox/rules/ClassRule.kt
> +     * the sandbox.
This isn't clear to me and it doesn't seem to be used. From what I understand all rules are run before rewriting right?

2018-06-18 19:00 UTC, tlil commented on djvm/src/main/kotlin/net/corda/sandbox/code/EmitterModule.kt
> +    var emitDefaultInstruction: Boolean = true
If this flag is unset, the superclass' visitor doesn't get called for the currently processed instruction, effectively voiding the emittance of said instruction.

In short, for each instruction, we run through the following steps:
 1. Process emitters, which each can emit instructions to the class (at the current instruction pointer)
 2. Emit original instruction, unless `emitDefaultInstruction` is false

2018-06-18 19:02 UTC, tlil commented on djvm/src/main/kotlin/net/corda/sandbox/rules/ClassRule.kt
> +     * the sandbox.
Indeed - will remove.

2018-06-18 19:05 UTC, tlil commented on djvm/src/main/kotlin/net/corda/sandbox/code/EmitterModule.kt
> +    var emitDefaultInstruction: Boolean = true
Essentially:

https://github.com/corda/corda/blob/26212ff5894d1ed6b96c7bfa3a0a4fa46abe8477/djvm/src/main/kotlin/net/corda/sandbox/analysis/ClassAndMemberVisitor.kt#L495-L508

2018-06-18 19:07 UTC, tlil commented on djvm/src/main/kotlin/net/corda/sandbox/rules/implementation/AlwaysInheritFromSandboxedObject.kt
> +        if (instruction is MemberAccessInstruction &&
How do you mean? Anything in particular that you had in mind? Either way, I'd be keen to punt on that to a follow-up ticket.

2018-06-18 19:09 UTC, tlil commented on djvm/src/main/kotlin/net/corda/sandbox/tools/Utilities.kt
> +    }
This `tmp` directory is relative to the current working directory, so it works on Windows as well. In other words, we're not creating `/tmp/...` here, but rather `$(pwd)/tmp/...`. 😉

2018-06-18 19:33 UTC, tlil commented on djvm/src/main/kotlin/net/corda/sandbox/source/ClassSource.kt
> +        open val qualifiedClassName: String = "",
This was not used in the sources that could have multiple classes. I've removed the dependency between `ClassSource` and `PathClassSource` to avoid that confusion. For `ClassSource` it is now truly the qualified name :)

2018-06-18 19:43 UTC, tlil commented on djvm/src/main/kotlin/net/corda/sandbox/references/ReferenceMap.kt
> +    private val map: MutableMap<EntityReference, MutableSet<SourceLocation>> = hashMapOf()
Hmm, not quite. `entities` are used to guarantee safe traversal and processing of the collection of references whilst still allowing updates to be made. 

The fact that we're maintaining both `mapByLocation` and `map` is to speed up keying into the set of references per location and locations per reference, respectively. The former is accessible through `from()` whereas the latter can be retrieved via `get()`.

I've renamed these fields and methods to clarify.

2018-06-18 20:21 UTC, exFalso commented on djvm/src/main/kotlin/net/corda/sandbox/rules/implementation/AlwaysInheritFromSandboxedObject.kt
> +        if (instruction is MemberAccessInstruction &&
Ah this was just a general wonderingment

2018-06-19 07:47 UTC, tlil commented on djvm/src/main/kotlin/net/corda/sandbox/code/EmitterModule.kt
> +    var emitDefaultInstruction: Boolean = true
Yep. ASM's visitor pattern at play ;)

2018-06-19 10:03 UTC, exFalso commented on djvm/src/main/kotlin/net/corda/sandbox/references/ReferenceMap.kt
> +    private val map: MutableMap<EntityReference, MutableSet<SourceLocation>> = hashMapOf()
What I meant was calling `process` drains the queue, which means subsequent `process` calls won't do the same thing, however `size` and `get` still return the same values. One way of mitigating this is to simply iterate the queue instead of draining.
But it's only used in a single place, so perhaps it's fine, I was just a bit confused trying to figure out the api contract:)

2018-06-19 10:18 UTC, exFalso commented on djvm/src/main/kotlin/net/corda/sandbox/source/JarInputStreamIterator.kt
> +) : Iterator<InputStream>, AutoCloseable {
I meant that the type's contract indicates that we could do something like this:
```kotlin
  val streamOfStreams: Iterator<InputStream> = ...
  val threadPool: Executor = ...
  for (steam in streamOfStreams) {
    threadPool.execute { processStream(stream) }
  }
```
which would be incorrect. An `Iterator<InputStream>` indicates that the elements are independent and `Iterator` is parametric, it doesn't indicate that the underlying streams are actually linked, and also affect the enclosing `Iterator`.

In other words the `Iterator` contract is much more liberal than the structure that `nextEntry -> next` extracts.

Anyway, the only reason I'm bringing this up is because I have ptsd from another project that used stream of streams everywhere and it was completely incomprehensible :D

2018-06-19 10:22 UTC, tlil commented on djvm/src/main/kotlin/net/corda/sandbox/source/JarInputStreamIterator.kt
> +) : Iterator<InputStream>, AutoCloseable {
Yes, I know. Seems like that's how you roll with this Jar stream though, unless you want to constrain usage and only surface the resulting `ByteArray`s or `Class<*>`s. Instead of the stream. The latter would require the iterator class to have some knowledge of context. Let's take this convo offline. You're sitting right next to me after all. :-)

2018-06-19 14:18 UTC, exFalso reviewed
Second pass done.

All in all this code is very readable! The Rule/Emitter/Provider separation is very neat. 

The only parts that were a bit unclear to me were the high-level traversal order of classes/references and the pinned class/whitelist interaction, I think these could be made more explicit. Some clarification/docs on these would be nice.

Other than that I'm happy with this PR, great stuff!

2018-06-19 14:18 UTC, exFalso commented on djvm/src/main/kotlin/net/corda/sandbox/analysis/ClassResolver.kt
> +            whitelist + pinnedClasses + Regex("^$sandboxPrefix.*$")
It's still unclear to me what the relation between the whitelist and pinned classes is. In some places they seem to be used interchangably, in others it seems pinned classes are a superset of the whitelist (e.g. in Whitelist.kt), here it seems they can be separate. In SandboxExecutor it seems whitelisted classes are not loaded at all during validation, and yet in SandboxClassLoader there is an extra check to skip analysing whitelisted classes.

Can you add a comment about what the difference is somewhere please? My understanding was that pinned classes are ones that don't get rewritten and whitelisted classes are ones that don't get validated. However for example in this file `resolveName()` indicates that whitelisted classes also don't get remapped.

2018-07-05 21:49 UTC, tlil commented on djvm/src/main/kotlin/net/corda/sandbox/SandboxRuntimeContext.kt
> +            SandboxRuntimeContext.INSTANCE = this
Nope, that should never happen. I could assert on it, but wouldn't matter anyway.

2018-07-05 21:54 UTC, tlil commented on djvm/src/main/kotlin/net/corda/sandbox/analysis/AnalysisConfiguration.kt
> +        private val sandboxPrefix: String = "sandbox/",
The binary package names are represented with slashes `/` as separators rather than dots `.`. 

And the slash could be appended in the `init` block for input without it, as you say. That said, this is a const really anyway, so will move it to being that instead.

2018-07-05 21:59 UTC, tlil commented on djvm/src/main/kotlin/net/corda/sandbox/analysis/ClassAndMemberVisitor.kt
> +    private fun addReferenceToType(type: String) {
I'll change to `recordTypeReference`

2018-07-05 22:00 UTC, tlil commented on djvm/src/main/kotlin/net/corda/sandbox/analysis/ClassAndMemberVisitor.kt
> +    private fun addReferenceToMember(owner: String, name: String, desc: String) {
I'll change to `recordMemberReference`

2018-07-05 22:07 UTC, tlil commented on djvm/src/main/kotlin/net/corda/sandbox/analysis/ClassAndMemberVisitor.kt
> +    open fun visitInstruction(method: Member, emitter: EmitterModule, instruction: Instruction) {}
It has access to the class through `method.className`

2018-07-05 22:13 UTC, tlil commented on djvm/src/main/kotlin/net/corda/sandbox/analysis/ClassAndMemberVisitor.kt
> +            currentClass?.apply {
I've tidied up in this, yeah. Good call.

2018-07-05 22:16 UTC, tlil commented on djvm/src/main/kotlin/net/corda/sandbox/analysis/ClassResolver.kt
> +                    continue@loop
Doesn't work since we're inside a `when` block

2018-07-05 22:20 UTC, tlil commented on djvm/src/main/kotlin/net/corda/sandbox/costing/RuntimeCostSummary.kt
> +        "Contract [${it.name}] terminated due to over-allocation"
Yep, good point

2018-07-05 22:46 UTC, tlil commented on djvm/src/main/kotlin/net/corda/sandbox/analysis/ClassAndMemberVisitor.kt
> +        analysisContext = context
B/c I wanted to be able to reuse the visitor class to traverse a class structure in different context. Especially considering that there can be various derived implementations of it as well, e.g. for remapping, etc. Can revisit that decision at a later stage, but won't make any changes to it as part of this PR.

2018-07-05 23:07 UTC, tlil commented
Addressed most comments; will add a few more details around pinned vs whitelisted classes tomorrow, plus update the whitelist in accordance with the latest version of `deterministic-rt.jar`.

2018-07-31 18:39 UTC, mikehearn requested changes
Incredibly clean and professionally done code, congratulations on building something quite special here.

2018-07-31 18:39 UTC, mikehearn commented on djvm/src/main/kotlin/net/corda/djvm/analysis/ClassResolver.kt
> + * Functionality for resolving the class name of a sandboxed or sandboxable class.
I could use a bit of description here about what "resolved" means exactly.

2018-07-31 18:39 UTC, mikehearn commented on djvm/src/main/kotlin/net/corda/djvm/analysis/Whitelist.kt
> +        // TODO Refine to contain only the bare minimum of classes needed from java/lang
Does this TODO need to be done for the security arguments to hold? There's quite a lot in this package!

2018-07-31 18:39 UTC, mikehearn commented on djvm/src/main/kotlin/net/corda/djvm/analysis/Whitelist.kt
> +                // TODO This is a snapshot of what's currently in our deterministic rt.jar build
Is this done now?

2018-07-31 18:39 UTC, mikehearn commented on djvm/src/main/kotlin/net/corda/djvm/analysis/Whitelist.kt
> +                val kotlin = Whitelist.fromResource("kotlin-deterministic.dat.gz")
Why is the Kotlin stdlib special here?

2018-07-31 18:39 UTC, mikehearn commented on djvm/src/main/kotlin/net/corda/djvm/costing/RuntimeCostSummary.kt
> + * This class provides a summary of the accumulated costs for the runtime metrics that are being tracked. It also keeps
I wonder if we should define a blended metric here, or whether the network parameters should represent cost limits as these individual values?

2018-07-31 18:39 UTC, mikehearn commented on djvm/src/main/kotlin/net/corda/djvm/execution/ExecutionSummary.kt
> +        val costs: Map<String, Long> = emptyMap()
not very type safe - is it done this way to avoid classloader issues or something?

2018-07-31 18:39 UTC, mikehearn commented on djvm/src/main/kotlin/net/corda/djvm/execution/IsolatedRunnable.kt
> +class IsolatedRunnable(
It claims to be a Runnable but it's actually not implementing Runnable. Maybe IsolatedTask is better?

2018-07-31 18:39 UTC, mikehearn commented on djvm/src/main/kotlin/net/corda/djvm/execution/IsolatedRunnable.kt
> +                        "allocations" to runtimeCosts.allocationCost.value,
Maybe these should be defined as constants somewhere.

2018-07-31 18:39 UTC, mikehearn commented on djvm/src/main/kotlin/net/corda/djvm/execution/IsolatedRunnable.kt
> +        val threadName = "Sandbox-$identifier-${uniqueIdentifier.getAndIncrement()}"
maybe Sandbox -> DJVM

2018-07-31 18:39 UTC, mikehearn commented on djvm/src/main/kotlin/net/corda/djvm/execution/IsolatedRunnable.kt
> +            name = threadName
There's a (lower case) `thread` helper in kotlin that might avoid the apply here and be useful in general.

2018-07-31 18:39 UTC, mikehearn commented on djvm/src/main/kotlin/net/corda/djvm/execution/IsolatedRunnable.kt
> +                is StackOverflowError -> throw StackOverflowError("Stack overflow")
why not rethrow the original exceptions?

2018-07-31 18:39 UTC, mikehearn commented on djvm/src/main/kotlin/net/corda/djvm/execution/SandboxExecutor.kt
> +        // 5. We drain this queue by validating references, this time including member references.
A bit of discussion here about what "validating references" means would be good.

2018-07-31 18:39 UTC, mikehearn commented on djvm/src/main/kotlin/net/corda/djvm/execution/SandboxExecutor.kt
> +        logger.trace("Executing {} with input {}...", runnableClass, input)
A bit of discussion about possible parallelism might be good too.

2018-07-31 18:39 UTC, mikehearn commented on djvm/src/main/kotlin/net/corda/djvm/execution/SandboxedRunnable.kt
> +interface SandboxedRunnable<in TInput, out TOutput> : DiscoverableRunnable {
Isn't this a java 8 `Function`, basically?

2018-07-31 18:39 UTC, mikehearn commented on djvm/src/main/kotlin/net/corda/djvm/rules/implementation/AlwaysInheritFromSandboxedObject.kt
> +            loadConstant(0xfed_c0de)
A note about what this magic number is would be useful here, although I suspect the hashCode RNG should be something we can set from outside the sandbox so it's initialised from the tx bytes hash and iterates appropriately.

2018-07-31 18:39 UTC, mikehearn commented on djvm/src/main/kotlin/net/corda/djvm/rules/implementation/AlwaysUseExactMath.kt
> + * Use exact integer and long arithmetic where possible.
Note here that this rule is not required for determinism, but we believe it helps make code more robust, so we enable it.

2018-07-31 18:39 UTC, mikehearn commented on djvm/src/main/kotlin/net/corda/djvm/rules/implementation/AlwaysUseExactMath.kt
> +class AlwaysUseExactMath : Emitter {
Why does it appear unused?

2018-07-31 18:39 UTC, mikehearn commented on djvm/src/main/kotlin/net/corda/djvm/rules/implementation/AlwaysUseStrictFloatingPointArithmetic.kt
> + * Definition provider that ensures that all methods use strict floating-point arithmetic in the sandbox.
Can you add a note here that future JVM releases may make this pass obsolete:

https://bugs.openjdk.java.net/browse/JDK-8175916

2018-07-31 18:39 UTC, mikehearn commented on djvm/src/main/kotlin/net/corda/djvm/rules/implementation/DisallowFinalizerMethods.kt
> +        fail("Disallowed finalizer method") given ("${member.memberName}:${member.signature}" == "finalize:()V")
Maybe add a // TODO here to just automatically erase them. The JVM is allowed to never call a finalizer so this might increase our compatibility a bit.

2018-07-31 18:39 UTC, mikehearn commented on djvm/src/main/kotlin/net/corda/djvm/rules/implementation/DisallowReflection.kt
> +        // TODO Enable controlled use of reflection APIs
Hmm, there are more reflection APIs than just these e.g. in `sun.misc.Unsafe`. 

We should disallow access to any of the packages that are forbidden by the default Java sandbox security policy. See the `package.access` key in jre/lib/security/java.security

2018-07-31 18:39 UTC, mikehearn commented on djvm/src/main/kotlin/net/corda/djvm/utilities/Processor.kt
> +    inline fun <reified T> processEntriesOfType(
This looks more like an extension method on `List<*>` - but I wonder if we should refactor out a generic Corda utilities library for both djvm and node/core to share.

2018-07-31 18:39 UTC, mikehearn commented on djvm/src/main/kotlin/sandbox/java/lang/Object.kt
> +open class Object(private val hashValue: Int) {
So, this works, but will cause crap performance in hash maps and other such things.

What we should probably do is have a per-context RNG seeded from the tx merkle root, that is iterated each time it's accessed or something. Perhaps it doesn't matter and we can just have a todo here.

hashCode here should probably chain to System.identityHashCode with a comment that in the DJ subset, System.identityHashCode is deterministic?

2018-07-31 18:39 UTC, mikehearn commented on djvm/src/main/kotlin/sandbox/net/corda/sandbox/costing/RuntimeCostAccounter.kt
> +        // TODO Derive better size estimates for complex types.
This might be useful: https://github.com/DimitrisAndreou/memory-measurer

2018-07-31 18:39 UTC, mikehearn commented on djvm/src/main/kotlin/sandbox/net/corda/sandbox/costing/RuntimeCostAccounter.kt
> +        val size = allocationCosts.getOrDefault(typeName, 16)
Need to check here that length is >= 0 otherwise I can write bytecode that arbitrarily reduces my own allocation cost.

2018-07-31 18:39 UTC, mikehearn commented on djvm/src/main/kotlin/sandbox/net/corda/sandbox/costing/RuntimeCostAccounter.kt
> +        context.runtimeCosts.allocationCost.increment(length * typeSize)
ditto

2018-08-03 14:56 UTC, tlil commented on djvm/src/main/kotlin/sandbox/net/corda/sandbox/costing/RuntimeCostAccounter.kt
> +        val size = allocationCosts.getOrDefault(typeName, 16)
Yep, good point. Also changed the accounter to use `Math.addExact()` to catch potential overflows as well.

2018-08-03 15:05 UTC, tlil commented on djvm/src/main/kotlin/sandbox/java/lang/Object.kt
> +open class Object(private val hashValue: Int) {
Yes, fully aware 😄 What you mention has been the plan all along. This work has just been the enabler for it. The value gets passed in through the emitter at the moment:

https://github.com/corda/corda/blob/d0a743f8c778749bedc7bf614786743263c15a98/djvm/src/main/kotlin/net/corda/djvm/rules/implementation/AlwaysInheritFromSandboxedObject.kt#L38-L41

So `hashValue` could either be derived from context and injected per access on emittance (which potentially could make caching less efficient), or this class can be modified to pull in the context-based seed in a different manner.

Will clarify by either adding a TODO or provide a reference implementation of how it can be done when I push my changes.

2018-08-13 11:09 UTC, exFalso reviewed
Small things

2018-08-13 11:09 UTC, exFalso commented on djvm/src/main/kotlin/net/corda/djvm/rewiring/SandboxClassLoader.kt
> +            supportingClassLoader.loadClass(name)
In what circumstances is this `catch` hit?

2018-08-13 11:09 UTC, exFalso commented on djvm/cli/src/main/kotlin/net/corda/djvm/tools/cli/TreeCommand.kt
> +        description = ["Show the hierarchy of the classes that has been created with the 'new' command."]
typo has -> have

2018-08-13 11:09 UTC, exFalso commented on djvm/src/main/kotlin/net/corda/djvm/validation/RuleContext.kt
> +     * Classes that has been explicitly defined in the sandbox namespace.
typo has -> have

2018-08-20 12:06 UTC, tlil commented on djvm/src/main/kotlin/net/corda/djvm/execution/ExecutionSummary.kt
> +        val costs: Map<String, Long> = emptyMap()
I've made this strongly typed

2018-08-20 12:07 UTC, tlil commented on djvm/src/main/kotlin/net/corda/djvm/execution/IsolatedRunnable.kt
> +                        "allocations" to runtimeCosts.allocationCost.value,
Made the costs strongly typed, which removes the need for these string constants in the first place.

2018-08-20 12:15 UTC, tlil commented on djvm/src/main/kotlin/net/corda/djvm/execution/IsolatedRunnable.kt
> +                is StackOverflowError -> throw StackOverflowError("Stack overflow")
Will fix

2018-08-20 12:32 UTC, tlil commented on djvm/src/main/kotlin/net/corda/djvm/rules/implementation/AlwaysUseExactMath.kt
> +class AlwaysUseExactMath : Emitter {
It's just because the rules are implicitly registered at the moment. I will remove the annotation.

2018-08-20 13:16 UTC, tlil commented on djvm/src/main/kotlin/sandbox/net/corda/sandbox/costing/RuntimeCostAccounter.kt
> +        // TODO Derive better size estimates for complex types.
Yes, I had a look at that a while ago. Decided against using it for now since:

1) `MemoryMeasurer` requires a Java agent, and
2) `ObjectGraphMeasurer` just gives you a footprint object with number of objects, primitives and references.

To avoid inflating the scope of this initial PR too much ;), I'll leave this as future work. Will add the link as a comment to `RuntimeCostAccounter.kt` though.

2018-08-20 14:45 UTC, tlil commented on djvm/src/main/kotlin/net/corda/djvm/execution/SandboxedRunnable.kt
> +interface SandboxedRunnable<in TInput, out TOutput> : DiscoverableRunnable {
Basically, yeah. It just adds the `DiscoverableRunnable` and explicitly allows for nullable return values from `run()` (in Kotlin land).

2018-08-20 14:48 UTC, tlil commented on djvm/src/main/kotlin/net/corda/djvm/utilities/Processor.kt
> +    inline fun <reified T> processEntriesOfType(
Yes, I was thinking that could be useful as well. Let's do that as a follow-up to this PR though.

2018-08-20 14:58 UTC, tlil commented on djvm/src/main/kotlin/net/corda/djvm/costing/RuntimeCostSummary.kt
> + * This class provides a summary of the accumulated costs for the runtime metrics that are being tracked. It also keeps
@exFalso, thoughts? Pinned limits provided through the network parameters? I think we can do that as a follow-up to this PR regardless, though :)

2018-08-20 15:01 UTC, tlil commented on djvm/src/main/kotlin/net/corda/djvm/rules/implementation/AlwaysInheritFromSandboxedObject.kt
> +            loadConstant(0xfed_c0de)
Yes, this has been intended as a placeholder and example of how it can be passed in. I will add a comment describing that this is a magic number and that an RNG should be passed from the outside. Will clarify a bit and push an update.

2018-08-20 15:13 UTC, tlil commented on djvm/src/main/kotlin/sandbox/java/lang/Object.kt
> +open class Object(private val hashValue: Int) {
As for chaining to `System.identityHashCode()` - that's somewhat tricky unfortunately as `System` resides in `java.lang` and defining classes in that package is illegal. What did you have in mind here @mikehearn ? If I could re-define `System` through the classloader, that would make sense, but I can't.

2018-08-20 15:37 UTC, tlil commented on djvm/src/main/kotlin/sandbox/java/lang/Object.kt
> +open class Object(private val hashValue: Int) {
Okay, so will:
1) Implement a `sandbox.java.lang.System`
2) Replace references in loaded classes accordingly
3) Change `sandbox.java.lang.Object.hashCode()` to call `sandbox.java.lang.System.identityHashCode(this)`

2018-08-22 11:57 UTC, tlil commented
@mikehearn @exFalso - back to you

2018-08-22 12:42 UTC, mikehearn requested changes

2018-08-22 12:42 UTC, mikehearn commented on djvm/src/main/kotlin/sandbox/net/corda/sandbox/costing/RuntimeCostAccounter.kt
> +        context.runtimeCosts.allocationCost.increment(length * typeSize)
I guess it's impossible to have a type size of zero so we should use > rather than >= here

2018-08-22 12:42 UTC, mikehearn commented on djvm/src/main/kotlin/net/corda/djvm/rules/implementation/AlwaysReferencePinnedClasses.kt
> +// TODO Use sandbox.* versions of registered pinned classes
I'm not sure I understand this comment or what impact it has on security.

2018-08-22 12:42 UTC, mikehearn commented on djvm/src/main/kotlin/sandbox/java/lang/System.kt
> +        throw NotImplementedError()
This should just return NULL to indicate "no security manager in use". The standard pattern for Java sandbox permission checks is to call getSecurityManager and then if it's not null, use it.

2018-08-22 12:42 UTC, mikehearn commented on djvm/src/main/kotlin/sandbox/java/lang/System.kt
> +        throw NotImplementedError("Eh eh, no can do!")
Maybe these can be empty too, so libraries that try to load native code but in which we never hit the codepath that needs them still work.

2018-08-22 12:45 UTC, mikehearn commented
Looks super good now, nearly there.

2018-08-22 12:49 UTC, tlil commented on djvm/src/main/kotlin/net/corda/djvm/rules/implementation/AlwaysReferencePinnedClasses.kt
> +// TODO Use sandbox.* versions of registered pinned classes
This file was removed in a previous commit. And the type size comment above has already been fixed.

2018-08-22 12:55 UTC, tlil commented on djvm/src/main/kotlin/net/corda/djvm/rules/implementation/AlwaysReferencePinnedClasses.kt
> +// TODO Use sandbox.* versions of registered pinned classes
Ah, GitHub fouled me. I see what you meant about type size. Fixed

2018-08-22 12:59 UTC, mikehearn approved these changes

2018-08-22 13:00 UTC, mikehearn commented
![giphy](https://user-images.githubusercontent.com/971089/44464845-267fb980-a61c-11e8-88f0-9750e11d5f1b.gif)

2018-08-22 15:01 UTC, merged