CORDA-1314 Change logic around Contract version selection
corda/corda pull request #3410
Opened 2018-06-20 16:49 UTC by tudor-malene

WIP
https://r3-cev.atlassian.net/browse/CORDA-1314

How it behaves now:

- BankA, BankB start with Cash(Hash=1) and the HashConstraint
- BankB issues some Cash and exchanges some with BankA
- BankB decides to tinker with his Cordapp so will install Cash(Hash=2)
- BankA sends some Cash to BankB, and BankB is happy to accept it because it "trusts" Cash(Hash=1)
- BankB selects some Cash from it's vault and because the input states are using Hash=1, then that will be inherited by the output states and will be set in the "attachments" field
- Now, if BankB self-Issues some Cash, then this will be created with (Hash=2). Obviously this new batch is not fungible with the old batch (Hash=1), because the HashConstraint will fail for one of them
- BankB selects 1 coin from the second batch, and sends it to BankA. BankA does not know anything about this Cash(Hash=2) version so it rejects the transaction. ( this is back to this issue: https://r3-cev.atlassian.net/browse/ENT-1643)

2018-06-21 11:48 UTC, chrisr3 submitted a review, later dismissed

2018-06-21 11:48 UTC, chrisr3 commented on core/src/main/kotlin/net/corda/core/transactions/LedgerTransaction.kt
> +            log.warn("Transaction $this failed to verify.", tve)
We can't do this because it requires the contract's `toString()` not to contain references to classes such as
`net.corda.core.internal.Emoji`. Besides, `LedgerTransaction.verify()` is going to be executed inside the DJVM and so no-one could ever read this message anyway.

2018-06-28 15:38 UTC, mikehearn requested changes

2018-06-28 15:38 UTC, mikehearn commented on core/src/main/kotlin/net/corda/core/transactions/MissingContractAttachments.kt
> +sealed class TransactionBuildingException(message: String) : FlowException(message)
public API needs KDocs

2018-06-28 15:38 UTC, mikehearn commented on core/src/main/kotlin/net/corda/core/transactions/MissingContractAttachments.kt
> +class ConflictingAttachmentsRejection(contractClassName: ContractClassName)
kdocs

2018-06-28 15:38 UTC, mikehearn commented on core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
> +    @Throws(TransactionBuildingException::class)
I suspect this is source incompatible for Java users? If I have a `catch (MissingContractAttachments e)` clause, will it still compile after this or will javac complain that i'm not catching `TransactionBuildingException`?

2018-06-28 15:38 UTC, mikehearn commented on core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
> +        val contractAttachments = determineContractAttachments(services)
explicitly specify the type here as it's not obvious to the read what it'll be (alt-enter to do it automatically)

2018-06-28 15:38 UTC, mikehearn commented on core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
> +                else -> state.copy(constraint = HashAttachmentConstraint(contractAttachments.get(state.contract)!!))
Could use square brackets instead of get here I suppose

2018-06-28 15:38 UTC, mikehearn commented on core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
> +     * This method is responsible for selecting the Contract Attachments to be used for the current transaction.
contract attachments lower case

2018-06-28 15:38 UTC, mikehearn commented on core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
> +     * * For input states with [HashAttachmentConstraint], if the attachment with the "hash" is trusted, then it will be inherited to the output states.
why is hash in quotes here? Also you may want to define what trusted means. Maybe the word installed is better than trusted?

2018-06-28 15:38 UTC, mikehearn commented on core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
> +        // If they are hand-crafted with the HashAttachmentConstraint -for some reason-, then use that hash
How does this interact with the default constraint stuff ... what if someone sets a future SignatureConstraint on the output, does it matter here? A bit more discussion might be helpful as this stuff is quite complex.

2018-06-28 15:38 UTC, mikehearn commented on core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
> -        inputsWithTransactionState.add(stateAndRef.state)
What's this about?

2018-06-28 16:46 UTC, tudor-malene commented on core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
> +    @Throws(TransactionBuildingException::class)
You're right. The Java compiler will complain.

Should I create a deprecated version of the method that somehow wraps the TransactionBuildingException into a MissingContractAttachments?

I think it makes much more sense to declare it throws a generic "TransactionBuildingException" to cover more future cases.

2018-06-28 16:58 UTC, tudor-malene commented on core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
> +        // If they are hand-crafted with the HashAttachmentConstraint -for some reason-, then use that hash
Ok. I'll add more.

Something like:

This method is called before the AutomaticConstraint on output states is transformed into a real constraint.

So, the only case ( so far) that can really affect the contract jar selection is manually setting a specific HashConstraint on an output state. The other constraints won't point to an actual jar version, but to some rules that the jar needs to obey.

I can't think of any other case when you wouldn't want to use the latest jar that you installed on the node when you build the transaction.

2018-06-28 17:02 UTC, tudor-malene commented on core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
> -        inputsWithTransactionState.add(stateAndRef.state)
That's the private list of statesAndRefs.

I thought I needed the  stateAndRef (not just the state), but I didn't in the end.

I left it as it makes more sense then to just store the state, and then manually pair them if you need them.

2018-06-30 14:17 UTC, mikehearn commented on core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
> +    @Throws(TransactionBuildingException::class)
It does make more sense, the question is what's the best way to migrate the API. Maybe we should make TransactionBuildingException unchecked?

2018-07-02 10:10 UTC, tudor-malene commented on core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
> +    @Throws(TransactionBuildingException::class)
I thought about that, but then it couldn't extend from FlowException any more ( which extends Exception).
But, I'm not 100% sure it actually needs to be a FlowException as it would be (probably) mostly recoverable.

2018-07-17 14:25 UTC, mikehearn commented on core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
> +    @Throws(TransactionBuildingException::class)
It seems you went for deprecating this rather common function here. I'd rather we just made the new exception unchecked. If we do introduce a new function it should be something like `toWireTransaction2` rather than "new" on the end (then if we need to change it again it'd become NewNew etc)

2018-07-17 14:29 UTC, mikehearn requested changes
Can we undo the toWireTransactionNew thing? It hardly seems worth it just to enable a new exception to be checked.

2018-08-20 16:15 UTC, tudor-malene commented
This has been superseded by https://github.com/corda/enterprise/pull/1335

2018-08-20 16:15 UTC, closed without merging