Tudor fix hibernate observer
corda/corda pull request #3689
Opened 2018-07-25 11:14 UTC by tudor-malene

WIP
https://r3-cev.atlassian.net/browse/CORDA-1847

2018-07-25 15:53 UTC, josecoll submitted a review, later dismissed
Code changes look good to me!
Just need to sort out the failing tests.

2018-07-26 08:01 UTC, josecoll commented
@tudor-malene did you get to the bottom of why certain tests only work when you switch the driver `startNodesInProcess` flag from `true` to `false?`

2018-07-26 08:13 UTC, josecoll requested changes
Maybe we push this PR out quickly to the customer to validate it fixes the support ticket problem, and then re-visit certain failing tests.

2018-07-26 08:13 UTC, josecoll commented on node/src/test/kotlin/net/corda/node/services/schema/PersistentStateServiceTests.kt
> +@Ignore("needs reworking")
switched off?

2018-07-26 08:13 UTC, josecoll commented on confidential-identities/src/test/kotlin/net/corda/confidential/IdentitySyncFlowTests.kt
> +                cordappPackages = listOf("net.corda.finance.contracts.asset", "net.corda.finance.schemas"),
I am curious to know how these tests worked before without the additional schema package specification.
Do we need to document this more clearly in the docs now?

2018-07-26 08:13 UTC, josecoll commented on finance/src/integration-test/kotlin/net/corda/finance/flows/CashSelectionTest.kt
> +        driver(DriverParameters(startNodesInProcess = false, extraCordappPackagesToScan = listOf("net.corda.finance"))) {
Need to get to the bottom of why these tests no longer work "in process".

2018-07-26 08:13 UTC, josecoll commented on finance/src/test/kotlin/net/corda/finance/contracts/CommercialPaperTests.kt
> +    private val ledgerServices = MockServices(listOf("net.corda.finance.schemas"), megaCorp, miniCorp)
ditto - seems like we need to specify schema packages more rigorously now.

2018-07-26 08:13 UTC, josecoll commented on node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt
> +                persistentStateService.persist(vaultUpdate.produced)
What is the impact of this method call throwing an exception? (which I think was the origin of the support ticket)

2018-07-26 08:13 UTC, josecoll commented on node/src/test/kotlin/net/corda/node/services/persistence/HibernateConfigurationTest.kt
> +        val schemaService = NodeSchemaService(extraSchemas = setOf(CashSchemaV1, SampleCashSchemaV1, SampleCashSchemaV2, SampleCashSchemaV3, DummyLinearStateSchemaV1, DummyLinearStateSchemaV2, DummyD
Seems like we have removed some default package classpath scanning somewhere.

2018-07-26 08:56 UTC, tudor-malene commented on node/src/test/kotlin/net/corda/node/services/schema/PersistentStateServiceTests.kt
> +@Ignore("needs reworking")
Yes, it is very bound to the observable implementation.
Needs to be rewritten

2018-07-26 08:58 UTC, tudor-malene commented on confidential-identities/src/test/kotlin/net/corda/confidential/IdentitySyncFlowTests.kt
> +                cordappPackages = listOf("net.corda.finance.contracts.asset", "net.corda.finance.schemas"),
I realised it's the same issue I had when I added liquibase to ent, and tables were not being created.
It's because in that observer, a session factory was created using the classpath, so it didn't rely on these packages

2018-07-26 08:59 UTC, tudor-malene commented on finance/src/integration-test/kotlin/net/corda/finance/flows/CashSelectionTest.kt
> +        driver(DriverParameters(startNodesInProcess = false, extraCordappPackagesToScan = listOf("net.corda.finance"))) {
Yes, it's really odd.

2018-07-26 09:15 UTC, tudor-malene commented on node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt
> +                persistentStateService.persist(vaultUpdate.produced)
it's less likely to throw an error now, as there are no more database operations.

My eventual plan is to completely get rid of this observable, and use the events that Hibernate generates.

2018-07-26 09:37 UTC, josecoll approved these changes
OK - lets get this fix out there and tested in the field!!!

2018-07-26 09:50 UTC, tudor-malene commented on finance/src/integration-test/kotlin/net/corda/finance/flows/CashSelectionTest.kt
> +        driver(DriverParameters(startNodesInProcess = false, extraCordappPackagesToScan = listOf("net.corda.finance"))) {
So it seems that these were flaky unrelated to this change, and @szymonsztuka removed them as a patch.

2018-07-26 14:46 UTC, rick-r3 commented on node/src/main/kotlin/net/corda/node/services/schema/PersistentStateService.kt
> +        statesAndRefs.forEach {
The idea behind the dynamic session factories was to allow dynamic loading of cordapps and their schemas.  Do we lose the ability here?  

I think you can't add new entities to an already built session factory, but maybe I'm wrong.  

Admittedly I think the use of the dynamic schemas has fallen off the vault query end (or maybe it wasn't ever there).

Worth thinking about anyway.

2018-07-26 14:58 UTC, tudor-malene commented on node/src/main/kotlin/net/corda/node/services/schema/PersistentStateService.kt
> +        statesAndRefs.forEach {
I don't think that it is really possible to do that in a true enterprise scenario.
There's tables that need to be created, indexes, etc. Applications might not have rights to create tables.

This is consistent with the ``QueryableState`` design, which assumes that these cordapps can be dynamically loaded and persisted.
My opinion is that we should revisit this assumption.

2018-08-06 08:13 UTC, vkolomeyko commented
Apologies if I missed update on this work, but are we still planning to have this PR merged?

2018-08-06 09:33 UTC, tudor-malene commented
@vkolomeyko , This was the reference PR. Unfortunately on the wrong branch.
I kept it for reference, as all the comments were here.
I'll close it as soon as I finalise the last backport of thi.

2018-08-13 16:28 UTC, vkolomeyko commented
Thanks @tudor-malene.
Would you know what would be the correct branch for these changes?
Has PR targeting correct branch been created?

2018-08-13 16:31 UTC, tudor-malene commented
@vkolomeyko, the winning branches were:

https://github.com/corda/corda/pull/3726
https://github.com/corda/corda/pull/3694

2018-09-03 17:01 UTC, tudor-malene commented
PR against wrong branch.

2018-09-03 17:01 UTC, closed without merging