Rog data distribution groups
corda/corda pull request #3763
Opened 2018-08-09 13:45 UTC by roger3cev

Added a new module for data distribution groups and worked on a PoC. This PR is just to review the PoC. Do not merge!

2018-08-09 13:58 UTC, dazraf commented
will there be permissioning / voting for adding a member to the d-group?

2018-08-09 14:17 UTC, roger3cev commented
Currently there is only support for existing members of a group to invite new members. However, we are open to other approaches as invite only doesn't cater for all scenarios.

For the time being only the founder of the group can write to it. The founder can add readonly members to the group and those readonly members can add other readonly members.

For the MVP, nodes will be able to invite others as read/write members of the group.

2018-08-10 13:58 UTC, roger3cev commented
@dazraf currently there's no support for leaving :) However, if I were to add support and the founder left, then the group would be left to be useless as no-one else can add transactions to it! This might be desired behaviour depending on the rationale for the group. Probably more correctly though, if the only read/write member of the group leaves, then an operation should propagate through the group to exit all of the states representing that group.

Re: proposal flows. Yes, using an abstraction here makes sense. However I'm not sure how voting would work with the current construct. group members are only aware of those who invited them and those they invited. There's no omniscient member who can see all other members. Collecting votes would be problematic. We'd need to build out flows similar to the ones we used in project Ubin. It _can_ be done but will take a fair bit of effort. 

What do you mean by:
> Also, we're wondering if it would be possible for the datagroup to be a synthetic AbstractParty ...

Cheers

2018-08-13 08:51 UTC, rick-r3 commented on data-distribution-groups/src/main/kotlin/net/corda/groups/contracts/Group.kt
> +class Group : Contract {
Some thoughts:

1. Make this abstract / open
2. Have a single subclass for now which is `SingleOwnerGroupWithNoLeave`
3. Add a `Leave` command, and leave flows.  Probably also want a `ChangeRole` or some such for making people owners or demoting owners.  All should be governed by the `verify`  of the contracts and in the one (current) implementation subclass, could throw unsupported.
4. This means custom "group" contracts can govern membership as they see fit, without needing any new flows, I think.  

Thus the concept and flows are defined, but new membership / governance models can sprout from new contracts.

WDYT?

2018-08-13 13:59 UTC, mikehearn requested changes
I haven't read the code, just commented on the readme file.

I wonder if before we proceed with this we should tackle storing non-participatory states in the vault properly? That would fix issues with observer states and this too. Feels like a prereq.

2018-08-13 13:59 UTC, mikehearn commented on data-distribution-groups/src/main/kotlin/net/corda/groups/README.md
> +* Groups are stored as ContractStates in the vault.
should they be? which features of states do they need?

2018-08-13 13:59 UTC, mikehearn commented on data-distribution-groups/src/main/kotlin/net/corda/groups/README.md
> +  write to it. Only the founder can add transactions to the group.
Can we extend this to "anyone with the key can write"? To allow explicitly for the possibility of key sharing?

2018-08-13 13:59 UTC, mikehearn commented on data-distribution-groups/src/main/kotlin/net/corda/groups/README.md
> +* Inviting the same node twice can happen but doesn't have any impact
Should such an invite flow throw an exception?

2018-08-13 13:59 UTC, mikehearn commented on data-distribution-groups/src/main/kotlin/net/corda/groups/README.md
> +* There is currently no persistence of transaction which have been sent
?

2018-08-13 13:59 UTC, mikehearn commented on data-distribution-groups/src/main/kotlin/net/corda/groups/README.md
> +* Only signed transactions can be added to a group.
Isn't this part implied by the above statement that the founder signs the tx?

2018-08-13 16:54 UTC, roger3cev commented on data-distribution-groups/src/main/kotlin/net/corda/groups/README.md
> +* Groups currently have a name and key. The name is just a string.
The idea behind name was so that users can choose a group by a human readable identifier. The public key is the unique identifier.

2018-08-13 16:55 UTC, roger3cev commented on data-distribution-groups/src/main/kotlin/net/corda/groups/README.md
> +* Groups are stored as ContractStates in the vault.
This is how we designed the obligation graph for Ubin. It worked quite well. It also allows us to re-use all the infrastructure around vault querying. The alternative is to store the data in manually generated SQL tables - requires more effort.

2018-08-13 16:57 UTC, roger3cev commented on data-distribution-groups/src/main/kotlin/net/corda/groups/README.md
> +  write to it. Only the founder can add transactions to the group.
In the design I'm writing up, key sharing is not allowed. Instead, those that are invited with read/write access will be asked to generate a key pair. The inviter will sign the newly generated public key of the invitee, thus forming a key chain back to the key of the founder of the group (which may or may not be signed by the founder's legal identity key).

2018-08-13 16:58 UTC, roger3cev commented on data-distribution-groups/src/main/kotlin/net/corda/groups/README.md
> +* Inviting the same node twice can happen but doesn't have any impact
It can do!

2018-08-13 16:58 UTC, roger3cev commented on data-distribution-groups/src/main/kotlin/net/corda/groups/README.md
> +* There is currently no persistence of transaction which have been sent
Whoops not sure what happened here. Persistence will be added later, as it will take a bit of work.

2018-08-13 16:59 UTC, roger3cev commented on data-distribution-groups/src/main/kotlin/net/corda/groups/README.md
> +* Only signed transactions can be added to a group.
Yes. These notes are just some initial thoughts... Probably tomorrow or Wednesday I'll follow up with a design document.

2018-08-13 16:59 UTC, roger3cev commented on data-distribution-groups/src/main/kotlin/net/corda/groups/contracts/Group.kt
> +class Group : Contract {
This is a great idea! I'll incorporate it into the design document - thanks!

2018-08-17 12:40 UTC, mikehearn commented on data-distribution-groups/src/main/kotlin/net/corda/groups/README.md
> +* Groups currently have a name and key. The name is just a string.
Sure, maybe "Title" then? The word "name" has quite a few connotations in programming that don't apply for the way this field is actually used.

2019-01-09 16:34 UTC, vkolomeyko commented
Last comment on this PR is from 13-Aug-2018 and the branch is in conflicted state.
Is there still hope to have this PR merged?

2019-01-09 17:10 UTC, roger3cev commented
@vkolomeyko It's ok we can close this PR - it was raised just so someone can review it.

2019-01-09 17:10 UTC, closed without merging