Replace @return with Returns due to rendering issues.
corda/corda pull request #4183
Opened 2018-11-07 10:57 UTC by kchalkias

Annotation only kdocs/javadocs don't render that great.
See https://docs.corda.net/head/codestyle.html#comments (second bullet in the second list).

2018-11-12 15:49 UTC, mikehearn commented
So technically the guidance is for kdocs/javadocs that *only* contain a `@return` tag. Not all uses of it! Was this PR much work to create? Is it easy to restrict the script to only looking at Kdocs that are exclusively `@return` tags i.e. match against `/** (\n +*|) @return` or something like that.

2018-11-12 15:49 UTC, mikehearn requested changes

2018-11-12 15:49 UTC, mikehearn commented on core/src/main/kotlin/net/corda/core/crypto/Crypto.kt
> +     * true if verification passes or throw exception if verification fails.
Seems "Returns" went missing here?

2018-11-12 15:49 UTC, mikehearn commented on core/src/main/kotlin/net/corda/core/crypto/Crypto.kt
> +     * Returns true if verification passes or throws an exception if verification fails.
Does text that appears after `@param` work right? It's a bit unusual but I know this was done automatically so no problem.

2018-11-12 15:56 UTC, kchalkias commented
@mikehearn It was originally automatic yes, but then I had to rewrite/rephrase a few of them (fixed some typos while checking as well, missing periods etc), so eventually it was mixed work and did it while waiting for CryptoService TC tests.
I will change according to your recommendation, during another TC test round :)

2018-11-13 18:37 UTC, kchalkias commented
Back to you @mikehearn

2019-03-22 09:49 UTC, shamsasari commented
Unfortunately this has been neglected. Best to close and retry later.

2019-03-22 09:49 UTC, closed without merging