CORDA-2280 migration from whitelist constraint to signature constraint
corda/corda pull request #4596
Opened 2019-01-16 17:04 UTC by szymonsztuka

WIP

2019-01-17 11:52 UTC, tudor-malene requested changes
This is tricky logic.

What we want to do is:

- If the selected attachment is whitelisted and signed. 
- And if any of the input states have the WhitelistConstraint.
- Then the AutomaticPlaceHolderConstraint of the corresponding output states should be replaced with the SignatureConstraint(all_signer_from_the_jar)

I would just modify the last condition from `attachmentConstraintsTransition` to reflect the above conditions.

Also maybe logging some info : "Automatically transitioned the state.. to the SignatureConstraint".

2019-01-17 11:54 UTC, josecoll commented
>> If the selected attachment is whitelisted and signed.
It cannot be both as that is not a valid scenario.

2019-01-17 11:56 UTC, josecoll requested changes

2019-01-17 11:56 UTC, josecoll commented on node/src/integration-test/kotlin/net/corda/contracts/SignatureConstraintVersioningTests.kt
> +    private val baseUnsinded = cordappWithPackages(MessageState::class.packageName, DummyMessageContract::class.packageName)
typo: **baseUnsigned**

2019-01-17 11:56 UTC, josecoll commented on node/src/integration-test/kotlin/net/corda/contracts/SignatureConstraintVersioningTests.kt
> +    private fun `use states to create transaction with newer cordapp`(cordapp: CustomCordapp, newCordapp: CustomCordapp, whiteListedCordapps : List<CustomCordapp>): StateAndRef<MessageState>? {
please give this a conventional functional name.

2019-01-17 11:56 UTC, josecoll commented on node/src/integration-test/kotlin/net/corda/contracts/SignatureConstraintVersioningTests.kt
> +    //TODO the test actually doesn't check that signature constraint was used for the second transaction
why not?

2019-01-17 11:58 UTC, josecoll commented on core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
> +        attachmentToUse.signerKeys.isNotEmpty() && constraints.all { it is WhitelistedByZoneAttachmentConstraint } -> makeSignatureAttachmentConstraint(attachmentToUse.signerKeys)
is this strictly true?
what happens when we have a mixture of HASH and CZ constrained input states?

2019-01-17 12:07 UTC, tudor-malene commented
> > > If the selected attachment is whitelisted and signed.
> > > It cannot be both as that is not a valid scenario.

why not? 
How would this work otherwise?

2019-01-17 12:21 UTC, josecoll commented
If the selected attachment is whitelisted and signed.
It cannot be both as that is not a valid scenario.

why not?
How would this work otherwise?

2019-01-17 12:23 UTC, josecoll commented
> > > > If the selected attachment is whitelisted and signed.
> > > >It cannot be both as that is not a valid scenario.

>>why not? 
>>How would this work otherwise?

Why do you need to add a signed version of the same JAR to the CZ whitelist?

2019-01-17 12:40 UTC, tudor-malene commented
> > > > > If the selected attachment is whitelisted and signed.
> > > > > It cannot be both as that is not a valid scenario.
> 
> > > why not?
> > > How would this work otherwise?
> 
> Why do you need to add a signed version of the same JAR to the CZ whitelist?
> Also could you explain the process from an operational perspective (afaik none of this is documented)

It was covered in the design document.

2019-01-17 12:41 UTC, josecoll commented
@tudor-malene end users are not going to read your design document.
These fundamental changes to operational behaviour need to be documented on the Doc website.
Please raise a JIRA to document this or add to this PR.

2019-01-17 12:42 UTC, tudor-malene commented
> @tudor-malene end users are not going to read your design document.
> These fundamental changes to operational behaviour need to be documented on the Doc website.
> Please raise a JIRA to document this or add to this PR.

Already raised.

2019-01-17 12:43 UTC, josecoll commented
Whats the JIRA please?

2019-01-17 14:40 UTC, szymonsztuka commented on node/src/integration-test/kotlin/net/corda/contracts/SignatureConstraintVersioningTests.kt
> +    //TODO the test actually doesn't check that signature constraint was used for the second transaction
I didn't find a way yet to easy check what a contract constraint was used from RPC level. I would need to run JDBC query.

2019-04-26 17:33 UTC, shamsasari commented
Closing this PR as it's not superseded by #5053.

2019-04-26 17:33 UTC, closed without merging