CORDA-2543 object graph traversal
corda/corda pull request #4698
Opened 2019-01-31 16:39 UTC by r3domfox

Per [CORDA-2543](https://r3-cev.atlassian.net/browse/CORDA-2543), introduce an `ObjectGraphTraverser` which uses the type analysis from the serialization framework to traverse an object graph in depth-first order, emitting a `Sequence` of objects in the graph:

```kotlin
val peopleInObjectGraph = ObjectGraphTraverser.traverse(object) { it is Person }.toList()
```

To support code which must run in `core`, the `LocalTypeModel` code and related classes have been separated from the `serialization` context and now stand alone, in `net.corda.core.internal.reflection`.

The remaining classes in `serialization.amqp` have been re-organised with some additional packages being introduced - the aim was to clarify the dependencies between groups of classes and eliminate cyclic dependencies between packages, but some cycles remain which it would be troublesome to remove.

By re-implementing the very small part of `TypeToken` that is actually used in `serialization`, we remove the dependency on `TypeToken` from both `core` and `serialization`.

2019-01-31 17:56 UTC, shamsasari requested changes
Can you wire this up to `StatePointerSearch`. There's also `CordaSerializableBeanSerializerModifier` that can benefit from this I think.

Further, this is a big PR and I see that some classes have been moved into their own files. Can you keep such changes to a minimum please to reduce the amount of changes and to keep the git history. You can always do the refactoring in a separate PR.

2019-01-31 17:56 UTC, shamsasari commented on core/src/main/kotlin/net/corda/core/internal/reflection/PropertyReader.kt
> +@KeepForDJVM
I thought reflection is disabled in the DJVM. @chrisr3 ?

2019-02-01 09:08 UTC, chrisr3 commented on core/src/main/kotlin/net/corda/core/internal/reflection/PropertyReader.kt
> +@KeepForDJVM
Corda's `djvm` module will rewrite the bytecode to replace all `java.lang.reflect.*` and `java.lang.invoke.*` methods with stubs that throw `RuleViolationError` inside Avian. So this code won't work inside the sandbox.

The `jdk8u-deterministic/jdk/jre/lib/rt.jr` is still including them at the moment, though - for reasons I cannot remember right now.

2019-02-01 09:50 UTC, r3domfox commented on core/src/main/kotlin/net/corda/core/internal/reflection/PropertyReader.kt
> +@KeepForDJVM
Object graph traversal, used in `StatePointerSearch`, will rely on reflection to traverse the object graph, whether it uses this code or not.

2019-02-01 15:31 UTC, r3domfox commented
Wiring up into `StatePointerSearch` is now done, with a couple of additional tests indicating the behaviour around calculated properties. @roger3cev, could you maybe kick the tires on `StatePointerSearch` and its associated tests and confirm whether we have the right behaviour for all the cases we care about?

2019-02-05 09:42 UTC, roger3cev commented
@r3domfox i'll have a look today - cheers!!

2019-02-11 10:13 UTC, shamsasari reviewed
You have a merge conflict. Otherwise this is looking ready to merge.

2019-02-11 10:13 UTC, shamsasari commented on core/src/test/kotlin/net/corda/core/internal/reflection/PropertyEnumeratorTests.kt
> +        data class Middle(val value: String, val bottoms: List<Bottom>)
Can you add separate simple test cases for List and Map

2019-02-11 13:36 UTC, r3domfox commented on core/src/test/kotlin/net/corda/core/internal/reflection/PropertyEnumeratorTests.kt
> +        data class Middle(val value: String, val bottoms: List<Bottom>)
Done.

2019-03-18 13:45 UTC, closed without merging