tidy up documentation around documentation building now that it's dockerized
corda/corda pull request #4733
Opened 2019-02-11 15:27 UTC by roastario

2019-02-11 15:30 UTC, anthonykeenan requested changes
Other than the one thing it's fine

2019-02-11 15:30 UTC, anthonykeenan commented on docs/source/building-the-docs.rst
> -In order to build the documentation you will need a development environment set up as described under :doc:`building-corda`.
I think you still need this line, I mean, you need Java and stuff still don't you?

2019-03-21 18:16 UTC, josecoll commented
Seems like we forgot to merge this for Corda 4.
@fenryka ^^^

2019-04-26 17:34 UTC, shamsasari commented
What's the status of this PR?

2019-05-03 09:56 UTC, closed without merging