CORDA-2707 defer exceptions to deserialisation-time
corda/corda pull request #4856
Opened 2019-03-06 13:44 UTC by r3domfox

We allow serializers to be generated in the presence of non-deserialisable types (types that aren't on the receiver's classpath, and which we don't want to carpent up), and defer throwing exceptions to when a non-deserialisable value is required in the construction of a new value. This enables the evolution serialiser to work in the case that the original type has a field of a type that is no longer available in the new type: if the field itself has been removed, then it doesn't matter if we haven't carpented up a type to deserialise its value into.

If carpentry is enabled, then all missing types will be carpented, whether they are used or not, as it's too early in the deserialisation pipeline to know exactly which types will be required.

Because `DeserialisationInput.readObjectOrNull` can now return a value of type `NonDeserialisable`, it is up to the consumer of that value to signal whether the presence of non-deserialisation values means that deserialisation cannot be completed. This enables `ObjectBuilder`s to consume such values and throw them away, when they are not needed to construct objects, typically because they are assigned to a property that the object under construction no longer possesses. Other serialisers which may have to handle a `NonDeserialisable` value are `CollectionSerializer`, `MapSerializer` and `ArraySerializer`, which have been modified to fail if any of the elements in the collection is non-deserialisable. All three are covered by unit tests.

There is a risk that other custom serialisers which use `DeserialisationInput.readObjectOrNull` to obtain part-values during deserialisation will fail with a `ClassCastException` when given `NonDeserialisable`, if they have not been explicitly modified to handle this case. Any custom deserialiser which accepts part-values of type `Any` will not fail at all, but may end up constructing an object containing `NonDeserialisable` values, which may cause trouble further down the line. One possible way to mitigate this would be to introduce a method `DeserialisationInput.unsafeReadObjectOrNull` to be used only by those serialisers which explicitly handle `NonDeserialisable` values, and have `readObjectOrNull` throw an exception rather than ever returning a `NonDeserialisable`. However, as `readObjectOrNull` is already marked as `internal`, it is unlikely that ad hoc use will occur.

Deserialisation should fail if data-loss protection is enabled and a non-null value of a non-deserialisable type is received for a property that no longer exists, but succeed if the value passed is null. The `NonDeserialisable` type represents the non-null value case, while `null` is still the null value. A test has been added to `EvolvabilityTests` which exercises this scenario.

2019-03-08 23:04 UTC, fenryka requested changes
In the spirit of "Changes gooing forward for the betterment of Corda" I wonder if we shouldn't put this (and my) change behind a flag. We're changing behaviour we *might* want to turn off in the future. Plus, it's a good testing ground  for adding such "feature" flags

Change Log?

Otherwise LGTM!

2019-03-09 08:44 UTC, gendal commented
good point @fenryka ! We keep saying we need to protect the codebase with more features we can turn off through a flag.  I've never 100% understood how it would work in practice... does that mean we need to build with it on and off from now on to check both codepaths work?  or is it simpler than that?  I'm all for proving it out here if it makes sense

2019-03-15 13:05 UTC, mikehearn requested changes

2019-03-15 13:05 UTC, mikehearn commented on serialization/src/main/kotlin/net/corda/serialization/internal/model/TypeLoader.kt
> + * @param mustCarpentMissingTypes Controlled by feature flag DISABLE-CORDA-2707 - if this flag is set, then a [ClassNotFoundException]
Seems this param was taken out.

2019-03-15 14:11 UTC, mikehearn submitted a review, later dismissed

2019-03-26 10:30 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/context/FeatureFlag.kt
> +object FeatureFlag  {
I think we should put this inside the `internal` package of `core` as an indicator it's for R3 not consumers of `core` (and eventually we will block access).

2019-03-26 10:30 UTC, rick-r3 commented on serialization/src/main/kotlin/net/corda/serialization/internal/amqp/CollectionSerializer.kt
> +            if (item is NonDeserializable) throw NotSerializableException("Collection item $index is non-deserializable ${item.descriptor}")
Why do you check this return value after each call to `readObjectOrNull()`, rather than checking before return from `readObjectOrNull()` ?

2019-03-26 10:42 UTC, r3domfox commented on serialization/src/main/kotlin/net/corda/serialization/internal/amqp/CollectionSerializer.kt
> +            if (item is NonDeserializable) throw NotSerializableException("Collection item $index is non-deserializable ${item.descriptor}")
Because `readObjectOrNull` is used in cases where we don't mind if the result is `NonDeserializable` (or don't yet know if we mind - it gets passed forward to an object builder which might or might not just throw it away):

> A new type, `NonDeserialisable`, is introduced to represent a value in the serialisation stream that could not be deserialised. Most clients of `DeserialisationInput` use `DeserialisationInput.read` to obtain deserialised values, and this method fails with an exception rather than returning a `NonDeserialisable`. However, serialisers which obtain part-values from the stream and use them to build a result call into `DeserialisationInput.readObjectOrNull` instead, and this method will return a value of type `NonDeserialisable` if there is no serialiser available to read the type in the stream.

2019-03-26 17:51 UTC, r3domfox commented on core/src/main/kotlin/net/corda/core/context/FeatureFlag.kt
> +object FeatureFlag  {
Done.

2019-04-26 17:47 UTC, shamsasari commented
This PR is now bit-rotting.

2019-11-20 17:31 UTC, closed without merging