make StatePointerSearch allow for null packages (like primitives)
corda/corda pull request #4961
Opened 2019-03-29 09:34 UTC by roastario

backport changes to allow StatePointerSearch to handle primitives.

Should we REALLY be doing this graph search of the entireTX without the user requesting it? There are some usecases where they might not want to attach all statepointer states ..

2019-03-29 09:36 UTC, roger-that-dev approved these changes
Agree that we should make this optional - we can introduce a flag on transaction builder methods. Perhaps the default is to include reference states but developers can specify not to.

2019-04-11 16:50 UTC, mikehearn requested changes

2019-04-11 16:50 UTC, mikehearn commented on core/src/main/kotlin/net/corda/core/internal/StatePointerSearch.kt
> +    //interesting - this seems to do a graph search of EVERY FIELD IN EVERY STATE in the TX
Can we put design discussion into a PR or mailing list thread rather than comments please.

Also note the comment style in the code style guide: https://docs.corda.net/codestyle.html#comments

2019-04-11 16:50 UTC, mikehearn commented on core/src/main/kotlin/net/corda/core/internal/StatePointerSearch.kt
> +    //interesting - this seems to do a graph search of EVERY FIELD IN EVERY STATE in the TX
Can we put design discussion into a PR or mailing list thread rather than comments please.

Also note the comment style in the code style guide: https://docs.corda.net/codestyle.html#comments

2019-05-03 09:56 UTC, closed without merging