ENT-3322: Improved error reporting in interactive shell when an error occurs after a ctor is matched.
corda/corda pull request #4969
Opened 2019-04-01 11:35 UTC by adelel1

The interactive shell implementation will try to match the passed in flow start argument list with each flow constructor in turn. Apart from the matching constructor there will be either too few or too many arguments specified, or missing parameters. All these errors are accumulated into a list.

If the matching constructor also fails for a legitimate reason, e.g. the Party cannot be found then this error is also added to the cumulative list and the whole list is sent back to the user and displayed in the shell. This is not right, only the errors related to the matching constructor should be displayed. This is now done in this PR, if there is no matching constructor then all errors are returned as before.

Note that we do not support two matching constructors with the same parameter names but different only by type. However the previous implementation would allow this. The first matching constructor that succeeded would be used, previous matching constructors that failed would be ignored. In this implementation if the first matching constructor fails then the error is reported.

2019-04-02 09:09 UTC, chrisr3 commented on tools/shell/src/main/kotlin/net/corda/tools/shell/InteractiveShell.kt
> +        var constructorFound = false
This `Boolean` bothers me because it makes this function's control-flow a lot less obvious. This function has three parts:
- selecting the correct constructor
- parsing the constructor arguments
- invoking this constructor with the arguments

Unfortunately, this is being obscured by this "One Try-Catch Block To Rule Them All!", which is really just handling  `StringToMethodCallParser.UnparseableCallException` and its descendants. I'm sure that this can be simplified, e.g.
```kotlin
val nameTypeList = run {
    val allErrors = ArrayList<String>()
    for (ctor in clazz.constructors) {
        try {
            // etc
            return@run nameTypeList
        } catch (...) {
            // etc
        }
    }
    throw NoApplicableConstructor(allErrors)
}

try {
    val args = parser.parseArguments(clazz.name, nameTypeList, inputData)
    return invoke(clazz, args)
} catch (...) {
    throw NoApplicableConstructor(...)
}
```
The problem (of course) is these multi-layered lambdas for generating all of the error messages! Is there any way that you can untangle this function please?

2019-04-03 09:30 UTC, adelel1 commented on tools/shell/src/main/kotlin/net/corda/tools/shell/InteractiveShell.kt
> +        var constructorFound = false
Hi,
Points noted. I have simplified code. Ready for your review.
Thanks, Adel

2019-04-03 23:11 UTC, chrisr3 requested changes
Nice; small things though.

2019-04-03 23:11 UTC, chrisr3 commented on tools/shell/src/main/kotlin/net/corda/tools/shell/InteractiveShell.kt
> +                                            om: ObjectMapper) : List<Pair<String, Type>> {
This function doesn't use its `om` parameter, so can you remove it please?
But the line defining this function's prototype is a bit _long_, so can you reformat it too? The `runFlowFromString` function is a good example.

2019-04-04 08:39 UTC, adelel1 commented on tools/shell/src/main/kotlin/net/corda/tools/shell/InteractiveShell.kt
> +                                            om: ObjectMapper) : List<Pair<String, Type>> {
All updates done, ready for your review.
Thanks,

2019-04-05 08:37 UTC, adelel1 commented
Ready for review

2019-04-05 10:14 UTC, chrisr3 approved these changes

2019-04-12 10:13 UTC, merged