Willh confidential identities no cert
corda/corda pull request #5064
Opened 2019-04-26 17:35 UTC by willhr3

- Stripped out some of the certificates dependencies from confidential identities
- Created a flow for requesting a new public key 
- Keys and Parties are stored in SignedPublicKey map 

Still to do:
- Share keys flow
- Sync keys flow

2019-04-29 12:09 UTC, roger-that-dev requested changes
Looks good so far - definitely going in the right direction I think! Added some points around the request key flows.

Some other bits we'll need to make sure we have addressed:
1. This PR is based upon @roastario 's initiate flow with abstract party branch. We'll want to merge this is before any of this work.
2. The identity service changes are also in this PR, I think we should split them out into a separate PR for ease of review. We should also get that PR merged before any of the work on confidential identities is merged in.
3. In the identity service we'll need to check that migration from the old certificates based identity service to the new simpler service doesn't lose any of the mappings and properly migrates the existing mappings over to the new approach. This is always more difficult to get right than you first think.
4. With all of this stuff we'll need to update the documentation and add kDocs to all of the new APIs. For now don't worry about this as it's just a PoC.
5. We'll need to update the api-current.txt file as we've made some API changes to Corda in this PR (otherwise the CI checks won't pass).

Next steps: once we can fully demonstrate this working then we can set about putting together a design doc for a design review board, with the lessons learnt from building this.

Good work - cheers!

2019-04-29 14:03 UTC, willhr3 commented on confidential-identities/build.gradle
> +    cordaCompile (group: 'net.corda', name: 'corda-node', version: '5.0-SNAPSHOT')
We end up with a circular dependency when you use that which is strange.

2019-05-01 16:09 UTC, roger3cev commented on node/src/main/kotlin/net/corda/node/services/identity/PersistentIdentityService.kt
>              return AppendOnlyPersistentMap(
would be ncie to see if we can remove all the cert stuff, then deprecate all the cert based methods. We'll also need to deal with migration from the cert based mapping to the non cert based mapping.

2019-07-30 16:05 UTC, roger3cev commented
Let's close this PR now. Cheers!

2019-07-30 16:05 UTC, closed without merging