CORDA-2087 First draft to document contract best practices
corda/corda pull request #5106
Opened 2019-05-07 15:32 UTC by tudor-malene

This PR attempts to document security related best practices for writing contracts and also comes with (secure?) reference code .

2019-05-07 15:44 UTC, gendal commented on docs/source/contract-verification-best-practices.rst
> +E.g: When redeeming a commercial paper, ensure that there exists a transition moving enough Cash.
... and that there is no possibility that another contract, maybe one you don't even know about, also thinks this Cash is being moved on their behalf. For example, you may choose to require that the Cash movement contains a memo/reference field that matches a unique identifier for the commercial paper contract.

2019-05-07 15:49 UTC, tudor-malene commented on docs/source/contract-verification-best-practices.rst
> +E.g: When redeeming a commercial paper, ensure that there exists a transition moving enough Cash.
Actually I was planning to write a Transition based Cash implementation as well. ( same as I did for CP)

And reference the Cash Move Transition from the CP Move Transition (somehow)

I thought it's best to get some feedback on this approach first.

Adding a field to the state is another way to do it, indeed.

2019-05-07 15:50 UTC, gendal commented on docs/source/contract-verification-best-practices.rst
> +E.g: When redeeming a commercial paper, ensure that there exists a transition moving enough Cash.
excellent. and yeah.. I'm not actually sure what the best approach actually is.  could be worth pinging Roger to see how (if) he solved it in the corda settler? same issue there with obligations I guess?

2019-05-07 16:05 UTC, tudor-malene commented on docs/source/contract-verification-best-practices.rst
> +E.g: When redeeming a commercial paper, ensure that there exists a transition moving enough Cash.
I've always felt this ultra-explicit transition based approach is the way to go for contract code.

If all Commands in a transaction declare what states they control there would be no more potential for ambiguity as the checks could be performed by the core.

That reduces the  problem to verifying individual transitions and maybe identifying other transitions that need to happen.

For example, Cash could have this sort of code: `MoveTransition(.., val paysFor:Int /*= the id of some other transition*/)` 

If an attacker tries to build a transaction and pay with the same cash for 2 completely different things, one of those transitions would fail as `paysFor` would point to the other one.

@roger3cev , wdyt?

2019-05-09 13:19 UTC, tudor-malene commented on docs/source/contract-verification-best-practices.rst
> +E.g: When redeeming a commercial paper, ensure that there exists a transition moving enough Cash.
@gendal, I've updated the sample .

2019-05-09 15:30 UTC, gendal commented on docs/source/contract-verification-best-practices.rst
> +E.g: When redeeming a commercial paper, ensure that there exists a transition moving enough Cash.
thanks...  I'm probably not the right person to review that though (Except to comment that the file structure ("best practice" versus, say, "good practice") is a hostage to fortune :)

2019-05-14 15:09 UTC, mikehearn requested changes
Good stuff. Maybe discuss right at the start that checks for the _inner validity_ of types such as states, or types in states, should go into the constructors. The verify function is only needed for checking _transitions between_ valid constructions of the objects. Stress that in effect the constructors and methods of your classes are themselves transitively a part of the verify method.

2019-05-14 15:09 UTC, mikehearn commented on docs/source/contract-verification-best-practices.rst
> +Generally, after unambiguously identifying all transitions (commands and states) the contract must make sure there's no extra commands and states in the transaction.
probably worth clarifying here, no extra commands/states in the tx **for that app**. Otherwise you won't be able to combine apps due to over-strict checking

2019-05-14 15:09 UTC, mikehearn commented on docs/source/contract-verification-best-practices.rst
> +Another mandatory check for each transition is to reject a command if it is not expected. Remember, an attacker can extend your base ``Command`` class and attach that
Unless it's sealed?

2019-05-14 15:09 UTC, mikehearn commented on docs/source/contract-verification-best-practices.rst
> +Always target the latest platform version on which the CorDapp was tested. This will ensure it will be able to benefit from the latest security fixes
Maybe link here to the versioning part of the docs to ensure it's clear what "always target" means.

2019-05-14 15:09 UTC, mikehearn commented on docs/source/contract-verification-best-practices.rst
> +so make sure to only use ``open`` when there is a good reason. This is necessary to close the possibility of a an attacker to find an exploit
Sealed classes here too? Maybe also use enums in Java, as I don't think they can be extended in any way.

2019-05-14 15:09 UTC, mikehearn commented on docs/source/contract-verification-best-practices.rst
> +Make sure the ContractState class is annotated with ``@BelongsToContract``. This metadata will instruct the platform to check that a malicious
Or is a static inner class of the contract.

2019-05-15 13:53 UTC, tudor-malene commented on docs/source/contract-verification-best-practices.rst
> +Another mandatory check for each transition is to reject a command if it is not expected. Remember, an attacker can extend your base ``Command`` class and attach that
Sealing doesn't help here, unless you make the base Command class as protected.
Is that what you had in mind?

2019-05-15 14:20 UTC, tudor-malene commented on docs/source/contract-verification-best-practices.rst
> +Make sure the ContractState class is annotated with ``@BelongsToContract``. This metadata will instruct the platform to check that a malicious
I left that one out on purpose .
I think it's better people use the annotation. 
What if someone decides to refactor the contract and move the state out?
(unit tests would fail in case targetVersion >=4, but still)

2019-05-15 14:23 UTC, tudor-malene commented
Back to you @mikehearn .

What do you think about the CommercialPaper sample?
( It's another take on our default implementation that has a security issue. See comment on file)

2019-06-13 11:24 UTC, shamsasari commented
@mikehearn it seems this PR is blocked on you.

2019-06-25 16:08 UTC, mikehearn requested changes

2019-06-26 16:38 UTC, tudor-malene commented
@mikehearn , comments addressed.
Did you get a chance to look at the sample code?

2019-07-03 12:17 UTC, mikehearn commented on docs/source/contract-verification-best-practices.rst
> +Another mandatory check for each transition is to reject a command if it is not expected. Remember, an attacker can extend your base ``Command`` class and attach that
I mean the Kotlin notion of sealing.

2019-07-03 12:27 UTC, mikehearn requested changes

2019-07-03 12:27 UTC, mikehearn commented on samples/best-practice/contracts/src/main/kotlin/net/corda/finance/sample/Cash.kt
> +    @BelongsToContract(Cash::class)
This line is implicit, right? But maybe best to keep it explicit in sample code.

2019-07-03 12:27 UTC, mikehearn commented on samples/best-practice/contracts/src/main/kotlin/net/corda/finance/sample/Cash.kt
> +        override fun toString() = "${Emoji.bagOfCash}Cash($amount at ${amount.token.issuer} owned by $owner)"
Sample code shouldn't use internal classes like `Emoji` (yeah yeah, I know, my bad, it could have been public API though).

2019-07-03 12:27 UTC, mikehearn commented on samples/best-practice/contracts/src/main/kotlin/net/corda/finance/sample/Cash.kt
> +    interface Commands : CommandWithMetadata {
We should make this a sealed class, perhaps?

2019-07-03 12:27 UTC, mikehearn commented on samples/best-practice/contracts/src/main/kotlin/net/corda/finance/sample/Cash.kt
> +class Cash : Contract {
I wonder if we should rather not use Cash as a best practices example but rather, something simpler, because:

* In future we'll point people towards the tokens SDK so making your own token like this will become a worst practice rather than best practice
* It's quite complicated
* Most apps want to maintain data structures rather than fungible tokens

Maybe a simple state that cannot be split, with one or two commands to just edit the fields?

2019-07-03 12:28 UTC, tudor-malene commented on samples/best-practice/contracts/src/main/kotlin/net/corda/finance/sample/Cash.kt
> +    @BelongsToContract(Cash::class)
Yes, I left it there on purpose to illustrate the point that you should not forget about it.

2019-07-03 12:32 UTC, tudor-malene commented on samples/best-practice/contracts/src/main/kotlin/net/corda/finance/sample/Cash.kt
> +    interface Commands : CommandWithMetadata {
I need to dig more into sealing.
My (untested ) assumption was that at runtime it is just ignored, so you can't rely on it.

2019-07-03 12:47 UTC, tudor-malene commented on samples/best-practice/contracts/src/main/kotlin/net/corda/finance/sample/Cash.kt
> +class Cash : Contract {
I chose Cash and CP to test the approach on a slightly more complex scenario with inter-contract dependencies, and as a way to propose a fix to the bug in CP that allows you to redeem multiple papers of the same value for the same coins.

@roastario and @roger3cev are looking to implement this pattern into tokens, so maybe we can just reference that.
But I think this pattern of also specifying what you're paying for as metadata in the command can also be useful.

2019-07-16 09:33 UTC, mikehearn commented on samples/best-practice/contracts/src/main/kotlin/net/corda/finance/sample/Cash.kt
> +    interface Commands : CommandWithMetadata {
It's enforced by marking the constructor private, I believe. So I think it is, but am not sure - checking would be good.

2019-07-16 09:35 UTC, mikehearn commented on samples/best-practice/contracts/src/main/kotlin/net/corda/finance/sample/Cash.kt
> +class Cash : Contract {
Yes, but I don't know if the most complex scenario you could think of is a good source of reference/sample code. Many details may get lost in the weeds. 

Also:

* Sample code shouldn't have TODO comments in it or comments saying "nothing to see here".
* There are no comments anywhere calling out the security-related aspects of the sample. 

Just in general I think this sample code should be rewritten to be explicitly a teaching exercise, not a test-case scenario based on a now obsolete app. Otherwise it's going to just confuse people who try to study it thinking this is the most shining example we can give of how to write ideal Corda code, when it's not.

2019-07-16 10:28 UTC, tudor-malene commented on samples/best-practice/contracts/src/main/kotlin/net/corda/finance/sample/Cash.kt
> +class Cash : Contract {
Fair enough. I'll come up with something more simple.

But before I do that, just want to make sure that the approach is valid. Eg. splitting a Transaction into state Transitions, etc

2019-07-17 15:37 UTC, mikehearn commented on samples/best-practice/contracts/src/main/kotlin/net/corda/finance/sample/Cash.kt
> +class Cash : Contract {
Yeah, I think that works.

2019-07-17 15:53 UTC, mnesbit reviewed
This doesn't talk about composability. e.g. Cash is problematic because you can't easily encode a forex exchange due to limitations on the composability of commands. Similar consideration should be made about grouping inputs/outputs for this sort of verification.

Also, we don't talk about considerations when people add fields as it is very easy to miss validating new fields.

Is there any discussion about future proofing that we need to have here? Are there things that won't work with version2 contracts?

Should we talk about the ContractConstraints?

2019-07-17 15:53 UTC, mnesbit commented on docs/source/contract-verification-best-practices.rst
> +Contract logic will eventually run in a sandboxed deterministic environment (the Deterministic JVM), which will prevent access to any source of randomness.
This breaks Mike Ward's request not to include future promises in our docs.

2019-07-17 15:53 UTC, mnesbit commented on docs/source/contract-verification-best-practices.rst
> +    * For ownable assets added as input states make sure the owner is among the signers.
Needs to highlight that signers are on the command objects

2019-07-17 15:53 UTC, mnesbit commented on docs/source/contract-verification-best-practices.rst
> +------------------------------------------------------------
Need to clarify what forms of 'business logic' are suitable for verify which is a sealed pure function universe as opposed to things that need to be 'in flows' or which should be factored out into checks against ReferenceStates.

2019-07-17 15:53 UTC, mnesbit commented on docs/source/contract-verification-best-practices.rst
> +    * Avoid, if possible, text parsing and regex. Or dependencies that rely on that. This means for example, that it is preferable to use a typed data model
Our general guideline has been don't do XML/JSON validation at all in verify methods, instead expand into explicit Java types. If docs must be included there is also value in having them as attachments to get automatic dedupe and compression.

2019-11-20 17:37 UTC, tudor-malene commented
@mnesbit, please advice on how to proceed with this PR.
Should I close it?

2019-11-21 09:18 UTC, mnesbit commented
It would be good to have a document on this in our docs. Is anything blocking this, or is it just a lack of time and noise from the change in branching strategy?

2019-11-21 11:13 UTC, tudor-malene commented
> It would be good to have a document on this in our docs. Is anything blocking this, or is it just a lack of time and noise from the change in branching strategy?

Cheers. 
Should I finalise it then?
Should I leave the code examples? Change them?

2022-02-08 13:12 UTC, closed without merging