Design document for CI changes.
corda/corda pull request #5110
Opened 2019-05-09 12:57 UTC by roger3cev

For review before DRB on the same subject.

2019-05-09 16:00 UTC, dimosr reviewed
It seems like the accounts design is a pre-requisite for reading this design ? I struggled a bit understanding how some of the proposed APIs are supposed to be used, probably because I haven't managed to read it yet. If so, it might be worth calling it out in the beginning.

2019-05-09 16:32 UTC, roger3cev commented on docs/source/design/confidential-identities/design.md
> +are unnecessary and shouldn't happen.
I removed the bit about the node shell. What I was aiming to say is that the `principalToParties` mapping is only used for a single purpose: to provide a fuzzy search for x500names from the shell. E.g. type in `Node A` and it resolves to `O=Node A,L=London,C=GB`. It all seems a bit pointless! Regardless, we need to maintain it for backwards compatibility reasons.

2019-05-09 16:32 UTC, roger3cev commented on docs/source/design/confidential-identities/design.md
> +   should contain **all** public keys mapped to the x500 name of the node
Yup, i'll amend.

2019-05-09 16:36 UTC, roger3cev commented on docs/source/design/confidential-identities/design.md
> +4. Nodes must to be able to generate key pairs for multiple purposes; "confidential
Ah yes, this is not entirely clear. What I was trying to get at is that a node operator may generate a new key pair for multiple purposes:
1. Maybe the node operator is a single legal identity and they wish to generate a new key pair ( or confidential identity) to transact with.
2. Maybe the the node operator hosts accounts on behalf of its customers. As such, the node operator will need to generate a "Default" key pair for each account (the "account key") and further key pairs if an account wishes to use a "confidential identity" and not continually have their account key associated with their states.

2019-05-09 16:40 UTC, roger3cev commented on docs/source/design/confidential-identities/design.md
> +            val signature: DigitalSignature.WithKey
Yes, that might be a good idea. What I didn't explain but perhaps should have was that the node receiving the `SignedKeyToPartyMapping` can trivially match the `PublicKey` associated with the `DigitalSignature` to the `Party` object in the `KeyToPartyMapping` and, in turn, verify the `Party` object is bonafide via the identity service by obtaining the `PartyAndCertificate` and verifying it.

2019-05-09 16:42 UTC, roger3cev commented on docs/source/design/confidential-identities/design.md
> +Keys with no mapping must be rendered as a substring of the public key.
You might not necessarily share the key mapping with all parties in a transaction. E.g. you might be able to map half the participant's keys (because you received the signed mappings) but maybe you never received the other half's keys and thus never know who they are. This was a pattern used in project ubin for the multi-lateral netting transactions.

2019-05-09 16:44 UTC, roger3cev commented on docs/source/design/confidential-identities/design.md
> +Three sets of flows will be added:
Good question. I should address this in the PR 😄

2019-05-09 16:44 UTC, roger3cev commented on docs/source/design/confidential-identities/design.md
> +For some reason, the `BasicHSMKeyManagementService` currently depends on
Waiting for Rick to weigh in here!

2019-05-10 09:58 UTC, dimosr commented on docs/source/design/confidential-identities/design.md
> +4. Nodes must to be able to generate key pairs for multiple purposes; "confidential
thanks for clarifying. The way you phrased it here is a lot easier to grasp, it might be worth adding it to the doc.

2019-05-10 10:00 UTC, roger3cev commented on docs/source/design/confidential-identities/design.md
> +4. Nodes must to be able to generate key pairs for multiple purposes; "confidential
I will - thanks for the feedback @dimosr !

2019-05-10 10:01 UTC, dimosr commented on docs/source/design/confidential-identities/design.md
> +            val signature: DigitalSignature.WithKey
Makes sense. I think this part is a bit related with the discussion on slack yesterday around making the verification more deterministic, by embedding the mapping and prevent lookups. Anyway, a thing to discuss..

2019-05-13 08:42 UTC, willhr3 commented on docs/source/design/confidential-identities/design.md
> +For some reason, the `BasicHSMKeyManagementService` currently depends on
It looks like we won't be able to remove this dependency after all since  `KeyManagementService.freshKeyAndCert` uses the `identityService` to register CIs and our new way of doing this needs to be done from within a flow so we have decided to deprecate this method instead of removing the dependency.

2019-06-12 14:20 UTC, mikehearn requested changes

2019-06-12 14:20 UTC, mikehearn commented on docs/source/design/confidential-identities/design.md
> +it is not a public facing API. What's going on here?
Nothing in `net.corda.node` or the `node` module is public API, that's what!

2019-06-12 14:20 UTC, mikehearn commented on docs/source/design/confidential-identities/design.md
> +For some reason, the `BasicHSMKeyManagementService` currently depends on
I didn't quite follow that explanation, sorry - why does it need to use the identity service to register CIs?

2019-06-12 14:20 UTC, mikehearn commented on docs/source/design/confidential-identities/design.md
> +**Update:** It looks like we won't be able to remove this dependency after
Best to actually update the document rather than mislead the reader then spring this on them later, although, see above - I didn't really follow why this dependency can't be simplified. Is it inherent that the identity service is the only way to register a new CI?

2019-06-18 18:09 UTC, rick-r3 commented on docs/source/design/confidential-identities/design.md
> +For some reason, the `BasicHSMKeyManagementService` currently depends on
It is for performance.  Because the vault scans the public keys to decide relevancy, if it looks at key management service, it naturally always misses the cache for all the keys that do not belong to the current node (which is likely to be 50% plus, except issuance).  Scanning the identity service has a much better hit rate.  Unfortunately `filterMyKeys` is out in the open on the API of KMS.

This isn't integral to the design here, though, right?  You could still do it the existing way?

2019-06-18 18:39 UTC, rick-r3 commented on docs/source/design/confidential-identities/design.md
> +   need to be updated when new `SignedKeyToPartyMapping` are stored.
Doesn't it also continue to contain existing confidential identities generated with the now deprecated methods?

2019-06-18 18:42 UTC, rick-r3 commented on docs/source/design/confidential-identities/design.md
> +2. `verifyAndRegisterIdentity` should now only be called by the network
And the deprecated methods?

2019-06-18 18:44 UTC, rick-r3 commented on docs/source/design/confidential-identities/design.md
> +   Essentially we are trading performing an extra map lookup to storing
Doesn't this change the behaviour for existing anonymous identities?  I thought the certs chain included the anonymous key.

2019-06-19 07:12 UTC, rick-r3 commented on docs/source/design/confidential-identities/design.md
> +For some reason, the `BasicHSMKeyManagementService` currently depends on
Of course we could change the call sites, but it might be being used elsewhere.  Doesn't mean we can't deprecate and put the identity service method out into the public as replacement.

General rule that I've been going with:
1. Identity service answers questions about identity.  Who owns a key, essentially, whether it is the current node or someone else.  "Which of these keys is mine?" fits here.  
2. Key management service signs on behalf of public keys.  Quite literally key/value, if you'll excuse the pun.

2019-06-19 07:14 UTC, rick-r3 commented on docs/source/design/confidential-identities/design.md
> +* We perform one extra map look-up for key to X look-ups on the `IdentityService`
The `filterMyKeys` change will have negative impact.  But seems like we could preserve the existing functionality with reducing the functional benefits here.

2019-06-19 07:15 UTC, rick-r3 commented on docs/source/design/confidential-identities/design.md
> +entity. Once moved, they can be removed from the `keysToParties` table.
Hmmm.... is this true?  See comment elsewhere about cert chain of confidential identities.

2019-06-19 09:29 UTC, shamsasari commented on docs/source/design/confidential-identities/design.md
> +Indeed, it could be for an account or a legal identity, if a company wishes
From what I understand an account is just a public key with no backing cert, so `KeyToPartyMapping` couldn't work with accounts?

2019-06-19 09:35 UTC, shamsasari commented on docs/source/design/confidential-identities/design.md
> +            val signature: DigitalSignature.WithKey
What's this signature exactly of? I assume the serialised bytes of `mapping`? If so the way to model a signed data structure is to use the `SerializedBytes<T>` of the `T` that we want signed and not `T` itself. We have `SignedData` and `SignedDataWithCert` that work this way. They have `verified` methods which does the deserialisation and verify the signature over the bytes. Embedding the serialised bytes ensures that we don't accidently created unverifiable objects due to changes in the serialisation engine.

2019-06-19 09:41 UTC, shamsasari commented on docs/source/design/confidential-identities/design.md
> +            val signature: DigitalSignature.WithKey
In fact I think you can use the existing `SignedDataWithCert` class to model this. `raw` would be `SerializedBytes<PublicKey>` and the the `sig` would include the certificate containing the mapped public key.

2019-06-19 09:44 UTC, shamsasari commented on docs/source/design/confidential-identities/design.md
> +   entity (if an externalId is specified) and returns a `SignedKeyToPartyMapping`.
>(if an externalId is specified)

So the `externalID` parameter should be nullable?

2019-06-19 09:47 UTC, shamsasari commented on docs/source/design/confidential-identities/design.md
> +   **Note:** that the `SignedKeyToPartyMapping` must be registered with the `IdentityService`
Should this not be done automatically? Or is there a use case for generating a new public key mapping without registering it as an identity? I wouldn't have thought so, otherwise why not just generate a bog standard new key?

2019-06-19 09:48 UTC, shamsasari commented on docs/source/design/confidential-identities/design.md
> +2. Add a new API called `fun freshKey(externalID: UUID): SignedKeyToPartyMapping`
`freshMappedKey` or something similar, as the return type is not just a public key and would cause confusion when compared against the existing `freshKey` method.

2019-06-19 09:51 UTC, shamsasari commented on docs/source/design/confidential-identities/design.md
> +   2. `IdentityServiceInternal.justVerifyAndRegisterIdentity`
There's no need to deprecate the `IdentityServiceInternal` methods. If they're no longer used then it's a simple matter of deleting them, as they're not public API.

2019-06-19 10:00 UTC, shamsasari commented on docs/source/design/confidential-identities/design.md
> +2. Add a new API called `fun freshKey(externalID: UUID): SignedKeyToPartyMapping`
If the intention is for `SignedKeyToPartyMapping` to be public then `SignedDataWithCert<PublicKey>` may not be ideal. For a start it's in an internal package and so would have to be moved.

2019-06-19 10:00 UTC, roger-that-dev reviewed
thanks for the feedback @rick-r3, @shamsasari and @mikehearn

2020-09-14 11:05 UTC, closed without merging