[CORDA-2867] Allow non-code attachments to have colliding file names
corda/corda pull request #5136
Opened 2019-05-17 10:08 UTC by JamesHR3

The no-overlap rule causes transaction validation to fail if two attachments on the transaction provide files with the same name but different contents. This prevents attacks where classes are redefined in a second attachment to do something malicious. However, the check also applies to non-code files. For attachments containing code, this check is required and still prevents attacks. However, if the attachment contains no code at all, then this prevents multiple attachments containing documents with the same names, which is a compatibility break from Corda 3.

This change filters attachments passed to the `AttachmentsClassloader`, removing those that contain no `.class` files. The result is that attachments that contain no code do not collide with other non-code attachments.

Testing has been limited to unit tests and an integration test in this case.

2019-05-17 10:20 UTC, tudor-malene requested changes

2019-05-17 10:20 UTC, tudor-malene commented on core/src/main/kotlin/net/corda/core/transactions/WireTransaction.kt
> +                .filter { attachment ->  doesAttachmentContainCode(attachment) }
This is not according to the approach described in the story .

All attachments need to be available in the `LedgerTransaction`, but these non-code attachments should not be added to the `AttachmentsClassloader`.

2019-05-17 10:27 UTC, shamsasari requested changes

2019-05-17 10:27 UTC, shamsasari commented on core/src/main/kotlin/net/corda/core/internal/TransactionUtils.kt
> +        while (entry != null && !containsCode) {
This pattern of iterating through a jar stream is done several times, all using a while loop. Can we start to clean this up a bit by having a utility method that returns a `Sequence<JarEntry>` which would be easier to use. This already exists in JarSignatureCollector.kt, justs needs to be moved somewhere more public, but internal - InternalUtils.kt.

2019-05-17 10:27 UTC, shamsasari commented on core/src/main/kotlin/net/corda/core/transactions/WireTransaction.kt
> +                .filter { attachment ->  doesAttachmentContainCode(attachment) }
Filtering out attachments will break verify methods if they look up non-code attachments. We shouldn't be filtering out attachments anyway, just being smarter of when we throw the no-overlap exception. Shouldn't the change be where the no-overlap checks are made?

2019-05-17 10:27 UTC, shamsasari commented on core/src/main/kotlin/net/corda/core/internal/TransactionUtils.kt
> +                containsCode = true
You can return true here to terminate the iteration early

2019-05-17 10:31 UTC, JamesHR3 commented on core/src/main/kotlin/net/corda/core/transactions/WireTransaction.kt
> +                .filter { attachment ->  doesAttachmentContainCode(attachment) }
Ah, my mistake, I misunderstood.

2019-05-17 10:45 UTC, JamesHR3 commented on core/src/main/kotlin/net/corda/core/internal/TransactionUtils.kt
> +        while (entry != null && !containsCode) {
I've added this and tried to identify some locations where it could/should be used. I've changed some easy ones, but those that require more serious refactoring I've left alone for now. (I don't claim to have identified all places this would be useful!)

2019-05-17 10:57 UTC, shamsasari commented on core/src/main/kotlin/net/corda/core/internal/TransactionUtils.kt
> +        while (entry != null && !containsCode) {
You didn't have to refactor the other occurrences, just this one. If the changes are small then fine.

2019-05-17 11:06 UTC, gendal commented
PRs like this give me the heebie-jeebies...

the whole no-overlap-rule and associated security assumptions in this part of the platform are so critical to the soundness of the platform that we should probably be insanely over the top in reviews of these sorts of PRs and in documenting the heck out of the code for the benefit of those who come after us.

James - looks like you have the right eyes on it but let's be insanely conservative.

2019-05-17 11:12 UTC, tudor-malene commented
> PRs like this give me the heebie-jeebies...
> 
> the whole no-overlap-rule and associated security assumptions in this part of the platform are so critical to the soundness of the platform that we should probably be insanely over the top in reviews of these sorts of PRs and in documenting the heck out of the code for the benefit of those who come after us.
> 
> James - looks like you have the right eyes on it but let's be insanely conservative.

I suggested on the JIRA: https://r3-cev.atlassian.net/browse/CORDA-2867 , that @mikehearn validates that the proposed approach is indeed the best one.

Recap suggested approach:
 - Non-code attachments should not be added to the classloader and thus not trip the `no-overlap` rule.
 - If a contract wants to load a file from one of these attachments, he can do that using the Attachments api. (as the attachments are available on the `LedgerTransaction`)
- Hopefully nobody tries to load the file from the classloader at the moment.

2019-05-17 11:20 UTC, shamsasari commented
>Hopefully nobody tries to load the file from the classloader at the moment.

Are you referring to the contract verify method? I don;t think we can take the risk of breaking a verify method that uses `Class.getResource` or something.

2019-05-17 11:22 UTC, tudor-malene commented
> > Hopefully nobody tries to load the file from the classloader at the moment.
> 
> Are you referring to the contract verify method? I don;t think we can take the risk of breaking a verify method that uses `Class.getResource` or something.

Yes. Unfortunately, this is main issue with this approach.
But we break cordapps whatever we do. 
If we don't do this, then we break people who used the same file name.

2019-05-17 11:29 UTC, JamesHR3 commented
A possibility just discussed - instead of checking for non-code attachments before passing them to the classloader, instead check for them within the classloader and exclude them from just the no-overlap rule. (We were already doing this for the untrusted attachments check.)

2019-05-23 13:27 UTC, mikehearn commented
This change shouldn't be happening - as I outlined on Slack, the no-overlap rule is supposed to apply to data files as well as code.

What's driving this change? There is certainly another way to solve it.

2019-05-23 13:27 UTC, closed without merging

2019-05-23 13:31 UTC, mnesbit commented
This is to fix legitimate customer problems. In at least one case a customer has used attachments to store provided contract details documents. As the names of these are set by the originating customer it is perfectly possible for them to clash when composed into a full transaction.

2019-05-23 13:39 UTC, mikehearn commented
Sure, but that can be fixed by appending a random number to the end of the file name when it's wrapped in a zip. What if the two files aren't actually the same?

I wasn't aware Corda 3 wasn't enforcing this rule properly, that's a pity. Rather than define a new class of "non code attachment" (which would be weird and will trip people up for sure, it should be secure to attach data files to transactions), perhaps we can track files that are duplicated and just block them from being accessed at all. Apps that examine attachments directly would work, but the overlapping files would disappear during transaction verification. So there's no risk of the wrong data being seen. It's still not ideal (maybe the absence of a file is taken to mean something) but seems a bit safer. The concept of a "non-code attachment" would stick around forever and open up subtle traps for people to fall into, it seems to me.

2019-05-23 13:42 UTC, mnesbit commented
The files aren't the same content, they just happen to have the same name, because the actual user provides them. I think the app is some sort of KYC thing with people attaching various extra bits of info to support their application.

2019-05-23 13:56 UTC, mikehearn commented
That seems likely to cause confusion in other ways, but OK.

Blocking/hiding files that overlap (via the classloader) resolves the "some attachments are more secure than others" problem, but does it create a new one with files in META-INF which are expected to overlap? I'm not sure it does, I think the rule already takes META-INF into account.

Can we get a quick discussion somewhere (maybe corda-dev) of what the current no-overlap rule is, followed by the proposed new rule, so we can figure out if it enables new attacks, before coding up a change? Overlap handling is very sensitive.

Perhaps a good way to start is with a PR that contains only documentation. Then we can all agree on the approach, then the PR can be updated with another commit that adds the implementation.

2019-05-24 09:57 UTC, tudor-malene commented
Thanks @mikehearn , I had my reservations as well about this approach. 

Afaik, this is only a problem during some integration tests.

Corda 3 didn't use the AttachmentsClassloader at all, but the good thing is that contracts could have only accessed resources using the classloader when the file was also dropped in the `cordapps` folder. Otherwise they had to use the Attachments api.

I'll try to cover this topic in the dependencies/classloaders design I'm working on.

2019-06-04 11:07 UTC, mikehearn commented
Maybe overlap handling should have been gated on target version >= 4 then?