add a shared memory port allocator to allow multiple processes to sha…
corda/corda pull request #5223
Opened 2019-06-13 15:47 UTC by roastario

2019-06-14 08:47 UTC, r3domfox commented
I'm persuaded by the tests that this works, although there might be some hardware/platform-specific wrinkles - has it been tried on both Windows and Linux? Do we have an CI environments where we're not using a JVM in which UNSAFE is available?

2019-06-18 16:43 UTC, roastario commented
> I'm persuaded by the tests that this works, although there might be some hardware/platform-specific wrinkles - has it been tried on both Windows and Linux? Do we have any CI environments where we're not using a JVM in which UNSAFE is available?

All Java8 JDK's that we support (and essentially all) provide unsafe. 

JDK11 will be a bit more fun, as we will have to depend on the unsupported module, but zulu, corretto and oracle will continue to provide it.

2019-06-20 12:44 UTC, r3domfox submitted a review, later dismissed
LGTM

2019-06-21 15:42 UTC, mikehearn requested changes
Can you make sure the new API is fully documented and mention it in the integration testing section of the docsite, so users can use it?

2019-06-21 15:42 UTC, mikehearn commented on testing/node-driver/src/main/kotlin/net/corda/testing/driver/Driver.kt
> +class SharedMemoryPortAllocation private constructor(startPort: Int, endPort: Int, file: File = File(System.getProperty("user.home"), "$startPort-to-$endPort-allocator.bin")) : PortAllocation() {
KDocs?

2019-06-21 15:42 UTC, mikehearn commented on testing/node-driver/src/main/kotlin/net/corda/testing/driver/Driver.kt
> +                //we have gone past the point of no return
Comment style.

2019-06-21 15:42 UTC, mikehearn commented on testing/node-driver/src/main/kotlin/net/corda/testing/driver/Driver.kt
> +class SharedMemoryPortAllocation private constructor(startPort: Int, endPort: Int, file: File = File(System.getProperty("user.home"), "$startPort-to-$endPort-allocator.bin")) : PortAllocation() {
I'm not sure putting this in the home directory is especially friendly. Why not use the temporary directory, which is often mounted on an in-memory filesystem?

2019-06-21 15:42 UTC, mikehearn commented on testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/TestCordappImpl.kt
> +            val gradleLockFile = RandomAccessFile(File(System.getProperty("user.home"), "gradle.lock"), "rw")
temp dir? also this file name makes it look like gradle created it, which isn't so.

2019-06-21 15:42 UTC, mikehearn commented on testing/node-driver/src/test/java/net/corda/testing/node/PortAllocationRunner.java
> +        //each JVM will be launched with [allocationFile, spinnerFile, reportingIndex]
Comment style

2019-06-21 15:42 UTC, mikehearn commented on testing/node-driver/src/test/java/net/corda/testing/node/PortAllocationRunner.java
> +public class PortAllocationRunner {
KDoc would be useful here - what's this program for? Also why Java?

2019-06-21 15:42 UTC, mikehearn commented on testing/node-driver/src/test/java/net/corda/testing/node/PortAllocationRunner.java
> +        while (spinnerBuffer.getShort(0) != 8) {
You may as well Thread.sleep for a hundred msec or so here. You'll just waste a lot of CPU time burning the rest of the timeslice here.

2019-06-21 16:26 UTC, rick-r3 commented on testing/node-driver/src/main/kotlin/net/corda/testing/driver/Driver.kt
> +class SharedMemoryPortAllocation private constructor(startPort: Int, endPort: Int, file: File = File(System.getProperty("user.home"), "$startPort-to-$endPort-allocator.bin")) : PortAllocation() {
Use kotlin `object` instead of `INSTANCE`?  

Move inside `PortAllocation`, rename to `SharedMemory`, make private and offer a static/companion method/val `default` on `PortAllocation` itself.  Think that if we ever change the default again, would be nice not to change the call sites.  It also allows us to switch implementations using conditional logic.  And use `@JvmStatic` to make it nicer from Java

WDYT?

2019-06-21 16:26 UTC, rick-r3 commented on testing/node-driver/src/main/kotlin/net/corda/testing/driver/Driver.kt
> +        val INSTANCE = SharedMemoryPortAllocation(10000, FIRST_EPHEMERAL_PORT)
Should `10000` be a constant like `FIRST_EPHEMERAL_PORT` ?

2019-06-21 16:26 UTC, rick-r3 commented on BUILD_ENV_PARAMETERS
> +CORE_TESTING_FORKS : Number of JVMS to fork for running unit tests in :core
Maybe give this file a type? `.md` or `.txt` or something to imply docs.  Or is this file some magic build thing?

2019-06-21 16:26 UTC, rick-r3 commented on sizing.sh
> +  export CORE_TESTING_FORKS=1
Prefix with `CORDA_ENV_` or something like that just to namespace these a little.  Would make it easier to search for them across code base too.  Noticed the first file in this PR... maybe diminishes the need, but perhaps we should still standardise.

2019-06-21 16:55 UTC, roastario commented
build

2019-06-21 18:50 UTC, roastario commented on testing/node-driver/src/test/java/net/corda/testing/node/PortAllocationRunner.java
> +public class PortAllocationRunner {
This is just for unit testing the port allocator. 

I chose java just to make it easier to launch as a main class

2019-06-23 09:59 UTC, roastario commented
Build

2019-06-23 10:00 UTC, roastario commented
build

2019-06-23 10:56 UTC, roastario commented
build

2019-06-23 15:59 UTC, roastario commented
build

2019-06-23 16:55 UTC, roastario commented
build

2019-06-24 10:02 UTC, roastario commented
build

2019-06-24 10:04 UTC, roastario commented on testing/node-driver/src/main/kotlin/net/corda/testing/driver/Driver.kt
> +class SharedMemoryPortAllocation private constructor(startPort: Int, endPort: Int, file: File = File(System.getProperty("user.home"), "$startPort-to-$endPort-allocator.bin")) : PortAllocation() {
This will not be exposed to the user, to avoid the whole API issue as before. 

I've added a single function in DriverDSL.nextPort() which will provide access to this functionality in a way which doesn't expose all the internals.

2019-06-24 10:04 UTC, roastario commented on testing/node-driver/src/main/kotlin/net/corda/testing/driver/Driver.kt
> +class SharedMemoryPortAllocation private constructor(startPort: Int, endPort: Int, file: File = File(System.getProperty("user.home"), "$startPort-to-$endPort-allocator.bin")) : PortAllocation() {
I've moved the files to the temp dir.

2019-06-24 10:05 UTC, roastario commented on testing/node-driver/src/main/kotlin/net/corda/testing/driver/Driver.kt
> +                //we have gone past the point of no return
removed

2019-06-24 10:05 UTC, roastario commented on testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/TestCordappImpl.kt
> +            val gradleLockFile = RandomAccessFile(File(System.getProperty("user.home"), "gradle.lock"), "rw")
renamed and moved

2019-06-24 10:09 UTC, roastario commented on testing/node-driver/src/test/java/net/corda/testing/node/PortAllocationRunner.java
> +        //each JVM will be launched with [allocationFile, spinnerFile, reportingIndex]
fixed

2019-06-24 10:09 UTC, roastario commented on testing/node-driver/src/test/java/net/corda/testing/node/PortAllocationRunner.java
> +        while (spinnerBuffer.getShort(0) != 8) {
even a 100ms is eons compared to the time taken to select 10,000 ports. 
we have to busy spin to ensure there are overlapping port selections.

2019-06-24 10:18 UTC, roastario commented on sizing.sh
> +elif ((NUM_CPU > 32 && NUM_CPU <= 64)); then
done

2019-06-24 10:23 UTC, roastario commented on testing/node-driver/src/main/kotlin/net/corda/testing/driver/Driver.kt
> +    open class Incremental(private val startingPort: Int) : PortAllocation() {
I have changed all the callsites - the problem with leaving incremental totally alone, is that because we made it part of "API" anyone currently using Incremental allocation will suddenly start experiencing random failures if they ever want to make use of parallel builds.

by redirecting the Incremental to the new SharedMemoryIncremental provider, we can catch this edge case.

2019-06-24 15:31 UTC, roastario commented on sizing.sh
> +  export CORE_TESTING_FORKS=1
done

2019-06-24 15:31 UTC, roastario commented on BUILD_ENV_PARAMETERS
> +CORE_TESTING_FORKS : Number of JVMS to fork for running unit tests in :core
done

2019-06-24 15:31 UTC, roastario commented on testing/node-driver/src/main/kotlin/net/corda/testing/driver/Driver.kt
> +        val INSTANCE = SharedMemoryPortAllocation(10000, FIRST_EPHEMERAL_PORT)
done

2019-06-24 15:32 UTC, roastario commented on testing/node-driver/src/main/kotlin/net/corda/testing/driver/Driver.kt
> +class SharedMemoryPortAllocation private constructor(startPort: Int, endPort: Int, file: File = File(System.getProperty("user.home"), "$startPort-to-$endPort-allocator.bin")) : PortAllocation() {
moved it and created new static method defaultAllocator on PortAllocation

2019-06-24 16:52 UTC, roastario commented on testing/node-driver/src/main/kotlin/net/corda/testing/driver/Driver.kt
> +class SharedMemoryPortAllocation private constructor(startPort: Int, endPort: Int, file: File = File(System.getProperty("user.home"), "$startPort-to-$endPort-allocator.bin")) : PortAllocation() {
Ah, which introduced a new fun issue. From within the context of gradle `File(System.getProperty("java.io.tmpdir")` is repurposed, so instead of returning /tmp it returns /tmp/<submodule>

which leads to things like:

```
agent@ubuntu-correto-large643eb0:~$ find /tmp/ | grep allocator
find: ‘/tmp/systemd-private-19a9e916ecd14721b9657212b3012de0-systemd-resolved.service-1jbzx8’: Permission denied
/tmp/workspace/Corda Pull Request Integration Tests/finance/workflows/build/10000-to-30000-allocator.bin
/tmp/workspace/Corda Pull Request Integration Tests/client/rpc/build/10000-to-30000-allocator.bin
/tmp/workspace/Corda Pull Request Integration Tests/docs/source/example-code/build/10000-to-30000-allocator.bin
/tmp/workspace/Corda Pull Request Integration Tests/samples/attachment-demo/build/10000-to-30000-allocator.bin
/tmp/workspace/Corda Pull Request Integration Tests/samples/simm-valuation-demo/build/10000-to-30000-allocator.bin
/tmp/workspace/Corda Pull Request Integration Tests/samples/irs-demo/build/10000-to-30000-allocator.bin
/tmp/workspace/Corda Pull Request Integration Tests/samples/trader-demo/build/10000-to-30000-allocator.bin
/tmp/workspace/Corda Pull Request Integration Tests/testing/node-driver/build/10000-to-30000-allocator.bin
/tmp/workspace/Corda Pull Request Integration Tests/tools/shell/build/10000-to-30000-allocator.bin
/tmp/workspace/Corda Pull Request Integration Tests/webserver/build/10000-to-30000-allocator.bin
```

2019-07-02 16:42 UTC, mikehearn approved these changes

2019-07-02 18:38 UTC, merged