Filtering out attachments to reference only ContractStates.
corda/corda pull request #5258
Opened 2019-06-26 15:04 UTC by dimashblocksure

Here is a proposed fix to improve the serialisation execution context with attachments classloader. I have raised and described the issue here https://github.com/corda/corda/issues/5249. 

Summary: 

We are experiencing very slow execution when uploading attachments because our repository classpath is always rescanned for new attachments. Every individual transaction recomputes the key for different attachments.

The solution proposed will only compute the keys for ContractAttachments because are they are the only ones that are needed (data attachments do not need to been reflected in an updated classpath search). Thus, it will use the precomputed value for following transactions and ignore the data attachments as part of the key.

# PR Checklist:

- [ Yes] Have you run the unit, integration and smoke tests as described [here](https://docs.corda.net/head/testing.html)? (All builds pass except `Task :node:integrationTest`. Caused by: `org.apache.activemq.artemis.api.core.ActiveMQNotConnectedException: AMQ119007: Cannot connect to server(s). Tried with all available servers.`)
- [ No] If you added public APIs, did you write the JavaDocs? (No changes in the API)
- [ No] If the changes are of interest to application developers, have you added them to the [changelog](https://github.com/corda/corda/blob/master/docs/source/changelog.rst), and potentially the [release notes](https://github.com/corda/corda/blob/master/docs/source/release-notes.rst)? 
- [ Yes] If you are contributing for the first time, please read the agreement in [CONTRIBUTING.md](https://github.com/corda/corda/blob/master/CONTRIBUTING.md) now and add a comment to this pull request stating that your PR is in accordance with the [Developer's Certificate of Origin](https://github.com/corda/corda/blob/master/CONTRIBUTING.md#developer-certificate-of-origin).

Thanks for your code, it's appreciated! :)

I hereby certify that my contribution is in accordance with the Developer Certificate of Origin (https://developercertificate.org/).

Note: The following issue is experienced on Corda 4. In case it is accepted, could it be included in the upcoming Corda 4 release please.

2019-06-26 15:04 UTC, roastario commented
Can one of the admins verify this patch?

2019-06-26 15:12 UTC, richardblocksure commented
> Can one of the admins verify this patch?

LGTM :-)

2019-06-26 15:16 UTC, lankydan commented
ye probs best to rebase to undo the commit and not include all the deleted files. Probs worth @tudor-malene taking a look at this too.

2019-06-26 15:16 UTC, tudor-malene requested changes

2019-06-26 15:16 UTC, tudor-malene commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
> +        val attachmentIds = attachments.filterIsInstance<ContractAttachment>().map { it.id }.toSet()
Thanks for the contribution Dimash.

The issue with this fix is that transactions could be run within an invalid classloader.

Let's say that instead of attaching an image file, you attach some actual reference data that must be used in the contract code.
If you cache only by code jar ids (like your proposed fix), then a transaction could be run with the reference data of some other transaction, which would make verification wrong/non-deterministic.
This is because the classloader that you're reusing is built with different reference data.

The way to fix it is to create another cache keyed only on code jars that should cache the expensive serialiser classes.

2019-06-26 15:22 UTC, ragmondo commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
> +        val attachmentIds = attachments.filterIsInstance<ContractAttachment>().map { it.id }.toSet()
Thanks for the super quick analysis @tudor-malene . The issue we are trying to fix is that _any_ corda transaction that uses an attachment will be dreadfully slow once the classpath starts expanding. Like "is this thing on?" slow. I agree with you that there is the case that reference data could be included  that needs to be compatible with verify but there are a lot of cases where this data is just a placeholder for a document, image etc which will never be referenced in verify. Even if this PR is not accepted, can someone start looking at determining which attachments can be referenced within verify and which are for ledger-completeness without having to refer to yet another data store ?

2019-06-26 15:30 UTC, tudor-malene commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
> +        val attachmentIds = attachments.filterIsInstance<ContractAttachment>().map { it.id }.toSet()
If we cache things at the right level, I hope we can avoid having to differentiate between attachments like this. 

This code has been rushed at the last moment before releasing v4 and that explains why it's not  ideal.

If you guys want to contribute and fix this we could arrange a call or meet to discuss what a good approach would be.

2019-06-26 15:37 UTC, ragmondo commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
> +        val attachmentIds = attachments.filterIsInstance<ContractAttachment>().map { it.id }.toSet()
Sure we can. For our situation, we are going to deploy our release with a fork so we can include this - it's literally stopping our user flow dead in it's tracks the moment they need to add a picture in our of product functions. Also appreciate the brutal honesty as usual

2019-06-26 16:45 UTC, tudor-malene commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
> +        val attachmentIds = attachments.filterIsInstance<ContractAttachment>().map { it.id }.toSet()
This code is at the heart of the contract verification logic. It is quite sensitive.
All aspects must be considered when changing it.

You can go with this temporary patch unless you have any contracts that use reference data for verification, and also don't foresee any on the network until all nodes upgrade.

2019-06-27 10:32 UTC, ragmondo commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
> +        val attachmentIds = attachments.filterIsInstance<ContractAttachment>().map { it.id }.toSet()
Can I spell this out for my understanding and please correct me if I'm wrong on any part of this (and apologies in advance for dumbing it down to the basics but I just want to be sure I haven’t missed anything).

A transaction contains attachments. These attachments can be of (almost) any type but, broadly speaking, they are one of the following:

1. contract (and therefore executable) code
2. a data attachment that is referenced in the verify but has no inherent executable code (such as an agreed interest rate or a logged temperature reading etc).  
3. a data attachment that the application refers for ledger completeness (such as a digital image of a passport or - in our case - evidence of an accident). These attachments are included such that the application can use the ledger to pass this data around as opposed to using another service and having the reference to that service included in the transaction.

When attachments that include any form of executable code are included in the transaction, we need to scan the classpath in order to determine where exactly our code will be from when executed in the verify in a manner that is strictly deterministic. Additionally, if the attachment contains data that is used in verify, this also needs to be accessible from verify (I’m not sure if these need to be classpath’d or not - but it’s not relevant to our request). 

The issue we are finding arises from when a data attachment is not used within the verify but does need to be associated to the transaction. As the attachment hash changes for each instance of the transaction (i.e. for us when a user uploads an image), then the class path is regenerated each time. This is CPU costly when the class path is non trivial. What we would like to do is mark an attachment as “for interest only” (or words to that affect) and not have that referenced in this class path determination and therefore massively improve the performance of all subsequent transactions (as the cache lookup succeeds). To re-iterate: These attachments do not necessarily need to be available from within the depths of the verify method. We just pass the hash (and the subsequent data) to ensure that the data has not been tampered.

2019-06-27 10:42 UTC, tudor-malene commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
> +        val attachmentIds = attachments.filterIsInstance<ContractAttachment>().map { it.id }.toSet()
That sounds correct @ragmondo .

> I’m not sure if these need to be classpath’d or not - but it’s not relevant to our request

That is one of the requirements we do have. So yes, attachments need to be on the classpath.

> What we would like to do is mark an attachment as “for interest only” (or words to that affect) and not have that referenced in this class path determination

This would mean a new API, and an extra concept to learn for Cordapp developers. The only reason for it is to optimize some internal implementation. I'm sure we can achieve the same without having to add this extra concept.

2019-06-27 11:01 UTC, dimashblocksure commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
> +        val attachmentIds = attachments.filterIsInstance<ContractAttachment>().map { it.id }.toSet()
Thanks for all the insight Tudor. It was very helpful!

2019-06-28 10:19 UTC, ragmondo commented
@tudor-malene Thanks for spending a bit of time with us today helping us understand the complexity of this. Obviously this code in it's current state can't be approved so should we either withdraw the PR or leave until we have something more suitable? If I am blunt, I don't think we will be able to do the later option in any reasonable time. Happy to leave the PR as active though if it helps serve as a reminder. Let us know or action as you see fit.

2019-06-28 11:14 UTC, mikehearn commented
Had a chat with Tudor about this.

We'd like to support attaching non-consensus files to transactions. Tweaking the existing mechanism isn't likely the right way to go. Maybe we can call them attached streams, to reflect the fact that they're potentially very large.

The best approach is *not* to retrofit the existing attachments mechanism, but rather to add a new component group to `WireTransaction` i.e. a totally independent transaction feature. This is because:

* Attachments propagate with transaction data, but things like photos for accidents shouldn't propagate around. Usually only your counterparty cares.
* We don't want to load these attachments into memory whilst transaction processing, as contract logic wouldn't have access to them anyway. We especially don't want to load them into SGX enclaves.
* For such files wrapping them in a ZIP is a pain. It'd be good to be able to attach them directly, without ZIPs getting involved. That in turn means each entry needs at least a file name and probably a MIME type.
* We don't need to care about overlaps, so the hated no-overlap rule can be ignored for these things.
* Old nodes (should) ignore new transaction components, so it might be deployable without a minPlatformVersion increment. A bit of an open question.

What work is involved?

1. Figuring out the right API. Probably it's something like adding an `InputStream` to a `TransactionBuilder`. There's no obvious reason why the attachment should have to be explicitly copied into an RDBMS first. When the `TransactionBuilder` creates the `WireTransaction`, it'd read the entire stream to calculate the hash, ensuring it's also copied into some file store that isn't the RDBMS. Probably just a configurable directory for now? That way you can use https://github.com/s3fs-fuse/s3fs-fuse or ObjectiveFS to upload the streams to Amazon S3 if you have a lot of them.
2. Make sure `InputStream` is supported in client RPC. We did do some work on this before Corda 1.0 ... Artemis supports attaching `InputStream` objects to MQ messages that are then streamed over the message bus, and I think the RPC client library knows how to serialise `InputStream` objects to handles and then attach the stream to the underlying message, and do the reverse on the other side, so it all gets reconnected properly with the object graph on the other end.
3. Make sure you can pass a stream into a flow constructor. Again, this *should* come for free, if the RPC client code is still working properly.
4. Now add support for sending an `InputStream` over a flow. Of course one way to do it is just read a chunk, send it as a byte array, read another chunk etc until the end. But it'd be a lot nicer if it's more integrated. [Worth trying the built-in Artemis support](https://activemq.apache.org/components/artemis/documentation/latest/large-messages.html) ... remember, at no time must the entire message be stored in RAM! Only fragments!
5. On our side, this may require some enhancements to the Corda Firewall.
6. Finally, once streams can be passed around all the different bits of the Corda ecosystem without ever being fully buffered into RAM, we can add a new `ComponentGroup` to `WireTransaction` and define a new type to represent these 'attached streams'. For instance there should be a file name, an optional mime type, an optional file size field, maybe a description field? Maybe an extension point so users can provide their own file metadata? Then we need to extend ResolveTransactionsFlow to download these additional streams, hash them (as the data passes through to disk) and check the hash against the hash in the transaction. 

Mostly this is just wiring up features that already exist and making sure they actually work.

I would fully understand if this project is too big for you. If your attachments can be guaranteed to fit under 10mb in size, you could for now just add a hack to your local Corda fork that excludes attachments with a magic filename as their first entry or something else like that. Alternatively you could experiment with just storing ByteArrays in your states directly and see what happens.

2019-06-28 13:33 UTC, ragmondo commented
Appreciate the level of detail that you chaps have given this along with what would be the preferred option for development. As you recognise, I think it would be folly of us to embark upon that level of development effort though without quite strict guidance to ensure the fruits of the labour are good enough to (eventually be) PR approved to master. Pragmatically though, that, and the fact we have a real need today to improve our particular use case _now_ means that I think we are going to go ahead with the hack to the local Corda fork for now (and have to keep re-applying to 4.2, 4.3 ...etc).  If anyone else is using attachments like this then I would imagine they would start to see similar issues once their classpath starts expanding. 

As mentioned, no offence taken if you want to close this PR as long as we can keep the issue open.

2020-01-21 14:51 UTC, davidrapacchiale commented
Hi @ragmondo , I am going to close this issue in github as we are tracking it on our OS Jira project (https://r3-cev.atlassian.net/browse/CORDA-3215). Thanks!

2020-01-21 14:51 UTC, closed without merging