First draft - cordapp plugin design
corda/corda pull request #5301
Opened 2019-07-15 14:03 UTC by tudor-malene

WIP

2019-07-15 14:12 UTC, gendal commented on docs/source/design/corda-gradle-plugin-v2/design.md
> +To keep it simple under those requirements, its approach is to extend the functionality of the standard java plugin by giving extra packaging responsibilities to the basic dependency
Given how scary most people seem to find Gradle, should there be a short preamble that defines some contexts?  eg you jump straight into this document with an assumption that the reader knows what the "standard java plugin" is.  Is that a safe assumption?

2019-07-15 14:14 UTC, tudor-malene commented on docs/source/design/corda-gradle-plugin-v2/design.md
> +To keep it simple under those requirements, its approach is to extend the functionality of the standard java plugin by giving extra packaging responsibilities to the basic dependency
Good point. 
I added a link to it below, but it should be here as it's the first mentioning.

2019-07-15 16:21 UTC, chrisr3 reviewed
Uurggh, too much thinking about Gradle. _**Brayne Hurtzzzz**_

2019-07-15 16:21 UTC, chrisr3 commented on docs/source/design/corda-gradle-plugin-v2/design.md
> +- Create a new plugin and deprecate the current one. The complexity of improving the existing plugin is too high.
The `cordapp` plugin implements semi-fat jarring and jar signing. Are you suggesting something more complex than this or less complex? Because my reading of this is that your new plugin would be _at least_ as complex.

The existing `cordapp` plugin assumes the following:
- a module that wants to create a CorDapp will apply the `cordapp` plugin.
- the primary output of a CorDapp module should be the semi-fat jar, i.e. what Gradle provides when you write:
```gradle
dependencies {
    implementation project(':my-cordapp')
}
```
- Gradle's `maven-publish` plugin also expects to publish the project's primary artifact.

Gradle can be a _**Royal PITA**_ when a module's primary artifact _isn't_ the output of the `jar` task. Notice that the output of the `shadow` plugin has the `all` classifier by default because it assumes that the `jar` task is still the primary artifact. Projects that blithely overwrite the default `jar` with the shaded one have actually _broken_ Gradle's incremental task assumptions.

2019-07-15 16:28 UTC, tudor-malene commented on docs/source/design/corda-gradle-plugin-v2/design.md
> +- ``cordapp`` : compile against it, but don't fat-jar and also deploy it to ``cordformation`` nodes.
This was supposed to be a functional description. 
When you declare a dependency as "cordapp" - this is what happens (if you also use codeformation of cource)

2019-07-15 16:39 UTC, tudor-malene commented on docs/source/design/corda-gradle-plugin-v2/design.md
> +- ``cordaCompile`` : compile against this, but don't fat-jar.
> So the problem became: "Out of all of a CorDapp's arbitrary `compile` and `runtime` dependencies, how can developers configure _precisely_ which ones they wish to bundle into their CorDapps?". And so Clinton created two new configurations:
> 
> * `cordaCompile` for the compile time dependencies which are also Corda artifacts
> * `cordaRuntime` for runtme dependencies which are also Corda artifacts
> 
> By the power of Gradle, adding something to `cordaCompile` _automatically_ adds it to `compile` too, as otherwise the CorDapp wouldn't compile any more. And ditto for the relationship between `cordaRuntime` and `runtime`, of course.

This is what I tried to address at the beginning of this doc. The actual requirements turned out to be a bit more complex.

> The `cordformation` plugin is an obvious user of the `cordaRuntime` configuration because it needs to find `corda.jar` at runtime so that it can execute `deployNodes`. And similarly for the Network Bootstrapper, which is part of `corda-node-api`.
> 
> _However, it would be presumptuous to assume that `cordformation` is the **only** user of `cordaRuntime`._ `cordaRuntime` should be considered for what it is: the subset of the CorDapp's `runtime` dependencies which are not to be bundled into the semi-fat jar.

The thing is it's pretty obvious that a *CorDa*pp depends on Corda. I don't think it needs any special configuration to express that.

> Ironically, this extension of how Gradle's own `java` plugin works is now dismissed as "magic". Go figure...

That's a bit harsh.. 
It's about overloading "compile" with behaviour it doesn't normally have.
Which is surprising.

2019-07-15 16:40 UTC, tudor-malene commented on docs/source/design/corda-gradle-plugin-v2/design.md
> +
That shouldn't be a requirement. 
Let's say you write a CorDapp that depends on the Tokens sdk.
You can't fat-jar the tokens sdk..

2019-07-15 16:42 UTC, tudor-malene commented on docs/source/design/corda-gradle-plugin-v2/design.md
> +
3. is a cordapp if it is a utility that flows or contracts would depend upon.
Think an SDK.

2019-07-15 16:43 UTC, tudor-malene commented on docs/source/design/corda-gradle-plugin-v2/design.md
> +
Actually I meant to link here to the java plugin:
https://docs.gradle.org/current/userguide/java_plugin.html

I'll change the link

2019-07-15 16:46 UTC, tudor-malene commented on docs/source/design/corda-gradle-plugin-v2/design.md
> +
These were just high level requirements.
Solutions were proposed below

2019-07-15 16:51 UTC, tudor-malene commented on docs/source/design/corda-gradle-plugin-v2/design.md
> +- Create a new plugin and deprecate the current one. The complexity of improving the existing plugin is too high.
Basically I suggest we build something less complex as the "cordapp plugin v2" and move the stuff necessary for testing into the "cordapp testing plugin" - which would be integrated with both cordformation and the driver.

The cordapp plugin:
- declares the version of corda
- handles adding metadata ( tpv, mpv, licence, etc)
- Adds dependency security constraints.
- outsources packaging ( fat-jarring), but will call it during its lifecycle
- handles signing

It no longer takes on any fat-jarring role.

2019-07-16 08:18 UTC, chrisr3 commented on docs/source/design/corda-gradle-plugin-v2/design.md
> +- Create a new plugin and deprecate the current one. The complexity of improving the existing plugin is too high.
How will this step actually _work_ though?
> outsources packaging ( fat-jarring), but will call it during its lifecycle

I can't claim to understand CorDapps in depth, but AFAIK we _do_ want to sign the "semi-fat" jar version. Moreover, it is the _requirement_ that we create a semi-fat jar that is causing all this complexity in the first place, and that requirement doesn't seem to have disappeared.

Is "outsourcing" a euphemism for telling CorDapp developers to do the semi-fat jar packaging all by themselves, however they see fit?

Do you intend for the primary output of the `cordapp` plugin to be a typical "thin jar", or a CorDapp that can be deployed into Corda?

2019-07-16 10:19 UTC, tudor-malene commented on docs/source/design/corda-gradle-plugin-v2/design.md
> +- Create a new plugin and deprecate the current one. The complexity of improving the existing plugin is too high.
> I can't claim to understand CorDapps in depth, but AFAIK we _do_ want to sign the "semi-fat" jar version. Moreover, it is the _requirement_ that we create a semi-fat jar that is causing all this complexity in the first place, and that requirement doesn't seem to have disappeared.

It is a requirement. But there is a good plugin out there - shadow - that we can leverage, so we don't have to replicate its functionality.

> Is "outsourcing" a euphemism for telling CorDapp developers to do the semi-fat jar packaging all by themselves, however they see fit?

Pretty much.
Obviously there would be sensible defaults to get you going:
- By default just use the `jar` task  that creates a thin jar.
- if the shadow plugin is installed, use the `shadowJar` task

> Do you intend for the primary output of the `cordapp` plugin to be a typical "thin jar", or a CorDapp that can be deployed into Corda?

Obviously a CorDapp that can be deployed into Corda. 
But that doesn't mean it can't be a thin jar with dependency metadata inside it.

2019-07-16 11:15 UTC, chrisr3 commented on docs/source/design/corda-gradle-plugin-v2/design.md
> +- Create a new plugin and deprecate the current one. The complexity of improving the existing plugin is too high.
Defining a CorDapp as a "thin jar" with dependency information _would_ simplify things, except that the dependency information would still have to be generated by the exact same logic that the `cordapp` plugin currently uses to determine the contents of the "semi-fat" jar. This logic effectively subtracts the resolved contents of the `cordapp`, `cordaCompile` and `cordaRuntime` configurations from the resolved contents of the `runtimeClasspath` to create list of jars.

Is getting rid of the "semi-fat" jar _itself_ enough? This would help developers who want to make CorDapps depend on other CorDapps etc, but I doubt it would help with the "_Help! It's Gradle! **Run Away!**_" mindset that everyone seems to have.

2019-07-16 11:40 UTC, chrisr3 commented on docs/source/design/corda-gradle-plugin-v2/design.md
> +- Create a new plugin and deprecate the current one. The complexity of improving the existing plugin is too high.
How do you envisage resolving the dependency metadata from a collection of "thin jar" CorDapps into a single set of jars that should be deployed into a Corda node?

2019-07-16 13:02 UTC, chrisr3 commented on docs/source/design/corda-gradle-plugin-v2/design.md
> +- Create a new plugin and deprecate the current one. The complexity of improving the existing plugin is too high.
Of course, that problem would disappear if each CorDapp had its own classloader. We might not even feel the need for shading any more in that world.

Then imagine if a CorDapp were some kind of `ZIP` file containing the user's "thin jar" along with all of its dependent jars (without Corda dependencies, Kotlin or Quasar etc... i.e. what we currently bundle into the "semi-fat" jar)

And in a flash, you suddenly realise that you can make the Gradle madness  _**disappear**_ by saying the magic word:

:sparkles:  **_ABRACAD-APPLICATION-SERVER!!_** :sparkles:

2019-07-16 13:55 UTC, tudor-malene commented on docs/source/design/corda-gradle-plugin-v2/design.md
> +- Create a new plugin and deprecate the current one. The complexity of improving the existing plugin is too high.
> Defining a CorDapp as a "thin jar" with dependency information _would_ simplify things, except that the dependency information would still have to be generated by the exact same logic that the `cordapp` plugin currently uses to determine the contents of the "semi-fat" jar. This logic effectively subtracts the resolved contents of the `cordapp`, `cordaCompile` and `cordaRuntime` configurations from the resolved contents of the `runtimeClasspath` to create a list of jars.

Just to clarify, a CorDapp doesn't have to be a thin jar or a fat jar. 
It can be whatever its creator decides. She can use the full power of the shadow plugin to shade, filter, minimize, etc.
The cordapp-v2 plugin will not create any special configurations for this purpose.

For special cases, like when you depend on a widely used SDK and can't embed it, you must somehow set constraints on the jar that must be in the classloader at runtime. That's what the `dependencyConstraints` thing is for.

 
> Is getting rid of the "semi-fat" jar _itself_ enough? This would help developers who want to make CorDapps depend on other CorDapps etc, but I doubt it would help with the "_Help! It's Gradle! **Run Away!**_" mindset that everyone seems to have.

This new iteration is not about getting rid of fat-jarring. 
It's more about making the plugin more explicit and reducing its scope.

The rest of its functionality would be moved to the "cordapp-test" plugin but a bit more general and flexible to solve other problems we have.

2019-07-16 13:56 UTC, tudor-malene commented on docs/source/design/corda-gradle-plugin-v2/design.md
> +- Create a new plugin and deprecate the current one. The complexity of improving the existing plugin is too high.
> How do you envisage resolving the dependency metadata from a collection of "thin jar" CorDapps into a single set of jars that should be deployed into a Corda node?

That's what the `cordapp-testing` in the proposal for the testing plugin is for.

2019-07-16 14:00 UTC, tudor-malene commented on docs/source/design/corda-gradle-plugin-v2/design.md
> +- Create a new plugin and deprecate the current one. The complexity of improving the existing plugin is too high.
> Of course, that problem would disappear if each CorDapp had its own classloader. We might not even feel the need for shading any more in that world.
> 
> Then imagine if a CorDapp were some kind of `ZIP` file containing the user's "thin jar" along with all of its dependent jars (without Corda dependencies, Kotlin or Quasar etc... i.e. what we currently bundle into the "semi-fat" jar)
> 
> And in a flash, you suddenly realise that you can make the Gradle madness _**disappear**_ by saying the magic word:
> 
> ✨ **_ABRACAD-APPLICATION-SERVER!!_** ✨

That would be nice, but it looks like we're not heading in that direction.

Even if we did -this  proposal makes it easy, because it's just the packaging bit that would change, which is not included in the plugin in the first place.

2019-07-16 15:01 UTC, chrisr3 commented on docs/source/design/corda-gradle-plugin-v2/design.md
> +- Create a new plugin and deprecate the current one. The complexity of improving the existing plugin is too high.
OK, so to be clear:
- Gradle is _just too hard_, and so we are **washing our hands** of it (_ahem_ "outsourcing" it).
- Building CorDapp jars so that they deploy correctly to a Corda node will now be **100%** the CorDapp developers' ~fault~ responsibility. _This includes all of the semi-fat jarring functionality currently contained within the `cordapp` plugin._
- Everything Corda-related that is deemed to be beyond mere mortal comprehension will be stuffed into a `cordapp v2` plugin, and one person from this Galaxy will be appointed to guard it.

To be fair, I wouldn't miss the semi-fat jarring if it disappeared. But Java applications are a _solved problem_, CorDapp developers are _crying out_ for classloader isolation and we seem to be iterating from square wheels to triangular ones.

2019-07-16 15:16 UTC, tudor-malene commented on docs/source/design/corda-gradle-plugin-v2/design.md
> +- Create a new plugin and deprecate the current one. The complexity of improving the existing plugin is too high.
> * Gradle is _just too hard_, and so we are **washing our hands** of it (_ahem_ "outsourcing" it).

Not gradle. But packaging jars. There is a plugin out there that is much better (known, documented, tested, feature-rich) than what we can come up with.

> * Building CorDapp jars so that they deploy correctly to a Corda node will now be **100%** the CorDapp developers' ~fault~ responsibility. _This includes all of the semi-fat jarring functionality currently contained within the `cordapp` plugin._

Yes. Obviously there would be guides. But they should be able to do whatever they want, as long as they test it and it works.

> * Everything Corda-related that is deemed to be beyond mere mortal comprehension will be stuffed into a `cordapp v2` plugin, and one person from this Galaxy will be appointed to guard it.

That would be `groot` :)
The idea is to stuff all the testing/cordformation stuff into the "cordapp testing plugin", and the packaging stuff to be handled separately ( if a thin-jar is not enough). 

> To be fair, I wouldn't miss the semi-fat jarring if it disappeared. But Java applications are a _solved problem_, CorDapp developers are _crying out_ for classloader isolation and we seem to be iterating from square wheels to triangular ones.

That's another point of this proposal. To make cordapp modules just plain java modules.
And just add the minimum corda-specific stuff required (like the metadata and signing), without extending anything from the underlying gradle plugin.

2019-07-16 15:51 UTC, chrisr3 commented on docs/source/design/corda-gradle-plugin-v2/design.md
> +- Create a new plugin and deprecate the current one. The complexity of improving the existing plugin is too high.
> Not gradle. But packaging jars. There is a plugin out there that is much better (known, documented, tested, feature-rich) than what we can come up with.

_Yes, Gradle!_ I am fully aware of what the `shadow` plugin can do, having recently had a (minor) contribution to it accepted by its maintainer. And the "Gradle-Fu" that I have exerted in order to wield it has at times been _considerable_. So may I suggest that you use it now to create a CorDapp with the following restrictions:
- It should contain no Corda dependencies
- It should contain no _transitive dependencies_ of any Corda dependencies
- It should not contain any Kotlin or Quasar dependencies either.
- Once complete, it should be signed and then published to `mavenLocal` with a viable POM.

I am assuming that we'll want to sign the output of the `shadowJar` task and then publish the signed jar, of course.

2019-07-16 15:55 UTC, tudor-malene commented on docs/source/design/corda-gradle-plugin-v2/design.md
> +- Create a new plugin and deprecate the current one. The complexity of improving the existing plugin is too high.
> _Yes, Gradle!_ I am fully aware of what the `shadow` plugin can do, having recently had a (minor) contribution to it accepted by its maintainer. And the "Gradle-Fu" that I have exerted in order to wield it has at times been _considerable_. So may I suggest that you use it now to create a CorDapp with the following restrictions:
> 
> * It should contain no Corda dependencies
> * It should contain no _transitive dependencies_ of any Corda dependencies
> * It should not contain any Kotlin or Quasar dependencies either.
> * Once complete, it should be signed and then published to `mavenLocal` with a viable POM.
> 
> I am assuming that we'll want to sign the output of the `shadowJar` task and then publish the signed jar, of course.

Maybe I'm wrong here, but afaict, all you have to do is get rid of `project.configurations.runtime` from `shadow.configurations`

2019-07-16 16:17 UTC, chrisr3 commented on docs/source/design/corda-gradle-plugin-v2/design.md
> +- Create a new plugin and deprecate the current one. The complexity of improving the existing plugin is too high.
`project.configurations.runtime` has been deprecated for a while now.

2019-07-16 16:19 UTC, tudor-malene commented on docs/source/design/corda-gradle-plugin-v2/design.md
> +- Create a new plugin and deprecate the current one. The complexity of improving the existing plugin is too high.
Does it matter ? 
Basically you have to tell shadow to not fatjar stuff that's on  "runtime" by default.

2019-07-17 14:09 UTC, mikehearn requested changes

2019-07-17 14:09 UTC, mikehearn commented on docs/source/design/corda-gradle-plugin-v2/design.md
> +- Create a new plugin and deprecate the current one. The complexity of improving the existing plugin is too high.
I guess I'd like more info too. How does the shadow plugin - if that's what's being invoked - know what to include and what not to include, if it's pluggable and only loosely coupled? Is the assumption here that the cordapp plugin adds dependencies on things like `core` on the fly, in such a way that the packager task used ignores them?

Is the idea here that we use `api` vs `implementation` to demarcate what's bundled and what's not?

2019-07-17 14:09 UTC, mikehearn commented on docs/source/design/corda-gradle-plugin-v2/design.md
> +- Add a section ``dependencyConstraints`` that can specify what cryptographic constraints the libraries from the same classloader must obey.
Dependency security is going to be something the whole Java ecosystem needs to start thinking about. It might be good to split this out into a separate design effort, a separate project even (with its own name) and then we can promote it across the wider Java ecosystem. If nothing else it'd help raise our profile.

2019-07-17 14:09 UTC, mikehearn commented on docs/source/design/corda-gradle-plugin-v2/design.md
> +TODO
Please fill out sections like this before review, don't just ignore them. You're suggesting rewriting code, and changing the Gradle API, which is a big step. It's not clear to me why the plugin we have can't be improved. OK, maybe split out testing into a separate plugin - why does that imply the existing one has to be scrapped? I'm sympathetic to Chris' point that it feels the new plugin would have many of the same tasks as the old one. If refactoring really isn't possible, it'd be good to have a robust explanation here.

2019-07-17 14:20 UTC, tudor-malene commented on docs/source/design/corda-gradle-plugin-v2/design.md
> +
The way I defined CorDapp in this doc is "any code that runs on Corda".

2019-07-17 14:23 UTC, tudor-malene commented on docs/source/design/corda-gradle-plugin-v2/design.md
> +
I need to elaborate more on this aspect, as it is a big advantage.

By reducing the scope of the "cordapp" plugin, and removing the custom configurations, the developer is free to use the library plugin.

2019-07-17 14:29 UTC, chrisr3 commented on docs/source/design/corda-gradle-plugin-v2/design.md
> +
I think my main point was that the `cordapp` plugin predates the new Gradle `api`, `implementation` and `runtimeOnly` configurations and so doesn't support them, i.e. dependencies added to any of these are not currently considered by the "semi-fat" jarring algorithm! 

I am prepared to leave the more philosophical question of whether a given CorDapp should be considered to be an application or a library in the developers' own hands. But the `cordapp` plugin should support both cases regardless.

2019-07-17 14:42 UTC, tudor-malene commented on docs/source/design/corda-gradle-plugin-v2/design.md
> +- Create a new plugin and deprecate the current one. The complexity of improving the existing plugin is too high.
We discussed this in person yesterday. I need to elaborate a bit more in the doc.

My idea is to remove the packaging responsibility from the `cordapp` plugin.

By default, the output will be just a thin jar as resulted from the `jar` task. ( containing all the metadata ).

If the developer wants to fat-jar stuff, they must use a packaging tool. 
We can create one, but there is already the shadow plugin. By default it fat-jars the entire `runtime`, but that can be easily customized. There's plenty of examples. It also supports filtering.

This approach is basically making fat-jarring into an advanced topic, which reflects the reality.

It definitely won't force shadow on people. 

The alternative is for us to implement more advanced packaging logic and maintain it..

2019-07-17 14:46 UTC, tudor-malene commented on docs/source/design/corda-gradle-plugin-v2/design.md
> +I'm personally not quite sure what the reason was for creating different metadata for contracts and workflows.
that's fine, but it doesn't mean that the label must be different, right?

The contracts jar can have:
`Cordapp-Licence: "Liberal licence"`

while the flows one would be:
`Cordapp-Licence: "Restrictive licence"`

This metadata is per jar

2019-07-17 14:47 UTC, tudor-malene commented on docs/source/design/corda-gradle-plugin-v2/design.md
> +-
this is a WIP document 
I have a feeling there's more :)

2019-07-17 14:54 UTC, tudor-malene commented on docs/source/design/corda-gradle-plugin-v2/design.md
> +TODO
Fair point. This is an iteration to sanity check the approach. Not the final proposal.

The mental overhead of keeping both approaches working at the same time seems huge to me.
I'll elaborate on this.

2019-08-15 14:47 UTC, tudor-malene commented
Ready for a re-review.
Best to start with the index: 
https://github.com/corda/corda/pull/5301/files#diff-c4fc198a8aea3cf4e7f199bd4716fc6cR1

2019-08-20 17:32 UTC, shamsasari requested changes
Can you put everything into a single file for a clear design narrative. It wasn't helpful having to navigate to different files.

2019-08-20 17:32 UTC, shamsasari commented on docs/source/design/corda-gradle-plugin-v2/jar-signer.md
> +# Jar signing gradle plugin
It's not clear why changes to the jar signing process in the gradle plugin needs to change for this design.

2019-08-20 17:32 UTC, shamsasari commented on docs/source/design/corda-gradle-plugin-v2/cordapp-v2.md
> +        // Same as before but moved from the contract or workflow blocks.
What's the reason for not using the existing `contract` and `workflow` blocks? Unless there's some major underlying design hole in them we shouldn't introduce new concepts or discard them so easily.

2019-08-20 17:32 UTC, shamsasari commented on docs/source/design/corda-gradle-plugin-v2/cordapp-v2.md
> +    // If `onLedgerCode=true` or the `secure-dependency-constraints` plugin was included, all these dependencies
What does the `secure-dependency-constraints` plugin do? Is it described somewhere else? Why does it exist if we have `onLedgerCode`?

2019-08-20 17:32 UTC, shamsasari commented on docs/source/design/corda-gradle-plugin-v2/cordapp-v2.md
> +        - to include the ``dependency-constraints`` and add cryptographic proofs to dependencies.
I'm not sure what this means. What cryptographic proofs are added to dependencies?

2019-08-20 17:32 UTC, shamsasari commented on docs/source/design/corda-gradle-plugin-v2/cordapp-v2.md
> +Also, know as "contract JARs", these will no longer be distributed by default as semi fat-jars, but as normal jars with cryptographic links to their dependencies.
typo: known

2019-08-20 17:32 UTC, shamsasari commented on docs/source/design/corda-gradle-plugin-v2/cordapp-v2.md
> +Currently, all installed CorDapps are loaded in the same classloader, but this will change when CorDapps will be isolated.
This sentence feels like it's a note, and not an actual element of the design.

2019-08-20 17:32 UTC, shamsasari commented on docs/source/design/corda-gradle-plugin-v2/cordapp-v2.md
> +There should be a command line utility ``install -cordapp com.foo:foo-cordapp:1.0 -repository ... -user -password``.
I think it better than the gradle plugin does all of this and package up the CorDapp and its dependencies into a single zip file, and we update the node to understand that a zip file means a self-contained CorDapp with dependencies. We can introduce a new gradle task that does this packaging.

Having a separate tool means duplicating repo settings and the like, and it's an extra step that needs to be performed, while the packaging gradle task can simply replace the existing `jar` that's used today.

2019-08-20 17:32 UTC, shamsasari commented on docs/source/design/corda-gradle-plugin-v2/cordapp-v2.md
> +Note that this type of structure could support multiple simultaneous versions, because a self-contained classloader can be created from each of these folders.
Can you make it clear that this design is not going to introduce separate classloaders for CorDapps, as you've mentioned this end-goal several times without elaborating that it's a future piece of work.

2019-08-20 17:32 UTC, shamsasari commented on docs/source/design/corda-gradle-plugin-v2/cordapp-v2.md
> +Given that the output is not a fat-jar any more, all custom ``cordaFoo`` configurations are now removed.
Rather than simply removing them and causing gradle to pick up the error, we should throw an helpful error message with perhaps a link to the docs explaining how to migrate to the new way.

2019-08-20 17:32 UTC, shamsasari commented on docs/source/design/corda-gradle-plugin-v2/cordapp-v2.md
> +All sub-blocks like ``contract``, ``workflow``, ``info`` will be removed and the metadata must be declared in the main block.
You need to explain why these are being removed.

2019-08-21 08:41 UTC, tudor-malene commented
> Can you put everything into a single file for a clear design narrative. It wasn't helpful having to navigate to different files.

Umm, I hoped the index file would make things easier.
I described there how to read the design. 
There's multiple pieces here. 
The secure dependencies plugin will be usable on its own .

2019-08-21 08:42 UTC, tudor-malene commented on docs/source/design/corda-gradle-plugin-v2/secure-dependencies.md
> +In case of a detected conflict, a dependency present in the root file takes precedence over one declared in a dependency.
That is exactly it. 
A dependency found in the root is pretty much one "forced" by the developer.

2019-08-21 08:44 UTC, tudor-malene commented on docs/source/design/corda-gradle-plugin-v2/secure-dependencies.md
> +This library contains a (URL?)Classloader that is able to read the ``META-INF/DEPENDENCY-CONSTRAINTS`` of all the loaded JARs and enforce the constraints.
The design for secure dependencies doesn't really care how you pin the root.
It could be by signature or by hash.
It assumes that the root of trust was established outside.

I should update the doc to reflect this, as it's not obvious.

2019-08-21 08:45 UTC, tudor-malene commented on docs/source/design/corda-gradle-plugin-v2/jar-signer.md
> +# Jar signing gradle plugin
This is the part of the doc that's the least impacted.
One factor is that the name "signing" collides with a default plugin, and the other is that it's not really a corda specific concern.

2019-08-21 08:49 UTC, tudor-malene commented on docs/source/design/corda-gradle-plugin-v2/cordapp-v2.md
> +        // Same as before but moved from the contract or workflow blocks.
Well, CorDapp code can also be an SDK or some other reusable library.

The thinking is that metadata like licensing, versioning would apply to any code that runs on Corda.

And, since this is a new plugin, that users will opt-in to, there is no point really in carrying that extra syntax.

In the current design, code that runs on ledger is marked with a special flag.

2019-08-21 08:51 UTC, tudor-malene commented on docs/source/design/corda-gradle-plugin-v2/cordapp-v2.md
> +    // If `onLedgerCode=true` or the `secure-dependency-constraints` plugin was included, all these dependencies
Yes, it's described in a separate file in this design.
`onLedgerCode` is just declaring the intent of this code.
Base on this information, the dependencies plugin is included and configured with sensible defaults. The dependencies plugin will pin the hash of the dependencies inside the output jar.

2019-08-21 08:53 UTC, tudor-malene commented on docs/source/design/corda-gradle-plugin-v2/cordapp-v2.md
> +        - to include the ``dependency-constraints`` and add cryptographic proofs to dependencies.
Hashes of the dependency jars.

E.g: `FooContract` depends on `guava:2.16`. 
Before building the cordapp jar, the plugin will detect the dependency on guava, and will add the hash of the guava:2.16 jar into a file that will be included in the output jar.

2019-08-21 08:53 UTC, tudor-malene commented on docs/source/design/corda-gradle-plugin-v2/cordapp-v2.md
> +There should be a command line utility ``install -cordapp com.foo:foo-cordapp:1.0 -repository ... -user -password``.
Fair point.
I'll add this as an alternative.

2019-08-21 08:56 UTC, tudor-malene commented on docs/source/design/corda-gradle-plugin-v2/cordapp-v2.md
> +Given that the output is not a fat-jar any more, all custom ``cordaFoo`` configurations are now removed.
My bad, I worded this badly.
Given that this is a new plugin, they're not really removed. 
A user that will migrate to the new plugin, will have to replace the old plugin id with the new one, so there will be no error.

2019-08-21 09:00 UTC, shamsasari commented on docs/source/design/corda-gradle-plugin-v2/secure-dependencies.md
> +In case of a detected conflict, a dependency present in the root file takes precedence over one declared in a dependency.
Yes of course.

2019-08-21 10:08 UTC, mnesbit commented
I am really struggling to follow this PR, but it is a key architectural decision. My feeling is this needs full rewrite to make it clearer and probably a design workshop/whiteboarding session. Ideally also with some diagrams.
1. The plugin does far too much today. We should not continue this and should decompose it into a series of smaller problems. This will also make the document clearer and probably several smaller PRs.
2. There needs to be a much clearer up front description of the requirements and motivations for this. I am aware of reasons such as to allow a component reseller market, to make us better able to handle gradle 5, but we need to detail them so that we can consider how well the chosen options fit.
3. I need clarity on the dependency logic and how it will interact with classloaders and sandboxing. I currently can't see how we would manage to enforce any of this and I don't get how it will interact with contract composition, or version evolution.
4. What about people who aren't using gradle? We have people who don't and I don't want to leave them stranded.
5. The focus on hashes is very inflexible as to my mind it risks locking in known broken libraries. So what is the escape route. We already had to switch to a publishing key approach elsewhere and this looks likely to repeat that mess. Can we consider alternative signature based approaches.
6. State and workflow plugins should be separate considerations, which may well be discussed here, but I am having problems following the dialogue.

2019-11-14 16:50 UTC, fenryka commented
Closing as design docs and discussion are being moved out of the Corda Repo

2019-11-14 16:50 UTC, closed without merging