Tech white paper refresh
corda/corda pull request #5329
Opened 2019-07-26 08:50 UTC by mikehearn

Merge a major refresh of the tech white paper. There's lots of new content, all content was updated to reflect the final design and the paper has been reorganised to make it clearer what's implemented and what's not.

2019-07-31 09:37 UTC, josecoll requested changes
Some great new stuff in this paper.
My review comments break down into:
- grammar, typos, missing/incorrect references
- suggestions on section title name changes
- highlighting older items that seem redundant/less relevant now (and perhaps could be removed)
- versioning

2019-07-31 09:37 UTC, josecoll commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> +taken to ensure only a single certificate laying claim to a name/key pair was issued, as the platform as this time
typo: as the platform **at** this time

2019-07-31 09:37 UTC, josecoll commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> -\item [Timestamp] When present, a timestamp defines a time range in whic
detail below => in section 6.3 (a few more pages later)

2019-07-31 09:37 UTC, josecoll commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> -\item [Timestamp] When present, a timestamp defines a time range in whic
is there such thing as the Google/Amazon timeline? (this was previously the Java timeline *with reference)

2019-07-31 09:37 UTC, josecoll commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> -\item [Timestamp] When present, a timestamp defines a time range in whic
The sentence "Embedding the JVM specification in the Corda specification" doesn't really make sense.
What is the Corda specification?
What do you mean by embedding the JVM within the Corda specification?

2019-07-31 09:37 UTC, josecoll commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> -\item [Timestamp] When present, a timestamp defines a time range in whic
"Current versions of the platform" => decouple current state of code from textual explanation.

2019-07-31 09:37 UTC, josecoll commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> -\item [Timestamp] When present, a timestamp defines a time range in whic
"This feature is discussed later." => what feature specifically? 
(ps: I know this was in the original WP)

2019-07-31 09:37 UTC, josecoll commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> -\item [Timestamp] When present, a timestamp defines a time range in whic
missing comma => Within a transaction,

2019-07-31 09:37 UTC, josecoll commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> -\item [Timestamp] When present, a timestamp defines a time range in whic
I find this section very rambling .... and it doesn't mention anything about "how package namespace claiming should be performed " (eg. network operator needs to accept/add to network parameters).

2019-07-31 09:37 UTC, josecoll commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> -\item [Timestamp] When present, a timestamp defines a time range in whic
"Bug fixes" doesn't seem appropriate/necessary in this title section.

2019-07-31 09:37 UTC, josecoll commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> +Having defined various kinds of abstract token, the SDK goes on to define (finally!) \texttt{Money} and
remove "(finally!)"

2019-07-31 09:37 UTC, josecoll commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> +\item Message queue brokers provide significant amounts of infrastructure for building reliable apps
The Observables mechanism does not provide adequate reliability/recovery (nor back-pressure) as it is not tied into MQ.

2019-07-31 09:37 UTC, josecoll commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> +magnitude. Contract logic only executed only a few times will be run interpreted, avoiding the overhead of
grammar error (remove an "only"): only executed only

2019-07-31 09:37 UTC, josecoll commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> +\section{Privacy}\label{sec:privacy}
This top-level section feels a bit out of place as it is a summary of stuff discussed previously (but before a lot more stuff discussed on future work).
Perhaps move to Conclusion.

2019-07-31 09:37 UTC, josecoll commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> +\paragraph{Key randomisation.}The vault generates and uses random keys that are unlinkable to an identity.
This is not the Vault's functionality, but the Key Management service's.

2019-07-31 09:37 UTC, josecoll commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> +ledger and validating it using secure hardware enclaves. This can provide the benefits of homomorphic encryption
Add refs where new technology concepts first introduced: ZKP, homomorphic encryption.

2019-07-31 09:37 UTC, josecoll commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> +\subsection{Secure signing devices}\label{sec:secure-signing-devices}
This original section is very lengthy and talks a lot about TREZOR and wallet based smart signing devices (YES/NO screen, etc).
Feels less relevant now that strategically we are not targeting the consumer market.

2019-07-31 09:37 UTC, josecoll commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> +\subsection{Data distribution groups}
This is something we have continuously punted to the back of our backlog.
Should we just remove it and/or combine it with the new Guaranteed Data Distribution section?

2019-07-31 09:37 UTC, josecoll commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> +\subsection{Guaranteed data distribution}
This is a great new section but I feel the title is incorrect (or at most misleading).
Rename to "Transaction data distribution"?

2019-07-31 09:37 UTC, josecoll commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> +much CPU power. A prototype of such a library already exists.
Add reference to GitHub source code.

2019-07-31 09:37 UTC, josecoll commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> +\subsection{Data streams}\label{subsec:data-streams}
Great new section ... but it would ideally sit close to the previous section/explanation of Attachments.

2019-07-31 11:48 UTC, josecoll requested changes
The Conclusion section definitely needs updating (to remove all the "financial" market conotations).
A few other minor comments.

2019-07-31 11:48 UTC, josecoll commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> +to model with flows not just multi-party protocols but higher level business processes which may include human
Reads poorly. Perhaps:
"As well as multi-party protocols, a common need is to model flows with higher level business processes which may include human interaction"

2019-07-31 11:48 UTC, josecoll commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> +Today such tasks can be achieved by splitting a flow up and having UI logic update shared database tables. But
substitute: But => However,

2019-07-31 11:48 UTC, josecoll commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> +Individuals and groups of individuals within an organisation would be modelled as parties that can be looked up via a
Don't make this prescriptive ... there are 101 ways to integrate/map identities within an organisation.

2019-07-31 11:48 UTC, josecoll commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> +don't provide a universal solution: most research has focused on tokens and provides limited or no value to
Define "tokens" in this context (ie. readers may confuse with previous description of Corda tokens in 6.11 Tokens section).

2019-07-31 11:48 UTC, josecoll commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> +technology are found; as of writing this ``TCB recovery'' process has been used several times.
recommend add a reference for "TCB recovery"

2019-07-31 11:48 UTC, josecoll commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> +We have presented Corda, a decentralised database designed for the financial sector. It allows for a unified data
update "financial sector" references to more general purpose ones adopted in the new Intro.

2019-07-31 11:48 UTC, josecoll commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> +A standard type system is provided for the modelling of financial logic. The design considers security throughout:
for the modelling of "cross-sector, industry wide" logic (or something more generic than "financial").

2019-07-31 11:48 UTC, josecoll commented on docs/source/whitepaper/corda-technical-whitepaper.tex
>  Finally, the platform defines standard ways to integrate the global ledger with financial infrastructure like high
Possible remove this sentence completely and/or rephrase to capture multiple different industry verticals.

2019-08-01 08:36 UTC, roger-that-dev reviewed
Just some comments on section 5.3.

2019-08-01 08:36 UTC, roger3cev commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> +This feature must be used with care. There's no way for the private key to be held outside the node at the time
Not strictly true as Thomas demonstrated: https://r3-cev.atlassian.net/wiki/spaces/RI/pages/129539443/R3+Engineering+Team+Tech+Talks?preview=/129539443/1144914293/android-signing-demo.mp4

2019-08-01 08:36 UTC, roger3cev commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> +(see~\cref{sec:secure-signing-devices}). Moreover it's only reasonable to do this in specific situations, such
We should remove this sentence. As currently written, it will turn people off using the accounts feature for THEIR customers when that’s all what people want to use it for! No-one actually wants to use it for employee signing currently and indeed, the accounts feature primarily WASN’T created to support accounts for employees.

2019-08-01 08:36 UTC, roger3cev commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> +as when the signer of a transaction is an employee of the organisation hosting the node. This is because whilst
True but it is up to CorDapp developers to assess this trade-off themselves and for most it is probably acceptable given that we are soon going to deliver out of node key generation and signing - it is on the roadmap.

2019-08-01 15:55 UTC, mikehearn commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> +to the notion of a hard fork.
How about this:

> In proof-of-work based block chain systems a hard fork creates two split views of the ledger that
then proceed to evolve independently, with each side remaining in some strictly technical sense `usable' by parties on each side of the fork. Consensus will only be lost over transactions where both sides do really disagree and for any transaction that traces its origin back to a post-fork coinbase transaction. But in Corda, there is no way to continue past an unacceptable change in the network parameters and remain on the `losing side'. Thus the notion of flag days is subtly different to the notion of a hard fork.

2019-08-01 15:59 UTC, mikehearn commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> +\subsection{Protocol versioning}\label{subsec:protocol-versioning}
This is a point on which reasonable people can disagree. They're unified deliberately, for two reasons:

1. Most parts of the Corda protocol are defined by object serialisation. Thus the API and the protocol are closely related: most protocol changes require API changes and many API changes imply protocol changes. So almost all of the time the two versions would increment together anyway. Although they *could* be kept separate, this would introduce the possibility of accidentally not keeping them in sync properly. This opens the potential for obscure bugs.
2. We've committed to backwards compatibility for the protocol. So, it doesn't really matter how often we increment the version: client logic just has to check that the peer version isn't *lower* than what it needs. It can be arbitrarily *higher*.

2019-08-01 15:59 UTC, mikehearn commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> +The protocol data structures are reflected in the platform API, which is therefore versioned in an identical
In Corda they are not distinct, see above.

2019-08-01 16:00 UTC, mikehearn commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> +others. The platform provides a notion of membership management via the `business network management service'
From the user's perspective it's all "stuff provided by the Corda people" - our strange packaging would be a distraction at this point in the text. The BNMS work really should be a part of the platform: having it be separated has some downsides, but from the user's perspective, it's all just Corda.

2019-08-01 16:05 UTC, mikehearn commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> -\item [Timestamp] When present, a timestamp defines a time range in whic
I added a citation for https://developers.google.com/time/smear

2019-08-01 16:06 UTC, mikehearn commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> -\item [Timestamp] When present, a timestamp defines a time range in whic
Well ..... you're gonna *love* this, but the tech white paper + API docs + protocol docs I wrote are currently the closest thing to a spec we have. The goal is that one day we have a full, standalone Corda specification that describes the protocol independently of the code, but, that's a lot of work.

2019-08-01 16:10 UTC, mikehearn commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> -\item [Timestamp] When present, a timestamp defines a time range in whic
Hmm. I was trying to communicate the idea that disputes may often arise due to bugs. I can take it out though. @gendal WDYT?

2019-08-01 16:11 UTC, mikehearn commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> +\section{Privacy}\label{sec:privacy}
Hmm. I see your point but I'd worry that not having a top level section on privacy would make it seem like we don't care about it. @gendal ?

2019-08-01 16:12 UTC, mikehearn commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> +ledger and validating it using secure hardware enclaves. This can provide the benefits of homomorphic encryption
Hmm, these are general crypto terms, I'm not sure what refs to use. Perhaps very old papers that originally defined them? But that could go back decades.

2019-08-01 16:13 UTC, mikehearn commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> +\subsection{Secure signing devices}\label{sec:secure-signing-devices}
We've never targeted the consumer market - the intention here was to keep a company secure in the presence of a compromised node, by issuing employees with signing devices. This also has the (desirable? undesirable?) side effect of allowing transactions to be traced back to individual employees cryptographically.

2019-08-01 16:14 UTC, mikehearn commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> +\subsection{Data distribution groups}
It's in the future work section and there's always a lot of interest in it. I think it'll get done sooner or later. A firm in the community has even volunteered to work on implementing it!

2019-08-01 16:16 UTC, mikehearn commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> +\subsection{Guaranteed data distribution}
It's actually in the old paper too, it got moved to the "future work" section. 

Maybe could rename - but Corda already handles transaction data distribution, so that might be a bit confusing. This section describes a failsafe for the case where a node doesn't follow the protocols.

2019-08-01 16:17 UTC, mikehearn commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> +much CPU power. A prototype of such a library already exists.
Ah, you caught me :( I'd have to actually publish it first. There's a plan for me and Kat to combine our code ... but mine still has a few small bugs. I was going to fix them first. Then I guess I can go back and add a link here.

2019-08-01 16:17 UTC, mikehearn commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> +\subsection{Data streams}\label{subsec:data-streams}
It's in the "future work" section so it can't be physically close to the attachments section. This is an unfortunate side effect of more clearly separating implemented vs non-implemented features.

2019-08-01 16:18 UTC, mikehearn commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> +to model with flows not just multi-party protocols but higher level business processes which may include human
Used it.

2019-08-01 16:19 UTC, mikehearn commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> +Individuals and groups of individuals within an organisation would be modelled as parties that can be looked up via a
would -> could

2019-08-01 16:22 UTC, mikehearn commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> +don't provide a universal solution: most research has focused on tokens and provides limited or no value to
They're pretty much the same in this context (coins, tokens, etc).

2019-08-01 16:27 UTC, mikehearn commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> +technology are found; as of writing this ``TCB recovery'' process has been used several times.
Annoyingly the only reference I can find is in a SlideShare presentation! Intel's docs on this process could be a lot better, suffice it to say! I've added a footnote.

2019-08-01 16:54 UTC, gendal commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> +\section{Privacy}\label{sec:privacy}
I think we should have a section with this title.... we make such a big song and dance about it after all

2019-08-02 09:02 UTC, josecoll submitted a review, later dismissed
LGTM! 
Versioning is what it is, so no more comments in this PR.

2019-08-02 09:05 UTC, josecoll commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> +\section{Privacy}\label{sec:privacy}
Right, my point is that perhaps this could be summarised in a paragraph in the Conclusion (as it currently sits in a strange place within the overall document and breaks continuity).
Anyway ... no big deal.

2019-08-02 09:06 UTC, josecoll commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> +ledger and validating it using secure hardware enclaves. This can provide the benefits of homomorphic encryption
No problem - I'm sure the curious reader would quickly google these (as I had to).

2019-08-12 14:39 UTC, mikehearn commented
Alright, another try!

Last call for comments, <whistle> the train is leaving the station, parp parp!

2019-08-14 01:47 UTC, rogersanick commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> +of the total work a bank actually does.
The introduction seems focused on banks. I recognize this use case is historically front and center, but given that we are now targeting (and developing for) a broader array of use cases, we should consider referencing other business entities.

e.g. - “In the financial sector the effort of keeping different databases synchronised, reconciling that synchronization and resolving the ‘breaks’ or ‘conflicts’ that occur in the aftermath represent a significant fraction of the total work a bank (or any other commercial entity) actually does.”

2019-08-14 01:49 UTC, rogersanick commented on docs/source/whitepaper/corda-technical-whitepaper.tex
>  \item Who would run this database? Where would we find a sufficient supply of angels to own it?
The meaning of the term ‘angel’ wasn’t immediately apparent to me. This could be my being uninformed - is it a term that's widely used and understood? We could substitute for something more explicit like - `trustworthy third-parties.`

2019-08-14 01:50 UTC, rogersanick commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> +\item Nodes are arranged in an authenticated peer to peer network. All communication is direct. Gossip is not used.
While this is apparent to 99% of our audience, it couldn’t hurt to be more descriptive here.

e.g. Gossip is not used --> "A gossip protocol is not used."

2019-08-14 01:56 UTC, rogersanick commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> +on the fly to be fully deterministic, and to implement deterministic execution time quotas.
In the list of novel features, we do not describe P2P transaction verification. This might be worthwhile to mention - it seems novel as compared to other DLT platforms.

* “New transaction types can be defined using JVM bytecode. The bytecode is statically analyzed and rewritten on the fly to be fully deterministic, and to implement deterministic execution time quotas.”
* + “This bytecode is mutually verified by all counterparties relevant to the transaction, ensuring the validity of ledger updates contained therein.”

2019-08-14 02:05 UTC, rogersanick commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> +time, by anyone.
We could expand on this point to help the reader understand why issuance transactions have significance. This also transitions well into the next section.

For example - "Issuance transactions may append new states to the database without consuming any existing states but unlike in Bitcoin these transactions are not special. In Bitcoin, issuance transactions represent value creation and facilitate a crypto-economic incentivize. This, in turn, motivates validators or miners. In Corda, there is no need for a crypto-economic incentive and so issuance transactions may be created at any time, by anyone to issue arbitrary data onto the ledger.

2019-08-14 02:06 UTC, rogersanick commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> +than QRcodes to identify a counterparty.
This makes sense if you’ve seen a bitcoin wallet QR code, but in the unlikely scenario one of our readers has not context couldn't hurt.

e.g. - “And user-facing applications rely on auto-completion and search to specify human-readable legal identities rather than specific public keys - which in the bitcoin ecosystem are often distributed as QR codes.”

2019-08-14 02:08 UTC, rogersanick commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> +\paragraph{Flag days and hard forks.}There must be a mechanism for the parameters to be updated. Each signed
At first glance this title makes it seem like we have both. Should we consider changing it to: 
- “Flag days vs. hard forks.”

2019-08-14 02:15 UTC, rogersanick commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> +context to other states but which is only changed from time to time. Note that the pointed to state must be unconsumed
This is likely too pedantic but context is provided to the verifying smart contract in relation to other states - not to the states themselves. How about:
- “Reference states are useful for importing data which provides context to a verifying smart contract in its analysis of other states."

2019-08-14 02:17 UTC, rogersanick commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> +transaction will not be notarised. In this way, non-consuming inpu
CFOs might as well be gender-neutral - "e.g. their subordinates"

2019-08-14 02:21 UTC, rogersanick commented on docs/source/whitepaper/corda-technical-whitepaper.tex
> +A micronode is a program that performs some but not all of the functions of a regular node. Micronodes may be suitable
What is the benefit of a micro-node? It could be helpful to start to make this clear at the outset of the section.

- “A micronode is a program that performs some but not all of the functions of a regular node 
- `+` "with the advantage of a smaller footprint to accommodate a broader array of computing devices”

2019-08-14 11:10 UTC, mikehearn commented on docs/source/whitepaper/corda-technical-whitepaper.tex
>  \item Who would run this database? Where would we find a sufficient supply of angels to own it?
It's informal language, in the hope of making the intro less dry/more readable. It means literally, the Christian notion of an angelic being who is purely good and never sins. But if it's confusing then we could replace it with more technical language for sure.

2019-08-14 19:52 UTC, mikehearn commented
@rogersanick Thanks, useful review! I mostly just copied your suggestions. How does it look now?

2019-08-15 10:04 UTC, rogersanick commented
No problem at all - thanks for incorporating! LGTM!

2019-08-16 10:56 UTC, gendal commented
ok.... so I've just read it from start to finish. Only looking for major comments at this stage.

5.2 Confidential Identities.  The BIP32/HD Wallets discussion. Add a line to clarify that this would be future work?

6.6 Package namespace ownership. "Corda allows parts of the Java package namespace to be reserved for particular developers with a network".   s/with/within/ ?

7.1 A touch of the Paul McCartneys... "of which they can prove ownership of to others"... "this ever-changing world in which we live in"

Energy consumption... isn't bitcoin now at the level of a small COUNTRY?  https://digiconomist.net/bitcoin-energy-consumption (Austria?)

14 Acknowledgements...  remove me from this if I'm named on the front? (and change author to authors)?

2019-08-20 08:45 UTC, mikehearn commented
@gendal Mauve, as ordered! Our bikes never looked so good.

2019-08-21 08:52 UTC, gendal approved these changes
A momentous occasion! We should invite the queen to the opening of the bike shed.

2019-08-22 17:23 UTC, mikehearn commented
Merged! (manually)

I also tweaked the start page of the docsite whilst I was at it.

2019-08-22 17:23 UTC, closed without merging