TM-3
corda/corda pull request #5377
Opened 2019-08-20 12:25 UTC by Schife

created new tasks: one that copies all the xml files under a submodule to the root build folder and the other to use those xml files to create a JUnit report out of them. Also increased the size of the cache to 2 GB since the task was running out of memory

2019-08-20 14:09 UTC, zkiss commented on build.gradle
> +    antJUnit
I'm not sure I like this as a pattern, as I don't know if it scales. I naively would have added whatever lib the build needs on the classpath to `buildscript.dependencies`. Is this not a good option here for some reason?

2019-08-20 14:09 UTC, zkiss commented on build.gradle
> +task mergeJUnitReports {
Can we please extract this logic in `buildSrc`? Let's make some effort to reduce the complexity of the build script.

2019-08-20 14:09 UTC, zkiss commented on build.gradle
> +                classname: 'org.apache.tools.ant.taskdefs.optional.junit.XMLResultAggregator',
I don't feel too good about using an ant task here.

Ant is an ancient piece of tech, and the functionality we're reusing appears to be quite trivial. I'd simply rewrite it and spare us the extra external dependency. Not sure where others stand on this.

Rewriting it would definitely allow us to use constant memory for xml merging and would not require the increase of xmx in the build.

2019-08-20 14:12 UTC, Schife commented on build.gradle
> +    test.finalizedBy(copyReport)
I would assume the test cycle in gradle would handle all types of tests but I might be wrong

2019-08-20 14:16 UTC, Schife commented on build.gradle
> +                classname: 'org.apache.tools.ant.taskdefs.optional.junit.XMLResultAggregator',
Well this is part of the ant JUnit plugin and I'm not sure why you would consider trivial since besides merging all the reports it does generate the html report

2019-08-20 14:17 UTC, Schife commented on build.gradle
> +task mergeJUnitReports {
mergeJUnitReports can be moved to buildSrc

2019-08-20 14:20 UTC, Schife commented on build.gradle
> +    task copyReport(type: Copy) {
The copyReport task should only be run as a final step after everything under the gradle test cycle has finished so I think that this current format it is a lot clearer as to what and when is it supposed to do it compared to your suggestion

2019-08-20 14:31 UTC, Schife commented on build.gradle
> +task mergeJUnitReports {
Just tried moving it and it doesn't seem to work anymore as it won't find it anymore. I might just not be familiar enough with invoking a task that lives in the buildSrc build.gradle

2019-08-20 14:40 UTC, Schife commented on build.gradle
> +    antJUnit
This was most likely caused by my own ignorance as I honestly don't really understand how the gradle build file hangs together and because of that i was uncertain as to where to put these

2019-08-20 14:53 UTC, r3domfox commented on build.gradle
> +                classname: 'org.apache.tools.ant.taskdefs.optional.junit.XMLResultAggregator',
Let's, ah, _defer_ rewriting the ancient XSLT that generates the report. I agree that a constant-time streaming transform is possible, but this doesn't seem like the most urgent problem to be solving right now.

2019-08-20 16:32 UTC, zkiss commented on build.gradle
> +                classname: 'org.apache.tools.ant.taskdefs.optional.junit.XMLResultAggregator',
Maybe I am missing the point in what we're trying to achieve here, so please bear with me.

We're trying to parallelise the build, correct?
We do not want to change what it does and the build artifacts it produces, do we?

By distributing the tests on multiple workers the existing gradle task for testing will produce xmls only for the tests it ends up running. It would generate an html report as well, however it would also be partial, and this is the issue, correct? We need to produce the same html report that our existing build does, that includes all the tests.

I originally missed the point that we also need to (re)produce a html report for all the tests globally.

I still don't feel good about using an ant task for this, so I'll ask this final question: could we consider, instead of it, looking at what [gradle does](https://github.com/gradle/gradle/blob/master/subprojects/testing-base/src/main/java/org/gradle/api/tasks/testing/AbstractTestTask.java#L549) and somehow replicate it? After taking a glance, it does not seem too hard to construct the objects the testReporter needs to produce an HTML report.
- org.gradle.api.internal.tasks.testing.junit.result.BinaryResultBackedTestResultsProvider implements parsing the binary test results.
- BuildOperationExecutor should be easy to obtain from gradle

2019-08-20 16:38 UTC, Schife commented on build.gradle
> +                classname: 'org.apache.tools.ant.taskdefs.optional.junit.XMLResultAggregator',
I believe the thing you're suggesting is what Stefano is currently attempting to do in the KubesReporting file on the branch. Hence why this work might be redundant. But we don't know if it will actually work in practice so we're keeping this work as it is since it works as a backup

2019-08-20 21:55 UTC, gendal commented
What is this? The PR title is incomprehensible ("TM-3" ???) and I can't figure out what #5377 is. https://r3-cev.atlassian.net/browse/CORDA-5377, for example, leads nowhere.

2019-08-28 15:40 UTC, roastario requested changes
This looks good - just marking it as "changes required" to put them into the holding pen for a bit. 

I've taken your code and integrated it into the PoC build branch.

2019-09-17 08:50 UTC, closed without merging