WIP Kubenetes parallel build
corda/corda pull request #5396
Opened 2019-08-26 12:44 UTC by roastario

2019-08-26 12:57 UTC, roastario commented
5396

2019-09-02 12:31 UTC, zkiss submitted a review, later dismissed
Overall looks good, few questions.

2019-09-02 12:31 UTC, zkiss commented on buildSrc/src/main/java/net/corda/testing/KubesReporting.java
> + * Shameful copy of TestReportTask - modified to handle results from k8s testing.
If I understand this correctly, this is a copy of a piece of code that already exists somewhere but we needed changes to it and copying the code was the only way to make that change, is it correct?

In this case, please can you add a link to the original code and an explanation on what the main difference is and why it was not possible to use it? This information helps us reevaluate our situation in the future as things evolve.

2019-09-02 12:31 UTC, zkiss commented on buildSrc/src/test/groovy/net/corda/testing/ListTestsTest.groovy
> +        for (int numberOfTests = 1; numberOfTests < 100; numberOfTests++) {
please also test the `numberOfTests = 0` case.

2019-09-02 12:31 UTC, zkiss commented on core/src/test/java/net/corda/core/concurrent/ListingTest.java
> +    public void test() {
is this test intentionally left here? Why?

2019-09-02 12:31 UTC, zkiss commented on gradle/wrapper/gradle-wrapper.properties
> +#Wed Aug 21 10:48:19 BST 2019
This is an autogenerated file, correct? Should we commit this to git?

2019-09-02 12:31 UTC, zkiss commented on node/src/integration-test/kotlin/net/corda/node/NodeRPCTests.kt
> +@Ignore
intentional?

2019-09-02 12:31 UTC, zkiss commented on node/src/integration-test/kotlin/net/corda/node/persistence/H2SecurityTests.kt
> +import net.corda.node.flows.isQuasarAgentSpecified
appears to be unused

2019-09-02 13:10 UTC, roastario commented on build.gradle
> +            "gitNotAvailable"
good idea, will add log line and remove camel case

2019-09-02 13:10 UTC, roastario commented on buildSrc/build.gradle
> +    compile gradleApi()
buildSrc automatically has the gradleAPI added as a dependency - I just thought it would be better to explicitly add this as a dependency, so if these plugins were ever moved out into their own project - it would be clear it's required.

2019-09-02 13:11 UTC, roastario commented on buildSrc/build.gradle
> +    compile 'com.bmuschko:gradle-docker-plugin:5.0.0'
will fix.

2019-09-02 13:12 UTC, roastario commented on buildSrc/src/main/groovy/net/corda/testing/KubesTest.groovy
> +        def gitSha = new BigInteger(project.hasProperty("corda_revision") ? project.property("corda_revision").toString() : "0", 36)
yes, this might be an over-genericification. I'm half certain that these plugins will need to be moved into their own project - and potentially used for other r3 projects that don't have the revision available.

2019-09-02 13:12 UTC, roastario commented on buildSrc/src/main/groovy/net/corda/testing/KubesTest.groovy
> +        int k8sTimeout = 50 * 1_000
agreed - will fix.

2019-09-02 13:13 UTC, roastario commented on buildSrc/src/main/groovy/net/corda/testing/KubesTest.groovy
> +                .withWebsocketPingInterval(k8sTimeout * 6)
agreed - will fix.

2019-09-02 13:14 UTC, roastario commented on buildSrc/src/main/groovy/net/corda/testing/KubesTest.groovy
> +                System.out.println("deleting: " + podToDelete.getMetadata().getName())
so, logging in gradle is a bit of a mess - will try moving to logger.lifecycle and seeing if it appears.

2019-09-02 13:16 UTC, roastario commented on buildSrc/src/main/groovy/net/corda/testing/KubesTest.groovy
> +        String namespace = "thisisatest"
namespace is what kubenetes uses to "silo" tasks. All pods within a namespace are visible to each other as network endpoints and share common resources (such as registry credentials etc).

It's not used for anything outside of the KubesTest plugin. Will move it a private static const.

2019-09-02 13:16 UTC, roastario commented on buildSrc/src/main/groovy/net/corda/testing/KubesTest.groovy
> +        int numberOfNodes = 20
agreed - will fix.

2019-09-02 13:16 UTC, roastario commented on buildSrc/src/main/groovy/net/corda/testing/KubesTest.groovy
> +            client.pods().inNamespace(namespace).withName(podName).waitUntilReady(60, TimeUnit.MINUTES)
agreed - will fix.

2019-09-02 13:17 UTC, roastario commented on buildSrc/src/main/groovy/net/corda/testing/KubesTest.groovy
> +                String podName = (taskToExecuteName + "-" + stableRunId + suffix + i).toLowerCase()
agreed. Will prepend some info. I see the "buildId" parameter being used to make clear what type of build a pod is for, for example (PR-4567-test-...)

2019-09-02 13:19 UTC, roastario commented on buildSrc/src/main/groovy/net/corda/testing/KubesTest.groovy
> +                BufferedReader br = new BufferedReader(new InputStreamReader(stdOutIs))
true true. I was being lazy here - I was relying on the fact that this is always a short running application, and we can afford to have a few leaks. Migrate to groovy api.

2019-09-02 13:22 UTC, roastario commented on buildSrc/src/main/groovy/net/corda/testing/ListTests.groovy
> +        int consumedTests = numberOfTestsPerFork * forks;
so I will address the next few questions in this one comment review. 

Given: numberOfForks=3 and numberOfTests = 14
Then: numberOfTestsPerFork = (14/3) = 4 and consumedTests = 4*3 = 12

We have two "left over" tests. 

This is what the supplementary index is doing, it's basically saying: Take the slice you are responsible for AND if your supplementary index is within the copy.size() also take one of the left overs. 

This ensures that all tests are consumed.... I had many issues with this (see test case :P)

2019-09-02 13:22 UTC, roastario commented on buildSrc/src/main/groovy/net/corda/testing/ListTests.groovy
> +        int ourSupplementaryIdx = consumedTests + fork;
see above

2019-09-02 13:23 UTC, roastario commented on buildSrc/src/main/groovy/net/corda/testing/ListTests.groovy
> +        int numberOfTestsPerFork = Math.max((copy.size() / forks).intValue(), 1);
We still need the math.max() as there is a possibility that soemthing like forks=20 and tests=5, would result in 5/20 = 0.

2019-09-02 13:25 UTC, roastario commented on buildSrc/src/main/groovy/net/corda/testing/ListTests.groovy
> +        return toReturn.stream().filter { it -> it != null }.collect(Collectors.toList());
see above for logic about consuming supplementary tests. 

As for the padding, when combined with the fact that we are introducing a task specific seed (task.path.hashcode) _should_ result in different tasks allocating tests to different workers. 

If we didn't pad, and there was N tests, and K workers, and N<K - this would result in the first N workers ALWAYS being the ones allocated work. Whereas with the padding, this is not the case.

2019-09-02 13:26 UTC, roastario commented on core/src/test/java/net/corda/core/concurrent/ListingTest.java
> +    public void test() {
AAAAH, I've tried to delete this file about 7 times. It will be killed.

2019-09-02 13:26 UTC, roastario commented on buildSrc/src/test/groovy/net/corda/testing/ListTestsTest.groovy
> +        for (int numberOfTests = 1; numberOfTests < 100; numberOfTests++) {
oooh .... let's see what breaks.

2019-09-02 13:27 UTC, roastario commented on gradle/wrapper/gradle-wrapper.properties
> +#Wed Aug 21 10:48:19 BST 2019
it's not quite auto generated, I am changing the distribution of gradle to include source.

2019-09-02 13:27 UTC, roastario commented on node/src/integration-test/kotlin/net/corda/node/NodeRPCTests.kt
> +@Ignore
yes, this test is FaF .. flakey as ...

2019-09-02 13:27 UTC, roastario commented on node/src/integration-test/kotlin/net/corda/node/persistence/H2SecurityTests.kt
> +import net.corda.node.flows.isQuasarAgentSpecified
will kill.

2019-09-02 13:40 UTC, zkiss commented on buildSrc/src/main/groovy/net/corda/testing/ListTests.groovy
> +        return toReturn.stream().filter { it -> it != null }.collect(Collectors.toList());
Riiight... I didn't think of the fact that this runs _per module_. I thought we merge all tests into a global list and then distribute to workers. We could get the best of both approaches if we randomised the worker order per module, reproducibly.

2019-09-02 13:44 UTC, zkiss commented on buildSrc/src/main/groovy/net/corda/testing/ListTests.groovy
> +        int numberOfTestsPerFork = Math.max((copy.size() / forks).intValue(), 1);
Isn't that scenario prevented by the null padding above?

2019-09-02 13:44 UTC, zkiss commented on buildSrc/src/main/groovy/net/corda/testing/ListTests.groovy
> +                    c.getMethodInfo().filter { m -> m.hasAnnotation("org.junit.Test") }.collect { m -> c.name + "." + m.name }
Forgot to ask: Now that we list individual test methods, do we not want to make sure that the same worker gets all tests from the same class? I'm a bit worried that there is heavy initial setup done for each test class and that is done on more than one workers, generating more work than optimal. I'm OK ignoring this case as well, just want to make a conscious choice.

2019-09-02 13:52 UTC, zkiss commented on buildSrc/src/main/groovy/net/corda/testing/ListTests.groovy
> +        int consumedTests = numberOfTestsPerFork * forks;
Right, I think I get it. If we stick with the null padding approach, we could alter it so that it doesn't only happen when the number of tests is < forks, but always; meaning that the number of elements in the `copy` is always divisible by `forks`. That would lead to cleaner logic maybe?

2019-09-02 14:56 UTC, roastario commented on buildSrc/src/main/groovy/net/corda/testing/ListTests.groovy
> +                    c.getMethodInfo().filter { m -> m.hasAnnotation("org.junit.Test") }.collect { m -> c.name + "." + m.name }
hmmm, yes - you are right - the padding takes care of the division issue! will remove this extra line.

2019-09-02 17:35 UTC, chrisr3 requested changes
Errr... That was just a first look, but I didn't really  recognise it as a Gradle plugin. More like an embedded Groovy script... :thinking:

2019-09-02 17:35 UTC, chrisr3 commented on buildSrc/src/main/groovy/net/corda/testing/DistributedTesting.groovy
> +        if (!project.plugins.hasPlugin(ImageBuilding)) {
Just apply it anyway? Gradle should only allow you to apply each plugin once.

2019-09-02 17:35 UTC, chrisr3 commented on buildSrc/src/main/groovy/net/corda/testing/ImageBuilding.groovy
> +        DockerBuildImage buildDockerImageForSource = project.tasks.create('buildDockerImageForSource', DockerBuildImage) {
The `sgxjvm/sgx-jvm-plugin/sgx-jvm-plugin-host` project does something similar. But more Gradley...

2019-09-02 21:53 UTC, chrisr3 requested changes
Gradle Bunny says: "We're gonna need a bigger bag of carrots!" :carrot:

2019-09-02 21:53 UTC, chrisr3 commented on buildSrc/src/main/java/net/corda/testing/KubesReporting.java
> +                    throw new GradleException(message);
Which `GradleException`? E.g. `InvalidUserCodeException`, `InvalidUserDataException`?

2019-09-02 21:53 UTC, chrisr3 commented on buildSrc/src/main/java/net/corda/testing/KubesReporting.java
> +        } catch (RuntimeException e) {
Why only `RuntimeException`?

2019-09-02 21:53 UTC, chrisr3 commented on buildSrc/src/main/groovy/net/corda/testing/DistributedTesting.groovy
> +                    def fork = getPropertyAsInt(subProject, "dockerFork", 0)
I would expect to see all of the configuration properties set from within the `build.gradle` script rather than passed as Gradle properties - presumably via the command line here. The typical pattern would be (for a plugin in `buildSrc`):
```gradle
apply plugin: net.corda.testing.KubernetesThingy

kubernetesThingy {
    // An extension object for configuring all of the tasks that the plugin is creating.
    // This would be "lazy" Property objects whose values aren't actually computed
    // until Gradle has evaluated the project.
}
```
The two SGX plugins should provide useful examples how the basic Gradle 5.x APIs work.

2019-09-02 22:00 UTC, chrisr3 commented on buildSrc/build.gradle
>      }
Ah, I *deleted* the `canonicalizer` directory! :smiling_imp: But all the same, migrating this new plugin into a subdirectory of its own still makes sense. (You might want to add another plugin at some point in the future...)

2019-09-03 09:11 UTC, zkiss commented on buildSrc/src/main/groovy/net/corda/testing/DistributedTesting.groovy
> +        if (System.getProperty("kubenetize") != null) {
I think it would be nice if the behaviour was not affected by esoteric properties but the task invocation: ie if we want to build in parallel we'd invoke a `gradle buildParallel` and `gradle build` would be the normal build.

2019-09-03 09:26 UTC, roastario commented on node/src/integration-test/kotlin/net/corda/node/persistence/H2SecurityTests.kt
> +import net.corda.node.flows.isQuasarAgentSpecified
actually is used on line 34

2019-09-03 09:28 UTC, roastario commented on buildSrc/src/main/groovy/net/corda/testing/DistributedTesting.groovy
> +        if (System.getProperty("kubenetize") != null) {
Gradle system properties are Java System properties no?

2019-09-03 09:28 UTC, roastario commented on buildSrc/src/main/groovy/net/corda/testing/KubesTest.groovy
> +    static final ExecutorService singleThreadedExecutor = Executors.newSingleThreadExecutor()
yes - and it's horrible.

2019-09-03 09:30 UTC, roastario commented on buildSrc/src/main/groovy/net/corda/testing/ImageBuilding.groovy
> +                if (!gradleDir.exists()) {
ah, but these are really not output directories - they are only used to ensure that the building process will not affect the permissions on the user version of these directories (and also to help people using toy oses which do not have real docker)

2019-09-03 09:31 UTC, roastario commented on buildSrc/src/main/groovy/net/corda/testing/DistributedTesting.groovy
> +        if (!project.plugins.hasPlugin(ImageBuilding)) {
:+1:

2019-09-03 09:33 UTC, zkiss commented on node/src/integration-test/kotlin/net/corda/node/persistence/H2SecurityTests.kt
> +import net.corda.node.flows.isQuasarAgentSpecified
Interesting, the only change in this file is the new import, I wonder how it compiled before...

2019-09-03 09:38 UTC, roastario commented on buildSrc/src/main/java/net/corda/testing/KubesReporting.java
> +                    throw new GradleException(message);
This is actually a point of contention in the gradle world - there is no dedicated way to mark a build as failed. And in this case the TestExecutionException/BuildOperationException do not apply.

2019-09-03 09:39 UTC, roastario commented on buildSrc/src/main/java/net/corda/testing/KubesReporting.java
> +        } catch (RuntimeException e) {
I copied this badboy from the original gradle implementation!

2019-09-03 09:39 UTC, roastario commented on buildSrc/src/test/groovy/net/corda/testing/ListTestsTest.groovy
> +        for (int numberOfTests = 1; numberOfTests < 100; numberOfTests++) {
nuffin!

2019-09-03 09:40 UTC, chrisr3 commented on buildSrc/src/main/groovy/net/corda/testing/ImageBuilding.groovy
> +                if (!gradleDir.exists()) {
Or instances of `DirectoryProperty`. The point is that I would expect Gradle to create these directories automatically, and that fact that you need to do it manually suggests that these tasks aren't integrated with Gradle as well as they might be.

2019-09-03 09:42 UTC, chrisr3 commented on buildSrc/src/main/groovy/net/corda/testing/DistributedTesting.groovy
> +        if (System.getProperty("kubenetize") != null) {
Not to my knowledge... One is set on the command line using `-P` and the other is set using `-D`.

2019-09-03 15:40 UTC, merged