CORDA-3133 (Version 2)
corda/corda pull request #5428
Opened 2019-09-03 18:53 UTC by series0ne

### CORDA-3133 (Version 2)

https://r3-cev.atlassian.net/browse/CORDA-3133

This one is a little more flexible by design. This adds an internal `resolveAtTransaction` property to the `StatePointer` class. It's a default property set to `true`, so by default, the behaviour is the same as it is without the fix in place and therefore should be backwards compatible with any existing code. 

This gives developers an opt-in which means that they can choose whether state pointers should be resolved to reference inputs per-state pointer. This does however mean that developers can create output states that point to stale data, simply because it would not be resolved by the transaction builder.

I think the flexibility is worth considering - it puts the control back in the hands of the developer and the restriction can be strict or relaxed on a per-business case, rather than a blanket rule. 

_Apologies for naming: `resolveAtTransaction` actually sounds terrible to me, but it's 7PM and my brain is shutting down!_

2019-09-03 18:53 UTC, roastario commented
Can one of the admins verify this patch?

2019-09-05 08:27 UTC, roger3cev commented
This approach looks good to me! @mnesbit what do you reckon? Thanks for the contribution @series0ne !

2019-09-05 08:30 UTC, roger3cev commented on core/src/main/kotlin/net/corda/core/contracts/StatePointer.kt
> +        override val resolveAtTransaction: Boolean = true
Maybe `StaticPointer`s should be set to _not_ resolve by default - for the reasons you stated prior.

2019-09-05 08:30 UTC, roger3cev commented on core/src/main/kotlin/net/corda/core/contracts/StatePointer.kt
> +sealed class StatePointer<T : ContractState>(internal open val resolveAtTransaction: Boolean = true) {
Ya, naming is always tough for stuff like this... What about `isResolved` ?

2019-09-05 09:01 UTC, mnesbit commented on core/src/main/kotlin/net/corda/core/contracts/StatePointer.kt
> +sealed class StatePointer<T : ContractState>(internal open val resolveAtTransaction: Boolean = true) {
This probably shouldn't be internal because name mangling and serialization will not interact at all well. Is it ok to make it private? It can always have a public read only val.

2019-09-05 09:07 UTC, shamsasari requested changes

2019-09-05 09:07 UTC, shamsasari commented on core/src/main/kotlin/net/corda/core/contracts/StatePointer.kt
> +sealed class StatePointer<T : ContractState>(internal open val resolveAtTransaction: Boolean = true) {
In line with the other properties, can you declare this as an abstract property below (where `pointer` and `type` are) and not give it a default value. The default value is not necessary here as the concrete classes below specify them.

Also any reason why you made this internal? I think it's OK to have this public, the subclasses make this public anyway.

2019-09-05 09:07 UTC, shamsasari commented on core/src/main/kotlin/net/corda/core/contracts/StatePointer.kt
> +        override val resolveAtTransaction: Boolean = true
You will need to annotate the new c'tor with `@JvmOverloads` to preserve the old one that's now part of the API. This is probably why the API check is failing.

2019-09-05 09:07 UTC, shamsasari commented on core/src/main/kotlin/net/corda/core/contracts/StatePointer.kt
> +        override val resolveAtTransaction: Boolean = true
ditto

2019-09-05 09:17 UTC, shamsasari commented on core/src/main/kotlin/net/corda/core/contracts/StatePointer.kt
> +sealed class StatePointer<T : ContractState>(internal open val resolveAtTransaction: Boolean = true) {
It can't be public as it's needed by TransactionBuilder

2019-09-05 09:23 UTC, series0ne commented on core/src/main/kotlin/net/corda/core/contracts/StatePointer.kt
> +        override val resolveAtTransaction: Boolean = true
@roger3cev I did wonder that, but existing applications that are using state pointers might start to behave unexpectedly when upgraded to a new Corda version, and it wouldn't be immediately apparent as to why.

2019-09-05 09:25 UTC, roger3cev commented
This is true.... But this, in a way, is a bug fix. Will talk with Matthew and get back to you. Cheers

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Matthew Layton <notifications@github.com>
Sent: Thursday, September 5, 2019 10:23:25 AM
To: corda/corda <corda@noreply.github.com>
Cc: Roger Willis <roger.willis@r3.com>; Mention <mention@noreply.github.com>
Subject: Re: [corda/corda] CORDA-3133 (Version 2) (#5428)


@series0ne commented on this pull request.

________________________________

In core/src/main/kotlin/net/corda/core/contracts/StatePointer.kt<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcorda%2Fcorda%2Fpull%2F5428%23discussion_r321158862&data=02%7C01%7C%7Cf063b7d9ec9d4f01691308d731e2b54a%7Ca4be1f2e2d10419587cd736aca9b672c%7C0%7C0%7C637032722087919414&sdata=yxCqhnwBT3VZYoXkEgVD3p4o99%2FZ4s8h%2BlGoYqPQzOc%3D&reserved=0>:

> @@ -54,7 +56,11 @@ sealed class StatePointer<T : ContractState> {
  *   throw a [TransactionResolutionException]
  */
 @KeepForDJVM
-class StaticPointer<T : ContractState>(override val pointer: StateRef, override val type: Class<T>) : StatePointer<T>() {
+class StaticPointer<T : ContractState>(
+        override val pointer: StateRef,
+        override val type: Class<T>,
+        override val resolveAtTransaction: Boolean = true


@roger3cev<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Froger3cev&data=02%7C01%7C%7Cf063b7d9ec9d4f01691308d731e2b54a%7Ca4be1f2e2d10419587cd736aca9b672c%7C0%7C0%7C637032722087919414&sdata=1uUv3%2Be6L%2B6Q27y6TAX6Ehr1COIOnrCXLzcvTDw3e2Q%3D&reserved=0> I did wonder that, but existing applications that are using state pointers might start to behave unexpectedly when upgraded to a new Corda version, and it wouldn't be immediately apparent as to why.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcorda%2Fcorda%2Fpull%2F5428%3Femail_source%3Dnotifications%26email_token%3DAFMSO7SYI2CUNP7ZDX2TEKTQIDFY3A5CNFSM4ITJWKVKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCDXWNYQ%23discussion_r321158862&data=02%7C01%7C%7Cf063b7d9ec9d4f01691308d731e2b54a%7Ca4be1f2e2d10419587cd736aca9b672c%7C0%7C0%7C637032722087929410&sdata=r%2BHEBjwru6hO4uQP%2FMOAO6StpkMYrr5XQceETihzL%2BA%3D&reserved=0>, or mute the thread<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAFMSO7SN3ZPGZAY5NXNIF23QIDFY3ANCNFSM4ITJWKVA&data=02%7C01%7C%7Cf063b7d9ec9d4f01691308d731e2b54a%7Ca4be1f2e2d10419587cd736aca9b672c%7C0%7C0%7C637032722087939407&sdata=u2LhzwsKh0KmOX6Gr2NsQQNwIMStr1Kko6Tyym23m50%3D&reserved=0>.

2019-09-05 09:27 UTC, shamsasari commented on core/src/main/kotlin/net/corda/core/contracts/StatePointer.kt
> +        override val resolveAtTransaction: Boolean = true
Also, I just realised that `StatePointer` is corda serialisable, which means we need to preserve compatibility with the old serialisation format that doesn't include `resolveAtTransaction`. Normally this is all done seamlessly if we're only adding new properties which are nullable. `resolveAtTransaction` is not so unfortunately we need to add a bit more boilerplate. It's all explained here https://docs.corda.net/serialization-default-evolution.html.

2019-09-05 09:27 UTC, series0ne commented on core/src/main/kotlin/net/corda/core/contracts/StatePointer.kt
> +sealed class StatePointer<T : ContractState>(internal open val resolveAtTransaction: Boolean = true) {
My rationale was that this probably doesn't need to be seen by consuming code beyond the constructor, except for in the transaction builder where it's needed to determine whether or not to resolve the state pointer to a reference input.

As another thought, you could make it public instead. This would mean that you could use it in your contract code if needed; for example:

```
"Resolved pointers must point to the specified reference input" using (
    if(stateWithPointer.resolveAtTransaction) {
        // make checks against your reference input
    }
)
```

2019-09-05 10:23 UTC, roger3cev commented on core/src/main/kotlin/net/corda/core/contracts/StatePointer.kt
> +        override val resolveAtTransaction: Boolean = true
Ah yes good spot!

2019-09-05 10:23 UTC, roger3cev commented on core/src/main/kotlin/net/corda/core/contracts/StatePointer.kt
> +        override val resolveAtTransaction: Boolean = true
This is true.... But this, in a way, is a bug fix. Will talk with Matthew and get back to you. Cheers

2019-09-08 13:44 UTC, series0ne commented
I've added some updates to this PR. For some reason it's not building on my machine due to javafx dependencies, though this seems like more of a local issue if anything.

If there are any further issues with this, it might be worth me coming into R3 and sitting down with someone to get this over the line.

2019-09-09 10:58 UTC, roger3cev commented on core/src/main/kotlin/net/corda/core/contracts/StatePointer.kt
> +sealed class StatePointer<T : ContractState>(internal open val resolveAtTransaction: Boolean = true) {
This has been addressed

2019-09-09 10:58 UTC, roger3cev commented on core/src/main/kotlin/net/corda/core/contracts/StatePointer.kt
> +sealed class StatePointer<T : ContractState>(internal open val resolveAtTransaction: Boolean = true) {
This has been addressed

2019-09-09 11:04 UTC, roger3cev commented on core/src/main/kotlin/net/corda/core/contracts/StatePointer.kt
> +        override val resolveAtTransaction: Boolean = true
Looks like this is resolved now

2019-09-09 11:21 UTC, shamsasari commented on core/src/main/kotlin/net/corda/core/contracts/StatePointer.kt
> +    abstract val isResolved: Boolean
The API checker is still complaining. It's because we've added a new abstract method but the class is not annotated with `DoNotImplement`.

The easiest way to resolve this is to make it non-abstract and make it return the default value.
`open val isResolved: Boolean: get() = false`

There's a separate discussion to be had on whether we should annotate `StatePointer` with `@DoNotImplement`. It seems to be an omission that we didn't annotate it in the first place. Perhaps we should do it before the next release.

2019-09-09 11:32 UTC, roger3cev commented
@shamsasari Yes, it makes sense to annotate it with `DoNotImplement`

2019-09-09 11:32 UTC, roger-that-dev reviewed
Looks like it's nearly there - just need to get the API checker to pass. See @shamsasari 's comments. Ping me on slack if you get stuck. Cheers!

2019-09-09 11:32 UTC, roger3cev commented on core/src/main/kotlin/net/corda/core/contracts/StatePointer.kt
> +class StaticPointer<T : ContractState>(
Add `JvmOverloads` here

2019-09-09 11:32 UTC, roger3cev commented on core/src/main/kotlin/net/corda/core/contracts/StatePointer.kt
> +class LinearPointer<T : LinearState>(
Add JvmOverloads here

2019-09-09 11:38 UTC, shamsasari commented on core/src/main/kotlin/net/corda/core/contracts/StatePointer.kt
> +class StaticPointer<T : ContractState>(
Actually it's not needed as the other overloaded c'tor is defined below.

2019-09-09 11:38 UTC, shamsasari commented on core/src/main/kotlin/net/corda/core/contracts/StatePointer.kt
> +class LinearPointer<T : LinearState>(
likewise

2019-09-09 11:40 UTC, roger3cev commented on core/src/main/kotlin/net/corda/core/contracts/StatePointer.kt
> +class StaticPointer<T : ContractState>(
Ah gosh - ignore me @series0ne :) thanks @shamsasari

2019-09-10 15:01 UTC, roger3cev commented
Boom API checks passing @series0ne !

2019-09-10 15:09 UTC, shamsasari commented on core/src/main/kotlin/net/corda/core/contracts/StatePointer.kt
> +@DoNotImplement
Can you add an entry to the changelog.rst saying that `StatePointer` has been marked as `@DoNotImplement`, which was an omission in the original release.

2019-09-10 16:04 UTC, shamsasari commented on core/src/main/kotlin/net/corda/core/contracts/StatePointer.kt
> +        inline fun <reified T : ContractState> staticPointer(
Hmm, I understand the reason for having this but I'm not sure this is the PR to do it in. I'd rather this PR just deal with CORDA-3133. Feel free to raise a separate PR (you will have to check that it makes sense in Java code).

2019-09-10 16:06 UTC, roger3cev commented on core/src/main/kotlin/net/corda/core/contracts/StatePointer.kt
> +        inline fun <reified T : ContractState> staticPointer(
I said it's ok for him to merge in the other PR - it was approved but floundering as CI kept on takes ages then it needed a rebase etc...

2019-09-10 16:23 UTC, shamsasari commented on core/src/main/kotlin/net/corda/core/contracts/StatePointer.kt
> +        inline fun <reified T : ContractState> staticPointer(
Fair enough.

2019-09-10 16:24 UTC, shamsasari approved these changes

2019-09-10 17:10 UTC, roastario commented
Build

2019-09-11 07:51 UTC, merged