CORDA-3141: Add GracefulReconnect callbacks
corda/corda pull request #5430
Opened 2019-09-04 10:20 UTC by fowlerrr

GracefulReconnect callbacks allow logic to be performed when RPC disconnects unexpectedly.

2019-09-04 12:12 UTC, dimosr reviewed
Aware this is in draft mode, adding some comments before I vanish for 10 days..

We also need to update the rpc client docs for this change (`clientrpc.rst`). Some things I believe it's worth mentioning there:
- that the handlers are by default executed in a blocking way on the same thread and in a serialized fashion (i.e. disconnect -> reconnect -> disconnect -> reconnect). As a consequence, if the client is used by multiple threads and user-specified handlers are heavy, this can make reconnection slower for all the threads using the client. 
- It's up to the application code to delegate these handlers to background threads, if needed. In that case, application code will be responsible of ensuring they are still executed in the same serial way (my comment below on UUIDs is about facilitating this). Otherwise, bad effects can take place (i.e. reconnects executed before disconnects, leading to blocked UIs).

2019-09-04 12:12 UTC, dimosr commented on client/rpc/src/main/kotlin/net/corda/client/rpc/internal/ReconnectingCordaRPCOps.kt
> +        private val reconnectIdx = AtomicLong(0)
[Discussed offline with Ryan] I think there's no need for this, given `reconnectOnError` is synchronized. However, it might be useful to include a UUID in the disconnect/reconnect handlers, so that clients can correlate them in case they perform them in an asynchronous way (just an idea).

2019-09-04 12:12 UTC, dimosr commented on client/rpc/src/main/kotlin/net/corda/client/rpc/CordaRPCClient.kt
> +    fun start(username: String, password: String, externalTrace: Trace?, impersonatedActor: Actor?, gracefulReconnect: GracefulReconnect? = null): CordaRPCConnection {
[minor] worth slightly updating the docs for these methods on the `gracefulReconnect` parameter

2019-09-12 13:26 UTC, shamsasari requested changes

2019-09-12 13:26 UTC, shamsasari commented on client/rpc/src/main/kotlin/net/corda/client/rpc/CordaRPCClient.kt
> +    override var currentState: RPCConnection.CurrentState = actualConnection.currentState
You've exposed this into the public API. Was that done intentionally? There may be merit to having something like this in the API but for this PR let's not do that now. Can you hide this away.

2019-09-12 13:26 UTC, shamsasari commented on client/rpc/src/main/kotlin/net/corda/client/rpc/CordaRPCClient.kt
> + * GracefulReconnect provides the opportunity to perform certain logic when the RPC encounters an error
It's not "error" but rather connection disconnect.

2019-09-12 13:26 UTC, shamsasari commented on client/rpc/src/main/kotlin/net/corda/client/rpc/RPCConnection.kt
> +    var currentState: CurrentState
Yeah, let's not add this to the interface.

2019-09-12 13:26 UTC, shamsasari commented on client/rpc/src/main/kotlin/net/corda/client/rpc/internal/ReconnectingCordaRPCOps.kt
> +                        } else {}
Remove the `else`

2019-09-12 13:26 UTC, shamsasari commented on client/rpc/src/main/kotlin/net/corda/client/rpc/internal/ReconnectingCordaRPCOps.kt
> +                        fun retry() = if (method.isStartFlow()) {
Rename this method as it's no longer about retrying. Can you also reduce the clutter of this `invoke` method and move this local method out.

2019-09-12 13:26 UTC, shamsasari commented on client/rpc/src/main/kotlin/net/corda/client/rpc/internal/ReconnectingCordaRPCOps.kt
> +            fun result(): Any? {
Move this local method out of `invoke` - i didn't even notice that at first.

2019-09-13 09:26 UTC, shamsasari requested changes
The changelog needs to be updated as it still thinks `gracefulReconnect` is a boolean.

2019-09-13 09:26 UTC, shamsasari commented on client/rpc/src/main/kotlin/net/corda/client/rpc/internal/ReconnectingCordaRPCOps.kt
> +        private fun result(method: Method, args: Array<out Any>?): Any? {
`doInvoke` or something like that

2019-09-13 09:26 UTC, shamsasari commented on docs/source/clientrpc.rst
> +   val gracefulReconnect = GracefulReconnect(onDisconnect={}, onReconnect{})
Does this line compile? We also need the Java example.

2019-09-13 09:26 UTC, shamsasari commented on client/rpc/src/main/kotlin/net/corda/client/rpc/internal/ReconnectingCordaRPCOps.kt
> +                        attemptedAddress, rpcConfiguration.copy(connectionMaxRetryInterval = retryInterval, maxReconnectAttempts = 1), sslConfiguration, classLoader
Does this mean that if `gracefulReconnect` is specified then `connectionMaxRetryInterval` and `maxReconnectAttempts` are ignored? If that's the case then can we document that in kdocs.

2019-09-13 09:26 UTC, shamsasari commented on client/rpc/src/main/kotlin/net/corda/client/rpc/CordaRPCClient.kt
> + * @param onDisconnect implement this callback to perform logic when the RPC disconnects on connection disconnect
What thread are these callbacks executed on? I think we should document here that the callbacks may be executed on a separate thread to the one that started the RPC client or makes the RPC calls.

2019-09-13 09:26 UTC, shamsasari commented on node/src/integration-test-slow/kotlin/net/corda/node/services/rpc/RpcReconnectTests.kt
> +                assertThat(currentStackTrace().count { it.methodName == "reconnectOnError" }).isEqualTo(1)
Add a comment on what this is testing.

2019-09-13 09:26 UTC, shamsasari commented on node/src/integration-test-slow/kotlin/net/corda/node/services/rpc/RpcReconnectTests.kt
> +                assertThat(currentStackTrace().count { it.methodName == "reconnectOnError" }).isEqualTo(1)
If the `onReconnect` call was made via `scheduleResubscribe` then this assert won't be made on the test thread and so if this assert fails, then the test won't fail. You probably need to use an `AtomicInteger` or something and assert at the end.

2019-09-13 09:26 UTC, shamsasari commented on client/rpc/src/main/kotlin/net/corda/client/rpc/internal/ReconnectingCordaRPCOps.kt
> +            gracefulReconnect?.onDisconnect?.invoke()
I've just noticed that `reconnectOnError` is called by `ReconnectingObservable.scheduleResubscribe` and so if there's N open observables then `onDisconnect` and `onReconnect` will be called N + 1 times each (per reconnect), right? Can you add a test for this and make sure they're only called once.

2019-09-13 09:37 UTC, fowlerrr commented on docs/source/clientrpc.rst
> +   val gracefulReconnect = GracefulReconnect(onDisconnect={}, onReconnect{})
Yep, although I could at least put in `/*insert code here*/` in side the brackets

2019-09-13 14:05 UTC, fowlerrr commented on client/rpc/src/main/kotlin/net/corda/client/rpc/internal/ReconnectingCordaRPCOps.kt
> +                        attemptedAddress, rpcConfiguration.copy(connectionMaxRetryInterval = retryInterval, maxReconnectAttempts = 1), sslConfiguration, classLoader
Not sure how that would happen.  The `gracefulReconnect` doesn't affect these parameters?

2019-09-13 14:14 UTC, shamsasari commented on client/rpc/src/main/kotlin/net/corda/client/rpc/internal/ReconnectingCordaRPCOps.kt
> +        val lock = ReentrantLock()
make these two private

2019-09-13 14:16 UTC, shamsasari commented on client/rpc/src/main/kotlin/net/corda/client/rpc/internal/ReconnectingCordaRPCOps.kt
> +                lock.unlock()
The unlock should be in a `finally`

2019-09-13 14:17 UTC, shamsasari commented on client/rpc/src/main/kotlin/net/corda/client/rpc/internal/ReconnectingCordaRPCOps.kt
> +        val lock = ReentrantLock()
`reconnectLock` or similar

2019-09-13 16:10 UTC, shamsasari commented on client/rpc/src/main/kotlin/net/corda/client/rpc/internal/ReconnectingCordaRPCOps.kt
> +            if (reconnectLock.tryLock()) {
`reconnectLock` is not being used as a logic. You could replace `ReentrantLock` with `AtomicBoolean` and achieve the same thing. 

As mentioned offline, I'm not sure `isReconnecting` is being used safely. It's being set to false under the guard of `monitor` but its setting to false is not guarded by anything, so it's not clear that `waitOnReconnection` will see it.

I've come up with an alternative:

```
        private val isReconnecting = AtomicBoolean(false)
        private var reconnectLatch = CountDownLatch(1)

        /**
         * Called on external error.
         * Will block until the connection is established again.
         */
        fun reconnectOnError(e: Throwable) {
            // First one to get here gets to do all the reconnect logic, including calling onDisconnect and onReconnect. This makes sure
            // that they're only called once per reconnect.
            if (isReconnecting.compareAndSet(false, true)) {
                val previousConnection = currentRPCConnection
                currentState = DIED
                gracefulReconnect?.onDisconnect?.invoke()
                //TODO - handle error cases
                log.error("Reconnecting to ${this.nodeHostAndPorts} due to error: ${e.message}")
                log.debug("", e)
                connect()
                previousConnection?.forceClose()
                gracefulReconnect?.onReconnect?.invoke()
                reconnectLatch.await()
                reconnectLatch = CountDownLatch(1)
                isReconnecting.set(false)
            } else {
                // Everyone else waits for the first one
                reconnectLatch.await()
            }
        }
```

2019-09-16 08:53 UTC, shamsasari commented on client/rpc/src/main/kotlin/net/corda/client/rpc/internal/ReconnectingCordaRPCOps.kt
> +        private var isReconnecting = AtomicBoolean(false)
`val`

2019-09-16 08:57 UTC, shamsasari commented on client/rpc/src/main/kotlin/net/corda/client/rpc/CordaRPCClient.kt
> +data class GracefulReconnect(val onDisconnect: () -> Unit = {}, val onReconnect: () -> Unit = {})
This is not really a data class. Let's remove that and avoid the API compatibility headaches that come with data classes.

2019-09-16 09:09 UTC, shamsasari commented on docs/source/clientrpc.rst
> +            return Unit.INSTANCE;
This is one reason why we should provide Java examples - because then you can see ugliness like this. Unfortunately Kotlin's `() -> Unit` function type doesn't map nicely to Java (which is the main user base). What you're going to need to do is make the callbacks of type `Consumer`.

2019-09-16 09:27 UTC, fowlerrr commented on docs/source/clientrpc.rst
> +            return Unit.INSTANCE;
Like this? 

`class GracefulReconnect(val onDisconnect: Consumer<Void>, val onReconnect: Consumer<Void>)`

Will that muddy up the Kotlin interface, then?

2019-09-16 09:35 UTC, shamsasari commented on docs/source/clientrpc.rst
> +            return Unit.INSTANCE;
Ah sorry, I meant `Runnable`

2019-09-16 09:48 UTC, shamsasari submitted a review, later dismissed
👍

2019-09-17 08:59 UTC, shamsasari approved these changes

2019-09-17 09:00 UTC, merged