Rog external id refactor
corda/corda pull request #5434
Opened 2019-09-04 16:23 UTC by roger3cev

Throw stones as necessary...

1. Moved `externalIdForPublicKey` from `KeyManagementService` to `IdentityService` as request by Matthew as the semantics didn't really work so well with it sitting in the KMS.
2. Added a new API to `IdentityService` called `registerKeyToExternalId` which allows CorDapp developers to map `PublicKey`s to `UUID`s
3. TODO: Add an API to return all the keys associated with a specified UUID.

2019-09-09 11:15 UTC, mnesbit submitted a review, later dismissed
Makes sense to me

2019-09-09 17:26 UTC, szymonsztuka commented on node/src/main/kotlin/net/corda/node/services/identity/PersistentIdentityService.kt
> +            @Lob
With @lob mapping this will create OID column type on PostgreSQL (this is our defult way) however maybe better would be to use BYTE type - there can be a performance gain for selects and it's easier to write raw JDBC if needed.
To change column to be BYTEA in PostgreSQL you would need to add `@Type(type = "corda-blob")` instead of `@Lob` and specific branch in Liquibase XML for Postgres like in file 
`/node/src/main/resources/migration/node-core.changelog-postgres-blob.xml`

2019-09-09 17:27 UTC, kasiastreich reviewed
minor comments

2019-09-09 17:27 UTC, kasiastreich commented on core/src/main/kotlin/net/corda/core/node/services/IdentityService.kt
> -    @Deprecated("This method has been deprecated in favour of using a new way to generate and use confidential identities. See the new " +
So do we deprecate it or not?

2019-09-09 17:27 UTC, kasiastreich commented on core/src/main/kotlin/net/corda/core/node/services/IdentityService.kt
> -    fun registerKeyToParty(key: PublicKey, party: Party)
Isn't it API break?

2019-09-09 17:27 UTC, kasiastreich commented on core/src/main/kotlin/net/corda/core/node/services/IdentityService.kt
> +     * logged and the operation will not be carried out as a key can only ever be registered to one [Party].
But you still throw an exception in this case?

2019-09-09 17:27 UTC, kasiastreich commented on core/src/main/kotlin/net/corda/core/node/services/IdentityService.kt
> +    fun registerKey(publicKey: PublicKey, party: Party, externalId: UUID? = null)
Shouldn't we add `@JvmOverloads` if you introduce API method with defaults?

2019-09-09 17:27 UTC, kasiastreich commented on core/src/main/kotlin/net/corda/core/node/services/IdentityService.kt
> +    fun publicKeysForExternalId(externalId: UUID): Iterable<PublicKey>
add kdocs for this method too

2019-09-09 17:27 UTC, kasiastreich commented on node/src/main/kotlin/net/corda/node/services/identity/InMemoryIdentityService.kt
> +    override fun registerKey(publicKey: PublicKey, party: Party, externalId: UUID?) {
Don't you have to implement it?

2019-09-09 17:27 UTC, kasiastreich commented on node/src/main/kotlin/net/corda/node/services/identity/PersistentIdentityService.kt
> +                    toPersistentEntity = { key: String, value: PublicKey ->
Shouldn't hash be derived from the key?

2019-09-09 17:27 UTC, kasiastreich commented on node/src/main/kotlin/net/corda/node/services/identity/PersistentIdentityService.kt
> +            // specified key then it's either our key which has been stored prior or another node's key which we have preciously mapped.
Preciously or previously :joy:

2019-09-09 17:27 UTC, kasiastreich commented on node/src/main/kotlin/net/corda/node/services/identity/PersistentIdentityService.kt
> +            // EVERY key should by mapped to a Party in the "keyToName" table. Therefore if there is already a record in that table for the
typo: should be

2019-09-09 17:27 UTC, kasiastreich commented on node/src/main/kotlin/net/corda/node/services/identity/PersistentIdentityService.kt
> +                if (party.name != keyToName[publicKeyHash]) {
!= existingEntryForKey

2019-09-09 17:27 UTC, kasiastreich commented on node/src/main/kotlin/net/corda/node/services/identity/PersistentIdentityService.kt
> +    private fun publicKeysForExternalId(externalId: UUID, table: Class<*>): List<PublicKey> {
Could you comment why we do that? It's not clear that we have two tables one for our keys second for the other parties.

2019-09-10 12:43 UTC, roger3cev commented on node/src/main/kotlin/net/corda/node/services/identity/PersistentIdentityService.kt
> +            @Lob
Thanks @szymonsztuka !

2019-09-11 08:51 UTC, roastario commented
build

2019-09-11 09:05 UTC, roger-that-dev commented on core/src/main/kotlin/net/corda/core/node/services/IdentityService.kt
> -    @Deprecated("This method has been deprecated in favour of using a new way to generate and use confidential identities. See the new " +
We can't really deprecate this because it is still used by a few other things.

2019-09-11 09:05 UTC, roger-that-dev commented on core/src/main/kotlin/net/corda/core/node/services/IdentityService.kt
> -    fun registerKeyToParty(key: PublicKey, party: Party)
It usually would be but this is unreleased code - so we can still move stuff around :)

2019-09-11 09:05 UTC, roger-that-dev commented on core/src/main/kotlin/net/corda/core/node/services/IdentityService.kt
> +     * logged and the operation will not be carried out as a key can only ever be registered to one [Party].
No, not anymore. I don't think it's an exceptional case. What do you think ?

2019-09-11 09:05 UTC, roger-that-dev commented on core/src/main/kotlin/net/corda/core/node/services/IdentityService.kt
> +    fun registerKey(publicKey: PublicKey, party: Party, externalId: UUID? = null)
ok

2019-09-11 09:05 UTC, roger3cev commented on core/src/main/kotlin/net/corda/core/node/services/IdentityService.kt
> +    fun publicKeysForExternalId(externalId: UUID): Iterable<PublicKey>
It's not exposed via the API but will add docs

2019-09-11 09:05 UTC, roger3cev commented on node/src/main/kotlin/net/corda/node/services/identity/InMemoryIdentityService.kt
> +    override fun registerKey(publicKey: PublicKey, party: Party, externalId: UUID?) {
True, I was just being lazy :P

2019-09-11 09:05 UTC, roger3cev commented on node/src/main/kotlin/net/corda/node/services/identity/PersistentIdentityService.kt
> +                    toPersistentEntity = { key: String, value: PublicKey ->
Yeah, it is. I guess you are saying that the constructor for this can be simplified by just providing a public key instead of a publickey and a string (which is the hash).

2019-09-11 09:05 UTC, roger3cev commented on node/src/main/kotlin/net/corda/node/services/identity/PersistentIdentityService.kt
> +            // EVERY key should by mapped to a Party in the "keyToName" table. Therefore if there is already a record in that table for the
noted

2019-09-11 09:05 UTC, roger3cev commented on node/src/main/kotlin/net/corda/node/services/identity/PersistentIdentityService.kt
> +            // specified key then it's either our key which has been stored prior or another node's key which we have preciously mapped.
oops thanks

2019-09-11 09:05 UTC, roger3cev commented on node/src/main/kotlin/net/corda/node/services/identity/PersistentIdentityService.kt
> +    private fun publicKeysForExternalId(externalId: UUID, table: Class<*>): List<PublicKey> {
Yeah I can add a comment. Basically, "our keys" are kept separate from "not our keys" due to the semantics of the KMS being for "our keys" only.

2019-09-11 09:31 UTC, roger3cev commented
Still to do:
1. Implement mock identity service methods.
2. Double check migration is set up as it should be.
3. Add a test for the migration.

2019-09-11 13:08 UTC, willhr3 submitted a review, later dismissed
Looks good to me - cheers!

2019-09-11 13:29 UTC, kasiastreich commented on node/src/main/kotlin/net/corda/node/migration/PersistentIdentityMigrationNewTable.kt
> +        val us = identityService.ourNames.first()
are we sure that the first one there will be correct?

2019-09-11 13:32 UTC, kasiastreich commented on node/src/main/kotlin/net/corda/node/migration/PersistentIdentityMigrationNewTable.kt
> +        if (name != us) {
or should it be a check `name !in ourNames`?

2019-09-11 15:15 UTC, kasiastreich commented on node/src/test/kotlin/net/corda/node/services/vault/ExternalIdMappingTest.kt
> +    fun `roger uber keys test`() {
fun fun fun :joy:

2019-09-13 15:40 UTC, roger3cev commented on node/src/main/kotlin/net/corda/node/migration/PersistentIdentityMigrationNewTable.kt
> +        val us = identityService.ourNames.first()
Someone told me it was!

2019-09-13 15:45 UTC, roger3cev commented on node/src/main/kotlin/net/corda/node/services/identity/InMemoryIdentityService.kt
> +    override fun registerKey(publicKey: PublicKey, party: Party, externalId: UUID?) {
Implemented now.

2019-09-13 15:45 UTC, roger3cev commented on core/src/main/kotlin/net/corda/core/node/services/IdentityService.kt
> +     * logged and the operation will not be carried out as a key can only ever be registered to one [Party].
Added it back - thanks

2019-09-13 15:46 UTC, roger3cev commented on node/src/test/kotlin/net/corda/node/services/vault/ExternalIdMappingTest.kt
> +    fun `roger uber keys test`() {
🎉

2019-09-16 08:20 UTC, willhr3 commented on core/src/main/kotlin/net/corda/core/node/services/IdentityService.kt
>       */
This kdoc probs needs changing since we've removed the externalId from the method sig

2019-09-16 08:26 UTC, willhr3 commented on node/src/main/kotlin/net/corda/node/migration/PersistentIdentityMigrationNewTable.kt
> +        if (name != us) {
Yeah I think this would work better _just in case_ theres some DB weirdness and `us` isn't `ourNames.first()`

2019-09-16 08:30 UTC, willhr3 requested changes
Just two minor changes then it looks good to me.

2019-09-16 10:24 UTC, kasiastreich commented on node/src/main/kotlin/net/corda/node/migration/PersistentIdentityMigrationNewTable.kt
> +        val us = identityService.ourNames.first()
it's set, I would check for inclusion

2019-09-16 10:43 UTC, roger3cev commented on node/src/main/kotlin/net/corda/node/migration/PersistentIdentityMigrationNewTable.kt
> +        if (name != us) {
Fixed

2019-09-16 10:44 UTC, roger3cev commented on node/src/main/kotlin/net/corda/node/migration/PersistentIdentityMigrationNewTable.kt
> +        val us = identityService.ourNames.first()
OK

2019-09-16 10:44 UTC, roger3cev commented on core/src/main/kotlin/net/corda/core/node/services/IdentityService.kt
>       */
ah yes thanks

2019-09-16 10:53 UTC, willhr3 approved these changes

2019-09-16 12:14 UTC, merged