CORDA-3193: Update docs to mention branching strategy
corda/corda pull request #5451
Opened 2019-09-09 14:57 UTC by lockathan

Removed mention of master branch except to describe that the master branch is no longer used.
Added explanation of branching strategy to contributing guide.
Renamed building-against-master to building-against-non-release

2019-09-09 15:44 UTC, gendal commented
for an external contributor who may not know the answers to these questions, what do we suggest?  open against the default branch? contact us first?

2019-09-09 21:10 UTC, blsemo requested changes

2019-09-09 21:10 UTC, blsemo commented on docs/source/contributing.rst
> +github branch will always be the current development branch of Corda. Development work should target the oldest version
As @gendal said - mention here that this isn't just the default GitHub branch, it should also be the default to work against (unless fixing a specific issue in a specific version).

2019-09-09 21:10 UTC, blsemo commented on docs/source/contributing.rst
> +1. Create a pull request from your fork to the current development branch of the Corda repo
What is the `current development branch`? Shouldn't that be the release branch for the version you developed against?

2019-09-10 08:14 UTC, edward-prosser commented on docs/source/contributing.rst
> +2. Update the relevant `.rst file(s)
Remove the backtick from before .rst

2019-09-10 15:13 UTC, blsemo approved these changes
LGTM

2019-09-10 15:14 UTC, merged