Add Jenkinsfile for integration into CI
corda/corda pull request #5468
Opened 2019-09-12 14:01 UTC by roastario

2019-09-13 09:52 UTC, wzur-r3 commented on Jenkinsfile
> +def killall_jobs() {
how this functionality worked in the non-pipeline Jenkins project? Was it an option or something?

2019-09-13 10:17 UTC, wzur-r3 requested changes

2019-09-13 10:17 UTC, wzur-r3 commented on Jenkinsfile
> +def killall_jobs() {
It looks like this can be achieved with `milestone` step: https://jenkins.io/doc/pipeline/steps/pipeline-milestone-step/

see https://issues.jenkins-ci.org/browse/JENKINS-43353?focusedCommentId=365375&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-365375

2019-09-16 09:23 UTC, roastario commented on Jenkinsfile
> +def killall_jobs() {
I don't think this is how milestones work. 

If I have Builds [ 1, 2 ] and Milestones [ A, B ]; 

Build 1 is triggered, reaches Milestone A, but is then slowed down due to a network issue. 
Build 2 is triggered, reaches Milestone A, and shortly afterwards reaches Milestone B.
Build 1 is aborted. 

now in the usual case

Build 1 is triggered, reaches Milestone A, and shortly afterwards reaches Milestone B.
Build 2 is triggered, reaches Milestone A, and shortly afterwards reaches Milestone B.
Build 1 is NOT aborted, as it is an earlier build, and reached Milestone B first.  

I don't think milestones will fix our issues here. See: https://issues.jenkins-ci.org/browse/JENKINS-43132 for discussions around this issue.

2019-09-16 09:35 UTC, roastario commented on Jenkinsfile
> +def killall_jobs() {
Once the issue linked in your comment is resolved, the milestone step will provide the functionality required.

2019-09-16 09:53 UTC, wzur-r3 commented on Jenkinsfile
> +def killall_jobs() {
The suggestion from the second link I posted is this:

```groovy
def buildNumber = env.BUILD_NUMBER as int
if (buildNumber > 1) milestone(buildNumber - 1)
milestone(buildNumber)
```

I'd say it does exactly what you need, ie it kills an earlier build if a newer one is started and there is never a danger that it is the earlier one to kill the one started later.

2019-09-16 10:05 UTC, wzur-r3 approved these changes
I'm not going to keep this waiting over `milestone` step. Anything else looks fine to me.

2019-09-16 10:29 UTC, merged