ENT-3973 missing logging on shutdown
corda/corda pull request #5480
Opened 2019-09-17 10:54 UTC by StefanIliev545

Added a disable shutdownHook in the log4j2.xml to prevent double call to shutdown from our code and from the library, otherwise the async appenders never finish out flushing events.

2019-09-19 11:10 UTC, adagys commented
Good work 👍  One thing to take into consideration is that people tend to use custom log4j2 config files so this might get overridden. Should we emphasise this in the docs somewhere?

2019-09-19 11:48 UTC, StefanIliev545 commented
> Good work 👍 One thing to take into consideration is that people tend to use custom log4j2 config files so this might get overridden. Should we emphasise this in the docs somewhere?

I'm planning to solve that by overriding the classes used for parsing the config and enforce the option to be always off, but I think it's too big step for a patch release and prefer not risking such changes when there is a clear solution that if someone stumbles on that, we can instruct him to modify the log4j2 for now.

2019-09-19 11:59 UTC, anthonykeenan commented
We should definitely add it to the docs in that case

2019-09-20 08:50 UTC, anthonykeenan requested changes
Needs an OS ticket

2019-09-20 12:57 UTC, StefanIliev545 commented
Needs to go into 4.3 :')

2019-09-20 12:57 UTC, closed without merging