ENT-4150, ENT-4053 - Jolokia docs update
corda/corda pull request #5486
Opened 2019-09-18 13:13 UTC by StefanIliev545

Updated the text to show the commands in red with background rather than italic. Added security policy hint and synchronised with enterprise version of the page.

2019-09-19 12:57 UTC, anthonykeenan commented
You need CORDA jiras for this PR

2019-09-19 13:00 UTC, anthonykeenan requested changes

2019-09-19 13:00 UTC, anthonykeenan commented on docs/source/node-administration.rst
> +This section covers monitoring performance and health of a node in Corda Enterprise with Jolokia and Graphite. General best practices for monitoring (e.g. setting up TCP checks for the ports the node
I think the 'but should be followed' can be deleted.

2019-09-19 13:00 UTC, anthonykeenan commented on docs/source/node-administration.rst
> +* To pass a security policy use ``java -Dcapsule.jvm.args=-javaagent:./drivers/jolokia-jvm-1.6.0-agent.jar,policyLocation=file:./config-path/jolokia-access.xml -jar corda.jar``
I think you need to make it clearer that you can't use `jmxMonitoringHttpPort` if you want your own security policy, you should probably say something about that just being for development, and it using the built in jolokia dependency which will be removed in a future version and that we recommend the second method and providing your own jar.

2019-09-19 13:03 UTC, StefanIliev545 commented on docs/source/node-administration.rst
> +This section covers monitoring performance and health of a node in Corda Enterprise with Jolokia and Graphite. General best practices for monitoring (e.g. setting up TCP checks for the ports the node
Are we sure? I'm just transferring stuff from enterprise.

2019-09-19 13:04 UTC, StefanIliev545 commented on docs/source/node-administration.rst
> +* To pass a security policy use ``java -Dcapsule.jvm.args=-javaagent:./drivers/jolokia-jvm-1.6.0-agent.jar,policyLocation=file:./config-path/jolokia-access.xml -jar corda.jar``
It does not use a built in dependency, but the security policy won't work yes. If I understand the code correctly at least around jmxMonitoringHttpPort, it attempts to load from drivers first.

2019-09-19 13:06 UTC, anthonykeenan commented on docs/source/node-administration.rst
> +* To pass a security policy use ``java -Dcapsule.jvm.args=-javaagent:./drivers/jolokia-jvm-1.6.0-agent.jar,policyLocation=file:./config-path/jolokia-access.xml -jar corda.jar``
If you set jmxMonitoringHttpPort without a driver it will pick one up from in side Corda, definitely, which is behaviour we need to remove

2019-09-20 12:54 UTC, StefanIliev545 commented on docs/source/node-administration.rst
> +* To pass a security policy use ``java -Dcapsule.jvm.args=-javaagent:./drivers/jolokia-jvm-1.6.0-agent.jar,policyLocation=file:./config-path/jolokia-access.xml -jar corda.jar``
<img width="1315" alt="Screenshot 2019-09-20 at 13 53 39" src="https://user-images.githubusercontent.com/46542846/65328389-23078a80-dbae-11e9-9a85-e9806e281d8d.png">

2019-09-30 13:21 UTC, anthonykeenan requested changes

2019-09-30 13:21 UTC, anthonykeenan commented on docs/source/node-administration.rst
> +* Specify the Node configuration parameter ``jmxMonitoringHttpPort``.
which will use the jolokia agent v$current_jolokia_version which is bundled within the node?

Since we're going to remove jolokia from the node anyway and reccomend people supply their own driver, I think we should remove this. Maybe say something like:

----

Jolokia can be enabled by supplying the driver and configuration via the command line i.e.:

``java -Dcapsule.jvm.args="-javaagent:drivers/jolokia-jvm-1.6.0-agent.jar=port=7777,host=localhost" -jar corda.jar``

Additionally, the ``jmxMonitoringHttpPort`` option can be set in the ``node.conf`` (link to jmxMonitoringHttpPort in node configuration doc) and the option can be omitted from the comand line giving:

``java -Dcapsule.jvm.args="-javaagent:drivers/jolokia-jvm-1.6.0-agent.jar=host=localhost" -jar corda.jar``

------

Also possibly a link to any jolokia documentation on how to set up?

If we remove jolokia from the node, will we still be able to set the jmxMonitoringHttpPort in the node, or will that configuration option become unavailable?

2019-09-30 13:21 UTC, anthonykeenan commented on docs/source/node-administration.rst
> +Note that this will **not** work if you are loading jolokia using the ``jmxMonitoringHttpPort`` config option.
We can remove this note if we just talk about the external driver method.

2019-10-02 10:37 UTC, StefanIliev545 commented on docs/source/node-administration.rst
> +* Specify the Node configuration parameter ``jmxMonitoringHttpPort``.
Not sure the second suggestion will work at all with port in node conf and host there.
It does not use node bundled agent instantly, but rather tries loading from drivers/ if there is a jar already on $current_jolokia_version
Removal of jolokia from the node means we won't know what version we want to load, so quite possibly we'd still have minimum version for security reasons and we'll be trying to load jolokia > 1.6.1, but the option would still work (on proper removal that is) 

All in all takeway from here is that I need to finish off explaining what happens when you specify the jmx port?

2019-10-02 16:39 UTC, anthonykeenan requested changes

2019-10-02 16:39 UTC, anthonykeenan commented on docs/source/node-administration.rst
> +* Specify the Node configuration parameter ``jmxMonitoringHttpPort`` which will attempt loading the jolokia driver from the ``drivers`` folder.
_attempt to load_

2019-10-02 16:39 UTC, anthonykeenan commented on docs/source/node-administration.rst
> +* Specify the Node configuration parameter ``jmxMonitoringHttpPort`` which will attempt loading the jolokia driver from the ``drivers`` folder.
And does it? Does the jar need a specific format? Does it need to be in the drivers folder? Should it really say 'it will attempt to load a version of jolokia from the classpath including the drivers folder and any specified jarDirs' or something like that?

2019-10-02 16:39 UTC, anthonykeenan commented on docs/source/node-administration.rst
> +To pass a security policy use ``java -Dcapsule.jvm.args=-javaagent:./drivers/jolokia-jvm-1.6.0-agent.jar,policyLocation=file:./config-path/jolokia-access.xml -jar corda.jar``
If you want to pass a security policy does the jolokia jar need to be specified explicitly?

2019-10-08 09:31 UTC, anthonykeenan commented on node/src/main/resources/build.properties
> +#jolokiaAgentVersion=1.6.1
Why is this just commented? can this not be deleted?

2019-10-08 09:33 UTC, StefanIliev545 commented on node/src/main/resources/build.properties
> +#jolokiaAgentVersion=1.6.1
In case people come looking by inertia to upgrade the version here, to see that it's not used anymore and it has been moved to constants. I guess it might be a good idea to actually just make it a comment which will better explain the move.

2019-10-08 11:59 UTC, anthonykeenan commented on node/src/main/resources/build.properties
> +#jolokiaAgentVersion=1.6.1
Is there anything else in the file? If not I'd suggest we just delete the file - people will be able to see what's happened from the commit history and this PR

2019-10-08 12:00 UTC, StefanIliev545 commented on node/src/main/resources/build.properties
> +#jolokiaAgentVersion=1.6.1
We'll have to ensure we can safely delete the prod file in that case.

2019-10-10 10:11 UTC, bpaunescu commented on node/src/main/resources/build.properties
> +#jolokiaAgentVersion=1.6.1
why not add the jolokiaAgentVersion to the root build.gradle? where most of our dependency versions already are

2019-10-10 10:12 UTC, bpaunescu submitted a review, later dismissed
One minor comment about the jolokia version location

2019-10-10 10:12 UTC, StefanIliev545 commented on node/src/main/resources/build.properties
> +#jolokiaAgentVersion=1.6.1
@bpaunescu it's in the constants because the python scripts for the docs pull stuff from there to substitute when building.

2019-10-10 10:13 UTC, StefanIliev545 commented on node/src/main/resources/build.properties
> +#jolokiaAgentVersion=1.6.1
> @bpaunescu it's in the constants because the python scripts for the docs building stuff from there to substitute when building.

2019-10-14 09:07 UTC, anthonykeenan approved these changes

2019-10-14 09:08 UTC, merged