CORDA-3091: Move AutoClose to CordaRPCOps interface
corda/corda pull request #5491
Opened 2019-09-19 08:04 UTC by fowlerrr

This will allow the `ReconnectingCordaRPCOps` to be closed without needing an extra cast.

Note this exposes the `AutoClose` on a public interface rather than the internal one, which I don't think is a problem, but wanted to raise.

2019-09-19 09:42 UTC, shamsasari requested changes
See my comment on the cast change. If that's the only reason for adding `AutoCloseable` then we shouldn't do it and this PR should be closed.

However, reading the original JIRA ticket, it does raise a valid point regarding clean up of the executor that the connecting RPC uses. But making `CordaRPCOps` `AutoCloseable` is not the right way of doing it I think. `CordaRPCConnection` is already closeable so why can't the cleanup of the executor be done via that? Having two `close` entry points will make things confusing.

> or the ReconnectingRPCConnection should also close the thread pools that the ReconnectingCordaRPCOps currently closes.

This sounds like the better option.

2019-09-19 09:42 UTC, shamsasari commented on client/jfx/src/main/kotlin/net/corda/client/jfx/model/NodeMonitorModel.kt
> +            rpc.close()
We're making a change to the public API just so that this internal class doesn't need to cast? That's not a good enough reason. Rather, this class shouldn't even be using the internal reconnecting RPC, or if it needs it then the cast is acceptable. However I think this can be converted to use just the public API.

2019-09-19 10:07 UTC, mnesbit commented
I agree with Shams ownership of the active resources should be at the connection level.

2019-09-23 10:38 UTC, fowlerrr commented
@shamsasari would now be a good time to tackle this, then?

```
// TODO The executor service is not needed. All we need is a single thread that deals with reconnecting and onto which ReconnectingObservables
//  and other things can attach themselves as listeners for reconnect events.
```

I remember we've discussed it before.  Just make it a `singleThreadedExecutor`?

2019-09-23 10:44 UTC, shamsasari commented
@fowlerrr I'm not sure if using a singleton executor is correct or not. Better to leave this for a separate PR, unless you have thought it through.

2019-09-23 11:55 UTC, shamsasari commented on client/rpc/src/main/kotlin/net/corda/client/rpc/internal/ReconnectingCordaRPCOps.kt
> +            observersPool ?: Executors.newCachedThreadPool())
There's no need to make `observersPool` pool nullable in `ReconnectingCordaRPCOps`. I think this is a hangover from when this class was meant to be used directly. Let's make this non-nullable.

2019-09-23 12:40 UTC, fowlerrr commented on client/rpc/src/main/kotlin/net/corda/client/rpc/internal/ReconnectingCordaRPCOps.kt
> +            observersPool ?: Executors.newCachedThreadPool())
That change has a bit of reach.  Several classes make the ReconnectingCordaRPCOps directly and will now have to provide the pool (not that I mind, just mentioning).

2019-09-23 12:54 UTC, shamsasari approved these changes
LGTM

2019-09-23 13:07 UTC, shamsasari submitted a review, later dismissed

2019-09-23 13:43 UTC, shamsasari commented on tools/shell/src/main/kotlin/net/corda/tools/shell/InteractiveShell.kt
> +                ).also {
The use of `also` here does not save us lines of code, but does increase the complexity a bit. Perhaps just do this conventional way with a local variable.

2019-09-23 13:44 UTC, shamsasari commented on detekt-baseline.xml
> +    <ID>MaxLineLength:InteractiveShell.kt$InteractiveShell${ private val log = LoggerFactory.getLogger(javaClass) private lateinit var rpcOps: (username: String, password: String) -&gt; InternalCorda
What change have you made here?

2019-09-23 13:48 UTC, fowlerrr commented on detekt-baseline.xml
> +    <ID>MaxLineLength:InteractiveShell.kt$InteractiveShell${ private val log = LoggerFactory.getLogger(javaClass) private lateinit var rpcOps: (username: String, password: String) -&gt; InternalCorda
There were two lines that detekt was erroneously marking as too long.  A quick chat with @Schife and we decided to baseline them (he suspects something about dodgy line endings)

2019-09-23 13:59 UTC, shamsasari submitted a review, later dismissed

2019-09-25 14:01 UTC, shamsasari commented on client/jfx/src/main/kotlin/net/corda/client/jfx/model/NodeMonitorModel.kt
>          } catch (e: Exception) {
I didn't originally think it an issue, but seeing this catch makes think I was wrong. The `close` method will not shutdown the executor if the `actualConnection.close()` throws, so it needs to be done in a `finally`.

2019-09-25 14:03 UTC, shamsasari commented on client/jfx/src/main/kotlin/net/corda/client/jfx/model/NodeMonitorModel.kt
> +        val (statesSnapshot, vaultUpdates) =
My personal preference is to put the params on separate lines. It makes the entire expression easier to read.

2019-09-25 14:04 UTC, shamsasari commented on samples/bank-of-corda-demo/src/main/kotlin/net/corda/bank/api/BankOfCordaClientApi.kt
> +    fun requestRPCIssue(rpcAddress: NetworkHostAndPort, params: IssueRequestParams): SignedTransaction =
Convert this to a block body instead.

2019-09-25 14:05 UTC, shamsasari commented on samples/bank-of-corda-demo/src/main/kotlin/net/corda/bank/api/BankOfCordaClientApi.kt
> +        .use { rpc->
Can you not have the `use` on the line above?

2019-09-25 14:34 UTC, fowlerrr commented on client/jfx/src/main/kotlin/net/corda/client/jfx/model/NodeMonitorModel.kt
>          } catch (e: Exception) {
Which bit do you mean?  The `observersPool.shutdown()` in the CordaRPCConnection`?

2019-09-25 14:56 UTC, shamsasari commented on client/jfx/src/main/kotlin/net/corda/client/jfx/model/NodeMonitorModel.kt
>          } catch (e: Exception) {
yes

2019-09-26 16:42 UTC, shamsasari commented on client/jfx/src/main/kotlin/net/corda/client/jfx/model/NodeMonitorModel.kt
> +                statesSnapshot,
This is a bit silly - the destructed properties should be on one line.

2019-09-26 16:45 UTC, shamsasari approved these changes

2019-09-26 16:48 UTC, merged