CORDA-3246 - Missing logs on shutdown
corda/corda pull request #5501
Opened 2019-09-20 13:13 UTC by StefanIliev545

Moved pr to be for 4.3 os, later on cherry picked into 4.2 for the patch. 
Added doc entry that looks like that at node-administration/logging section:
<img width="1309" alt="Screenshot 2019-09-20 at 14 11 39" src="https://user-images.githubusercontent.com/46542846/65329675-e0937d00-dbb0-11e9-8fef-9316a79f4e57.png">

2019-09-23 09:42 UTC, anthonykeenan requested changes

2019-09-23 09:42 UTC, anthonykeenan commented on docs/source/node-administration.rst
> +.. warning:: Ensure that ``shutdownHook="disable"`` is set if you are overriding the log4j2 configuration file
You need to mention that _where_ to set `shutdownHook="disable"`. Might be worth also mentioning _why_?

2019-09-23 10:34 UTC, StefanIliev545 commented on docs/source/node-administration.rst
> +.. warning:: Ensure that ``shutdownHook="disable"`` is set if you are overriding the log4j2 configuration file
<img width="1313" alt="Screenshot 2019-09-23 at 11 34 45" src="https://user-images.githubusercontent.com/46542846/65419250-29884300-ddf6-11e9-92f4-11f23e1f872f.png">

2019-09-30 13:18 UTC, anthonykeenan requested changes

2019-09-30 13:18 UTC, anthonykeenan commented on docs/source/node-administration.rst
> +   otherwise logs will not be flushed properly on shutdown and loss may occur. The option is set at the ``Configuration``
_in_ the ``Configuration`` tag _of the log4j2 configuration file_

2019-09-30 13:18 UTC, anthonykeenan commented on docs/source/node-administration.rst
> +   tag, for example ``<Configuration ... shutdownHook="disable">``. This has to be set as Corda is calling shutdown after
This is because Corda overrides the default log4j2 shutdown logic in order to make sure it gets shut down correctly.

2019-10-08 09:18 UTC, anthonykeenan approved these changes
LGTM

2019-10-08 09:18 UTC, merged