ENT-4189 - add support for environment variables in linux
corda/corda pull request #5523
Opened 2019-09-26 12:37 UTC by StefanIliev545

Added support for defining environment variables with underscore. Needs lowercasing as in Linux yelling is the STANDARD_FORMAT.

2019-09-30 13:17 UTC, anthonykeenan requested changes
Also needs documentation and changelog updating

2019-09-30 13:17 UTC, anthonykeenan commented on node/src/main/kotlin/net/corda/node/services/config/ConfigUtilities.kt
> +    private const val CORDA_PROPERTY_PREFIX_LINUX = "corda_"
Can we remove the reference to linux, I'm assuming it's also a mac thing and will still work on Windows

2019-09-30 13:17 UTC, anthonykeenan commented on node/src/integration-test/kotlin/net/corda/node/NodeConfigParsingTests.kt
> +                systemProperties = mapOf("corda_sshd_port" to sshPort.toString()),
Is this actually simulating an environment variable? Or is it just simulating a system variable?

2019-09-30 13:18 UTC, StefanIliev545 commented on node/src/integration-test/kotlin/net/corda/node/NodeConfigParsingTests.kt
> +                systemProperties = mapOf("corda_sshd_port" to sshPort.toString()),
Just a system variable, but goes through the code that needs to be tested. Both use the same toCordaPropertiesOnly() call.

2019-09-30 13:19 UTC, anthonykeenan commented
Also needs an OS ticket

2019-10-03 13:03 UTC, anthonykeenan requested changes
Why have you done a re-base line? Is the issue because this signature can't be changed because it's part of the API? Because if that is the case we need another solution because we actually _can't_ change this code - re-baselining is not a solution.

2019-10-03 13:03 UTC, anthonykeenan commented on node/src/main/kotlin/net/corda/node/services/config/ConfigUtilities.kt
> +        val codaPropOccurrences = mutableSetOf<String>()
corda

2019-10-08 09:28 UTC, anthonykeenan requested changes
Can we add appropriate @Suppress comments to the public API parts of the driver rather than re-baseline?

2019-10-08 09:28 UTC, anthonykeenan commented on .idea/codeStyles/Project.xml
> +      <option name="NAME_COUNT_TO_USE_STAR_IMPORT_FOR_MEMBERS" value="20" />
Did you mean to check this in?

2019-10-08 09:28 UTC, anthonykeenan commented on .idea/codeStyles/codeStyleConfig.xml
> -    <option name="PREFERRED_PROJECT_CODE_STYLE" value="Default" />
Did you mean to delete this?

2019-10-08 09:29 UTC, StefanIliev545 commented on .idea/codeStyles/Project.xml
> +      <option name="NAME_COUNT_TO_USE_STAR_IMPORT_FOR_MEMBERS" value="20" />
Nope, but apparently I did...

2019-10-08 09:30 UTC, StefanIliev545 commented on .idea/codeStyles/codeStyleConfig.xml
> -    <option name="PREFERRED_PROJECT_CODE_STYLE" value="Default" />
I definitely didnt

2019-10-10 10:03 UTC, bpaunescu requested changes

2019-10-10 10:03 UTC, bpaunescu commented on node/src/integration-test/kotlin/net/corda/node/NodeConfigParsingTests.kt
> +                startNode().getOrThrow()
It's possible the node fails to start due to other issues. This doesn't test the variable shadowing.

2019-10-10 10:03 UTC, bpaunescu commented on node/src/main/kotlin/net/corda/node/services/config/ConfigUtilities.kt
> +        if (path.size == 0)
require(!path.isEmpty) {error message} is cleaner.

2019-10-11 12:24 UTC, StefanIliev545 commented
<img width="1621" alt="Screenshot 2019-10-11 at 13 21 52" src="https://user-images.githubusercontent.com/46542846/66651170-4a3ffd80-ec2a-11e9-877d-e24dc3ba20fc.png">
Added a bit more edge case handling for when a variable is already defined and starts with CORDA_ but is not a config property. Resolution will fail and print out a warning, the variable will be skipped and Corda will resume starting up normally as it wasn't there. This is to avoid failing to load config for people who have already defined CORDA_WHATEVER_DEPLOYMENT_PROPERTY or stuff like that.

2019-10-11 12:48 UTC, StefanIliev545 commented
Text updated.
<img width="1622" alt="Screenshot 2019-10-11 at 13 47 03" src="https://user-images.githubusercontent.com/46542846/66652510-cc7df100-ec2d-11e9-84fa-fd40b4605fa0.png">

2019-10-11 13:07 UTC, bpaunescu submitted a review, later dismissed
LGTM

2019-10-16 16:07 UTC, anthonykeenan submitted a review, later dismissed
Just a couple of bits but otherwise good to go

2019-10-16 16:07 UTC, anthonykeenan commented on node/src/main/kotlin/net/corda/node/services/config/ShadowingException.kt
> +        "Environment variable $definedProperty is shadowing another property transformed to $convertedProperty")
Can we specify the name of the conflicting property and where it came from (environment/system) if possible? Rather than the end property it is being mapped to.

2019-10-16 16:07 UTC, anthonykeenan commented on node/src/main/kotlin/net/corda/node/services/config/ConfigUtilities.kt
> +                                            " double check the spelling and ensure there is such config key.")
I liked this error - however can we update the wording slightly:

`! ATTENTION: CORDA_ARTIFACTORY_PASSWORD (property or environment variable) cannot be mapped to an existing Corda config property and thus _won't_ be used as a config override! _If that was the intention_ double check the spelling and ensure there is such config key.`

2019-10-17 14:56 UTC, anthonykeenan requested changes
Just a few doc grammar/structure changes

2019-10-17 14:56 UTC, anthonykeenan commented on docs/source/changelog.rst
> +* Environment variables and system properties can now be provided with underscore separators instead of dots. Both are also not case sensitive
Neither are case sensitive.

2019-10-17 14:56 UTC, anthonykeenan commented on docs/source/corda-configuration-file.rst
> +.. note:: Underscores can be used in instead of dots. For example overriding the p2pAddress with environment variable can be done
p2pAddress should be code

2019-10-17 14:56 UTC, anthonykeenan commented on docs/source/corda-configuration-file.rst
> +.. note:: Underscores can be used in instead of dots. For example overriding the p2pAddress with environment variable can be done
overriding the `p2pAddress` with _an_ environment variable

2019-10-17 14:56 UTC, anthonykeenan commented on docs/source/corda-configuration-file.rst
> +   by specifying ``CORDA_P2PADDRESS=host:port``. Variables and properties are not case sensitive. Corda will warn you if a prefixed
Corda will warn you if a variable prefixed with `CORDA` cannot be mapped to a valid property.

2019-10-17 14:56 UTC, anthonykeenan commented on docs/source/corda-configuration-file.rst
> +   will raise an exception on startup. This is to prevent hard to spot mistakes.
Is it an exception or just a warning?

2019-10-17 14:56 UTC, anthonykeenan commented on docs/source/corda-configuration-file.rst
> +.. note:: Underscores can be used in instead of dots. For example overriding the p2pAddress with environment variable can be done
This should be under the "Environment variables" heading instead of as a note, and should start with something like "Corda properties can be overridden using Environment Variables. Dots can be replaced with underscores for systems that don't support dots in environment variables....

2019-10-21 08:43 UTC, StefanIliev545 commented on docs/source/corda-configuration-file.rst
> +   will raise an exception on startup. This is to prevent hard to spot mistakes.
exception, we do not want to start with conflicting same priority overrides as we have no way to weigh em.

2019-10-21 11:01 UTC, anthonykeenan approved these changes
Looks good now, great work!

2019-10-21 11:01 UTC, merged