ENT-4240 Added general exception handler for Virtual Machine errors.
corda/corda pull request #5530
Opened 2019-09-30 11:12 UTC by josecoll

The existing default thread exception handler dealt with unrecoverable Database errors only.

This PR generalises the exception handler to cater for all types of `VirtualMachineError`, including the 5 types VirtualMachineError triggered by the JVM run-time:

- OutOfMemoryError
- StackOverflowError
- InternalError
- UnknownError
- ZipError

and two additional types throwable by 3rd party libraries:

- OutOfDirectMemoryError (Netty)
- OutOfDirectMemoryError (Gradle docker shaded to Netty plugin)

2019-09-30 11:57 UTC, mnesbit commented on node/src/main/kotlin/net/corda/node/internal/GeneralExceptionHandler.kt
> +        else if (e is VirtualMachineError) {
Should this clause be first and should we make this a static string, not one that will involve a string buffer before calling the abort

2019-09-30 12:49 UTC, josecoll commented on node/src/main/kotlin/net/corda/node/internal/GeneralExceptionHandler.kt
> +        else if (e is VirtualMachineError) {
Good suggestion.

2019-09-30 12:50 UTC, mnesbit submitted a review, later dismissed
LGTM

2019-09-30 13:35 UTC, rick-r3 requested changes

2019-09-30 13:35 UTC, rick-r3 commented on node/src/main/kotlin/net/corda/node/internal/GeneralExceptionHandler.kt
> -            errorAndTerminate("Thread ${t!!.name} failed due to database connection error. This is unrecoverable, terminating node.", e)
We want to keep the previous error handling (although I'm not sure what would have been triggering it, looking at it).  Was/is there a test that triggered this prior logic somewhere?

2019-09-30 13:35 UTC, rick-r3 commented on node/src/main/kotlin/net/corda/node/internal/GeneralExceptionHandler.kt
> +            errorAndTerminate(UNRECOVERABLE_ERROR, e)
Is deteckt making you use the `const` ?  Don't think this is more readable than having the string here.

Actually, we need the thread name in it so that it is reported in the background logging of that function.

2019-09-30 13:35 UTC, rick-r3 commented on node/src/main/kotlin/net/corda/node/utilities/errorAndTerminate.kt
> -    thread {
I think we want to conditionally drop immediately to the `halt` if it is a `VirtualMachineError`.   Keep the `sleep` and background logging for the other path, though.  The sleep gives things a chance to actually finish logging.  The background logging is needed in case the disk is full which would block the log statement from completing.

2019-09-30 13:37 UTC, josecoll commented
@rick-r3 please see @mnesbit comments (the changes you are asking for were removed based on these).

2019-09-30 13:38 UTC, josecoll commented on node/src/main/kotlin/net/corda/node/utilities/errorAndTerminate.kt
> -    thread {
I can change this (it would possible be useful for non-OOM cases only).

2019-09-30 13:41 UTC, rick-r3 commented on node/src/main/kotlin/net/corda/node/internal/GeneralExceptionHandler.kt
> -            errorAndTerminate("Thread ${t!!.name} failed due to database connection error. This is unrecoverable, terminating node.", e)
Actually, @mnesbit makes a good point.  Okay, for VMEs, let's just call `halt` and not `errorAndTerminate`.  Keep that for all the other errors.

2019-09-30 13:41 UTC, rick-r3 commented on node/src/main/kotlin/net/corda/node/internal/GeneralExceptionHandler.kt
> +            errorAndTerminate(UNRECOVERABLE_ERROR, e)
Shouldn't be an allocation problem now, if we are avoiding this function for VMEs.

2019-09-30 13:42 UTC, rick-r3 commented on node/src/main/kotlin/net/corda/node/utilities/errorAndTerminate.kt
> -    thread {
Could probably put this back the way it was, although the try/finally is a good ideal still.

2019-10-01 08:37 UTC, rick-r3 commented on node/src/main/kotlin/net/corda/node/internal/GeneralExceptionHandler.kt
> +            Runtime.getRuntime().halt(1)
Let's add one line above this with a `println(e?.message)` so we can tell what type it was.  Was worried we would silently exit and not know what type it is.  

We should have exited via the other JVM command line args if we are out of heap, so that should be safe.  Can't do a log as logging might be blocked and we might be out of threads so can't do it in the background.

2019-10-01 08:37 UTC, rick-r3 reviewed
Looks good.  Can we add the `println` as mentioned below?

2019-10-01 08:49 UTC, josecoll commented on node/src/main/kotlin/net/corda/node/internal/GeneralExceptionHandler.kt
> +            Runtime.getRuntime().halt(1)
`e` cannot be `null` as it is smart casted after the (`e is VirtualMachine`) check.

2019-10-01 12:56 UTC, rick-r3 approved these changes

2019-10-01 15:12 UTC, merged