CORDA-2756 - Node configuration doc change
corda/corda pull request #5550
Opened 2019-10-03 12:19 UTC by StefanIliev545

<img width="1313" alt="Screenshot 2019-10-03 at 13 18 30" src="https://user-images.githubusercontent.com/46542846/66126017-526fbb80-e5e0-11e9-89bd-f2f044a1de71.png">

Added a warning as per the ticket, as of right now the only way to catch duplicates is to write a custom parser or heavily modifying the typesafe library.

2019-10-03 13:00 UTC, anthonykeenan requested changes

2019-10-03 13:00 UTC, anthonykeenan commented on docs/source/corda-configuration-file.rst
> +
What about the precedence of system variables and environment variables? How does that work if I define and environment variable that clashes with a node.conf variable etc.......

2019-10-03 13:02 UTC, StefanIliev545 commented on docs/source/corda-configuration-file.rst
> +
This is explained in its own section "config overriding section" already. No point in duplicating information on a warning bubble

2019-10-03 13:06 UTC, anthonykeenan commented on docs/source/corda-configuration-file.rst
> +
Ok that's fair. Although it would be nice to say (below) which takes precedence when you set both the environment variable and the JVM option.

2019-10-07 14:31 UTC, StefanIliev545 commented on docs/source/corda-configuration-file.rst
> +
<img width="1345" alt="Screenshot 2019-10-07 at 15 31 01" src="https://user-images.githubusercontent.com/46542846/66320845-7ea87680-e917-11e9-85fb-cba07494945e.png">

2019-10-08 09:14 UTC, anthonykeenan commented on docs/source/corda-configuration-file.rst
> +
If the same field is overriden by both an environnment variable and system property, the system property takes precedence.

2019-10-08 09:14 UTC, anthonykeenan requested changes
Just a slight grammar change

2019-10-08 09:51 UTC, anthonykeenan approved these changes

2019-10-08 11:57 UTC, merged