TM-40 Ephemeral workspace for k8s workers that survives restarts
corda/corda pull request #5567
Opened 2019-10-08 16:22 UTC by zkiss

k8s test runners receive a new volume mounted under `/test-runs` that survives pod death.

This storage is a [PVC](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#lifecycle-of-a-volume-and-claim) that dynamically creates volumes and discards them after use.

2019-10-09 07:08 UTC, barrylapthorn submitted a review, later dismissed
Seem fine to me.  A couple of extra comments would be good.  And the `.idea` folder changes can probably be reverted I expect (there's a whole Slack debate on that one).

Presumably there's nothing that can be usefully unit tested?

Pedantic stuff:  you can write slightly more idiomatic groovy, but it makes no difference, so up to you:

* Can use `def s = new Something()` in a few places where the RHS is clearly stated.
* Can use the Elvis operator:  `res ?: 0` rather than `res ? res : 0`
* Can simplify some of the closures, as `it` is the implicit parameter, i.e.

```
c.stream().filter({ i -> i == 4 })
```
can be
```
c.stream().filter({ it == 4 })
```
when it is clear.  You can also remove the parentheses in some cases if you choose (or Intellij lights up the right gutter with yellow lines).

2019-10-09 07:08 UTC, barrylapthorn commented on buildSrc/src/main/groovy/net/corda/testing/KubesTest.groovy
> +            Retry.fixed(numberOfRetries).run {
Maybe add a comment about why we're retrying?

2019-10-09 07:08 UTC, barrylapthorn commented on buildSrc/src/main/groovy/net/corda/testing/KubesTest.groovy
>                  .withImagePullSecrets(new LocalObjectReference("regcred"))
Is `regcred` a magic string?

2019-10-09 11:11 UTC, zkiss commented on .idea/codeStyles/Project.xml
> +    </GroovyCodeStyleSettings>
This time I mean it. Reason is that in [this](https://github.com/corda/corda/pull/5567/files#diff-b0602ea167b28ffdf8cf33883f35436aR77) piece of code if we use `*` imports we **have to use the FQN** of `ConfigBuilder`. Furthermore, when I switched this setting back to where it was, **the code broke** because it started using the wrong class.

2019-10-09 11:22 UTC, zkiss commented
Added some comments and made some changes suggested by @barrylapthorn, Thank you! I have not gone through all lambdas, so in case you know of specific places readability can be improved, please point them out via comments on the relevant lines!

I consider this PR done until further feedback.

2019-10-09 11:30 UTC, zkiss commented on buildSrc/src/main/groovy/net/corda/testing/KubesTest.groovy
> +                int resCode = waiter.join()
Quick note on this: all this piece of code does in the majority of time is wait on the `waiter` `Future` `join()` to return. This means we're submitting a task to an executor that mostly waits on another `Future`. This means we have two threads waiting on the same thing. This can be optimised, but I have not done it because it is a larger refactor of this code than I was ready to do at this time, but I think it's worth noting.

Should I add this as a comment in the code?

2019-10-09 14:11 UTC, Schife commented on buildSrc/src/main/groovy/net/corda/testing/KubesTest.groovy
> +                int resCode = waiter.join()
Maybe create a Jira ticket instead of a comment

2019-10-09 14:14 UTC, barrylapthorn commented on buildSrc/src/main/groovy/net/corda/testing/KubesTest.groovy
> +                int resCode = waiter.join()
It's recorded here in github, so not necessary unless you really want to.  It's not a `TODO` 👍

2019-10-09 14:45 UTC, Schife submitted a review, later dismissed
LGTM

2019-10-11 15:31 UTC, r3domfox submitted a review, later dismissed
LGTM

2019-10-14 10:32 UTC, roastario commented
this seems to be failing due to

`  Normal   Scheduled  10m                     default-scheduler                       Successfully assigned thisisatest/integrationtest-1lmzs3vh06j1k-1mpqberaoqbbs-9 to aks-core8-18738514-vmss000341
  Normal   Pulling    8m33s (x4 over 9m55s)   kubelet, aks-core8-18738514-vmss000341  Pulling image "stefanotestingcr.azurecr.io/testing:f82f9f3b-a66"
  Warning  Failed     8m32s (x4 over 9m54s)   kubelet, aks-core8-18738514-vmss000341  Failed to pull image "stefanotestingcr.azurecr.io/testing:f82f9f3b-a66": [rpc error: code = Unknown desc = Error response from daemon: manifest for stefanotestingcr.azurecr.io/testing:f82f9f3b-a66 not found: manifest unknown: manifest unknown, rpc error: code = Unknown desc = Error response from daemon: Get https://stefanotestingcr.azurecr.io/v2/testing/manifests/f82f9f3b-a66: unauthorized: authentication required]
  Warning  Failed     8m32s (x4 over 9m54s)   kubelet, aks-core8-18738514-vmss000341  Error: ErrImagePull
  Warning  Failed     8m6s (x6 over 9m53s)    kubelet, aks-core8-18738514-vmss000341  Error: ImagePullBackOff
  Normal   BackOff    4m54s (x20 over 9m53s)  kubelet, aks-core8-18738514-vmss000341  Back-off pulling image "stefanotestingcr.azurecr.io/testing:f82f9f3b-a66"
`
I do see some changes around the way regcred is specified

2019-10-14 15:10 UTC, roastario requested changes
resolving conflicts doesn't mean just deleting existing changes.

2019-10-14 17:11 UTC, zkiss commented on buildSrc/src/main/groovy/net/corda/testing/KubesTest.groovy.bak
> +package net.corda.testing
will be deleted once im done with pr

2019-10-15 09:27 UTC, Schife approved these changes
LGTM

2019-10-15 09:52 UTC, roastario approved these changes

2019-10-15 09:52 UTC, roastario commented on buildSrc/src/main/java/net/corda/testing/retry/Retry.java
> +package net.corda.testing.retry;
I see the purpose of this class - but do we reeeeaaally need an abstraction over a try-catch loop?

2019-10-15 09:52 UTC, merged