adding one point to whitelist contract constraints migration - signed…
corda/corda pull request #5568
Opened 2019-10-08 19:50 UTC by snedamle

… CorDapp JAR must be registered with the CZ network operator

👮🏻👮🏻👮🏻 !!!! DESCRIBE YOUR CHANGES HERE !!!! DO NOT FORGET !!!! 👮🏻👮🏻👮🏻

# PR Checklist:

- [ ] Have you run the unit, integration and smoke tests as described [here](https://docs.corda.net/head/testing.html)?
- [ ] If you added public APIs, did you write the JavaDocs?
- [ ] If the changes are of interest to application developers, have you added them to the [changelog](https://docs.corda.net/head/changelog.html) (`/docs/source/changelog.rst`), and potentially the [release notes](https://docs.corda.net/head/release-notes.html) (`/docs/source/release-notes.rst`)?
- [ ] If you are contributing for the first time, please read the [contributor agreement](https://docs.corda.net/head/contributing.html) now and add a comment to this pull request stating that your PR is in accordance with the [Developer's Certificate of Origin](https://docs.corda.net/head/contributing.html#merging-the-changes-back-into-corda).

Thanks for your code, it's appreciated! :)

2019-10-09 10:26 UTC, josecoll commented
@lankydan I've noticed you changed this doc to remove the step (old step 2/4) that @snedamle is stating is required. 
Please can you review and double check whether this step if required or not (since the code changed to support automatic transitioning of CZ to Signature constraints)

2019-10-09 10:28 UTC, josecoll commented
@snedamle you appear to have reverted back to the previous commit for this documentation.
This is not correct as the behaviour has changed (eg. code now supports auto-transitioning of CZ whitelisted states).

2019-10-09 10:39 UTC, lankydan commented on docs/source/cordapp-constraint-migration.rst
> +automatically propagate any pre-existing on-ledger *CZ whitelisted* constrained states (and generate *signature* constrained outputs).sn
There is a random "sn" at the end here

2019-10-09 10:40 UTC, lankydan commented
@josecoll The cordapp must be whitelisted to transition a state with a whitelist constraint to a signature constraint. But that is only included in 4.3 not 4.0.

2019-10-09 10:44 UTC, lankydan commented
I think the change is fine in general. Really, I need to update this doc myself to add a 4.3 version to detail the content in "later releases". As later releases, is actually implemented in the version that the docs are for...

2019-10-09 10:48 UTC, josecoll commented
Right - ok. So basically you've accidentally merged the 4.3 instructions into a previous version.
Please can you add a PR to revert this (we can close this PR as it refers to 4.3 - so the instructions are correct at this point).

On a related point, we now have a documentation guideline that states "not to mention forward version functionality" (so we should remove the section on "Later releases" completely). @edward-prosser can you confirm this is guideline is enforce.

2019-10-09 11:11 UTC, josecoll commented
@snedamle to summarise:

Corda OS 4.0 and Corda OS 4.1 correctly detail the 4 steps required for these versions:
https://docs.corda.net/releases/release-V4.0/cordapp-constraint-migration.html
https://docs.corda.net/releases/release-V4.1/cordapp-constraint-migration.html

Corda OS 4.3 (aka. master, next version of Corda OS, there is no OS 4.2) correctly details the 3 steps for 4.3 functionality:
https://docs.corda.net/releases/head/cordapp-constraint-migration.html

2019-10-09 11:25 UTC, josecoll commented
@lankydan 
I recommend we explicitly reference the Corda version variable (`|corda_version|`)so that the headings do not confuse the end reader.

eg. header in the RST source
```
Corda |corda_version|
~~~~~~~~~~~~~~~~~~~~~
```

2019-10-10 08:07 UTC, snedamle commented
ok got it, adding the jar hash to whitelistzone param in network param will be automatically handled in version 4.3. so no changes required for 4.3. closing this merge request then.

2019-10-10 08:22 UTC, lankydan commented
The cordapp must still be in the whitelistzone param. The only automatic bit is the migration to signature constraints.

2019-10-10 08:33 UTC, lankydan commented on docs/source/cordapp-constraint-migration.rst
Ok, so i think I have not explained this very well. And now it is finally clicking in my head. I think we should add the docs back in that you are suggesting (adding the hash to the whitelist).

I think this point (2.) should stay as what I wrote. But with an extra clause:

"Any flow that builds transactions using this CorDapp will automatically transition states to use the ``SignatureAttachmentConstraint`` if no other constraint is specified __and the CorDapp continues to be whitelisted__. Therefore, there are two ways to alter the existing code."

Then add your addition into point 3 explaining how to whitelist a cordapp. Or add how to whitelist a cordapp as a note box under part 2.

The part 3 you added is not needed.

2019-10-10 08:33 UTC, lankydan commented
I would also recommend changing the header from 4.0 to 4.3 as @josecoll suggested. I think at that point it should be good. Sorry for all the confusion

2019-10-11 08:16 UTC, josecoll requested changes
Looks good - just some minor edits on the version number.

2019-10-11 08:16 UTC, josecoll commented on docs/source/cordapp-constraint-migration.rst
> +Corda 4.3
Use variable so we don't need to change this in future releases:
change `4.3` for `|corda_version|`

2019-10-11 08:16 UTC, josecoll commented on docs/source/cordapp-constraint-migration.rst
> +Corda 4.3 requires some additional steps to consume and evolve pre-existing on-ledger **hash** constrained states:
same: change `4.3` for `|corda_version|`

2019-10-11 08:16 UTC, josecoll commented on docs/source/cordapp-constraint-migration.rst
> +Corda 4.3
ditto: change `4.3` for `|corda_version|`

2019-10-11 08:54 UTC, josecoll approved these changes
Looks good to me.
@lankydan please give it a final thumbs up!

2019-10-11 13:31 UTC, lankydan approved these changes
👍 LGTM

2019-11-01 10:49 UTC, merged