CORDA-3043 RPC Invocation fails when calling classes with defaulted constructors O/S
corda/corda pull request #5569
Opened 2019-10-09 08:52 UTC by nickdunstone13

RPC Invocation fails when calling classes with defaulted constructors.

This change is for 4.3 and related to Jira:

https://r3-cev.atlassian.net/browse/CORDA-3043

The new logic is to try all constructors and find ones where the parameters match up to the number supplied by the caller. Additional constructor parameters must be defaulted. If there are multiple matches then the constructor with the least number of defaulted arguments used is preferred. It will never fail for multiple constructor matches.

2019-10-09 10:11 UTC, rick-r3 requested changes

2019-10-09 10:11 UTC, rick-r3 commented on node/src/main/kotlin/net/corda/node/services/statemachine/FlowLogicRefFactoryImpl.kt
> +                    val argType = argTypes[index]
Extract content of this entire loop and the variables above the loop into a private method.  e.g. `checkMatch`

2019-10-09 10:11 UTC, rick-r3 commented on node/src/main/kotlin/net/corda/node/services/statemachine/FlowLogicRefFactoryImpl.kt
> +            val optional = ArrayList<Boolean>()
You can use `map` here like is used on the `ctorTypes` to do this pretty much on one line.

2019-10-09 10:11 UTC, rick-r3 commented on node/src/main/kotlin/net/corda/node/services/statemachine/FlowLogicRefFactoryImpl.kt
> +    private val log: Logger = LoggerFactory.getLogger("net.corda.flow")
Put this in a companion object.

2019-10-09 10:11 UTC, rick-r3 commented on node/src/main/kotlin/net/corda/node/services/statemachine/FlowLogicRefFactoryImpl.kt
> +    private val log: Logger = LoggerFactory.getLogger("net.corda.flow")
Is probably does not need to define the logger name.  Perhaps better to stick with `contextLogger()` we use to just auto name them.

2019-10-09 10:11 UTC, rick-r3 commented on node/src/main/kotlin/net/corda/node/services/statemachine/FlowLogicRefFactoryImpl.kt
> +        log.debug { "${javaClass.name}.findConstructorCheckDefaultParams() called for RPC parameter argument types:" }
You wouldn't need this class name qualification if the logger was named the normal way.

2019-10-09 10:11 UTC, rick-r3 commented on node/src/main/kotlin/net/corda/node/services/statemachine/FlowLogicRefFactoryImpl.kt
> +            conInd++
Maybe start from zero and increment at the end of the loop (more in keeping with others).

2019-10-09 10:11 UTC, rick-r3 commented on node/src/main/kotlin/net/corda/node/services/statemachine/FlowLogicRefFactoryImpl.kt
> +                    val opt = if (index < optional.size) { optional[index] } else { false }
Can we ever get into the `else` ?

2019-10-09 10:11 UTC, rick-r3 commented on node/src/main/kotlin/net/corda/node/services/statemachine/FlowLogicRefFactoryImpl.kt
> +                    val opt = if (index < optional.size) { optional[index] } else { false }
This looks like we assume optional args are at the end?  This isn't necessarily true (I think!).  Maybe you could check? Which suggests a much more intensive evaluation of each constructor (if it has any defaults and args.size != params.size).

2019-10-09 10:11 UTC, rick-r3 commented on node/src/main/kotlin/net/corda/node/services/statemachine/FlowLogicRefFactoryImpl.kt
> +                    val opt = if (index < optional.size) { optional[index] } else { false }
The real flaw here is that we don't have a named parameter API in RPC, which is a big failure.  I'll raise a JIRA.

I think if there are conflicting permutations via this un-named API, we refuse to choose one.

2019-10-09 10:11 UTC, rick-r3 commented on node/src/main/kotlin/net/corda/node/services/statemachine/FlowLogicRefFactoryImpl.kt
> +            // There must be at least as many constructor arguments as supplied arguments
Should this also `continue` if they are `==`, since that would have meant a direct match ?

2019-10-09 10:11 UTC, rick-r3 commented on node/src/main/kotlin/net/corda/node/services/statemachine/FlowLogicRefFactoryImpl.kt
> +            if (matched) {
All this could be extracted into a helper private function I think.

2019-10-09 10:11 UTC, rick-r3 commented on node/src/main/kotlin/net/corda/node/services/statemachine/FlowLogicRefFactoryImpl.kt
> +            var argSummary = "" // Create a meaningful error message for the client
Helper function?

2019-10-09 10:11 UTC, rick-r3 commented on node/src/main/kotlin/net/corda/node/services/statemachine/FlowLogicRefFactoryImpl.kt
> +        return ctorMatch
Okay, so a constructor is returned, but does the caller know how to call it ?

2019-10-09 10:42 UTC, nickdunstone13 commented on node/src/main/kotlin/net/corda/node/services/statemachine/FlowLogicRefFactoryImpl.kt
> +    private val log: Logger = LoggerFactory.getLogger("net.corda.flow")
Done. Also I've refactored and removed most of the logging anyway

2019-10-09 10:43 UTC, nickdunstone13 commented on node/src/main/kotlin/net/corda/node/services/statemachine/FlowLogicRefFactoryImpl.kt
> +        log.debug { "${javaClass.name}.findConstructorCheckDefaultParams() called for RPC parameter argument types:" }
Done (removed anyway).

2019-10-09 10:44 UTC, nickdunstone13 commented on node/src/main/kotlin/net/corda/node/services/statemachine/FlowLogicRefFactoryImpl.kt
> +            conInd++
Main reason was that there was a continue which means you have to increment in more than one place. In the past I've forgot to add in. Removed that anyway.

2019-10-09 10:46 UTC, nickdunstone13 commented on node/src/main/kotlin/net/corda/node/services/statemachine/FlowLogicRefFactoryImpl.kt
> +            val optional = ArrayList<Boolean>()
Of course.

2019-10-09 14:03 UTC, nickdunstone13 commented on node/src/main/kotlin/net/corda/node/services/statemachine/FlowLogicRefFactoryImpl.kt
> +                    val argType = argTypes[index]
Already done.

2019-10-10 10:29 UTC, nickdunstone13 commented on node/src/main/kotlin/net/corda/node/services/statemachine/FlowLogicRefFactoryImpl.kt
> +            // There must be at least as many constructor arguments as supplied arguments
I'm not sure what you are referring to here. I have re-factored quite a bit anyway so will mark this resolved. If it's still an issue then comment again on the new code

2019-10-10 10:31 UTC, nickdunstone13 commented on node/src/main/kotlin/net/corda/node/services/statemachine/FlowLogicRefFactoryImpl.kt
> +                    val opt = if (index < optional.size) { optional[index] } else { false }
We do assume (as per the conversation yesterday) that optional arguments are at the end, until such time as we pass a map of parameter names vs values. We can do that if need be via separate Jira. I'll mark as resolved in the context of this Jira.

2019-10-10 10:33 UTC, nickdunstone13 commented on node/src/main/kotlin/net/corda/node/services/statemachine/FlowLogicRefFactoryImpl.kt
> +                    val opt = if (index < optional.size) { optional[index] } else { false }
Regarding the else (index < optional.size) then strictly no but it's a safety check as the optional comes from a different object to the rest (kotlin vs java objects). It seemed sensible to sanity check it just in case and not throw.

2019-10-10 10:34 UTC, nickdunstone13 commented on node/src/main/kotlin/net/corda/node/services/statemachine/FlowLogicRefFactoryImpl.kt
> +            if (matched) {
Matching logic has been taken out into a separate function.

2019-10-10 10:34 UTC, nickdunstone13 commented on node/src/main/kotlin/net/corda/node/services/statemachine/FlowLogicRefFactoryImpl.kt
> +            var argSummary = "" // Create a meaningful error message for the client
Indeed and done.

2019-10-10 10:36 UTC, nickdunstone13 commented on node/src/main/kotlin/net/corda/node/services/statemachine/FlowLogicRefFactoryImpl.kt
> +        return ctorMatch
Ironically I'm not sure it actually gets called. This appears to be used to validate there is a match. I have found that in reality it calls what ever it decides matches (it being either somewhere else in the program or some other library we use). I have found that (by reordering constructors I can make the actual one called different to the one returned by this method (when there are 2 or more that match)).

2019-10-11 10:00 UTC, rick-r3 approved these changes

2019-10-11 10:00 UTC, merged