CORDA-3081  …
corda/corda pull request #5601
Opened 2019-10-16 17:25 UTC by szymonsztuka

warn that flow ID passed to flow kill is malformed as due to JDK8 doesn't fully validate it - JDK8 bug https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8159339

Test procedure:
``./gradlew samples:trader-demo:deploynodes``

``cd ./samples/trader-demo/build/nodes``

edit "Bank A"/node.conf , add ``sshdPort : 2223``

``./runnodes``

in "Bank A" shell: 
 ``flow start CashIssueFlow amount: $100, issuerBankPartyRef: 123, notary: "Notary Service" ``

kill BankOfCorda node

in "Bank A"  shell:
``flow watch``

on the terminal (not any node's shell):  ``ssh demo@localhost -p 2222``
and : ``flow start CashPaymentFlow amount: $1, recipient: BankOfCorda``

on Bank A shell you should see e.g:
``f1fc0302-e4f3-4e75-bb64-2db181777eaf       Cash Payment     demo      In progress
Waiting for completion or Ctrl-C ...``

Copy flow ID
Ctrl+C

``flow kill <flow-id>`` but remove two last characters to give wrong ID e.g.:
``flow kill f1fc0302-e4f3-4e75-bb64-2db181777ea
Flow ID of 'f1fc0302-e4f3-4e75-bb64-2db181777ea' seems to be malformed - a UUID should have 36 characters. Expand the terminal window to see the full UUID value.
Failed to kill flow [f1fc0302-e4f3-4e75-bb64-02db181777ea]``

then to check if the flow can be killed:
``flow kill <flow-id>``
e.g:
``flow kill f1fc0302-e4f3-4e75-bb64-2db181777eaf
[ERROR] 18:17:24+0100 [Node thread-1] corda.flow. - Flow interrupted while waiting for events, aborting immediately {actor_id=demo, actor_owning_identity=O=Bank A, L=London, C=GB, actor_store_id=NODE_CONFIG, fiber-id=10000001, flow-id=f1fc0302-e4f3-4e75-bb64-2db181777eaf, invocation_id=a082a238-9d2b-492a-9ecd-8b524e0a986f, invocation_timestamp=2019-10-16T17:17:03.533Z, origin=demo, session_id=f4a2c62b-a851-4655-aa4e-df4f67016dfa, session_timestamp=2019-10-16T17:16:43.823Z, thread-id=164}
Killed flow [f1fc0302-e4f3-4e75-bb64-2db181777eaf]``

2019-10-17 09:53 UTC, anthonykeenan requested changes

2019-10-17 09:53 UTC, anthonykeenan commented on tools/shell/src/main/kotlin/net/corda/tools/shell/InteractiveShell.kt
> +                log.warn(msg)
Should we not return here?

2019-10-17 10:22 UTC, szymonsztuka commented on tools/shell/src/main/kotlin/net/corda/tools/shell/InteractiveShell.kt
> +                log.warn(msg)
Yes we could, with extended msg ? - as the error from the invocation will not be displayed:
```
 val msg = "Can not kill the flow. Flow ID of '$id' seems .....
```

2019-10-18 15:39 UTC, anthonykeenan commented on tools/shell/src/main/kotlin/net/corda/tools/shell/InteractiveShell.kt
> +                log.warn(msg)
Yes sounds good.

2019-10-22 09:53 UTC, anthonykeenan approved these changes
Looks good

2019-10-22 10:32 UTC, merged