Update UAT.md
corda/corda pull request #5602
Opened 2019-10-17 08:50 UTC by carolynequinn

Includes 
- new url for "how to join" - now directing users to corda.network website
- Some new wording to call it Pre-Production more than UAT (our current preference)

2019-10-25 09:12 UTC, colljos requested changes
Minor points.

2019-10-25 09:12 UTC, colljos commented on docs/source/corda-network/UAT.md
> +Corda Network Pre-Production (or UAT) seeks to provide a test environment which is as close as possible to Corda Network in its make-up and operation.
I think you should remove the `(or UAT)` part to avoid future confusion and prevent this environment ever being referred to as UAT again (which I assume is the purpose of this doc renaming)

2019-10-25 09:12 UTC, colljos commented on docs/source/corda-network/UAT.md
> +*The below joining steps assume the potential participant is joining the Pre-Production environment directly, and as such is not “sponsoring” or onboarding other participants. If this is the case, pl
the end of the sentence seems incomplete:
"how to ‘sponsor’ end-participants on.*" 
???

2019-10-25 09:12 UTC, colljos commented on docs/source/corda-network/UAT.md
> +Corda Network Pre-Production is governed by an [independent Foundation](https://corda.network/governance/index.html).
inconsistent spelling: 
independent (lower-case)
Foundation (upper-case)

2019-11-05 08:11 UTC, carolynequinn commented on docs/source/corda-network/UAT.md
> +*The below joining steps assume the potential participant is joining the Pre-Production environment directly, and as such is not “sponsoring” or onboarding other participants. If this is the case, pl
this is fine!

2019-11-05 08:12 UTC, carolynequinn reviewed
happy with all of these changes - no further changes needed.

2019-11-06 06:57 UTC, carolynequinn commented on docs/source/corda-network/UAT.md
> +Corda Network Pre-Production (or UAT) seeks to provide a test environment which is as close as possible to Corda Network in its make-up and operation.
unfortunately we need to keep this in, for now... a lot of ppl still use this term so better to keep in to be clear

2019-11-12 17:30 UTC, josecoll commented
Removing myself from this PR as my comments have not been addressed.

2019-12-15 19:21 UTC, fenryka commented
If this is docs please add in @edward-prosser

2019-12-16 10:25 UTC, edward-prosser approved these changes

2019-12-19 18:28 UTC, merged