CORDA-3281: Interactive shell clean up for gracefulShutdown
corda/corda pull request #5605
Opened 2019-10-17 14:07 UTC by fowlerrr

Drop some errors to warnings and clean up logic around the "gracefulShutdown" command.

The errors weren't actually errors since they were around RPC disconnects which were already being handled by the `ReconnectingCordaRPCOps`.

The main bug was the shell calling `terminate` on the node and _then afterwards_ trying to connect to get the pending flows and watch/println them as they finished.  This won't work when there aren't any flows to watch.  Also, it's just plain backwards.  So I moved the code around to subscribe to the pending flows first and then call terminate after.

There was also a lot of dead code around the shell handling of `gracefulShutdown`.  So I've tidied that up.

Finally since I was touching some files I appeased the `detekt` gods with some long line cleanups.

2019-10-17 14:22 UTC, fowlerrr commented on client/rpc/src/main/kotlin/net/corda/client/rpc/CordaRPCClient.kt
> +                shutdownNow()
This may be controversial.  But I think we can get away with just shutting down the threads as we know the connection is down now anyway.

2019-10-17 14:22 UTC, fowlerrr commented on node/src/main/kotlin/net/corda/node/internal/CordaRPCOpsImpl.kt
All of the changes is this file are line length fixes for `detekt`

2019-10-17 14:22 UTC, fowlerrr commented on tools/shell/src/main/kotlin/net/corda/tools/shell/InteractiveShell.kt
> +            display { println("RPC failed: ${e.rootCause}", Color.red) }
I actually reverted the logic here.  It'll now actually display something on an error.

2019-10-17 15:35 UTC, JamesHR3 reviewed
A few minor comments, mostly around tidying up.

I think logic wise we're ok here, but I think it might be worth getting a third pair of eyes on it, particularly from someone who has a better knowledge of `CordaRPCOps` than me.

2019-10-17 15:35 UTC, JamesHR3 commented on client/rpc/src/main/kotlin/net/corda/client/rpc/CordaRPCClient.kt
> +                shutdownNow()
We know that the connection is down, but this is the observers thread pool that's being shut down. Is it possible that a client is subscribed to some observables and is expecting their `onNext`/`onComplete` calls to be invoked while the connection is closing? Feels like it's possible for some events to have been received through them before the close but the processing of them hasn't happened yet.

2019-10-17 15:35 UTC, JamesHR3 commented on node/src/main/kotlin/net/corda/node/internal/CordaRPCOpsImpl.kt
> +        val (snapshot, updates) =
Extremely minor but did this line cause a `detekt` warning?

2019-10-17 15:35 UTC, JamesHR3 commented on tools/shell/src/main/kotlin/net/corda/tools/shell/InteractiveShell.kt
> +    // TODO: This utility is generally useful and might be better moved to the node class, or an RPC,
This TODO is getting on for 3 years old - I can't see this ever making the stable API. Maybe I'm wrong but I think we can probably just remove it.

2019-10-17 15:35 UTC, JamesHR3 commented on tools/shell/src/main/kotlin/net/corda/tools/shell/InteractiveShell.kt
> +                            { (first, second) -> display { println("...remaining: $first / $second") } },
Can we change the name of `first` and `second` to something a bit more descriptive? I assume these are the completed and pending flows respectively but I had to go and look that up.

2019-10-17 15:35 UTC, JamesHR3 commented on tools/shell/src/main/kotlin/net/corda/tools/shell/InteractiveShell.kt
>          } catch (e: StringToMethodCallParser.UnparseableCallException) {
This function doesn't use a `StringToMethodCallParser`, so I don't think we can ever catch this exception here. (It could happen in the calling function, where I suspect this has been copy-pasted from.) We can probably delete this block.

2019-10-18 07:03 UTC, fowlerrr commented on node/src/main/kotlin/net/corda/node/internal/CordaRPCOpsImpl.kt
> +        val (snapshot, updates) =
This one probably wasn't `detekt` so much as Intellij expanding the line past a limit to inline the types of `snapshot` and `updates`.

2019-10-18 07:06 UTC, fowlerrr commented on tools/shell/src/main/kotlin/net/corda/tools/shell/InteractiveShell.kt
> +    // TODO: This utility is generally useful and might be better moved to the node class, or an RPC,
Removing.

2019-10-18 09:47 UTC, fowlerrr commented on client/rpc/src/main/kotlin/net/corda/client/rpc/CordaRPCClient.kt
> +                shutdownNow()
Brought it back.  It was actually the `stateMachinesFeed()` subscription in `pendingFlowsCount()` that was holding us up.  It needed an unsubscribe after the flows were finished or it would hold up shutdown

2019-10-18 10:05 UTC, shamsasari commented on client/rpc/src/main/kotlin/net/corda/client/rpc/RPCConnection.kt
> +    override fun close() = notifyServerAndClose()
Can you update the kdoc for `notifyServerAndClose` to say that that method is the implementation of the `close` method.

2019-10-18 10:08 UTC, shamsasari commented on client/rpc/src/main/kotlin/net/corda/client/rpc/CordaRPCClient.kt
> +    {
Move brace up

2019-10-18 10:08 UTC, shamsasari commented on client/rpc/src/main/kotlin/net/corda/client/rpc/CordaRPCClient.kt
> +    private fun doCloseLogic(close: () -> Unit)
Make `inline`

2019-10-18 10:16 UTC, shamsasari commented on node/src/main/kotlin/net/corda/node/internal/CordaRPCOpsImpl.kt
> +        val (snapshot, updates) =
Can you move the `@Supress` above the line so that this call is one one line.

2019-10-18 12:13 UTC, fowlerrr commented on client/rpc/src/main/kotlin/net/corda/client/rpc/CordaRPCClient.kt
> +    {
Can you tell I once worked with C++?

2019-10-18 15:31 UTC, fowlerrr commented on node/src/main/kotlin/net/corda/node/internal/CordaRPCOpsImpl.kt
> +        val (snapshot, updates) =
Done

2019-10-18 15:54 UTC, shamsasari requested changes
The `RPCConnection` classes no longer need to implement `close`.

2019-10-22 09:56 UTC, shamsasari approved these changes

2019-10-22 10:02 UTC, merged