TM-67 converting ImageBuilding from groovy to java
corda/corda pull request #5609
Opened 2019-10-17 16:08 UTC by Schife

Converting file from groovy to java for better readability and to remove the risk or groovy going rogue

2019-10-17 17:02 UTC, zkiss commented on buildSrc/src/main/groovy/net/corda/testing/ImageBuilding.java
> +        String password = !System.getProperty("docker.push.password").isEmpty() ? System.getProperty("docker.push.password") : "";
Could use `System.getProperty("docker.push.password", "")`

2019-10-18 09:23 UTC, barrylapthorn commented
General comment:  you can add `final` in a lot of places.

Also you can add (jetbrains) annotations, `@NotNull` or `@Nullable` to method parameters and return types, which helps out Intellij and its static tools.

2019-10-18 09:37 UTC, r3domfox commented
> General comment: you can add `final` in a lot of places.
> 
> Also you can add (jetbrains) annotations, `@NotNull` or `@Nullable` to method parameters and return types, which helps out Intellij and its static tools.

Agreed, we're stepping outside of the Kotlin Safety Zone, and should make use of whatever guard-rails are available to help us stay bug-free.

2019-10-18 09:43 UTC, Schife commented
Once I get a green build, which now seems likely I'll proceed to add all the guard-rails

2019-10-18 11:03 UTC, barrylapthorn requested changes

2019-10-18 11:03 UTC, barrylapthorn commented on buildSrc/src/main/groovy/net/corda/testing/ImageBuilding.java
> +                            System.getProperty("docker.work.dir") : System.getProperty("java.io.tmpdir"));
`System.getProperty("docker.work.dir")` can return if it is not set, so `System.getProperty("docker.work.dir").isEmpty()` would throw a `NullReferenceException` (I think - I may be wrong).  So @zkiss 's comment, earlier, do

```
System.getProperty("docker.work.dir", "").isEmpty()
```
Also, looks a bit different to the groovy version.

```
             File baseWorkingDir = new File(System.getProperty("docker.work.dir") ? System.getProperty("docker.work.dir") : System.getProperty("java.io.tmpdir"))
```

2019-10-18 11:03 UTC, barrylapthorn commented on buildSrc/src/main/groovy/net/corda/testing/ImageBuilding.java
> +                    File mavenDir = new File(baseWorkingDir, "maven");
More opportunity for `final`

2019-10-18 11:03 UTC, barrylapthorn commented on buildSrc/src/main/groovy/net/corda/testing/ImageBuilding.java
> +                    HashMap<String, String> map = new HashMap<>();
LHS side could just be `Map<..>`

2019-10-18 11:40 UTC, roastario commented on buildSrc/src/main/groovy/net/corda/testing/ImageBuilding.java
> +                            System.getProperty("docker.work.dir") : System.getProperty("java.io.tmpdir"));
Optionals are your friend!

2019-10-18 12:11 UTC, Schife commented on buildSrc/src/main/groovy/net/corda/testing/ImageBuilding.java
> +                    File mavenDir = new File(baseWorkingDir, "maven");
Done deal

2019-10-18 12:12 UTC, Schife commented on buildSrc/src/main/groovy/net/corda/testing/ImageBuilding.java
> +                    HashMap<String, String> map = new HashMap<>();
Agree

2019-10-18 12:14 UTC, Schife commented on buildSrc/src/main/groovy/net/corda/testing/ImageBuilding.java
> +                            System.getProperty("docker.work.dir") : System.getProperty("java.io.tmpdir"));
System.getProperty does throw a null pointer hence the null check before it. As for the different look it's because Java does not have a simple way like groovy to check if something exists. Functionally the code does the same thing

2019-10-18 13:38 UTC, roastario approved these changes

2019-10-18 15:42 UTC, zkiss approved these changes

2019-10-18 15:53 UTC, r3domfox approved these changes
LGTM

2019-10-18 15:53 UTC, r3domfox commented on buildSrc/src/main/groovy/net/corda/testing/ImageBuilding.java
> +    public DockerPushImage pushTask;
`private final` with a getter?

2019-10-18 15:54 UTC, merged