Re enabling persistent volume claims
corda/corda pull request #5628
Opened 2019-10-22 12:48 UTC by Schife

Instead of making use of azure disks, I've created a new type of storage class centered around azure files which are a less expensive form of storage.

2019-10-22 14:05 UTC, zkiss submitted a review, later dismissed

2019-10-22 14:05 UTC, zkiss commented on buildSrc/src/main/groovy/net/corda/testing/KubesTest.java
> +        return executorService.submit(new Callable<KubePodResult>() {
seems like this could be a lambda

2019-10-22 14:15 UTC, Schife commented on buildSrc/src/main/groovy/net/corda/testing/KubesTest.java
> +        return executorService.submit(new Callable<KubePodResult>() {
I'm just reintroducing the code that was already there

2019-10-25 12:33 UTC, roastario requested changes
Looks good Raz, could you just commit the .yaml that creates the storage class?

2019-10-25 14:57 UTC, roastario requested changes

2019-10-25 14:57 UTC, roastario commented on buildSrc/src/main/groovy/net/corda/testing/KubesTest.java
> +        Path tempDir = new File(new File(TEST_RUN_DIR, "test-results-xml"), podName).toPath();
this I think is incorrect - we should leave the original path here, as this is the path on the machine we are downloading to.

2019-10-25 15:13 UTC, Schife commented on buildSrc/src/main/groovy/net/corda/testing/KubesTest.java
> +        Path tempDir = new File(new File(TEST_RUN_DIR, "test-results-xml"), podName).toPath();
you are correct

2019-10-28 15:54 UTC, roastario submitted a review, later dismissed

2019-10-29 16:22 UTC, roastario commented
Looks good to me!

2019-10-29 16:22 UTC, roastario approved these changes

2019-10-29 16:23 UTC, merged