[CORDA-3350] - Increase size of constraints column
corda/corda pull request #5639
Opened 2019-10-28 12:17 UTC by dimosr

### Changes
Increasing the column size for constraints, so that it can accommodate `CompositeKey`s with many leaf keys. Given this change affects consensus, it's gated on the min platform version of the network.

### Testing
Executed the following set of manual tests:
- Run a node with the default finance CorDapp (1 signature) on a network with min. platform version of 4. Verified the CorDapp can be used successfully.
- Run a node with the finance CorDapp after adding one more signature (2 signatures) on a network with min. platform version of 4. Verified transactions fail during verification with the following message:
```
 ✓ Starting
      Generating anonymous identities
 ✓ Generating transaction
▶︎ Signing transaction
✘ Finalising transaction
✘ Done
☂ Composite keys for signature constraints requires all nodes on the Corda compatibility zone to be running at least platform version 5. The current zone is only enforcing a minimum platform version of 4. Please contact your zone operator.
```
- Run a node with the finance CorDapp after adding two more signatures (3 in total) on a network with min. platform version 5. Attempted a transaction with the previous version of Corda and the new version. Verified that transaction initially failed with the error reported in the ticket and it was successful on the new version of Corda with the fix.

2019-10-28 14:56 UTC, tudor-malene requested changes
It would be a good idea to also add a check in the TransactionBuilder.
Basically serialize the constraint type of each issued state and check that the size < max.

To catch any problems early in case someone tries to do something crazy at some point.

2019-10-28 15:09 UTC, dimosr commented
@tudor-malene I agree it's better to fail as early as possible. I'll add a check in the transaction builder too, but I'd prefer to add the same check as in ledger transaction for behaviour consistency and to also avoid any performance implications of the additional serialization.

2019-10-28 16:11 UTC, tudor-malene commented on core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
> +    private fun checkForUnsupportedConstraints(transactionState: TransactionState<ContractState>, services: ServicesForResolution) {
I didn't mean this check. This is already done in the LedgerTransaction, which is run during building.

I meant a check for the future, when the network is on version 5 already.
To protect against someone adding a constraint with more then 10 public keys that will not be able to fit in the 10_000 bytes.

2019-10-28 16:18 UTC, dimosr commented on core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
> +    private fun checkForUnsupportedConstraints(transactionState: TransactionState<ContractState>, services: ServicesForResolution) {
ah, I see. How about putting an upper limit on 10 keys, instead of checking the serialized size? That might have a bit cleaner semantics.

2019-10-28 16:23 UTC, dimosr commented on core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
> +    private fun checkForUnsupportedConstraints(transactionState: TransactionState<ContractState>, services: ServicesForResolution) {
ah, I see. How about setting an explicit upper limit on 10 keys, instead of checking the serialized size? That might have a bit cleaner semantics.

2019-10-29 13:17 UTC, tudor-malene requested changes
Few minor things.

I think 2 tests would be helpful:
1. test that currently it fails early with 2 signatures over a jar.
2. test that with mpv=5 it works with 20 but fails with 21.

2019-10-29 13:17 UTC, tudor-malene commented on core/src/main/kotlin/net/corda/core/contracts/TransactionVerificationException.kt
> +    class InvalidConstraintRejection(txId: SecureHash, val contractClass: String, val reason: String)
You should also add a serialization test for this exception - TransactionVerificationExceptionSerialisationTests.

2019-10-29 13:17 UTC, tudor-malene commented on core/src/main/kotlin/net/corda/core/internal/ConstraintsUtils.kt
> + */
I would also add in this comment that this is a consensus value, and it can't be changed without an mpv bump.

2019-10-29 13:17 UTC, tudor-malene commented on core/src/main/kotlin/net/corda/core/internal/TransactionVerifierServiceInternal.kt
> +                    checkMinimumPlatformVersion(ltx.networkParameters?.minimumPlatformVersion ?: 1, 5,
Some comments with context would be helpful here.

2019-10-30 10:33 UTC, tudor-malene submitted a review, later dismissed
LGTM!
Great work. 
Maybe @rick-r3  should also take a look to validate that adding this new consensus rule is ok.

2019-11-01 10:21 UTC, rick-r3 submitted a review, later dismissed

2019-11-01 10:21 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/node/services/VaultService.kt
> +const val MAX_CONSTRAINT_DATA_SIZE = 1_000 * MAX_NUMBER_OF_KEYS_IN_SIGNATURE_CONSTRAINT
This sort of change makes me very nervous.  Can we please have a constant for pre-MVP 5 (the 563) and check the serialized size is not greater than that ?

2019-11-01 10:22 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/node/services/VaultService.kt
> +const val MAX_CONSTRAINT_DATA_SIZE = 1_000 * MAX_NUMBER_OF_KEYS_IN_SIGNATURE_CONSTRAINT
(to prevent anything sneaking under the wire that would previously have not fitted)

2019-11-01 10:25 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/node/services/VaultService.kt
> +const val MAX_CONSTRAINT_DATA_SIZE = 1_000 * MAX_NUMBER_OF_KEYS_IN_SIGNATURE_CONSTRAINT
And relax the other check about composite key or not.

2019-11-01 10:57 UTC, tudor-malene commented on core/src/main/kotlin/net/corda/core/node/services/VaultService.kt
> +const val MAX_CONSTRAINT_DATA_SIZE = 1_000 * MAX_NUMBER_OF_KEYS_IN_SIGNATURE_CONSTRAINT
@rick-r3 , the check for `mpv=4` is that there can be only 1 signer. Which is a stronger condition then this 563bytes max size.
It was added in the verify method of transactions.

2019-11-04 11:50 UTC, dimosr commented on core/src/main/kotlin/net/corda/core/node/services/VaultService.kt
> +const val MAX_CONSTRAINT_DATA_SIZE = 1_000 * MAX_NUMBER_OF_KEYS_IN_SIGNATURE_CONSTRAINT
Discussed it offline with Matthew too, since Rick's away atm. The main negative I see with the current check is that it still has some risk for breaking consensus, e.g. nodes running in 4 with bytesize-specific logic disagreeing with nodes running in 5 and using number-of-keys logic. So, I'll switch the `mpv < 5` logic to use bytesize logic.

Also, I think I'll enrich the `mpv >= 5` logic to also use bytesize logic as a failsafe against consensus break in degenerate cases that make use of unsupported composite keys (e.g. extremely large key sizes).

2019-11-04 11:58 UTC, tudor-malene commented on core/src/main/kotlin/net/corda/core/node/services/VaultService.kt
> +const val MAX_CONSTRAINT_DATA_SIZE = 1_000 * MAX_NUMBER_OF_KEYS_IN_SIGNATURE_CONSTRAINT
I really don't understand what's wrong with the current solution.

The *only* problem I see with it, is if someone has already managed to squeeze 2 public keys inside that 563 bytes, and has transactions done that way.

Or another potential problem is if someone on a network with only a db that didn't care about the field size has used more keys. But we wouldn't be solving this problem with a size check instead of a nr_of_signatures check.

2019-11-04 13:27 UTC, dimosr commented on core/src/main/kotlin/net/corda/core/node/services/VaultService.kt
> +const val MAX_CONSTRAINT_DATA_SIZE = 1_000 * MAX_NUMBER_OF_KEYS_IN_SIGNATURE_CONSTRAINT
[Discussed offline w/ @mnesbit @tudor-malene] Decision: remove any pre-5 logic completely, since it does not completely eliminate the disagreement coming from DB differences. Keep the logic for post-5.

2019-11-04 16:25 UTC, tudor-malene requested changes
Minor change

2019-11-04 16:25 UTC, tudor-malene commented on node/src/main/resources/migration/vault-schema.changelog-v10.xml
> +                        newDataType="varbinary(10000)"/>
shouldn't this be 20k ?

2019-11-04 16:29 UTC, dimosr commented on node/src/main/resources/migration/vault-schema.changelog-v10.xml
> +                        newDataType="varbinary(10000)"/>
ah yes, good catch. good thing tests didn't fail though, apparently there's enough headroom :)
will update this.

2019-11-04 16:40 UTC, dimosr commented on node/src/main/resources/migration/vault-schema.changelog-v10.xml
> +                        newDataType="varbinary(10000)"/>
P.S.: I also renamed the liquibase script to `v11` to align with ENT.

2019-11-04 16:52 UTC, mnesbit commented on core/src/main/kotlin/net/corda/core/node/services/VaultService.kt
> +const val MAX_CONSTRAINT_DATA_SIZE = 1_000 * MAX_NUMBER_OF_KEYS_IN_SIGNATURE_CONSTRAINT
Typical RSA 2048 bit key is 270 bytes  as ASN1 encoded, but we probably use our AMQP wrapper around that. So would be worth just commenting on the size of RSA, EdDSA and ECDSA composite trees as measured.

2019-11-04 17:13 UTC, dimosr commented on core/src/main/kotlin/net/corda/core/node/services/VaultService.kt
> +const val MAX_CONSTRAINT_DATA_SIZE = 1_000 * MAX_NUMBER_OF_KEYS_IN_SIGNATURE_CONSTRAINT
Did some measurements and updated the comment with the results.

2019-11-05 10:08 UTC, mnesbit approved these changes
OK

2019-11-05 10:56 UTC, tudor-malene approved these changes
LGTM!

The only thing left is to write something - somewhere that must be used to notify clients that they must manually increase the size of that column to stay out of trouble.

2019-11-05 11:00 UTC, merged