Fix for underscore variables
corda/corda pull request #5682
Opened 2019-11-06 13:02 UTC by StefanIliev545

Logic changed to use the validation schema for the node configuration and check for unknown keys, whilst ignoring missing required fields errors, as we are building config with only one key.

2019-11-06 13:03 UTC, StefanIliev545 commented
Dont merge me yet :)

2019-11-08 10:43 UTC, anthonykeenan submitted a review, later dismissed

2019-11-08 10:43 UTC, anthonykeenan commented on node/src/integration-test/kotlin/net/corda/node/NodeConfigParsingTests.kt
> +class NodeConfigParsingTests {
I would be more comfortable with a test to check that the issue that caused us to revert this last time is fixed

2019-11-08 11:28 UTC, chrisr3 requested changes
What _was_ the problem with the original code?

2019-11-08 11:28 UTC, chrisr3 commented on node/src/integration-test/kotlin/net/corda/node/NodeConfigParsingTests.kt
> +            assert(hasSsh)
Wrong `assert` function! Please  use JUnit's `assertTrue()` which doesn't require that the JVM run with `-ea`.

This comment applies _throughout_ this PR... :wink:

2019-11-08 11:28 UTC, chrisr3 commented on testing/node-driver/src/main/kotlin/net/corda/testing/driver/Driver.kt
> +            environmentVariables = emptyMap()
This is a `copy()` function, so you're effectively slicing any existing `environmentVariables` here. You need
```kotlin
environmenyVariables = environmentVariables
```
so that any existing variables are preserved.

2019-11-08 11:28 UTC, chrisr3 commented on testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/DriverDSLImpl.kt
> +            environmentVariables = defaultParameters.environmentVariables
Oops! Indentation!

2019-11-08 11:28 UTC, chrisr3 commented on node/src/main/kotlin/net/corda/node/services/config/ConfigUtilities.kt
> +
Why not just force `newKey` into lower case instead of using lots of :sparkles: `ignoreCase()` :sparkles: magic?

2019-11-08 11:28 UTC, chrisr3 commented on node/src/main/kotlin/net/corda/node/services/config/ConfigUtilities.kt
> +fun String.ignoreCase() = CaseInsensitiveUtils(this)
I _really_ don't like this :sob:. There _must_ be an easier way, and I am completely unmoved by people who want to write "CoRdA." or "coRDA.".

2019-11-08 11:39 UTC, StefanIliev545 commented on node/src/main/kotlin/net/corda/node/services/config/ConfigUtilities.kt
> +
It won't map to a config schema property as they are case sensitive.

2019-11-08 11:40 UTC, StefanIliev545 commented on node/src/main/kotlin/net/corda/node/services/config/ConfigUtilities.kt
> +fun String.ignoreCase() = CaseInsensitiveUtils(this)
It was a additional requirement in the original ticket Matthew opened, "ignoring corda. case sensitivity."

2019-11-08 11:43 UTC, StefanIliev545 commented on node/src/main/kotlin/net/corda/node/services/config/ConfigUtilities.kt
> +fun String.ignoreCase() = CaseInsensitiveUtils(this)
https://r3-cev.atlassian.net/browse/CORDA-3237

2019-11-08 11:44 UTC, mnesbit commented on node/src/main/kotlin/net/corda/node/services/config/ConfigUtilities.kt
> +fun String.ignoreCase() = CaseInsensitiveUtils(this)
I was probably a bit ambigious in my request. I really meant that corda_ and CORDA_ should work. I wasn't necessarily expecting to squash the rest of the property name that we substitute into the config file.

2019-11-14 13:44 UTC, chrisr3 requested changes
Better, but I suspect that `Config.cordaEntriesOnly()` can be simplified further :smiley_cat:.

2019-11-14 13:44 UTC, chrisr3 commented on node/src/integration-test/kotlin/net/corda/node/NodeConfigParsingTests.kt
> +import junit.framework.Assert.assertTrue
Not this one. You want `org.junit.Assert.assertTrue`.

2019-11-14 13:44 UTC, chrisr3 commented on node/src/main/kotlin/net/corda/node/services/config/ConfigUtilities.kt
> +import kotlin.reflect.full.memberProperties
These two imports are not used and so should be removed.

2019-11-14 13:44 UTC, chrisr3 commented on testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/DriverDSLImpl.kt
> +            environmentVariables = defaultParameters.environmentVariables
Still not fixed... This file also has some unused imports that it would be nice to remove :wink:.

2019-11-14 13:44 UTC, chrisr3 commented on node/src/main/kotlin/net/corda/node/services/config/ConfigUtilities.kt
> +                                .replace("_", ".")
It would probably be better to use
```kotlin
.replace('_', '.')
```
because you are only replacing a single character with another character, and are not replacing substrings.

2019-11-14 13:44 UTC, chrisr3 commented on node/src/main/kotlin/net/corda/node/services/config/ConfigUtilities.kt
> +                                    .removePrefix(CORDA_PROPERTY_PREFIX)))
`removePrefix()` is implemented as:
```kotlin
public fun String.removePrefix(prefix: CharSequence): String {
    if (startsWith(prefix)) {
        return substring(prefix.length)
    }
    return this
}
```
so maybe:
```kotlin
if (newKey.startsWith(CORDA_PROPERTY_PREFIX)
    && cordaPropOccurrences.contains(newKey.substring(CORDA_PROPERTY_PREFIX.length)))
```
would be more efficient?

2019-11-14 13:44 UTC, chrisr3 commented on node/src/main/kotlin/net/corda/node/services/config/ConfigUtilities.kt
> +                        CORDA_PROPERTY_PREFIX + nodeConfKey
Is this _always_ equal to `key`, seeing as you have defined `nodeConfKey` as:
```kotlin
val nodeConfKey = key.removePrefix(CORDA_PROPERTY_PREFIX)
```

2019-11-14 13:44 UTC, chrisr3 commented on node/src/integration-test/kotlin/net/corda/node/NodeConfigParsingTests.kt
> +import org.junit.Assert.assertTrue
Maybe move this `import` down to be with the other `org.junit` imports? :grin:

2019-11-14 13:44 UTC, chrisr3 commented on node/src/main/kotlin/net/corda/node/services/config/ConfigUtilities.kt
> +                        val nodeConfKey = key.removePrefix(CORDA_PROPERTY_PREFIX)
As above, using `substring()` would be more efficient because otherwise you're implicitly calling `startsWith()` again.

2019-11-14 16:41 UTC, chrisr3 submitted a review, later dismissed
LGTM - although that `CORDA_PROPERTY_PREFIX + key` concatenation is probably still superfluous :wink:.

2019-11-19 17:51 UTC, anthonykeenan approved these changes
Looks good now

2019-11-19 17:51 UTC, merged