TM-84 Reduce noise when excluding tests
corda/corda pull request #5688
Opened 2019-11-07 15:04 UTC by Schife

Create intersection between includes and excludes and remove the intersection from the includes, that way we only print relevant exclusions instead of creating noise

2019-11-11 14:32 UTC, barrylapthorn submitted a review, later dismissed

2019-11-11 14:32 UTC, barrylapthorn commented on Jenkinsfile
> +            archiveArtifacts artifacts: ['**/pod-logs/**/*.log', '**/build/test-results-xml/**/*.xml'], fingerprint: false
I guess this is fine because it is typically what TeamCity does anyway.  

Does it get compressed?  Otherwise that starts being quite sizeable I expect.  There was a prior piece of code I've removed that archived a zip of those files to Artifactory, but removed it since we didn't need it.

2019-11-11 14:32 UTC, barrylapthorn commented on build.gradle
> +    streamOutput true
Off when done :)

2019-11-11 14:32 UTC, barrylapthorn commented on buildSrc/src/main/groovy/net/corda/testing/DistributedTesting.groovy
>                      }
If you feel it is still readable, groovy 'magic' allows you to use the implicit iterator, i.e.

```
intersection.forEach { 
                        subProject.logger.info "excluding: $it for testing task ${task.getPath()}"
                        excludeTestsMatching it
                    }
```

2019-11-11 14:45 UTC, Schife commented on buildSrc/src/main/groovy/net/corda/testing/DistributedTesting.groovy
>                      }
We'll want to port this file as well to Java in the future so I refrained from using any groovy in this code except for closures

2019-11-11 14:58 UTC, roastario requested changes
change to DEBUG - otherwise LGTM

2019-11-11 14:58 UTC, roastario commented on buildSrc/src/main/groovy/net/corda/testing/DistributedTesting.groovy
> +                    subProject.logger.info "EXCLUDE: ${executedTests.toString()} "
can this be DEBUG level

2019-11-11 15:41 UTC, cairncross approved these changes
LGTM

2019-11-12 13:19 UTC, roastario approved these changes

2019-11-12 13:19 UTC, merged