NOTICK: Updated release notes for 4.3
corda/corda pull request #5692
Opened 2019-11-08 14:21 UTC by lockathan

Updated release notes for 4.3

2019-11-11 14:16 UTC, fenryka requested changes

2019-11-11 14:16 UTC, fenryka commented on docs/source/release-notes.rst
> +* Fix issue with Quasar errors redirecting to useless page [CORDA-2821]
Filter this for only issues, it's an absolute mess at the moment, also none of them are hyperlinked as per normal

2019-11-11 14:16 UTC, fenryka commented on docs/source/release-notes.rst
> +It’s been a little under 5 months since the release of Corda 4.1 added to the powerful suite of tools that Corda offers. Now, we are proud to release Corda 4.3, bringing over 400 fixes and documentat
does Corda offer tools? I think we offer features and functionality, tools tend to come via external additions

2019-11-11 14:16 UTC, fenryka commented on docs/source/release-notes.rst
> +Corda 4.3 supports enhancements to the Tokens SDK in the Tokens 1.1 release, coming later in 2019.
This doesn't make sense, if it's just adding back end things to enable features for the next Tokens release it doesn't sound very interesting, if it's actually adding functionality to the Tokens stuff talk about that, not what might happen later on

2019-11-11 14:16 UTC, fenryka commented on docs/source/release-notes.rst
> +Please note: Confidential Identities generated using the API available in Corda 4.1 and earlier are not compatible with the new Confidential Identities API functions in Corda 4.3.
That's a scary statement to read, what's the migration path? whats the impact to me as a node operator

2019-11-11 14:16 UTC, fenryka commented on docs/source/release-notes.rst
> +We're confident in the improvements made to RPC client connectivity but would remind you that applications should be developed with contingencies in the event of an RPC connection failure.
Can we link to a set of best practice docs? otherwise, we're saying "do it better, but we won't tell you how"

2019-11-11 14:16 UTC, fenryka commented on docs/source/release-notes.rst
> +This new functionality allows hosts to take a custodial role over their nodes, supporting a broader range of use-cases.
needs a doc link

2019-11-11 14:16 UTC, fenryka commented on docs/source/release-notes.rst
> +It’s been a little under 5 months since the release of Corda 4.1 added to the powerful suite of tools that Corda offers. Now, we are proud to release Corda 4.3, bringing over 400 fixes and documentat
Feels like this sentence repeats our previous release notes

2019-11-11 14:16 UTC, fenryka commented on docs/source/release-notes.rst
> +Corda 4.3 allows nodes to record transactions at different points in time with different levels of visibility.
docs link, as knowing *how* to do this might be helpful

2019-11-12 09:23 UTC, roger-that-dev requested changes

2019-11-12 09:23 UTC, roger3cev commented on docs/source/release-notes.rst
> +This new functionality allows hosts to take a custodial role over their nodes, supporting a broader range of use-cases.
https://github.com/corda/accounts/blob/master/docs.md

2019-11-12 09:23 UTC, roger3cev commented on docs/source/release-notes.rst
> +Please note: Confidential Identities generated using the API available in Corda 4.1 and earlier are not compatible with the new Confidential Identities API functions in Corda 4.3.
Just to be super clear:

1. On upgrade of 4.1 to 4.3, there is a schema migration which copies all the old CIs into the new CI tables - this is a one time upgrade.
2. Any old CIs generated after this point will not be reflected in the new tables. This is a bug which engineering choose not to fix this time round.
3. The fix will come in 4.4 which writes old CI info to the new tables. 

In addition: it's worth noting that:

* `IdentityService.wellKnownPartyFromAnonymous` works with both old CIs and new CIs. 
* `IdentityService.PartyFromKey` works with both old and new CIs
* `IdentityService.certificateFromCordaX500Name` with with both old and new CIs.
* Old CIs should be registered using `IdentityService.verifyAndRegisterIdentity` 
* New CIs should be registered using `IdentityService.registerKey`

2019-11-12 09:23 UTC, roger3cev commented on docs/source/release-notes.rst
> +Corda 4.3 supports enhancements to the Tokens SDK in the Tokens 1.1 release, coming later in 2019.
Maybe we can just remove this?

2019-11-12 11:14 UTC, edward-prosser submitted a review, later dismissed

2019-11-12 11:16 UTC, roger-that-dev approved these changes

2019-11-12 11:25 UTC, fenryka submitted a review, later dismissed
More comments

2019-11-12 11:25 UTC, fenryka commented on docs/source/release-notes.rst
> +Welcome to the Corda 4.3 release notes. Please read these carefully to understand what’s new in this release and how the changes can help you. Just as prior releases have brought with them commitment
continued commitments, Corda *is* Wire Stability

2019-11-12 11:25 UTC, fenryka commented on docs/source/release-notes.rst
> +Welcome to the Corda 4.3 release notes. Please read these carefully to understand what’s new in this release and how the changes can help you. Just as prior releases have brought with them commitment
also, repeated stability could just say wire and api etc

2019-11-12 11:25 UTC, fenryka commented on docs/source/release-notes.rst
> +
double blank line

2019-11-12 11:25 UTC, fenryka commented on docs/source/release-notes.rst
> +It’s been a little under 5 months since the release of Corda 4.1 added to the powerful suite of tools that Corda offers. Now, we are proud to release Corda 4.3, bringing over 400 fixes and documentat
still not addressed

2019-11-12 11:25 UTC, fenryka commented on docs/source/release-notes.rst
> +It’s been a little under 5 months since the release of Corda 4.1 added to the powerful suite of tools that Corda offers. Now, we are proud to release Corda 4.3, bringing over 400 fixes and documentat
is this resolved?

2019-11-12 11:25 UTC, fenryka commented on docs/source/release-notes.rst
> +It is worth noting that any confidential identities registered using the old API will not be reflected in the new tables after migration to Corda 4.3. However, the standard APIs work with both old an
What if my app uses the old CI interface is it being deprecated? is there a migration plan? can I continue? What's being addressed in a future release? (also we shouldn't say this at all as  it constitues a promise we may never enact)

2019-11-12 11:25 UTC, fenryka commented on docs/source/release-notes.rst
> +* more evident error message when multiple versions of the same CorDapp installed
no jira, no add

2019-11-12 11:34 UTC, roger-that-dev submitted a review, later dismissed

2019-11-12 11:34 UTC, roger3cev commented on docs/source/release-notes.rst
> +It is worth noting that any confidential identities registered using the old API will not be reflected in the new tables after migration to Corda 4.3. However, the standard APIs work with both old an
@lockathan 
Can still use old CIs. 
Nothing has been removed and probably will be removed any time soon.
The old flows and APIs are being deprecated.
The "migration path" is simply a case of using the new flows.

2019-11-12 11:42 UTC, lockathan commented on docs/source/release-notes.rst
> +Welcome to the Corda 4.3 release notes. Please read these carefully to understand what’s new in this release and how the changes can help you. Just as prior releases have brought with them commitment
Don't agree with your comment - I think we'd be making an assumption that a reader would assume Corda is wire stability. Also stability is not repeated.

2019-11-12 12:06 UTC, fenryka commented on docs/source/release-notes.rst
> +It is worth noting that any confidential identities registered using the old API will not be reflected in the new tables after migration to Corda 4.3. However, the standard APIs work with both old an
As long as we word it in such a way that we don't confuse / worry people :)

2019-11-12 12:06 UTC, fenryka commented on docs/source/release-notes.rst
> +Welcome to the Corda 4.3 release notes. Please read these carefully to understand what’s new in this release and how the changes can help you. Just as prior releases have brought with them commitment
it's not any more, it was when I made the comment

2019-11-12 12:08 UTC, fenryka commented on docs/source/release-notes.rst
> +Welcome to the Corda 4.3 release notes. Please read these carefully to understand what’s new in this release and how the changes can help you. Just as prior releases have brought with them commitment
They're not changes per-se, they're features. also they're valid in theory back to 3.0

2019-11-12 12:10 UTC, lockathan commented on docs/source/release-notes.rst
> +Welcome to the Corda 4.3 release notes. Please read these carefully to understand what’s new in this release and how the changes can help you. Just as prior releases have brought with them commitment
I can change that to read states and apps for 3.0 are valid in 4.3 (prettied up of course), but "in theory" worries me a little.

2019-11-12 12:18 UTC, fenryka commented on docs/source/release-notes.rst
> +Welcome to the Corda 4.3 release notes. Please read these carefully to understand what’s new in this release and how the changes can help you. Just as prior releases have brought with them commitment
oh, don't say in theory, they are... :)

2019-11-12 12:26 UTC, edward-prosser submitted a review, later dismissed

2019-11-12 12:54 UTC, roger-that-dev submitted a review, later dismissed

2019-11-12 15:26 UTC, CaisManai submitted a review, later dismissed

2019-11-12 15:43 UTC, edward-prosser approved these changes

2019-11-12 15:45 UTC, merged