NOTICK: Mention platform version change in release notes
corda/corda pull request #5721
Opened 2019-11-15 12:16 UTC by lockathan

Update the release notes to mention the platform version change.

2019-11-15 12:18 UTC, lockathan commented
I will also be raising a separate PR to update the versioning.rst file. This is because that change needs to go into 4.1 and be forward ported.

2019-11-15 12:36 UTC, edward-prosser submitted a review, later dismissed

2019-11-15 13:45 UTC, roger-that-dev submitted a review, later dismissed

2019-11-15 13:48 UTC, gendal commented on docs/source/release-notes.rst
> +
Maybe add: "Since the APIs added do not affect the wire protocol or have other zone-level implications, applications can take advantage of these new platform version 5 features even if the Corda 4.3 is running on a network whose minimum platform version is 4."

2019-11-17 09:04 UTC, edward-prosser submitted a review, later dismissed

2019-11-18 09:24 UTC, fenryka requested changes

2019-11-18 09:24 UTC, fenryka commented on docs/source/release-notes.rst
> +As some API calls were added to Corda to support Accounts, the platform version of Corda 4.3 needed to be changed from 4 to 5. This allows CorDapps that use Accounts to set their minimum platform ver
I must admit this is somewhat confusing to read, maybe a table / matrix of what will and won’t work would be a bit clearer

Additionally, I would phrase the start slightly differently.

“Given the addition of a new API to support the Accounts feature, the platform version of 4.3 has been bumped up to 5. As per our spec this is to prevent apps that utilise it being deployed onto nodes unable to host them.”

The current phrasing is a bit too matter of fact

2019-11-18 10:08 UTC, fenryka requested changes
just one more thing I think and it's good

2019-11-18 10:08 UTC, fenryka commented on docs/source/release-notes.rst
> +Given the addition of a new API to support the Accounts feature, the platform version of Corda 4.3 has been bumped up from 4 to 5. This is to prevent CorDapps that use it being deployed onto nodes un
My only remaining comment is can we make it clearer that v5 apps *will* run on a mpv 4 zone, perhaps as a ..important style thing

2019-11-18 12:16 UTC, fenryka approved these changes
LGTM

2019-11-18 12:42 UTC, merged