[CORDA-3442] Update app upgrade notes for gradle version for PV5
corda/corda pull request #5740
Opened 2019-11-19 14:18 UTC by JamesHR3

This PR updates the app upgrade notes to indicate that the gradle version has changed, and that an additional repository must be added to the gradle file to pick up the gradle-api-tooling dependency.

2019-11-19 15:45 UTC, anthonykeenan requested changes
Couple of minor things

2019-11-19 15:45 UTC, anthonykeenan commented on docs/source/app-upgrade-notes.rst
> +        ./gradlew wrapper --gradle-version 5.4.1
Oooh I didn't know you could do that I've just been editing it manually.

2019-11-19 15:45 UTC, anthonykeenan commented on docs/source/app-upgrade-notes.rst
> +gradle-api-tooling dependency. You can do this by adding the following to the repositories in your Gradle file:
I think gradle-api-tooling needs backticks

2019-11-19 15:45 UTC, anthonykeenan commented on docs/source/app-upgrade-notes.rst
> +   numbers in your Gradle file as shown in this section. See `Step 2. Update Gradle version and associated dependencies`_
Have you build the docs and checked whether that link actually works? I thought you had to do something funny with a `::ref` link

2019-11-19 16:38 UTC, JamesHR3 commented on docs/source/app-upgrade-notes.rst
> +        ./gradlew wrapper --gradle-version 5.4.1
We suggest doing the same thing in the 4.1 upgrade notes :)

2019-11-19 16:39 UTC, JamesHR3 commented on docs/source/app-upgrade-notes.rst
> +   numbers in your Gradle file as shown in this section. See `Step 2. Update Gradle version and associated dependencies`_
I had built locally and this did work for me (and is part of the rst spec as far as I can tell), however we consistently don't do this elsewhere, so I've switched to an explicit `:ref:` to match everywhere else in the docs.

2019-11-21 11:52 UTC, anthonykeenan approved these changes

2019-11-21 11:52 UTC, merged