CORDA-3202 Add a specific exception for flows to hospitalise themselves
corda/corda pull request #5767
Opened 2019-11-27 23:11 UTC by kyriathar

Introducing a new type of exception, which, whenever thrown by a flow, leads to the flow being sent to the hospital immediately for overnight observation.

This new exception is being handled by a newly introduced staff of the StaffedFlowHospital.

2019-11-28 10:22 UTC, lankydan requested changes

2019-11-28 10:22 UTC, lankydan commented on core/src/main/kotlin/net/corda/core/flows/FlowException.kt
> +class PauseFlowException(message: String, cause: Throwable?) : CordaRuntimeException(message, cause) {
It isn't really pausing the flow, instead it is hospitalising/rescheduling/retrying the flow.

Maybe a name like `RescheduleFlowException` or `HospitalizeFlowException` would be a better name.

Since this will become public api we need to get the naming right.

2019-11-28 10:22 UTC, lankydan commented on node/src/main/kotlin/net/corda/node/services/statemachine/StaffedFlowHospital.kt
> +            return if (newError is PauseFlowException) {
I think using `mentionsThrowable` would be safer here.

2019-11-28 10:22 UTC, lankydan commented on core/src/main/kotlin/net/corda/core/flows/FlowException.kt
> + */
I think it might be worth moving this exception to its own file. Both `FlowException` and `UnexpectedFlowEndException` propagate to counterparties. This exception will not.

2019-11-28 10:22 UTC, lankydan commented on core/src/main/kotlin/net/corda/core/flows/FlowException.kt
> +class PauseFlowException(message: String, cause: Throwable?) : CordaRuntimeException(message, cause) {
Make `message` nullable and define secondary constructors as `FlowException` does. Will make using it easier in kotlin and java.

2019-11-28 10:22 UTC, lankydan commented on core/src/main/kotlin/net/corda/core/flows/FlowException.kt
> +class PauseFlowException(message: String, cause: Throwable?) : CordaRuntimeException(message, cause) {
Make it an `open` class so it can be extended. This means users can either wrap their exceptions with this exception or create a new one and extend the exception.

Write tests for both of these cases.

2019-11-28 11:08 UTC, kyriathar commented on core/src/main/kotlin/net/corda/core/flows/FlowException.kt
> +class PauseFlowException(message: String, cause: Throwable?) : CordaRuntimeException(message, cause) {
Let's go with "HospitalizeFlowException". I think it sounds a little bit more direct of the initial intention of throwing it.

2019-11-28 15:16 UTC, lankydan commented on core/src/main/kotlin/net/corda/core/flows/HospitalizeFlowException.kt
> + * Thrown when the user needs to pause a flow. It will send the flow throwing it directly to the hospital.
Change this kdoc to say that it sends the flow to the hospital to be retried at a later time (basically remove the mention of _pause_). Maybe also indicate that other rules in the hospital might take precedence over this exception.

2019-11-28 15:17 UTC, lankydan commented on node/src/main/kotlin/net/corda/node/services/statemachine/StaffedFlowHospital.kt
> +     * Pauses a flow, hospitalizing it immediately, upon throwing a [HospitalizeFlowException].
Same as other comment, say "keeps flow in for observation if [HospitalizeFlowException] is received.

2019-12-05 16:16 UTC, lankydan reviewed
Mainly doc improvements needed.

2019-12-05 16:16 UTC, lankydan commented on node/src/integration-test/kotlin/net/corda/node/services/statemachine/FlowHospitalTest.kt
> +        driver(DriverParameters(startNodesInProcess = true,
Format the code you added

2019-12-05 16:16 UTC, lankydan commented on node/src/integration-test/kotlin/net/corda/node/services/statemachine/FlowHospitalTest.kt
> +            // Create an instance out of the Class reference and TODO check if it is or has a HospitalizeFlowException.
Remove this comment

2019-12-05 16:16 UTC, lankydan commented on docs/source/api-flows.rst
> +                    throw HospitalizeFlowException("The resource requested could not be found!") // throw a HospitalizeFlowException arbitrarily.
Remove this `if` statement

2019-12-05 16:16 UTC, lankydan commented on docs/source/api-flows.rst
> +                // We can achieve this by wrapping the thrown exception with a HospitalizeFlowException and throw it instead.
Remove ` // We can achieve this by wrapping the thrown exception with a HospitalizeFlowException and throw it instead.`

2019-12-05 16:16 UTC, lankydan commented on docs/source/node-flow-hospital.rst
> +
Is the following description better?

```rst
* ``HospitalizeFlowException``:
     The aim of this exception is to provide user code to a way to replay a flow from its last checkpoint if a known intermittent failure occurred.
     Any ``HospitalizeFlowException`` that is thrown and not handled by any of the scenarios detailed above, will be kept in for observation.
```

Also, move the mention of **Internal Corda errors** to be the last point in the list.

2019-12-05 16:16 UTC, lankydan commented on docs/source/api-flows.rst
> +Here is an example of a flow that we might have wanted to be retried again in the future instead of terminating erroneously:
I think this can all be simplified:

```rst
Some operations can fail intermittently and will succeed if they are tried again at a later time. Flows have the ability to halt their
execution in such situations. By throwing a ``HospitalizeFlowException``, a flow will stop and replay at a later time (such as node restart).

.. note:: If the cause of a ``HospitalizeFlowException`` is explicitly handled by Corda, the outcome of a flow may change. For example, the flow
  could instantly retry or terminate if a critical error occurred.

A ``HospitalizeFlowException`` can be defined in various ways:

.. container:: codeset

    .. literalinclude:: ../../core/src/main/kotlin/net/corda/core/flows/HospitalizeFlowException.kt
        :language: kotlin
        :start-after: DOCSTART 1
        :end-before: DOCEND 1

.. note:: HospitalizeFlowException can be extended for customized exceptions. These exceptions will be treated in the same way when thrown.

Below is an example of a flow that should retry again in the future if an error occurs:
```

2019-12-05 16:16 UTC, lankydan commented on docs/source/api-flows.rst
> +.. note:: Custom exceptions extending HospitalizeFlowException will be treated the same way when thrown.
Remove this note, as it makes more sense being further up. (I have included it in my big suggestion above).

2019-12-06 16:38 UTC, lankydan commented on docs/source/api-flows.rst
> +Below is an example of a flow couple making use of ``FlowException``:
Below is an example using ``FlowException``:

2019-12-06 16:58 UTC, lankydan approved these changes
👍

2019-12-10 12:03 UTC, rick-r3 requested changes
Happy to discuss.  You might have been through the thought process already and thought why we shouldn't do what I suggest.

2019-12-10 12:03 UTC, rick-r3 commented on docs/source/api-flows.rst
> +.. note:: If a ``HospitalizeFlowException`` is wrapping or extending an exception already being handled by the :doc:`node-flow-hospital`, the outcome of a flow may change. For example, the flow
I'm not convinced we should make the situation so complicated with fallbacks etc.  The idea is to use this to raise things up to the hospital.  If we then go ahead and add new rules to the hospital, stuff might stop being held for observation when it should be etc.  i.e. chance of accidentally breaking someones app in the future is perhaps increased.

I'd rather we just had one exception to force the flow into "Kept in for Observation", with no conditionality.  I also think we should force the presence of the `message` field, so it can be displayed in a hospital GUI.

2019-12-10 12:03 UTC, rick-r3 commented on docs/source/api-flows.rst
> +                } catch (e: UnknownHostException) {
We should comment on how it is acceptable to catch very specific exceptions, but broadly catching exceptions is discouraged as it will interfere with the normal hospital handling.  Another example might be a data validation failure, rather than catching an exception and wrapping before re-throwing.

2019-12-11 10:35 UTC, rick-r3 approved these changes
Okay.  Changed my mind.

2019-12-11 10:35 UTC, merged