Jenkins file for nightly regression tests
corda/corda pull request #5786
Opened 2019-12-05 09:06 UTC by relyafi

New Jenkins file for running "nightly" regression tests, intended for feature branches. Key differences from the vanilla "regression" Jenkinsfile:

- Trigger to poll GitHub nightly is included in the Jenkinsfile, which takes effect after the first build happens in Jenkins (which must be triggered via other means)
- Option to override the Jenkins server organisation level triggers specified, so these no longer trigger after the Jenkinsfile is loaded

2019-12-05 12:59 UTC, wzur-r3 submitted a review, later dismissed

2019-12-06 15:47 UTC, roastario requested changes

2019-12-06 15:47 UTC, roastario commented on .ci/dev/nightly-regression/Jenkinsfile
> +    agent { label 'gke' }
the gke label will force the builds to occur on the Google Kubernetes Engine. 

This cluster is limited to maximum of 20 nodes. I would set the label to k8s for use with the azure cluster.

2019-12-09 14:36 UTC, r3domfox approved these changes
LGTM

2019-12-17 13:00 UTC, r3domfox approved these changes
LGTM

2019-12-17 13:02 UTC, merged