Fix empty IN statements in vault queries for MS SQL Server
corda/corda pull request #5787
Opened 2019-12-05 13:06 UTC by taavi-kala-gt

From Insurwave fork of the Open Source 4.1

Courtesy of @marko-mets-gt (bug fix) and me (test)

2019-12-10 15:33 UTC, fowlerrr requested changes
`detekt` doesn't like the change because it's too 'complex' a method now.  I played about and it's probably worth refactoring the string handling to another method, eg:

```
    private fun stringCollectionComparisonToPredicate(
            columnPredicate: CollectionExpression<*>,
            column: Path<String?>,
            literal: Collection<String>
    ): Predicate {
        return when (columnPredicate.operator) {
            IN -> column.`in`(literal)
            IN_IGNORE_CASE -> criteriaBuilder.upper(column).`in`(literal.map { it.toUpperCase() })
            NOT_IN -> criteriaBuilder.not(column.`in`(literal))
            NOT_IN_IGNORE_CASE -> criteriaBuilder.not(criteriaBuilder.upper(column).`in`(literal.map { it.toUpperCase() }))
        }
    }

    private fun collectionComparisonToPredicate(column: Path<out Any?>, columnPredicate: CollectionExpression<*>): Predicate {
        val literal = if (columnPredicate.rightLiteral.isEmpty()) {
            // This is needed because MS SQL does not allow writing IN statement with empty list, e.g this is invalid: "select 1 where 'a' in ()"
            // To fix it we just insert a null into the list and the query becomes: "select 1 where 'a' in (null)"
            listOf(null)
        } else {
            columnPredicate.rightLiteral
        }
        return if (literal.any { it is String }) {
            @Suppress("UNCHECKED_CAST")
            stringCollectionComparisonToPredicate(columnPredicate, column as Path<String?>, literal as Collection<String>)
        } else {
            when (columnPredicate.operator) {
                IN, IN_IGNORE_CASE -> column.`in`(literal)
                NOT_IN, NOT_IN_IGNORE_CASE -> criteriaBuilder.not(column.`in`(literal))
            }
        }
    }
```

2019-12-10 15:33 UTC, fowlerrr commented on node/src/main/kotlin/net/corda/node/services/vault/HibernateQueryCriteriaParser.kt
> +            // This is needed because MS SQL does not allow writing IN statement with empty list, e.g this is invalid: "select 1 where 'a' in ()"
`detekt` is failing because this line is too long.  Can you make it less than 140 characters?

2019-12-10 15:37 UTC, fowlerrr commented
The code change itself looks innocuous?  Has it been tested against other DBs to make sure they haven't broken?

2020-01-13 11:30 UTC, marko-mets-gt commented
It has been tested only on H2 and MSSQL.

2022-02-08 16:23 UTC, nargas-ritu commented
Internal backlog ticket [CORDA-4199](https://r3-cev.atlassian.net/browse/CORDA-4199)

2022-06-13 09:06 UTC, marcellofarina75 commented
Hello [taavi-kala-gt](https://github.com/taavi-kala-gt),
thank you for your contribution to Corda!

Our engineers reviewed your Pull Request and established that, while your proposal would definitely improve Corda, the work needed to merge it (in terms of unit, integration and regression tests, documentation updates, security assessments, and ongoing maintenance) would prevent us from shipping features and fixes that are prioritised higher in our roadmap (which is driven directly from inputs from across the user base).

So this means we regretfully need to let you know that your PR will be declined.

Please feel free to contact [devrel@r3.com](mailto:devrel@r3.com) if you need any further information

2022-06-13 09:06 UTC, closed without merging