ENT-4652: Do not register cordapp custom serialisers when using attachment classloader.
corda/corda pull request #5788
Opened 2019-12-05 13:12 UTC by chrisr3

The CorDapp custom serialisers are only applicable when also deserialising with their corresponding classloader. Skip registering these custom serialisers when using a different classloader.

2019-12-11 17:36 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/transactions/SignedTransaction.kt
> +            retryVerification(e, e, ltx, services)
Should this stuff recurse in case there is more than one missing attachment / JAR or one of each?  i.e. verification re-enters this method, with the list of attachments building up as they go.  I guess the list could default to empty in the signature for existing callers.

2019-12-11 17:36 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/transactions/SignedTransaction.kt
> +        (services.transactionVerifierService as TransactionVerifierServiceInternal)
Recurse into `verifyRegularTransaction` ?

2019-12-11 17:36 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/transactions/SignedTransaction.kt
>          (services.transactionVerifierService as TransactionVerifierServiceInternal).verify(ltx, listOf(attachment)).getOrThrow()
Recurse ?

2019-12-11 20:09 UTC, chrisr3 commented on core/src/main/kotlin/net/corda/core/transactions/SignedTransaction.kt
> +            retryVerification(e, e, ltx, services)
Hmm, I've just replicated the logic of the existing `verifyWithExtraDependency()` function here. Doesn't this recurse already?

2019-12-12 10:52 UTC, tudor-malene requested changes
There's one piece of the puzzle there's missing.
Currently we have this fallback mechanism for dependencies both in the transaction builder and in verify.

It would be interesting to find out what would happen during normal transaction building in your scenario.
I would guess your exception would get thrown. 
The question is: do we leave it like this OR we attempt the fallback?

I would tend to the former if the exception is explicit enough, and this can be fixed at dev time.
But would be good to know what happens

2019-12-12 10:52 UTC, tudor-malene commented on serialization/src/main/kotlin/net/corda/serialization/internal/amqp/AMQPSerializationScheme.kt
> +            val isEnabled = customSerializer::class.java.classLoader == context.deserializationClassLoader
Nitpick: Is this the best name for this?
I think some comments would be good here to describe why we need to do this

2019-12-12 10:52 UTC, tudor-malene commented on serialization/src/main/kotlin/net/corda/serialization/internal/amqp/AMQPSerializationScheme.kt
> +            val isEnabled = customSerializer::class.java.classLoader == context.deserializationClassLoader
Also, I'm not sure I understand why this still needs to be registered with the flag?
Why not register it at all?

2019-12-12 11:20 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/transactions/SignedTransaction.kt
> +            retryVerification(e, e, ltx, services)
Yeah, I'm questioning the existing logic too.  I'm not aware that it does recurse. I can't see how it ends up back in this `verifyRegularTransaction`, but maybe I'm looking at it wrong.

2019-12-12 11:21 UTC, chrisr3 commented on serialization/src/main/kotlin/net/corda/serialization/internal/amqp/AMQPSerializationScheme.kt
> +            val isEnabled = customSerializer::class.java.classLoader == context.deserializationClassLoader
The `CorDappCustomSerializer` knows which `SerializationCustomSerializer` class should be associated with the given type descriptor, and also which CorDapp JAR this serializer lives in.

_This is precisely what I need to know when catching the `NotSerializableException` inside `SignedTransaction.verifyRegularTransaction()`!_

The idea here is that we learn at registration time which type descriptors will cause problems and then record the information we will need to recover. I am also assuming that this recovery mechanism will **not** normally be required.

2019-12-12 11:36 UTC, chrisr3 commented
Does `TransactionBuilder` use `AttachmentsClassLoader`? Because the problem here is that classes in `AttachmentsClassLoader` are assignment-incompatible with the same classes from `JarScanningCordappLoader`.

2019-12-12 13:15 UTC, tudor-malene commented on core/src/main/kotlin/net/corda/core/transactions/SignedTransaction.kt
> +            retryVerification(e, e, ltx, services)
it can recurse if there are multiple missing attachments.

2019-12-12 13:19 UTC, tudor-malene commented on serialization/src/main/kotlin/net/corda/serialization/internal/amqp/AMQPSerializationScheme.kt
> +            val isEnabled = customSerializer::class.java.classLoader == context.deserializationClassLoader
Fair enough. 
This was not exactly my mental model for this, but I guess if it works it's fine.
Anyway this should be added as a code comment as it's totally not obvious

2019-12-13 09:44 UTC, tudor-malene submitted a review, later dismissed
LGTM!
Nice work.

The only thing I can mention is that now we have slightly different mechanisms for handling when a dependency contains a serializer from a normal dependency.
I guess this should be documented or some entry in a changelog.

2019-12-13 09:54 UTC, chrisr3 commented
>  The only thing I can mention is that now we have slightly different mechanisms for handling when a dependency contains a serializer from a normal dependency.

Isn't this inevitable though? The serializers are missing because they're almost certainly in the workflows CorDapp and therefore _not_ a normal dependency.

2019-12-13 11:12 UTC, tudor-malene approved these changes
LGTM!

2019-12-13 11:14 UTC, tudor-malene commented
> > The only thing I can mention is that now we have slightly different mechanisms for handling when a dependency contains a serializer from a normal dependency.
> 
> Isn't this inevitable though? The serializers are missing because they're almost certainly in the workflows CorDapp and therefore _not_ a normal dependency. And names of custom **serializer classes** are arbitrary and known only to the serialization layer anyway.

That could be said about any dependency.
Anyway, all this mechanism should be revisited at some point when dependencies are implemented.

2019-12-13 13:46 UTC, chrisr3 commented
I need to rethink this.

2019-12-13 13:46 UTC, closed without merging