ENT-4595 Add git based version
corda/corda pull request #5799
Opened 2019-12-10 14:44 UTC by blsemo

This adds the ability to publish to a git based version based on the command line property `-PversionFromGit`
@lockathan has asked for this to be added to 4.3 and 4.4 to fix some issue with version links as well. This will supersede https://github.com/corda/corda/pull/5798 by a merge from 4.3 to 4.4

2019-12-10 14:46 UTC, lockathan submitted a review, later dismissed
LGTM

2019-12-11 08:23 UTC, lockathan submitted a review, later dismissed
LGTM

2019-12-11 11:56 UTC, chrisr3 reviewed
Does this break IntelliJ native builds, i.e. does it _require_ people now to delegate to Gradle?

IIRC the generated file was checked into the repository for a reason...

2019-12-11 11:56 UTC, chrisr3 commented on build.gradle
> +    ext.corda_release_version = "${ext.baseVersion}".toString()
```gradle
ext.corda_release_version = ext.baseVersion
```

2019-12-11 11:57 UTC, mnesbit commented
I need the Chris to bless this

2019-12-11 11:58 UTC, chrisr3 commented
> I need the Chris to bless this

Hmm, tricky. First fetch me the Wicked Witch of the West's broomstick!

2019-12-11 12:01 UTC, lockathan commented
> Does this break IntelliJ native builds, i.e. does it _require_ people now to delegate to Gradle?
> 
> IIRC the generated file was checked into the repository for a reason...

Christian said that it was automatically generated during the build, but yes, I don't know what effect this would have on IntelliJ. 

He removed the generated file because it had the side effect of hiding problems. With the file in existence, he wasn't aware that something had broken until the TC builds failed. But it worked fine on his own computer. As soon as he deleted the file on his own computer, the build tried to generate it again and failed, causing him to be able to replicate the problem that TC was getting.

So the problem is that TC doesn't actually use what is checked in - it always tries to generate the file again, and if it fails, you get this weird exception saying it could not find the file. This means that Corda builds differently locally vs in TC, which is why he wanted to delete the file.

2019-12-11 12:06 UTC, chrisr3 commented
> He removed the generated file because it had the side effect of hiding problems. With the file in existence, he wasn't aware that something had broken until the TC builds failed. But it worked fine on his own computer. As soon as he deleted the file on his own computer, the build tried to generate it again and failed, causing him to be able to replicate the problem that TC was getting.

TC builds using Gradle, so if the build was working locally for Christian and failing on TC then it sounds like Christian _doesn't_ delegate to Gradle ... :worried:.

2019-12-11 16:11 UTC, chrisr3 requested changes
I think we should keep the comment in the template file.

2019-12-11 16:11 UTC, chrisr3 commented on common/logging/src/main/template/kotlin/net/corda/common/logging/Constants.kt
> + * the generated file does not need to be committed to source control
Can we restore this comment please? Or maybe update it to mention the IntelliJ native build?

2019-12-11 16:54 UTC, chrisr3 approved these changes
LGTM - although @blsemo may pull more of his hair out.

2019-12-11 17:50 UTC, merged