modify CollectSignaturesFlow.kt to allow multiple collections from WellKnown sessions
corda/corda pull request #5800
Opened 2019-12-10 16:44 UTC by roastario

2019-12-11 11:47 UTC, rick-r3 requested changes

2019-12-11 11:47 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/flows/CollectSignaturesFlow.kt
> +        val notWellKnownSessions = sessionsToCollectFrom.filterNot { it.destination is Party }
If we wrote this as `sessionsToCollectFrom.filter { it.destination is AnonymousParty }`, do we need the change to `AbstractParty` ?  We would probably want to check if the number of well known and not well known sessions is equal to the number of input sessions.  If not, there's a `Destination` we do not understand and we than throw an error.

We'll deal with other `Destination` implementations explicitly when they get implemented.

On this basis, I think we could also reword `notWellKnown...` to be `anonymous...`

I think this would also be more correct, as at the moment you assume all `Destination` can be converted to `AbstractParty` and we'll get a casting exception if not.  With this change we will explicitly detect unsupported `Destination` implementations and error with (hopefully) a better message.

2019-12-11 11:47 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/flows/CollectSignaturesFlow.kt
> +            { "There are multiple sessions initiated for Destination ${entry.key.owningKey.toStringShort()}" }
I would make this explicitly `AnonymousParty` rather than `Destination`.  No one will know what you're talking about.

2019-12-11 11:47 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/flows/CollectSignaturesFlow.kt
> +        { " Unable to match key(s): $keysThatDoNotMapToAWellKnownSession to a session to collect signatures from" }
Indent look a bit odd.  What does a reformat do ?

2019-12-11 11:47 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/flows/CollectSignaturesFlow.kt
> +        val wellKnownSessionsToAbstractPartyMap = wellKnownSessions.groupBy { (it.destination as AbstractParty) }
Are these not `abstractPartyToWellKnownSessions` and `abstractPartyToAnonymousSessions` ?  i.e. the naming is the opposite of what the map actually is.

2019-12-11 11:47 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/flows/CollectSignaturesFlow.kt
> +        val wellKnownSessionsToAbstractPartyMap = wellKnownSessions.groupBy { (it.destination as AbstractParty) }
Also, I think certainly with maps like this, it's much easier to follow if the `val` declares the type rather than inferring.

2019-12-11 11:47 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/flows/CollectSignaturesFlow.kt
> +            { "${entry.key} is a required signer, but no session has been passed in for them" }
Weird indent again.  Reformat?

2019-12-11 11:47 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/flows/CollectSignaturesFlow.kt
> +        { "The Initiator of CollectSignaturesFlow must pass in exactly the sessions required to sign the transaction." }
Weird indent again.

2019-12-11 11:51 UTC, rick-r3 commented on constants.properties
> +cordaVersion=4.3.1-SNAPSHOT
Forgot to comment on this.  Need to think about the OS release side of things.  Can you target OS 4.4 for now and then some decision needs to be made about OS 4.3 patch.  Don't want to conflate that with approving the substance of the fix.

2019-12-12 11:25 UTC, roastario commented on core/src/main/kotlin/net/corda/core/flows/CollectSignaturesFlow.kt
> +        { " Unable to match key(s): $keysThatDoNotMapToAWellKnownSession to a session to collect signatures from" }
so this is an edge case in formatting kotlin - I've tried reformatting, it's due to the fact that I've moved the closure outside of the function definition. If I put it back in, it formats as expected, but you get a yellow underline in intellij.

2019-12-12 15:00 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/flows/CollectSignaturesFlow.kt
> +        val wellKnownSessionsToPartyMap: Map<Party, List<FlowSession>> = wellKnownSessions.groupBy { (it.destination as Party) }
The naming of these still seems inverted.  `partyToWellKnownSessions`...  Same below.

2019-12-12 15:00 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/flows/CollectSignaturesFlow.kt
> +
We should assert that the counts/sizes add up to the original number of `sessionsToCollectFrom` counts/sizes.

2019-12-12 15:00 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/flows/CollectSignaturesFlow.kt
> +        val extraNotWellKnownSessions = anonymousSessions.filterNot { (it.destination as AbstractParty).owningKey in unsigned }
Also change this to be filter for `AnonymousParty`

2019-12-12 15:00 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/identity/AbstractParty.kt
> +abstract class AbstractParty(val owningKey: PublicKey): Destination {
Why is this needed?

2019-12-13 11:24 UTC, roastario commented on core/src/main/kotlin/net/corda/core/identity/AbstractParty.kt
> +abstract class AbstractParty(val owningKey: PublicKey): Destination {
so this restores the "original" purpose of this entire feature - which is that as a cordapp developer, I can just put AbstractParty in your state and your code can interact with flow sessions regardless of which underlying type is used.

2019-12-13 11:31 UTC, roastario commented on core/src/main/kotlin/net/corda/core/flows/CollectSignaturesFlow.kt
> +        val wellKnownSessionsToPartyMap: Map<Party, List<FlowSession>> = wellKnownSessions.groupBy { (it.destination as Party) }
yup, sorry I read it as inverted as being Anonymous when it was wellKnown and vice versa - fixing.

2019-12-17 16:23 UTC, rick-r3 commented
I'm happy with this now.

2019-12-17 16:25 UTC, rick-r3 approved these changes

2019-12-17 16:26 UTC, merged

2019-12-18 17:23 UTC, rekalov commented on core/src/main/kotlin/net/corda/core/identity/AbstractParty.kt
> +abstract class AbstractParty(val owningKey: PublicKey): Destination {
Was corresponding opencore version published to artifactory?