CORDA-3329 Exceptions thrown in raw vault observers can cause critical issues
corda/corda pull request #5816
Opened 2019-12-17 11:02 UTC by kyriathar

Observers registered on NodeVaultService#rawUpdates, if they threw an exception when called from FinalityFlow#notariseAndRecord, this led to transactions being notarized but not recorded in in the ledger. The -failed to be recorded locally- transaction and its output states are not visible to any vault, and its input states cannot be consumed by a new transaction, since they are recorded as consumed within the Notary.

Therefore, we need not loose, by any means, the current transaction. To achieve this, we catch all exceptions thrown from serviceHub#recordTransactions, in FinalityFlow#notariseAndRecord, wrapping them with a HospitalizeFlowException throwing it instead. The flow will get to the hospital for observation to be retried from previous checkpoint on next node restart. 

The above fix should only apply to this sole case and not to any other serviceHub#recordTransactions since, if a transaction does not  get notarized the above issue does not occur. The input states are not spent and therefore there is no constraint in initiating a new flow and a new transaction to spend them. On the contrary it would introduce issues in the synchronization among counter flows.

2019-12-17 12:02 UTC, blsemo submitted a review, later dismissed
Generally ok, but the tests need some work to not become candidates for flakiness, and the warning message needs rewording.

2019-12-17 12:02 UTC, blsemo commented on core-tests/src/test/kotlin/net/corda/coretests/flows/FinalityFlowTests.kt
> +        assertFailsWith<TimeoutException> {
Wouldn't it be better to wait for a future you can set in the onFlowKeptForOvernightObservation observer? Thus, the test would not hang for 5 seconds before carrying on.
Also, waiting for a time out exception is potentially flaky. What if something is a bit slow on the build server and the flow genuinely takes longer than 5 seconds?

2019-12-17 12:02 UTC, blsemo commented on core-tests/src/test/kotlin/net/corda/coretests/flows/FinalityFlowTests.kt
> +        assertFailsWith<TimeoutException> {
Same as above. You could also check there what exception you actually got.

2019-12-17 12:02 UTC, blsemo commented on core-tests/src/test/kotlin/net/corda/coretests/flows/FinalityFlowTests.kt
> +            { throw Exception("Error in Observer#onError") }) // register a -throwing Exception- Observer.
What does adding this `onError` handler add to the test case?

2019-12-17 12:02 UTC, blsemo commented on core-tests/src/test/kotlin/net/corda/coretests/flows/FinalityFlowTests.kt
> +        observationCounter = 0
You should at least mention that the throwing observer got unsubscribed when it threw - otherwise, it is completely unclear why it is "fixed" the second time round, at least to the casual reader who does not know the internal quirks of Rx.Observables.

2019-12-17 12:02 UTC, blsemo commented on core/src/main/kotlin/net/corda/core/flows/FinalityFlow.kt
> +
Superfluous blank lines

2019-12-17 12:02 UTC, blsemo commented on core/src/main/kotlin/net/corda/core/flows/FinalityFlow.kt
> +        val notaryCandidate = if (needsNotarySignature(transaction)) {
Why'd you rename `notarised` to `notaryCandidate`? I am not sure that makes it any more readable - also it's not a candidate for notarisation, it is either notarised or not.

2019-12-17 12:02 UTC, blsemo commented on core/src/main/kotlin/net/corda/core/flows/FinalityFlow.kt
> +                    "Caught an Exception for the notarised transaction ${notaryCandidate.id} when trying to record it locally. " +
I think this warning message is genuinely to long - should be a shorter message, and maybe refer to the documentation or similar where the problem is described in more detail.
Also, the wording is not ideal - I would write something like:
`Caught an exception while trying to record notarised transaction ${notaryCandidate.id} locally - the affected states are in an inconsistent state between the node and the notary. Hospitalising the flow.`

2019-12-17 12:02 UTC, blsemo commented on core/src/main/kotlin/net/corda/core/flows/FinalityFlow.kt
> +                            "*** Therefore, we need not loose, by any means, the current transaction (${notaryCandidate.id}) *** " +
You want "lose" here - you can only "loose" an arrow or similar when you shoot it.

2019-12-17 13:02 UTC, kyriathar commented on core-tests/src/test/kotlin/net/corda/coretests/flows/FinalityFlowTests.kt
> +            { throw Exception("Error in Observer#onError") }) // register a -throwing Exception- Observer.
Exception thrown will no longer be OnErrorNotImplementedException , but OnErrorFailedException.

2019-12-17 13:55 UTC, kyriathar commented on core/src/main/kotlin/net/corda/core/flows/FinalityFlow.kt
> +        val notaryCandidate = if (needsNotarySignature(transaction)) {
I mostly did it for cases like `hasNotarySignature(notarised)`. Going back to `notarised`.

2019-12-17 17:35 UTC, rick-r3 requested changes
I don't think this is the correct approach.  We want any failure in `recordTransactions` to be trapped and handled.  `FinalityFlow` is too much of a special case.  I don't think we should necessarily bother with the special case of transactions that don't need notarising, and just treat all the failures the same.

Also, are the outcomes / tests not impacted by https://r3-cev.atlassian.net/browse/CORDA-3381 ?  It seems like maybe all the tests would need re-working if we prevent the unsubscribe ?  If so, maybe we should do that first?

2019-12-19 13:34 UTC, mnesbit commented on node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt
> +                    log.warn(
Why is this only at warn level? Sounds pretty ominous to me!

2020-01-13 18:10 UTC, blsemo reviewed
If I understand the code correctly, scheduling of an error event is replaced by hooking the transaction and making sure that any exception that might have been suppressed is rethrown on commit, relying on the fact that the state machine will commit the transaction and send the flow to the flow hospital if that throws?
I think this would warrant at least a bit of a comment, as following this thought is not at all obvious.

2020-01-13 18:10 UTC, blsemo commented on node/src/main/kotlin/net/corda/node/services/statemachine/StaffedFlowHospital.kt
> +    }
If `atDepth` is not null, there is no point of further recursion, is there? In this case, we look for an exception at a specific depth in the chain, and if that doesn't match, we return false right away.

2020-01-13 18:10 UTC, blsemo commented on node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
> +            }
What do we need the flow state machine for here? Is that just to check that we are inside a flow?

2020-01-13 18:10 UTC, blsemo commented on node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/CordaPersistence.kt
> +            inTopLevelTransaction(isolationLevel, recoverableFailureTolerance, recoverAnyNestedSQLException, statement)
Might be a good idea to explain why top level transactions are treated differently here - my guess is because that call will not be able to suppress the exception anyway?

2020-01-14 09:42 UTC, mnesbit commented
Can we review if there is enough test coverage. I had expected at least a few tests added, or else a change to a test to cover teh new behaviour.

2020-01-14 10:33 UTC, lankydan commented on core/src/main/kotlin/net/corda/core/flows/FinalityFlow.kt
> +        return needsNotarisation && !hasNotarySignature(stx)
I don't think there is any need to change this to `!hasNotarySignature` I think it was clear enough as it was.

2020-01-14 13:25 UTC, lankydan commented on node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/DatabaseTransaction.kt
> +    var logicalTxCorruptedBy: Throwable? = null // TODO: probably not needed to be set in case of SQLException or PersistenceException?
This `TODO` will need to be addressed

2020-01-14 13:25 UTC, lankydan commented on node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/DatabaseTransaction.kt
> +            throw logicalTxCorruptedBy as Throwable
Does this need to be cast to `Throwable`? I thought kotlin should infer this type because of the null check above.

2020-01-14 13:25 UTC, lankydan commented on node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/DatabaseTransaction.kt
> +    // is to be used when a logical transaction/ chain of logical transactions throws certain exceptions within a state machine
Could we expand on this comment?

2020-01-14 13:25 UTC, lankydan commented on node/src/integration-test/kotlin/net/corda/node/services/vault/VaultObserverExceptionTest.kt
> +    fun noneExceptionFromVaultObserverCanBeSuppressedInFlow() {
Rename the test `exceptionFromVaultObserverCannotBeSuppressedInFlow`

2020-01-14 13:25 UTC, lankydan commented on node/src/integration-test/kotlin/net/corda/node/services/vault/VaultObserverExceptionTest.kt
> +//    fun `calling AppServiceHub#jdbcSession in observer code breaks transactional - leaves rubbish in the database - retry from checkpoint should find duplicates `() {
Remember to tidy this test up

2020-01-14 15:40 UTC, rick-r3 requested changes

2020-01-14 15:40 UTC, rick-r3 commented on node/src/main/kotlin/net/corda/node/services/statemachine/StaffedFlowHospital.kt
> +    currDepth: Int = 0
Can we just name this `currentDepth` ?

2020-01-14 15:40 UTC, rick-r3 commented on node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt
> +                        is OnErrorNotImplementedException -> "- caused by an exception thrown in a rx.Observer#onNext that was unhandled (the observer has been unsubscribed!) "
in _an_ rx.Observer

(same in the lin below)

2020-01-14 15:40 UTC, rick-r3 commented on testing/cordapps/dbfailure/dbfworkflows/src/main/kotlin/com/r3/dbfailure/workflows/DbListenerService.kt
> +                            log.info("Throw Exception")
Could you add 2 more tests, one for `OnErrorNotImplementedException` and one for `OnErrorFailedException` so we exercise all the code paths (even though they are trivial)?

2020-01-14 15:49 UTC, kyriathar commented on node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/DatabaseTransaction.kt
> +            throw logicalTxCorruptedBy as Throwable
Because it is a mutable property, some other thread could have modified this one to null between != null and throwing it.

2020-01-15 11:42 UTC, kyriathar commented on testing/cordapps/dbfailure/dbfworkflows/src/main/kotlin/com/r3/dbfailure/workflows/DbListenerService.kt
> +                            log.info("Throw Exception")
All the existing tests, throwing an exception in a vault observer, they are failing with a `OnErrorNotImplementedException`. 

Will add test that will fail with `OnErrorFailedException`.

2020-01-16 00:03 UTC, kyriathar commented on node/src/main/kotlin/net/corda/node/services/statemachine/StaffedFlowHospital.kt
> +    currDepth: Int = 0
Flow Hospital is reverted back; depths are removed from `mentionsThrowable` .

2020-01-22 09:59 UTC, lankydan commented on node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/DatabaseTransaction.kt
> +            firstExceptionInDatabaseTransaction = null
Does this work with the `set` function which null checks

2020-01-22 10:03 UTC, lankydan commented on node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/DatabaseTransaction.kt
> +    var firstExceptionInDatabaseTransaction: Throwable? = null
Should this be an `Exception` instead of a `Throwable`? I don't think we ever pass `Error`s to here, so it shouldn't matter too much but might be worth changing.

2020-01-22 10:21 UTC, lankydan commented on testing/cordapps/dbfailure/dbfworkflows/src/main/kotlin/com/r3/dbfailure/workflows/DbListenerService.kt
> +        // make flow executed on a outOfProcess node throw an unrecoverable error the first time only
No need to put this into the companion object

2020-01-23 09:51 UTC, rick-r3 submitted a review, later dismissed
LGTM.  Let's try and get the integration tests to pass.

2020-01-23 10:42 UTC, rick-r3 submitted a review, later dismissed
Approving again after rebase

2020-01-24 18:20 UTC, rick-r3 approved these changes
Approve after rebase

2020-01-24 18:21 UTC, merged