ENT-4652: Provide an "attachment fixup" mechanism to repair broken transactions.
corda/corda pull request #5825
Opened 2019-12-20 11:31 UTC by chrisr3

Older transactions may no longer verify on Corda 4 because custom serializers had been bundled with the workflows CorDapps which had not been included into the attachment storage. Provide an initial "fix-up" mechanism that will allow us to define rules for how to recover from this.

2020-01-03 09:36 UTC, rick-r3 requested changes
I think this is looking really good.  

Definitely need a better term than "fix up".  Can we just use "dependencies" and/or "add dependencies"?

However, one small wrinkle.  I think existing CorDapps on V4 that are using existing random walk to find a missing class implementation will come a cropper as the existing logic has been completely removed, hasn't it?

Is it possible to put in the old fallback when no defined fix up is available?  With lots of extra aggressive warning saying to use the fix up file.  We should gate it behind a minimum platform version such that it is disabled beyond a certain min version, but I think that could be debated and fixed later.

2020-01-03 09:36 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/internal/CordaUtils.kt
> +fun CordappProvider.internalFixupAttachmentIds(attachmentIds: Collection<AttachmentId>): Set<AttachmentId> {
Rather than `fixup`, can we make this sound more _intentional_?  e.g. `dependency`  

And spread that change around wherever we use `fixup`.

2020-01-03 09:36 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/transactions/SignedTransaction.kt
>          // To detect if the transaction was created before Corda 4 we check if the transaction has the NetworkParameters component group.
I think we should consider relaxing this check.  Even in Corda 4, the rules are not bullet proof.  It's perfectly possible to have a contract depend on a dependency of Corda (e.g. Guava), and then at a later date we remove or change the dependency, causing verification failures.  However, this is more secure, so perhaps we can debate the relaxation another time.

2020-01-03 09:36 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/transactions/SignedTransaction.kt
> +                if (underlying is ClassNotFoundException) {
Is there another subtle version of this involving `NoClassDefFoundError` and a missing dependency of a class we are trying to load ?  Not essential for this PR but interested in your thoughts.

2020-01-03 09:36 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
> +        protected val attachments: MutableList<AttachmentId> = arrayListOf(),
Just a type alias, so this is fine.

2020-01-03 09:36 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/transactions/SignedTransaction.kt
> +                if (underlying is ClassNotFoundException) {
Interesting.  It is handled in the `TransactionBuilder`.  Should we be handling here?

2020-01-03 09:36 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
> +        log.warn("Attempting to rebuild transaction with these attachments:{}",
We previously used `warnOnce`.  I think this code path triggers all the time for Tokens SDK.   It might be worth thinking about that.   Need to make sure there's not an infinite number of combinations of the message (e.g. don't mention all attachments, just the substitutions).

Looking at this message, it doesn't mention exclusions.

2020-01-03 09:36 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
> +        log.warn("Attempting to rebuild transaction with these attachments:{}",
We will probably want to (in a future performance tweak), look at somehow recognising when we have a set of attachments that commonly fails and preempt, perhaps.

2020-01-03 09:36 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/transactions/SignedTransaction.kt
> +            log.warn("Transaction {} has missing class: {}", ltx.id, missingClass)
Can we perhaps be a little more consistent with the logging here?  I suspect we should log a reason for failing the `checkReverifyAllowed` in that method, before throwing.  i.e. reverify is not allowed because there are network params and thus is deemed to have been created under version 4.  

We don't log at all in the other `catch` branches.  We probably should, saying there seems to be a missing serializer etc.

2020-01-03 09:36 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/internal/TransactionVerifierServiceInternal.kt
>       * Required for transactions built with Corda 3.x that might miss some dependencies due to a bug in that version.
I reckon we remove this comment line.   This is an internal interface, and there's a chance it becomes inconsistent with `SignedTransaction.checkReverifyAllowed`, plus we also use it in V4 during transaction building.

2020-01-03 09:36 UTC, rick-r3 commented on docs/source/changelog.rst
> +  include any missing custom serializers from other CorDapps within ``AttachmentStorage``.
We should document the capability and file formats etc elsewhere in the docs.

2020-01-03 09:36 UTC, rick-r3 commented on node/src/main/kotlin/net/corda/node/internal/cordapp/CordappProviderImpl.kt
> +        return cordappLoader.appClassLoader.getResources("META-INF/Corda-Fixups").asSequence().flatMapTo(ArrayList()) { fixup ->
Could we add some comments here just to describe the format a little.  It will need a documentation section on it as well, but something in the code would be good here.

2020-01-03 09:36 UTC, rick-r3 commented on node/src/main/kotlin/net/corda/node/internal/cordapp/CordappProviderImpl.kt
> +        return cordappLoader.appClassLoader.getResources("META-INF/Corda-Fixups").asSequence().flatMapTo(ArrayList()) { fixup ->
Did you need the "self" concept ?

2020-01-03 09:36 UTC, rick-r3 commented on samples/simm-valuation-demo/contracts-states/src/main/kotlin/net/corda/vega/contracts/CordappDependencies.kt
> +        val deps = cl.getResource("META-INF/Cordapp-Dependencies") ?: return emptyList()
Is this use of `META-INF/Cordapp-Dependencies` purely for the test ?  The main code base seems to use `META-INF/Corda-Fixups` (I'm suggesting we change that.... but point still holds here).

2020-01-03 14:19 UTC, chrisr3 commented on samples/simm-valuation-demo/contracts-states/src/main/kotlin/net/corda/vega/contracts/CordappDependencies.kt
> +        val deps = cl.getResource("META-INF/Cordapp-Dependencies") ?: return emptyList()
FWIW, I have added a basic _and separate_ "dependencies" mechanism here that is entirely local to the SIMM Valuation sample, because this sample was relying on the previous "missing class" logic to add a dependency on the `Cash` contract for normal operation. This broke its integration test.

i chose _not_ to fix the integration test using the new fix-up mechanism here because my understanding was that fix-ups were for helping you migrate old CorDapps out of a hole, and their use was _not_ intended to become standard practice for new CorDapps. As the log warnings say, you should contact the CorDapp developer, and so I fixed the SIMM Valuation CorDapp _properly_ instead.

The `META-INF/Cordapp-Dependencies` file just contains a list of SHA256 hashes of all CorDapp JARs that were added to the Gradle `cordapp` configuration when the `contract-states` CorDapp was built. These SHA256 are the same as the `AttachmentId`s and so are then added as extra attachments whenever `contract-states` uses `TransactionBuilder`.

Note that `META-INF/Cordapp-Dependencies` has a completely different file format to `META-INF/Corda-Fixups`, the latter consisting of lines like:
```
SHA256-a,SHA256-b,...=>SHA256-1,SHA256-2,...
```
For the life of me, I cannot see how we will guarantee a deterministic outcome if we have multiple `Corda-Fixup` files containing multiple lines like these, which is probably an argument for not allowing `Corda-Fixup` within 10 zillion light-years of `TransactionBuilder`. It should probably be nailed into a box deep in the bowels of `SignedTransaction` and only brought out under exceptional circumstances.

2020-01-03 14:33 UTC, chrisr3 commented on node/src/main/kotlin/net/corda/node/internal/cordapp/CordappProviderImpl.kt
> +        return cordappLoader.appClassLoader.getResources("META-INF/Corda-Fixups").asSequence().flatMapTo(ArrayList()) { fixup ->
I did not implement the "self" concept here, no. It is not required for the current use-case, and I do not believe that other use-cases are sufficiently well defined yet.

2020-01-03 14:39 UTC, chrisr3 commented on core/src/main/kotlin/net/corda/core/internal/CordaUtils.kt
> +fun CordappProvider.internalFixupAttachmentIds(attachmentIds: Collection<AttachmentId>): Set<AttachmentId> {
This is _by no means_ a "dependency" mechanism. A _true_ dependency mechanism would involve only a list of SHA256 `AttachmentId`s that the CorDapp actually depends on, whereas this feels more like battlefield triage.

2020-01-05 14:37 UTC, chrisr3 commented on core/src/main/kotlin/net/corda/core/internal/TransactionVerifierServiceInternal.kt
>       * Required for transactions built with Corda 3.x that might miss some dependencies due to a bug in that version.
+1

2020-01-06 16:15 UTC, chrisr3 commented on core/src/main/kotlin/net/corda/core/transactions/SignedTransaction.kt
> +            log.warn("Transaction {} has missing class: {}", ltx.id, missingClass)
The retryVerification()` method logs a warning if it detects a missing serializer.

2020-01-06 16:24 UTC, chrisr3 commented on core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
> +        log.warn("Attempting to rebuild transaction with these attachments:{}",
Do we still need `warnOnce()` if we're agreed that the fix-up code-path is _not_ for standard use?

2020-01-08 14:06 UTC, rick-r3 commented
Am I correct in thinking that the fallback to the old "rummage around for a something that makes things work" only applies to TransactionBuilder but not verification of pre-V4 transactions (as it did previously)?

For compatibility we would need it for pre-V4 transactions, in case someone is successfully (however briefly) relying on that to verify V3 transactions, currently.  Let's grab @mnesbit and see what he thinks.

2020-01-08 17:02 UTC, chrisr3 commented
> Am I correct in thinking that the fallback to the old "rummage around for a something that makes things work" only applies to TransactionBuilder but not verification of pre-V4 transactions (as it did previously)?

Yes. I have restored the "missing class" mechanism to `SignedTransaction` as a fallback in case the fix-up rules have no effect.

2020-01-09 09:30 UTC, rick-r3 reviewed
I think this looks "good" now.

We should just decide what we are going to document and where.  Is there any page in the docs where the existing rummaging around is documented?

2020-01-09 10:09 UTC, chrisr3 commented
> We should just decide what we are going to document and where. Is there any page in the docs where the existing rummaging around is documented?

In `cordapp-advanced-concepts.rst` there is a section called
> Changes between version 3 and version 4 of Corda

2020-01-09 16:49 UTC, tudor-malene commented
> It says that missing CorDapps will be attached automatically, but doesn't describe precisely how. Perhaps by ✨ "magic" ✨?

_These incomplete transactions need to be considered valid in Corda 4 and beyond though, so the fix we added for this was to look for a trusted attachment in the current node storage that contains the missing code and use that for validation. This fix is in the spirit of the original transaction and is secure because the chosen code must have been vetted and whitelisted first by the node operator._

I think this paragraph describes pretty accurately what the code is doing.

2020-01-09 18:01 UTC, chrisr3 commented
> I think this paragraph describes pretty accurately what the code is doing.

it's a bit "high-level" though: I would never have guessed that it was searching for the highest version of an attachment whose ZIP contains a missing class and adding that attachment into the transaction repeatedly until the `verify()` function passes.

2020-01-14 15:18 UTC, rick-r3 approved these changes

2020-01-14 15:18 UTC, merged