Corda 3513 rpc flow without permission
corda/corda pull request #5828
Opened 2019-12-20 16:31 UTC by fowlerrr

We'll just re-throw the exception so that it can be picked up outside of the reconnecting ops.

2020-01-06 14:25 UTC, dimosr requested changes
Looks good, some minor comments only.

2020-01-06 14:25 UTC, dimosr commented on node/src/integration-test/kotlin/net/corda/node/flows/FlowRetryTest.kt
> +            val nodeBHandle = startNode(providedName = BOB_NAME, rpcUsers = listOf(user)).getOrThrow()
minor: I think we can remove the second node to make the test a bit lighter, since it's not really used by the test. You might have to use a test identity in the flow invocation.

2020-01-06 14:25 UTC, dimosr commented on client/rpc/src/main/kotlin/net/corda/client/rpc/internal/ReconnectingCordaRPCOps.kt
> +                            throw RPCException("User does not have permission to perform operation ${method.name}.  Will not retry.", e)
Given this is expected to surface at the user-level, I'd suggest removing the `Will not retry.` part.

2020-01-06 14:25 UTC, dimosr commented on client/rpc/src/main/kotlin/net/corda/client/rpc/internal/ReconnectingCordaRPCOps.kt
> +        private fun checkIsClosed() {
nit: how about renaming this method to `checkIfClosed`? This name makes it look like as if the closed connection is the happy path.

2020-01-06 16:38 UTC, fowlerrr commented on node/src/integration-test/kotlin/net/corda/node/flows/FlowRetryTest.kt
> +            val nodeBHandle = startNode(providedName = BOB_NAME, rpcUsers = listOf(user)).getOrThrow()
I just found a flow which doesn't need a receiving party

2020-01-07 09:15 UTC, dimosr approved these changes
👌

2020-01-07 11:35 UTC, merged