[CORDA-3436] Allow CorDapps access to node diagnostic information
corda/corda pull request #5834
Opened 2020-01-03 11:41 UTC by JamesHR3

Add the `DiagnosticsService` to `ServiceHub`. This provides an interface that can be used by CorDapps to obtain information about the node the CorDapp is currently running on, including the CorDapps that are currently installed on the node.

2020-01-04 16:10 UTC, gendal commented
Are there any privacy implications to this? _Should_ apps be able to know which other apps are installed? (And does this still work in a putative future where a node is decomposed into multiple cooperating processes?)

2020-01-06 11:13 UTC, anthonykeenan commented
I don't think there are any _new_ privacy implications from this - I'm pretty sure if you wanted to you could get the information we're providing here with some reflective olympics. I think when we introduce CorDapp sandboxing there is a discussion about what you allow the CorDapp to know, and I suspect there will need to be different levels of sandboxing. I've seen CorDapps used for maintainance tasks that need to know about the whole node, as opposed to transactional CorDapps that probably want to have a smaller surface area exposed to them and that should probably be a decision for the node operator on a per-CorDapp basis.

With regards to future nodes with multiple cooperating processes, I imagine there will still be a concept of what CorDapps are available to the node as a whole, even though there may then be a another layer of detail as to what CorDapps are available to each process of the node, so again, I don't think this is an issue there.

2020-01-06 13:22 UTC, gendal commented
ok - thanks... however, I've now read this JIRA: https://r3-cev.atlassian.net/browse/FEAT-55

I think we need to add some REALLY clear docs to this to make sure CorDapp developers NEVER use the version/revision information returned from the call to make functionality/loading decisions... and we should use the opportunity this PR affords to make sure they understand the meaning of Platform Version.    

History is littered with horror stories that arose from apps making decisions based on querying the wrong information (eg all the apps that would have broken when Windows jumped from 3 to 95, etc., absent heroic hacks from the MS engineering team to work around it).

Actually, I wonder if we need to educate our own teams? Presumably we've bumped the platform version for 4.4 from 5 to 6 already (since this is a new API)?  Are there others?

2020-01-07 09:46 UTC, JamesHR3 commented
> ok - thanks... however, I've now read this JIRA: https://r3-cev.atlassian.net/browse/FEAT-55
> 
> I think we need to add some REALLY clear docs to this to make sure CorDapp developers NEVER use the version/revision information returned from the call to make functionality/loading decisions... and we should use the opportunity this PR affords to make sure they understand the meaning of Platform Version.
> 
> History is littered with horror stories that arose from apps making decisions based on querying the wrong information (eg all the apps that would have broken when Windows jumped from 3 to 95, etc., absent heroic hacks from the MS engineering team to work around it).
> 
> Actually, I wonder if we need to educate our own teams? Presumably we've bumped the platform version for 4.4 from 5 to 6 already (since this is a new API)? Are there others?

I thought a bit here about how we could change the API to not reveal this information directly, to prevent this type of misuse. I don't think that's appropriate though, as I'm not sure how we'd do this without becoming opinionated on how diagnostic information is reported by the app. Better I think to provide the data and let them report it as they see fit. I'll put a warning on the diagnostics service that diagnostic information should only be used for that purpose (and add this to the `ServiceHub` API docs). Ultimately this cannot prevent this type of headache - we already have examples of API misuse (such as using the clearly internal `internalVerifiedTransactionsFeed`).

Regarding documentation of platform version, we already do this on our versioning pages in the docs (see https://docs.corda.net/versioning.html) in a way that reasonably explains the concept and how a developer may access it. What extra are we imagining here?

Platform version as a concept I think is relatively well understood within R3, but the surrounding concepts can be very confusing (`minimumPlatformVersion`, `targetPlatformVersion` and when to use them. There's also two `minimumPlatformVersion`s for different things). The number is already bumped in 4.4.

2020-01-07 10:48 UTC, JamesHR3 commented
This needs a bit of tweaking as FEAT-48 is punted.

2020-01-07 13:00 UTC, gendal commented
Thanks James. I guess we should probably update that page to explain the network mPV and how it's different to app mPV?  And maybe add in that table we started at the back end of last year... but could be a different Jira/PR though...    Can you raise a Jira so we don't miss it? Or should I?   As for this PR, yes... as long as there are really scary warning about not relying on those two methods and strongly pointing people to that page you referenced maybe we'll be ok (although I'm still worried :). )

2020-01-07 13:08 UTC, mnesbit commented
My view is this should restrict visible cordapps to ones with the same publisher.

2020-01-07 13:45 UTC, gendal commented
nice compromise!

2020-01-07 13:48 UTC, JamesHR3 commented
I've created https://r3-cev.atlassian.net/browse/CORDA-3518 to cover documentation improvements around versioning. I think providing information about what other CorDapps are currently running (FEAT-48) is a task for another PR, after a little thought has gone into the implications (although Matthew's suggestion sounds appealing).

2020-01-08 15:19 UTC, anthonykeenan requested changes
Just a couple of minor bits

2020-01-08 15:19 UTC, anthonykeenan commented on core/src/main/kotlin/net/corda/core/node/services/diagnostics/NodeVersionInfo.kt
> + * functional decisions.
This isn't right is I don't think, the part of the object can be used, because you can use the platformVersion to make functionality decisions? I'm wondering whether vendor is also valid because you might want to make some functionality decisions based on whether it's open source or enterprise.

2020-01-08 15:19 UTC, anthonykeenan commented on docs/source/api-service-hub.rst
> +      used for diagnostic purposes ONLY
Again, I don't think this applies to the whole service?

2020-01-08 15:26 UTC, anthonykeenan commented
Just wondering whether it is valid to differentiate whether it is an Open Source or Enterprise node to make functionality decisions. If it is, we should probably add an enum with the node type to the data structure (for use in both RPC and within CorDapps). You can get the information from the Vendor but that's a string and we may change that, if people are going to use it, we should at least give them something a bit more robust. Possibly one for @VCAMP ?

2020-01-08 15:33 UTC, JamesHR3 commented
I think we should leave the diagnostics service as a service purely for diagnostics information, and in cases where functional decisions could reasonably be made with the data provide that bit of data elsewhere. Taking the example of `platformVersion`, this is already accessible to a CorDapp via the `myInfo` property on the `ServiceHub`.

The reasoning for this is that it's much more confusing to say "you can use these bits but please don't use these other bits" than just a blanket "anything you get from here is diagnostics only, do not depend on it".

I'd argue that functionality decisions based on whether you're running on OS vs ENT is not something to be encouraged, as it's much harder to guarantee that an app written against OS runs on ENT nodes. In theory the functionality visible to the app should be the same (or at least very similar) on each type of node. (This may not be quite true today, but moving to open core should improve the situation there.)

2020-01-09 11:18 UTC, anthonykeenan approved these changes
Ok @JamesHR3, that makes sense, lets leave it as is

2020-01-09 11:18 UTC, merged