CORDA-3507: Use the config value for connectionRetryInterval
corda/corda pull request #5850
Opened 2020-01-10 15:54 UTC by fowlerrr

Use the config rather than a hardcoded value.  (seeing as it's there and all)

I verified this by running some reconnect tests and ensuring the logs show that we're waiting the appropriate amount of time.

without change (hardcoded retry interval of 1 second):
```
[INFO] 15:41:50,030 [pool-13-thread-1] internal.RPCClient. - Failed Startup took 2058 msec
[INFO] 15:41:51,034 [pool-13-thread-1] internal.ReconnectingCordaRPCOps. - Connecting to: localhost:11744
```

with change (default config retry interval of 5 seconds):
```
[INFO] 15:28:20,043 [pool-13-thread-2] internal.RPCClient. - Failed Startup took 2043 msec
[INFO] 15:28:25,043 [pool-13-thread-2] internal.ReconnectingCordaRPCOps. - Connecting to: localhost:11712
```

2020-01-10 15:55 UTC, fowlerrr commented on node/src/integration-test-slow/kotlin/net/corda/node/services/rpc/RpcReconnectTests.kt
> +            val client = CordaRPCClient(addressesForRpc, configuration = config)
This was just to keep the test speedier as per it's original version.  Seeing as the default will now be 5 seconds.

2020-01-13 10:06 UTC, dimosr requested changes

2020-01-13 10:06 UTC, dimosr commented on client/rpc/src/main/kotlin/net/corda/client/rpc/internal/ReconnectingCordaRPCOps.kt
> +                retryInterval: Duration = rpcConfiguration.connectionRetryInterval,
How about making this a mandatory parameter & passing through the value from the node config at the next level up during invocation? Reason I'd like that a bit more is it would reduce the risk of inadvertently overriding the value with the default without knowing.

2020-01-13 15:17 UTC, dimosr approved these changes

2020-01-14 09:53 UTC, mnesbit commented
Any doc change needed?

2020-01-14 09:57 UTC, merged

2020-01-14 09:58 UTC, fowlerrr commented
Yes, some docs changes are probably relevant.  I'll raise another PR.