[NOTICK] Print out local version
corda/corda pull request #5851
Opened 2020-01-10 17:02 UTC by blsemo

Make gradle output the version string it is about to install  when running install or publishToMavenLocal so it can be used as a local dependency.

2020-01-11 17:28 UTC, chrisr3 requested changes
I'm not sure I understand what you're _really_ aiming for here. Publishing is "per sub-project", and you've only configured the root project (which doesn't have anything to publish)!

2020-01-11 17:28 UTC, chrisr3 commented on build.gradle
> +}
This task will log a message when it is _configured_ (I think). It will also be configured eagerly. Perhaps better:
```gradle
def printLocalVersion = tasks.register('printLocalVersion') { task ->
    task.doLast {
        logger.lifecycle("Publishing local version $corda_release_version")
    }
}
```
This will create a `TaskProvider` rather than a `Task`, and it won't be configured until needed. It will also log only when it is actually executed. But having said that, I suspect you've defined it in the wrong place.

2020-01-11 17:28 UTC, chrisr3 commented on build.gradle
> +
This is the `publishToMavenLocal` task belong to the **top-level** Gradle project, but I don't think this project has anything to publish?!

If you want every sub-project to log a message when it publishes its own artifacts to the local Maven repository then you would need to put something more like this inside the `allprojects {}` block:
```gradle
allprojects {
    ...

    def printLocalVersion = tasks.register('printLocalVersion') { task ->
        task.doLast {
            logger.lifecycle("Publishing local ${project.name} version $corda_release_version")
        }
    }

    tasks.withType(PublishToMavenLocal) { task ->
        task.finalizedBy printLocalVersion
    }

    ...
}
```

2020-01-13 14:05 UTC, blsemo commented
I got rid of all the clever logic to extend the publish local job - just print out the version we are building/testing/potentially publishing on every run. This way, we can e.g. also find it when publishing a preview to artifactory via TC.

2020-01-13 14:05 UTC, chrisr3 approved these changes
That's a _**lot**_ simpler... :wink:

2020-01-14 08:36 UTC, merged