Gradle version 5.4.1 is used in all samples and cordapp templates. Ad…
corda/corda pull request #5855
Opened 2020-01-13 16:31 UTC by JonathanScialpi

Documentation change only: Gradle version 5.4.1 is used in all samples and cordapp templates. Additionally, the link in the docs for 4.10 is actually pointing to gradle 6.0.1

👮🏻👮🏻👮🏻 !!!! DESCRIBE YOUR CHANGES HERE !!!! DO NOT FORGET !!!! 👮🏻👮🏻👮🏻

# PR Checklist:

- [ ] Have you run the unit, integration and smoke tests as described [here](https://docs.corda.net/head/testing.html)?
- [ ] If you added public APIs, did you write the JavaDocs?
- [ ] If the changes are of interest to application developers, have you added them to the [changelog](https://docs.corda.net/head/changelog.html) (`/docs/source/changelog.rst`), and potentially the [release notes](https://docs.corda.net/head/release-notes.html) (`/docs/source/release-notes.rst`)?
- [ ] If you are contributing for the first time, please read the [contributor agreement](https://docs.corda.net/head/contributing.html) now and add a comment to this pull request stating that your PR is in accordance with the [Developer's Certificate of Origin](https://docs.corda.net/head/contributing.html#merging-the-changes-back-into-corda).

Thanks for your code, it's appreciated! :)

2020-01-13 16:31 UTC, JonathanScialpi commented
My PR is in accordance with Developer's Certificate of Origin

2020-01-13 17:17 UTC, rogersanick requested changes

2020-01-13 17:17 UTC, rogersanick commented on docs/source/getting-set-up.rst
> +  Please note: Corda requires Gradle version 5.4.1 at a minimum.
I think it might be helpful to mention when this requirement changed? 

For example 
' Please note: Corda 4.x and greater requires Gradle version...'

2020-01-13 17:17 UTC, rogersanick commented on docs/source/getting-set-up.rst
> +4. Install `Gradle <https://gradle.org/install/>`_. If you are using a supported Corda sample, the included ``gradlew`` script should install Gradle automatically.
I think versioning is important here - should we say 5.4.1+? Can they just download the latest stable version?

2020-01-13 20:13 UTC, chrisr3 commented on docs/source/getting-set-up.rst
> +  Please note: Corda requires Gradle version 5.4.1 at a minimum.
Yes, Corda's _own_ build uses Gradle 5.4.1, but so what? The `getting-set-up` document is about _**CorDapp**_ development, for which you need the [Corda Gradle plugins](https://github.com/corda/corda-gradle-plugins).

As far as these plugins go, our 4.x branch is compatible Gradle 4.9+ and our 5.x branch is ccompatible with Gradle 5.1+. I haven't tried using them with Gradle 6.x yet because JetBrains' own Kotlin 1.2 plugin is incompatible with Gradle 6 :man_facepalming:. (Corda 4.3 _was_ going to be called "Corda 5", and this renumbering has thrown a spanner into our plugins' original versioning scheme, but anyway...).

As for which is the "correct" version of Gradle to use, I would _recommend_ using a version that supports the most recent version of the Corda Gradle plugins. But trhat's a _long_ way short of being a "requirement".

2020-01-15 04:40 UTC, JonathanScialpi commented on docs/source/getting-set-up.rst
> +  Please note: Corda requires Gradle version 5.4.1 at a minimum.
I guess the text just has some confusing parts to it as a client I recently worked with pointed out. He was under the impression that 4.10 was the **only version** that would work but then noticed my machine's Gradle version was 6.0.1 and that each CorDapp downloads its own version of Gradle anyways.

So in summary: 

1. The version to be downloaded.
- Why mention this version at all in the hyperlink text if the CorDapp is going to run the version mentioned in gradle-wrapper.properties anyways?

2. "Corda requires Gradle version 4.10, and does not support any other version of Gradle."
- We know that 4.x supports 4.10 and 5.x supports 5.4.1, so this statement is no longer valid.

I updated my PR to hopefully reduce any confusion by removing the mention of 4.10 in the hyperlink as the version needed to download and also that 4.10 is the only Gradle version supported.

2020-01-15 14:06 UTC, JonathanScialpi commented on docs/source/getting-set-up.rst
> +4. Install `Gradle <https://gradle.org/install/>`_. If you are using a supported Corda sample, the included ``gradlew`` script should install Gradle automatically.
Good point. I updated the PR to reflect what version of Gradle Corda 4.x and 5.x needs

2020-01-15 17:19 UTC, rogersanick commented on docs/source/getting-set-up.rst
> +  Please note: Corda requires Gradle version 5.4.1 at a minimum.
@chrisr3 - I think you're right in flagging that requirement might be the wrong language. I think it still helps to be specific in a `getting-set-up` doc. Do you think we should either:
a) Point the user to a formal list of Corda Gradle Versions mapped to Gradle Versions
or 
b) Just include the 5.x branch info (given were on master anyways)

2020-01-20 00:14 UTC, chrisr3 commented on docs/source/getting-set-up.rst
> +  Please note: Corda requires Gradle version 5.4.1 at a minimum.
> I guess the text just has some confusing parts to it as a client I recently worked with pointed out. He was under the impression that 4.10 was the **only version** that would work but then noticed my machine's Gradle version was 6.0.1 and that each CorDapp downloads its own version of Gradle anyways.

I'm interested in how Gradle 6.0.1 is working out for you, because Gradle's deprecation warnings say this about the Kotlin 1.2.71 plugin:
```
The DefaultSourceDirectorySet constructor has been deprecated. This is scheduled to be removed in Gradle 6.0. Please use the ObjectFactory service to create instances of SourceDirectorySet instead.
        at org.gradle.api.internal.file.DefaultSourceDirectorySet.<init>(DefaultSourceDirectorySet.java:65)
        at org.gradle.api.internal.file.DefaultSourceDirectorySet.<init>(DefaultSourceDirectorySet.java:79)
        at org.gradle.api.internal.file.DefaultSourceDirectorySet.<init>(DefaultSourceDirectorySet.java:85)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.jetbrains.kotlin.gradle.plugin.sources.DefaultKotlinSourceSetKt$createDefaultSourceDirectorySet$1$2.invoke(DefaultKotlinSourceSet.kt:139)
        at org.jetbrains.kotlin.gradle.plugin.sources.DefaultKotlinSourceSetKt$c
```
If you're building your CorDapp using Kotlin 1.3 then you need to be aware that the Corda node will force it to use the Kotlin 1.2 standard libraries at runtime. Or are you building your CorDapp with Java 8 instead?

2020-01-20 00:39 UTC, chrisr3 requested changes
There is no "requirement" to use Gradle 5.4.1, and no Corda 5.x yet either. The `master` branch is about to cut Corda 4.4... :wink:

2020-01-20 00:39 UTC, chrisr3 commented on docs/source/getting-set-up.rst
> +  Please note: Corda 4.x requires Gradle version 4.10 while Corda 5.x requires 5.4.1.
Again, not really true. _CorDapp_ development assumes that you are using our [`net.corda.plugins.cordapp`](https://plugins.gradle.org/plugin/net.corda.plugins.cordapp) Gradle plugin, and you need to use a version of Gradle that is compatible with the version of the `cordapp` plugin that you wish to use.

The question then becomes: "Which version of the `cordapp` plugin will create a CorDapp compatible with Corda X?". And this is trickier to answer because the old model of "Corda N.x needs `cordapp` plugin N.y" was broken when Corda 5.0 was released as Corda 4.3(?) instead.

My personal advice would be to use Gradle 5.6.4 whenever possible, as this is the most recent version of Gradle that I am confident will work with Kotlin 1.2. I see no reason to recommend using Gradle 5.4.1 just because I haven't had a chance to upgrade the Corda builds yet?!

2020-01-21 12:21 UTC, closed without merging