CORDA-3542: Use the config values for reconnecting retry interval and max reconnect attempts
corda/corda pull request #5869
Opened 2020-01-21 14:01 UTC by fowlerrr

What we had before was confusing and, in some cases, incorrect.  This should be clearer, cleaner and hopefully simpler.

The two changes this would bring in are that now the reconnecting rpc will use the exponential back-off (both in that it's now possible and by will be enabled by default) and the config value for max reconnect attempts will be respected (which defaults to infinite as before).

TODO:  Assuming using the config for max retries is acceptable I should also put in a quick test that gives up after a few attempts.

2020-01-21 15:44 UTC, mnesbit commented on client/rpc/src/main/kotlin/net/corda/client/rpc/internal/ReconnectingCordaRPCOps.kt
> +                currentRPCConnection = establishConnectionWithRetry(
Don't people want infinite retries?

2020-01-21 15:55 UTC, fowlerrr commented on client/rpc/src/main/kotlin/net/corda/client/rpc/internal/ReconnectingCordaRPCOps.kt
> +                currentRPCConnection = establishConnectionWithRetry(
I'd assume (!) that they'd want the choice.  Which may or may not be bad to give them.  In this scenario they can still have infinite retries (and do by default).

2020-01-21 15:56 UTC, fowlerrr commented on client/rpc/src/main/kotlin/net/corda/client/rpc/internal/ReconnectingCordaRPCOps.kt
> +                currentRPCConnection = establishConnectionWithRetry(
But my question with that change is "do we want to give them the choice? or is that too much rope?"

2020-01-22 10:02 UTC, dimosr requested changes

2020-01-22 10:02 UTC, dimosr commented on client/rpc/src/main/kotlin/net/corda/client/rpc/internal/RPCClientProxyHandler.kt
> +            throw (RPCException("Cannot connect to server(s).", e))
I think we should keep the old message here, since that's surfaced when using the other mode with the Artemis performing the reconnection.

2020-01-22 10:02 UTC, dimosr commented on client/rpc/src/main/kotlin/net/corda/client/rpc/internal/ReconnectingCordaRPCOps.kt
> +                currentRPCConnection = establishConnectionWithRetry(
I don't think it hurts exposing the option to cap the retries as long as the default is infinite and the docs make it clear.

2020-01-22 10:02 UTC, dimosr commented on docs/source/clientrpc.rst
> +- by default the rpc will continue retrying until the connection is re-established.  See ``CordaRPCClientConfiguration`` for adjusting the number of retries.
some minor comments:
- this does not read very well in conjunction with the initial `This will..`. Some rephrasing would help, e.g. `- continue retrying to establish a new connection by default`.
- It might be worth specifying the exact value to reduce the reader's effort, e.g. `See CordaRPCClientConfiguration.maxReconnectAttempts for ..`

2020-01-22 10:02 UTC, dimosr commented on node/src/integration-test-slow/kotlin/net/corda/node/services/rpc/RpcReconnectTests.kt
> +                    connectionRetryIntervalMultiplier = 1.0
thanks for remembering to do this, this would become quite slow otherwise :)

Might be worth doing the same for `CordaRPCClientReconnectionTest`.

2020-01-22 13:14 UTC, dimosr commented on client/rpc/src/integration-test/kotlin/net/corda/client/rpcreconnect/CordaRPCClientReconnectionTest.kt
> -            val client = CordaRPCClient(node.rpcAddress)
what about the other tests in this class?

2020-01-22 15:08 UTC, dimosr submitted a review, later dismissed

2020-01-24 13:23 UTC, fowlerrr commented on client/rpc/src/integration-test/kotlin/net/corda/client/rpcreconnect/CordaRPCClientReconnectionTest.kt
> +    @Test(timeout = 60_000)
@roastario are there any issues with adding a timeout to this test?  We don't want the rpc to attempt reconnecting forever, but there were strange build issues around junit timeouts.

2020-01-24 15:31 UTC, roastario commented
So, yes there are some fun issues with timeouts. Take a look at https://github.com/corda/corda/pull/5875

I had to modify this test specifically to handle the fact that test methods are executed in different threads as the serialisation rule.

2020-01-28 10:54 UTC, fowlerrr commented
Test Evidence, where it tries twice to connect and gives up (yes, I set the config to 2)

```
[WARN] 10:51:12,570 [Test worker] internal.ReconnectingCordaRPCOps. - Reconnecting to [localhost:15354] due to error: null
[INFO] 10:51:12,570 [Test worker] internal.ReconnectingCordaRPCOps. - Connecting to: localhost:15354
[ERROR] 10:51:14,552 [Thread-0 (ActiveMQ-client-factory-threads-1633091499)] DefaultPromise.rejectedExecution. - Failed to submit a listener notification task. Event loop shut down? [errorCode=4gthfh, moreInformationAt=https://errors.corda.net/OS/4.4-SNAPSHOT/4gthfh]
 java.util.concurrent.RejectedExecutionException: event executor terminated
	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:842) ~[netty-common-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:328) ~[netty-common-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:321) ~[netty-common-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:765) ~[netty-common-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:768) ~[netty-common-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:432) ~[netty-common-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:112) ~[netty-common-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.DefaultChannelPromise.setFailure(DefaultChannelPromise.java:89) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.AbstractChannelHandlerContext.safeExecute(AbstractChannelHandlerContext.java:1010) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:610) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:465) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.DefaultChannelPipeline.close(DefaultChannelPipeline.java:1003) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.AbstractChannel.close(AbstractChannel.java:238) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at org.apache.activemq.artemis.core.remoting.impl.netty.NettyConnection.closeChannel(NettyConnection.java:558) ~[artemis-core-client-2.6.2.jar:2.6.2]
	at org.apache.activemq.artemis.core.remoting.impl.netty.NettyConnection.close(NettyConnection.java:240) ~[artemis-core-client-2.6.2.jar:2.6.2]
	at org.apache.activemq.artemis.core.protocol.core.impl.RemotingConnectionImpl.internalClose(RemotingConnectionImpl.java:417) ~[artemis-core-client-2.6.2.jar:2.6.2]
	at org.apache.activemq.artemis.core.protocol.core.impl.RemotingConnectionImpl.destroy(RemotingConnectionImpl.java:235) ~[artemis-core-client-2.6.2.jar:2.6.2]
	at org.apache.activemq.artemis.core.client.impl.ClientSessionFactoryImpl.failoverOrReconnect(ClientSessionFactoryImpl.java:621) ~[artemis-core-client-2.6.2.jar:2.6.2]
	at org.apache.activemq.artemis.core.client.impl.ClientSessionFactoryImpl.handleConnectionFailure(ClientSessionFactoryImpl.java:508) ~[artemis-core-client-2.6.2.jar:2.6.2]
	at org.apache.activemq.artemis.core.client.impl.ClientSessionFactoryImpl.handleConnectionFailure(ClientSessionFactoryImpl.java:501) ~[artemis-core-client-2.6.2.jar:2.6.2]
	at org.apache.activemq.artemis.core.client.impl.ClientSessionFactoryImpl.connectionException(ClientSessionFactoryImpl.java:372) ~[artemis-core-client-2.6.2.jar:2.6.2]
	at org.apache.activemq.artemis.core.remoting.impl.netty.NettyConnector$Listener$2.run(NettyConnector.java:1073) ~[artemis-core-client-2.6.2.jar:2.6.2]
	at org.apache.activemq.artemis.utils.actors.OrderedExecutor.doTask(OrderedExecutor.java:42) ~[artemis-commons-2.6.2.jar:2.6.2]
	at org.apache.activemq.artemis.utils.actors.OrderedExecutor.doTask(OrderedExecutor.java:31) ~[artemis-commons-2.6.2.jar:2.6.2]
	at org.apache.activemq.artemis.utils.actors.ProcessorBase.executePendingTasks(ProcessorBase.java:66) ~[artemis-commons-2.6.2.jar:2.6.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_231]
	at org.apache.activemq.artemis.utils.ActiveMQThreadFactory$1.run(ActiveMQThreadFactory.java:118) ~[artemis-commons-2.6.2.jar:2.6.2]
[ERROR] 10:51:14,552 [Thread-0 (ActiveMQ-client-factory-threads-1633091499)] internal.RPCClientProxyHandler. - Could not reconnect to the RPC server.
[INFO] 10:51:14,594 [Test worker] internal.RPCClient. - Failed Startup took 2023 msec
[INFO] 10:51:15,602 [Test worker] internal.ReconnectingCordaRPCOps. - Connecting to: localhost:15354
[INFO] 10:51:17,627 [Test worker] internal.RPCClient. - Failed Startup took 2025 msec
[ERROR] 10:51:18,631 [Test worker] internal.DriverDSLImpl. - Driver shutting down because of exception [errorCode=tzkx8c, moreInformationAt=https://errors.corda.net/OS/4.4-SNAPSHOT/tzkx8c]
 net.corda.client.rpc.RPCException: Cannot connect to server(s). Tried with all available servers.
```

Here's the test:

```
    @Test
    fun `RPC connection stops reconnecting after config number of retries`() {
        driver(DriverParameters(cordappsForAllNodes = emptyList())) {
            val address = NetworkHostAndPort("localhost", portAllocator.nextPort())
            val conf = config.copy(maxReconnectAttempts = 2)
            val node = startNode(
                    providedName = CHARLIE_NAME,
                    rpcUsers = listOf(CordaRPCClientTest.rpcUser),
                    customOverrides = mapOf("rpcSettings.address" to address.toString())
            ).getOrThrow()

            val connection = CordaRPCClient(node.rpcAddress, conf).start(rpcUser.username, rpcUser.password, gracefulReconnect)
            node.stop()
            // Spin waiting for the RPC to shutdown
            while (!connection.proxy.isWaitingForShutdown()) {
                sleep(200)
            }
        }
    }
```

2020-01-28 14:34 UTC, dimosr commented on client/rpc/src/integration-test/kotlin/net/corda/client/rpcreconnect/CordaRPCClientReconnectionTest.kt
> +                CordaRPCClient(NetworkHostAndPort("localhost", portAllocator.nextPort()), config)
am I right thinking that this test exercises the previous behaviour, i.e. the first connection and not the reconnection? If so, should we add one more test for the new behaviour?

2020-01-28 14:39 UTC, fowlerrr commented on client/rpc/src/integration-test/kotlin/net/corda/client/rpcreconnect/CordaRPCClientReconnectionTest.kt
> +                CordaRPCClient(NetworkHostAndPort("localhost", portAllocator.nextPort()), config)
I tried to add a test for the new behaviour but, unfortunately, the only way to know this is working is by inspecting the logs and Kotlin doesn't really have a way to snooping the logger (that I could find).

That's why I put the test and results in a comment above.  So at least it's documented somewhere.

2020-01-28 14:39 UTC, fowlerrr commented on client/rpc/src/integration-test/kotlin/net/corda/client/rpcreconnect/CordaRPCClientReconnectionTest.kt
> +                CordaRPCClient(NetworkHostAndPort("localhost", portAllocator.nextPort()), config)
Also, yes, that test exercises the behaviour for the first connection

2020-01-28 14:45 UTC, dimosr commented on client/rpc/src/integration-test/kotlin/net/corda/client/rpcreconnect/CordaRPCClientReconnectionTest.kt
> +                CordaRPCClient(NetworkHostAndPort("localhost", portAllocator.nextPort()), config)
> the only way to know this is working is by inspecting the logs
Can't we verify the behaviour by checking that the re-establishing the connection fails and this surfaces to the client through a failed RPC call, while it would block in the default case until the connection is re-established?

2020-01-28 15:03 UTC, fowlerrr commented on client/rpc/src/integration-test/kotlin/net/corda/client/rpcreconnect/CordaRPCClientReconnectionTest.kt
> +                CordaRPCClient(NetworkHostAndPort("localhost", portAllocator.nextPort()), config)
That's already tested.  What I've fixed here is (a) that we only try <config> number of times and (b) that we take our time to do it.  Neither of those things are exposed to the rpc user

2020-01-28 16:29 UTC, dimosr commented on client/rpc/src/integration-test/kotlin/net/corda/client/rpcreconnect/CordaRPCClientReconnectionTest.kt
> +                CordaRPCClient(NetworkHostAndPort("localhost", portAllocator.nextPort()), config)
hmm, but if I understand correctly, the connection would potentially be re-usable previously, while that's not the case anymore, right? Even if the node comes back up, if the retries for connection re-establishment have been exhausted, the previous connection will not be able to reconnect and will fail all the RPC calls? Or am I missing something?

2020-01-28 20:24 UTC, fowlerrr commented on client/rpc/src/integration-test/kotlin/net/corda/client/rpcreconnect/CordaRPCClientReconnectionTest.kt
> +                CordaRPCClient(NetworkHostAndPort("localhost", portAllocator.nextPort()), config)
No I understand what you mean.  We can definitely check for the exception.  And, actually, if we do that, we can update the exception message to include the number of retries (which means we can check for the config value)

2020-01-29 10:37 UTC, fowlerrr commented on client/rpc/src/integration-test/kotlin/net/corda/client/rpcreconnect/CordaRPCClientReconnectionTest.kt
> +                CordaRPCClient(NetworkHostAndPort("localhost", portAllocator.nextPort()), config)
Okay, I've made the changes after our discussion.  There's a new test which at least checks that we give up eventually and I updated the other exception to include the method name

2020-01-29 12:48 UTC, dimosr approved these changes
👌

2020-01-29 13:08 UTC, merged