ENT-4474 O/S Changes to support bulk backchain fetching
corda/corda pull request #5894
Opened 2020-01-24 15:10 UTC by nickdunstone13

This requirement focuses on improving the time taken to fetch backchain by requesting items in bulk.

These changes are required to open source to handle generating the correct response from O/S at Platform version 6. Also the code is re-used in Enterprise which also will need to handle the correct response with multiple items being returned.

In the event that the resulting message would exceed half the max message size, then only items up to this limit will be returned with a minimum of one item.

Only items that are returned are removed from the permission list. Any item not returned as a result of message size overflow may be safely re-requested.

This change is backwardly compatible with existing single backchain item requests.

These changes have been tested in Enterprise with the following permutations: 4.4->4.3, 4.4->4.3, 4.3->4.4

2020-01-27 09:32 UTC, rick-r3 requested changes

2020-01-27 09:32 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/flows/SendTransactionFlow.kt
> +        val maxTransactionSize = networkMaxMessageSize / 2
This isn't actually max transaction size is it?  It's max payload size, or something like that?

2020-01-27 09:32 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/internal/FetchDataFlow.kt
> +                for (hash in toFetch) {
Hmmm.... there's only one, not much need for a loop. `val hash = toFetch.single()`

2020-01-27 09:32 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/internal/FetchDataFlow.kt
> +                val fetchSet = LinkedHashSet<SecureHash>()
You could modify `loadWhatWeHave` to return a `Set` (that is a `LinkedHashSet`) for `toFetch`.

2020-01-27 09:32 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/flows/SendTransactionFlow.kt
> +            var maxByteCount = maxTransactionSize // Sample once before the loop
Maybe mention "the loop" is the `map` on the hashes (since I managed to not spot that!).

2020-01-27 09:32 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/flows/SendTransactionFlow.kt
> +                    val maybeserialized = MaybeSerializedSignedTransaction(txId, if (multiFetchCountExceeded) { null } else { serialized }, null)
Yeah, I don't understand the need for the `MaybeSerializedSignedTransaction`.  The payload can be nullable to solve the `null` or `SerializedBytes<SignedTransaction>`

2020-01-27 09:32 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/flows/SendTransactionFlow.kt
> +                            multiFetchCountExceeded = true
I guess somewhat unfortunately this continues looping when the response is full.  Is there a way we can stop once we exceed the limit (e.g. a loop with a `break`)?

2020-01-27 09:32 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/flows/SendTransactionFlow.kt
> +                    logger.trace { "Sending: Attachments" }
It's perhaps worth modifying all the `trace` statements to specify what the hashes are in all the places.  That way we could fully understand the flow.

2020-01-27 09:32 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/internal/FetchDataFlow.kt
> +                    logger.trace { "Requested[${reqInd}] = '${req}'" }
Do we want a log line for each of these or just wrap up into a single line?  I would prefer the latter I think.

2020-01-27 09:32 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/internal/FetchDataFlow.kt
> +                } else if (item is MaybeSerializedSignedTransaction) {
There are more types than just these two (`SignedTransaction` and `MaybeSerializedSignedTransaction`).  This class now seems to only support just the two.

2020-01-27 09:32 UTC, rick-r3 commented on node/src/main/kotlin/net/corda/node/services/DbTransactionsResolver.kt
> +    override fun downloadDependencies(multiMode : Boolean) {
I think rather than "multi mode" as a naming convention, I would go with "batched mode" (and adjust various names in the code to follow that).

2020-01-27 10:36 UTC, nickdunstone13 commented on core/src/main/kotlin/net/corda/core/flows/SendTransactionFlow.kt
> +            var maxByteCount = maxTransactionSize // Sample once before the loop
Done

2020-01-27 10:59 UTC, nickdunstone13 commented on core/src/main/kotlin/net/corda/core/flows/SendTransactionFlow.kt
> +                    val maybeserialized = MaybeSerializedSignedTransaction(txId, if (multiFetchCountExceeded) { null } else { serialized }, null)
Is this comments still valid in light of the discussion we had about the same object type being returned as a signed transaction then being sent back?

2020-01-27 11:08 UTC, nickdunstone13 commented on core/src/main/kotlin/net/corda/core/flows/SendTransactionFlow.kt
> +                    logger.trace { "Sending: Attachments" }
Yes done.

2020-01-27 11:12 UTC, nickdunstone13 commented on core/src/main/kotlin/net/corda/core/internal/FetchDataFlow.kt
> +                for (hash in toFetch) {
Done

2020-01-27 11:44 UTC, nickdunstone13 commented on core/src/main/kotlin/net/corda/core/internal/FetchDataFlow.kt
> +                val fetchSet = LinkedHashSet<SecureHash>()
Good improvement. Done.

2020-01-27 11:57 UTC, nickdunstone13 commented on core/src/main/kotlin/net/corda/core/internal/FetchDataFlow.kt
> +                    logger.trace { "Requested[${reqInd}] = '${req}'" }
It's much easier to see one per line when testing especially with index against it. I can change if you really want. It's all wrapped in isTraceEnabled() so should not be too heavy.

2020-01-27 13:12 UTC, nickdunstone13 commented on core/src/main/kotlin/net/corda/core/internal/FetchDataFlow.kt
> +                } else if (item is MaybeSerializedSignedTransaction) {
Fixed

2020-01-27 13:26 UTC, nickdunstone13 commented on node/src/main/kotlin/net/corda/node/services/DbTransactionsResolver.kt
> +    override fun downloadDependencies(multiMode : Boolean) {
Done, consolidated as batch.

2020-01-27 13:52 UTC, nickdunstone13 commented on core/src/main/kotlin/net/corda/core/flows/SendTransactionFlow.kt
> +        val maxTransactionSize = networkMaxMessageSize / 2
I could not see that in Network Parameters but I did rename the variable locally:
val maxPayloadSize = networkMaxMessageSize / 2

2020-01-27 13:55 UTC, nickdunstone13 commented on core/src/main/kotlin/net/corda/core/flows/SendTransactionFlow.kt
> +                            multiFetchCountExceeded = true
Yes, however it is benign in that the logic which fetches from the database will not get called outside of the test "if (!batchFetchCountExceeded) {". The present model is such that enterprise expects to see all hashes with null values. This could be modified but risks making the scope of the change higher and more risky. Given if we keep this model we still need to add the transactions in as null items then there is no real benefit from breaking then adding back in.

2020-01-27 14:58 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/flows/SendTransactionFlow.kt
> +            var maxByteCount = maxPayloadSize // Sample once before the loop
Don't need this, just use `maxPayloadSize`

2020-01-27 14:58 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/internal/FetchDataFlow.kt
> +                        val isSer = item.serialized != null
Encapsulate in `MaybeSerializedSignedTransaction.payloadTypeDescription` or something.

2020-01-27 14:58 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/internal/ServiceHubCoreInternal.kt
> +    fun downloadDependencies(batchMode : Boolean)
No space before `:`

2020-01-27 15:22 UTC, nickdunstone13 commented on core/src/main/kotlin/net/corda/core/flows/SendTransactionFlow.kt
> +            var maxByteCount = maxPayloadSize // Sample once before the loop
Done

2020-01-27 15:39 UTC, nickdunstone13 commented on core/src/main/kotlin/net/corda/core/internal/FetchDataFlow.kt
> +                        val isSer = item.serialized != null
Moved to MaybeSerializedSignedTransaction

2020-01-27 15:46 UTC, nickdunstone13 commented on core/src/main/kotlin/net/corda/core/internal/ServiceHubCoreInternal.kt
> +    fun downloadDependencies(batchMode : Boolean)
Noted.

2020-01-27 17:12 UTC, rick-r3 approved these changes
Fingers crossed it goes green

2020-01-28 09:04 UTC, blsemo approved these changes
Approved based on Rick's previous approval

2020-01-28 09:04 UTC, merged