CORDA-3752: rethrow non-rpc specific errors (for GracefulReconnect)
corda/corda pull request #5922
Opened 2020-02-04 22:46 UTC by fowlerrr

rather than try to reconnect to the server.  It's just confusing to have the rpc try to reconnect for errors which have nothing to do with rpc connection issues.

2020-02-05 10:49 UTC, dimosr requested changes
Looks good, just a minor comment.
Let's also run the smoke tests as a sanity check.

2020-02-05 10:49 UTC, dimosr commented on client/rpc/src/integration-test/kotlin/net/corda/client/rpc/CordaRPCClientTest.kt
> +        }
worth checking the exception type here

2020-02-05 10:49 UTC, dimosr commented
run smoke tests please

2020-02-05 11:14 UTC, fowlerrr commented on client/rpc/src/integration-test/kotlin/net/corda/client/rpc/CordaRPCClientTest.kt
> +        }
I'd originally done that, and almost did again but the exception gets so wrapped up in different layers it doesn't really make much sense (except for the text, which I can parse).  I think that's actually a deficit with `assertThat`, sadly.  Still, I'll pop in a check that the message contains `DuplicateAttachmentException`.

2020-02-05 11:32 UTC, fowlerrr commented on client/rpc/src/integration-test/kotlin/net/corda/client/rpc/CordaRPCClientTest.kt
> +        }
Nope the only thing you can get is `CordaRuntimeException`.  No message and no way I can see to get the wrapped `DuplicateAttachmentException`

2020-02-10 10:50 UTC, dimosr commented on client/rpc/src/main/kotlin/net/corda/client/rpc/internal/ReconnectingCordaRPCOps.kt
> +                            throw e
I think it's better to do here `throw e.targetException`.

2020-02-10 10:53 UTC, dimosr commented on client/rpc/src/integration-test/kotlin/net/corda/client/rpc/CordaRPCClientTest.kt
> +        }
yeah, there are multiple layers introduced due to reflection. If you do the change I suggested in the other comment, the corda runtime exception will be the top-level and you could verify, e.g. in the following way:
```
.isInstanceOf(CordaRuntimeException::class.java)
.hasMessageContaining(DuplicateAttachmentException::class.java.name)
```
Arguably, the `DuplicateAttachmentException` should also be the cause, but I noticed it's not for some reason. Let's not change this now though, because people might have based logic on the current behaviour.

2020-02-11 14:56 UTC, fowlerrr commented on client/rpc/src/integration-test/kotlin/net/corda/client/rpc/CordaRPCClientTest.kt
> +        }
Done

2020-02-11 14:57 UTC, fowlerrr commented
run tests: smoke

2020-02-11 15:09 UTC, dimosr submitted a review, later dismissed

2020-02-11 16:22 UTC, roastario commented
run tests: smoke

2020-02-12 11:36 UTC, dimosr approved these changes

2020-02-13 14:08 UTC, merged