CORDA-3484: Now cope with 2 contract jars with same hash but different name
corda/corda pull request #5952
Opened 2020-02-12 16:33 UTC by adelel1

We can now cope with 2 contract jars with the same hash, but different file names. As the files are the same we just pick one and use that one.

The issue was in CordappProviderImpl. This class maintains two collections, a list of cordapps and a map of hash to cordapp url. The list of cordapps contained all the jars, including the duplicates, while the map as its keyed on file hash would resolve the duplicate hashes into a single entry and its value would be the last cordapp jar url seen.

I've simplified the code by removing the map. All it did was return the hash given a jar file. But the cordapp already maintains its own hash, so this can just be returned after checking it contains contract classes.

Is what I have done OK, I presume the state of the code as it is now is due to historical reasons.

2020-02-12 17:24 UTC, josecoll submitted a review, later dismissed
LGTM!

2020-02-12 17:25 UTC, josecoll reviewed
Do you have the right CORDA JIRA reference in the title?
CORDA-3484 refers to an unrelated EPIC

2020-02-12 17:35 UTC, adelel1 commented
> Do you have the right CORDA JIRA reference in the title?
> CORDA-3484 refers to an unrelated EPIC

Corrected. Should be CORDA-3584

2020-02-13 14:04 UTC, chrisr3 requested changes
Problems with `CordappProviderImplTests`.

2020-02-13 14:04 UTC, chrisr3 commented on node/src/test/kotlin/net/corda/node/internal/cordapp/CordappProviderImplTests.kt
> +        val contractsJARDuplicate: URL = this::class.java.getResource("/samplecontract-duplicate.jar")
Am I understanding this correctly? You are looking for two (presumably identical) resources called
- `samplecontract.jar`
- `samplecontract-duplicate.jar`

but this PR only adds two jars called
- `contracts.jar`
- `contracts-duplictae.jar`

instead. If this test is supposed to be looking for `samplecontract.jar` then how does it work?

Secondly, If you are testing that two jars are identical but have different file names then why not check in only _one_ jar and then copy it somewhere else? That would protect you against someone updating only one of the jars by accident.

Thirdly, why not generate the `contracts.jar` "on the fly" and check in _no_ jars, c.f. `File.writeFixupRules()` at the bottom of this very test?

2020-02-13 14:58 UTC, adelel1 commented on node/src/test/kotlin/net/corda/node/internal/cordapp/CordappProviderImplTests.kt
> +        val contractsJARDuplicate: URL = this::class.java.getResource("/samplecontract-duplicate.jar")
Your right, I copied the wrong jar. And I could duplicate it programmatically!

2020-02-17 14:05 UTC, adelel1 commented on node/src/test/kotlin/net/corda/node/internal/cordapp/CordappProviderImplTests.kt
> +        val contractsJARDuplicate: URL = this::class.java.getResource("/samplecontract-duplicate.jar")
Contract jars now generated on the fly.

2020-02-17 14:52 UTC, chrisr3 requested changes
What's baffling me about this PR atm is that two binary-identical CorDapps _must_ define overlapping packages. And I thought Corda rejected those already...

2020-02-17 14:52 UTC, chrisr3 commented on node/src/test/kotlin/net/corda/node/internal/cordapp/CordappProviderImplTests.kt
> +            val duplicateJarPath = signedJarPath.parent.resolve("duplicate-" + signedJarPath.fileName)
```kotlin
val duplicateJarPath = signedJarPath.resolveSibling(...)
```

2020-02-17 14:52 UTC, chrisr3 commented on node/src/test/kotlin/net/corda/node/internal/cordapp/CordappProviderImplTests.kt
> +            val actual = provider.getContractAttachmentID(className)
Perhaps easier to leverage Kotlin's null-checking:
```kotlin
val actual = provider.getContractAttachmentID(className) ?: fail("End of World!")

assertEquals(firstId, secondId)
assertEquals(actual, firstId)
```

2020-02-17 14:54 UTC, chrisr3 commented on node/src/main/kotlin/net/corda/node/internal/cordapp/CordappProviderImpl.kt
> -    private val cordappAttachments = HashBiMap.create<SecureHash, URL>()
Remove unused `import` for `HashBiMap`.

2020-02-17 15:57 UTC, chrisr3 commented
I am _really_ confused by this whole PR. I've copied your `@Test` into the current `release/os/4.4` branch, which resuls in the following:
-  `provider.getContractAttachmentID(className)` returns `null`
- I see this warning in the logs:
```
[WARN] 15:50:08,041 [Time-limited test] cordapp.CordappResolver. - The CorDapp (name: duplicate-attachment-MyContract-1-0-signed, file: duplicate-attachment-MyContract-1-0-signed) is installed multiple times on the node. The following files correspond to the exact same content: [attachment-MyContract-1-0-signed]
```
Isn't this already correct?

2020-02-18 14:14 UTC, adelel1 commented
> I am _really_ confused by this whole PR. I've copied your `@Test` into the current `release/os/4.4` branch, which resuls in the following:
> 
> * `provider.getContractAttachmentID(className)` returns `null`
> * This warning in the log:
> 
> ```
> [WARN] 15:50:08,041 [Time-limited test] cordapp.CordappResolver. - The CorDapp (name: duplicate-attachment-MyContract-1-0-signed, file: duplicate-attachment-MyContract-1-0-signed) is installed multiple times on the node. The following files correspond to the exact same content: [attachment-MyContract-1-0-signed]
> ```
> 
> Isn't this already correct? (Well, almost... It _could_ give the correct file name?)

After our discussion I have reverted this change. We now treat 2 jars with the same hash but different file names as an error condition. In this case the node will fail to start. PR description has been updated.

2020-02-18 16:11 UTC, chrisr3 submitted a review, later dismissed
I don't think we need/want to use reflection here.

2020-02-18 16:11 UTC, chrisr3 commented on node/src/test/kotlin/net/corda/node/internal/cordapp/CordappProviderImplTests.kt
> +        CordappResolver::class.members.single { it.name == "clear" }.call(CordappResolver)
_Yikes!_ I don't think we need this because we also generate a `core-tests` artifact. All you need to do is add
```kotlin
fun CordappResolver.resetForTesting() {
    clear()
}
```
to the `CordappResolverTest.kt` file. You'll need the following Gradle changes too:
For Open Source:
```gradle
testCompile project(path: ':core', configuration: 'testArtifacts')
```
Which becomes this on Enterprise because of Open Core:
```gradle
testCompile "net.corda:corda-core:$os_corda_release_version:tests"
```

2020-02-18 16:11 UTC, chrisr3 commented on node/src/test/kotlin/net/corda/node/internal/cordapp/JarScanningCordappLoaderTest.kt
> +    }
Another candidate for `CordappResolver.resetForTesting()`.

2020-02-18 16:53 UTC, adelel1 commented on node/src/test/kotlin/net/corda/node/internal/cordapp/CordappProviderImplTests.kt
> +        CordappResolver::class.members.single { it.name == "clear" }.call(CordappResolver)
Done. Yes, your suggestion is much better.

2020-02-18 16:54 UTC, adelel1 commented on node/src/test/kotlin/net/corda/node/internal/cordapp/JarScanningCordappLoaderTest.kt
> +    }
Done.

2020-02-18 16:58 UTC, chrisr3 commented on node/src/test/kotlin/net/corda/node/internal/cordapp/CordappProviderImplTests.kt
> +            val duplicateJarPath = signedJarPath.parent.resolve("duplicate-" + signedJarPath.fileName)
:grinning:

2020-02-18 18:01 UTC, chrisr3 commented on core/src/main/kotlin/net/corda/core/internal/cordapp/CordappResolver.kt
> +                throw java.lang.IllegalStateException("The CorDapp (name: ${cordapp.info.shortName}, file: ${cordapp.name}) " +
Why `java.lang.IllegalStateException` and not just `IllegalStateException`?

2020-02-19 22:54 UTC, chrisr3 reviewed
Err, `CordappResolver`???

2020-02-19 22:54 UTC, chrisr3 commented on core/src/main/kotlin/net/corda/core/internal/cordapp/CordappResolver.kt
> +    private val insideInMemoryTest: Boolean by InsideInMemoryTestDelegate
I am staring and _staring_ at `CordappResolver` and my insides are turning into jelly. It's like watching a triffid grow.

Why does this class exist? What does it actually _do_?

:fire: Can we burn it? :fire:

2020-02-21 15:24 UTC, tudor-malene submitted a review, later dismissed
LGTM!
Basically this replaces the warning with an ISE.
And also gets rid of the `CordappResolver` singleton which contained logic duplicated in another class.

2020-02-21 15:24 UTC, tudor-malene commented on core/src/main/kotlin/net/corda/core/flows/FinalityFlow.kt
> +                    "FinalityFlow with FlowSessions. (${serviceHub.getAppContext().cordapp.info})")
Interesting.
We had almost the exact same logic in 2 different places

2020-02-21 16:43 UTC, adelel1 commented on core/src/main/kotlin/net/corda/core/internal/cordapp/CordappResolver.kt
> +    private val insideInMemoryTest: Boolean by InsideInMemoryTestDelegate
Burnt. Triffid count is one less!

2020-02-21 16:47 UTC, mnesbit commented on node/src/test/kotlin/net/corda/node/services/vault/NodeVaultServiceTest.kt
> +        services.recordTransactions(StatesToRecord.ONLY_RELEVANT, listOf(createTx(1, megaCorp.party)))
Is this equivalent? Or do we need to do something special to drive version 3 inserts? (Do we need to care about version 3 inserts anyway?)

2020-02-24 10:24 UTC, adelel1 commented on node/src/test/kotlin/net/corda/node/services/vault/NodeVaultServiceTest.kt
> +        services.recordTransactions(StatesToRecord.ONLY_RELEVANT, listOf(createTx(1, megaCorp.party)))
There is nothing calling the CordappResolver (apart from the 2 log statements handled elsewhere) - so yes its equivalent. I have removed the V3 bit from the description as there is nothing V3 specific in this test (now and previously).

2020-02-25 09:49 UTC, mnesbit submitted a review, later dismissed
OK

2020-02-25 09:53 UTC, chrisr3 commented on node/src/main/kotlin/net/corda/node/internal/cordapp/JarScanningCordappLoader.kt
> +        appClassLoader.close()
Why do we need to clear `cordappClasses`? Isn't this entire object about to be garbage-collected? But if we really do then maybe:
```kotlin
appClassLoader.use {
    cordappClasses.clear()
}
```

2020-02-25 10:16 UTC, chrisr3 reviewed
How does
```kotlin
import java.util.*
```
get past DeteKt? Oh well...

2020-02-25 11:03 UTC, adelel1 commented on node/src/main/kotlin/net/corda/node/internal/cordapp/JarScanningCordappLoader.kt
> +        appClassLoader.close()
Ok. I reverted this, to let classes be garbage collected.

2020-02-25 11:17 UTC, mnesbit approved these changes
OK

2020-02-25 11:18 UTC, merged