[EG-65] Improved error reporting on stdout
corda/corda pull request #5962
Opened 2020-02-13 16:23 UTC by woggioni

I modified the `ErrorCodeRewritePolicy` to concatenate all the error messages of the exception's cause chain.
The code will start from the throwable being passed to the logger and concatenate its error message with the one in its cause and proceed recursively until it finds an exception with no cause or it detects a loop (an exception already encountered in the traversal).

This should provide customers with more information about errors without havingg to look at the logs (that should still remain the primary source of information)

Here is an example of a stdout after a faiulure opening a JDBC connection with Postgres before the change
```
[ERROR] 10:41:00+0000 [main] pool.HikariPool. - HikariPool-1 - Exception during pool initialization. [errorCode=7gemva, moreInformationAt=https://errors.corda.net/OS/4.3-SNAPSHOT/7gemva]
[ERROR] 10:41:00+0000 [main] internal.NodeStartupLogging. - Exception during node startup: net.corda.nodeapi.internal.persistence.CouldNotCreateDataSourceException: Could not connect to the database. Please check your JDBC connection URL, or the connectivity to the database. [errorCode=1a3cce8, moreInformationAt=https://errors.corda.net/OS/4.3-SNAPSHOT/1a3cce8]
```
And here is the same situation after this change
```
[ERROR] 15:27:14+0000 [main] pool.HikariPool. - Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections. - Connection refused (Connection refused) [errorCode=7gemva, moreInformationAt=https://errors.corda.net/OS/4.3-SNAPSHOT/7gemva]
[ERROR] 15:27:14+0000 [main] internal.NodeStartupLogging. - Could not connect to the database. Please check your JDBC connection URL, or the connectivity to the database. - Failed to initialize pool: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections. - Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections. - Connection refused (Connection refused) [errorCode=gn3vsm, moreInformationAt=https://errors.corda.net/OS/4.3-SNAPSHOT/gn3vsm]
```

2020-02-13 16:41 UTC, JamesHR3 reviewed
I think this looks reasonable. Is it possible to add a small unit test for this? (I'm aware that testing in common/logging is lacking at the moment) Mostly just to prove that we can't get into a loop.

2020-02-14 11:11 UTC, JamesHR3 requested changes
Really minor comment then I think we're good to go.

2020-02-14 11:11 UTC, JamesHR3 commented on common/logging/src/test/kotlin/net/corda/commmon/logging/WalkExceptionCausedByListTest.kt
> +    @Test
Might want to stick the `timeout=300_000` in this annotation as we're going to start enforcing it at some point soon.

2020-02-14 14:09 UTC, JamesHR3 approved these changes
LGTM!

2020-02-17 11:33 UTC, fenryka approved these changes
LGTM

2020-02-17 11:34 UTC, merged