Corda 3597 Replace old Checkpoint table with new one.
corda/corda pull request #5992
Opened 2020-02-21 14:17 UTC by williamvigorr3

2020-02-24 16:44 UTC, lankydan reviewed
I'll have another run through this.

2020-02-24 16:44 UTC, lankydan commented on node/src/main/kotlin/net/corda/node/services/persistence/DBCheckpointStorage.kt
> +                                   serializedCheckpoint: SerializedBytes<Checkpoint>): DBFlowCheckpoint {
Maybe pass in the serialization context instead of the serialized bytes. This can be a lazy half way house instead of fully tidying up the dependency injection to this class. A.k.a we need the serialization context when creating `DBCheckpointStorage` to fully fix this.

2020-02-24 16:44 UTC, lankydan commented on node/src/main/kotlin/net/corda/node/services/persistence/DBCheckpointStorage.kt
> +                                   serializedCheckpoint: SerializedBytes<Checkpoint>): DBFlowCheckpoint {
Ill create a jira for tidying this up

2020-02-24 16:44 UTC, lankydan commented on node/src/main/kotlin/net/corda/node/services/persistence/DBCheckpointStorage.kt
> +//            @JoinColumn(name = "flow_id", referencedColumnName = "flow_id")
Hopefully we can re-add and use `session.get`

2020-02-24 16:44 UTC, lankydan commented on node/src/main/kotlin/net/corda/node/services/persistence/DBCheckpointStorage.kt
> +            private var id: Long? = null,
Can these id's be set to `0` instead of `null` to generate the sequence number?

2020-02-24 16:44 UTC, lankydan commented on node/src/main/kotlin/net/corda/node/services/persistence/DBCheckpointStorage.kt
> +            @OneToOne(fetch = FetchType.LAZY, cascade = [CascadeType.ALL])
I dont think we want to cascaded the `result` and `exception` fields, since they dont always update. The blob might be fine to cascade.

2020-02-26 09:39 UTC, williamvigorr3 commented on node/src/main/kotlin/net/corda/node/services/persistence/DBCheckpointStorage.kt
> +            private var id: Long? = null,
Yes I have got this working now.

2020-02-26 10:47 UTC, williamvigorr3 commented on node/src/main/kotlin/net/corda/node/services/persistence/DBCheckpointStorage.kt
> +                                   serializedCheckpoint: SerializedBytes<Checkpoint>): DBFlowCheckpoint {
I have done this. Annoyingly there was some metering stuff which means we are now serializing the checkpoint twice (one to measure the size). Do you think we should pull the metering stuff into DBCheckpointStorage (that feels more natural to me)?

2020-03-02 09:47 UTC, roastario requested changes

2020-03-02 09:47 UTC, roastario commented on node/src/main/kotlin/net/corda/node/services/persistence/DBCheckpointStorage.kt
> +        @OneToOne(fetch = FetchType.LAZY, cascade = [CascadeType.ALL], optional = true)
By putting Cascade = ALL, we are forcing hibernate to update all the child tables when persisting this entity. I think this will have a pretty big performance impact. 

I would instead manually persist the child entities.

2020-03-02 09:51 UTC, mnesbit approved these changes
Basically makes sense to me

2020-03-02 10:04 UTC, merged