Adds instructions to try out DJVM on a node
corda/corda pull request #6000
Opened 2020-02-25 17:51 UTC by joeldudleyr3

Also removed forward-looking statements, which should not be in the docs.

2020-02-26 23:38 UTC, chrisr3 requested changes
For all of the hard work involved here, the DJVM is still really in "beta". And it's not a magician either that can make CorDapps deterministic with a wave of a wand. It's actually more of a "nightclub bouncer" that will throw you out of the sandbox if you misbehave!

2020-02-26 23:38 UTC, chrisr3 commented on docs/source/key-concepts-djvm.rst
> +any source of non-determinism, transaction verification will fail.
This is certainly the DJVM's _intention_, but maybe we should be clearer that it is still "beta" software for Corda 4.4 and that we are rolling it out for wider testing. Developers will likely need to "tweak" their CorDapps too because not every class, constructor or method for `corda-core` and `corda-serialization` exists when running inside the sandbox. For the Hackathon, I applied a `deterministic.gradle` script plugin to our `contracts` CorDapp module in order to keep the code honest.
```gradle
apply from: "${rootProject.projectDir}/deterministic.gradle"
```
where I created `deterministic.gradle` as a file in the prject's root directory containing the following:
```gradle
configurations {
    compileClasspath { Configuration c -> deterministic(c) }
}

private final void deterministic(Configuration configuration) {
    if (configuration.state == Configuration.State.UNRESOLVED) {
        // Ensure that this module uses the deterministic Corda artifacts.
        configuration.resolutionStrategy.dependencySubstitution {
            substitute module("$corda_release_group:corda-serialization") with module("$corda_release_group:corda-serialization-deterministic:$corda_release_version")
            substitute module("$corda_release_group:corda-core") with module("$corda_release_group:corda-core-deterministic:$corda_release_version")
        }
    }
}
```

You can also enable the DJVM for DemoBench by clicking the "Deterministic Contract Verification" checkbox when creating the Notary node.

2020-02-27 17:24 UTC, chrisr3 requested changes
Almost there, I think. Or almost ready for RGB anyway...

2020-02-27 17:24 UTC, chrisr3 commented on docs/source/key-concepts-djvm.rst
> +.. warning:: The code in the DJVM module is still a beta release, and has not been integrated with the rest of the platform. It is provided
The DJVM has now been _partially_ integrated with Corda, i.e. contract verification. But DJVM-enabled nodes cannot yet participate in a general Corda network containing nodes without a DJVM. (The plan is for the DJVM sandbox to be an "opt in" feature.)

2020-02-27 17:24 UTC, chrisr3 commented on docs/source/key-concepts-djvm.rst
> +CorDapp developers may need to tweak their CorDapps for use inside the DJVM. This is because not every class, constructor or method defined
"tweak their contract CorDapps". Let's _hammer it home._

2020-02-27 17:24 UTC, chrisr3 commented on docs/source/key-concepts-djvm.rst
> +Uses of classes, constructors or methods not available inside the DJVM in that module will then cause compilation errors.
Urg... Maybe
> Uses of Corda's core or serialization APIs which are unavailable inside the sandbox will then cause compilation errors.

2020-02-27 17:24 UTC, chrisr3 commented on docs/source/key-concepts-djvm.rst
> +This will cause your node to use the DJVM to sandbox every call to ``Contract.verify``. If your transaction contains
Maybe just
> This will cause your node to sandbox every call to ...

I think there were too many "to"s in the previous version :wink:.

2020-02-29 12:50 UTC, chrisr3 commented on docs/source/key-concepts-djvm.rst
> +This will cause your node to sandbox every call to ``Contract.verify``. If your transaction contains any source of non-determinism,
I'm not sure we should say "any" source of non-determinism at this stage. Maybe just "a" source?

2020-02-29 12:50 UTC, chrisr3 reviewed
This is looking good! Just one small thing.

I've been thinking about this over the weekend, and I think we need to tell developers how to _test_ their CorDapps. Compiling against `core-deterministic` and `serialization-deterministic` is a Good First Step, but is hardly sufficient - the only way to _guarantee_ that a contract works in the DJVM is actually to run it inside a node. I've extended `DriverParameters` in `node-driver` to allow some limited testing with "out-of-process" nodes (see the node's integration tests) but that's subtle to set up correctly. There's really no substitute for deploying real nodes with either `cordformation` or DemoBench.

2020-03-09 13:03 UTC, mnesbit commented
Do you mean 4.5? Shouldn't this be on 4.4?

2020-03-09 13:04 UTC, joeldudleyr3 commented
@chrisr3 I explain how to configure the nodes to use the DJVM in the updated docs, either via Demobench or the node.conf (see the `Enabling Use of the DJVM for a Node` section). That's how people can test this. What else do you feel we need to say?

@mnesbit It would apply to both. I thought I was supposed to PR against the latest (4.5) then backport?

2020-03-09 13:06 UTC, mnesbit commented
No we work on oldest branch and merge up these days

2020-03-09 13:07 UTC, mnesbit commented
This is docs so fine for it to be late, but QA won't have it for RC05

2020-03-09 13:39 UTC, joeldudleyr3 commented
Reopened against 4.4 branch as https://github.com/corda/corda/pull/6043.

2020-03-09 13:39 UTC, closed without merging