EG-464 Corda returns incorrect exit code in case if node is started with unknown/missing option
corda/corda pull request #6010
Opened 2020-02-28 14:12 UTC by pnemeth

Use a custom error handler to handle ParseException and ExecutionException and return error code 1

Added RunCordaNodeReturnCodeTests to check error codes for various arguments

2020-02-28 14:21 UTC, JamesHR3 reviewed
This seems reasonable, but I think it's probably worth verifying that for the cases where `verbose` did work before this change (so any of the tools) that we'll still print `Throwable` stack traces if `verbose` is set. Have you done that already?

2020-03-02 09:56 UTC, pnemeth commented
need to fix a bug

2020-03-02 14:30 UTC, pnemeth commented
reopening for review

2020-03-02 14:32 UTC, pnemeth commented
> This seems reasonable, but I think it's probably worth verifying that for the cases where `verbose` did work before this change (so any of the tools) that we'll still print `Throwable` stack traces if `verbose` is set. Have you done that already?

Cheers, retested this after latest commit, and it works fine.

2020-03-02 14:49 UTC, JamesHR3 submitted a review, later dismissed
LGTM!

2020-03-02 15:45 UTC, woggioni commented
it would probably be good to have a unit test that checks that `--verbose` prints the stacktrace while the default is to only print the exception message..

I mean only testing `CordaCliWrapper`, like implementing a simple cli in the unit test with a single command that always throws an exception.

This would set the expected behavior of this class, preventing other people to change it again and also will make it clear that, if that feature doesn't work in any of the implementing cli, it is because that is broken (swallowing and managing exception itself), not this class

2020-03-02 16:32 UTC, pnemeth commented
> it would probably be good to have a unit test that checks that `--verbose` prints the stacktrace while the default is to only print the exception message..
> 
> I mean only testing `CordaCliWrapper`, like implementing a simple cli in the unit test with a single command that always throws an exception.
> 
> This would set the expected behavior of this class, preventing other people to change it again and also will make it clear that, if that feature doesn't work in any of the implementing cli, it is because that is broken (swallowing and managing exception itself), not this class

Cheers Walter, good idea, looking into this.

2020-03-03 14:22 UTC, JamesHR3 requested changes
Couple of really small changes.

How confident are we that the test will continue to pass if e.g. the stack trace of the exception were to change? This could happen if the code in `cliutils` were changed. (From my reading of it I think we're ok, but always worth verifying regexs I think.)

2020-03-03 14:22 UTC, JamesHR3 commented on tools/cliutils/src/main/kotlin/net/corda/cliutils/SampleCordaCliWrapper.kt
> +            description = [ "Root directory containing the node configuration files and CorDapp JARs that will form the test network.",
Can we change this description to better match what the test app does?

2020-03-03 14:22 UTC, JamesHR3 commented on testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/ProcessUtilities.kt
> +
Remove the space here

2020-03-03 14:57 UTC, woggioni commented on tools/cliutils/src/main/kotlin/net/corda/cliutils/SampleCordaCliWrapper.kt
> +package net.corda.cliutils
I believe this file should go in the test folder...

2020-03-03 16:05 UTC, pnemeth commented
> Couple of really small changes.
> 
> How confident are we that the test will continue to pass if e.g. the stack trace of the exception were to change? This could happen if the code in `cliutils` were changed. (From my reading of it I think we're ok, but always worth verifying regexs I think.)

I think the regexp is quite general, but of course if it changes a lot we will have to update the test.

2020-03-04 11:25 UTC, JamesHR3 approved these changes
LGTM

2020-03-05 15:38 UTC, roastario approved these changes

2020-03-05 15:38 UTC, merged