CORDA-3603 Save completed flow information
corda/corda pull request #6034
Opened 2020-03-05 14:21 UTC by williamvigorr3

When a flow is finished do not delete the checkpoint from the checkpoint table instead store the result in the checkpoint table.

2020-03-05 14:41 UTC, lankydan commented on node/src/main/kotlin/net/corda/node/services/statemachine/transitions/TopLevelTransition.kt
> +                                        result = event.returnValue, status = Checkpoint.FlowStatus.COMPLETED),
Can we format these onto new lines 😄

2020-03-05 14:41 UTC, lankydan commented on node/src/test/kotlin/net/corda/node/services/statemachine/FlowFrameworkTests.kt
> +            assertTrue(result is Unit)
Can we have a few tests that store different results?

I think the `Unit` test is good (wouldn't have thought of doing that originally).

Testing what happens with the following results would be good:

- `null` from a nullable result
- `SignedTransaction`
- Any general custom object

2020-03-05 14:41 UTC, lankydan commented on node/src/test/kotlin/net/corda/node/services/statemachine/FlowFrameworkTests.kt
> +    fun `Result is stored in database when the flow finishes`() {
I'm considering if we should make some new test classes for these tests and tests coming in future changes.

Possibly `FlowFinishTest`. We can then have `FlowErrorTest`, `FlowStartTest`, maybe even `FlowKillTest`. I will ask for other's opinions before we do this. Just make changes to this file for now before we make a decision.

2020-03-05 14:41 UTC, lankydan commented on node/src/main/kotlin/net/corda/node/services/statemachine/transitions/TopLevelTransition.kt
> +                                        numberOfSuspends = checkpoint.checkpointState.numberOfSuspends + 1),
I'm curious (I'll need to change the code), since we are no longer deleting the checkpoint, what data is held within the checkpoint's `flowState`? I'll try check this, not that it should matter since the flow is completely finished.

2020-03-05 14:57 UTC, williamvigorr3 commented on node/src/test/kotlin/net/corda/node/services/statemachine/FlowFrameworkTests.kt
> +    fun `Result is stored in database when the flow finishes`() {
I agree that would be a good idea.

2020-03-05 15:02 UTC, lankydan commented on node/src/test/kotlin/net/corda/node/services/statemachine/FlowFrameworkTests.kt
> +            val result = checkpoint.result?.bytes?.deserialize<Any>()
Can we also go and directly access the `DBFlowResult` entity and assert that its values are what we would expect.

2020-03-05 15:04 UTC, lankydan commented on node/src/test/kotlin/net/corda/node/services/statemachine/FlowFrameworkTests.kt
> +            assertTrue(result is Unit)
Actually maybe, we should be doing this in `DBCheckpointStorageTest` since that is where the actual persisting happens...

2020-03-05 15:47 UTC, kyriathar commented on node/src/main/kotlin/net/corda/node/services/statemachine/transitions/TopLevelTransition.kt
> +                                        numberOfSuspends = checkpoint.checkpointState.numberOfSuspends + 1),
Hmmmm, maybe we could remove `flowState` upon executing Action.RemoveFlow.

2020-03-05 15:49 UTC, lankydan commented on node/src/main/kotlin/net/corda/node/services/statemachine/transitions/TopLevelTransition.kt
> +                                        numberOfSuspends = checkpoint.checkpointState.numberOfSuspends + 1),
There is another task to do that separately from this PR

2020-03-06 16:49 UTC, lankydan commented on node/src/main/kotlin/net/corda/node/services/statemachine/transitions/TopLevelTransition.kt
> +                                result = event.returnValue,
We can set the `result` on the checkpoint as we have done here. But we should remove/comment out the saving of the result data in `DBCheckpoint` storage.

I have got a PR approved to manually handle saving the result record. If we rebase this branch once that is merged and then you remove the code that persists the result record then that will work.

So either, don't set the `result` on the `Checkpoint` or removing the result record persisting in `DBCheckpointStorage`. Any preference @rick-r3 ?

2020-03-09 10:40 UTC, kyriathar commented on node/src/main/kotlin/net/corda/node/services/statemachine/transitions/TopLevelTransition.kt
> +                            Action.PersistCheckpoint(context.id, currentState.checkpoint, currentState.isAnyCheckpointPersisted),
I think: `Action.PersistCheckpoint` here seems a bit misleading, because in fact we will remove at least most basic parts of the actual checkpoint (like the fiber's stack). Perhaps we could instead keep the `RemoveCheckpoint` action and change its behaviour instead ? Moreover, If we keep it this way, means that we would also have to go and do some kind of distinction within the DBCheckpointStorage between the different `PersistCheckpoint`s now.

2020-03-09 14:36 UTC, lankydan commented on node/src/main/kotlin/net/corda/node/services/statemachine/transitions/TopLevelTransition.kt
> +                            Action.PersistCheckpoint(context.id, currentState.checkpoint, currentState.isAnyCheckpointPersisted),
I think persist checkpoint is still correct. We can review this when we get onto the task that clears out the flow stack, but that is still the same in my opinion. We update the checkpoint to have no flow stack and call persist.

2020-03-09 15:09 UTC, lankydan requested changes
After talking to @rick-r3 we will do the following:

- Set the result on the `Checkpoint` object
- In `DBCheckpointStorage.updateDBCheckpoint` set the entities result field to `null` in all cases (do not store the result).
- Comment out the line that creates the result entity and leave a comment that this will be added back in the future (do not use TODO or detekt will break 😄)

After this it should still work as you have done it now (only the status is updated).

We will also need to `@Ignore` the tests in `DBCheckpointStorageTest` around storing results.

2020-03-10 15:22 UTC, lankydan submitted a review, later dismissed
Looks good. Two in one day?

2020-03-12 10:31 UTC, rick-r3 approved these changes
LGTM

2020-03-12 10:31 UTC, rick-r3 commented
Feel free to merge @lankydan

2020-03-12 10:34 UTC, williamvigorr3 commented
🍾

2020-03-12 11:45 UTC, merged