[EG-438] Error Reporting Framework
corda/corda pull request #6125
Opened 2020-04-02 16:48 UTC by JamesHR3

This PR introduces the error reporting framework, which is a small piece of code to allow errors to be reported to the logs in a more robust way. It also allows for these errors to be internationalized using resource bundles. Note that in order for an error to be reported, it has to be marked in the code with the `ErrorCode` interface and reported by calling `report` on a logger. This code may be pulled into its own library at some point, and so the code aims to have as few dependencies on other parts of Corda as possible.

Some small changes are made in the Corda code to start the library on node startup, and to introduce a small number of error conditions. This will be improved on in future commits to this feature branch.

A utility is also included for generating error code documentation for hosting on the docs site, using the resource bundles. This is included in `tools/error-page-builder`.

## Testing
- Check that errors are correctly reported in the initially supported locale (English)
- Check that the error page builder generates a valid markdown table using different locales.
- Check the error page builder handles invalid directories and the file to generate already existing

(There's still some testing to do around subcommands of the node.)

2020-04-06 14:50 UTC, fenryka requested changes
Some comments

2020-04-06 14:50 UTC, fenryka commented on common/logging/src/main/kotlin/net/corda/common/logging/errorReporting/CordaErrorContextProvider.kt
> +class CordaErrorContextProvider : ErrorContextProvider {
kdocs

2020-04-06 14:50 UTC, fenryka commented on common/logging/src/main/kotlin/net/corda/common/logging/errorReporting/CordaErrorContextProvider.kt
> +    companion object {
*something* rubs me a bit wrong with these being defined in the code and not at runtime / as part of gradle. Can't really pin down my exact objection, save if these change it means recompiling the code, which isn't really that big of a deal.

2020-04-06 14:50 UTC, fenryka commented on common/logging/src/main/kotlin/net/corda/common/logging/errorReporting/ErrorCode.kt
> +     * Error codes are used to indicate what sort of error occurred. A unique code should be returned for each possible
how are we enforcing that? where is the existing list? how should I work out what the next error code is?

2020-04-06 14:50 UTC, fenryka commented on common/logging/src/main/kotlin/net/corda/common/logging/errorReporting/ErrorCode.kt
> +    val namespace: String
Feels like we might want to make this an enum of something to prevent an explosion of different spellings and contractions and to formally list them somewhere

2020-04-06 14:50 UTC, fenryka commented on common/logging/src/main/kotlin/net/corda/common/logging/errorReporting/ErrorReporterImpl.kt
> +    private fun constructErrorInfoBar(error: ErrorCode) : String {
Whats an InfoBar? short comment might be helpful

2020-04-06 14:50 UTC, fenryka commented on common/logging/src/main/kotlin/net/corda/common/logging/errorReporting/ErrorReporting.kt
> +object ErrorReporting {
rather than a global object feels like this should be some form of factory result so we can change behaviour for tests etc... mostly I hate globals

2020-04-06 14:50 UTC, fenryka commented on common/logging/src/main/kotlin/net/corda/common/logging/errorReporting/ErrorReportingUtils.kt
> +    val reporter = ErrorReporting.getReporter()
could just be a one liner

2020-04-06 14:50 UTC, fenryka commented on common/logging/src/main/kotlin/net/corda/common/logging/errorReporting/ErrorResource.kt
> +                    private val classLoader: ClassLoader? = null) {
I'd pull this into two versoin of the class to avoid the constant switch at runtime and make it a compile time swap

2020-04-06 14:50 UTC, fenryka commented on tools/error-page-builder/src/main/kotlin/net/corda/errorPageBuilder/ErrorPageBuilder.kt
> +class ErrorPageBuilder : CordaCliWrapper("error-page-builder", "Builds the error table for the error codes page") {
Does it make sense to have this as part of Corda, after all it applies to CENM and others so seems strange to live here

2020-04-06 17:01 UTC, mnesbit requested changes
Locale is a VERY big topic, this cannot be introduced without some serious discussions

2020-04-07 15:16 UTC, JamesHR3 commented on tools/error-page-builder/src/main/kotlin/net/corda/errorPageBuilder/ErrorPageBuilder.kt
> +class ErrorPageBuilder : CordaCliWrapper("error-page-builder", "Builds the error table for the error codes page") {
No, eventually all this code should end up outside of Enterprise I imagine. However, the repository for the library side of this effectively doesn't exist yet. This particular tool could be pulled out into r3-tools, but as it depends on the library side there's a bit of setup work to do first. I figured I'd get the code right first and sort out the packaging bit afterwards.

2020-04-08 09:42 UTC, JamesHR3 commented on common/logging/src/main/kotlin/net/corda/common/logging/errorReporting/CordaErrorContextProvider.kt
> +    companion object {
I can understand why this feels a bit questionable as if the address changes suddenly this will direct to the wrong place, and the only way to fix it is to deploy a new version of the software. I'm not sure putting them in gradle changes that though (and they're not really build time constants either). I guess what you'd want is to read them from somewhere at run time, but I'm not sure there's an appropriate mechanism for doing this right now. (It's not config either, for example.) If we think it's enough of a problem, I think what you'd want to do is to put some sort of resource in a Corda node that should not be touched by operators, but can be swapped out by them deploying a new version of it.

2020-04-08 15:34 UTC, JamesHR3 commented on common/logging/src/main/kotlin/net/corda/common/logging/errorReporting/ErrorCode.kt
> +     * Error codes are used to indicate what sort of error occurred. A unique code should be returned for each possible
I've made these enums (as well as the namespacing), but might need a little thought of how we want to organise these.

2020-04-08 15:36 UTC, mnesbit commented on common/logging/src/main/kotlin/net/corda/common/logging/errorReporting/ErrorCode.kt
> +    val namespace: String
If we use enums we must space them out and we should expect these files to end up a source of lots of merge pain

2020-04-20 11:40 UTC, JamesHR3 commented on common/logging/src/main/kotlin/net/corda/common/logging/errorReporting/ErrorCode.kt
> +     * Error codes are used to indicate what sort of error occurred. A unique code should be returned for each possible
Current proposal for organising would be to keep codes separate between OS and ENT (probably by having a separate file for ENT codes). There would have to be a single enum of namespaces, so there would be some merge pain there. I'll probably end up elaborating on that in a follow up PR.

2020-04-20 11:54 UTC, fenryka commented on common/logging/src/main/kotlin/net/corda/common/logging/errorReporting/CordaErrorContextProvider.kt
> +    companion object {
Yeah, I think this should really be a runtime resource, that way we can capture that information outside of the codebase and thus have it visible and ownable by someone else

2020-04-20 11:55 UTC, fenryka commented on tools/error-page-builder/src/main/kotlin/net/corda/errorPageBuilder/ErrorPageBuilder.kt
> +class ErrorPageBuilder : CordaCliWrapper("error-page-builder", "Builds the error table for the error codes page") {
fair enough

2020-04-20 12:26 UTC, JamesHR3 commented on common/logging/src/main/kotlin/net/corda/common/logging/errorReporting/CordaErrorContextProvider.kt
> +    companion object {
Ok, I can potentially do that. Do we have any idea who would own this resource once the original is created? This again represents a bit of a change to how Corda is deployed and run, and sets a precedent for runtime resource files outside of configuration and the CorDapps, so we might want to think about this a little.

2020-04-20 14:38 UTC, fenryka commented on common/logging/src/main/kotlin/net/corda/common/logging/errorReporting/CordaErrorContextProvider.kt
> +class CordaErrorContextProvider : ErrorContextProvider {
were these added?

2020-04-20 14:47 UTC, fenryka requested changes
stilla few issues

2020-04-20 14:47 UTC, fenryka commented on common/logging/src/main/kotlin/net/corda/common/logging/errorReporting/ErrorResource.kt
> +                    private val classLoader: ClassLoader? = null) {
pretty certain we should subclass this and move classloader onto one of them and remove the runtime switch

2020-04-20 14:47 UTC, fenryka commented on common/logging/src/main/kotlin/net/corda/common/logging/errorReporting/ErrorReporting.kt
> +    fun initialise(localeString: String, location: String) {
what would calling this a second time mean?

2020-04-20 14:59 UTC, JamesHR3 commented on common/logging/src/main/kotlin/net/corda/common/logging/errorReporting/ErrorResource.kt
> +                    private val classLoader: ClassLoader? = null) {
I think you've accidentally reviewed an old version of the code as I have changed this (although it's slightly different to this as well, I realised that all I was really doing was getting a resource bundle from a different place, so I ended up with two static methods for building one of these objects).

2020-04-20 15:00 UTC, JamesHR3 commented on common/logging/src/main/kotlin/net/corda/common/logging/errorReporting/ErrorReporting.kt
> +    fun initialise(localeString: String, location: String) {
This code has also been changed.

2020-04-23 11:36 UTC, fenryka requested changes
two minor things left

2020-04-23 11:36 UTC, fenryka commented on common/logging/src/main/kotlin/net/corda/common/logging/errorReporting/ErrorReporting.kt
> +    fun withLocale(locale: String) : ErrorReporting {
given we've not tested anything should this throw if it's not the default?

2020-04-23 11:36 UTC, fenryka commented on common/logging/src/main/kotlin/net/corda/common/logging/errorReporting/Errors.kt
> +package net.corda.common.logging.errorReporting
We've got two things here that conceptually relate, but not programatically, that feels like a recepie for disaster

2020-04-23 15:06 UTC, JamesHR3 commented on common/logging/src/main/kotlin/net/corda/common/logging/errorReporting/Errors.kt
> +package net.corda.common.logging.errorReporting
Indeed. I'd actually run into this myself when I started to add error codes and addressed this on another branch (along with some other improvements). Logically though these probably belong in this PR, so I'll port them over.

2020-04-27 12:02 UTC, fenryka approved these changes

2020-04-28 09:40 UTC, mnesbit approved these changes
OK

2020-04-28 13:07 UTC, merged