CORDA-3569 - Add RestrictedConnection and more blocked methods to RestrictedEntityManager
corda/corda pull request #6129
Opened 2020-04-03 13:20 UTC by nikinagy

Implemented the TODO on RestrictedEntityManager and blocked transaction related calls on JDBC session, for the second one I introduced the RestrictedConnection class.
Wrote Unit tests to these classes.

2020-04-03 13:49 UTC, fowlerrr submitted a review, later dismissed
I think we should try this without delegation.  Forcing compile-time errors is (nearly) always better than runtime ones.

It should be minimal change to the actual code, but the tests will need some updating then.

2020-04-03 13:49 UTC, fowlerrr commented on core/src/main/kotlin/net/corda/core/node/RestrictedConnection.kt
> +class RestrictedConnection(private val delegate : Connection) : Connection by delegate {
We mentioned in that one meeting about swapping delegation for simply overriding the passed-in `Connection`.  I would prefer that as it gives a compile-time check instead of runtime exceptions.

Doing that _may_ get you past the detekt `TooManyFunctions` check as well.  Or it might not.

2020-04-03 14:26 UTC, fowlerrr commented
> I think we should try this without delegation. Forcing compile-time errors is (nearly) always better than runtime ones.
> 
> It should be minimal change to the actual code, but the tests will need some updating then.

After chatting with Niki we realised that this won't be possible because we'd have to implement all of the interface members, which puts us in the same situation. :(  So we have to have the runtime errors.

2020-04-03 14:27 UTC, fowlerrr commented
We'll want to make sure some docs are added regarding the restriction as well.

2020-04-03 14:36 UTC, mnesbit commented
Have you tried proxying? May help you intercept at a common point

2020-04-03 14:52 UTC, fowlerrr commented
For `RestrictedEntityManager` I think we can actually get away with just returning the class instead of the interface.  So we don't actually need anything fancy there.  Not sure the same holds true of the `jdbcSession(): [Restricted]Connection`

2020-04-03 16:44 UTC, fowlerrr commented
And it turns out we can't even do that. (!) So it's just a matter of adding a couple of driver/MockNode tests of the functionality within a CorDapp and we're done.

2020-04-03 16:49 UTC, mnesbit commented
We can't have compile time errors without pruning the interfaces and they are well known interfaces for a reason. Therefore runtime error are the best we can do, but we should strive to make those errors clear and helpful to the developer.

2020-04-06 10:09 UTC, rick-r3 requested changes
You'll need to fix the detekt issues.  The "too many functions" will obviously need suppressing since you don't have much choice there.

2020-04-06 10:09 UTC, rick-r3 commented on core/src/test/kotlin/net/corda/core/node/RestrictedConnectionTest.kt
> +    fun testAbort(){
Could do with a reformat to put a space in between `(){` throughout this file.  I'm surprised this isn't picked up by detekt.

2020-04-06 10:09 UTC, rick-r3 commented on node-api/src/test/kotlin/net/corda/nodeapi/internal/persistence/RestrtictedEntityManagerTest.kt
> +    fun testClear(){
Could do with a reformat to put a space in between (){ throughout this file. I'm surprised this isn't picked up by detekt.

2020-04-06 15:05 UTC, nikinagy commented
> And it turns out we can't even do that. (!) So it's just a matter of adding a couple of driver/MockNode tests of the functionality within a CorDapp and we're done.

I added the MockNode tests as requested.

2020-04-06 15:45 UTC, fowlerrr commented on node-api-tests/src/test/kotlin/net/corda/nodeapitests/internal/persistence/RestrictedEntityManagerFlowTest.kt
> +                exception = e
I don't think you need to catch this exception.  You can use `assertThatExceptionIsThrown` to check in the test that calls this Flow.

2020-04-06 15:45 UTC, fowlerrr commented on node-api-tests/src/test/kotlin/net/corda/nodeapitests/internal/persistence/RestrictedConnectionFlowTest.kt
> +                exception = e
You can use `assertThatExceptionIsThrown` in the caller instead.

2020-04-09 08:25 UTC, mnesbit commented
I think my only concern here is that the delegate approach is black list only for the methods. Worth double checking that we agree on the interface methods to block and haven't missed any

2020-04-21 13:38 UTC, rick-r3 approved these changes
LGTM 

@lankydan heads up this will mildly conflict with your entity manager stuff but should be easy to resolve (anything you actively support should override unsupported-ness here).

2020-04-21 13:39 UTC, merged