CORDA-3715: Check contract classes hav…
corda/corda pull request #6155
Opened 2020-04-16 18:51 UTC by adelel1

…e class version between 49 and 52

👮🏻👮🏻👮🏻 !!!! DESCRIBE YOUR CHANGES HERE !!!! DO NOT FORGET !!!! 👮🏻👮🏻👮🏻

# PR Checklist:

- [ ] Have you run the unit, integration and smoke tests as described [here](https://docs.corda.net/head/testing.html)?
- [ ] If you added public APIs, did you write the JavaDocs?
- [ ] If the changes are of interest to application developers, have you added them to the [changelog](https://docs.corda.net/head/changelog.html) (`/docs/source/changelog.rst`), and potentially the [release notes](https://docs.corda.net/head/release-notes.html) (`/docs/source/release-notes.rst`)?
- [ ] If you are contributing for the first time, please read the [contributor agreement](https://docs.corda.net/head/contributing.html) now and add a comment to this pull request stating that your PR is in accordance with the [Developer's Certificate of Origin](https://docs.corda.net/head/contributing.html#merging-the-changes-back-into-corda).

Thanks for your code, it's appreciated! :)

2020-04-17 14:38 UTC, chrisr3 requested changes
Did you ask the Classgraph maintainer if he'd be prepared to export the Java byte-code version in his `ClassInfo`?

2020-04-17 14:38 UTC, chrisr3 commented on node/src/main/kotlin/net/corda/node/internal/cordapp/JarScanningCordappLoader.kt
> +            verifyClassVersionNumber(appClassLoader, serializationCustomSerializers.map { it.javaClass.name }.toList(), jarPath)
The `.map {}` already returns a `List<*>` so you don't need to add `.toList()` on the end.

2020-04-17 14:38 UTC, chrisr3 commented on core/src/main/kotlin/net/corda/core/internal/cordapp/CordappImpl.kt
> +        val contractStateClassNames: List<String> = emptyList()
Perhaps?
```kotlin
val contractStateClassNames: Set<String> = emptySet()
```

2020-04-17 14:38 UTC, chrisr3 commented on node/src/main/kotlin/net/corda/node/internal/cordapp/JarScanningCordappLoader.kt
> +        return coreContractStateClasses.flatMap { scanResult.getNamesOfClassesImplementing(it) }.distinct()
Perhaps `flatMapTo(LinkedHashSet()) { ... }` so that we construct the object that we really want straight away?

2020-04-17 14:38 UTC, chrisr3 commented on node/src/test/kotlin/net/corda/node/internal/cordapp/JarScanningCordappLoaderTest.kt
> +        Assume.assumeTrue(JavaVersion.isVersionAtLeast(JavaVersion.Java_11))
I would have thought the _first_ "BAD" version would be Java 9 rather than Java 11. I'm sure that _someone_ out there is using Java 9 and Java 10 _specifically_ to spite us.

2020-04-17 14:38 UTC, chrisr3 commented on core/src/main/kotlin/net/corda/core/internal/InternalUtils.kt
> +            if (magic != -0x35014542) {
Now _that's_ a "Magic Number"! It could do with a name though.

2020-04-17 14:38 UTC, chrisr3 commented on core/src/main/kotlin/net/corda/core/internal/InternalUtils.kt
> +        DataInputStream(classloader.getResourceAsStream("${it.replace('.', '/')}.class")).use { dataStream ->
`getResourceAsStream()` can return `null` if it fails to find the resource.

2020-04-17 14:38 UTC, chrisr3 commented on core/src/main/kotlin/net/corda/core/internal/InternalUtils.kt
> +private const val MAX_CONTRACT_CLASS_VERSION = 52
I don't like these names. Which versions of Java do they correspond to? Java 5 to Java 8?

2020-04-21 17:15 UTC, chrisr3 requested changes
The DJVM will throw up its hands the moment it's asked to sandbox _any_ class that isn't [JDK5..JDK8]. The only way to be _sure_ is to ~nuke the `AttachmentsClassLoader` from orbit~ scan the entire thing.

2020-04-21 17:15 UTC, chrisr3 commented on core/src/main/kotlin/net/corda/core/internal/TransactionVerifierServiceInternal.kt
> +            verifyClassVersionNumber(transactionClassLoader, allStates.map { it.contract }.toSet().toList())
I am confused - why do we still need this function now that ClassGraph can identify the byte-code versions for us? :confused:

And why only check Contract and State classes? The DJVM's is going to check _every single class that it needs to rewrite_, which means that _no_ class inside `AttachmentsClassLoader` can be > Java 8. This includes custom serializers, serialization whitelists and even little utility classes which salt your hashes with emojis.

2020-04-21 17:15 UTC, chrisr3 commented on core/src/main/kotlin/net/corda/core/internal/TransactionVerifierServiceInternal.kt
> +        verifyStatesAndContractsHaveValidClassVersion()
The DJVM already checks the byte-code itself and so doesn't need a check here. And I thought that with the new `ClassGraph` you'd only need to tweak the _existing_ scan something like:
```kotlin
fun <T: Any> getNamesOfClassesImplementing(classloader: ClassLoader, clazz: Class<T>): Set<String> {
    return ClassGraph().overrideClassLoaders(classloader)
        .enableURLScheme(attachmentScheme)
        .ignoreParentClassLoaders()
        .enableClassInfo()
        .pooledScan()
        .use { result ->
            /**
             * Probably not LITERALLY like this, because I'm sure this function is used
             * elsewhere that doesn't necessarily want to scan the entire classloader!
             */
            result.allClasses.firstOrNull { c -> c.classfileMajorVersion !in 49..52 }?.also {
                throw IllegalArgumentException("DOOMED BY ${it.name}")
            }

            result.getClassesImplementing(clazz.name)
                .filterNot(ClassInfo::isAbstract)
                .mapTo(LinkedHashSet(), ClassInfo::getName)
        }
}
```

2020-04-23 11:12 UTC, mnesbit commented
In case anyone screams we need a release note adding

2020-04-28 10:10 UTC, chrisr3 commented on core/src/main/kotlin/net/corda/core/internal/InternalUtils.kt
> +const val JDK1_1_CLASS_FILE_FORMAT_MAJOR_VERSION = 45
According to ASM, the version constant for Java 1.1 isn't like all the others:
```
  // Java ClassFile versions (the minor version is stored in the 16 most significant bits, and the
  // major version in the 16 least significant bits).

  int V1_1 = 3 << 16 | 45;
```
Do you take this into account?

2020-04-28 10:40 UTC, adelel1 commented on core/src/main/kotlin/net/corda/core/internal/InternalUtils.kt
> +const val JDK1_1_CLASS_FILE_FORMAT_MAJOR_VERSION = 45
As discussed switched to 1.2

2020-04-28 11:55 UTC, chrisr3 requested changes
The `SerializationWhitelist` classes are also mapped into the sandbox.

2020-04-28 11:55 UTC, chrisr3 commented on core-deterministic/testing/src/test/kotlin/net/corda/core/internal/ClassLoadingUtils.kt
>      return emptySet()
Why `IntRange.EMPTY` instead of `null`? You have to check `classVersionRange` anyway, so why not check whether it's `null`?

2020-04-28 11:55 UTC, chrisr3 commented on core/src/main/kotlin/net/corda/core/internal/ClassLoadingUtils.kt
> +            if (classVersionRange != IntRange.EMPTY) {
You're checking `classVersionRange` before using it, so why _not_ just check whether it's `null`?

2020-04-28 11:55 UTC, chrisr3 commented on core/src/main/kotlin/net/corda/core/internal/ClassLoadingUtils.kt
> +                                           classVersionRange: IntRange = IntRange.EMPTY): Set<String> {
This function only has two callers, and I'm not a big fan of assigning default parameter values to everything, Can we drop this default value here and just add it explictly to `DeterministicVerifier` instead please?
```kotlin
val customSerializerNames = getNamesOfClassesImplementing(transactionClassLoader, SerializationCustomSerializer::class.java, null)
```
Note that the other caller provides an explicit value here anyway, and I don't see what we gain by using `IntRange.EMPTY` instead of `null`.

2020-04-28 11:55 UTC, chrisr3 commented on core/src/main/kotlin/net/corda/core/internal/ClassLoadingUtils.kt
> +    return getNamesOfClassesImplementing(classloader, clazz, classVersionRange)
Better:
```kotlin
fun <T: Any> createInstancesOfClassesImplementing(classloader: ClassLoader, clazz: Class<T>,
                                                  classVersionRange: IntRange? = null): Set<T> {
   ...
}
```
And missing KDoc :grin:.

2020-04-28 11:55 UTC, chrisr3 commented on node/src/main/kotlin/net/corda/node/internal/cordapp/JarScanningCordappLoader.kt
>          val whitelists = ServiceLoader.load(SerializationWhitelist::class.java, appClassLoader).toList()
You need to version-check the `SerializationWhitelist` classes too.

2020-04-28 13:35 UTC, adelel1 commented on core-deterministic/testing/src/test/kotlin/net/corda/core/internal/ClassLoadingUtils.kt
>      return emptySet()
Changed to null.

2020-04-28 13:35 UTC, adelel1 commented on core/src/main/kotlin/net/corda/core/internal/ClassLoadingUtils.kt
> +            if (classVersionRange != IntRange.EMPTY) {
Changed.

2020-04-28 13:37 UTC, adelel1 commented on core/src/main/kotlin/net/corda/core/internal/ClassLoadingUtils.kt
> +                                           classVersionRange: IntRange = IntRange.EMPTY): Set<String> {
I left the default in, createInstancesOfClassesImplementing has 6 callers (incl 3 test ones).

2020-04-28 13:38 UTC, adelel1 commented on core/src/main/kotlin/net/corda/core/internal/ClassLoadingUtils.kt
> +    return getNamesOfClassesImplementing(classloader, clazz, classVersionRange)
Updated.

2020-04-28 13:38 UTC, adelel1 commented on node/src/main/kotlin/net/corda/node/internal/cordapp/JarScanningCordappLoader.kt
>          val whitelists = ServiceLoader.load(SerializationWhitelist::class.java, appClassLoader).toList()
Done.

2020-04-28 14:53 UTC, rick-r3 commented
We need to be very cautious / clear about the introduction of this:

1. What if someone has class versions currently on the ledger that are "too old" ?  It seems like we can't stop a transaction that used to verify from verifying.

2. Under what scenarios can someone have classes that are "too new"?  Would they have to be running on JDK9+ or could transactions be verifying on JDK8 with JDK9+ classes "knocking around in the JARs"  that we might now detect and reject?

2020-04-28 14:57 UTC, rick-r3 commented
@chrisr3 is familiar with some sneaky techniques for substituting attachments in failure scenarios.  Maybe we need to make this one of the scenarios in which substitution is allowed?  i.e. we found illegal byte code in your attachments, invoke substitution mechanism.

2020-04-28 15:47 UTC, adelel1 commented
@rick-r3 The reason for this change is to validate that contract bytecode is JDK 1.8 conformant. In terms of older class versions we do allow from JDK1.2.
There shouldn't be any newer class file versions being used, if there are any then the UnsupportedClassVersionError exception will be raised.
For existing customers assuming they are using JDK8, they wont be able to use newer class versions, the JDK will raise UnsupportedClassVersionError. So I believe we are OK here.

2020-04-29 10:09 UTC, chrisr3 requested changes
Missed one :wink:

I'm not a great fan of Kotlin's default parameters, tbh. They might make the source code look pretty, but they also generate nasty synthetic surprises in your public ABI.

2020-04-29 10:09 UTC, chrisr3 commented on core-deterministic/testing/src/test/kotlin/net/corda/core/internal/ClassLoadingUtils.kt
>      return emptySet()
This file in the `:core-deterministic:testing` module is a stub-copy of `ClassLoadingUtils.kt` in `:core`. It's signature needs to be updated to use `null` too, to match the one in `:core`.

2020-04-29 15:51 UTC, mnesbit approved these changes
OK

2020-04-29 17:14 UTC, chrisr3 approved these changes
Fair enough.

2020-04-30 07:57 UTC, merged