[EG-153]Adding sshd by default to docker node.conf template
corda/corda pull request #6171
Opened 2020-04-21 21:22 UTC by jmacmahonr3

Adding the sshd field and port by default to the node.conf template that is used by the docker images when generating node config on container start up.

2020-04-27 13:29 UTC, JamesHR3 requested changes
One small comment in the code, plus a general question below.

Will the change in the `generate-config` file conflict when this gets merged into ENT?

2020-04-27 13:29 UTC, JamesHR3 commented on docker/src/bash/generate-config.sh
> +    : ${NETWORK_TRUST_PASSWORD=:? '$NETWORK_TRUST_PASSWORD, the password to the network store to use when joining must be set as environment variable'}
Think you've duplicated the password bit here, and I can't see where you're checking for the existence of the `SSHPORT` variable - have you accidentally forgotten to change this?

2020-04-29 14:59 UTC, JamesHR3 requested changes

2020-04-29 14:59 UTC, JamesHR3 commented on docker/src/config/starting-node.conf
> +    port=${SSHPORT}
You still don't have an `SSHPORT` variable in `generate-config.sh` do you?

2020-04-29 21:18 UTC, jmacmahonr3 commented on docker/src/config/starting-node.conf
> +    port=${SSHPORT}
Don't think it's a mandatory field. You can generate without one if you want.

2020-04-30 08:21 UTC, JamesHR3 commented on docker/src/config/starting-node.conf
> +    port=${SSHPORT}
Ah, so that's only for mandatory fields? Out of interest, what happens if the `SSHPORT` isn't specified? I would guess ordinarily if you didn't want the ssh config you wouldn't specify the `sshd` config block at all

2020-04-30 13:44 UTC, JamesHR3 approved these changes
LGTM

2020-04-30 13:44 UTC, fenryka commented
what happens to people who are currently running this and we suddenly break it by making something they don't have mandatory?

2020-04-30 13:50 UTC, jmacmahonr3 commented
I suspect any running docker images will be fine but redeploying will require the new required variables.

2020-04-30 13:51 UTC, fenryka commented
So, can that be mitigated? if not this is a big old RELEASE NOTE required type thing @ivanterziev-r3

2020-04-30 14:00 UTC, jmacmahonr3 commented
My previous comment is incorrect. 

This Open source 4.5 will be a new image and will require mandatory migration from any of the previous 4.4 issues. No one using any of the current images should be affected by this.

2020-04-30 14:03 UTC, merged