CORDA-3659 - adding kdoc for RestrictedEntityManager and RestrictedConnection
corda/corda pull request #6179
Opened 2020-04-23 09:53 UTC by nikinagy

adding kdoc for RestrictedEntityManager and RestrictedConnection

2020-04-23 12:15 UTC, rick-r3 requested changes

2020-04-23 12:15 UTC, rick-r3 commented on node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/RestrictedConnection.kt
> + * - setSavepoint()
I think these kdoc should go on the APIs the customers (CorDapp authors) see, rather than our implementations of the restricted connection / entity manager.

i.e. put them on the methods on `ServiceHub` that give access (`jdbcSession`, and the `withEntityManager` variants).

2020-04-23 12:16 UTC, nikinagy commented on node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/RestrictedConnection.kt
> + * - setSavepoint()
Okay, fair point.

2020-04-23 14:09 UTC, nikinagy commented on node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/RestrictedConnection.kt
> + * - setSavepoint()
I moved it.

2020-04-24 12:25 UTC, rick-r3 approved these changes

2020-04-28 08:35 UTC, merged