CORDA-3755: Switched attachments map to a WeakHashMap
corda/corda pull request #6214
Opened 2020-05-04 15:26 UTC by adelel1

Switched the map holding the attachments to a weak hash map. 

The associated strong reference referring to it is the attachment id, which then gets stored in a URL, which is used by the AttachmentsClassLoader.

2020-05-04 15:31 UTC, mnesbit commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
> +
I guess the question is will the IOException on line 385 happen more often now and is that bad/handled proeprly?

2020-05-04 15:33 UTC, mnesbit commented on core/src/test/kotlin/net/corda/core/internal/ClassLoadingUtilsTest.kt
> +            System.gc()
Do we need a test that forces GC during a verify, or something? To ensure that we know references are held thoughout verify and flows that manipulate attachements?

2020-05-04 16:05 UTC, adelel1 commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
> +
It shouldn't happen any more often, actually it shouldn't happen at all.

The existing code doesn't really completely handle a new 'attachments' protocol. i.e. I cannot create a string "attachment::/123454322" pass this to a URL and then stream data from the inputStream. I can only create a URL by passing the attachment I want to stream from. So the life of the attachment matches the life of the URL, this is then passed to URL class loader.
So basically the implementation assumes its only used by the AttachmentsClassLoader.

2020-05-04 16:09 UTC, chrisr3 reviewed
I'm sure that I had a branch somewhere that planned to add `/$id` as the URL path, because I had a reason for wanting the path elements to start with `/`. Something to do with matching code-sources to grants in a security policy file (I think). I don't seem to have that branch any more, but that change would break this PR wide open.

2020-05-04 16:09 UTC, chrisr3 commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
>          return URL(attachmentScheme, "", -1, id, AttachmentURLStreamHandler)
You are now _relying_ on `URL` maintaining a strong reference to this _particular_ `id` String object. The fact that it does so is merely a fortunate implementation detail of this `URL` constructor. This is non-obvious and very scary.

2020-05-04 16:09 UTC, chrisr3 commented on core/src/test/kotlin/net/corda/core/internal/ClassLoadingUtilsTest.kt
> +        while (AttachmentURLStreamHandlerFactory.loadedAttachmentsSize() != 0 && count++ < 100) {
IIRC `System.gc` merely _requests_ that the JVM schedule some garbage collection. Calling it repeatedly like this is just like hammering the button on a pelican crossing. Have you considered using a `ReferenceQueue`? You could put the `String` object inside a _second_ `WeakReference` that has an associated `ReferenceQueue`, clear the strong reference, invoke `System.gc` once and then wait for the object to appear on the queue.

More specifically, you'd probably need to extend `WeakReference<URL>` so that you could add an extra data field to it. `WeakReference.get()` will return `null` once the URL has been garbage collected, but if you remove an instance of your extended `WeakReference` class off the queue then you can still read its extra data field.

2020-05-05 12:39 UTC, adelel1 commented on core/src/test/kotlin/net/corda/core/internal/ClassLoadingUtilsTest.kt
> +            System.gc()
Added a test for this for the verify. For flows this change is orthogonal. The change only affects code where the attachments are in the classpath.

2020-05-05 12:41 UTC, adelel1 commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
>          return URL(attachmentScheme, "", -1, id, AttachmentURLStreamHandler)
Ok, I have also now attached the lifetime of the attachments in the map to the lifetime of the attachments classloader using them (which should also match the URL lifetime).

2020-05-05 12:45 UTC, adelel1 commented on core/src/test/kotlin/net/corda/core/internal/ClassLoadingUtilsTest.kt
> +        while (AttachmentURLStreamHandlerFactory.loadedAttachmentsSize() != 0 && count++ < 100) {
Ok - now checking the reference queue after a gc.

2020-05-05 15:43 UTC, rick-r3 requested changes

2020-05-05 15:43 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
> +        loadedAttachments[attachmentWithKey.key] = attachmentWithKey.attachment
There is significant jeopardy / bugs here.  I think @chrisr3 was mentioning some.  My main concern is that the `String` of the ID is new every time.  So if someone requests the same attachment in parallel, one potentially overwrites the other and then the lifetimes of the `String` in the `WeakHashMap` are not aligned with the need to keep the mapping in the map and you could find that it's not possible to resolve a URL that should be in the map.

If we could somehow arrange to retrieve the identical `String` that is already a key in the map and use that in the URL then we would be linking the life span appropriately.  But this linking by `String` of the URL path seems very brittle to me.

Basically, it's a right pain.

2020-05-05 15:43 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
> +        loadedAttachments[attachmentWithKey.key] = attachmentWithKey.attachment
I've pushed what I think it should look like in a branch `parkri/CORDA-3755`.  It looks a bit mad, but I think this is required.

2020-05-05 15:47 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
> +        loadedAttachments[attachmentWithKey.key] = attachmentWithKey.attachment
Basically I created a strong reference chain from the `Attachment` to the `String` ID.  The `Attachment` need to be shared always, so there's a de-duplication step there, and the de-duplicated ones are retained by the class loader to assure equal or better life span.  Finally the original map's value is wrapped in a `WeakReference` otherwise there's a cycle.  It might have needed it before, perhaps, but it definitely does now.

2020-05-05 15:57 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
> +        loadedAttachments[attachmentWithKey.key] = attachmentWithKey.attachment
Two threads (lines begin with thread number):

1. Build attachment class loader with attachments (A, B)
1. Map ends up with "A" = A and "B" = B
2. Build attachment class loader with attachments (A, C) 
2. Map ends up with "A"(prime) = A, "B" = B, "C" = C (i.e. the string "A" is different instance)
2. Looks up attachments during verify .... all good.
2. Class loader discarded (I know it's cached.... but might be evicted and want it to work without cache). "A"(prime) goes out of scope so attachment is discarded from map.
1. Looks up attachment for "A", finds null.  Boom!

2020-05-06 16:58 UTC, rick-r3 submitted a review, later dismissed
LGTM

2020-05-06 16:58 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
> +private class AttachmentsHolderImpl : AttachmentsHolder {
Nice.  Really boosts readability at the call site.

2020-05-07 12:11 UTC, chrisr3 reviewed
Just a few comments on the tests.

2020-05-07 12:11 UTC, chrisr3 commented on core/src/test/kotlin/net/corda/core/internal/ClassLoadingUtilsTest.kt
> +    @Ignore
Even better:
```kotlin
@Ignore("Using System.gc in this test which has no guarantees when/if gc occurs.")
```

2020-05-07 12:11 UTC, chrisr3 commented on core/src/test/kotlin/net/corda/core/internal/ClassLoadingUtilsTest.kt
> +        assertNotNull(ref2)
More accurately:
```kotlin
assertSame(weakReference2, ref2)
assertSame(weakReference1, referenceQueue1.poll())
```
And then you can suppress fewer warnings too:
```kotlin
@Suppress("ExplicitGarbageCollectionCall", "UNUSED_VALUE")
```

2020-05-07 12:11 UTC, chrisr3 commented on core/src/test/kotlin/net/corda/core/internal/ClassLoadingUtilsTest.kt
> +        assertNotNull(ref1)
```kotlin
assertSame(weakReference1, ref1)
```

2020-05-07 12:11 UTC, chrisr3 commented on core/src/test/kotlin/net/corda/core/internal/ClassLoadingUtilsTest.kt
> +        assertNotNull(ref2)
```kotlin
assertSame(weakReference2, ref2)
```
And then suppress fewer warnings again.

2020-05-11 17:08 UTC, rick-r3 commented
I think if you rebase this you might pick up some test fixes

2020-05-12 08:50 UTC, rick-r3 approved these changes

2020-05-12 08:51 UTC, merged