fixed EG-465+tests+manual
corda/corda pull request #6224
Opened 2020-05-07 14:24 UTC by pnemeth

- Improved functionality to support transaction id-s not only hashes of transactions
- Updated test
- Update manual

2020-05-07 15:10 UTC, JamesHR3 requested changes
Couple of comments.

Could you put the Jira ticket as the first item in the PR title? It's generally good style to do this, and I'm not sure if Jira picks the PR up if you don't. It's useful to put a description in the title for exactly what it is you've fixed here too, partially for people browsing PRs to figure out if they care, and partly as the PR title often ends up as the message in `git log` for the change.

2020-05-07 15:10 UTC, JamesHR3 commented on tools/shell/src/integration-test/kotlin/net/corda/tools/shell/HashLookupCommandTest.kt
> +        println(response)
I don't think you want to leave this in.

2020-05-07 15:10 UTC, JamesHR3 commented on tools/shell/src/main/java/net/corda/tools/shell/HashLookupShellCommand.java
> +    @Command
You should also edit the `@Usage` statement below.

2020-05-07 16:49 UTC, JamesHR3 approved these changes
LGTM

2020-05-07 16:50 UTC, JamesHR3 commented
@adagys do you know why the test here was `@Ignore`d? I just want to make sure we're not going to introduce further TC instability or similar by enabling this.

2020-05-08 09:55 UTC, merged

2020-05-11 07:09 UTC, adagys commented
@JamesHR3 Unfortunately, I don't remember why