Adding serializable payload with all contents of a TB
corda/corda pull request #6226
Opened 2020-05-07 20:46 UTC by rogersanick

👮🏻👮🏻👮🏻 !!!! DESCRIBE YOUR CHANGES HERE !!!! DO NOT FORGET !!!! 👮🏻👮🏻👮🏻

**_DRAFT_** - Adding utility functions to transform a TB into an acceptable format for transmission over the wire to facilitate DVP.

# PR Checklist (_will update as completed_):

- [ ] Have you run the unit, integration and smoke tests as described [here](https://docs.corda.net/head/testing.html)?
- [ ] If you added public APIs, did you write the JavaDocs?
- [ ] If the changes are of interest to application developers, have you added them to the [changelog](https://docs.corda.net/head/changelog.html) (`/docs/source/changelog.rst`), and potentially the [release notes](https://docs.corda.net/head/release-notes.html) (`/docs/source/release-notes.rst`)?
- [ ] If you are contributing for the first time, please read the [contributor agreement](https://docs.corda.net/head/contributing.html) now and add a comment to this pull request stating that your PR is in accordance with the [Developer's Certificate of Origin](https://docs.corda.net/head/contributing.html#merging-the-changes-back-into-corda).

Thanks for your code, it's appreciated! :)

2020-05-11 08:13 UTC, mnesbit requested changes
I have always fought against precisely this type of serialization of the transaction builder. The problem with this sort of logic is that nobody goes back and checks the underlying data. The flows just pass around the object even if somebody has manipulated the content and the peers just blindly sign it. It was very intentional that flows end up sending StateRefs (not even StateAndRefs as again you have to resolve the source transaction to prove no manipulation). The name WireTransactionBuilder is also very confusing as we have a very concrete WireTransaction type that this is not related to.
I did investigate originally an append only TransactionBuilder that when you deserialized could be merged with an original one to confirm the peer had only appended data, not modified your leg of the transaction. However, that was pretty ugly too when I wrote it.
In general it is much better if one party coordinates the assembly of the transaction and then we send an immutable SignedTransaction for peers to confirm. In practice the nodes are working to some external data reference anyway when it comes to selecting the content of a shared deal.
So could you add some more details on the DVP logic you are playing with to work out what would be a better approach.

2020-05-11 08:39 UTC, mnesbit commented
Also this is clearly 4.6 work

2020-05-11 13:07 UTC, rogersanick commented
@mnesbit - Thank you for the feedback!

I understand your point about peers blindly signing - for the sake of argument, could one assume that any malicious changing of the TX data would be caught by the implemented contract? Assuming the initiating party also performed a check to ensure that the counter party only appended data to the TX builder and didn't change its initial content.

The append-only transaction builder is really interesting. What about its implementation was ugly? Also I hear your criticism on the naming, I will try something that is less easily confused with `WireTransaction`.

The code [this flow(https://github.com/rogersanick/SettlersOfCordan/blob/master/workflows/src/main/kotlin/com/r3/cordan/primary/flows/trade/ExecuteTradeFlow.kt) is what I'm trying to avoid. Facilitating a two-party deal flow becomes difficult when the counter party needs to make some kind of selection. E.g. - an FX swap where I send $1 USD and you respond with $1.32 CAD - in doing so you would have to select tokens amounting to $1.32 CAD from your vault, add the appropriate commands, produce change, attach the token type jar, etc. All of those actions are currently facilitated using the Transaction Builder via the tokens SDK. So if you want to have some semblance of DVP using the tokens SDK, you have to decompose the TX builder and send its components over the wire (which is VERY ugly).

2020-09-17 22:01 UTC, rnicoll commented
@rogersanick Trying to clean up old PRs, is this still in progress or should it be closed?

2020-09-18 12:57 UTC, rogersanick commented
@rnicoll -- yes, intention was to allow sending of a TB contents over the wire to simplify multiparty transaction building. No ticket or anything so we can close this one. More of a POC than anything else.

2020-09-18 12:57 UTC, closed without merging