CORDA-3587 - adding kdocs for current behaviour of VaultQueryCriteria
corda/corda pull request #6242
Opened 2020-05-12 17:46 UTC by nikinagy

https://r3-cev.atlassian.net/browse/CORDA-3589

2020-05-14 12:17 UTC, fowlerrr commented on core/src/main/kotlin/net/corda/core/node/services/vault/QueryCriteria.kt
> +         */
I wonder if you will need this section for each function, nearly identical but slightly specific to each?  Because as kdoc it should end up in the api spec on the docs site, right?  One comment above a block doesn't show up well, I think.

2020-05-14 12:40 UTC, ivanterziev-r3 commented on core/src/main/kotlin/net/corda/core/node/services/vault/QueryCriteria.kt
> +         */
/**
         * Each of the following functions creates a new [VaultQueryCriteria] object with default values, and sets the value of the given parameter.
         * Please use only one function at a time to make sure they are not overwriting each other.
         */

2020-05-14 12:40 UTC, ivanterziev-r3 commented on core/src/main/kotlin/net/corda/core/node/services/vault/QueryCriteria.kt
> +         */
Also @fowlerrr has got a point, we should have a description per function even if they are identical.

2020-05-14 12:43 UTC, ivanterziev-r3 commented on core/src/main/kotlin/net/corda/core/node/services/vault/QueryCriteria.kt
> +         * The following functions are copying the existing [VaultQueryCriteria] object and setting the given value for the given field.
* Each of the following functions below copies the existing [VaultQueryCriteria] object, and sets the given value for the given field.

NB Same as above, perhaps refactor to add the following sentence for each function:

         * This function copies the existing [VaultQueryCriteria] object and sets the given value for the given field.

BTW, what is the "given value" here? Sounds like a mistake to me.

2020-05-14 12:48 UTC, nikinagy commented on core/src/main/kotlin/net/corda/core/node/services/vault/QueryCriteria.kt
> +         * The following functions are copying the existing [VaultQueryCriteria] object and setting the given value for the given field.
You need to define the new value for the field you want to change, that is the given value.

2020-05-14 12:48 UTC, ivanterziev-r3 commented on core/src/main/kotlin/net/corda/core/node/services/vault/QueryCriteria.kt
> +         * Copies [this] [VaultQueryCriteria] object.
For consistency:

         * This function copies [this] [VaultQueryCriteria] object.

2020-05-14 12:51 UTC, ivanterziev-r3 commented on core/src/main/kotlin/net/corda/core/node/services/vault/QueryCriteria.kt
> +         * The following functions are copying the existing [VaultQueryCriteria] object and setting the given value for the given field.
Ok that makes sense, but then we should document it (if it's not too obvious of course). 
Is it the same case for the functions above e.g. you define the field value too?

2020-05-14 12:53 UTC, ivanterziev-r3 commented on core/src/main/kotlin/net/corda/core/node/services/vault/QueryCriteria.kt
> +         * Creates a [VaultQueryCriteria] object with the values passed, all the other fields are getting the default values.
* This function creates a [VaultQueryCriteria] object with the given values. All other fields have the default values set.

NB I assumed that "passed" here is equivalent to "given" as above.

2020-05-14 12:54 UTC, ivanterziev-r3 commented on core/src/main/kotlin/net/corda/core/node/services/vault/QueryCriteria.kt
> +         * Creates a [VaultQueryCriteria] object with the values passed, all the other fields are getting the default values.
Same as in the comment below

2020-05-14 12:56 UTC, ivanterziev-r3 commented on core/src/main/kotlin/net/corda/core/node/services/vault/QueryCriteria.kt
> +         * You can use more than one of these functions together.
If adding a description for every function, keep this as a note for each description and change to:

         * You can use more than one of the functions in this group together.

NB We need to see how the list of functions will look like in the kotlin docs output, my reference to "functions in this group" might be misleading depending on how the functions are listed with their descriptions.

2020-05-14 12:57 UTC, ivanterziev-r3 commented on core/src/main/kotlin/net/corda/core/node/services/vault/QueryCriteria.kt
> +         * In case you are using a function from above as well (which creates a new [VaultQueryCriteria] object), make sure that you are
* In case you are also using a function that creates a new [VaultQueryCriteria] object, make sure that you are
         * calling these methods after the method described here.

NB check for accuracy (e.g. the method described here)

2020-05-14 12:58 UTC, ivanterziev-r3 requested changes
Added a few suggestions

2020-05-14 13:08 UTC, nikinagy commented on core/src/main/kotlin/net/corda/core/node/services/vault/QueryCriteria.kt
> +         * The following functions are copying the existing [VaultQueryCriteria] object and setting the given value for the given field.
Yes, the purpose of these functions is that you want to change the current value of a field to a new value, so it requires that you have to define the new value.
For example with withParticipants() you are changing the list of participants, but of course you need to add there the new list of the participants you want like this: withParticipants(newListOfParticipantsThatIWant())
I don't think that this part needs any documentation, I think it is pretty obvious.

2020-05-14 13:18 UTC, ivanterziev-r3 commented on core/src/main/kotlin/net/corda/core/node/services/vault/QueryCriteria.kt
> +         * The following functions are copying the existing [VaultQueryCriteria] object and setting the given value for the given field.
Agreed, so in that case the sentence above should also have the "given" part in it, e.g.

This function creates a new [VaultQueryCriteria] object for ConstraintTypes with default values, and sets the given value of the given parameter.

2020-05-16 10:53 UTC, ivanterziev-r3 approved these changes
LGTM

2020-05-21 12:26 UTC, merged