[EG-2225] Prevent extra directories being created when relative base directories are specified
corda/corda pull request #6282
Opened 2020-05-22 14:40 UTC by JamesHR3

There is a hidden `cordappDirectories` configuration option that informs the node where CorDapps are located. By default, this points to the `cordapps` directory within the base directory of the node. If the configuration option is not specified, then path resolution was being performed twice, resulting in the actual path appearing in the node configuration looking like `basepath/./basepath/./cordapps` if `basepath` is a relative path. The `CordappConfigFileProvider` uses the value of the `cordappDirectories` configuration to create the `config` directory if this doesn't exist. As a result, when a relative path is passed as the base directory, an extra set of directories would be created in the base directory as `node-name/cordapps/config`.

The fix is to ensure that the base directory is only resolved once.

2020-06-02 12:55 UTC, fenryka requested changes
just two comments, mostly I think we should think a bit more carefully about test timeouts

2020-06-02 12:55 UTC, fenryka commented on node/src/test/kotlin/net/corda/node/services/config/NodeConfigurationImplTest.kt
> +    @Test(timeout=300_000)
not to be picky but I don't think setting this timeout to such a big number is sane

2020-06-02 12:55 UTC, fenryka commented on node/src/test/kotlin/net/corda/node/services/config/NodeConfigurationImplTest.kt
> +        assertThat(nodeConfiguration.isValid).isTrue()
doesn't assertTrue or just assert exist?

2020-06-02 14:26 UTC, fenryka approved these changes

2020-06-02 14:26 UTC, merged

2020-06-18 19:11 UTC, rekalov commented
3 seconds??? In my IDE test takes ~3.25 (in CE).