CORDA-3578 add corda prefix to conf file names as original issue was …
corda/corda pull request #6322
Opened 2020-06-08 13:42 UTC by Vengi58

CORDA-3578 add corda prefix to conf file names as original issue was having non-corda reference.conf files on classpath causes DriverDSLImp failure
it is better to have this naming convention and avoid further conflicts of conf files.

2020-06-10 08:30 UTC, rick-r3 commented on testing/testserver/src/main/kotlin/net/corda/webserver/WebArgsParser.kt
> +        val defaultConfig = ConfigFactory.parseResources("corda-web-reference.conf", parseOptions.setAllowMissing(false))
I don't think I would necessarily change this one.  It's in testing, and not part of the clash that is `reference.conf`.  Partly because I'm not sure what the fall out from that would be.  The web server stuff is borrowed often by developers.  Not sure quite in what way... but best left alone I think.

2020-06-10 08:30 UTC, rick-r3 commented on tools/demobench/src/test/kotlin/net/corda/demobench/model/NodeConfigTest.kt
> +                .withFallback(ConfigFactory.parseResources("corda-web-reference.conf"))
Again, think I would leave this one.

2020-06-10 08:30 UTC, rick-r3 commented on tools/loadtest/src/main/kotlin/net/corda/loadtest/Main.kt
> +    val defaultConfig = ConfigFactory.parseResources("corda-loadtest-reference.conf", ConfigParseOptions.defaults().setAllowMissing(false))
I think this one is fine as I'm certain no one is expecting to mess around with the code here (unlike the web server bit.

2020-06-10 14:22 UTC, Vengi58 commented on testing/testserver/src/main/kotlin/net/corda/webserver/WebArgsParser.kt
> +        val defaultConfig = ConfigFactory.parseResources("corda-web-reference.conf", parseOptions.setAllowMissing(false))
reverted this rename.

2020-06-10 14:22 UTC, Vengi58 commented on tools/demobench/src/test/kotlin/net/corda/demobench/model/NodeConfigTest.kt
> +                .withFallback(ConfigFactory.parseResources("corda-web-reference.conf"))
reverted this rename.

2020-06-10 14:23 UTC, Vengi58 commented on tools/loadtest/src/main/kotlin/net/corda/loadtest/Main.kt
> +    val defaultConfig = ConfigFactory.parseResources("corda-loadtest-reference.conf", ConfigParseOptions.defaults().setAllowMissing(false))
reverted this rename.

2020-06-10 14:37 UTC, fowlerrr requested changes
I think you have a comment and file rename to fix:

node/src/main/resources/reference.conf → node/src/main/resources/corda-reference.conf

2020-06-10 14:37 UTC, fowlerrr commented on tools/demobench/src/main/kotlin/net/corda/demobench/model/NodeConfig.kt
> + * This is a subset of FullNodeConfiguration, containing only those configs which we need. The node uses corda-reference.conf
Does this need reverting now?

2020-06-10 14:40 UTC, Vengi58 commented on tools/demobench/src/main/kotlin/net/corda/demobench/model/NodeConfig.kt
> + * This is a subset of FullNodeConfiguration, containing only those configs which we need. The node uses corda-reference.conf
No, as agreed, reference.conf should be renamed to corda-reference.conf and not the other conf files. So I renamed in the comment as well.

2020-06-11 08:14 UTC, fowlerrr approved these changes

2020-06-16 08:15 UTC, merged