CORDA-3769: Switched attachments class loader cache to use caffeine
corda/corda pull request #6326
Opened 2020-06-09 10:32 UTC by adelel1

Switched the attachments class loader to use caffeine for its cache. The original implementation is kept for deterministic core.

2020-06-09 13:09 UTC, chrisr3 requested changes
I've been immersed in byte-code-land for _far_ too long, and am not one of Kotlin's biggest fans...

2020-06-09 13:09 UTC, chrisr3 commented on core-deterministic/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsCacheImpl.kt
> +private class AttachmentsCacheImpl<K, V>(maxSize: Int = 1000) : AttachmentsCache<K, V> {
Why does this constructor have a default parameter value? This default is just an unused magic number that tells Kotlin to generate synthetic bloat. It can be removed, and no-one will ever notice.

P.S. I am not a fan of Kotlin's default parameter values - as far as I can tell they're a lot of pain for negligible gain.

2020-06-09 13:09 UTC, chrisr3 commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
> +private class AttachmentsCacheImpl<K, V>(maxSize: Int = 1000) : AttachmentsCache<K, V> {
This class doesn't need a default constructor parameter value either, for the same reason.

2020-06-09 13:09 UTC, chrisr3 commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
> +    private val cache: Cache<K, V> = Caffeine.newBuilder().maximumSize(maxSize.toLong()).build<K, V>()
The generic parameters for `build<K, V>()` are not needed.

2020-06-09 13:09 UTC, chrisr3 commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
> +}
The underlying cache suggests that the type of the mapping function is actually:
```kotlin
java.util.function.Function<in K, out V>
```
Kotlin generates an extra synthetic class to map the Kotlin lambda to `java.util.function.Function`:
```
AttachmentsCacheImpl$sam$java_util_function_Function$0.class
```
which is why you needed to add the `*` to the exclusions in `core-deterministic/build.gradle`. Alternatively, you could just use `java.util.function.Function` directly and remove some more Kotlin bloat.

2020-06-09 14:19 UTC, adelel1 commented on core-deterministic/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsCacheImpl.kt
> +private class AttachmentsCacheImpl<K, V>(maxSize: Int = 1000) : AttachmentsCache<K, V> {
ok, done.

2020-06-09 14:19 UTC, adelel1 commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
> +private class AttachmentsCacheImpl<K, V>(maxSize: Int = 1000) : AttachmentsCache<K, V> {
Ok, done.

2020-06-09 14:19 UTC, adelel1 commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
> +    private val cache: Cache<K, V> = Caffeine.newBuilder().maximumSize(maxSize.toLong()).build<K, V>()
Done.

2020-06-09 14:22 UTC, adelel1 commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
> +}
I tried this. But then it would mean the client code in AttachmentsClassLoaderBuilder would need to change slightly, i.e. would need to pass in Function { ... }, rather than the expression as it is now.
I figured how it is now is OK.

2020-06-09 14:28 UTC, chrisr3 commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
> +}
Specifically,
```kotlin
val serializationContext = cache.computeIfAbsent(Key(attachmentIds, params)) {
   // expression
}
```
would become
```kotlin
val serializationContext = cache.computeIfAbsent(Key(attachmentIds, params), Function {
    // exactly the same expression
})
```
That didn't seem like a biggie to me.

2020-06-09 14:46 UTC, adelel1 commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
> +}
Ok. Updated.

2020-06-09 14:56 UTC, chrisr3 submitted a review, later dismissed
LGTM. I'm sure a lot of Kotlin's features exist just to make the _source code_ look pretty, because I really don't like much of the generated byte-code.

2020-06-09 15:01 UTC, chrisr3 commented on core-deterministic/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsCacheImpl.kt
> +private class AttachmentsCacheImpl<K, V>(maxSize: Int = 1000) : AttachmentsCache<K, V> {
:+1:

2020-06-09 15:01 UTC, chrisr3 commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
> +private class AttachmentsCacheImpl<K, V>(maxSize: Int = 1000) : AttachmentsCache<K, V> {
:+1:

2020-06-09 15:02 UTC, chrisr3 commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
> +}
:+1:

2020-06-09 15:02 UTC, chrisr3 commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
> +    private val cache: Cache<K, V> = Caffeine.newBuilder().maximumSize(maxSize.toLong()).build<K, V>()
:+1:

2020-06-09 16:40 UTC, rick-r3 requested changes
That's the basics, but we need to hook up to our Caffeine cache factory.

2020-06-09 16:40 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
> +    private val cache: AttachmentsCache<Key, SerializationContext> = AttachmentsCacheImpl(CACHE_SIZE)
This needs more work to make use of the `NamedCacheFactory` infrastructure we have.  Somehow we need to thread that through.  I think it will probably need to come in on the call to `withAttachmentsClassloaderContext`, taking the factory from `ServicesForResolution` somewhere along the line.  i.e. I think `WireTransaction.toLedgerTransaction(services: ServicesForResolution)` will be the point we can pick up the factory.

The factory is already on `ServiceHubInternalImpl` so we just need to get it to the right place.  `ServicesForResolution.specialize()` might be an interesting avenue.  Maybe the verifier service that accesses could have the `AttachmentsCache` on it ?

2020-06-09 16:40 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
> +    private val cache: AttachmentsCache<Key, SerializationContext> = AttachmentsCacheImpl(CACHE_SIZE)
The reason for using the factory is many fold:

1. The factory allows for the adjustment of cache sizes.
2. The factory decorates the caches with metrics.

2020-06-11 18:56 UTC, adelel1 commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
> +    private val cache: AttachmentsCache<Key, SerializationContext> = AttachmentsCacheImpl(CACHE_SIZE)
Updated, is this what your thinking? (A lot of hoops to jump through!).

2020-06-12 15:50 UTC, rick-r3 commented on node/src/main/kotlin/net/corda/node/utilities/NodeNamedCache.kt
> +                name == "AttachmentsClassLoader_cache" -> caffeine.maximumSize(defaultCacheSize)
Need to think about the default setting.  The class loaders are potentially very big, so the default is probably too many.

2020-06-12 15:50 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/transactions/LedgerTransaction.kt
> +    var attachmentsClassLoaderCache: AttachmentsClassLoaderCache<AttachmentsClassLoaderKey, SerializationContext>? = null
Not sure I like this `var`.  I'm more in favour of it being a `val` like the `verifierFactory` and threading it through that way. Then the `specialise` method on `LedgerTransaction` itself can be used to make a quick copy to inject it.

2020-06-22 15:52 UTC, adelel1 commented on node/src/main/kotlin/net/corda/node/utilities/NodeNamedCache.kt
> +                name == "AttachmentsClassLoader_cache" -> caffeine.maximumSize(defaultCacheSize)
The original cache size was 1000, I figured the new default of 1024 close enough to that.

2020-06-22 15:53 UTC, adelel1 commented on core/src/main/kotlin/net/corda/core/transactions/LedgerTransaction.kt
> +    var attachmentsClassLoaderCache: AttachmentsClassLoaderCache<AttachmentsClassLoaderKey, SerializationContext>? = null
Done. Updated.

2020-06-22 16:35 UTC, chrisr3 commented
run tests: slow

2020-06-22 17:19 UTC, chrisr3 reviewed
My `DeterministicVerifierFactoryService` needed to avoid being checkpointed as part of `LedgerTransaction`. How does your `AttachmentsClassLoaderCache` escape the checkpointer's clutches?

2020-06-22 17:19 UTC, chrisr3 commented on node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
> +                                     ?: AttachmentsClassLoaderCacheImpl(cacheFactory)
Hmm, I see you have not used `tokenize()` for this cache. I dimly recall _needing_ to use `tokenize()` for my `DeterministicVerifierFactoryService` in order to prevent Kryo from trying to include the DJVM inside a checkpoint.

What is preventing Kryo from trying to checkpoint your `AttachmentsClassLoaderCache`?

2020-06-22 17:19 UTC, chrisr3 commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
> +                                              attachmentsClassLoadercache: AttachmentsClassLoaderCache<AttachmentsClassLoaderKey, SerializationContext>?,
The small "c" for `cache` in `attachmentsClassLoadercache` really, _*really*_ bothers me...

2020-06-22 17:19 UTC, chrisr3 commented on node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
> +                                   = djvmCordaSource?.let { AttachmentsClassLoaderSimpleCacheImpl<AttachmentsClassLoaderKey, SerializationContext>() }
Unnecessary generic parameter values for `AttachmentsClassLoaderSimpleCacheImpl`.

2020-06-23 16:04 UTC, chrisr3 requested changes
I have "generics fatigue" after using `AttachmentsClassLoaderCache` too long.

2020-06-23 16:04 UTC, chrisr3 commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
> +}
Do we _really_ need `K` and `V` as generic type parameters here? They will _always_ be:
- `K` = `AttachmentsClassLoaderKey`
- `V` = `SerializationContext`

so why not declare `AttachmentsClassLoaderCache` accordingly?

2020-06-23 16:04 UTC, chrisr3 commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
> +}
Similarly for these two classes which implement `AttachmentsClassLoaderCache`. It looks as if these two classes have been simplified with generic parameters, at the expense of making all of their usages more complicated.

2020-06-23 16:50 UTC, adelel1 commented on node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
> +                                     ?: AttachmentsClassLoaderCacheImpl(cacheFactory)
As you suggested AttachmentsClassLoaderSimpleCacheImpl removed and now tokenize AttachmentsClassLoaderCacheImpl.

2020-06-23 16:50 UTC, adelel1 commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
> +                                              attachmentsClassLoadercache: AttachmentsClassLoaderCache<AttachmentsClassLoaderKey, SerializationContext>?,
I understand. Fixed!

2020-06-23 16:50 UTC, adelel1 commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
> +}
Ok. removed.

2020-06-23 17:00 UTC, chrisr3 requested changes
Little things :grinning:

2020-06-23 17:00 UTC, chrisr3 commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
> +}
You can still use `in` and `out`;
```kotlin
interface AttachmentsClassLoaderCache {
    fun computeIfAbsent(key: AttachmentsClassLoaderKey, mappingFunction: Function<in AttachmentsClassLoaderKey, out SerializationContext>): SerializationContext
}
```

2020-06-23 17:00 UTC, chrisr3 commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
> +class AttachmentsClassLoaderSimpleCacheImpl : SingletonSerializeAsToken(), AttachmentsClassLoaderCache {
This no longer needs to extend `SingletonSerializeAsToken`, and consequently doesn't need `@DeleteForDJVM` either.

2020-06-23 17:10 UTC, chrisr3 commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
> +                                              attachmentsClassLoadercache: AttachmentsClassLoaderCache<AttachmentsClassLoaderKey, SerializationContext>?,
:+1:

2020-06-23 17:30 UTC, adelel1 commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
> +}
Done

2020-06-23 17:30 UTC, adelel1 commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
> +class AttachmentsClassLoaderSimpleCacheImpl : SingletonSerializeAsToken(), AttachmentsClassLoaderCache {
Done

2020-06-23 17:33 UTC, chrisr3 submitted a review, later dismissed
LGTM

2020-06-23 18:19 UTC, chrisr3 commented
run tests: slow

2020-06-26 13:53 UTC, rick-r3 reviewed
Pretty close now.

2020-06-26 13:53 UTC, rick-r3 commented on node/src/main/kotlin/net/corda/node/utilities/NodeNamedCache.kt
> +                name == "AttachmentsClassLoader_cache" -> caffeine.maximumSize(defaultCacheSize)
In ENT the default cache size also resizes based on heap size.  For a 32GB heap the default size becomes about 200,000 I think.

I think 1000 or 1024 are both excessive since I'd expect a class loader to be quite expensive in terms of memory.  I think not many class loaders should be cached by default.  Maybe something as little as 4-16 ?

I was trying to figure out a ratio that makes sense in enterprise also.  defaultCacheSize / 256 ?  So on 32GB VM you get close to 1000, and on OS you get 4.

I do think we should have the ability to override the default with config in ENT.  We have a section in the ENT config for tuning.

2020-06-26 13:53 UTC, rick-r3 commented on node/src/main/kotlin/net/corda/node/migration/MigrationServicesForResolution.kt
> +                    attachmentsClassLoaderCache = null) {
There's a cache factory available.   We should try and use that.

2020-06-26 13:53 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
> +    const val CACHE_SIZE = 1000
I think 1000 is very large.  When do we use the fallback ?  If it is just tests and legacy use of some LedgerTransaction APIs, then we should make the size very small.  See my suggestions for the sizing in the cache factory.

What does the DJVM use?  The one the DJVM uses should be sized differently/configured in ENT at least so if that is using the fallback maybe we need to figure out how to inject one (I appreciate it probably needs so still be `AttachmentsClassLoaderSimpleCacheImpl` just with a different size).

I think one use case during migration below I've suggested we can use a NamedCacheFactory.

2020-06-26 13:53 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
> +    private val fallBackCache: AttachmentsClassLoaderCache = AttachmentsClassLoaderSimpleCacheImpl()
I'd suggest passing the size to the constructor here rather than having `AttachmentsClassLoaderSimpleCacheImpl` refer back to the constant.

2020-07-14 13:08 UTC, adelel1 commented on node/src/main/kotlin/net/corda/node/utilities/NodeNamedCache.kt
> +                name == "AttachmentsClassLoader_cache" -> caffeine.maximumSize(defaultCacheSize)
Currently any non code per transaction attachments get bundled in a class loader, which means there could be many entries in the cache - maybe one per transaction in some scenarios. So this may cause the class loader we really do want to be cached being kicked out of the cache. If we reduce to something smaller it may affect behaviour for existing customers, i.e. some transaction verification is slower.
Once the stuff in first paragraph is resolved (the other work we're doing now), then we can reduce size of cache.
For ENT, it can be made configurable, I can raise JIRA for that.

2020-07-14 13:09 UTC, adelel1 commented on node/src/main/kotlin/net/corda/node/migration/MigrationServicesForResolution.kt
> +                    attachmentsClassLoaderCache = null) {
Done.

2020-07-14 16:54 UTC, adelel1 commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
> +    const val CACHE_SIZE = 1000
I have reduced the size to 16, yes its tests and some legacy LedgerTransaction api.
The DJVM does not use this simple cache implementation, so OK there. @chrisr3 this is what you said previously.

2020-07-14 16:56 UTC, adelel1 commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
> +    private val fallBackCache: AttachmentsClassLoaderCache = AttachmentsClassLoaderSimpleCacheImpl()
Done.

2020-07-14 17:57 UTC, rick-r3 commented on node/src/main/kotlin/net/corda/node/utilities/NodeNamedCache.kt
> +                name == "AttachmentsClassLoader_cache" -> caffeine.maximumSize(defaultCacheSize)
Class loaders are pretty expensive, but not sure _how_ expensive.  Let's reduce this a little (e.g. divide by 4) and raise a JIRA to control it better in Enterprise ?

2020-07-15 11:31 UTC, adelel1 commented on node/src/main/kotlin/net/corda/node/utilities/NodeNamedCache.kt
> +                name == "AttachmentsClassLoader_cache" -> caffeine.maximumSize(defaultCacheSize)
Done. ENT-5485 created.

2020-07-16 08:57 UTC, rick-r3 approved these changes

2020-07-16 08:58 UTC, merged