EG-1561: Allow unordered placement of global options in command line arguments
corda/corda pull request #6343
Opened 2020-06-12 13:27 UTC by palade

This PR updates the version of picocli version and allows for global options `--logging-level` or  `--log-to-console` to be placed in any order regardless of where sub-commands are placed.

# PR Checklist:

- [ ] Have you run the unit, integration and smoke tests as described [here](https://docs.corda.net/head/testing.html)?
- [x ] If you added public APIs, did you write the JavaDocs?
- [ ] If the changes are of interest to application developers, have you added them to the [changelog](https://docs.corda.net/head/changelog.html) (`/docs/source/changelog.rst`), and potentially the [release notes](https://docs.corda.net/head/release-notes.html) (`/docs/source/release-notes.rst`)?
- [ ] If you are contributing for the first time, please read the [contributor agreement](https://docs.corda.net/head/contributing.html) now and add a comment to this pull request stating that your PR is in accordance with the [Developer's Certificate of Origin](https://docs.corda.net/head/contributing.html#merging-the-changes-back-into-corda).

Thanks for your code, it's appreciated! :)

2020-06-15 11:42 UTC, JamesHR3 requested changes
I think we might accidentally be breaking tools that use `cliutils` that aren't node startup, unfortunately. I'm not sure how easy it is to work around this. Either way, I think we'll need to expand our testing with this change to include tools as well as node startup - this is a large change.

2020-06-15 11:42 UTC, JamesHR3 commented on node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt
> +                //initialRegistrationCli.cmdLineOptions.copyFrom(cmdLineOptions)
If we don't need this line let's remove it.

2020-06-15 11:42 UTC, JamesHR3 commented on node/src/main/kotlin/net/corda/node/internal/subcommands/ValidateConfigurationCli.kt
> +internal class ValidateConfigurationCli (): CliWrapperBase("validate-configuration", "Validate the configuration without starting the node.") {
I don't think you need the brackets added here?

2020-06-15 11:42 UTC, JamesHR3 commented on tools/cliutils/src/main/kotlin/net/corda/cliutils/CordaCliWrapper.kt
> -    @Option(names = ["-v", "--verbose", "--log-to-console"], description = ["If set, prints logging to the console as well as to a file."])
I don't think you can remove these from here, as `CliWrapperBase` is used by things other than the node startup commands (see for example the DB migration tool, or the Error tool added in 4.5). Removing this will remove these logging arguments from these tools. We might need to rethink how this works.

2020-06-15 11:42 UTC, JamesHR3 commented on tools/cliutils/src/main/kotlin/net/corda/cliutils/CordaCliWrapper.kt
> +        return false;
This change could also cause a problem for tools other than the node startup options.

2020-06-15 11:42 UTC, JamesHR3 commented on tools/cliutils/src/main/kotlin/net/corda/cliutils/CordaCliWrapper.kt
> +    @Suppress("SpreadOperator")
Out of interest, do you know why this is an extension method in the first place? Isn't `CordaCliWrapper` defined in the same file? I wonder if we can just put the start method in the class definition.

2020-09-17 22:03 UTC, rnicoll commented
@palade Trying to clean up old PRs, is this still in progress or should it be closed?

2020-09-18 08:33 UTC, palade commented
@rnicoll I will close this PR as it got mixed up with other commits and also the proposed solution has been changed. I will open a separate PR for this.

2020-09-18 08:33 UTC, closed without merging