[CORDA-3506] - Implement session close operations
corda/corda pull request #6357
Opened 2020-06-17 08:24 UTC by dimosr

🚧  Work in progress (not ready for review yet) 🚧

2020-06-18 10:43 UTC, dimosr commented
Run tests: slow

2020-06-18 13:40 UTC, rick-r3 commented
I think it is important to realise the session close _must_ checkpoint.  It must not be possible for a flow to retry and start using the session again once the close has  been sent to the peer.  It should only be possible to resend the close.  Thus there needs to be a checkpoint prior to sending the close.

2020-06-18 13:47 UTC, dimosr commented
@rick-r3 yes that's already done here. From a `close()` point-of-view, it's achieved by doing it via calling `suspend` with a `FlowIORequest.CloseSessions`. From the perspective of handling an incoming session-end message, it's done by scheduling a checkpoint & transaction commit before sending session-end messages (see: `StartedFlowTransition.terminateSessions()`.

2020-06-18 13:57 UTC, rick-r3 commented on node/src/main/kotlin/net/corda/node/services/statemachine/transitions/StartedFlowTransition.kt
> +    private fun findSessionsToBeTerminated(flowIORequest: FlowIORequest<*>, startingState: StateMachineState): SessionMap {
I've not really reviewed the whole thing, but this bit doesn't look quite right to me.

The checkpointing rule: It should checkpoint, then mutate.  That way, if there's a failure between the two, we restarted from the checkpoint and re-do the mutate.  In this case the mutate is closing the sessions.  

The way you have it, it looks to me like you would checkpoint with the sessions removed, then try and inform the peers.  If it fails between the two, the peers are never informed perhaps.  In general it is suspicious that it does not adhere to the general pattern of the `when` above.

2020-06-18 14:00 UTC, lankydan commented on core-tests/src/test/kotlin/net/corda/coretests/flows/FlowExternalOperationStartFlowTest.kt
> +            // shadow member variable to avoid fiber serialisation errors
What are the issues with this test? Needs fixing if something is wrong!!

2020-06-18 14:46 UTC, lankydan commented on core/src/main/kotlin/net/corda/core/flows/FlowLogic.kt
> +    fun close(sessions: NonEmptySet<FlowSession>, maySkipCheckpoint: Boolean = false) {
Should we provide an overload which takes in a single session?

Can we allow the checkpoint from being skipped?

2020-06-18 14:46 UTC, lankydan commented on core/src/main/kotlin/net/corda/core/flows/FlowLogic.kt
> +    fun close(sessions: NonEmptySet<FlowSession>, maySkipCheckpoint: Boolean = false) {
I see you do that on the session, i guess the reason for an overload is decreased but it still might make the API easier to work with.

2020-06-18 14:46 UTC, lankydan commented on core/src/main/kotlin/net/corda/core/flows/FlowSession.kt
> +    abstract fun close(maySkipCheckpoint: Boolean)
Can't we use `@JvmOverloads` here?

2020-06-18 14:46 UTC, lankydan commented on node/src/integration-test/kotlin/net/corda/node/flows/FlowSessionCloseTest.kt
> +class FlowSessionCloseTest {
Although im sure there are no issues. Should we trigger a retry to make sure it can handle triggering the session closing event again (retries from checkpoint and plays the event again).

2020-06-18 14:46 UTC, lankydan commented on node/src/main/kotlin/net/corda/node/services/statemachine/StateMachineState.kt
> +     * Returns a cope of the Checkpoint with the specified session removed from the session map.
`cope` should be `copy`?

2020-06-18 14:46 UTC, lankydan commented on node/src/main/kotlin/net/corda/node/services/statemachine/transitions/DeliverSessionMessageTransition.kt
> +    private fun TransitionBuilder.checkIfMissingSessionIsAnIssue(message: ExistingSessionMessage) {
This function name is a bit weird 😄 . Is there a better name for it?

2020-06-18 14:46 UTC, lankydan commented on node/src/main/kotlin/net/corda/node/services/statemachine/transitions/DeliverSessionMessageTransition.kt
> +    private fun TransitionBuilder.checkIfMissingSessionIsAnIssue(message: ExistingSessionMessage) {
If not, then leave it

2020-06-18 14:46 UTC, lankydan commented on node/src/main/kotlin/net/corda/node/services/statemachine/transitions/DeliverSessionMessageTransition.kt
> +    private fun TransitionBuilder.endMessageTransition(state: StateMachineState) {
cant we use the `initialState` instead of passing this in? (value on `TransitionBuilder`)

2020-06-18 14:46 UTC, lankydan commented on node/src/main/kotlin/net/corda/node/services/statemachine/transitions/StartedFlowTransition.kt
> +    private fun findSessionsToBeTerminated(flowIORequest: FlowIORequest<*>, startingState: StateMachineState): SessionMap {
Agreed, we are calling `Action.PersistCheckpoint`, which is handled by `Event.suspend`.

We can do the updating of the checkpoint's/flow's state but we don't need parts around committing anything. That can be handled by the next suspend's db commit.

2020-06-18 14:46 UTC, lankydan commented on node/src/main/kotlin/net/corda/node/services/statemachine/transitions/StartedFlowTransition.kt
> +                                    numberOfSuspends = currentState.checkpoint.checkpointState.numberOfSuspends + 1,
`numberOfSuspends = currentState.checkpoint.checkpointState.numberOfSuspends + 1` can be removed when we rely on the suspend to update the checkpoint.

2020-06-19 08:26 UTC, dimosr commented on core-tests/src/test/kotlin/net/corda/coretests/flows/FlowExternalOperationStartFlowTest.kt
> +            // shadow member variable to avoid fiber serialisation errors
If the member variable is used (as before), it now fails due to fiber serialisation with `ArrayIndexOutOfBoundsException: -1`. See the PR description for some more details.

Looking at how `serviceHub` is used, I initially thought that's kind of expected. But judging from your reaction, I guess it's not.. I'll reset this for now and let the tests fail and we can investigate and decide what we do later on. But, overall I think there's some deeper bug here that was just not manifesting before.

2020-06-19 08:33 UTC, dimosr commented on core/src/main/kotlin/net/corda/core/flows/FlowLogic.kt
> +    fun close(sessions: NonEmptySet<FlowSession>, maySkipCheckpoint: Boolean = false) {
I am just following the existing convention here, i.e.:
* We allow the checkpoint to be skipped in many suspending operations (e.g. `sendAll`, `receiveAll`), but it should only be done at the user's liability assuming the application is built in a way that can function properly without checkpoints.
* In other APIs that can involve one or more sessions, we include operations on a single session on `FlowSession`, but operations on multiple sessions on `FlowLogic`. For example, see `send`/`sendAll`, `receive`/`receiveAll`.

2020-06-19 08:39 UTC, lankydan commented on core-tests/src/test/kotlin/net/corda/coretests/flows/FlowExternalOperationStartFlowTest.kt
> +            // shadow member variable to avoid fiber serialisation errors
Uhhh ye this looks like the error from the jira you linked in the description. I'll take a look at it.

2020-06-19 09:26 UTC, dimosr commented on core/src/main/kotlin/net/corda/core/flows/FlowSession.kt
> +    abstract fun close(maySkipCheckpoint: Boolean)
Thinking about it, I believe we could (and should?).
The main reason I didn't do it is because I noticed the other methods here also perform explicit overloads and I thought there would be a reason. The only reason I can think of at the moment is the problematic evolution of methods with `JvmOverloads` (see `CordaRPCClient` to get an idea...). But, given these methods are expected to be quite static (I don't envision us having to add new parameters), I think we can go with it here.

2020-06-19 09:27 UTC, dimosr commented on node/src/integration-test/kotlin/net/corda/node/flows/FlowSessionCloseTest.kt
> +class FlowSessionCloseTest {
Yes, that would be useful. Do we have any easy way to do this or would I have to mess with byteman?

2020-06-19 09:28 UTC, dimosr commented on node/src/main/kotlin/net/corda/node/services/statemachine/StateMachineState.kt
> +     * Returns a cope of the Checkpoint with the specified session removed from the session map.
indeed, will fix.

2020-06-19 09:32 UTC, dimosr commented on node/src/main/kotlin/net/corda/node/services/statemachine/transitions/DeliverSessionMessageTransition.kt
> +    private fun TransitionBuilder.checkIfMissingSessionIsAnIssue(message: ExistingSessionMessage) {
dunno, seems as intent-revealing as it can get. Always open to suggestions though!

(P.S. The real motivation behind this method really is `detekt` complaining about crossing the cyclomatic complexity budget..)

2020-06-19 09:34 UTC, dimosr commented on node/src/main/kotlin/net/corda/node/services/statemachine/transitions/DeliverSessionMessageTransition.kt
> +    private fun TransitionBuilder.endMessageTransition(state: StateMachineState) {
I assume you mean via `currentState`.. agree, that's probably better and less error-prone for the future.

2020-06-19 10:03 UTC, lankydan commented on node/src/integration-test/kotlin/net/corda/node/flows/FlowSessionCloseTest.kt
> +class FlowSessionCloseTest {
Call `close` and then throw an exception that gets retried after it.

```kotlin
@StartableByRPC
@InitiatingFlow
class TransientConnectionFailureFlow(private val party: Party) : FlowLogic<Unit>() {
    companion object {
        var thrown = false
    }

    @Suspendable
    override fun call() {
        initiateFlow(party).send("hello there")
        // checkpoint will restart the flow after the send
       if (!thrown) {
          thrown = true
          throw SQLTransientConnectionException("Connection is not available")
       }
    }
}
```

Something like that will do it.

2020-06-19 12:52 UTC, dimosr commented on node/src/main/kotlin/net/corda/node/services/statemachine/transitions/StartedFlowTransition.kt
> +    private fun findSessionsToBeTerminated(flowIORequest: FlowIORequest<*>, startingState: StateMachineState): SessionMap {
Sharing some thoughts here (some of them discussed with Rick offline, but posting for visibility):
* The way it's done here it's indeed unsafe, it was an oversight. Originally the idea was to send session-end messages symmetrically (with the future message/session redesign), so that the messaging layer can observe session termination in all cases and perform the associated cleanup. This looked a bit better from a design/reasoning perspective, but it's suboptimal from a performance perspective and it can cause significantly more traffic. So, we agreed with Rick that it's probably a better idea to expose an API on the messaging layer, so that the state machine can inform about session termination. This would mean in optimal cases only one session-end is sent (there will still be cases, where two are sent when both sides terminate concurrently). It would also simplify a lot the logic here. Specifically, the `terminateSessions` method will only need to (i) register deduplication handlers for the session-end messages in the checkpoint (i) remove session bindings. Persistence of the new checkpoint/handlers & message acknowedgement will be performed automatically on the next suspension point.
* The reason session close is implemented via the conditional in the beginning of `transition()`, instead of embedding it inside the existing `when` is mostly because it makes it easier to maintain and reason about. The way it's done now, sessions that need to be terminated will be closed as part of a separate transition. This means that we don't have to go and update all the other transition methods to contain the same logic. It will also keep working if new transitions are introduced without any more changes needed.

Regarding the following points:
> we are calling `Action.PersistCheckpoint`, which is handled by `Event.suspend`.

I don't think that's right, it's the other way around. `Event.Suspend` triggers an `Action.PersistCheckpoint`, but execution of this action is separate and does not lead to scheduling of an `Event.Suspend`. It also doesn't mean this action cannot be triggered by other events too.

> We can do the updating of the checkpoint's/flow's state but we don't need parts around committing anything. That can be handled by the next suspend's db commit.

I think in this form, the separate checkpoint was needed, because we needed to make sure that data messages cannot be replayed after having sent session end messages. However, now that we won't be sending additional session-end messages, the checkpoint can be skipped.

2020-06-19 14:18 UTC, dimosr commented on node/src/main/kotlin/net/corda/node/services/statemachine/transitions/StartedFlowTransition.kt
> +    private fun findSessionsToBeTerminated(flowIORequest: FlowIORequest<*>, startingState: StateMachineState): SessionMap {
Actually, populating the pending dedup handlers is probably not needed here at all, since it's done automatically on `DeliverSessionMessageTransition`.

2020-06-19 14:44 UTC, dimosr commented on node/src/main/kotlin/net/corda/node/services/statemachine/transitions/StartedFlowTransition.kt
> +                                    numberOfSuspends = currentState.checkpoint.checkpointState.numberOfSuspends + 1,
see comment above - this was needed to ensure data messages and subsequent session-end messages (triggered from session-ends) would not have the same sequence number in the message ID.

This will go away now anyway, since we won't send additional session-ends here.

2020-06-19 15:40 UTC, dimosr commented on core/src/main/kotlin/net/corda/core/flows/FlowSession.kt
> +    abstract fun close(maySkipCheckpoint: Boolean)
ah, it seems there's a reason:
```
'@JvmOverloads' annotation cannot be used on abstract methods
```

2020-06-19 15:41 UTC, lankydan commented on core/src/main/kotlin/net/corda/core/flows/FlowSession.kt
> +    abstract fun close(maySkipCheckpoint: Boolean)
ah, fair enough (TIL)

2020-06-22 08:46 UTC, dimosr commented on node/src/main/kotlin/net/corda/node/services/statemachine/transitions/StartedFlowTransition.kt
> +    private fun findSessionsToBeTerminated(flowIORequest: FlowIORequest<*>, startingState: StateMachineState): SessionMap {
This is now changed based on my comments above and it's really small - just removing the session bindings and sessions from checkpointing and continues with the next transitions relying on the next checkpoint to persist the changes & acknowledge handlers (the pending handlers are populated when delivering the session-end message automatically).

2020-06-23 12:28 UTC, lankydan reviewed
I think the idea of this pr makes sense to me now and looks good. I've left some tidy up comments, that can be skipped if they don't seem useful.

2020-06-23 12:28 UTC, lankydan commented on node/src/integration-test/kotlin/net/corda/node/flows/FlowSessionCloseTest.kt
> +    fun `flow looping over sessions can close them to release resources and avoid out-of-memory failures, when the other side does not finish early`() {
Is it worth having a test that asserts that the sessions in `CheckpointState` are removed? I guess that this test is basically doing that.

If we were going to add this extra test, we would need to have a hook inside the flow that accesses the fiber and returns the number of sessions related to the flow. Which passes if it has decreased as expected.

2020-06-23 12:28 UTC, lankydan commented on node/src/main/kotlin/net/corda/node/services/statemachine/transitions/StartedFlowTransition.kt
> +            val alreadyClosedSessions = sessionIdsToRemove.filter { sessionId ->
Took me a while to realise what this was doing (possible brain fart). When doing so, wondered if either of these are clearer:

```kotlin
val alreadyClosedSessions = sessionIdsToRemove.filterNot(existingSessionsToRemove::contains) // could use ::containsKey as well

val alreadyClosedSessions = sessionIdsToRemove.filterNot { sessionId -> sessionId in existingSessionsToRemove }

val alreadyClosedSessions = sessionIdsToRemove.filter { sessionId -> sessionId !in existingSessionsToRemove }
```

2020-06-23 12:28 UTC, lankydan commented on node/src/main/kotlin/net/corda/node/services/statemachine/transitions/DeliverSessionMessageTransition.kt
>          override val startingState: StateMachineState,
I know its not part of the PR but would you be happy with changing the name of this transition to `DeliveredSessionMessageTransition` or `ReceivedSessionMessageTransition? Anything to show that it is to do with incoming messages, not delivering a message. This name confused me a lot before I had a proper look into this class. We don't have to do it now, but would be nice to get other peoples thoughts.

2020-06-23 12:28 UTC, lankydan commented on node/src/main/kotlin/net/corda/node/services/statemachine/transitions/DeliverSessionMessageTransition.kt
> +            freshErrorTransition(CannotFindSessionException(event.sessionMessage.recipientSessionId))
Worth adding a log line here for the missing session? `warn`?

2020-06-23 12:28 UTC, lankydan commented on core/src/main/kotlin/net/corda/core/internal/FlowIORequest.kt
> +    data class CloseSessions(
Formatting this onto a new line seems pointless

2020-06-23 12:28 UTC, lankydan commented on core/src/main/kotlin/net/corda/core/flows/FlowLogic.kt
> +     * To prevent misuse of the API, if there is an attempt to close an uninitialised session the invocation will fail with an [IllegalStateException].
Very thorough KDoc :thumbsup

2020-06-23 12:28 UTC, lankydan commented on node/src/integration-test/kotlin/net/corda/node/flows/FlowSessionCloseTest.kt
> +
If we are going to support `close` skipping checkpointing, we should have tests (maybe duplicates of these tests) that `close` and skip the checkpoint.

2020-06-23 13:28 UTC, dimosr commented on node/src/main/kotlin/net/corda/node/services/statemachine/transitions/StartedFlowTransition.kt
> +            val alreadyClosedSessions = sessionIdsToRemove.filter { sessionId ->
yeah, I think the last one is a bit more clean. I'll switch to that.

2020-06-23 13:31 UTC, dimosr commented on node/src/main/kotlin/net/corda/node/services/statemachine/transitions/DeliverSessionMessageTransition.kt
>          override val startingState: StateMachineState,
The `Deliver` part is because this transition essentially delivers a message from the messaging layer to the state machine.

2020-06-23 13:35 UTC, dimosr commented on node/src/main/kotlin/net/corda/node/services/statemachine/transitions/DeliverSessionMessageTransition.kt
> +            freshErrorTransition(CannotFindSessionException(event.sessionMessage.recipientSessionId))
not sure. Why warn, since we are going to error anyway?

2020-06-23 13:36 UTC, lankydan commented on node/src/main/kotlin/net/corda/node/services/statemachine/transitions/DeliverSessionMessageTransition.kt
> +            freshErrorTransition(CannotFindSessionException(event.sessionMessage.recipientSessionId))
after checking where the exception is used, i guess we could skip logging. Since the flow will end and log it from there anyway.

2020-06-23 13:40 UTC, dimosr commented on node/src/integration-test/kotlin/net/corda/node/flows/FlowSessionCloseTest.kt
> +
sure. I think duplicating all of the tests is slightly overkill and will have an impact on overall test duration (e.g. imagine what would happen if we tested all APIs that support skipping checkpoints for all the possible cases..). So, I'll just add a test for the happy path that skips the checkpoints as a sanity check.

2020-06-23 15:45 UTC, dimosr commented on node/src/integration-test/kotlin/net/corda/node/flows/FlowSessionCloseTest.kt
> +    fun `flow looping over sessions can close them to release resources and avoid out-of-memory failures, when the other side does not finish early`() {
Yes, this test is testing this plus the fact that there is no additional metadata left over for sessions that are terminated that can cause issues, such as out-of-memory errors.

I am not convinced whether it'd be worth doing that, since the part of the contract we care about is essentially tested already and these tests would probably end up being quite coupled to implementation (that might change) and thus brittle.

2020-06-24 10:59 UTC, dimosr commented on core/src/main/kotlin/net/corda/core/internal/FlowIORequest.kt
> +    data class CloseSessions(
agree, will put everything in a single line.

2020-06-25 15:08 UTC, lankydan commented on node/src/integration-test/kotlin/net/corda/node/flows/FlowSessionCloseTest.kt
> +
What im more interested in, is that it works correctly when being retried without checkpointing when closing the session. Would be better to have a single test for that, instead of the happy path one.

2020-06-25 15:27 UTC, dimosr commented on node/src/integration-test/kotlin/net/corda/node/flows/FlowSessionCloseTest.kt
> +
sure, I can switch this test to be the one with the retries. However, remember that the concept of _correctness_ is a bit fuzzy and application-specific, when skipping checkpoints.

2020-07-02 11:05 UTC, lankydan submitted a review, later dismissed
I think you've addressed all my feedback, so LGTM

2020-07-03 07:26 UTC, rick-r3 requested changes

2020-07-03 07:26 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/flows/FlowLogic.kt
> +    fun close(sessions: NonEmptySet<FlowSession>, maySkipCheckpoint: Boolean = false) {
I don't think we should offer `maySkipCheckpoint`.  I don't think there are any scenarios where it is valid to set it to `true`.  In fact I think we should get @lankydan to make the state machine ignore it in the internals.

We included it right from the beginning on Corda APIs thinking it was useful, but I don't think it is and is actually just dangerous.

2020-07-03 07:26 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/flows/FlowSession.kt
> +    abstract fun close(maySkipCheckpoint: Boolean)
No need for `maySkipCheckpoint`.

2020-07-03 07:27 UTC, rick-r3 commented
Oh, I pressed the wrong button.  Was trying to make a further comment.

2020-07-03 07:48 UTC, rick-r3 commented
I'm not convinced :-)

I was trying to work out why this isn't more elegant.  I a) noticed a bug with this approach and b) in attempt to think about how to fix that, figured out a way to maybe make it more elegant but c) think it maybe highlights and existing bug.

Here's the bug in your approach I think (of course I might be misreading it).  Let's say node B sends 2 messages and a close.  I think node A can process that close ahead of the other messages, because the data messages are buffered whereas the close is not (it might just be delayed due to a "current" FlowIORequest - which is where I think it's not so elegant).

I think a more elegant and easier to get correct model is to modify `SessionState.Initiated.receivedMessages` to handle any `ExistingSessionMessagePayload` like `SessionState.Initiating.bufferedMessages` does rather than just `DataSessionMessage`.  We can then queue the messages in order of receipt.   There's obviously work to do to process that buffer appropriately.   Perhaps if the buffer is empty on close or error you can continue to process immediately.  I don't think there should be a need to avoid closing sessions for an inflight send or receive FlowIORequest.

The current bug (before your change) is that we will process errors early, before we finish processing any `receivedMessages` which could be very confusing, because they don't have this buffering logic either.  We'd probably want to make those buffered like the close/end as it will be easier to understand when debugging flows this way I think.

Note, in the blurb on this PR you talk about messages arriving out of order.  Currently one of the requirements for Corda to work is that they are not out of order, so we don't need to think about that element at all for now.

2020-07-03 07:53 UTC, dimosr commented on core/src/main/kotlin/net/corda/core/flows/FlowLogic.kt
> +    fun close(sessions: NonEmptySet<FlowSession>, maySkipCheckpoint: Boolean = false) {
yeah, as I said to Dan I mostly added it for consistency with the rest of the API. Agree with the fact that it's not safe, will remove the option.

2020-07-03 08:23 UTC, dimosr commented
Yes, my main assumption was message re-ordering is considered a possibility, which would mean there would be no way to build this in a bullet-proof way without the contiguous sequence numbers. If we assume there's no such possibility, then it all gets much easier.

a) In the current approach, it's explicitly called out to the user that the `close` should be performed only from the side that performs the last receive. This was done essentially with the above in mind to provide the most bullet-proof solution. Of course, there's no (easy) way at the moment to protect against misuse of this aspect.

b & c) Agree, this is actually how I went about it in the PoC for the redesign. The main difference there was I had the contiguous sequence number in place. But, assuming messages are delivered in order, then we can just append the error messages to the buffer (instead of prepending it, as currently) and process them in order from the buffer. As you said, this would also mean we don't have to check what flow IO request we are suspended at. I'll have a go at it.

2020-07-03 11:33 UTC, rick-r3 commented
Yeah, for now we have to assume no message re-ordering.  We want to get to a place where we might be able to fix the ordering in the future.

2020-07-03 11:39 UTC, mnesbit commented on core/src/main/kotlin/net/corda/core/flows/FlowSession.kt
> +    abstract fun close(maySkipCheckpoint: Boolean)
Seconded, maySkipCheckpoint is a problem waiting to happen. We should not add any more to our API. The only place that safely uses it is notary client in an internal use case that we know is idempotent.

2020-07-06 10:25 UTC, dimosr commented on core/src/main/kotlin/net/corda/core/flows/FlowLogic.kt
> +    fun close(sessions: NonEmptySet<FlowSession>, maySkipCheckpoint: Boolean = false) {
removed

2020-07-06 10:25 UTC, dimosr commented on core/src/main/kotlin/net/corda/core/flows/FlowSession.kt
> +    abstract fun close(maySkipCheckpoint: Boolean)
removed

2020-07-06 10:25 UTC, dimosr commented
@rick-r3 refactored to the buffer-based approach, ready for another look

2020-07-08 14:39 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/flows/FlowSession.kt
> +    abstract fun close()
A couple of additional thoughts:

1. If a session is closed, it should remember it is closed and throw some kind of exception when any of the other methods are called.  Might need to be unchecked exception for Java API compatibility.
2.Maybe add an `isClosed` to find out.

2020-07-08 14:39 UTC, rick-r3 commented on node/src/main/kotlin/net/corda/node/services/statemachine/FlowSessionImpl.kt
> +
See my comment on the interface.

Do you think we should try and do something for current applications that discard sessions or future ones that forget to call `close` ?  e.g. We could keep the session in a `WeakHashMap` so they can be garbage collected (with a `finalize` that closes perhaps), but currently a discard session is not closed.

2020-07-08 14:39 UTC, rick-r3 commented on node/src/main/kotlin/net/corda/node/services/statemachine/transitions/ErrorFlowTransition.kt
> +            if (session is SessionState.Initiated && session.receivedMessages.none { it is ErrorSessionMessage }) {
Candidate for a method on session itself, since repeated below ?

eg. `isReceivedErrorMessagePending`

2020-07-08 14:39 UTC, rick-r3 commented on node/src/main/kotlin/net/corda/node/services/statemachine/transitions/StartedFlowTransition.kt
> +        val sessionsToBeTerminated = findSessionsToBeTerminated(startingState)
This just feels a bit clunky.  Scanning through N sessions on each transition just in case they have ended.

At the very least, every time you mutate `receivedMessages` for a session, you could check if the head of the `receivedMessages` was error or close and add a (potentially new) Action to tidy them up.  That way only sessions that need checking are checked, and only when they see message activity.

Also, do you need a new method / action (`removeSessions`) or should that removal be done as part of `Action.RemoveSessionBindings` logic ?

2020-07-08 14:56 UTC, dimosr commented on core/src/main/kotlin/net/corda/core/flows/FlowSession.kt
> +    abstract fun close()
1. This is already done, as explained by the docs above. An `UnexpectedFlowEndException` exception is thrown in this case. However, your comment made me realise there's one API that was missed in these checks (`getCounterpartyFlowInfo`), so I'll include this too.
2. I'd prefer to avoid adding an `isClosed` method to keep API surface as small as possible. The `close` is supposed to be called at a point after which the session is not going to be used anymore. Not doing this would be an improper use of the API, so we'd be throwing an exception. The developer should really never have to check if a session is closed programmatically.

2020-07-08 14:57 UTC, dimosr commented on node/src/main/kotlin/net/corda/node/services/statemachine/transitions/ErrorFlowTransition.kt
> +            if (session is SessionState.Initiated && session.receivedMessages.none { it is ErrorSessionMessage }) {
sure, will add.

2020-07-08 15:03 UTC, dimosr commented on node/src/main/kotlin/net/corda/node/services/statemachine/FlowSessionImpl.kt
> +
In principle, it sounds like a good idea. But, I am afraid it might complicate things a bit more and the original motivation for this work was mostly the pattern of looping over many sessions, which now has a solution in the form of the explicit `close` API. So, could we deliver the _implicit_ cleanup as a separate item to keep things simple for now?

2020-07-08 15:23 UTC, dimosr commented on node/src/main/kotlin/net/corda/node/services/statemachine/transitions/StartedFlowTransition.kt
> +        val sessionsToBeTerminated = findSessionsToBeTerminated(startingState)
hmm, I gave it some thought. Initially, I gravitated towards agreeing on the first part, but eventually I ended up disagreeing. The main reason is the way it is currently structured, the logic is centralised. If we move this to be done at every place a mutation of the received messages is performed, I think it gets harder to track and error-prone (e.g. someone adds some new logic mutating the messages, but forgets to check for closed sessions etc). From a performance perspective, all this scanning is done in memory, so it shouldn't cause issues given bottlenecks are elsewhere. It's also important to note that the logic for errors follows the same logic (see `collectRelevantErrorsToThrow` just above).

On the second point, there are two things that are done here (inside `terminateSessions`):
* the sessions are removed from the checkpoint by mutating the checkpoint state
* the sessions are removed from the state machine's bindings (that's done by the `Action.RemoveSessionBindings`)

So, that should be all, unless you refer to something else different to the above?

2020-07-10 08:53 UTC, rick-r3 commented on node/src/main/kotlin/net/corda/node/services/statemachine/transitions/StartedFlowTransition.kt
> +        val sessionsToBeTerminated = findSessionsToBeTerminated(startingState)
There's a finite number of places we mutate the `receivedMessages`.  If we want to centralise it, we could use a custom class to encapsulate them (rather than raw `List`) so that the scan is forced upon access.  Maybe there's a compromise here where we just keep track of what needs scanning (i.e. which sessions have been modified since last scan) via the encapsulation.

I really don't like the in-memory scan through all the sessions on each transition.  We have customers with 40,000 open sessions in a single flow.  In theory it is fast, but it's super inefficient when we clearly know which sessions need scanning.

2020-07-10 09:05 UTC, dimosr commented on node/src/main/kotlin/net/corda/node/services/statemachine/transitions/StartedFlowTransition.kt
> +        val sessionsToBeTerminated = findSessionsToBeTerminated(startingState)
Oh, ok yes 40,000 is 3 orders of magnitude higher than what I had in mind.. it makes full sense in this case.
I also like the idea of enforcing this via a custom class. I'll give it a go.

2020-07-13 08:20 UTC, dimosr commented on node/src/main/kotlin/net/corda/node/services/statemachine/transitions/StartedFlowTransition.kt
> +        val sessionsToBeTerminated = findSessionsToBeTerminated(startingState)
So, I worked on the code and ended up selecting a slightly different approach to reduce the size of the scanning. I added a field on the checkpoint that keeps hold of the sessions that have pending session end messages, so we scan only what's necessary.

I initially tried the original idea we discussed with the custom class and the injection of logic on mutation, but it didn't play nicely. One reason is logic would have to be injected on non-mutation accesses as well (e.g. when consuming a regular message, checking whether the next one is a session-end) and this became quite complex and a bit hard to enforce at the API level. It also required returning `Action`s from access methods, which should then be scheduled by the caller. Besides not being completely bullet-proof, this was becoming a bit hard to reason about, since actions could be injected in the middle of the other actions that were scheduled in-order as part of the transition until now.

2020-07-13 10:56 UTC, mnesbit commented on core/src/main/kotlin/net/corda/core/internal/FlowIORequest.kt
> +    data class CloseSessions(val sessions: NonEmptySet<FlowSession>): FlowIORequest<Unit>()
Don't forget to make sure platform version goes up for this new flow api (may already be for other work, but lets check)

2020-07-13 11:37 UTC, dimosr commented on core/src/main/kotlin/net/corda/core/internal/FlowIORequest.kt
> +    data class CloseSessions(val sessions: NonEmptySet<FlowSession>): FlowIORequest<Unit>()
Good point, thanks for the reminder. It seemed to still be the same, so I bumped it.

2020-07-14 08:51 UTC, rick-r3 commented on constants.properties
> +platformVersion=8
Yes!  We need to do this anyway and I keep forgetting.

2020-07-14 08:51 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/flows/FlowLogic.kt
> +        val request = FlowIORequest.CloseSessions(sessions.toNonEmptySet())
Is that `toNonEmptySet()` required given is already a non-empty set?

2020-07-14 08:51 UTC, rick-r3 commented on node/src/main/kotlin/net/corda/node/services/statemachine/FlowSessionImpl.kt
> +
Yeah, it starts off sounding like a nice idea to get a free win for existing applications, but then you realise it's going to actually be quite complex I think.  And testing anything GC-triggered not exactly easy.

2020-07-14 08:51 UTC, rick-r3 commented on node/src/main/kotlin/net/corda/node/services/statemachine/transitions/StartedFlowTransition.kt
> +        val sessionsToBeTerminated = findSessionsToBeTerminated(startingState)
This looks better.  Main thing was to know in advance what sessions to look at and that has been achieved.

Is the sequencing of this correct w.r.t. resilience?  Probably questioned this originally but worth I final thought. Just trying to model it in my head!  We should get @lankydan to think about it too, but I think this is correct.

1. End messages received and buffered.
1. Reach next suspension point.
1. Tidy up sessions
1. Persist checkpoint
1. Ack messages (so won't redeliver)

I think that means if we fail to checkpoint, the End messages are still out there and redelivered if replay from last checkpoint.  If we succeed in checkpointing, we'll ack the messages so they don't re-deliver.  If there's a failure between checkpoint and ack, the End messages will replay but for unknown sessions so they do nothing.

Seems good to me.

2020-07-14 08:51 UTC, rick-r3 commented on node/src/main/kotlin/net/corda/node/services/statemachine/transitions/StartedFlowTransition.kt
> +                                val errorMessage = sessionState.receivedMessages.first() as ErrorSessionMessage
Seems "correct" for us to consume the error message out of the buffer rather than leaving it in there.  I think there might be a code path that means the flow somehow staggers on when errored and not consuming the error messages causes it to get stuck erroring forever.

If I look at the call path to here, it's basically coming from the same bit of code you process session End messages (and remove them from the buffer).  I think we should be doing something similar with session Error messages, perhaps by passing in the `startingState` not just the checkpoint, and returning a revised state + errors and not just errors.

2020-07-14 08:53 UTC, lankydan commented
Before I forget, do we need to add these new functions to the `current-api.txt` file thingy?

2020-07-14 08:56 UTC, fowlerrr commented on constants.properties
> +platformVersion=8
If we want to go forward with the idea of "per release updating" shouldn't it just become part of the release process?  Then it should always be remembered (like updating the version number)

2020-07-14 09:01 UTC, rick-r3 commented on node/src/main/kotlin/net/corda/node/services/statemachine/transitions/StartedFlowTransition.kt
> +                                val errorMessage = sessionState.receivedMessages.first() as ErrorSessionMessage
Plausibly I'm wrong about this though.  What did we do with errors before?  Did they ever get cleared?  Perhaps we shouldn't have meddled with the error handling... symmetry of the problem seemed appealing but it might just be a can of worms and we should leave it alone?

2020-07-14 09:10 UTC, mnesbit commented
api-current.txt is meant to be regenerated after a release in the new branch. i.e. it protects API of released version, not API of unreleased working branch.

2020-07-14 09:12 UTC, dimosr commented on constants.properties
> +platformVersion=8
I think it's a bit more nuanced, since there might be cases where we want to bump it eagerly before the release is cut (e.g. if we want to introduce gating as part of a feature). But, I agree we need to have some final check that this has been bumped, when needed. It's not the first time we almost forgot - it's easier to forget when you don't need to use it for gating.

Maybe we can introduce some explicit checks as part of the release process?

2020-07-14 09:30 UTC, dimosr commented on core/src/main/kotlin/net/corda/core/flows/FlowLogic.kt
> +        val request = FlowIORequest.CloseSessions(sessions.toNonEmptySet())
indeed, it shouldn't be. It's probably a leftover, I'll remove.

2020-07-14 12:16 UTC, dimosr commented on node/src/main/kotlin/net/corda/node/services/statemachine/transitions/StartedFlowTransition.kt
> +                                val errorMessage = sessionState.receivedMessages.first() as ErrorSessionMessage
Yes, it would make sense conceptually. Practically, I think it does not make a big difference for session error messages specifically, because `StartedFlowTransition` (and thus all this logic) is not going to be executed again. If there are any errors here, this is going to lead to the following sequence of events:
* `FlowContinuation.Throw`
* exception thrown that exits the event loop
* exception picked up and an `Event.Error` scheduled
* `TopLevelTransition` handling the event by transitioning the flow to an errored state. This essentially guarantees we will not re-enter `StartedFlowTransition` from now on.
* Then the flow goes to hospital, error is untreatable and propagated, flow finishes etc.

Let me try and remove the error messages from the buffers and see what's in the can - worst case, we'll just close it back!

2020-07-14 13:31 UTC, dimosr commented on node/src/main/kotlin/net/corda/node/services/statemachine/transitions/StartedFlowTransition.kt
> +                                val errorMessage = sessionState.receivedMessages.first() as ErrorSessionMessage
P.S.: In the previous state, it was similar to how it is now, the error flag field was not reset.

2020-07-14 17:10 UTC, rick-r3 commented on node/src/main/kotlin/net/corda/node/services/statemachine/transitions/TransitionBuilder.kt
> +class PrematureSessionClose(sessionId: SessionId): IllegalStateException("The following session was closed before it was initialised: $sessionId")
I think stylistically we should have exceptions end in `...Exception`

2020-07-14 17:10 UTC, rick-r3 commented on node/src/main/kotlin/net/corda/node/services/statemachine/transitions/StartedFlowTransition.kt
> +                return collectErroredSessionErrors(startingState, startingState.checkpoint.checkpointState.sessions.keys)
@lankydan I would argue that this should not scan for session errors as it doesn't relate to any sessions (as neither does `Sleep` etc).  Instead it is scanning all the sessions, which is suboptimal if there's lots of sessions, and it would be better to just be consistent for non-session related suspensions.  Can you raise a JIRA (won't ask Dimos to do it here in case there's complications)?

2020-07-14 18:27 UTC, lankydan commented on node/src/main/kotlin/net/corda/node/services/statemachine/transitions/StartedFlowTransition.kt
> +                return collectErroredSessionErrors(startingState, startingState.checkpoint.checkpointState.sessions.keys)
Note I'm making this comment without fully looking into the code.

Since it waits for a transaction to be committed. Does this mean that the behaviour it currently has, is if an exception is sent to this node before the transaction it is waiting for commits, it will fail with the sent exception? If that is the case, I kind of feel that is the right behaviour.

I'll have a think and double-check the code.

2020-07-15 07:19 UTC, dimosr commented on node/src/main/kotlin/net/corda/node/services/statemachine/transitions/TransitionBuilder.kt
> +class PrematureSessionClose(sessionId: SessionId): IllegalStateException("The following session was closed before it was initialised: $sessionId")
yes, my omission, will add the suffix.

2020-07-15 07:42 UTC, dimosr commented on node/src/main/kotlin/net/corda/node/services/statemachine/transitions/StartedFlowTransition.kt
> +                return collectErroredSessionErrors(startingState, startingState.checkpoint.checkpointState.sessions.keys)
I think the decision on this has a lot to do with the semantics we want to give on error propagation. Currently, we've decided to let exceptions flow even to sessions that are unused. The common example of finality partial errors is one case where that might help, but not in a consistent way (since it's subject to race conditions on the initiator, i.e. how fast it reaches the end of the flow compared to how quickly counterparties reach the problematic point in the flow).

If we assume that the application has the proper flow-level acknowledgements, when needed, then I think we can remove this scanning. I am on the fence, but I think it might actually be a good decision, the semantics are going to be a bit cleaner (you see errors from counterparties only when you interact with the corresponding sessions) and the behaviour more deterministic and less subject to race conditions.

2020-07-15 08:26 UTC, lankydan commented on node/src/main/kotlin/net/corda/node/services/statemachine/transitions/StartedFlowTransition.kt
> +                return collectErroredSessionErrors(startingState, startingState.checkpoint.checkpointState.sessions.keys)
It would mean though, assuming the behaviour we stated is what it is actually doing. If we remove the collection of errors when a flow is waiting for a ledger commit, the only way for this flow to end is in the successful committing of the transaction.

If this transaction is never received and committed, this flow will not end and will need to be killed.

If the collection of errors is kept, there is a way for a counter party node to experience an error and be able to indicate that to the node waiting for the transaction commit.

2020-07-15 10:31 UTC, dimosr commented on node/src/main/kotlin/net/corda/node/services/statemachine/transitions/StartedFlowTransition.kt
> +                return collectErroredSessionErrors(startingState, startingState.checkpoint.checkpointState.sessions.keys)
I think it's a bit more subtle than that. Let's look at two more concrete use cases:
* A scenario where `waitForLedgerCommit` is invoked from participants already invoked in the flow that drives this transaction. It seems to me in most of these cases, `waitForLedgerCommit` is not really the right API to use. The initiator can rely on the return of `FinalityFlow` for the same things and the counterparties on the return of `ReceiveFinalityFlow`. So, any errors should be propagated as part of the send/receives of these flows.
* A scenario where `waitForLedgerCommit` is invoked from an unrelated, secondary flow. I think this is the most appropriate use of this API, i.e. to act as barrier across flows. In this case, `waitForLedgerCommit` will **not necessarily** error if the flow driving the original flow fails (since its flow does not contain these sessions), it can still remain blocked there until the flow is killed. 

The main difference is that in the current implementation `waitForLedgerCommit` will error quickly if one of this flow's sessions error (for reasons probably unrelated to the transaction it's waiting on), while making the suggested changes would mean these errors would flow only on the next interaction with these sessions.

2020-07-15 10:57 UTC, rick-r3 commented on node/src/main/kotlin/net/corda/node/services/statemachine/transitions/StartedFlowTransition.kt
> +                return collectErroredSessionErrors(startingState, startingState.checkpoint.checkpointState.sessions.keys)
I was really looking for some consistency.  We don't process session errors when we sleep or other "non-messaging" related `FlowIORequests`.  So `waitForLedgerCommit` is an oddity right now.   And maybe it's weird to have things that have nothing to do with messaging throwing exceptions to do with messaging.

2020-07-15 11:04 UTC, rick-r3 commented
I think this is okay.  Yeah, the error handling is/was a bit odd because, like you say, we divert immediately into the error transition stuff and the state of stuff doesn't matter any more.  

There's a subtle change here, and that is errors will queue behind other types of messages.  I think this is an important improvement, because if we start returning errors about "I don't recognise this session", those could previously overtake the close messages and actually generate an error that doesn't exist.  @lankydan Do we have a story about sending back such errors when a session is not recognised?  Vaguely recall the existence of it.  Is it in 4.6 or later ?

2020-07-15 11:31 UTC, dimosr commented on node/src/main/kotlin/net/corda/node/services/statemachine/transitions/StartedFlowTransition.kt
> +                                val errorMessage = sessionState.receivedMessages.first() as ErrorSessionMessage
I added clearing of the error messages after processing. It seems to work fine, I only had to introduce a new flag to indicate the error originated on the other side to avoid propagating error messages again.

P.S.: A cursory look at the existing code on `ErrorFlowTransition` makes me believe that we might be a bit inconsistent there, i.e. there might be cases we are propagating error messages twice and others (like this one) where we don't, but probably something to look at a separate investigation, if we need.

2020-07-16 13:28 UTC, dimosr commented
Looking at the current code (in the state machine manager), incoming messages for non-existent sessions are just discarded without propagating any error.

2020-07-16 13:59 UTC, lankydan commented on node/src/main/kotlin/net/corda/node/services/statemachine/transitions/StartedFlowTransition.kt
> +                return collectErroredSessionErrors(startingState, startingState.checkpoint.checkpointState.sessions.keys)
Yeah, ok, based on what @dimosr stated, I think we should be ok to remove the session collection here.

2020-07-16 14:31 UTC, lankydan commented on node/src/main/kotlin/net/corda/node/services/statemachine/transitions/StartedFlowTransition.kt
> +        val sessionsToBeTerminated = findSessionsToBeTerminated(startingState)
I think we are good.

- We are checkpointing before cleanup as we do not substitute out the suspend event.
- The next event (that actual suspending event, send/receive etc...) is highjacked to clean up the sessions
- The original event plays
- We then checkpoint when we reach the next suspend and acknowledge the messages/events

If we fail at any point (after the first suspend) then we have not persisted anything or acknowledged any messages. If we fail before the first suspend then we are good as well (we didnt change any code around this).

> If there's a failure between checkpoint and ack, the End messages will replay but for unknown sessions so they do nothing.

Bit confused about what situation we are talking about here as i dont see it very likely that we fail here. Or I have misunderstood something.

2020-07-16 15:05 UTC, lankydan commented
> Do we have a story about sending back such errors when a session is not recognised? Vaguely recall the existence of it. Is it > in 4.6 or later ?

@rick-r3 There is this story https://r3-cev.atlassian.net/browse/CORDA-3199

2020-07-20 10:18 UTC, rick-r3 approved these changes

2020-07-20 10:45 UTC, vkolomeyko approved these changes

2020-07-21 12:21 UTC, lankydan approved these changes

2020-07-21 12:26 UTC, merged