EG-2294 Request Membership flow implementation
corda/corda pull request #6364
Opened 2020-06-17 16:14 UTC by tubibuto

## Description

This is the second PR in the series of membership management flow PRs. We build on top of [Create Business Network flow PR](https://github.com/corda/corda/pull/6363) to introduce flow for requesting membership inside Business Network.

First we implement `RequestMembershipFlow` flow which takes `authorisedParty` that is responsible for building membership issuance transaction and distributing to the other authorised members of the Business Network and requesting party. It also takes `networkId` so that authorised party know which network the new potential member wants to join (`authorisedParty` may be member of multiple Business Networks).

The workflow is the following:
- Initiator (requesting party) sends `networkId` to authorised member
- Responder (authorised member) checks whether it's authorised to activate membership
- Responder builds transaction and sends it for signing to initiator
- Responder finalised transaction and sends it to initiator and all the other members authorised to modify membership

We decide to introduce abstract class `MembershipManagementFlow` which contains useful helper methods that any membership management flow can use for convenience and minimisation of code duplication, hence less chance of failure.

We also introduce `BNMemberAuth` which holds authorisation methods and implement 2 concrete implementations for centralised and decentralised BN governance model. Concrete `BNMemberAuth` implementation is loaded by `BNUtils.loadBNMemberAuth()` method.

*Note that exact way how to load custom authorisation methods will be discussed later and not as part of initial membership management flow PRs.*

In the end we add test coverage inside `RequestMembershipFlowTest` and amend `MembershipManagementFlowTest` to support more test helper methods.

## Test Plan

Ensure all existing and new Business Network related tests pass.

Deploy nodes, create Business Network, request memberships and query parties vaults for sanity check.

Created Business Network (BNO node):
<img width="1043" alt="Screenshot 2020-06-17 at 17 12 16" src="https://user-images.githubusercontent.com/37048878/84922426-be864700-b0bd-11ea-81c8-641ed81232ad.png">

Request membership (Member1 node):
<img width="977" alt="Screenshot 2020-06-17 at 17 12 23" src="https://user-images.githubusercontent.com/37048878/84922457-c940dc00-b0bd-11ea-9f6f-bbb249b55075.png">

Query vault (BNO node):
<img width="983" alt="Screenshot 2020-06-17 at 17 12 30" src="https://user-images.githubusercontent.com/37048878/84922480-d067ea00-b0bd-11ea-9c35-cabbcc2fe6ff.png">

2020-06-23 08:59 UTC, bpaunescu approved these changes
LGTM

2020-06-23 18:27 UTC, alexandradh requested changes
Please see my comments inline.
It's mainly around exceptions and checks around the command and authorisation.

2020-06-23 18:27 UTC, alexandradh commented on business-networks/workflows/src/test/kotlin/net/corda/bn/flows/RequestMembershipFlowTest.kt
> +            runRequestMembershipFlow(regularMember, authorisedMember, invalidNetworkId)
Wouldn't this use case deserve it's own exception?
Something along the lines of "network is not recognised". First check if the network if being recognised, if yes, going on with checking the membership and throwing this kind of exception.

2020-06-23 18:27 UTC, alexandradh commented on business-networks/workflows/src/main/kotlin/net/corda/bn/flows/RequestMembershipFlow.kt
> +            throw FlowException("Initiator is already a member of Business Network with $networkId ID")
Does this have to be an exception?
Alternatively, it could detect this and "do nothing", returning `null` instead, making the return a `SignedTransaction?`.

2020-06-23 18:27 UTC, alexandradh commented on business-networks/workflows/src/test/kotlin/net/corda/bn/flows/RequestMembershipFlowTest.kt
> +    fun `request membership flow should fail if receiver is not member of a business network`() {
This is to improve clarity: who is the `receiver`? `Initiator` is the one requesting the membership, is `receiver` the one responding to the request?

2020-06-23 18:27 UTC, alexandradh commented on business-networks/workflows/src/main/kotlin/net/corda/bn/flows/MembershipManagementFlow.kt
> +                ?: throw FlowException("Receiver is not member of a business network")
These exceptions could have their own types for easier distinction between use cases: `NotActiveMemberException`, `NotAuthorisedToActivateMembership` etc (bad naming, I know).

2020-06-23 18:27 UTC, alexandradh commented on business-networks/workflows/src/main/kotlin/net/corda/bn/flows/RequestMembershipFlow.kt
> +                if (command.value !is MembershipContract.Commands.Request) {
Would the observers need to run these checks themselves too?

2020-06-23 18:27 UTC, alexandradh commented on business-networks/workflows/src/main/kotlin/net/corda/bn/flows/MembershipManagementFlow.kt
> +            throw FlowException("Receiver's membership is not active")
Same as above.

2020-06-23 18:27 UTC, alexandradh commented on business-networks/workflows/src/main/kotlin/net/corda/bn/flows/MembershipManagementFlow.kt
> +            throw FlowException("Receiver is not authorised to activate membership")
Same as above.

2020-06-23 18:27 UTC, alexandradh commented on business-networks/workflows/src/main/kotlin/net/corda/bn/flows/RequestMembershipFlow.kt
> +        authorise(networkId, databaseService) { auth.canActivateMembership(it) }
Does anyone else in the network check if they are authorised to activate membership?

2020-06-24 12:55 UTC, tubibuto commented on business-networks/workflows/src/main/kotlin/net/corda/bn/flows/RequestMembershipFlow.kt
> +            throw FlowException("Initiator is already a member of Business Network with $networkId ID")
This could be confusing behaviour for the person initiating the flow (it may try to invoke it over and over again). Also we define that as invalid behaviour of flow user.

2020-06-24 12:55 UTC, tubibuto commented on business-networks/workflows/src/test/kotlin/net/corda/bn/flows/RequestMembershipFlowTest.kt
> +    fun `request membership flow should fail if receiver is not member of a business network`() {
Correct.

2020-06-24 12:58 UTC, tubibuto commented on business-networks/workflows/src/main/kotlin/net/corda/bn/flows/RequestMembershipFlow.kt
> +                if (command.value !is MembershipContract.Commands.Request) {
Only signers and observers are just subscribed for updates of states they are observing. The fact trusted parties, in this case fellow members, signed and before that checked transaction should be enough for them to say "okay this transaction comes from a trusted party which validated it", hence they can accept that transaction without need to do additional checks.

2020-06-24 13:00 UTC, tubibuto commented on business-networks/workflows/src/main/kotlin/net/corda/bn/flows/RequestMembershipFlow.kt
> +        authorise(networkId, databaseService) { auth.canActivateMembership(it) }
No, authorised member who builds transaction has other authorised memberships stored in its vault and knows which members are authorised, hence eligible for signing and observation of given pending membership.

2020-06-24 13:03 UTC, alexandradh commented on business-networks/workflows/src/main/kotlin/net/corda/bn/flows/RequestMembershipFlow.kt
> +                if (command.value !is MembershipContract.Commands.Request) {
This check on the command type is done on the observers in the other membership "broadcast" flows, like this one: https://github.com/corda/corda/blob/85829916de28d51f9037106f7da87fc548ddf0b2/business-networks/workflows/src/main/kotlin/net/corda/bn/flows/ActivateMembershipFlow.kt#L74

2020-06-24 13:06 UTC, tubibuto commented on business-networks/workflows/src/main/kotlin/net/corda/bn/flows/RequestMembershipFlow.kt
> +                if (command.value !is MembershipContract.Commands.Request) {
But if you take a closer look you may see only signers perform this check, not observers:
https://github.com/corda/corda/blob/85829916de28d51f9037106f7da87fc548ddf0b2/business-networks/workflows/src/main/kotlin/net/corda/bn/flows/MembershipManagementFlow.kt#L82

2020-06-24 13:23 UTC, alexandradh commented on business-networks/workflows/src/main/kotlin/net/corda/bn/flows/RequestMembershipFlow.kt
> +        authorise(networkId, databaseService) { auth.canActivateMembership(it) }
What I meant: does anyone else in the network check if the member activating the membership, is authorised to do so?

2020-06-24 13:26 UTC, tubibuto commented on business-networks/workflows/src/main/kotlin/net/corda/bn/flows/RequestMembershipFlow.kt
> +        authorise(networkId, databaseService) { auth.canActivateMembership(it) }
No, they don't have to since we rely on a fact everyone has the consistent view of the ledger, hence other members will have same view of activators membership meaning it is authorised from their perspective too.

2020-06-25 19:00 UTC, alexandradh requested changes

2020-06-25 19:00 UTC, alexandradh commented on business-networks/workflows/src/test/kotlin/net/corda/bn/flows/RequestMembershipFlowTest.kt
> +        assertFailsWith<UnexpectedFlowEndException> { runRequestMembershipFlow(regularMember, authorisedMember, networkId, authorisedMember.identity()) }
It seems like we're testing for a scenario when we're expecting the "unexpected" (responding flow failing, is that what's happening?) even though we know it's because the notary arg is invalid. Could give this exception a dedicated name and check for it?

2020-06-26 08:17 UTC, tubibuto commented on business-networks/workflows/src/test/kotlin/net/corda/bn/flows/RequestMembershipFlowTest.kt
> +        assertFailsWith<UnexpectedFlowEndException> { runRequestMembershipFlow(regularMember, authorisedMember, networkId, authorisedMember.identity()) }
I've been asking around in Slack channels and people confirmed my initial thoughts - It's not possible to get the initial cause of the exception thrown from responder flow unless that exception extends `FlowException`. The invalid notary exceptions are either `IllegalStateException` or `IllegalArgumentException`. I think it would be awkward to try to catch those on the responder flow side and re-throw `FlowException` since the portion of the code that would be wrapped with `try ... catch` block may throw those exceptions for the other reasons. The only proper solution would be to introduce notary specific exception inside the core of Corda, however I don't think that is trivial job to do.

2020-06-26 18:11 UTC, alexandradh approved these changes
Thanks for the changes, nice work!
I added an essay about the `UnexpectedFlowException` bit, @bpaunescu can say if anything needs changing there, but you're very right that we're stuck in a corner with that one.
Approved.

2020-06-26 18:11 UTC, alexandradh commented on business-networks/workflows/src/test/kotlin/net/corda/bn/flows/RequestMembershipFlowTest.kt
> +        assertFailsWith<UnexpectedFlowEndException> { runRequestMembershipFlow(regularMember, authorisedMember, networkId, authorisedMember.identity()) }
+1 on the `FlowException` part AND
+1 on the `try ... catch` being not a great option AND
+1 on this should be done from core
I was going back and forth on the pros and cons of trying to catch for this, and even questioning should we even test for this?
At the root of it is the custom notary option so I'll let @bpaunescu decide if this needs changing, in the end.
I have a personal hatred against `UnexpectedFlowEndedException` but this is also a tight corner we're forced into with this one.
Approving from my end.

2020-06-29 08:52 UTC, merged