EG-2294 Suspend Membership flow implementation
corda/corda pull request #6370
Opened 2020-06-18 11:36 UTC by tubibuto

## Description

This is the forth PR in the series of membership management flow PRs. We build on top of [Activate Membership flow PR](https://github.com/corda/corda/pull/6369) to introduce flow for suspension of membership inside Business Network.

First we implement `SuspendMembershipFlow` which takes membershipId which linear ID of the MembershipState we want to suspend. This is the workflow:

- Check initiator is authorised to suspend membership
- Initiator builds membership suspension transaction and sends it for signing to all active members authorised to modify membership
- Transaction is finalised and sent to all observers who are initiator, suspended member and all members authorised to modify membership
- If the member is first time onboarded (his membership state was in pending status before suspension), then all the authorised memberships are sent to it. It will also get all non revoked memberships if it's authorised to modify memberships.

In the end we add test coverage inside `SuspendMembershipFlowTest` and amend `MembershipFlowTest` to support more test helper methods.

## Test Plan

Ensure all existing and new Business Network related tests pass.

Deploy nodes, create Business Network, suspend membership and query parties vaults for sanity check.

Membership suspension and vault query (BNO node):
<img width="941" alt="Screenshot 2020-06-18 at 12 35 47" src="https://user-images.githubusercontent.com/37048878/85015684-49b81900-b160-11ea-90d6-d70992bfc1ea.png">

Vault query (Member1 node) - notice it also picked up authorised member state (BNO):
<img width="1042" alt="Screenshot 2020-06-18 at 12 35 56" src="https://user-images.githubusercontent.com/37048878/85015694-50df2700-b160-11ea-96a2-32999bb1819d.png">

2020-06-23 12:35 UTC, bpaunescu approved these changes
lgTM

2020-06-23 18:44 UTC, alexandradh requested changes
Please see my comments inline.

2020-06-23 18:44 UTC, alexandradh commented on business-networks/workflows/src/main/kotlin/net/corda/bn/flows/SuspendMembershipFlow.kt
> +                ?: throw FlowException("Membership state with $membershipId linear ID doesn't exist")
An `IllegalArgumentException` or a dedicated exception type would be more fitting.

2020-06-23 18:44 UTC, alexandradh commented on business-networks/workflows/src/main/kotlin/net/corda/bn/flows/SuspendMembershipFlow.kt
> +        // send authorised memberships to new activated or new suspended member (status moved from PENDING to ACTIVE/SUSPENDED)
Just to new suspended member, and status moving to SUSPENDED.

2020-06-26 15:35 UTC, alexandradh approved these changes
LGTM

2020-06-26 18:17 UTC, alexandradh approved these changes

2020-06-30 11:09 UTC, merged