ENT-5140: Tighten network parameters checks
corda/corda pull request #6390
Opened 2020-06-23 12:36 UTC by fowlerrr

Tighten up some network parameters checks

2020-06-24 09:33 UTC, fowlerrr commented
Ignore the `MS Windows Compatibility` failure.  That's something else that's already being tracked: https://r3-cev.atlassian.net/browse/EG-2854

2020-06-29 08:27 UTC, rick-r3 commented
This tightens just the initial check, if I remember correctly?

2020-06-29 14:39 UTC, fowlerrr commented
One line of the change tightens the initial check.

The addition of:
```
    init {
        sig.verify(raw)
    }
```
will mean that the verify also happens on any new `SignedWithDataCert` object.  And it does look like it could be copied around some (given that there's a `NetworkParametersCopier`)

Should we give it a run on the perf cluster first?

P.S. I could imagine removing the `init` method if performance is a concern.  Again, the signature should be verified on the initial download.

2020-07-15 13:31 UTC, rekalov commented
A few comments, since I suddenly got notified about this PR as a code owner :)
- `SignedDataWithCert` is designed in a similar way to `SignedData`, so it would be nice to make consistent changes
- pls. doublecheck `@CordaSerializable` side-effects
- I understand security aspects but ... isn't such verification in the constructor an anti-pattern?

2020-07-15 16:19 UTC, mnesbit requested changes

2020-07-15 16:19 UTC, mnesbit commented on core/src/main/kotlin/net/corda/core/internal/DigitalSignatureWithCert.kt
> +    init {
I very much dislike this! Throwing exceptions in constructors for objects that get deserialized is NOT helpful. It just leads to errors at the wrong place e.g. when loading from DB, rather than the use site. Plus we seem to be encouraging use of .deserialize(), which is an anti-pattern.

Can we look at other models e.g. that use the data you have to unwrap the object (which verifies it), or something else.

2020-07-15 16:33 UTC, fowlerrr commented on core/src/main/kotlin/net/corda/core/internal/DigitalSignatureWithCert.kt
> +    init {
The `deserialize` bit was just me aligning the method name with what it actually does.  `verfied()` as it previously existed simply also deserialized.  I suppose that was a lazy way of handling it?  Or maybe it was to avoid deserializing in the constructor.

I did go way off-topic with the changes in the hopes they'd make what's actually happening clearer.  I'll revert most of that.  But I see a potential performance issue with verifying frequently, which is what I was trying to alleviate.

Let me have a clean up and think about it

2020-07-17 07:33 UTC, fowlerrr commented on core/src/main/kotlin/net/corda/core/internal/DigitalSignatureWithCert.kt
> +        return _verified!!
Is this change worth it?  It seems to me that verifying the sig and deserializing each call is a bit of a waste, but I can revert this if it's out of scope here.

2020-07-17 07:36 UTC, fowlerrr commented on core/src/main/kotlin/net/corda/core/internal/DigitalSignatureWithCert.kt
> +        return obj
Is this change worth it? It seems to me that verifying the sig and deserializing each call is a bit of a waste, but I can revert this if it's out of scope here.

2020-07-17 09:10 UTC, rekalov commented on core/src/main/kotlin/net/corda/core/internal/DigitalSignatureWithCert.kt
> +        return obj
I doubt that network parameters are verified multiple times after deserialization (if it happens at all).

Normally signature verification is performed together with certificate verification on download from network map,. i.e. before serialization, so serialized parameters are always verified.

So, I'd revert this.

2020-07-17 10:46 UTC, rekalov approved these changes

2020-07-20 10:24 UTC, mnesbit approved these changes
OK

2020-07-20 10:26 UTC, merged