EG-2854
corda/corda pull request #6393
Opened 2020-06-24 11:35 UTC by pnemeth

checking if test still fails on Windows

2020-06-24 13:57 UTC, JamesHR3 requested changes
One small thing

2020-06-24 13:57 UTC, JamesHR3 commented on node/src/test/kotlin/net/corda/node/internal/NodeStartupCliTest.kt
>          CommandLine.populateCommand(startup, CommonCliConstants.CONFIG_FILE, "/$customNodeConf")
Might be better off constructing this as a path and then calling `toString` on it.

2020-06-24 15:37 UTC, JamesHR3 approved these changes
LGTM

2020-06-29 07:57 UTC, fowlerrr commented
Can I ask if this one can get merged?  It's probably just my personality type but all of those red `x`s in my PRs are driving me mad! 😄

2020-06-29 08:40 UTC, merged