ENT-5420 stop reconnecting when RejectedCommandException occurs.
corda/corda pull request #6394
Opened 2020-06-24 15:15 UTC by Vengi58

ENT-5420 originally the ticket was about = No delays between reconnections on flow start if node is in draining mode, but this issue is related to unwanted reconnect when RejectedCommandException thrown. The fix is to stop reconnecting in this case.

2020-06-25 06:06 UTC, fowlerrr commented
Can you add a test or evidence this works?

2020-06-25 06:14 UTC, fowlerrr requested changes

2020-06-25 06:14 UTC, fowlerrr commented on client/rpc/src/main/kotlin/net/corda/client/rpc/internal/ReconnectingCordaRPCOps.kt
> +                            remainingAttempts = 1
This leads to throwing a `MaxRpcRetryException` which isn't correct at all.  That would be misleading as we've not tried many times.  What we want is to pass on the exception which would lead to no more reconnections.

2020-06-25 14:37 UTC, Vengi58 commented on client/rpc/src/main/kotlin/net/corda/client/rpc/internal/ReconnectingCordaRPCOps.kt
> +                            remainingAttempts = 1
changed it to quiet return

2020-06-26 08:17 UTC, fowlerrr approved these changes
Cool.  I like this now.

2020-06-26 08:27 UTC, Vengi58 commented on client/rpc/src/main/kotlin/net/corda/client/rpc/internal/ReconnectingCordaRPCOps.kt
> +                            remainingAttempts = 1
changed it to rethrow and added test to verify it

2020-07-02 10:35 UTC, merged