CORDA-3880: Streamline re-connection logic in RPCClientProxyHandler
corda/corda pull request #6426
Opened 2020-07-01 14:02 UTC by vkolomeyko

Please see [Jira](https://r3-cev.atlassian.net/browse/CORDA-3880) for underlying reason for the change.

Also includes some minor tweaks to the whole class.

2020-07-02 08:25 UTC, dimosr requested changes

2020-07-02 08:25 UTC, dimosr commented on client/rpc/src/main/kotlin/net/corda/client/rpc/internal/RPCClientProxyHandler.kt
> + * To do the above we take advantage of serialisation data structure traversal. When the client is deserialising a message from
Thanks for refreshing the docs.

2020-07-02 08:25 UTC, dimosr commented on client/rpc/src/main/kotlin/net/corda/client/rpc/internal/RPCClientProxyHandler.kt
> +        while (if (maxReconnectCount > 0) reconnectAttempt < maxReconnectCount else true) {
having an if conditional inside a while statement makes it a bit hard to parse mentally.
It'd be better to have a private helper method, smth like `while(shouldRetry(reconnectAttempt, maxReconnectCount))`

Also, shouldn't the logic be instead:
`if (maxReconnectCount >= 0) reconnectAttempt <= maxReconnectCount else true`?

2020-07-02 08:25 UTC, dimosr commented on client/rpc/src/main/kotlin/net/corda/client/rpc/internal/RPCClientProxyHandler.kt
> +            val transport = serverLocator.staticTransportConfigurations.let { it[reconnectAttempt % it.size] }
minor: maybe switch to `it[(reconnectAttempt-1) % it.size]`, so that we try addresses in the order specified by the user.

2020-07-02 08:25 UTC, dimosr commented on client/rpc/src/main/kotlin/net/corda/client/rpc/internal/RPCClientProxyHandler.kt
> +        val maxReconnectReached = maxReconnectCount > 0 && reconnectAttempt >= maxReconnectCount
similar to the above, I'd think this should be:
`maxReconnectCount >= 0 && reconnectAttempt > maxReconnectCount`

2020-07-02 08:25 UTC, dimosr commented on client/rpc/src/main/kotlin/net/corda/client/rpc/internal/RPCClientProxyHandler.kt
> +                    if (sessionFactory == null) "NOT " else "" + "present"
what is the scenario in which `sessionFactory` would be null? I am afraid this log will be quite cryptic - is there a way to provide something more useful?

2020-07-02 08:28 UTC, vkolomeyko commented on client/rpc/src/main/kotlin/net/corda/client/rpc/internal/RPCClientProxyHandler.kt
> + * To do the above we take advantage of serialisation data structure traversal. When the client is deserialising a message from
👍

2020-07-02 08:36 UTC, vkolomeyko commented on client/rpc/src/main/kotlin/net/corda/client/rpc/internal/RPCClientProxyHandler.kt
> +        while (if (maxReconnectCount > 0) reconnectAttempt < maxReconnectCount else true) {
Thanks @dimosr 
I guess it is down to the contract for `maxReconnectCount`, which is not written anywhere. From the code when `maxReconnectCount` is `-1` then this means infinite number of reconnects. But what about when `maxReconnectCount == 0` ?
Since it is not written, my assumption was that  `maxReconnectCount = 0` also means infinite number of re-connects.

I take your point about helper function and will make a change accordingly.

2020-07-02 08:41 UTC, dimosr commented on client/rpc/src/main/kotlin/net/corda/client/rpc/internal/RPCClientProxyHandler.kt
> +        while (if (maxReconnectCount > 0) reconnectAttempt < maxReconnectCount else true) {
yeah, I also had a look at the docs, it's not completely clear, indeed. I assume that any non-negative values would have the natural meaning, so 0 would mean no retries.

I wouldn't be against the current logic assuming we'll clarify the docs to make clear the special meaning of 0. Another question I'd have in this case is is there any way to remove retries if we take the option of setting it to zero away?

2020-07-02 08:43 UTC, vkolomeyko commented on client/rpc/src/main/kotlin/net/corda/client/rpc/internal/RPCClientProxyHandler.kt
> +            val transport = serverLocator.staticTransportConfigurations.let { it[reconnectAttempt % it.size] }
Sure - makes sense not to skip `0` endpoint on first re-connect.

2020-07-02 08:45 UTC, vkolomeyko commented on client/rpc/src/main/kotlin/net/corda/client/rpc/internal/RPCClientProxyHandler.kt
> +        val maxReconnectReached = maxReconnectCount > 0 && reconnectAttempt >= maxReconnectCount
Sure - will change.

2020-07-02 08:56 UTC, vkolomeyko commented on client/rpc/src/main/kotlin/net/corda/client/rpc/internal/RPCClientProxyHandler.kt
> +                    if (sessionFactory == null) "NOT " else "" + "present"
Looking deeper into the code, I think `sessionFactory` would be `null` if it was never possible to establish connection with any of the endpoints specified. I.e. method `createSessionFactory` was always ended-up throwing an exception.

I guess I will re-phrase the error message to highlight this fact.

2020-07-02 09:27 UTC, vkolomeyko commented on client/rpc/src/main/kotlin/net/corda/client/rpc/internal/RPCClientProxyHandler.kt
> +        while (if (maxReconnectCount > 0) reconnectAttempt < maxReconnectCount else true) {
Sure - I will update the docs to be explicit.

> is there any way to remove retries
I guess there is a little bit of contradiction here. If the user providing a pool of endpoints of size greater than 1, why would such a user ever ask for no retries to happen?

2020-07-02 09:34 UTC, dimosr commented on client/rpc/src/main/kotlin/net/corda/client/rpc/internal/RPCClientProxyHandler.kt
> +        while (if (maxReconnectCount > 0) reconnectAttempt < maxReconnectCount else true) {
that's a good point, not sure. Maybe if someone wants to have all addresses tried on the first connection attempt, while at the same time failing fast and avoiding any retries on transient issues?

2020-07-02 09:52 UTC, vkolomeyko commented on client/rpc/src/main/kotlin/net/corda/client/rpc/internal/RPCClientProxyHandler.kt
> +        while (if (maxReconnectCount > 0) reconnectAttempt < maxReconnectCount else true) {
Yes, I agree - but this seem to be a very unusual type of requirement.

2020-07-02 09:58 UTC, vkolomeyko commented on client/rpc/src/main/kotlin/net/corda/client/rpc/internal/RPCClientProxyHandler.kt
> +        while (if (maxReconnectCount > 0) reconnectAttempt < maxReconnectCount else true) {
And I have updated the KDocs on `maxReconnectAttempts` to explicty say: `Any non-positive value would mean that there will be an infinite number of reconnect attempts.`

2020-07-02 10:14 UTC, dimosr commented on client/rpc/src/main/kotlin/net/corda/client/rpc/internal/RPCClientProxyHandler.kt
> +        while (if (maxReconnectCount > 0) reconnectAttempt < maxReconnectCount else true) {
Given this is essentially a refactoring change, I'd prefer to keep the old behaviour since there might be customers relying on it already.

2020-07-02 11:11 UTC, vkolomeyko commented on client/rpc/src/main/kotlin/net/corda/client/rpc/internal/RPCClientProxyHandler.kt
> +        while (if (maxReconnectCount > 0) reconnectAttempt < maxReconnectCount else true) {
I still think we have to explicitly state what is going to happen when a negative or zero value is passed into `maxReconnectAttempts`. Especially given that in our documentation we say: 
"See `CordaRPCClientConfiguration.maxReconnectAttempts` for adjusting the number of retries."

I doubt any of customers put a value of `0` to `maxReconnectAttempts`, but @dimosr do you think it would be correct to change the Kdocs to say `Any negative value would mean that there will be an infinite number of reconnect attempts.` and change the code accordingly?

2020-07-02 11:22 UTC, dimosr commented on client/rpc/src/main/kotlin/net/corda/client/rpc/internal/RPCClientProxyHandler.kt
> +        while (if (maxReconnectCount > 0) reconnectAttempt < maxReconnectCount else true) {
In cases like this, I usually prefer to be on the safe side and preserve existing behaviour (just in case someone relies on it) unless of course there's a clear requirement to change it. So, I'd do the following here:
* Adjust the kdocs to make clear what's the contract for negative values, i.e. infinite retries as you suggested. I believe that's already what the code does, so no code changes needed there.
* Change the code, so that it does not perform retries when `maxReconnectAttempts = 0`, similar to the existing behaviour. On the kdocs side, either call this out - the fact that zero means no retries - or not mention anything at all. I think this is the natural meaning of this value, so it shouldn't be a big problem.

2020-07-02 12:40 UTC, vkolomeyko commented on client/rpc/src/main/kotlin/net/corda/client/rpc/internal/RPCClientProxyHandler.kt
> +        while (if (maxReconnectCount > 0) reconnectAttempt < maxReconnectCount else true) {
OK, I will update the KDoc and change the code such that we do not re-connect if `maxReconnectAttempts = 0`.

2020-07-02 12:51 UTC, vkolomeyko commented on client/rpc/src/main/kotlin/net/corda/client/rpc/internal/RPCClientProxyHandler.kt
> +        while (if (maxReconnectCount > 0) reconnectAttempt < maxReconnectCount else true) {
@dimosr - I have pushed more changes as https://github.com/corda/corda/pull/6426/commits/cee7e796853b62f49abec0e681e8ce9f19488d24
Could you please re-review when you have time?

2020-07-02 14:01 UTC, dimosr approved these changes
LGTM

2020-07-03 07:56 UTC, mnesbit approved these changes
OK, but please check with Tamas

2020-07-03 08:29 UTC, merged