EG-2754, EG-2755 Group State and Contract for Business Network
corda/corda pull request #6442
Opened 2020-07-07 14:53 UTC by tubibuto

## Description

This PR is the continuation of the second phase of Business Network membership management which takes care of Business Network Groups implementation. The idea is to have multiple membership lists inside a Business Network which enable creation of private Business Networks where members are only subscribed to their group participants changes. 

First we create new `GroupState` data class which represents Business Network Group and consists of following fields:
- `networkId` is the unique identifier of BN the group belongs to
- `name` is more convenient way of distinction between groups
- `linearId` is unique identifier of group
- `participants` is list of all members belonging to given group

We also add supporting KDocs to this new state and generate custom database schema with supporting liquibase migration script. This is created since we are going to query the vault based on custom group state's fields.

After that we implement belonging contract logic inside `GroupContract` containing following commands:
- `Create` for issuance of the new `GroupState`
- `Modify` for modifying `name` or `participants` field of `GroupState`
- `Exit` for marking `GroupState` historic

Notice we make this an open class since in future we'll leave possibility for users to write their own custom membership contract logic based on the one we provide. `verify()` method is divided in 2 parts:
- Standard common checks which are applied to all command types. Those checks can't be overriden by users
- Verification checks specialised for each command via `verifyCreate()`, `verifyModify()` and `verifyExit()` open methods

In the end we write supporting test coverage inside `GroupContractTest` class.

Next PR will introduce flows for Business Network Group creation, modification and deletion.

## Test Plan

Ensure all existing and new Business Network related tests pass.

2020-07-09 16:25 UTC, mrworkman requested changes
m0aR kD()ckS.

2020-07-09 16:25 UTC, mrworkman commented on business-networks/contracts/src/main/kotlin/net/corda/bn/contracts/GroupContract.kt
> +open class GroupContract : Contract {
Please add kdocs for all classes, properties, and methods. Provide docs for all parameters, and return values as well.

2020-07-09 16:25 UTC, mrworkman commented on business-networks/contracts/src/main/kotlin/net/corda/bn/contracts/GroupContract.kt
> +    open fun verifyCreate(tx: LedgerTransaction, command: CommandWithParties<Commands>, outputGroup: GroupState) = requireThat {
`command` and `outputGroup` are not used.

2020-07-09 16:25 UTC, mrworkman commented on business-networks/contracts/src/main/kotlin/net/corda/bn/contracts/GroupContract.kt
> +    open fun verifyModify(tx: LedgerTransaction, command: CommandWithParties<Commands>, inputGroup: GroupState, outputGroup: GroupState) = requireThat {
`tx` is not used.

2020-07-09 16:25 UTC, mrworkman commented on business-networks/contracts/src/main/kotlin/net/corda/bn/contracts/GroupContract.kt
> +    open fun verifyExit(tx: LedgerTransaction, command: CommandWithParties<Commands>, inputGroup: GroupState) = requireThat {
`command` and `inputGroup` are not used.

2020-07-09 16:25 UTC, mrworkman commented on business-networks/contracts/src/main/kotlin/net/corda/bn/contracts/GroupContract.kt
> +    open fun contractName() = CONTRACT_NAME
This method is redundant. You can just use `CONTRACT_NAME` as a property.

2020-07-09 16:25 UTC, mrworkman commented on business-networks/contracts/src/main/kotlin/net/corda/bn/contracts/MembershipContract.kt
> +        class ModifyParticipants(requiredSigners: List<PublicKey>) : Commands(requiredSigners)
Please add kdocs for all classes, properties, and methods. Provide docs for all parameters, and return values as well. (Including for all existing code).

2020-07-09 16:25 UTC, mrworkman commented on business-networks/contracts/src/main/kotlin/net/corda/bn/schemas/GroupStateSchemaV1.kt
> +object GroupStateSchemaV1 : MappedSchema(schemaFamily = GroupState::class.java, version = 1, mappedTypes = listOf(PersistentGroupState::class.java)) {
Add kdocs for all the things.

2020-07-09 16:25 UTC, mrworkman commented on business-networks/contracts/src/main/kotlin/net/corda/bn/states/GroupState.kt
> +        override val participants: List<Party>
These do not have kdocs.

Also, moving kdocs to the actual properties will make docs appear correctly in intellij.
```kotlin
/** Some wonderful description that will make @mrworkman happy. */
override val participants: List<Party>
```

2020-07-09 16:25 UTC, mrworkman commented on business-networks/contracts/src/main/kotlin/net/corda/bn/states/GroupState.kt
> +    override fun supportedSchemas() = listOf(GroupStateSchemaV1)
Kdocs and explanatory comments.

2020-07-09 16:25 UTC, mrworkman commented on business-networks/contracts/src/main/kotlin/net/corda/bn/states/MembershipState.kt
> +    fun canModifyGroups() = AdminPermission.CAN_MODIFY_GROUPS in permissions()
These methods should all have kdocs explaining their purpose.

2020-07-09 16:25 UTC, mrworkman commented on business-networks/contracts/src/main/resources/group-state-schema-v1.changelog-init.xml
> +            </column>
These columns are not defined in the `GroupStateSchemaV1.PersistentGroupState` kotlin class. Are they part of `PersistentState`?

2020-07-09 16:25 UTC, mrworkman commented on business-networks/contracts/src/test/kotlin/net/corda/bn/contracts/GroupContractTest.kt
> +                fails()
These (`output`/`command`/`fails`) are alien to me. I'll need to be filled in on them.

2020-07-10 09:14 UTC, tubibuto commented on business-networks/contracts/src/main/kotlin/net/corda/bn/contracts/GroupContract.kt
> +    open fun verifyCreate(tx: LedgerTransaction, command: CommandWithParties<Commands>, outputGroup: GroupState) = requireThat {
Method is open so in case someone wants to override contract logic they may need to use any of the arguments provided

2020-07-10 10:53 UTC, tubibuto commented on business-networks/contracts/src/main/resources/group-state-schema-v1.changelog-init.xml
> +            </column>
Yes they are:
```
/**
 * A super class for all mapped states exported to a schema that ensures the [StateRef] appears on the database row.  The
 * [StateRef] will be set to the correct value by the framework (there's no need to set during mapping generation by the state itself).
 */
@KeepForDJVM
@MappedSuperclass
@CordaSerializable
class PersistentState(@EmbeddedId override var stateRef: PersistentStateRef? = null) : DirectStatePersistable
```

2020-07-10 11:02 UTC, tubibuto commented on business-networks/contracts/src/test/kotlin/net/corda/bn/contracts/GroupContractTest.kt
> +                fails()
This is actually part of `LedgerDSL` which basically syntactic sugar of the ledger Test DSL and delegates to the contained interpreter, and what is actually used in `ledger { (...) }`. Basically a nice way to write quick contract tests over mocked transactions.

2020-07-10 11:59 UTC, tubibuto commented on business-networks/contracts/src/main/kotlin/net/corda/bn/contracts/GroupContract.kt
> +    open fun contractName() = CONTRACT_NAME
If someone wants to override contract logic this is going to be the source of truth for contract name since companion object fields cannot be made open.

2020-07-10 15:32 UTC, tubibuto commented on business-networks/contracts/src/main/kotlin/net/corda/bn/states/GroupState.kt
> +    override fun supportedSchemas() = listOf(GroupStateSchemaV1)
I believe they docs will be seen since the original method has them:
<img width="628" alt="Screenshot 2020-07-10 at 16 31 20" src="https://user-images.githubusercontent.com/37048878/87171655-e2a70380-c2ca-11ea-8a4e-ce871ed034b3.png">

2020-07-14 08:47 UTC, mrworkman approved these changes
Nice work!

2020-07-14 12:33 UTC, merged