EG-2754, EG-2755 Group Management flows implementation
corda/corda pull request #6444
Opened 2020-07-07 15:50 UTC by tubibuto

## Description

This PR is the continuation of [group state and contracts PR](https://github.com/corda/corda/pull/6442) in which we introduce group management flows which will bring previously implemented states and contracts to life.

We implement 3 new flows for group management:
- `CreateGroupFlow` takes `networkId` of BN in which the new group will be created, optional custom `groupName` and `groupId` and set of `additionalParticipants` to be added alongside initiator to the new issued group.
- `ModifyGroupFlow` takes `groupId` of the group to be modified, new `name` of the group and new `participants` set of the group and modifies it accordingly
- `DeleteGroupFlow` takes `groupId` of the group to be marked historic and exits corresponding state

Each of the group management flow does membership states exchanges between new participants and modifies participants list of their membership states accordingly via new `syncMembershipsParticipants()` method which invokes brand new created internal `ModifyParticipantsFlow`. This flow builds transaction consisting of new `MembershipContract.Commands.ModifyParticipants` command.

After that we modify existing membership management flows not to modify participants lists of membership states. This is now done only by group management flows since they are the ones having direct impact on participants membership states' observers. We also modify `CreateBusinessNetworkFlow` so that it creates initial Business Network Group since one should always exist and no member must remain without any group to be participant.

In the end we adapt existing BN related test to the new group management logic.

Next PR will provide covering test coverage for group management logic.

## Test Plan

Ensure all existing BN related test pass.

Deploy nodes, create Business Network with 3 active members and try to manage groups and see expected results.

BNO creating new Business Network (we see the initial group created too):
<img width="891" alt="Screenshot 2020-07-07 at 16 27 47" src="https://user-images.githubusercontent.com/37048878/86807269-9f9e2380-c071-11ea-8476-dcf80cf206fb.png">

Member1 and Member2 states activated (we see they are still not participants of any groups - BNO is advised to do it as soon as the new member is onboarded):
<img width="993" alt="Screenshot 2020-07-07 at 16 29 28" src="https://user-images.githubusercontent.com/37048878/86807394-be041f00-c071-11ea-8311-6a6ccb617391.png">

Modifying initial group so that Member1 and Member2 are new participants (also changing name of the group):
<img width="1610" alt="Screenshot 2020-07-07 at 16 31 07" src="https://user-images.githubusercontent.com/37048878/86807460-ceb49500-c071-11ea-8c35-0efb5541e7e9.png">

Member1's vault (the group has changed, also the membership participants too):
<img width="940" alt="Screenshot 2020-07-07 at 16 31 32" src="https://user-images.githubusercontent.com/37048878/86807575-e55aec00-c071-11ea-9160-4e6f23b8954e.png">

2020-07-14 09:00 UTC, bpaunescu requested changes
Looks good. See comments inline about using specific notaries.

2020-07-14 09:00 UTC, bpaunescu commented on business-networks/workflows/src/main/kotlin/net/corda/bn/flows/DeleteGroupFlow.kt
> +        val builder = TransactionBuilder(notary ?: serviceHub.networkMapCache.notaryIdentities.first())
I may have missed this in other places, but I'd like to be able to specify the notary to be used. I recall talking about this before.

2020-07-14 09:00 UTC, bpaunescu commented on business-networks/workflows/src/main/kotlin/net/corda/bn/flows/ModifyGroupFlow.kt
> +        val builder = TransactionBuilder(notary ?: serviceHub.networkMapCache.notaryIdentities.first())
Same notary thing as above. Should be able to specify which is used.

2020-07-14 09:00 UTC, bpaunescu commented on business-networks/workflows/src/main/kotlin/net/corda/bn/flows/ModifyParticipantsFlow.kt
> +        val builder = TransactionBuilder(notary ?: serviceHub.networkMapCache.notaryIdentities.first())
Same notary thing.

2020-07-14 09:11 UTC, tubibuto commented on business-networks/workflows/src/main/kotlin/net/corda/bn/flows/DeleteGroupFlow.kt
> +        val builder = TransactionBuilder(notary ?: serviceHub.networkMapCache.notaryIdentities.first())
Sorry but I don't understand - we do specify it as a flow argument

2020-07-14 10:17 UTC, mrworkman requested changes
Looks pretty good overall. Just a few small things to fix up.

2020-07-14 10:17 UTC, mrworkman commented on business-networks/workflows/src/main/kotlin/net/corda/bn/flows/CreateBusinessNetworkFlow.kt
> +    private fun createBusinessNetworkGroup(databaseService: DatabaseService): SignedTransaction {
kdocs

2020-07-14 10:17 UTC, mrworkman commented on business-networks/workflows/src/main/kotlin/net/corda/bn/flows/CreateBusinessNetworkFlow.kt
> +            throw DuplicateBusinessNetworkGroupException("Business Network Group with $groupId already exists.")
If this exception will always be created with the same text, I suggest changing the constructor:

```kotlin
class DuplicateBusinessNetworkGroupException(groupId: UniqueIdentifier) 
    : FlowException("Business Network Group with $groupId already exists.")
```

And the same for other similar exceptions.

2020-07-14 10:17 UTC, mrworkman commented on business-networks/workflows/src/main/kotlin/net/corda/bn/flows/CreateBusinessNetworkFlow.kt
> +class DuplicateBusinessNetworkGroupException(message: String) : FlowException(message)
I suggest moving these to another source file, especially if they're used by other flows &mdash; i.e. `CreateGroupFlow`

2020-07-14 10:17 UTC, mrworkman commented on business-networks/workflows/src/main/kotlin/net/corda/bn/flows/DatabaseService.kt
>      private fun linearIdCriteria(linearId: UniqueIdentifier) = QueryCriteria.LinearStateQueryCriteria(linearId = listOf(linearId))
Maybe add a single brief block comment for these.

2020-07-14 10:17 UTC, mrworkman commented on business-networks/workflows/src/main/kotlin/net/corda/bn/flows/DeleteGroupFlow.kt
> +                .addCommand(GroupContract.Commands.Exit(requiredSigners), requiredSigners)
Add a comment here explaining why the exit command is appropriate.

2020-07-14 10:17 UTC, mrworkman commented on business-networks/workflows/src/main/kotlin/net/corda/bn/flows/MembershipManagementFlow.kt
> +        observerSessions.forEach { it.send(if (it in destinationSessions) membershipsTransactions.size else 0) }
I'm assuming `destinationSessions` will be small, and doing `it in destinationSessions`  for each observer session will remain reasonably performant?

2020-07-14 10:17 UTC, mrworkman commented on business-networks/workflows/src/main/kotlin/net/corda/bn/flows/MembershipManagementFlow.kt
> +                membership.state.data.identity.cordaIdentity in it.participants
Similar to above, group participants will remain small?

2020-07-14 10:17 UTC, mrworkman commented on business-networks/workflows/src/main/kotlin/net/corda/bn/flows/MembershipManagementFlow.kt
> +class IllegalBusinessNetworkGroupStateException(message: String) : FlowException(message)
Move these to separate source file(s).

2020-07-14 10:17 UTC, mrworkman commented on business-networks/workflows/src/main/kotlin/net/corda/bn/flows/ModifyParticipantsFlow.kt
> +class ModifyParticipantsFlow(
kdocs missing

2020-07-14 10:17 UTC, mrworkman commented on business-networks/workflows/src/test/kotlin/net/corda/bn/flows/CreateGroupFlowTest.kt
> +            val data = data as GroupState
Re-assignment isn't necessary. You can just place `data as GroupState` on a line by itself.

2020-07-14 10:17 UTC, mrworkman commented on business-networks/workflows/src/main/kotlin/net/corda/bn/flows/ModifyGroupFlow.kt
> +            membership.state.data.identity.cordaIdentity !in (databaseService.getAllBusinessNetworkGroups(networkId) - group).flatMap { it.state.data.participants }
Should probably avoid doing `databaseService.getAllBusinessNetworkGroups(networkId) - group` inside the `filter` lambda to avoid multiple calls to `getAllBusinessNetworkGroups()`.

2020-07-14 10:17 UTC, mrworkman commented on business-networks/workflows/src/test/kotlin/net/corda/bn/flows/ModifyGroupFlowTest.kt
> +            val data = data as GroupState
Re-assignment isn't necessary. You can just place `data as GroupState` on a line by itself.

2020-07-14 10:27 UTC, tubibuto commented on business-networks/workflows/src/main/kotlin/net/corda/bn/flows/MembershipManagementFlow.kt
> +        observerSessions.forEach { it.send(if (it in destinationSessions) membershipsTransactions.size else 0) }
Not necessary, this could impact performance in some cases - I think `HashSet` for `destinationSessions` is better approach.

Thanks :)

2020-07-14 10:27 UTC, tubibuto commented on business-networks/workflows/src/main/kotlin/net/corda/bn/flows/MembershipManagementFlow.kt
> +                membership.state.data.identity.cordaIdentity in it.participants
Same as above

2020-07-14 13:19 UTC, tubibuto commented on business-networks/workflows/src/main/kotlin/net/corda/bn/flows/MembershipManagementFlow.kt
> +                membership.state.data.identity.cordaIdentity in it.participants
However when I think a bit this case is different than the one above since we'll have one lookup per a group so the overhead of hash set creation will diminish algorithmic complexity improvement.

2020-07-14 13:25 UTC, tubibuto commented on business-networks/workflows/src/test/kotlin/net/corda/bn/flows/CreateGroupFlowTest.kt
> +            val data = data as GroupState
Tried it but idiomatic (idiotic maybe) Kotlin says it's not possible:
<img width="681" alt="Screenshot 2020-07-14 at 14 24 46" src="https://user-images.githubusercontent.com/37048878/87430954-d4fcc100-c5dd-11ea-9d6f-ce26db933254.png">

2020-07-14 13:26 UTC, tubibuto commented on business-networks/workflows/src/test/kotlin/net/corda/bn/flows/ModifyGroupFlowTest.kt
> +            val data = data as GroupState
Same as above

2020-07-14 17:16 UTC, mrworkman commented on business-networks/workflows/src/test/kotlin/net/corda/bn/flows/CreateGroupFlowTest.kt
> +            val data = data as GroupState
aw :(

2020-07-14 17:24 UTC, mrworkman approved these changes
👍

2020-07-15 09:22 UTC, bpaunescu commented on business-networks/workflows/src/main/kotlin/net/corda/bn/flows/DeleteGroupFlow.kt
> +        val builder = TransactionBuilder(notary ?: serviceHub.networkMapCache.notaryIdentities.first())
Ah my mistake then. Wasn't paying attention. I derped....Sorry :(

2020-07-15 09:22 UTC, bpaunescu approved these changes

2020-07-15 09:26 UTC, merged