CORDA-3777 Reload after every checkpoint
corda/corda pull request #6494
Opened 2020-07-21 16:51 UTC by lankydan

Enable reloading of a flow after every checkpoint is saved. This
includes reloading the checkpoint from the database and recreating the
fiber.

`reloadCheckpointAfterSuspend` is a field added to `Event.Suspend`. When
creating the event it checks the configuration to determine if it should
reload after processing the suspend event.

If it should reload, then it processes an `Event.RetryFlowFromSafePoint`
straight after completing the suspend. This handles the reloading.

This works because the flag on the suspend event, sets another flag on
the `StateMachineState`. When recreating the transient state
(`StateMachineState`), the same flag is set to false. This means when
the fiber is restarted (it resumes at the point after completing the
suspend event in `FlowStateMachineImpl.suspend`), it does not retry
again.

Without this switching between the flags the flow would be stuck in an
infinite loop of retrying.

A new staff member has been added to the flow hospital to force it to
ignore the `ReloadFlowFromCheckpointException` thrown if the flow fails
deserialization when reloading.

2020-07-21 17:06 UTC, rick-r3 commented
Looks good to me

2020-07-22 07:56 UTC, rick-r3 requested changes

2020-07-22 07:56 UTC, rick-r3 commented on node/src/main/kotlin/net/corda/node/services/statemachine/FlowStateMachineImpl.kt
> +                    reloadCheckpointAfterSuspend = serviceHub.value.configuration.reloadCheckpointAfterSuspend
Mmmm.... maybe it's not quite this easy!

e.g. imagine this is an `IdempotentFlow` that suspends many time (you could probably build a test one).  There will only be one checkpoint that we keep restoring from, but we do also want to test terminating at each suspension point.

Now I'm thinking the idea of having the hospital track which suspension points have been retried from (via medical history records) is a better idea.  

Or does the code already work that way?  My impression, without detailed study, is that it just goes to the next suspension after a retry and thus wouldn't work, but happy to be proven wrong.

2020-07-23 17:20 UTC, rick-r3 commented on node/src/main/kotlin/net/corda/node/services/statemachine/StaffedFlowHospital.kt
> +                Diagnosis.TERMINAL
Should we retain the checkpoint for analysis ?  Does that suggest observation (instead)?  Maybe that makes your testing harder.

2020-07-23 17:20 UTC, rick-r3 commented on node/src/main/kotlin/net/corda/node/services/statemachine/transitions/TopLevelTransition.kt
> +    private fun retryFlowFromSafePointTransition(): TransitionResult {
Yep, `startingState` is fed into `currentState` of the builder, so no need to also pass in here as you have figured out.

2020-07-23 17:22 UTC, rick-r3 commented on node/src/main/kotlin/net/corda/node/services/statemachine/StaffedFlowHospital.kt
> +                Diagnosis.TERMINAL
Maybe a test mode (for you) where it throws, but normally keeps in for observation.

2020-07-23 18:56 UTC, lankydan commented on node/src/main/kotlin/net/corda/node/services/statemachine/StaffedFlowHospital.kt
> +                Diagnosis.TERMINAL
Mmm I think if we are going to do that, we should both throw the exception and hospitalize the flow. Will be more work but I think that is the best idea.

I agree that keeping the checkpoint does make sense. Maybe this should hook into the client id work? In that, we plan to keep the exception if the flow failed when a client id was passed to it. We could keep the checkpoint but the status would be set to failed so it never gets run again.

2020-07-24 09:54 UTC, williamvigorr3 commented on node/src/main/kotlin/net/corda/node/services/statemachine/FlowCreator.kt
> +            reloadCheckpointAfterSuspendCount = reloadCheckpointAfterSuspendCount
As you pointed out this might look better with a sealed class. Do we want to do this now?

2020-07-24 09:54 UTC, williamvigorr3 commented on node/src/main/kotlin/net/corda/node/services/statemachine/FlowCreator.kt
>          return createFlowFromCheckpoint(nonResidentFlow.runId, checkpoint)
I think you need to update this as well. Otherwise for paused flows which retry won't the count go back to zero causing it to reload the first checkpoint?

2020-07-24 09:54 UTC, williamvigorr3 commented on node/src/main/kotlin/net/corda/node/services/statemachine/FlowCreator.kt
> +    private inline fun <reified T : Any> tryCheckpointDeserialize(
Should `tryDeserializeCheckpoint` also throw a `ReloadFlowFromCheckpointException` or similar inside SingleThreadedStateMachineManager.kt? In the case that the checkpoint itself can't be deserialized.

2020-07-24 09:54 UTC, williamvigorr3 commented on node/src/main/kotlin/net/corda/node/services/statemachine/FlowCreator.kt
>          return createFlowFromCheckpoint(nonResidentFlow.runId, checkpoint)
Okay I am wrong the only place we are using this is inside retryFlowFromSafePoint. This should work fine.

2020-07-24 09:54 UTC, williamvigorr3 commented on node/src/main/kotlin/net/corda/node/services/statemachine/FlowCreator.kt
> +        reloadCheckpointAfterSuspend: Boolean
You could use this `@FlowCreator.reloadCheckpointAfterSuspend` (at least I think you can do this) instead of passing it in here.

2020-07-24 09:54 UTC, williamvigorr3 commented on node/src/main/kotlin/net/corda/node/services/statemachine/SingleThreadedStateMachineManager.kt
> +            flowCreator.createFlowFromCheckpoint(flowId, checkpoint, currentState.reloadCheckpointAfterSuspendCount) ?: return
Maybe it would be clearer if we called an explicitly called different method here. I also think it would be better if     private val reloadCheckpointAfterSuspend = serviceHub.configuration.reloadCheckpointAfterSuspend was stored inside the statemachine manager and not inside flowCreator. The reason being is this option only actually makes a difference when called inside retryFlowFromSafePoint.

2020-07-24 09:54 UTC, williamvigorr3 commented on node/src/integration-test/kotlin/net/corda/node/flows/FlowReloadAfterCheckpointTest.kt
> +            assertEquals(null, reloadCounts[flowStartedByAlice])
`assertNull` :trollface:

2020-07-24 09:54 UTC, williamvigorr3 commented on node/src/integration-test/kotlin/net/corda/node/flows/FlowReloadAfterCheckpointTest.kt
> +            assertEquals(5, reloadCounts[flowStartedByAlice])
It might make it clearer to add a comments to `ReloadFromCheckpointFlow` and `ReloadFromCheckpointResponder ` every time the flow is supposed to suspend so it is easy to work out why this number should be 5.

2020-07-24 09:54 UTC, williamvigorr3 commented on node/src/integration-test/kotlin/net/corda/node/flows/FlowReloadAfterCheckpointTest.kt
> +class FlowReloadAfterCheckpointTest {
Looks comprehensive. It might be worth checking timedFlows work still by throwing a `FlowTimeoutException`.

2020-07-24 11:03 UTC, lankydan commented on node/src/main/kotlin/net/corda/node/services/statemachine/FlowCreator.kt
> +            reloadCheckpointAfterSuspendCount = reloadCheckpointAfterSuspendCount
I tried it but didnt like it tbh.

2020-07-24 11:05 UTC, lankydan commented on node/src/main/kotlin/net/corda/node/services/statemachine/FlowCreator.kt
>          return createFlowFromCheckpoint(nonResidentFlow.runId, checkpoint)
Yeah, pass in null from pause. It will then take the number of suspends from the checkpoint as its starting reload count (because `null` was passed to `createFlowFromCheckpoint` due to the default argument).

2020-07-24 11:07 UTC, lankydan commented on node/src/main/kotlin/net/corda/node/services/statemachine/FlowCreator.kt
> +    private inline fun <reified T : Any> tryCheckpointDeserialize(
Possibly, this is where I originally added the `ReloadFlowFromCheckpoint` exception but it turned out it wasn't being thrown from here. I could add it here to be 100% safe.

2020-07-24 11:07 UTC, lankydan commented on node/src/main/kotlin/net/corda/node/services/statemachine/FlowCreator.kt
> +        reloadCheckpointAfterSuspend: Boolean
Yes, I can.

2020-07-24 11:08 UTC, lankydan commented on node/src/main/kotlin/net/corda/node/services/statemachine/SingleThreadedStateMachineManager.kt
> +            flowCreator.createFlowFromCheckpoint(flowId, checkpoint, currentState.reloadCheckpointAfterSuspendCount) ?: return
The option is also important for new flows, as it decides whether to initialise the reload count or leave it null

2020-07-24 11:09 UTC, lankydan commented on node/src/integration-test/kotlin/net/corda/node/flows/FlowReloadAfterCheckpointTest.kt
> +            assertEquals(null, reloadCounts[flowStartedByAlice])
Lol, payback for all the times I've said it to you!

2020-07-24 11:19 UTC, lankydan commented on node/src/integration-test/kotlin/net/corda/node/flows/FlowReloadAfterCheckpointTest.kt
> +class FlowReloadAfterCheckpointTest {
`TimedFlow` is an `IdempotentFlow` which I have tested so it should work in the same way. Could add a test though.

2020-07-24 17:29 UTC, lankydan commented on node/src/integration-test/kotlin/net/corda/node/flows/FlowReloadAfterCheckpointTest.kt
> +class FlowReloadAfterCheckpointTest {
Good comment. Caught a bug with retries in general and fixed it.

2020-07-27 11:42 UTC, rick-r3 reviewed
Yeah, makes sense to disentangle the reload from the retry.  Happy for others to then study in more detail and approve.

2020-07-27 14:56 UTC, kyriathar commented on node/src/integration-test/kotlin/net/corda/node/flows/FlowReloadAfterCheckpointTest.kt
> +        val reloadCounts = mutableMapOf<StateMachineRunId, Int>()
I wonder if we should make this map a `ConcurrentMap` since the hook is accessible by 2 threads at the same time (although each mapping by one thread at a time).

2020-07-27 14:58 UTC, lankydan commented on node/src/integration-test/kotlin/net/corda/node/flows/FlowReloadAfterCheckpointTest.kt
> +        val reloadCounts = mutableMapOf<StateMachineRunId, Int>()
possibly but there should never be contention on the same flow id.

2020-07-27 15:34 UTC, williamvigorr3 commented on node/src/main/kotlin/net/corda/node/services/statemachine/SingleThreadedStateMachineManager.kt
> +            flowCreator.createFlowFromCheckpoint(flowId, checkpoint, currentState.reloadCheckpointAfterSuspendCount) ?: return
Actually yes this makes sense. As you set the count to zero in createCheckpointFromLogic and only increment it when a  reloadFlowFromCheckpointAfterSuspendTransition happens.

2020-07-27 15:34 UTC, williamvigorr3 commented
LGTM!

2020-07-27 16:35 UTC, kyriathar commented on node/src/integration-test/kotlin/net/corda/node/flows/FlowReloadAfterCheckpointTest.kt
> +    fun `idempotent flow will reload from initial checkpoint after calling a suspending function when reloadCheckpointAfterSuspend is true but can't throw deserialization error from objects in the ca
This test method seems to have the exact same body with the above one unless i m missing something.

2020-07-28 07:26 UTC, kyriathar commented on node/src/integration-test/kotlin/net/corda/node/flows/FlowReloadAfterCheckpointTest.kt
> +    class MyRestartingFlow : FlowLogic<Unit>() {
How is this a restarting flow if it is to throw a `HospitalizeFlowException`?

2020-07-28 07:28 UTC, lankydan commented on node/src/integration-test/kotlin/net/corda/node/flows/FlowReloadAfterCheckpointTest.kt
> +    class MyRestartingFlow : FlowLogic<Unit>() {
Its the flow i use to hospitalise a flow so i can restart the node.

2020-07-28 07:42 UTC, kyriathar commented on node/src/integration-test/kotlin/net/corda/node/flows/FlowReloadAfterCheckpointTest.kt
> +            val flowStartedByBob = bob.rpc.stateMachineRecordedTransactionMappingSnapshot()
I think this here could be a potential flaky situation because at this point bob's flow could have ended before testing thread executes this command.

2020-07-28 07:44 UTC, kyriathar commented on node/src/integration-test/kotlin/net/corda/node/flows/FlowReloadAfterCheckpointTest.kt
> +            val flowStartedByBob = bob.rpc.stateMachineRecordedTransactionMappingSnapshot()
Actually it's transactions so i think nevermind, thought it was `stateMachinesSnapshot`.

2020-07-28 08:06 UTC, kyriathar commented on node/src/main/kotlin/net/corda/node/services/statemachine/SingleThreadedStateMachineManager.kt
> +                throw ReloadFlowFromCheckpointException(e)
If this exception is to be used by the hospital, and in general it makes sense within the statemachine, then maybe it would make sense to check if we are inside a flow/ fiber then wrap with this exception otherwise throw the inner exception raw?

2020-07-28 08:51 UTC, kyriathar submitted a review, later dismissed
LGTM

2020-07-28 15:20 UTC, kyriathar approved these changes

2020-07-28 15:22 UTC, rick-r3 approved these changes

2020-07-28 15:27 UTC, merged