EG-2055 Implement network parameters hotloading
corda/corda pull request #6517
Opened 2020-07-27 11:48 UTC by pnemeth

2020-07-27 15:57 UTC, rekalov commented
A very first feedback:
- Pls. make sure that all updated code is properly formatted; avoid adding empty lines in places which are not directly related to the changed area
- Integration test for hotloading new notary is needed

2020-07-27 15:58 UTC, rekalov commented on node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
> +                    networkParametersUpdater)
fix format

2020-07-27 16:21 UTC, rekalov commented on node/src/main/kotlin/net/corda/node/services/identity/PersistentIdentityService.kt
> +        notaryIdentityCache.addAll(notaries.map { it.identity })
This update must be atomic.

2020-07-27 16:23 UTC, rekalov commented on node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
> +            log.warn("Network parameters hotloading can be set up only if network map/compatibility zone URL is specified")
Why warning?

2020-07-27 16:59 UTC, JamesHR3 requested changes
Couple of minor things right now, but I'll review again tomorrow morning with a fresh pair of eyes.

2020-07-27 16:59 UTC, JamesHR3 commented on node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
> +import net.corda.node.services.network.NetworkParametersUpdater
Could you remove the whitespace changes you've made in this file?

2020-07-27 16:59 UTC, JamesHR3 commented on node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
> +            log.warn("Network parameters hotloading can be set up only if network map/compatibility zone URL is specified")
Will this warn for every `devMode=true` network? If so, it might be better to only warn if dev mode is false, or make it info.

2020-07-27 16:59 UTC, JamesHR3 commented on node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
> +        networkParametersUpdater?.let {
I reckon you can move this into the `else` block if you use `.apply` instead of `.let`.

2020-07-27 16:59 UTC, JamesHR3 commented on node/src/main/kotlin/net/corda/node/services/network/NetworkParametersUpdater.kt
> +    private var networkParameterUpdateListeners = mutableListOf<NetworkParameterUpdateListener>()
I think this can be a `val`, along with `notaryUpdateListeners`

2020-07-27 16:59 UTC, JamesHR3 commented on node/src/main/kotlin/net/corda/node/services/network/NetworkParametersUpdater.kt
> +        this.networkParameterUpdateListeners.add(listener)
Don't think you need `this` here

2020-07-27 16:59 UTC, JamesHR3 commented on node/src/main/kotlin/net/corda/node/services/network/NetworkParametersUpdater.kt
> +        this.networkParameters = newNetworkParameters
Don't think you need `this` again? Might also be worth highlighting that these two properties are the current parameters/hash.

2020-07-27 17:03 UTC, rekalov commented on node/src/main/kotlin/net/corda/node/services/network/NetworkParametersUpdater.kt
> +            val newSignedNetParams = networkMapClient.getNetworkParameters(newNetworkParameterHash)
NetworkParameters should be already downloaded by `NetworkMapUpdater.handleUpdateNetworkParameters()`, so it's better to pass them via `update()` avoid double download.

2020-07-27 17:09 UTC, rekalov commented on node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
> +            log.warn("Network parameters hotloading can be set up only if network map/compatibility zone URL is specified")
I would remove networkMapClient from NetworkParametersUpdater at all and pass already downloaded parameters via `NetworkParametersUpdater.update()`

2020-07-27 17:12 UTC, rekalov commented on node/src/main/kotlin/net/corda/node/services/network/NetworkParametersUpdater.kt
> +        this.networkParameters = newNetworkParameters
We need to be extremely careful about `var` and multi-threading here: even if flag day is not a frequent procedure, there can be some nasty surprises.

2020-07-27 17:45 UTC, rekalov commented
Another thing: due to 10 seconds poll interval, it's quite likely that nodes transacting with each other during "flag day" will have different network parameters for a few seconds.  Did we actually check that flows will not be disrupted in this case?

It's not obvious what is better: either to allow flow disruptions or to have service downtime.

2020-07-28 08:40 UTC, pnemeth commented on node/src/main/kotlin/net/corda/node/services/network/NetworkParametersUpdater.kt
> +            val newSignedNetParams = networkMapClient.getNetworkParameters(newNetworkParameterHash)
I'm not sure about this:

- handleUpdateNetworkParameters will download the parameters once when  a future parameters update starts to be advertised
- then the new parameters will be saved to a file when they are accepted
- later we need to retrieve this info on the flag day

2020-07-28 08:49 UTC, pnemeth commented on node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
> +            log.warn("Network parameters hotloading can be set up only if network map/compatibility zone URL is specified")
@JamesHR3 yes, better to change this to info
@rekalov I think it's related to your other comment on "NetworkParameters should be already downloaded" replied to it down there.

2020-07-28 09:12 UTC, rekalov commented on node/src/main/kotlin/net/corda/node/services/network/NetworkParametersUpdater.kt
> +            val newSignedNetParams = networkMapClient.getNetworkParameters(newNetworkParameterHash)
correct

2020-07-28 09:51 UTC, JamesHR3 requested changes
Couple more thoughts.

2020-07-28 09:51 UTC, JamesHR3 commented on node/src/main/kotlin/net/corda/node/services/network/NetworkParameterUpdateListener.kt
> +interface NetworkParameterUpdateListener {
Probably worth a kdoc on this, describing what it's for.

2020-07-28 09:51 UTC, JamesHR3 commented on node/src/main/kotlin/net/corda/node/services/network/NotaryUpdateListener.kt
> +interface NotaryListUpdateListener {
Again, worth a kdoc

2020-07-28 09:51 UTC, JamesHR3 commented on node/src/main/kotlin/net/corda/node/services/network/PersistentNetworkMapCache.kt
> +        this.notaries = notaries
There's probably a thread safety issue here. `notaryIdentities` are calculated on every call by iterating over the `notaries` list. If a thread is accessing that property and the list changes underneath it, I imagine things will break.

2020-07-28 09:51 UTC, JamesHR3 commented on node/src/main/kotlin/net/corda/node/services/network/NetworkMapUpdater.kt
> +        networkParametersUpdater?.update(globalNetworkMap.networkParameterHash)
If this is somehow `null` and the parameters are mismatched, I think this change means the node won't shut down, which seems problematic. Under what circumstances might this be `null`? It might be better to do this by following the old logic and making the updater just responsible for hotloading. If it's not there or hotloading cannot be performed, then the old shutdown logic can be used here.

2020-07-28 09:51 UTC, JamesHR3 commented on node/src/main/kotlin/net/corda/node/services/network/NetworkMapUpdater.kt
>  import net.corda.core.internal.VisibleForTesting
You've got some slightly odd whitespace changes in this file too

2020-07-28 09:51 UTC, JamesHR3 commented on node/src/test/kotlin/net/corda/node/services/network/NetworkParametersUpdaterTest.kt
> +class NetworkParametersUpdaterTest {
If you move the actual exiting logic back to where it was before and just do the logic to update things and return whether you could update (and if it succeeded), then you can beef these tests up and ensure that the right callbacks are invoked on updates that should hotload, and it reports that hotloading cannot be done when that is the case.

2020-07-28 09:56 UTC, JamesHR3 commented
> Another thing: due to 10 seconds poll interval, it's quite likely that nodes transacting with each other during "flag day" will have different network parameters for a few seconds. Did we actually check that flows will not be disrupted in this case?
> 
> It's not obvious what is better: either to allow flow disruptions or to have service downtime.

We definitely need to do this testing, and I'm expecting Peter to work on this alongside the updates to this PR. Regarding your second point, I would have thought that flows are getting disrupted either way - under the old scheme, a node might suddenly become unavailable to transact with, which would also effectively stop the flow. I guess what we need to make sure is that if it does fail, the flow can retry and succeed from its last checkpoint once everyone has updated to the latest parameters.

2020-07-28 10:10 UTC, rekalov commented on node/src/main/kotlin/net/corda/node/services/network/NetworkMapUpdater.kt
> +        networkParametersUpdater?.update(globalNetworkMap.networkParameterHash)
Agree. Actually, the name NetworkParametersUpdater is confusing, because decent part of network parameters update logic is still done inside NetworkMapUpdater. It should be rather a "hotloader"

2020-07-28 12:30 UTC, pnemeth commented on node/src/main/kotlin/net/corda/node/services/network/NetworkMapUpdater.kt
> +        networkParametersUpdater?.update(globalNetworkMap.networkParameterHash)
It is null when networkMapClient is null.
But when networkMapClient is null, we never schedule the updates, so in theory we will never get to this point in the code.

2020-07-28 14:13 UTC, rekalov commented on node/src/main/kotlin/net/corda/node/services/network/NetworkMapUpdater.kt
> +        networkParametersUpdater?.update(globalNetworkMap.networkParameterHash)
Such nullability check is just a bad coding style. Much cleaner is:
```
        if (networkMapClient == null || networkParametersUpdater == null) {
            throw CordaRuntimeException("Network map cache can be updated only if network map/compatibility zone URL is specified")
        }
```

2020-07-28 17:59 UTC, JamesHR3 requested changes

2020-07-28 17:59 UTC, JamesHR3 commented on node/src/main/kotlin/net/corda/node/services/network/NetworkMapUpdater.kt
> +        if (networkParametersUpdater == null) {
Can you not add this check to the top of the function alongside the `networkMapClient` one (as Denis suggested)? Saves you from having the same exception and message thrown in two places.

2020-07-28 17:59 UTC, JamesHR3 commented on node/src/main/kotlin/net/corda/node/services/network/NetworkMapUpdater.kt
> +            networkParametersUpdater!!.update(globalNetworkMap.networkParameterHash)
I still think you're better off doing the shutdown logic in here, and letting the updater just handle hotloading. As mentioned before, it allows you to better unit test the updater. I think you should rename this to hotloader as Denis suggests to make it clearer what it's doing.

2020-07-28 18:18 UTC, rekalov commented
> > Another thing: due to 10 seconds poll interval, it's quite likely that nodes transacting with each other during "flag day" will have different network parameters for a few seconds. Did we actually check that flows will not be disrupted in this case?
> > It's not obvious what is better: either to allow flow disruptions or to have service downtime.
> 
> We definitely need to do this testing, and I'm expecting Peter to work on this alongside the updates to this PR. Regarding your second point, I would have thought that flows are getting disrupted either way - under the old scheme, a node might suddenly become unavailable to transact with, which would also effectively stop the flow. I guess what we need to make sure is that if it does fail, the flow can retry and succeed from its last checkpoint once everyone has updated to the latest parameters.

I have a feeling that forced restart on a flag day still may be useful, so we _may_ need a switch. Though nothing definite yet, let's just keep this in mind.

2020-07-29 16:44 UTC, JamesHR3 requested changes
Couple more things.

2020-07-29 16:44 UTC, JamesHR3 commented on node/src/integration-test/kotlin/net/corda/node/services/network/NetworkMapTest.kt
> +                //isDebug = true
Either you need this or you don't - let's remove it if you don't need it.

2020-07-29 16:44 UTC, JamesHR3 commented on node/src/integration-test/kotlin/net/corda/node/services/network/NetworkMapTest.kt
> +            Thread.sleep(cacheTimeout.toMillis() * 2)
This is likely to be brittle. Corda has an `eventually` method that you can use, which does a check every so often until either some time has expired (in which case it fails) or the check passes. I think you probably want to use that here.

2020-07-29 16:44 UTC, JamesHR3 commented on node/src/integration-test/kotlin/net/corda/node/services/network/NetworkMapTest.kt
> +            Thread.sleep(cacheTimeout.toMillis() * 2)
Same here and the function below.

2020-07-29 16:44 UTC, JamesHR3 commented on node/src/main/kotlin/net/corda/node/services/network/NetworkMapUpdater.kt
> +        currentParametersHash = newParameterHash
Don't you also need to set the `networkParameters` to the current parameters here? This is part of hotloading the parameters correctly so you could argue that it should register with the hotloader to get these updated.

2020-07-29 16:44 UTC, JamesHR3 commented on node/src/main/kotlin/net/corda/node/services/network/NetworkParametersHotloader.kt
> +    @VisibleForTesting
With your tests updated, you won't need this annotation and you can make this method private.

2020-07-29 16:44 UTC, JamesHR3 commented on node/src/test/kotlin/net/corda/node/services/network/NetworkParametersHotloaderTest.kt
> +class NetworkParametersHotloaderTest {
As discussed, you'll want to make these tests use the public methods of the class under test (so `attemptHotload`) and check that listeners are correctly invoked when they should be.

2020-07-29 16:44 UTC, JamesHR3 commented on testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/network/NetworkMapServer.kt
> +
More whitespace changes.

2020-07-29 16:44 UTC, JamesHR3 commented on testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/network/NetworkMapServer.kt
> +        //private val signedNetParams by lazy { networkMapCertAndKeyPair.sign(networkParameters) }
What's going on with this change? This will force the property to be recalculated on every access, which seems quite different to the previous lazy access - is that required because they can now change? You should either revert or remove the commented out code either way.

2020-07-29 18:10 UTC, pnemeth commented on testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/network/NetworkMapServer.kt
> +        //private val signedNetParams by lazy { networkMapCertAndKeyPair.sign(networkParameters) }
There was a bug because of the lazy access:
when the network parameters changed, the signed version did not change as it was only calculated once.

2020-07-29 18:29 UTC, pnemeth commented on node/src/integration-test/kotlin/net/corda/node/services/network/NetworkMapTest.kt
> +            Thread.sleep(cacheTimeout.toMillis() * 2)
I replaced it where I could but in some cases we don't have any check to run, we just need to wait longer thant the polling interval to make sure the polling has happened.

2020-07-30 08:00 UTC, JamesHR3 requested changes
Couple of small changes and a quick question.

2020-07-30 08:00 UTC, JamesHR3 commented on node/src/integration-test/kotlin/net/corda/node/services/network/NetworkMapTest.kt
> +            Thread.sleep(cacheTimeout.toMillis() * 2)
Hmm. Is there anything you can look at to determine that the node has become aware of the scheduled parameter update? I see the old tests do this so possibly not, but it would be good to work this out.

2020-07-30 08:00 UTC, JamesHR3 commented on node/src/integration-test/kotlin/net/corda/node/services/network/NetworkMapTest.kt
> +    }
Think you want one more test where both the notary and something else changes, showing that the node shuts down.

2020-07-30 08:00 UTC, JamesHR3 commented on node/src/test/kotlin/net/corda/node/services/network/NetworkParametersHotloaderTest.kt
> +    private fun `can hotload`(newNetworkParameters: NetworkParameters) {
I think it would be good in these cases to check that listeners are called, and good to check in the other case that listeners are not called.

2020-07-30 10:27 UTC, JamesHR3 submitted a review, later dismissed
I think we're there - let's see what @rekalov and @anuragr3 think.

2020-07-30 10:44 UTC, anuragr3 commented on node/src/integration-test/kotlin/net/corda/node/services/network/NetworkMapTest.kt
> +            eventually { assertThatThrownBy { alice.rpc.networkParameters }.hasMessageContaining("Connection failure detected") }
Is this a reliable way to check that the node has shut down? What is the timeout for eventually?

2020-07-30 10:49 UTC, pnemeth commented on node/src/integration-test/kotlin/net/corda/node/services/network/NetworkMapTest.kt
> +            eventually { assertThatThrownBy { alice.rpc.networkParameters }.hasMessageContaining("Connection failure detected") }
I think so, not sure if there is a better way as tests run in a different process.
5seconds

2020-07-30 11:01 UTC, anuragr3 commented on node/src/integration-test/kotlin/net/corda/node/services/network/NetworkMapTest.kt
> +            eventually { assertThatThrownBy { alice.rpc.networkParameters }.hasMessageContaining("Connection failure detected") }
Ok. 5 seconds might be too little? and what is the polling interval? Have you checked that the test passes on your machine and eventually doesn't just give up and return failure?

2020-07-30 11:09 UTC, pnemeth commented on node/src/integration-test/kotlin/net/corda/node/services/network/NetworkMapTest.kt
> +            eventually { assertThatThrownBy { alice.rpc.networkParameters }.hasMessageContaining("Connection failure detected") }
it should be enough with the 1 sec polling interval

yes, have run the tests a good few times

2020-07-30 11:43 UTC, rekalov commented on node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
> +            log.info("Network parameters hotloading can be set up only if network map/compatibility zone URL is specified")
Can you remove this log line completely? 
It doesn't make sense to print it for setup not using network map.

2020-07-30 11:43 UTC, rekalov commented on node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
> +            this._networkParameters = networkParameters
Just for case, can you annotate `_networkParameters` with `@Volatile`?

2020-07-30 11:43 UTC, rekalov commented on node/src/main/kotlin/net/corda/node/services/identity/PersistentIdentityService.kt
> +    private var notaryIdentityCache = HashSet<Party>()
Let's add `@Volatile` just for case.

2020-07-30 11:43 UTC, rekalov commented on node/src/main/kotlin/net/corda/node/services/network/NetworkMapUpdater.kt
>      private lateinit var currentParametersHash: SecureHash
Add `@Volatile`

2020-07-30 11:43 UTC, rekalov commented on node/src/main/kotlin/net/corda/node/services/network/NetworkMapUpdater.kt
> +    private  var networkParametersHotloader: NetworkParametersHotloader? = null
This line looks misformatted. Can you make sure that you set up IDE formatting properly and re-format *all* you changes? Only changed lines, but not existing code.

2020-07-30 11:44 UTC, rekalov commented on node/src/main/kotlin/net/corda/node/services/network/NetworkMapUpdater.kt
> +        val hotloadSucceded = networkParametersHotloader!=null && networkParametersHotloader!!.attemptHotload(newParameterHash)
Pls. remove `networkParametersHotloader!=null` - we expect networkParametersHotloader always present when this method is called.

2020-07-30 11:44 UTC, rekalov commented on node/src/main/kotlin/net/corda/node/services/network/NetworkMapUpdater.kt
> + fun NetworkParameters.valueChanged(newNetworkParameters: NetworkParameters, getter: Method?): Boolean {
can it be `internal`?

2020-07-30 11:44 UTC, rekalov commented on node/src/main/kotlin/net/corda/node/services/network/NetworkParametersHotloader.kt
> +class NetworkParametersHotloader(private val networkMapClient: NetworkMapClient?,
Let's set networkMapClient mandatory.

2020-07-30 11:44 UTC, rekalov commented on node/src/main/kotlin/net/corda/node/services/network/NetworkParametersHotloader.kt
> +                                 private var networkParameters: NetworkParameters,
Let's add `@Volatile`

2020-07-30 11:44 UTC, rekalov commented on node/src/main/kotlin/net/corda/node/services/network/NetworkParametersHotloader.kt
> +        if (networkMapClient==null) return false
This can be removed.

2020-07-30 11:44 UTC, rekalov commented on node/src/main/kotlin/net/corda/node/services/network/NetworkParametersHotloader.kt
> +        }
Please remove this, it doesn't add any value (in fact a dead code).

2020-07-30 11:44 UTC, rekalov commented on node/src/main/kotlin/net/corda/node/services/network/NetworkParametersHotloader.kt
> +            onlyNotariesChanged && notaryUpdateListeners.isNotEmpty() -> true
`notaryUpdateListeners.isNotEmpty()` can be removed

2020-07-30 11:44 UTC, rekalov commented on node/src/main/kotlin/net/corda/node/services/network/PersistentNetworkMapCache.kt
> +    private val lock = ReentrantReadWriteLock(true)
This is not needed, Kotlin lists are immutable.

2020-07-30 11:44 UTC, rekalov commented on node/src/main/kotlin/net/corda/node/services/network/PersistentNetworkMapCache.kt
> +        lock.write { this.notaries = notaries }
lock can be removed by `this.notaries` should be annotated as "@Volatile"

2020-07-30 14:07 UTC, anuragr3 submitted a review, later dismissed
Looks good to me.

2020-07-30 14:22 UTC, rekalov approved these changes
LGTM

2020-07-30 14:28 UTC, JamesHR3 approved these changes
LGTM

2020-07-30 15:02 UTC, merged