INFRA-505: Move integration tests to unit tests
corda/corda pull request #6530
Opened 2020-07-30 10:04 UTC by yift-r3

Move two integration tests to a few unit tests.

2020-07-30 15:21 UTC, vkolomeyko commented on node/src/test/kotlin/net/corda/node/internal/AbstractNodeKeystoreCheckTest.kt
> +    private val path = mock<Path>()
I am a bit not sure about approach taken.

Looks like we are creating a lot of node mocking for keystore to work.
This will be yet another facility for starting node... in addition to Driver, MockNetwork, RPCDriver, etc.

If I was to chose between the two - I actually like previous version of code better as it is more concise and IMO easier to understand.

Possibly changing this test to a unit test can be done, but first we need to refactor Keystore functionality and make it unit testable.

2020-07-30 22:37 UTC, rnicoll commented on node/src/test/kotlin/net/corda/node/internal/AbstractNodeKeystoreCheckTest.kt
> +    private val path = mock<Path>()
This is simply unwrapping the structures around the `node.start()` isn't it?

2020-07-31 09:58 UTC, yift-r3 commented on node/src/test/kotlin/net/corda/node/internal/AbstractNodeKeystoreCheckTest.kt
> +    private val path = mock<Path>()
Mostly for the node init

I can remove the validateKeyStores and getCertificateStores to be an internal static method, which will reduce the number of mocks we need to only the obvious ones.

The previous version tested a lot fewer use cases and took a lot more resources and time to do it.

2020-08-03 09:48 UTC, vkolomeyko commented on node/src/test/kotlin/net/corda/node/internal/AbstractNodeKeystoreCheckTest.kt
> +class AbstractNodeKeystoreCheckTest {
IMO - test looks much better now, focusing on the right node subsystem: Keystores

Perhaps it would be worth restoring original test name: `NodeKeystoreCheckTest`
"Abstract" in the name does not add much value, IMO.

2020-08-03 10:03 UTC, rekalov commented on node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
> +internal fun NodeConfiguration.initKeyStores(cryptoService: CryptoService, log: Logger): X509Certificate {
As long a we are moving this code, shouldn't be better to put it into a separate file, e.g. `NodeKeyStoreUtilities.kt`?

2020-08-03 10:08 UTC, rekalov commented on node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
> +                    "or if you don't have one yet, fill out the config file and run corda.jar initial-registration."
Do we really need to pass logger as an argument?

Instead, we can just catch `IOException` here and wrap it with `IllegalArgumentException` passing this text and the original exception to it.

2020-08-03 10:51 UTC, yift-r3 commented on node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
> +                    "or if you don't have one yet, fill out the config file and run corda.jar initial-registration."
This will change the behavior. Currently, if we get an IOException we will log "IO exception while trying to validate keystores and truststore" and then throw an exception with another text ("One or more keyStores (identity or TLS) or trustStore not found...").

2020-08-03 11:23 UTC, rekalov commented on node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
> +                    "or if you don't have one yet, fill out the config file and run corda.jar initial-registration."
Yes, this will. `IllegalArgumentException` is also printed as an error in log, so currently we always print both "IO exception while trying to validate" and "One or more keyStores" errors. The first message itself is useless, so idea is just to leave the second one but print it with combined stack.

But I agree with your point, let's not do this change in late 4.6.

2020-08-03 11:49 UTC, yift-r3 commented on node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
> +                    "or if you don't have one yet, fill out the config file and run corda.jar initial-registration."
Can you create a ticket?

2020-08-03 11:51 UTC, rekalov commented on node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
> +    internal data class AllCertificateStores(val trustStore: CertificateStore, val sslKeyStore: CertificateStore, val identitiesKeyStore: CertificateStore)
Let's move this one as well

2020-08-03 12:10 UTC, rekalov commented on node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
> +                    "or if you don't have one yet, fill out the config file and run corda.jar initial-registration."
I'll fix this in 4.7 within other planned PKI related changes for keystore loading.

Meanwhile, how about to remove `log` arguments and use `loggerFor<NodeConfiguration>()` for "IO exception"?
This will be still a little change of behavior for logging category (current one uses `Node` logger), but it's OK.

2020-08-03 12:11 UTC, rekalov commented on node/src/main/kotlin/net/corda/node/internal/NodeKeyStoreUtilities.kt
> +internal fun NodeConfiguration.validateKeyStores(log: Logger): X509Certificate {
Can we make it private? Same for getCertificateStores.

2020-08-03 12:12 UTC, rekalov commented on node/src/main/kotlin/net/corda/node/internal/NodeKeyStoreUtilities.kt
> +internal fun NodeConfiguration.validateKeyStores(log: Logger): X509Certificate {
And for AllCertificateStores

2020-08-03 12:17 UTC, rekalov commented on .gitignore
> +.dependx/
Is this on purpose?

Same Q for lib/quasar.jar (github doesn't allow to comment on binary file change)

2020-08-03 12:20 UTC, rekalov commented on node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
> +}
please remove this empty line change, if possible

2020-08-03 12:25 UTC, yift-r3 commented on .gitignore
> +.dependx/
This one is, the build keep creating this directory which should clearly be ignored.

The lib/quasar.jar  is not. I have no idea why the build keep changing this file.

2020-08-03 12:31 UTC, rekalov approved these changes
Thank you, looks good.

2020-08-03 12:33 UTC, rekalov commented on .gitignore
> +.dependx/
Actually, one more minor thing - can you comment what is that and put it into proper category in `.gitignore`?

2020-08-03 12:34 UTC, rekalov requested changes
I have one more thing, sorry for chaotic comments.

Newly added fine-gran tests and small re-factoring are fine. But how do we conceptually make sure that initKeyStores() is properly called on the node start after removal of integration tests?

@rnicoll , what do you think?

2020-08-03 13:00 UTC, rekalov commented on .gitignore
> +.dependx/
Well, the comment like "Dependx directory" is a bit useless, as it doesn't tell you more than `.dependx` dir name itself.
What I mean is to explain the origin of it (if it's a gradle plugin - put it in a proper dir) and also why you are removing it.

2020-08-03 13:22 UTC, yift-r3 commented on .gitignore
> +.dependx/
I'm not removing it, I'm ignoring it.

I'm not sure what it is, all I have is https://r3-cev.atlassian.net/browse/INFRA-209 that created it

2020-08-03 13:32 UTC, rekalov commented on .gitignore
> +.dependx/
@dgounaris , can you explain what is it `.dependx` folder for and if it's OK to add it to `.gitignore`?

2020-08-03 13:49 UTC, dgounaris commented on .gitignore
> +.dependx/
Was a folder that was generated by a plugin we created at some point to identify dependencies between packages/modules. Not sure if it needs to be there at this point, as the plugin isn't quite used anymore.

2020-08-03 13:55 UTC, rekalov commented on .gitignore
> +.dependx/
Thank you, let's revert this change then.

2020-08-03 14:22 UTC, yift-r3 commented on .gitignore
> +.dependx/
The plugin is still there, still running, and still create the directory. There is no reason to revert this until we remove the plugin.

2020-08-03 14:31 UTC, rekalov commented on .gitignore
> +.dependx/
I don't mind either way, just document it clearly, e.g. `# gradle-dependx plugin` or so.

2020-08-03 15:45 UTC, rekalov submitted a review, later dismissed

2020-08-03 15:47 UTC, rekalov commented
`BootTests` looks reasonable substitution for removed integration tests. So, OK.

2020-08-06 10:01 UTC, rnicoll commented
So it's a two part answer here; on the one hand, I think the dozens of tests which spin up full nodes then interact with their node info will cover this.

The other part, however, is that I would look to unit tests to stop accidental errors creeping in, rather than model how the code is written currently. Having a unit test for `initKeyStores()` (if we don't elsewhere) would be good, but I'd consider it unlikely someone would accidentally cut the call to `initKeyStores()` out later, and it's low value to test for.

2020-08-06 11:23 UTC, rnicoll approved these changes

2020-08-06 14:14 UTC, rekalov approved these changes

2020-08-06 14:16 UTC, merged