EG-3456: Make network parameters path configurable
corda/corda pull request #6531
Opened 2020-07-30 12:55 UTC by YashNabar

The network parameters of a node are currently housed inside the node's base directory. This should be configurable, so that the network parameters file may be stored at the location specified by the node configuration. This change addresses this issue by introducing `networkParametersPath` and using the path specified by this field to store the network parameters. In case a path is not specified, the node's base directory is used by default. The specified path may be relative or absolute, and directories on the path that do not exist will be created accordingly. The file name continues to be the one defined by `NETWORK_PARAMS_FILE_NAME`. The change has been manually tested.

2020-07-30 14:03 UTC, JamesHR3 requested changes
You'll want to add some automated testing to this too - there should be some configuration tests that you can extend to check the value is parsed correctly and defaults to the correct value. You should also be able to integration test this I would have thought. Have a look and see if you can find the right place for this.

2020-08-01 16:44 UTC, jmacmahonr3 submitted a review, later dismissed
LGTM

2020-08-05 13:11 UTC, JamesHR3 requested changes
Couple of thoughts.

2020-08-05 13:11 UTC, JamesHR3 commented on node/src/test/kotlin/net/corda/node/services/config/NodeConfigurationImplTest.kt
> +    @Test(timeout=3_000)
There have been some test cases failing recently on timeouts of this size, despite the relative simplicity of the test. Probably worth bumping this up a bit - we're in a position right now where reliability is a much greater concern than execution time.

2020-08-05 13:11 UTC, JamesHR3 commented on node/src/test/kotlin/net/corda/node/services/config/NodeConfigurationImplTest.kt
> +    fun `network parameters path defaults to base directory`() {
Might be worth running adding a second part to this case where you override the base directory and double check that the network parameters path ends up pointing to the specified base directory.

2020-08-05 13:11 UTC, JamesHR3 commented on node/src/main/kotlin/net/corda/node/services/config/schema/v1/V1NodeConfigurationSpec.kt
> +        val networkParametersPath = config[networkParametersPath] ?: baseDirectoryPath
Do you need to resolve this relative to the base directory as with the `cordappDirectories` field?

2020-08-05 13:11 UTC, JamesHR3 commented on docker/src/docker/Dockerfile
> +FROM azul/zulu-openjdk:8u242
This doesn't seem related to the bug - why does this need to be changed?

2020-08-11 11:49 UTC, JamesHR3 requested changes
Getting there!

2020-08-11 11:49 UTC, JamesHR3 commented on node/src/main/kotlin/net/corda/node/internal/NetworkParametersReader.kt
> +                              private val baseDirectory: Path,
Do you actually need the `baseDirectory` any more? Haven't looked in detail but it looks unused to me.

2020-08-11 11:49 UTC, JamesHR3 commented on node/src/test/kotlin/net/corda/node/services/config/NodeConfigurationImplTest.kt
> +    fun `network parameters path is set as specified by node config with overridden base directory`() {
Can you not reuse the `getConfig` function in this test?

2020-08-11 11:49 UTC, JamesHR3 commented on node/src/test/kotlin/net/corda/node/services/config/NodeConfigurationImplTest.kt
> +        val rawConfig = ConfigFactory.parseResources("working-config.conf", ConfigParseOptions.defaults().setAllowMissing(false))
Same with this test on the `getConfig` function.

2020-08-12 13:59 UTC, JamesHR3 submitted a review, later dismissed
LGTM!

2020-08-12 14:18 UTC, roastario commented
@YashNabar 
I've retargetted this for 4.7 as 4.6 has "shipped" - all looks good.

2020-08-12 14:46 UTC, JamesHR3 submitted a review, later dismissed
That's cool. Wasn't sure if it was required in 4.6, but if it's not needed there let's put it in 4.7.

2020-08-12 15:15 UTC, rekalov commented on build.gradle
> +    ext.jackson_version = '2.9.7'
Wrong merge?

2020-08-12 15:18 UTC, rekalov commented
Where is the original request coming from?
It's not a bug, as stated by EG-3456, but a new feature with customer's facing behavior (config change).
So it has to be agreed with product and documented.

2020-08-12 15:21 UTC, JamesHR3 commented
I believe @roastario needs it for some deployment work. You're right it's not really a bug though. Could you comment Stefano?

2020-08-12 16:32 UTC, roastario commented
This came from the deployment work, network parameters must be shared by multiple components to ensure that message size limits are respected.

2020-09-07 08:48 UTC, roastario approved these changes

2020-09-07 08:49 UTC, merged

2020-09-10 18:24 UTC, rekalov commented
How about to merge this to ENT 4.7?