INFRA-504: Replace out of process nodes with in process nodes
corda/corda pull request #6538
Opened 2020-07-31 10:28 UTC by benmcmahon100

Make tests use in process nodes wherever possible in the hopes of a substantial speed increase.

NodeRegistrationTest.`node registration correct root cert`
 - Before: 45s 252ms (first run) | 45s 666ms (second run)
 - After: 18s 820ms (first run) | 17S 850ms (second run)
**~60% speedup**

GenericReturnFailureReproductionIntegrationTest.flowShouldReturnGenericList
 - Before: 18s 996ms (first run) | 18s 560ms (second run)
 - After: 22s 585ms (first run) | 18s 818ms (second run)
**No real difference on this one outside of jitter**

CordappScanningDriverTest.`sub-classed initiated flow pointing to the same initiating flow as its super-class`
 - Before: 26s 964ms (first run) | 28s 500ms (second run)
 - After: 22s 689ms (first run) | 23s 162ms (second run)
**~18% Speedup**

2020-07-31 12:00 UTC, vkolomeyko submitted a review, later dismissed

2020-08-04 10:18 UTC, vkolomeyko submitted a review, later dismissed

2020-08-05 10:13 UTC, rnicoll commented
We've actually been just talking in the leads meeting about how issues with https://r3-cev.atlassian.net/browse/CORDA-3933 get worse with in-process nodes, so may need to hold off on squashing this until we can get the serialization environment under control, at risk of making things less stable.

2020-10-07 13:40 UTC, vkolomeyko reviewed
Probably need re-targeting to 4.7

2020-10-07 16:47 UTC, rnicoll commented on node/src/integration-test/kotlin/net/corda/node/services/events/ScheduledFlowIntegrationTests.kt
> +
```suggestion

```
Just nitpicking whitespace changes

2020-10-07 16:59 UTC, rnicoll submitted a review, later dismissed
Approved in theory, @vkolomeyko ready for you to review

2020-10-08 08:09 UTC, vkolomeyko commented
CI reports failure of `test that when states are being spent at the same time that schedules trigger everything is processed – net.corda.node.services.events.ScheduledFlowIntegrationTests` which probably needs investigation.

2020-10-08 09:21 UTC, roastario requested changes
Can we run this PR HEAVILY?

Inprocess nodes trigger the gradle exit (1) condition which breaks everything. We should be using inprocess as little as possible.

2020-10-08 09:36 UTC, benmcmahon100 commented
@roastario what do you mean by run heavily? This change was ran in a linear build that looped over a weekend earlier in it's life cycle, and it passed the majority of times. Targeting at 4.7 seems to have made it unreliable

2020-10-08 09:59 UTC, benmcmahon100 commented
I've realized there is a mistake in this PR. Will correct now

2020-10-08 10:03 UTC, benmcmahon100 commented
There is a change in this PR that should already be merged from 4.6, interestingly that's the one that fails

2020-10-08 13:48 UTC, benmcmahon100 commented
I've pulled the change that should've been merged from 4.6 out. so this pr is now as it should be

2020-10-08 14:55 UTC, rnicoll commented
Running the tests a few times to confirm stability @roastario but seems okay so far

2020-10-12 13:14 UTC, rnicoll approved these changes

2020-10-12 13:14 UTC, rnicoll commented
@roastario Are you okay with this now?

2020-10-12 15:58 UTC, roastario approved these changes

2020-10-12 16:00 UTC, merged