EG-3458 - Missing onError implementation message logged in the node log file with ERROR level
corda/corda pull request #6594
Opened 2020-08-07 12:54 UTC by conalsmith-r3

…og file with ERROR level - initial changes

👮🏻👮🏻👮🏻 !!!! DESCRIBE YOUR CHANGES HERE !!!! DO NOT FORGET !!!! 👮🏻👮🏻👮🏻

# PR Checklist:

- [ ] Have you run the unit, integration and smoke tests as described [here](https://docs.corda.net/head/testing.html)?
- [ ] If you added public APIs, did you write the JavaDocs?
- [ ] If the changes are of interest to application developers, have you added them to the [changelog](https://docs.corda.net/head/changelog.html) (`/docs/source/changelog.rst`), and potentially the [release notes](https://docs.corda.net/head/release-notes.html) (`/docs/source/release-notes.rst`)?
- [ ] If you are contributing for the first time, please read the [contributor agreement](https://docs.corda.net/head/contributing.html) now and add a comment to this pull request stating that your PR is in accordance with the [Developer's Certificate of Origin](https://docs.corda.net/head/contributing.html#merging-the-changes-back-into-corda).

Thanks for your code, it's appreciated! :)

2020-08-07 13:44 UTC, JamesHR3 requested changes
One small observation. I wouldn't mind Dan taking a quick look at this, as he's done some stuff around making observables more robust that perhaps could be leveraged.

2020-08-07 13:44 UTC, JamesHR3 commented on node/src/main/kotlin/net/corda/node/services/network/NetworkMapUpdater.kt
> +                .retryWhen { t -> t.delay(defaultWatchNodeInfoFilesRetryInterval.seconds, TimeUnit.SECONDS, nodeInfoWatcher.scheduler) }
Does `delay` take a `long`? If so I think you can just keep the retry interval a constant rather than providing a `Duration` here.

2020-08-07 13:48 UTC, JamesHR3 commented
Couple of other things:
 - We generally don't do patches to older OS releases, so I think you'll want to retarget this to 4.6
 - Similarly, I don't think we're too concerned about this in ENT versions before 4.6, so a merge after this has gone in should be sufficient.

2020-08-07 14:10 UTC, conalsmith-r3 commented on node/src/main/kotlin/net/corda/node/services/network/NetworkMapUpdater.kt
> +                .retryWhen { t -> t.delay(defaultWatchNodeInfoFilesRetryInterval.seconds, TimeUnit.SECONDS, nodeInfoWatcher.scheduler) }
Yea good spot, no point in using a Duration here thanks!

2020-08-10 13:10 UTC, conalsmith-r3 commented
I created https://github.com/corda/corda/pull/6602 to retarget this change for `release/os/4.6`

2020-08-11 13:00 UTC, conalsmith-r3 commented
So in my research into using the Resilient Observable/Subscriber, I couldn't quite get it to work, and digging deeper I found that this was because we are using `Observable.interval(...)` followed by a `.map(...)` function, this map function registers its own subscriber (`OnSubscribeMap.MapSubscriber`) before our ResilientSubscriber, and forces the observable to be killed and unsubscribed when exceptions come from `pollDirectory()`. I don't think using the ResilientSubscriber is applicable to this scenario.

I think the original change here is the tidiest solution, we have a nice warning message and delayed retry interval without trickery in the pollDirectory() function. 

Another possible solution is just catch the NoSuchFileException (or IOException) in the `pollDirectory()` function, we could output a log message and return an empty list for the NodeInfoUpdates. This should keep the observable alive because we're catching the error before `onError()` can be invoked, but I think this is a bit of trickery as if a different exception occurs we'll get the nasty "No onError handler on observable" error message again and this is part of the bug we wanted to fix. The original solution won't have this.

2020-08-13 09:25 UTC, JamesHR3 commented
Ah you didn't actually need to make a new one to retarget, you can just change the target branch on the PR :). Not to worry! You might as well close this one in that case.

2020-08-13 09:29 UTC, closed without merging

2020-08-13 09:32 UTC, conalsmith-r3 commented
Closing this as I opened https://github.com/corda/corda/pull/6602 instead. I thought there might be problems re-targeting the base branch to a different release and create a huge diff, but that's only the case if we're re-targeting to an older release