EG-3402 Removed the dependency 'io.spring.dependency-management' from the gradle files in irs-demo
corda/corda pull request #6596
Opened 2020-08-07 16:48 UTC by filipesoliveira

**Bug Reported**
It has been reported that the dependency 'io.spring.dependency-management' was causing build issues.

**Bug Summary**
It was not possible to reproduce the issue during testing because the bug reported only happens sometimes. However, it was noticed that the dependency 'io.spring.dependency-management' was not needed for the irs-demo project. The dependency was removed from the two gradle files present in irs-demo project.

**Tests cases**
- A clean build was performed to ensure the irs-demo project still builds correctly without the dependency 'io.spring.dependency-management'.

2020-08-08 21:29 UTC, chrisr3 requested changes
>     * A clean build was performed to ensure the irs-demo project still builds correctly without the dependency 'io.spring.dependency-management'.

If Corda still builds successfully then I suspect that something must still be applying the `io.spring.dependency-management` plugin, because you have not also deleted [the `dependencyManagement` block](https://docs.spring.io/dependency-management-plugin/docs/current/reference/html/) from `irs-demo/web/build.gradle`:
```gradle
dependencyManagement {
    dependencies {
        dependency "org.apache.logging.log4j:log4j-slf4j-impl:$log4j_version"
        dependency "org.apache.logging.log4j:log4j-core:$log4j_version"
        dependency "org.apache.logging.log4j:log4j-api:$log4j_version"
    }
}
```
I think you should reproduce this bug before submitting a PR for it. What if the real problem is something else entirely, and breaking the `io.spring.dependency-management` plugin is just a symptom?

2020-08-09 10:58 UTC, chrisr3 commented
I have added some context about this issue to the JIRA. Please do not merge this PR.

2020-08-10 08:03 UTC, mnesbit commented
Also note that we know the spring framework instruments our code and does odd things such as adding synthetic close methods. Thus the IRS demo has a dual purpose of testing corda in an environment where spring boot is active.

2020-08-20 09:22 UTC, filipesoliveira commented
PR was closed because the commits from this PR are no longer valid. A new PR will be created with a new solution.

2020-08-20 09:22 UTC, closed without merging