EG-3458 - Missing onError implementation message logged in the node l…
corda/corda pull request #6602
Opened 2020-08-10 09:38 UTC by conalsmith-r3

Changes for EG-3458 (https://r3-cev.atlassian.net/browse/EG-3458)

I found that when the additional-node-infos folder is missing (as in the case exposed by the network bootstrapper), we get an Exception and the observable which polls the directory dies. This means we cannot pick up network map updates from the additional-node-infos directory even if we recreate it. It requires a node restart to restart the observable.

These changes re-subscribe to the observable and keep retrying after 10 second delays with warning messages output in the log. This means after getting the error and adding the folder we can pick up network map updates.

It also means if the error occurs in when running nodes in a bootstrapped network, the node won't need to be restarted.

The test will delete the folder in the JimFS in memory filestore, recreate the folder, and assert that new updates get picked up.

Plan for merging:
- this -> release/os/4.6
- release/os/4.6 -> release/ent/4.6

# PR Checklist:

- [ ] Have you run the unit, integration and smoke tests as described [here](https://docs.corda.net/head/testing.html)?
- [ ] If you added public APIs, did you write the JavaDocs?
- [ ] If the changes are of interest to application developers, have you added them to the [changelog](https://docs.corda.net/head/changelog.html) (`/docs/source/changelog.rst`), and potentially the [release notes](https://docs.corda.net/head/release-notes.html) (`/docs/source/release-notes.rst`)?
- [ ] If you are contributing for the first time, please read the [contributor agreement](https://docs.corda.net/head/contributing.html) now and add a comment to this pull request stating that your PR is in accordance with the [Developer's Certificate of Origin](https://docs.corda.net/head/contributing.html#merging-the-changes-back-into-corda).

Thanks for your code, it's appreciated! :)

2020-08-10 13:25 UTC, conalsmith-r3 commented
I'm looking into the ResilientSubscriber class to see if we can make use of this here.

2020-08-11 13:03 UTC, conalsmith-r3 commented
So in my research into using the Resilient Observable/Subscriber, I couldn't quite get it to work, and digging deeper I found that this was because we are using `Observable.interval(...)` followed by a `.map(...)` function, this map function registers its own subscriber (`OnSubscribeMap.MapSubscriber`) before our ResilientSubscriber, and forces the observable to be killed and unsubscribed when exceptions come from `pollDirectory()`. I don't think using the ResilientSubscriber is applicable to this scenario.

I think the original change here is the tidiest solution, we have a nice warning message and delayed retry interval without trickery in the pollDirectory() function. 

Another possible solution is just catch the NoSuchFileException (or IOException) in the `pollDirectory()` function, we could output a log message and return an empty list for the NodeInfoUpdates. This should keep the observable alive because we're catching the error before `onError()` can be invoked, but I think this is a bit of trickery - if a different exception occurs we'll get the nasty "No onError handler on observable" error message again, the observable will be killed, and this nasty console output is part of the bug we wanted to fix.

2020-08-11 13:16 UTC, mnesbit commented on node/src/main/kotlin/net/corda/node/services/network/NetworkMapUpdater.kt
> +                .doOnError { logger.warn("Error encountered while polling directory for network map updates, " +
Observables do not do anything much sensible after calling onError they usually just call onComplete immediately thus ending all future streaming. So you do need to check that after a transient error is logged it doesn't prevent future polling.

2020-08-11 13:49 UTC, conalsmith-r3 commented on node/src/main/kotlin/net/corda/node/services/network/NetworkMapUpdater.kt
> +                .doOnError { logger.warn("Error encountered while polling directory for network map updates, " +
Thanks Matthew, according to the documentation the `.retryWhen(...)` operator should resubscribe to and mirror the source observable, and in testing I've seen that our subscriber does in fact resubscribe after an exception and the warning message in `.doOnError` does get output too.

2020-08-21 09:26 UTC, palade requested changes
Can you please add the links to the documentation that was followed to implement this solution?

2020-08-21 15:13 UTC, palade submitted a review, later dismissed
Couple of thoughts on the proposed solution

2020-08-21 15:13 UTC, palade commented on node/src/main/kotlin/net/corda/node/services/network/NetworkMapUpdater.kt
> +                .retryWhen { t -> t.delay(defaultWatchNodeInfoFilesRetryIntervalSeconds, TimeUnit.SECONDS, nodeInfoWatcher.scheduler) }
Some thoughts to better understand the proposed solution:

1. I think the body of the `retryWhen` can be shortened:

```
.retryWhen { t -> t.delay(defaultWatchNodeInfoFilesRetryIntervalSeconds, TimeUnit.SECONDS) }  

```

and the visibility of the scheduler can be reverted to private. Why is access to the scheduler in the nodeInfoWatcher necessary?

2. Most of the documented approaches use a flatMap inside the `retryWhen`:

```
.retryWhen { errors ->
                    logger.warn("Error encountered while polling directory for network map updates, " +
                            "will retry in $defaultWatchNodeInfoFilesRetryIntervalSeconds seconds")
                    errors.flatMap { Observable.timer(defaultWatchNodeInfoFilesRetryIntervalSeconds, TimeUnit.SECONDS) }
                }
```

 - This allows for the logging to also be performed inside the `retryWhen` body.
 - Allows to defer the decision until you know what kind of error you are dealing with. This means that if NoSuchFileException is thrown, will be handled differently in case if there is a different exception.


3. I think if the `retryWhen{}` is used, then the observer will be re-subscribed to a new observable until the expected event happens.  A counter may be used to keep track of number of retries and stop retrying after a certain number of times.

2020-08-25 11:55 UTC, conalsmith-r3 commented on node/src/main/kotlin/net/corda/node/services/network/NetworkMapUpdater.kt
> +                .retryWhen { t -> t.delay(defaultWatchNodeInfoFilesRetryIntervalSeconds, TimeUnit.SECONDS, nodeInfoWatcher.scheduler) }
The `scheduler` is for testing purposes,to advance time and assert the observable picks up file changes after the delay. I'm not sure of a better way, I'm not sure if we can advance time on the default scheduler (`computationScheduler` for `delay()`)

Logging in `doOnError` is just a way to separate concerns, but I do like your idea, currently, certain exceptions could be swallowed and we'll never know what happened.

It is quite a lot of warnings in the output logs, I think some incrementing backoff would be a good idea, maybe adding 10s every time to a max of 1 minute or so. Capping the retries will mean `onError` gets invoked, Observable will get removed and node will have to be restarted to pick up additional-node-info updates. 

So how about if I do the following?
1. in retryWhen, add more generic error message and the stacktrace for other exceptions
2. add an incrementing backoff (+10 seconds capped at 60 seconds delay) to reduce spam on the logs

2020-09-01 16:01 UTC, anuragr3 requested changes

2020-09-01 16:01 UTC, anuragr3 commented on node/src/test/kotlin/net/corda/node/services/network/NetworkMapUpdaterTest.kt
> +        advanceTime()
Are the two advanceTime calls intentional?

2020-09-01 16:01 UTC, anuragr3 commented on node/src/main/kotlin/net/corda/node/services/network/NetworkMapUpdater.kt
> +                .retryWhen { t -> t.delay(defaultWatchNodeInfoFilesRetryIntervalSeconds, TimeUnit.SECONDS, nodeInfoWatcher.scheduler) }
I assume the retry with increasing backoff fun was never added? Then why do we need the previousConsecutiveErrors at all?

2020-09-01 16:02 UTC, conalsmith-r3 commented
I spoke with JamesH and Anurag, we decided we'd keep this simple as it isn't critical to the functionality of the node.

I'm reducing the number of logs output while maintaining the retry logic. It will just output one warn every time the error happens. It still retries every 10 seconds.

I think the atomic boolean is necessary as the observable is asynchronous and will be running on a different thread

2020-09-01 16:05 UTC, conalsmith-r3 commented on node/src/test/kotlin/net/corda/node/services/network/NetworkMapUpdaterTest.kt
> +        advanceTime()
Yes these should trigger two retries but we should see only 1 warning message in the logs. I confirmed with debugging. I did think about testing the log messages by creating a custom log appender and asserting one WARN log followed by the INFO log, but I thought it wasn't necessary

2020-09-01 16:07 UTC, conalsmith-r3 commented on node/src/main/kotlin/net/corda/node/services/network/NetworkMapUpdater.kt
> +                .retryWhen { t -> t.delay(defaultWatchNodeInfoFilesRetryIntervalSeconds, TimeUnit.SECONDS, nodeInfoWatcher.scheduler) }
No backoff logic was not added. The previousConsecutiveErrors could be named better, it just keeps track of there being a previous error so we only log the first error, and only log the first succeeded, and if further errors happen we log them too.

2020-09-01 16:15 UTC, anuragr3 approved these changes, later dismissed

2020-09-01 18:13 UTC, anuragr3 submitted a review, later dismissed
LGTM. These are changes from master right?

2020-09-02 11:50 UTC, anuragr3 approved these changes

2020-09-02 12:58 UTC, rekalov approved these changes
Looks good

2020-09-02 13:05 UTC, palade approved these changes

2020-09-02 14:21 UTC, merged