ENT-5652 Allow schema property in node.conf
corda/corda pull request #6613
Opened 2020-08-11 10:19 UTC by davidjgolding

The `schema` property for `node.conf` has been introduced to OS, furthering the harmonisation between OS and Enterprise.

2020-08-12 09:11 UTC, rick-r3 commented on node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/CordaPersistence.kt
> +        val schema: String = Defaults.schema,
I think it is nullable in Enterprise, and defaults to `null` there.  Might as well make the same unless I'm missing something?

2020-08-12 09:26 UTC, davidjgolding commented on node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/CordaPersistence.kt
> +        val schema: String = Defaults.schema,
Yes that is the case with Enterprise, however, didn't @mnesbit suggest in Monday's standup to default to "sa"?

2020-08-27 11:03 UTC, fowlerrr commented
@blsemo can you have a look over this one?

2020-08-28 11:06 UTC, blsemo requested changes
I think this would work with H2, not so sure about Postgres. I also have a few question around the changes to demobench.

2020-08-28 11:06 UTC, blsemo commented on node-api/src/main/kotlin/net/corda/nodeapi/internal/persistence/CordaPersistence.kt
> +        val schema: String = Defaults.schema,
I am not convinced by this - we want to support Postgres as a first class DB as well, and sa is not good schema name for that.

2020-08-28 11:06 UTC, blsemo commented on tools/demobench/src/main/kotlin/net/corda/demobench/model/NodeConfig.kt
> +        val database: DatabaseConfig = DatabaseConfig(),
Hmm, how does this deal with `dataSourceProperties` now? Also, why do we now need to know about the `DatabaseConfig` class?

2020-08-28 11:06 UTC, blsemo commented on tools/demobench/src/test/kotlin/net/corda/demobench/model/NodeConfigTest.kt
> +                database = DatabaseConfig(schema = "sa"),
Does setting schema to "sa" make any difference when the default is already "sa"?

2020-08-28 15:44 UTC, davidjgolding commented
@blsemo I've simplified it and used `null` instead of `sa`

2020-09-01 17:12 UTC, blsemo commented
So what happens with the `schema` value now once it has been set? Is it used anywhere?

2020-09-02 09:10 UTC, davidjgolding commented
No it's not used anywhere - we assumed it was a missed bit of harmonisation so moved the property over to OS

2020-11-25 17:48 UTC, closed without merging