INFRA-604: Switch tests to use database snapshots
corda/corda pull request #6671
Opened 2020-08-27 08:46 UTC by lockathan

Created a database snapshot of a clean Corda OS 4.5.1 database, which can now be used for testing by both the node driver and mock network.

The MockNetwork was changed from using an in memory database to using an on disk database, and makes use of the snapshot to speed up setup times.

The Node Driver was changed from defaulting to an in-memory database to defaulting to an on-disk database. Tests that do not specify the type of database to use will thus use an on-disk database. Tests that opt in for an in-memory database will continue to use an in-memory database as before.

The database snapshots are copied to the node directory inside the build folder, therefore, they should be cleaned up after a build.

2020-08-27 09:05 UTC, yift-r3 reviewed
How was the db file created? Can we create it using Gradle?

2020-08-27 09:05 UTC, yift-r3 commented on testing/node-driver/src/main/kotlin/net/corda/testing/driver/Driver.kt
> +        val inMemoryDB: Boolean = false,
Will this break backward compatibility?

2020-08-27 09:05 UTC, yift-r3 commented on testing/node-driver/src/main/kotlin/net/corda/testing/node/DatabaseSnapshot.kt
> +        var fileName = "/databasesnapshots/${previousCordaVersion}/persistence.mv.db"
val

2020-08-27 09:05 UTC, yift-r3 commented on testing/node-driver/src/main/kotlin/net/corda/testing/node/DatabaseSnapshot.kt
> +        println("Copying from resource $fileName")
Do we need the println?

2020-08-27 09:05 UTC, yift-r3 commented on testing/node-driver/src/main/kotlin/net/corda/testing/node/DatabaseSnapshot.kt
> +            stream = resourceUri.openStream()
Why not just retrun resourceUri.openStream()

2020-08-27 09:05 UTC, yift-r3 commented on testing/node-driver/src/main/kotlin/net/corda/testing/node/DatabaseSnapshot.kt
> +            println("IOException occurred getting resource: ${e.message}")
println

2020-08-27 09:05 UTC, yift-r3 commented on testing/node-driver/src/main/kotlin/net/corda/testing/node/DatabaseSnapshot.kt
> +        if (!Files.exists(baseDirectory)) {
Do we actually need the if? Why not just createDirectories?

2020-08-27 09:05 UTC, yift-r3 commented on testing/node-driver/src/main/kotlin/net/corda/testing/node/DatabaseSnapshot.kt
> +        println("Copying stream to path: $path")
println

2020-08-27 09:05 UTC, yift-r3 commented on testing/node-driver/src/main/kotlin/net/corda/testing/node/DatabaseSnapshot.kt
> +        try {
do we need the try catch?

2020-08-27 09:05 UTC, yift-r3 commented on testing/node-driver/src/main/kotlin/net/corda/testing/node/MockServices.kt
> +            DatabaseSnapshot.copyDatabaseSnapshot(Paths.get("./build/mocknetworktestdb/${nodeName}"))
Maybe temporary directory and not in build?

2020-08-27 09:19 UTC, lockathan commented on testing/node-driver/src/main/kotlin/net/corda/testing/node/DatabaseSnapshot.kt
> +        println("Copying from resource $fileName")
I believe the println statements will be useful in debugging this feature. They assisted me in getting this to work in the first place. So, I'd recommend leaving them in for now.

2020-08-27 09:20 UTC, lockathan commented on testing/node-driver/src/main/kotlin/net/corda/testing/node/MockServices.kt
> +            DatabaseSnapshot.copyDatabaseSnapshot(Paths.get("./build/mocknetworktestdb/${nodeName}"))
Where would you suggest though? This must be compatible with all build systems, from developers running Windows to Jenkins. I selected build because everything in it is assumed to be temporary.

2020-08-27 09:22 UTC, yift-r3 commented on testing/node-driver/src/main/kotlin/net/corda/testing/node/MockServices.kt
> +            DatabaseSnapshot.copyDatabaseSnapshot(Paths.get("./build/mocknetworktestdb/${nodeName}"))
We can use Files.createTempDir()

2020-08-27 14:12 UTC, lockathan commented on testing/node-driver/src/main/kotlin/net/corda/testing/driver/Driver.kt
> +        val inMemoryDB: Boolean = false,
I've tested, and our existing tests pass with this change, with 3 exceptions, which are handled on a case by case basis.

2020-08-27 16:25 UTC, rnicoll commented on testing/node-driver/src/main/kotlin/net/corda/testing/driver/Driver.kt
> +        val inMemoryDB: Boolean = false,
We should make sure this is in the release notes... please raise a PR against https://github.com/corda/corda-docs-develop/blob/release/2020.3/content/en/docs/corda-os/4.6/release-notes.md

2020-08-27 16:27 UTC, rnicoll requested changes
One minor change and release notes needed.

2020-08-27 16:27 UTC, rnicoll commented on testing/node-driver/src/main/kotlin/net/corda/testing/node/MockServices.kt
> +            DatabaseSnapshot.copyDatabaseSnapshot(Paths.get("./build/mocknetworktestdb/${nodeName}"))
Certainly we need this to be Windows compatible, too, so either use something like `Files.createTempDir()` or build the path programmaticly.

2020-08-31 12:29 UTC, benmcmahon100 commented on testing/node-driver/src/main/kotlin/net/corda/testing/node/MockServices.kt
> +            DatabaseSnapshot.copyDatabaseSnapshot(Paths.get("./build/mocknetworktestdb/${nodeName}"))
From a jenkins POV, is the build dir not considered temporary as it is cleaned up after a build?

2020-09-01 15:57 UTC, rnicoll commented on testing/node-driver/src/main/kotlin/net/corda/testing/node/MockServices.kt
> +            DatabaseSnapshot.copyDatabaseSnapshot(Paths.get("./build/mocknetworktestdb/${nodeName}"))
Jonathan has mentioned the use of `Files.createTempDir()` created problems, so I've build the path programmatically instead so we don't presume path separator.

2020-09-01 16:13 UTC, rnicoll approved these changes, later dismissed

2020-09-01 18:42 UTC, rnicoll approved these changes, later dismissed

2020-09-03 08:16 UTC, yift-r3 commented on testing/node-driver/src/main/kotlin/net/corda/testing/node/DatabaseSnapshot.kt
> +        Files.copy(stream, path)
We need to close the input stream.

2020-09-03 08:25 UTC, rnicoll commented on testing/node-driver/src/main/kotlin/net/corda/testing/node/DatabaseSnapshot.kt
> +        Files.copy(stream, path)
Good spot, thanks

2020-09-03 09:26 UTC, rnicoll submitted a review, later dismissed

2020-09-03 09:30 UTC, Schife approved these changes, later dismissed

2020-09-03 11:10 UTC, blsemo reviewed
Looks ok in general, but I have 2 remarks:
- I am not a fan of replacing the timestamp directory name with a UUID, as it makes it harder to find/understand the working directory when trying to figure out a test failure. I would like to see a convincing argument why this is required...
- This seems to have added another case where driver needs to handle restarting a node without further mucking around with the database (I have come across a couple of those with the C4.6 database refactor), maybe we should add a `restartNode` function that just assumes no db modification are required.

2020-09-03 11:10 UTC, blsemo commented on testing/node-driver/src/main/kotlin/net/corda/testing/driver/Driver.kt
> +        val driverDirectory: Path = Paths.get("build") / "node-driver" / getUUIDAsDirectoryName(),
I am not sure I am really happy about this change - it was always *very* handy to be able to tell from the directory name which test was the most recent one...

2020-09-03 11:10 UTC, blsemo commented on testing/node-driver/src/main/kotlin/net/corda/testing/node/internal/CustomCordapp.kt
> +            val timeDirName = getUUIDAsDirectoryName()
`timeDirName` is no longer the correct name...

2020-09-03 11:45 UTC, rnicoll commented on testing/node-driver/src/main/kotlin/net/corda/testing/driver/Driver.kt
> +        val driverDirectory: Path = Paths.get("build") / "node-driver" / getUUIDAsDirectoryName(),
So there was a problem which turned up in this, that we can start multiple nodes within the same ms and they get the same folder name. This showed up because it was then trying to copy the snapshot over a file which already existed.

That's no reason I couldn't put a timestamp plus a say 8 random characters as the path name, though, if that works?

2020-09-03 11:48 UTC, blsemo commented on testing/node-driver/src/main/kotlin/net/corda/testing/driver/Driver.kt
> +        val driverDirectory: Path = Paths.get("build") / "node-driver" / getUUIDAsDirectoryName(),
Yes, that would work - I just found the timestamp to be extremely useful when working out why driver tests fail.

2020-09-03 13:07 UTC, rnicoll approved these changes

2020-09-03 13:08 UTC, rnicoll commented
run tests: slow

2020-09-03 13:12 UTC, rnicoll commented
Run tests: slow

2020-09-03 13:15 UTC, rick-r3 commented
This is okay with me.  It will be obvious how to fix any customer issues that arise via release notes, but most likely only us doing tricksy stuff across node restarts etc that cares.

2020-09-03 13:25 UTC, blsemo reviewed
Sorry, more questions...

2020-09-03 13:25 UTC, blsemo commented on testing/node-driver/src/main/kotlin/net/corda/testing/node/MockServices.kt
> +            val dbDir = Paths.get("","build", "mocknetworktestdb", nodeName)
More questions come to mind:
- How an when does this get cleaned up?
- If it doesn't get cleaned up immediately, is there a way to find the db directory for a given test from the logs/test output?

2020-09-03 13:28 UTC, rnicoll commented on testing/node-driver/src/main/kotlin/net/corda/testing/node/MockServices.kt
> +            val dbDir = Paths.get("","build", "mocknetworktestdb", nodeName)
@yift-r3 Do you happen to know the answer?

2020-09-03 13:37 UTC, blsemo approved these changes
Looks good to me if discoverability of test data bases will be given.

2020-09-03 13:41 UTC, rnicoll commented on testing/node-driver/src/main/kotlin/net/corda/testing/node/MockServices.kt
> +            val dbDir = Paths.get("","build", "mocknetworktestdb", nodeName)
Answered it myself; it's under the `build` folder so removed when the Kubernetes Pod stops.

2020-09-03 13:42 UTC, rnicoll commented
Raised docs PR https://github.com/corda/corda-docs-develop/pull/477

2020-09-03 13:43 UTC, rnicoll commented
Created JIRA for logging the DB path: https://r3-cev.atlassian.net/browse/INFRA-664

2020-09-03 13:43 UTC, merged