ENT-5666 Extract shutdown events when retrying a flow
corda/corda pull request #6684
Opened 2020-09-01 16:14 UTC by lankydan

When a flow is retrying, only a select set of events are transferred
over to the new fiber. Shutdown events were not included in this set.

This meant that if a flow retries when an `Event.SoftShutdown` is in its
queue, it will never process it. This causes the node to hang, as the
node awaits `liveFibers`, which never reaches 0 because the shutdown
event is never processed.

To resolve this, `Event.SoftShutdown` is added to the set of events to
extract and reschedule.

2020-09-02 09:09 UTC, lankydan commented
This fixes the failing test `FlowReloadAfterCheckpointTest.flow continues reloading from checkpoints after node restart when reloadCheckpointAfterSuspend is true` on ENT. This is the jenkins build for the ENT version of this PR that I have tested this against https://ci02.dev.r3.com/job/Corda-Enterprise/job/Corda%20Private%20Pull%20Requests/job/enterprise/job/PR-3759/ (red builds are before I added the fix).

2020-09-03 14:50 UTC, rnicoll approved these changes
I think makes sense but you probably want sign off from Rick before merging.

2020-09-03 16:22 UTC, rick-r3 requested changes
Technically SoftShutdown & Pause _are_ GeneratedByExternalEvent, so perhaps look to re-inherit those event types.  That would be more consistent, provided it doesn't throw up any other horrors.

2020-09-04 14:41 UTC, rick-r3 approved these changes
As discussed, alternative opened the can-of-worms I feared it might.

2020-09-04 14:44 UTC, merged