CORDA-3823-ported-hash-agility-with-cmd-line-option
corda/corda pull request #6687
Opened 2020-09-03 19:57 UTC by eierina

Ported hash agility to 4.7 and added command line option to enable support for alternate transaction hashing algorithms.

2020-09-04 10:32 UTC, mnesbit commented
Looks really good. Think it would be good to ask QA if they could run CRAFT on this to catch any compatibility/upgrade issues

2020-09-04 10:45 UTC, rekalov commented on node/src/main/resources/migration/node-core.changelog-master.xml
> +
Patch name will clash with ENT. Should it be v20?

2020-09-04 10:46 UTC, rekalov commented on node/src/main/resources/migration/node-notary.changelog-master.xml
> +    <include file="migration/node-notary.changelog-v100.xml"/>
Why v100?

2020-09-06 21:58 UTC, chrisr3 requested changes
It looks like you've ported my POC branch, but my POC branch was _never_ intended to be merged "as is" because it requires more extensive test coverage. For example, this changes how transaction IDs are both persisted and read back from the Vault, but there is no test coverage for this feature here, nor that "Cash Selection" still works. There need to be dedicated integration tests for this, with transactions built using a hash algorithm other than SHA-256.

I also picked the value of "80" for the `TXID` schema change out of my donkey, so we'd need to agree on a new value for a _proper_ reason based on which algorithms we intend to allow people to use in future. E.g. 80 still wouldn't be enough for anything like SHA3-384

2020-09-06 21:58 UTC, chrisr3 commented on core/src/main/kotlin/net/corda/core/schemas/PersistentTypes.kt
> +        @Column(name = "transaction_id", length = 80, nullable = false)
What a coincidence, you have also chosen to increase transaction ID from 64 to 80 characters! For my POC branch, I chose a value of 80 because the well-know hash algorithm "`bongohash`" has 9 letters. +1 for the `:` separator, and then rounded up to the nearest power of 2, i.e. 16, so 64 + 16 = 80.

What was your reason?

2020-09-06 21:58 UTC, chrisr3 commented on node/src/main/resources/migration/node-notary.changelog-master.xml
> +    <include file="migration/node-notary.changelog-v100.xml"/>
For my POC, I chose "v100" because I wanted a large gap between my change and any new ones being added to Corda, to reduce the chance of a merge conflict. This reason would obviously not apply here.

2020-09-15 11:55 UTC, mnesbit commented on core/src/main/kotlin/net/corda/core/schemas/PersistentTypes.kt
> +        @Column(name = "transaction_id", length = 80, nullable = false)
Agree that we should identify and enforce limits on the hash name size. I am actually fine with limiting to 256 bit hashes for now as there is little appetite for bigger hashes, more that we want drop in alternate hash algorithms.

2020-09-15 12:00 UTC, mnesbit commented
@eierina we need to change branch name to feature/CORDA-3823-hash-agility to trigger proper feature branch integration.

@chrisr3 totally agree that we need more tests and more integration testing. Can you list what you felt was missing from your original POC? Trying to help you out here, by getting Edoardo to take this on to production quality as you are busy elsewhere. We also need to find a solution that Matthijs van den Bos can integrate with.

2020-10-22 08:44 UTC, mnesbit commented
@eierina We need to chivvy this along. Window for Corda 4.7 is closing/closed

2020-10-30 10:13 UTC, eierina commented
Replaced by https://github.com/corda/corda/pull/6758

2020-10-30 10:13 UTC, closed without merging