NOTICK - Eliminate unneeded code
corda/corda pull request #6694
Opened 2020-09-08 13:22 UTC by kyriathar

Eliminate: 

1. unused code
2. unneeded warning message, since the race condition in `DBTransactionStorage.trackTransaction` did not occur due to database transaction isolation level, but because of late registering to transaction's updates `Observable`.

2020-09-08 13:26 UTC, lankydan commented
If we are just removing code, doesn't that mean the race condition is still there? Is there a way to fix it?

2020-09-08 13:27 UTC, kyriathar commented
The race condition is resolved by registering to `DBTransactionStorage.updates` prior to `getTransaction` in `DBTransactionStorage.trackTransaction`.

2020-09-08 14:29 UTC, blsemo commented
Not sure I quite follow your comment - is the change to remove the race condition also in this PR?

2020-09-08 14:33 UTC, kyriathar commented
This was done by @josephzunigadaly when implementing https://r3-cev.atlassian.net/browse/ENT-4857. I left that bit of code untouched yes.

2020-09-08 15:16 UTC, rick-r3 requested changes

2020-09-08 15:16 UTC, rick-r3 commented on node/src/main/kotlin/net/corda/node/services/persistence/DBTransactionStorage.kt
> -                    updates.filter { it.id == id }.toFuture()
I think this line of the PR is valid (I went back to look at @josephzunigadaly original and this accidentally got left in the OS port).

However, I don't think we can do the rest of it.  The `trackTransaction` is public API which can be called by CorDapp developers inside a database transaction (which triggers the race condition, and hence the warning).

2020-09-08 15:20 UTC, rick-r3 commented
Actually I saw your slack comment about it not being public API.  Maybe that is true....

2020-09-08 15:21 UTC, lankydan commented on node/src/main/kotlin/net/corda/node/services/persistence/DBTransactionStorage.kt
> -                    updates.filter { it.id == id }.toFuture()
`trackTransaction` is public, the with warning is not.

2020-09-08 15:23 UTC, rick-r3 commented
... ah I was blind `val validatedTransactions: TransactionStorage` on `ServiceHub`.  It is public API.

2020-09-08 15:26 UTC, lankydan commented
> ... ah I was blind `val validatedTransactions: TransactionStorage` on `ServiceHub`. It is public API.

Yes, but only an internal function was removed (since it was on `WritableTransactionStorage`, not `TransactionStorage`).

2020-09-08 16:47 UTC, rick-r3 commented
No my argument was more about the fact we can't remove the warning because you can trigger via public API.  Now, technically I think we can (and I hadn't realised) because we think we're moving the default isolation level to READ_COMMITTED which supposedly stops the race, but I think it is actually possible to still set a different isolation level via the Hikari data source properties.  So 🤷‍♂️

2020-09-09 08:29 UTC, josephzunigadaly commented
I think we should undo the changes that remove the warning and keep the removal of `updates.filter { it.id == id }.toFuture()`.

2020-09-09 13:29 UTC, kyriathar commented
Reverted -removing the warning- change, however would it make it better if we also check if the existing transaction when calling `trackTransaction` is `REPEATABLE_READ`? I think that's the only case we can potentially get a race due to transaction isolation level if they executed a `SELECT` before.

2020-09-09 13:37 UTC, josephzunigadaly submitted a review, later dismissed

2020-09-15 10:01 UTC, josephzunigadaly approved these changes

2020-09-15 12:53 UTC, merged