CORDA-3974: NetworkMapCache should link entries with different public keys by X.500 name
corda/corda pull request #6711
Opened 2020-09-15 12:42 UTC by rekalov

Replace NodeInfo in NetworkMapCache by X.500 name.
Also, improve logging, including printout of the key hash.

2020-09-16 09:48 UTC, mnesbit commented on node/src/main/kotlin/net/corda/node/services/messaging/P2PMessagingClient.kt
> +        log.info("Updating bridges on network map change: ${change::class.simpleName} ${change.node}")
Any side effects of updates due to key rotation on bridge logic? Would expect we have to tear down and completely recreate bridge on that? Do we need a new update type for this form of change?

2020-09-16 10:13 UTC, rekalov commented on node/src/main/kotlin/net/corda/node/services/messaging/P2PMessagingClient.kt
> +        log.info("Updating bridges on network map change: ${change::class.simpleName} ${change.node}")
No, we just generate `MapChange.Modified` on key rotation, so the existing logic works perfectly well:
```
            is NetworkMapCache.MapChange.Modified -> {
                destroyBridges(change.previousNode)
                deployBridges(change.node)
            }
```

We assume that other peers don't start flows against rotating node, so we don't care much about race conditions etc.

2020-09-16 10:15 UTC, mnesbit submitted a review, later dismissed
OK

2020-09-16 14:27 UTC, dimosr requested changes
LGTM code-wise, just a few minor comments

2020-09-16 14:27 UTC, dimosr commented on node/src/main/kotlin/net/corda/node/services/network/PersistentNetworkMapCache.kt
>          // TODO For now the main legal identity is left in NodeInfo, this should be set comparision/come up with index for NodeInfo?
Is this still valid (doesn't make a lot of sense to me)? If not, a good opportunity to remove it now.

2020-09-16 14:27 UTC, dimosr commented on node/src/main/kotlin/net/corda/node/services/network/PersistentNetworkMapCache.kt
> +    private fun getPreviousNodeInfo(session: Session, party: Party): NodeInfoSchemaV1.PersistentNodeInfo? {
got a bit confused by this method's name. Is it always returning the previous node info? Looking at how it's used in `updateInfoDB`, it makes me think it's returning the latest node info that's then updated in the DB.

2020-09-16 14:27 UTC, dimosr commented on node/src/test/kotlin/net/corda/node/services/network/NetworkMapCacheTest.kt
> +        // Check that keys and certificates are different
Shouldn't that be `keys are the same, but certificates are different` instead?

2020-09-16 16:13 UTC, rekalov commented on node/src/main/kotlin/net/corda/node/services/network/PersistentNetworkMapCache.kt
>          // TODO For now the main legal identity is left in NodeInfo, this should be set comparision/come up with index for NodeInfo?
Do you mean the comment?
Doesn't make sense, happy to remove.

2020-09-16 16:14 UTC, rekalov commented on node/src/main/kotlin/net/corda/node/services/network/PersistentNetworkMapCache.kt
> +    private fun getPreviousNodeInfo(session: Session, party: Party): NodeInfoSchemaV1.PersistentNodeInfo? {
Yes, it means currently stored. I will change to `getNodeInfo`

2020-09-16 16:56 UTC, rekalov commented on node/src/test/kotlin/net/corda/node/services/network/NetworkMapCacheTest.kt
> +        // Check that keys and certificates are different
Addressed, please review.

2020-09-17 07:22 UTC, dimosr approved these changes
LGTM

2020-09-17 08:25 UTC, merged