DRAFT-NOTICK - Convert WaitForLedgerCommit to a FlowAsyncOperation
corda/corda pull request #6736
Opened 2020-09-21 08:00 UTC by kyriathar

2020-09-21 08:10 UTC, lankydan reviewed
Looks fine to me.

@blsemo what is your opinion on this? `FlowAsyncOperation` is internal, so adding things to it should be fine. But, developers can still implement this interface themselves and therefore create behaviour that we don't really intend them to have control over. We can do it in a purely internal way, but the code done this way is simpler and easy to reason about.

`FlowExternalOperation` and `FlowExternalAsyncOperation` are the public versions of `FlowAsyncOperation`.

2020-09-21 11:15 UTC, lankydan commented
Remember to remove `Event.TransactionCommitted`

2020-09-24 08:14 UTC, chrisr3 requested changes
I see no reason for wanting to change the ProGuard settings.

2020-09-24 08:14 UTC, chrisr3 commented on core-deterministic/build.gradle
> +    dontwarn
Why is this here? We _like_ warnings about Bad Things. What are you trying to ignore?

2020-09-24 08:25 UTC, kyriathar commented on core-deterministic/build.gradle
> +    dontwarn
Hello Chris, like i mention on commit message "_To be reverted..._". I will be putting it back, i just kept getting a warning about a class (`net.corda.core.internal.WaitForLedgerCommit`) which cannot reference `ServiceHub` which did not make any sense. That got fixed locally after 1. a merge 2. adding the 'dontwarn' 3. removing it. Not sure what fixed it after all, but thought i could try the same on remote machine.

2020-09-24 08:33 UTC, chrisr3 commented on core-deterministic/build.gradle
> +    dontwarn
ProGuard's warning may have seemed bizarre, but it must have been highlighting a _real_ issue. ProGuard analyses the byte-code in the `.class` files and so also examines synthetic functions which are generated by the compiler and so do not exist in the source code (e.g. `access` functions and lambdas).

Try decompiling the `.class` file using `javap` to discover them.

2020-09-24 08:37 UTC, lankydan commented on core/src/main/kotlin/net/corda/core/internal/WaitForLedgerCommit.kt
> +class WaitForLedgerCommit(val hash: SecureHash, val services: ServiceHub): FlowAsyncOperation<SignedTransaction> {
private val

2020-09-24 08:39 UTC, lankydan commented on node/src/main/kotlin/net/corda/node/services/statemachine/ActionExecutorImpl.kt
> +            is Action.TrackTransaction -> {}
Assume you'll remove this.

2020-09-24 08:40 UTC, kyriathar commented on node/src/main/kotlin/net/corda/node/services/statemachine/ActionExecutorImpl.kt
> +            is Action.TrackTransaction -> {}
Yes : ] is next step.

2020-09-28 07:47 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/internal/WaitForLedgerCommit.kt
> +    override val collectErrorsFromSessions: Boolean
We have an option to change some things, so why don't we simplify things and either collect errors from sessions always or never for the async operations?  I noticed we had this special case for one or more of the non-messaging FlowIORequests but I'm not sure we did it particularly strategically.  WDYT @lankydan ?

2020-09-28 07:47 UTC, rick-r3 commented on node/src/main/kotlin/net/corda/node/services/statemachine/transitions/StartedFlowTransition.kt
> +            is FlowIORequest.WaitForLedgerCommit -> { TransitionResult(startingState) }
I'm assuming you're still working on removing this ?

2020-09-28 07:56 UTC, kyriathar commented on node/src/main/kotlin/net/corda/node/services/statemachine/transitions/StartedFlowTransition.kt
> +            is FlowIORequest.WaitForLedgerCommit -> { TransitionResult(startingState) }
Yes, i am replacing uses of  `FlowIORequest.WaitForLedgerCommit` one by one, and once done this line will be deleted.

2020-09-28 08:00 UTC, lankydan commented on core/src/main/kotlin/net/corda/core/internal/WaitForLedgerCommit.kt
> +    override val collectErrorsFromSessions: Boolean
We made the decision to keep it working as it is. Where you only collect errors if you interact with a session again. I think if we change this behaviour, we would need to change it for all suspending operations as its no longer obvious what happens in each scenario.

2020-09-30 12:57 UTC, lankydan commented on node/src/main/kotlin/net/corda/node/services/statemachine/FlowMonitor.kt
> +                is FlowIORequest.ExecuteAsyncOperation -> "for asynchronous operation of type ${request.operation::class.java} (${request.operation}) to complete"
Are you going to make this work differently for operations defined by users? As this won't look good at the moment.

2020-09-30 13:03 UTC, kyriathar commented on node/src/main/kotlin/net/corda/node/services/statemachine/FlowMonitor.kt
> +                is FlowIORequest.ExecuteAsyncOperation -> "for asynchronous operation of type ${request.operation::class.java} (${request.operation}) to complete"
Yes indeed, now that **i think** i have a way to test logs i will make that a different case.

2020-10-01 08:07 UTC, mnesbit commented on core/src/main/kotlin/net/corda/core/internal/WaitForLedgerCommit.kt
> +        return services.validatedTransactions.trackTransaction(hash).toCompletableFuture().asCordaFuture()
I am a little nervous about the reliability of this. Are we sure behaviour is correct when:
1. Flow is one producing/soft locking the transaction
2. Transaction is already in vault before subscribe
3. At state machine start up are there any race conditions
4. You aren't a participant?

2020-10-01 08:18 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/internal/WaitForLedgerCommit.kt
> +        return services.validatedTransactions.trackTransaction(hash).toCompletableFuture().asCordaFuture()
I think this is using the same Observable as the current implementation.  All valid questions, but perhaps outside scope here.

2020-10-01 08:39 UTC, kyriathar commented on core/src/main/kotlin/net/corda/core/internal/WaitForLedgerCommit.kt
> +        return services.validatedTransactions.trackTransaction(hash).toCompletableFuture().asCordaFuture()
I don't think we changed the behavior with this PR at all. It was more of by making a wait for ledger commit a `FlowAsyncOperation` to get rid of duplicate code.

2020-10-01 10:12 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/internal/WaitForLedgerCommit.kt
> +    override val collectErrorsFromSessions: Boolean
But it is currently inconsistent.  i.e. we have a tiny number of non-messaging scenarios where we do session processing, and this is one of them, and the majority we don't.  I'd rather we stopped doing it for this.

2020-10-01 10:18 UTC, lankydan commented on core/src/main/kotlin/net/corda/core/internal/WaitForLedgerCommit.kt
> +    override val collectErrorsFromSessions: Boolean
I think we need this collection though. If a flow is waiting for a tx to be committed (assuming that the counterparty flow is the one going to be initiating the committing of the tx), then the only way for it to resume is for the tx to be committed. If the counterparty flow fails and therefore can't initiate the committing of the tx, then the flow waiting for that tx will be forever waiting.

If we collect the session errors, then this flow can end without the tx being committed. This seems like the right behaviour to me.

But, I am not sure that this is the right behaviour for all usages for async operations.

Is this a wider discussion that we need to have about what to do with session errors on different flow io requests?

2020-10-01 11:12 UTC, kyriathar commented on core/src/main/kotlin/net/corda/core/internal/WaitForLedgerCommit.kt
> +    override val collectErrorsFromSessions: Boolean
I think, wait for ledger commit as it currently is, can be used in two ways:
a) part of a set of things including a tx initialization and then wait for tx commit.
b) in a separate flow that just awaits for that tx to be commited.

So if used in a) then yes we need to collect errors, but in b) no we don't because the flow called it will not receive any message as it could not have initialized a session with the throwing counter party.

2020-10-01 11:18 UTC, kyriathar commented on core/src/main/kotlin/net/corda/core/internal/WaitForLedgerCommit.kt
> +    override val collectErrorsFromSessions: Boolean
If we say `collectErrorsFromSessions` is unlikely to be used again other than wait for ledger commit (i.e. it is unlikely that there are going to be other async operations that need to collect errors from sessions), then we could remove it, for simplicity, and at `StartedFlowTransition.collectRelevantErrorsToThrow` go with `is WaitForLedgerCommit -> {...}`.

2020-10-02 08:34 UTC, lankydan commented on node/src/main/kotlin/net/corda/node/services/statemachine/FlowMonitor.kt
> +                        else -> request.operation
You could make this an extension function to `FlowAsyncOperation` and put it in `FlowAsyncOperation`'s file. Then you can keep the wrapped versions as internal. Plus it removed duplication.

2020-10-02 08:37 UTC, lankydan commented on node/src/main/kotlin/net/corda/node/services/rpc/CheckpointDumperImpl.kt
> +                    is WaitForLedgerCommit -> SuspendedOn(waitForLedgerCommit = (operation as WaitForLedgerCommit).hash)
This is fine for now, but we'll probably need to change this once the layering is sorted.

2020-10-02 11:55 UTC, kyriathar commented on node/src/main/kotlin/net/corda/node/services/statemachine/FlowMonitor.kt
> +                        else -> request.operation
Done -consolidated with pre existing `FlowAsyncOperation<*>.externalOperationImplName`-.

2020-10-02 12:52 UTC, lankydan commented on core/src/main/kotlin/net/corda/core/internal/FlowAsyncOperation.kt
> +fun FlowAsyncOperation<*>.unwrap(): Any =
Would rather just have the `unwrap` method and call `javaClass.canonicalName` where needed.

2020-10-02 13:06 UTC, kyriathar commented on core/src/main/kotlin/net/corda/core/internal/FlowAsyncOperation.kt
> +fun FlowAsyncOperation<*>.unwrap(): Any =
Done.

2020-10-05 10:35 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/internal/WaitForLedgerCommit.kt
> +    override val collectErrorsFromSessions: Boolean
@lankydan Hmmm.... Still considering this checking for session errors idea.  That is a valid scenario I guess.  i.e. wait for ledger commit but got a session with the flow that should be making the commit, but it errors instead.  Should we respond to the session error or not?  Perhaps desirable.  And thus could be desirable for any flow waiting on any future (i.e. apply to all async).  However, before we think about changes, if an error is received on a session whilst the flow is already waiting for the `Future`, do we interrupt the flow as things stand, or do we only check the errors on sessions as we _begin_ waiting ?

2020-10-05 10:48 UTC, lankydan commented on core/src/main/kotlin/net/corda/core/internal/WaitForLedgerCommit.kt
> +    override val collectErrorsFromSessions: Boolean
Mmmmm, I don't think we do cancel the futures in this scenario. Since it wasn't something that was possible. I guess this would be confirmed by a test. To me, this suggests that `WaitForLedgerCommit` didn't really work before since the future would continue running (I don't see anything suggesting otherwise).

So yes, we would need to make sure we cancel the future. 

One thing that me and kyriakos we discussing is that we don't need to collect session errors for `WaitForLedgerCommit` calls. It was used in v3 because of how `FinalityFlow` was used. In v4, you are meant to use `ReceiveFinalityFlow` instead. Therefore the only scenario you would use `WaitForLedgerCommit` is for a flow that is not actually involved in the creation of a transaction. In which case, you cannot receive the error from the flow creating the transaction in the first place.

My opinion on the wider collection of errors for async operations remains the same, that I am not sure if we need it. On the other hand, I don't really hold this position particularly strongly. The only reasons I see needing to collect session errors is if the future is waiting for something done by the initiated/counterparty flow.

2020-10-05 11:04 UTC, kyriathar commented on core/src/main/kotlin/net/corda/core/internal/WaitForLedgerCommit.kt
> +    override val collectErrorsFromSessions: Boolean
```
However, before we think about changes, if an error is received on a session whilst the flow is already waiting for the Future, do we interrupt the flow as things stand, or do we only check the errors on sessions as we begin waiting ?
```

I think, upon receiving the error message, it will then schedule a `Event.DoRemainingWork`, collect the error and throw it, meaning it will "interrupt" the async  operation and cancel the future on flow removal.

2020-10-05 14:08 UTC, lankydan commented on core/src/main/kotlin/net/corda/core/internal/WaitForLedgerCommit.kt
> +    override val collectErrorsFromSessions: Boolean
Yes, it only cancels it on flow removal but not when receiving the error. So the flow could catch the error and the future would continue.

2020-10-05 14:31 UTC, kyriathar commented on core/src/main/kotlin/net/corda/core/internal/WaitForLedgerCommit.kt
> +    override val collectErrorsFromSessions: Boolean
I guess the issue here is, the flow could start error transition so we have an `Event.Error` and then, before we are done with determining what to do with the flow, at some point in there the async operation finishes and the other thread schedules an `Event.AsyncOperationCompletion` which does not currently take into consideration if state is errored, which would led into the flow continuing while it shouldn't. I guess that can be issued by checking the state in `asyncOperationCompletionTransition` and if errored make it `ProcessEvents`.

2020-10-08 15:26 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/internal/WaitForStateConsumption.kt
> +@DeleteForDJVM
?

2020-10-08 15:26 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/internal/WaitForLedgerCommit.kt
> +class WaitForLedgerCommit(val hash: SecureHash, private val services: ServiceHub): FlowAsyncOperation<SignedTransaction> {
I think we shouldn't capture the `ServiceHub` here as it will end up in a checkpoint.  In theory that should be okay, but I'd rather avoid it.  It might be better if we actually changed the signature of `execute` on `FlowAsyncOperation` to take it as a param.  Leave the public "external operation" stuff alone / without.

2020-10-08 15:26 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/internal/WaitForLedgerCommit.kt
> +class WaitForLedgerCommit(val hash: SecureHash, private val services: ServiceHub): FlowAsyncOperation<SignedTransaction> {
Actually it should probably have full access to the same thing as `ActionExecutorImpl`, so `ServiceHubInternal`

2020-10-08 15:29 UTC, lankydan commented on core/src/main/kotlin/net/corda/core/internal/WaitForLedgerCommit.kt
> +class WaitForLedgerCommit(val hash: SecureHash, private val services: ServiceHub): FlowAsyncOperation<SignedTransaction> {
Its ok for it to use the `ServiceHub` as we already do the same for `WrappedFlowExternalOperation` anyway.

The better option is to change it to the transaction service thing instead, ready for when we bin `ServiceHub`.

2020-10-08 15:33 UTC, lankydan commented on core/src/main/kotlin/net/corda/core/internal/WaitForStateConsumption.kt
> +@DeleteForDJVM
We needed to add it to `WaitForLedgerCommit`. Chris suggested adding it here as well as we couldn't figure out why `WaitForStateConsumption` worked when the other didn't.

2020-10-09 08:00 UTC, lankydan commented on node/src/main/kotlin/net/corda/node/services/statemachine/FlowMonitor.kt
> +                    "for asynchronous operation of type ($operation) to complete"
we could put this back into a single line now that you extracted code into the `unwrap` function

2020-10-12 13:06 UTC, kyriathar commented on node/src/main/kotlin/net/corda/node/services/statemachine/FlowMonitor.kt
> +                    "for asynchronous operation of type ($operation) to complete"
Done.

2020-10-13 10:12 UTC, lankydan commented on core/src/main/kotlin/net/corda/core/internal/FlowAsyncOperation.kt
> +class WrappedFlowExternalOperation<R : Any>(
Are you able to make these `internal`?

2020-10-13 10:39 UTC, kyriathar commented on core/src/main/kotlin/net/corda/core/internal/FlowAsyncOperation.kt
> +class WrappedFlowExternalOperation<R : Any>(
Done.

2020-10-13 14:05 UTC, lankydan approved these changes

2020-10-13 15:25 UTC, rick-r3 approved these changes

2022-01-06 14:19 UTC, vkolomeyko commented
@kyriathar - do we still need this PR?

2022-01-07 09:00 UTC, lankydan commented
Nope, we merged it into C5, this was probably before we had the C5 branch. Closing.

2022-01-07 09:00 UTC, closed without merging