AG-323 Better notary metrics
corda/corda pull request #6811
Opened 2020-11-17 20:15 UTC by StefanIliev545

Core for https://github.com/corda/enterprise/pull/4110
Included in PR: time stamping logic that provides information about the duration of the flow until sending the final response.
Dropped:
Tracking messages - session ID albeit supposed to be symmetric seems to be different when calling otherSide.send and processing messages in FlowMessaging, thus making the message hard to relate unless changes are made to the state machine to expose its internal sessionId to Flow map, which is overkill for the scope of this ticket.
Timestamp taken post serialisation in the FlowStateMachine.suspend call - This one requires to modify public API and create a non transient value in the flow state machine. As the FSM lacks such values and the API is generally unrelated, taking the timestamp there was omitted and instead is done before the send call. This presents no issue for the notary, as the kryo serialisation calls are quick, because the call stack size is constant (for the notary) and serialisation latency in my tests on the notary dev deployment for cn-notary seem to be well under 5ms. The quick serialisation is because on checkpoints we do serialize(this), where this is the current class, overwritten by quasar. Quasar basically keeps a call stack on each @Suspendable call, so serialisation boils down to writing an array.

2020-11-18 16:45 UTC, relyafi requested changes
#### PR Description

I think this needs re-working to be clearer, specifically:

- The included section only mentions the duration of the flow, which is technically inaccurate in the context of this PR; we are delivering a new metric that captures the flow queue duration, regardless of the specific flow, as well as providing a framework for a notary implementation to provide an overall notarisation duration metric.
- I'd suggest the dropped section unnecessary to someone reading the PR (who is probably focused on what we did), although this may be useful information in the context of the design document (if someone wants to go back and understand the background and rationale for the implementation). There does however appear to be a brief reference to testing in this section, which is useful and I'd like to see expanded on (even if this is just referencing the ENT PR).

Also as a general comment - when writing blocks of text like this, I find use of whitespace, bullets etc. make things easier to understand. I had to read over this several times to understand exactly what was being communicated.

2020-11-18 16:45 UTC, relyafi commented on node/src/main/kotlin/net/corda/node/services/statemachine/FlowStateMachineImpl.kt
> +                              override val creationTime: Long = System.nanoTime()
This seems dangerous to me; this lives on the public interface of FlowStateMachine, which is part of core, so literally anyone could be using this value (although it doesn't look like it's being used within the Corda repo?).

Given it is just a Long, people will have to interpret the value as being in milliseconds, which means this could be a functional breaking change.

Given that expected value of the metric we are generating is of the order of milliseconds anyway, I'd suggest just capturing to millisecond accuracy.

As an aside, it strikes me that rather than use this, we could move the creationTime that is defined within NotaryServiceFlow up to FlowLogic, and then use that value later on at line 338? That would have the advantage of letting us retain nanosecond precision (since it's a new value), as well as letting other flows use that value as they see fit (although we'd probably need a comment on use to explain why we haven't used the existing creationTime with millisecond precision).

2020-11-18 16:45 UTC, relyafi commented on core/src/main/kotlin/net/corda/core/internal/notary/NotaryServiceFlow.kt
>          logger.info("Transaction [$txId] successfully notarised, sending signature back to [${otherSideSession.counterparty.name}]")
Something that occurs to me - it looks like it would  be trivial to update this logging to include the notarisation duration. For our managed services notaries, this potentially gives us a very rough and ready audit trail of the time it took individual transactions to notarise.

This does come at the risk of potentially breaking any existing loggers that pattern match on this message (although this seems unlikely). @ifrankrui / @fredflev do you have any thoughts on this?

2020-11-18 16:45 UTC, relyafi commented on core/src/main/kotlin/net/corda/core/internal/notary/NotaryServiceFlow.kt
> +        private val creationTime : Long = System.nanoTime()
(Style) Remove space before the colon

2020-11-18 16:45 UTC, relyafi commented on core/src/main/kotlin/net/corda/core/internal/notary/SinglePartyNotaryService.kt
> +    open fun recordNotarisationDuration(elapsedTime: Duration) {}
This needs a kdoc comment to provide an overview, and especially when it will be invoked (since we don't want people only interested in the notary API having to trawl through state machine code to find out).

2020-11-18 16:46 UTC, relyafi commented
Added @lankydan in case he has any comments on the state machine side of things

2020-11-24 10:26 UTC, relyafi reviewed
Title should be made more specific to reflect reduced scope of the change, e.g. "Flow startup queue time metric"

Otherwise, ready to approve once minor comment addressed and PR gates pass.

2020-11-24 10:26 UTC, relyafi commented on core/src/main/kotlin/net/corda/core/flows/FlowLogic.kt
> +     * and the creation times are different.
_This happens before the stateMachine and the creation times are different._

This sentence doesn't make sense to me - I'm assuming we're trying to say this happens before the state machine is instantiated and it has a different creation time?

If that's the case, I'd argue this is an unnecessary detail, and I'd just remove it.

2020-11-30 14:12 UTC, relyafi approved these changes
LGTM

2020-11-30 15:48 UTC, thschroeter approved these changes
LGTM

2020-11-30 16:48 UTC, lankydan approved these changes

2020-11-30 16:49 UTC, merged