CORDA-4105 Add public API to allow custom serialization schemes
corda/corda pull request #6848
Opened 2021-01-21 17:44 UTC by williamvigorr3

Added public interface CustomSerializationScheme so custom serialization schemes can be implemented. Added adapter code which takes an implementation of this interface and creates an implementation of SerializationScheme (this is the internal equivalent which existed before this PR). Currently this adapter is only used by tests, the idea is to eventually use this in the node after discovering implementations of CustomSerializationScheme.

2021-01-22 09:32 UTC, JamesHR3 requested changes

2021-01-22 09:32 UTC, JamesHR3 commented on core/src/main/kotlin/net/corda/core/serialization/CustomSerializationScheme.kt
> +     * This method must deserialize (any) object from SerializedBytes.
Worth saying what the input parameters are and what the output is (for this and all other public methods).

2021-01-22 09:32 UTC, JamesHR3 commented on core/src/main/kotlin/net/corda/core/serialization/CustomSerializationScheme.kt
> +class CustomSerializationMagic(val magicNumber: Int)
Needs a kdoc to describe what this is.

2021-01-22 09:32 UTC, JamesHR3 commented on core/src/main/kotlin/net/corda/core/serialization/CustomSerializationScheme.kt
> +interface CustomSerializationContext {
This too.

2021-01-22 09:32 UTC, JamesHR3 commented on node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/CustomSerializationSchemeAdapter.kt
> +        const val SIZE_OF_INT = 4
I think we should call this something like `SERIALIZATION_MAGIC_BUFFER_SIZE` - something that describes what it is used for.

2021-01-22 09:32 UTC, JamesHR3 commented on node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/CustomSerializationSchemeAdapter.kt
> +      @Suppress("UNCHECKED_CAST")
This cast is technically unsafe right? Should we verify that we get a `clazz` instance back from the custom serializer and throw if we don't?

2021-01-22 10:01 UTC, rick-r3 reviewed
Simplification and naming suggestion.

2021-01-22 10:01 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/serialization/CustomSerializationScheme.kt
> +    fun getSerializationMagic(): CustomSerializationMagic
Shall we perhaps just make this `SchemeId` and make it an `Int`, and avoid use of "magic" in the customer facing API ?

i.e. `fun getSchemeId(): Int`

2021-01-22 10:02 UTC, mnesbit commented on core/src/main/kotlin/net/corda/core/serialization/CustomSerializationScheme.kt
> +    fun getSerializationMagic(): CustomSerializationMagic
I presume whatever they pick won't clash with any existing magic bytes?

2021-01-22 10:03 UTC, mnesbit commented on core/src/main/kotlin/net/corda/core/serialization/CustomSerializationScheme.kt
> +class CustomSerializationMagic(val magicNumber: Int)
Probably also have to be clear on threading requirement

2021-01-25 09:29 UTC, williamvigorr3 commented on core/src/main/kotlin/net/corda/core/serialization/CustomSerializationScheme.kt
> +class CustomSerializationMagic(val magicNumber: Int)
I have added detailed Kdoc including threading requirements (which is something that would be very easy to get wrong).

2021-01-25 09:33 UTC, williamvigorr3 commented on node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/CustomSerializationSchemeAdapter.kt
> +        const val SIZE_OF_INT = 4
Changed it to `SERIALIZATION_SCHEME_ID_SIZE`

2021-01-25 09:34 UTC, williamvigorr3 commented on node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/CustomSerializationSchemeAdapter.kt
> +      @Suppress("UNCHECKED_CAST")
This is no longer needed. After properly templating the API.

2021-01-25 09:34 UTC, williamvigorr3 commented on core/src/main/kotlin/net/corda/core/serialization/CustomSerializationScheme.kt
> +    fun getSerializationMagic(): CustomSerializationMagic
I have changed it to an int. It can't clash as the adapter class encodes "CUS" and then the `SchemeId` as a 4 byte int. For AMQP we encode  "CORDA" and then 0 (as a byte) and then 1 (as a byte).

2021-01-25 10:05 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/serialization/CustomSerializationScheme.kt
> +    fun <T : Any> deserialize(bytes: SerializedBytes<T>, clazz: Class<T>, context: CustomSerializationContext): T
I'm having second thoughts about these signatures.  I think we shouldn't use `SerializedBytes` here or in `serialize` because by definition these are missing the magic bytes header that all `SerializedBytes` have.  Can we switch these to `ByteSequence` ?  I know that wipes off T, but I think it is worth it.

Otherwise things might well get confusing.

2021-01-25 10:05 UTC, rick-r3 commented on node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/CustomSerializationSchemeAdapter.kt
> +        val withOutMagic = byteSequence.bytes.slice(serializationSchemeMagic.size until byteSequence.size).toByteArray()
See my other comment about not using `SerializedBytes` on the new API.  Note: `ByteSequence.subSequence()` will help here once not using `SerializedBytes`.

2021-01-25 14:41 UTC, williamvigorr3 commented on core/src/main/kotlin/net/corda/core/serialization/CustomSerializationScheme.kt
> +    fun <T : Any> deserialize(bytes: SerializedBytes<T>, clazz: Class<T>, context: CustomSerializationContext): T
I managed to do this and no casts were needed in the end.

2021-01-25 14:46 UTC, JamesHR3 commented on core/src/main/kotlin/net/corda/core/serialization/CustomSerializationScheme.kt
> +interface CustomSerializationContext {
Are the values provided here options for (de)serialization? I wonder if it's worth at least pointing out a sensible default if the user has no specific requirements for these things. (I'm sure there's an "allow everything" under `ClassWhitelist` for example.) Incidentally, is `ClassWhitelist` public?

I notice `@DoNotImplement` here too - if this shouldn't be implemented, might be worth putting it in a separate file so it's less confusing what's actually part of the API and what isn't? (Might be worth doing this anyway.) If it should be implemented, how is the context and the scheme linked internally?

2021-01-25 16:01 UTC, williamvigorr3 commented on core/src/main/kotlin/net/corda/core/serialization/CustomSerializationScheme.kt
> +interface CustomSerializationContext {
So the idea here is we implement this interface inside Corda and a user should only use it inside there implementation of `CustomSerializationScheme.deserialize` and `CustomSerializationScheme.serialize`. I would still say it is still a part of the public API, just that a user should use it not implement it directly (like FlowSession for example).

The classloader might be required by the serialization library. If it calls class.forname after adding the name of the class to serialized blob.

I think the class whitelist is built from things annotated with `@CordaSerializable` (I will check that this is actually correct). These things can be both internal in Corda or user annotated in CorDapp itself. So a secure implementation will check that a class is in the whitelist before constructing it. Maybe this check is not necessary all the time it depends on the when deserialize is called.

2021-01-25 16:09 UTC, williamvigorr3 commented on core/src/main/kotlin/net/corda/core/serialization/CustomSerializationScheme.kt
> +interface CustomSerializationContext {
`ClassWhitelist` is public already.

2021-01-25 17:25 UTC, mnesbit commented on .ci/api-current.txt
> +##
This looks fine and the usual false flag that we get when abstract methods are added to corda

2021-01-26 08:49 UTC, JamesHR3 commented on core/src/main/kotlin/net/corda/core/serialization/CustomSerializationScheme.kt
> +interface CustomSerializationContext {
Right, got it - we'll give you a `CustomSerializationContext`, which is a `SerializationContext` but with just those fields we want you to inspect. We're guaranteed to give you the "right" classloader/whitelist, you just get the opportunity to look at those if you want to.

I think the following things might help a bit:
- Rename `CustomSerializationContext` (I'm not sure what to). I think the `Custom` out the front implies this is something you might want to implement (customize) to change the (de)serialization behaviour, which is not the case.
- Move it to its own file - that keeps the things you want to implement separate from the things you don't.
- Add to the kdocs some information about why you might want to inspect these properties on the context (security when constructing types on the whitelist, to ensure you can load the right type with `Class.forName` on the classloader)

2021-01-26 16:05 UTC, williamvigorr3 commented on core/src/main/kotlin/net/corda/core/serialization/CustomSerializationScheme.kt
> +interface CustomSerializationContext {
Okay I renamed this to `SerializationSchemeContext`. If moved it to it's own file and added more KDOC explaining how it is supposed to be used.

2021-01-26 16:39 UTC, JamesHR3 approved these changes, later dismissed
LGTM! Think the kdocs look a lot better now.

2021-01-28 09:30 UTC, JamesHR3 approved these changes

2021-01-28 09:31 UTC, merged