CORDA-4104 Implement custom serialization scheme discovery mechanism
corda/corda pull request #6854
Opened 2021-02-01 14:55 UTC by williamvigorr3

Discovers a CustomSerializationScheme implementation inside the drivers dir using a system property. Currently only one such scheme can be registered at any one time. This can be controlled by the system property experimental.corda.customSerializationScheme. This must be set to the fully qualified name of the class which implements `CustomSerializationScheme`.

2021-02-01 15:33 UTC, JamesHR3 requested changes
Couple of (minor) thoughts.

2021-02-01 15:33 UTC, JamesHR3 commented on core/src/main/kotlin/net/corda/core/serialization/internal/SerializationEnvironment.kt
> +
Might as well remove this whitespace change.

2021-02-01 15:33 UTC, JamesHR3 commented on core/src/main/kotlin/net/corda/core/serialization/internal/SerializationEnvironment.kt
> +        fun getCustomSerializationMagicFromSchemeId(schemeId: Int) : SerializationMagic {
Not sure this is the best place for this, as it's not really part of the serialization environment and more of a serialization utility. There's some stuff in `SerializationHelpers.kt` so maybe it could go in there? That also stops us pulling serialization internal classes into other packages.

2021-02-01 15:33 UTC, JamesHR3 commented on core-tests/src/test/kotlin/net/corda/coretests/transactions/TransactionBuilderTest.kt
> +        assertFailsWith<UnsupportedOperationException> {
Do you know what this exception says when you get it? Is it obvious that the problem is that the corresponding serialization scheme isn't registered? I'm wondering if we can throw a more descriptive exception here.

2021-02-01 15:33 UTC, JamesHR3 commented on node/src/main/kotlin/net/corda/node/internal/Node.kt
> +        if (schemaClass.constructors.size != 1 || schemaClass.constructors.single().parameters.isNotEmpty()) {
Is this condition overly restrictive? I suppose we can only use a no arg constructor anyway, but maybe it's ok scan for one, rather than enforce there's only one constructor with no arguments. (Happy to hear arguments why this is a bad idea.)

2021-02-01 15:33 UTC, JamesHR3 commented on node/src/main/kotlin/net/corda/node/internal/Node.kt
> +            throw ConfigurationException("$className does not implement ${CustomSerializationScheme::class.java.canonicalName}")
We should probably mention that this has come from the custom serialization scheme feature (so something like `"$className was declared as a custom serialization scheme but does not implement ${CustomSerializationScheme::class.java.canonicalName}"`). Could also potentially inherit from `ConfigurationException` to throw a `CustomSerializationSchemeConfigurationException` or something, but that might be overkill.

2021-02-01 15:55 UTC, williamvigorr3 commented on core/src/main/kotlin/net/corda/core/serialization/internal/SerializationEnvironment.kt
> +
Done 🤦

2021-02-01 16:08 UTC, williamvigorr3 commented on core/src/main/kotlin/net/corda/core/serialization/internal/SerializationEnvironment.kt
> +        fun getCustomSerializationMagicFromSchemeId(schemeId: Int) : SerializationMagic {
I agree with that (I was unsure where to put this). Unfortunately it cannot go in `SerializationHelpers.kt` because that is the `Serialization` project. It needs to go somewhere inside 'Core', so it can be used by both `TransactionBuilder.toWireTransaction` in core and `CustomSerializationSchemeAdapter` in `node-api`. We can either leave it here or put it in another file on its own (the package net.corda.core.serialization.internal).

2021-02-01 16:19 UTC, williamvigorr3 commented on core-tests/src/test/kotlin/net/corda/coretests/transactions/TransactionBuilderTest.kt
> +        assertFailsWith<UnsupportedOperationException> {
`java.lang.UnsupportedOperationException: Serialization scheme ([43555300000007], P2P) not supported.` Which is probably quite confusing. We can search in the blob for 0x435553 which is "CUS" in UTF-8 and throw something nicer.

2021-02-01 16:28 UTC, JamesHR3 commented on core/src/main/kotlin/net/corda/core/serialization/internal/SerializationEnvironment.kt
> +        fun getCustomSerializationMagicFromSchemeId(schemeId: Int) : SerializationMagic {
My mistake. I think a new file in `net.corda.core.serialization` makes sense for this (I'd have thought `internal` was things not meant to be imported elsewhere).

2021-02-01 18:03 UTC, williamvigorr3 commented on core/src/main/kotlin/net/corda/core/serialization/internal/SerializationEnvironment.kt
> +        fun getCustomSerializationMagicFromSchemeId(schemeId: Int) : SerializationMagic {
Hmm I thought `internal` is for things which we don't want to put in the public API for CorDApps (like this).

2021-02-02 12:22 UTC, williamvigorr3 commented on node/src/main/kotlin/net/corda/node/internal/Node.kt
> +        if (schemaClass.constructors.size != 1 || schemaClass.constructors.single().parameters.isNotEmpty()) {
I don't think this matters too much. I am not sure that how writing a constructor which takes arguments would be useful in practise (when you must have a no arg one) but I might be wrong. I have changed it to scan for a no arg one instead of require that there is only one.

2021-02-02 12:23 UTC, williamvigorr3 commented on node/src/main/kotlin/net/corda/node/internal/Node.kt
> +            throw ConfigurationException("$className does not implement ${CustomSerializationScheme::class.java.canonicalName}")
Done

2021-02-03 08:44 UTC, JamesHR3 approved these changes
LGTM

2021-02-04 09:04 UTC, merged