ENT-6330 Fixed reading jar entries in memory
corda/corda pull request #6960
Opened 2021-09-21 21:33 UTC by woggioni

This is a trivial fix that is however enough to allow to send zip bombs as attachments without having the node to crash, a size limit could be added for increased reliability

2021-09-22 09:06 UTC, woggioni commented
@mnesbit this is why `net.corda.v5.crypto.DigestService` is currently unusable

2021-09-22 09:11 UTC, alexey-kadyrov-r3 commented
> ... is why net.corda.v5.crypto.DigestService is currently unusable

Can you provide more details why it's unusable?

2021-09-22 09:17 UTC, woggioni commented
because it requires you to load in memory all the data you need to hash at once, leading the software vulnerable to malicious attacks like the one described in ENT-6330 (a zip bomb). The interface should expose a method that allows you to do streaming, something like

```
interface DigestService {
    fun hash(digestAlgorithmName: DigestAlgorithmName, withMessageDigestCallback : (MessageDigest) -> Unit): SecureHash 
} 
```

maybe using its own object if we don't want to expose MessageDigest

2021-09-22 09:21 UTC, alexey-kadyrov-r3 commented
We can add the streaming. However it's not the reason, it's consequence. The reason is tat there is no constrains on the attachments

2021-09-22 09:23 UTC, woggioni commented
would it make any sense to limit the size of an attachment to the amount of available memory? Because that is what we would have to do now

2021-09-22 09:29 UTC, alexey-kadyrov-r3 commented
It actually have to be well bellow than the available memory (regardless of the non streaming), I see it in range 10M-20M but for C4 it could be 50M-100M. Don't forget that even C4 not being multi tenant still executes a lot of flows concurrently.

2021-09-22 09:34 UTC, woggioni commented
with this change I've been able to successfully send and receive as an attachment [zblg.zip](https://www.bamsoftware.com/hacks/zipbomb/), a zip bomb which is 281 TB in size when expanded, and all I did was adding streaming to the hash computation

2021-09-30 13:47 UTC, rick-r3 requested changes

2021-09-30 13:47 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
> +            if(ctx.totalAttachmentSize >= params.maxTransactionSize) {
I think this is perhaps misunderstanding the problem https://r3-cev.atlassian.net/browse/ENT-6330 is trying to convey.   My understanding is that you can have a normal sized looking zip file that claims to contain very large files, or something along those lines.   There's one linked from the ticket in a github project, that is 778KB or so.

It may also be worthwhile checking the physical size, too.  I would probably also put the check closer to where we receive and install attachments.

2021-09-30 13:54 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
> +            if(ctx.totalAttachmentSize >= params.maxTransactionSize) {
Or am I misunderstanding and this is looking at the expanded form?

2021-09-30 13:54 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
> +            if(ctx.totalAttachmentSize >= params.maxTransactionSize) {
Ah, yes, maybe it is looking at expanded form since inside the openAsJAR

2021-09-30 13:54 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
> +            if(ctx.totalAttachmentSize >= params.maxTransactionSize) {
What happens if you try and write a test using the zip bomb example?

2021-09-30 14:06 UTC, woggioni commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
> +            if(ctx.totalAttachmentSize >= params.maxTransactionSize) {
I didn't write a unit test, I only tested it manually before enforcing the max transaction size limit. What happens is interesting: the node doesn't die but because of [this](https://r3-cev.atlassian.net/browse/CORE-2745) it doesn't verify the full bomb (which is several TB big) but only the first entry which is only about 4G, and since those aren't all loaded in memory at once it passes the verification. I expect it to fail now as 4GB would still exceed the max transaction size limit (will try it now)

2021-10-01 13:55 UTC, rick-r3 requested changes
I think this would be a good way to do it, except:

1) We already allowed total attachments, once decompressed, to exceed the maximum transactions size.  That was probably a mistake, since the max transaction size was originally targeted at memory footprint and, of course, the uncompressed size is important there.  So we can't suddenly introduce a new limit that might invalidate what has been done in the past in a legitimate fashion (welcome to the challenges of Corda!).
2) We have a `checkIsAValidJAR` on `NodeAttachmentService.kt` that looks like the sort of place we should be checking.  It's called by the import method for installing attachments.  We have some other security related defenses in there.  And if there's a blow up there, it's when receiving the attachment and trying to store it so it's more obvious who has sent it perhaps.
3) So if we can't complain about attachments exceeding that max transaction size limit (because it was allowed before), what can we try and look out for? Well, I think the only compromise is probably to think about compression ratios.
4) So I think the only thing we can really do is check the compression ratio in `checkIsValidJAR` is below some threshold. But if we use a threshold too low, it might be hit.  If we went with a ratio of 10x, that would work for the test and is unlikely to be hit.  You probably need to implement/find some counting input stream so you can compare the bytes actually read vs. the claimed entry sizes, and then complain if claimed entry sizes > 10x the input stream byte read count.

In hindsight, we should obviously have made the limit relate to decompressed size and then we wouldn't be where we are.

2021-10-01 14:10 UTC, woggioni commented
isn't a value of 10 a bit too strict? some text files (like logfiles) compress well above that value... I know there aren't many reason to add a logfile to a Corda transaction as an attachment, but why not?

2021-10-04 08:48 UTC, rick-r3 commented
Coming up with a heuristic is hard.  I think we should also incorporate the size (uncompressed).  i.e. we sort of don't care about the compression ratio if the end result is not so large.  We're looking for high compression ratio and end result very large.

Yes, 10 might be too small.

Got any examples for log files ?  What about PDFs, and maybe a JAR (code) ?  Worth just listing out some examples for consideration.  XML docs and JSON also good candidates to be attached.  I think log files are unlikely candidate but good data point.  I would assume things like images will compress badly, so not a concern.

2021-10-04 09:23 UTC, alexey-kadyrov-r3 commented
Can we have two limits? Like the size of the archive itself and also the size of the uncompressed data? And state that the latter will be applied only when we'll be uncompressing data - making clear that if the attachment passes the first limit it still may fail later due the second?

2021-10-04 09:27 UTC, woggioni commented
`.class` files rarely exceed a compression ratio of 2-3 but that is also variable: what if you put a huge static blank (which compresses pretty well) string constant in your java class?

XML and JSON rarely go beyond 4-5 but that also depends on the content (the more you repeat yourself the better it compresses)

already compressed image files like PNG and JPEG basically do not compress at all, so they're not an issue

I mentioned log files because they are consistently overly verbose and are unlikely to have low compression ratios.

I think it's hard to come up with a reliable heuristic for this but maybe something like "if the uncompressed size exceeds `maxTransactionSize` and the compression ratio is greater than 10 would do it"

2021-10-06 15:09 UTC, woggioni commented
I've added a check of the compression ration when uncompressed size exceeds `maxTransactionSize`, in short, attachment check now fails when both the uncompressed size exceed `maxTransactionSize` and the average compression ratio of the transaction attachments exceeds 10 (as an hardcoded value, don't know whether it is worth to make it configurable). I've tested it manually and seems to be ok, planning to add some automated tests as soon as I've time

2021-10-08 08:41 UTC, rick-r3 reviewed
I think this heuristic will have to do.  Anything more strict risks catching things inadvertently, but this is enough to catch the test zip in the issue raised.

I'd like to see this implemented at the attachment import stage though, rather than waiting until used in a transaction, which might also be easier to test, using a sample ZIP (okay to check in as a resource for a test).

The `NodeAttachmentService.import()` code path is executed when putting an attachment into the node, and it looks like it has access to things like max transactions size via `servicesForResolution.networkParameters`.

Note: fixing this is higher priority than any C5 work.  Apologies if that wasn't previously clear.

2021-10-08 08:41 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/contracts/TransactionVerificationException.kt
> +            txId, "The transaction attachments are too large and exceed both max transaction size and the maximum allowed compression ration", null)
`ration` -> `ratio`

`exceed both max transaction size` -> `exceed both max transaction size when decompressed`

2021-10-08 08:41 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
> +                        if(byte > 0) ctx.totalCompressedAttachmentSize += 1
`>= 0` ?

2021-10-08 09:25 UTC, woggioni commented on core/src/main/kotlin/net/corda/core/contracts/TransactionVerificationException.kt
> +            txId, "The transaction attachments are too large and exceed both max transaction size and the maximum allowed compression ration", null)
dunno why I keep writing "ration" 🤦🏿

2021-10-08 09:58 UTC, woggioni commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
> +                        if(byte > 0) ctx.totalCompressedAttachmentSize += 1
yeah, good catch!

2021-10-08 10:07 UTC, woggioni commented
I'm afraid I found a nasty issue: [JarInputStream loads the whole manifest file in memory in its own constructor](https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/util/jar/JarInputStream.java#L88-L103)

This means you can conveniently craft a zip file with a first entry named `META-INF/MANIFEST.MF` which expands to 4GB and easily deplete the JVM heap. The problem is that since the expansion happens internally (in the parent `ZipInputStream` class), I have no way to intercept the event and raise an exception before depleting the memory. there is actually a solution whihc is to have our own `JarInputStream` which is basically a copy of the JDK one except that it extends `net.corda.core.serialization.internal.ZipCheckerInputStream` (a ZipInputStream that crashes if the total size and the compression ratio are too big)

2021-10-08 10:14 UTC, woggioni commented
I know it isn't a particularly elegant solution but I cannot find another way :-(

2021-10-08 10:23 UTC, woggioni commented
ok that's not possible as [JarVerifier](https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/util/jar/JarInputStream.java#L48) isn't public.. I will simply read the attachment twice, one with a verifier stream and then, only if it passes the verification, will create a `JarInputStream`

2021-10-12 16:19 UTC, rick-r3 approved these changes

2021-10-13 08:46 UTC, merged