ENT-6586: Validate when signing that output states can be deserialized.
corda/corda pull request #7055
Opened 2022-02-03 18:24 UTC by adelel1

Validate when signing that output states can be deserialized.

2022-02-04 09:58 UTC, chrisr3 commented on core/src/main/kotlin/net/corda/core/node/ServiceHub.kt
> +            require(coreTransaction.outputStates.size >= 0) { "outputStates has an invalid size" }
Is it _possible_ for `outputStates` to have a negative size?

But I'm not understanding how this is supposed to "validate output states can be deserialized" regardless. If the goal is to force a `LazyMappedList` to become concrete then we already have this function:
```kotlin
package net.corda.core.internal

fun <T> List<T>.eagerDeserialise(onError: (TransactionDeserialisationException, Int) -> T? = { ex, _ -> throw ex }) {
    if (this is LazyMappedList<*, T>) {
        eager(onError)
    }
}
```

2022-02-04 10:20 UTC, rick-r3 requested changes

2022-02-04 10:20 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/node/ServiceHub.kt
> +        if (coreTransaction is TraversableTransaction) {
You know what?  This is more complicated.  I think maybe putting this on the raw signing methods is perhaps dangerous.  In theory, if you are not interested in recording the state in your vault then why should it matter if you can read the outputs outside of verify?   We could actually block some current valid use cases.

I actually think we can't blanket do this check.  What I think is a better way is for people to do the check in `SignTransactionFlow.checkTransaction()` which CorDapp authors have to implement.  We could implement some public helper methods for them to optionally call in that method, such as `checkAllOutputStatesCompatibleWithVault()` and `checkAllReferenceStatesCompatibleWithVault()`.   These can largely be modelled (and indeed perhaps call) some methods on `NodeVaultService` which are used later on by the vault.  Notably: 


```
        // Returns only output states that can be deserialised successfully.
        fun WireTransaction.deserializableOutputStates(): Map<Int, TransactionState<ContractState>> = withValidDeserialization(this.outputs, this.id)

        // Returns only reference states that can be deserialised successfully.
        fun LedgerTransaction.deserializableRefStates(): Map<Int, StateAndRef<ContractState>> = withValidDeserialization(this.references, this.id)
```

and then check that the sizes of those collections match the sizes of `this.outputs` and `this.references`.   

WDYT?   We'll have to obviously communicate this back to the customer, and indeed the kdocs entry for `checkTransaction()` should encourage their use. Not sure if that method is also mentioned in the broader documentation.  I think it also useful for complex scenarios to be able to get hands on the intermediate `Map<Int, ...>` in case you are not interested in the "all" part of the main helper methods.

Anything we offer must be in `core` module, and this is going to need to go to 4.9 (or later) because it adds API.

2022-02-04 10:41 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/node/ServiceHub.kt
> +            require(coreTransaction.outputStates.size >= 0) { "outputStates has an invalid size" }
Yes, I was going to make a comment about how the code looks misleading (the reality is that `outputStates` does what we want because it forcibly introspects the actual content) but the references to size here are misleading - since it managed to mislead you!   But there's a bigger philosophical issue I raise in my other comment.

2022-02-04 10:53 UTC, adelel1 commented on core/src/main/kotlin/net/corda/core/node/ServiceHub.kt
> +            require(coreTransaction.outputStates.size >= 0) { "outputStates has an invalid size" }
Yes, ok, it was my attempt at preventing the code being optimised away!

2022-02-04 12:40 UTC, adelel1 commented on core/src/main/kotlin/net/corda/core/node/ServiceHub.kt
> +        if (coreTransaction is TraversableTransaction) {
ENT-6586 updated following discussion. Decided to delay change to future. For now debug log message changed to a warn if the state cannot be deserialised.

2022-02-07 14:31 UTC, rick-r3 approved these changes

2022-02-07 14:43 UTC, chrisr3 commented on core/src/main/kotlin/net/corda/core/node/ServiceHub.kt
> +            require(coreTransaction.outputStates.size >= 0) { "outputStates has an invalid size" }
Is `outputStates` _not_ a `LazyMappedList` then? Or is it only a "computed property" that iterates over the actual `LazyMappedList`?

2022-02-07 16:16 UTC, adelel1 commented on core/src/main/kotlin/net/corda/core/node/ServiceHub.kt
> +            require(coreTransaction.outputStates.size >= 0) { "outputStates has an invalid size" }
No, it is a lazy mapped list.

2022-02-07 16:19 UTC, chrisr3 commented on core/src/main/kotlin/net/corda/core/node/ServiceHub.kt
> +            require(coreTransaction.outputStates.size >= 0) { "outputStates has an invalid size" }
If `outputStates` "is a" `LazyMappedList` then accessing its `size` property doesn't force it to deserialize anything... :thinking:

2022-02-07 18:05 UTC, merged