ENT-6791 New service lifecycle event published just before starting the state machine
corda/corda pull request #7164
Opened 2022-05-09 17:38 UTC by chriscochrane

At node startup, just prior to starting the state machine, a new service lifecycle event _ServiceLifecycleEvent.BEFORE_STATE_MACHINE_START_ is published.

2022-05-10 08:31 UTC, vkolomeyko submitted a review, later dismissed
LGTM

2022-05-13 07:59 UTC, vkolomeyko commented on node/src/integration-test/kotlin/net/corda/node/flows/FlowEntityManagerTest.kt
> +                alice.rpc.startFlow(::EntityManagerWithinTheSameDatabaseTransactionFlow).returnValue.getOrThrow(2000.seconds)
```suggestion
                alice.rpc.startFlow(::EntityManagerWithinTheSameDatabaseTransactionFlow).returnValue.getOrThrow(15.minutes)
```

2022-05-13 08:00 UTC, vkolomeyko approved these changes, later dismissed
One minor comment posted, but otherwise approved.

2022-05-13 09:12 UTC, chriscochrane commented
PR being held open until we get feedback from Marcello/SDX about this.

2022-05-13 09:44 UTC, lankydan commented on node/src/integration-test/kotlin/net/corda/node/flows/FlowEntityManagerTest.kt
> +                alice.rpc.startFlow(::EntityManagerWithinTheSameDatabaseTransactionFlow).returnValue.getOrThrow(2000.seconds)
Wouldn't think we want this change at all anyway, probably should be kept at 20 seconds

2022-05-13 09:46 UTC, lankydan commented on node/src/integration-test/kotlin/net/corda/node/services/CordaServiceLifecycleTests.kt
> +        assertEquals(listOf(BEFORE_STATE_MACHINE_START, STATE_MACHINE_STARTED), eventsCaptured)
Probably also worth a dedicated test that uses `BEFORE_STATE_MACHINE_START`, not sure if tests exist for the other notifications already.

2022-05-13 10:11 UTC, chriscochrane commented on node/src/integration-test/kotlin/net/corda/node/flows/FlowEntityManagerTest.kt
> +                alice.rpc.startFlow(::EntityManagerWithinTheSameDatabaseTransactionFlow).returnValue.getOrThrow(2000.seconds)
TBH I don't think I meant to include this change on this branch, I was probably just investigating a test failure - I'll just revert it.

2022-05-16 09:31 UTC, adelel1 requested changes

2022-05-16 09:31 UTC, adelel1 commented on node/src/integration-test/kotlin/net/corda/node/flows/FlowEntityManagerTest.kt
> +                alice.rpc.startFlow(::EntityManagerWithinTheSameDatabaseTransactionFlow).returnValue.getOrThrow(2000.seconds)
Shouldn't be taking 20secs at all. I think this needs reverting.

2022-05-16 09:31 UTC, adelel1 commented on node/src/integration-test/kotlin/net/corda/node/services/CordaServiceLifecycleTests.kt
> +        assertEquals(listOf(BEFORE_STATE_MACHINE_START, STATE_MACHINE_STARTED), eventsCaptured)
You could test STATE MACHINE STARTED events always come after all the BEFORE STATE MACHINE STARTED events.
This would test the event ordering is correct.
To check if the state machine has actually started or not, you could always try to run a flow. If you run a flow in BEFORE STATE MACHINE STARTED event, then I believe an exception is thrown which you can check for.

2022-05-16 09:31 UTC, adelel1 commented on node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
> +            nodeLifecycleEventsDistributor.distributeEvent(NodeLifecycleEvent.BeforeStateMachineStart(nodeServicesContext)).get()
This now means that the node could be hung at startup if a service never returns, or maybe it takes a long time.
Would it be useful to have a monitoring thread that output "warn" messages if a service it taking too long? e.g. every minute a log warn is output?

2022-05-16 10:20 UTC, chriscochrane commented on node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
> +            nodeLifecycleEventsDistributor.distributeEvent(NodeLifecycleEvent.BeforeStateMachineStart(nodeServicesContext)).get()
The test `corda service receives events` already tests the ordering of the events but I'll add a comment to that because it's not obvious it's checking the ordering.

WRT to running a flow - aha that sounds promising, I'll give that a try.

WRT monitoring - I could add that in but just to be clear - this is not a problem introduced by this change - previously, if a Corda service's constructor didn't return then the node would effectively hang at that point.
How long is "too long"? (How do we decide that?). Does the log interval change over time (I've seen that pattern somewhere)?
If we log warnings for this would this upset any log-monitoring systems customers might have in place that "get upset" when it sees warnings?

2022-05-16 17:36 UTC, adelel1 commented on node/src/integration-test/kotlin/net/corda/node/flows/FlowEntityManagerTest.kt
> +                alice.rpc.startFlow(::EntityManagerWithinTheSameDatabaseTransactionFlow).returnValue.getOrThrow(2000.seconds)
Shouldn't be taking 20secs at all. I think this needs reverting.

2022-05-16 17:38 UTC, chriscochrane commented on node/src/integration-test/kotlin/net/corda/node/flows/FlowEntityManagerTest.kt
> +                alice.rpc.startFlow(::EntityManagerWithinTheSameDatabaseTransactionFlow).returnValue.getOrThrow(2000.seconds)
Yes agree, reverted it locally and it works, will go in the next commit.

2022-06-09 10:41 UTC, adelel1 requested changes

2022-06-09 10:41 UTC, adelel1 commented on node/src/integration-test/kotlin/net/corda/node/services/CordaServiceLifecycleTests.kt
>              when (event) {
Can this when block be removed. We don't want to slow things down.

2022-06-09 11:24 UTC, chriscochrane commented on node/src/integration-test/kotlin/net/corda/node/services/CordaServiceLifecycleTests.kt
>              when (event) {
This delay is needed in order for the "_corda node blocks until all BEFORE_STATE_MACHINE_START events are processed_" test to FAIL is the node doesn't block when publishing the BEFORE_STATE_MACHINE_START event i.e. someone breaks this functionality.

25ms is about the shortest delay I used that reliably failed when the code was broken.

2022-06-09 11:42 UTC, adelel1 commented on node/src/integration-test/kotlin/net/corda/node/services/CordaServiceLifecycleTests.kt
>              when (event) {
What about setting 
eventsToBeCaptured = setOf(BEFORE_STATE_MACHINE_START, STATE_MACHINE_STARTED) 
then check the first 200 events are the BEFORE_STATE_MACHINE_START, and everything after is STATE_MACHINE_STARTED?
The delay shouldn't have any effect.

2022-06-09 12:17 UTC, adelel1 commented on node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
> +            nodeLifecycleEventsDistributor.distributeEvent(NodeLifecycleEvent.BeforeStateMachineStart(nodeServicesContext)).get()
OK, what about a couple of debug log events around this call, so at least we can tell if it gets hung in this part.

2022-06-09 12:45 UTC, chriscochrane commented on node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
> +            nodeLifecycleEventsDistributor.distributeEvent(NodeLifecycleEvent.BeforeStateMachineStart(nodeServicesContext)).get()
Yes I can add that, although I just noticed that the code that does the actual event distribution already contains some debug logging that describes what event is being sent to which observer:

NodeLifecycleEventDistributor::distributeEvent() {
....
    log.debug("Distributing event $event to: $it")
....
}

2022-06-10 17:03 UTC, adelel1 approved these changes

2022-06-10 18:55 UTC, vkolomeyko approved these changes

2022-06-10 18:56 UTC, merged