INFRA-1755 removed distributed testing code snippets
corda/corda pull request #7226
Opened 2022-08-03 10:03 UTC by E1P3

👮🏻👮🏻👮🏻 !!!! DESCRIBE YOUR CHANGES HERE !!!! DO NOT FORGET !!!! 👮🏻👮🏻👮🏻

# PR Checklist:

- [ ] Have you run the unit, integration and smoke tests as described [here](https://docs.r3.com/en/platform/corda/4.8/open-source/testing.html)?
- [ ] If you added public APIs, did you write the JavaDocs/kdocs?
- [ ] If the changes are of interest to application developers, have you added them to the changelog, and potentially the [release notes](https://docs.corda.net/head/release-notes.html) (`https://docs.r3.com/en/platform/corda/4.8/open-source/release-notes.html`)?
- [ ] If you are contributing for the first time, please read the [contributor agreement](https://docs.r3.com/en/platform/corda/4.8/open-source/contributing.html) now and add a comment to this pull request stating that your PR is in accordance with the [Developer's Certificate of Origin](https://docs.r3.com/en/platform/corda/4.8/open-source/contributing.html#merging-the-changes-back-into-corda).

Thanks for your code, it's appreciated! :)

2022-08-03 15:03 UTC, yarivus approved these changes, later dismissed
LGTM

2022-08-04 11:54 UTC, ronanbrowne requested changes

2022-08-04 11:54 UTC, ronanbrowne commented on build.gradle
> -apply plugin: 'com.r3.testing.distributed-testing'
@E1P3 Search the file there is another entry for "distributed-testing" above where the plugin is declared in the Build scrip block , This is the bit which declares this plugin as a build dependency - we want to remove this also

2022-08-05 08:54 UTC, ronanbrowne commented
@E1P3 check PR gates, so there's further code referencing it through out project that needs removal , ensure you run a gradle command locally to test the projects build code compiles (even ./gradlew help in this case should catch these issues)

2022-08-05 13:14 UTC, yarivus approved these changes, later dismissed
LGTM

2022-08-10 14:25 UTC, ronanbrowne requested changes

2022-08-10 14:25 UTC, ronanbrowne commented on build.gradle
>  import com.r3.testing.PodLogLevel
should be removed

2022-08-23 08:49 UTC, ronanbrowne requested changes

2022-08-23 08:49 UTC, ronanbrowne commented on gradle.properties
> +docker_plugin_version=5.3.0
@E1P3 Remove from here and put in constants. properties

then update build.gradle file to reference that in a similar manner to here https://github.com/corda/corda/blob/6d0875076f6e293fb503ba03b35e9b09b2b92862/build.gradle#L61

2022-09-08 10:58 UTC, yarivus reviewed
LGTM

2023-03-06 17:20 UTC, ronanbrowne approved these changes
lgtm

2023-03-06 17:58 UTC, yarivus reviewed
@ronanbrowne - this is a leftover PR from @E1P3 
Can you please indicate the intent of the PR - R we proceeding to merge it ?

2023-04-26 16:46 UTC, ronanbrowne commented
Closing will revisit this fresh as this PR is quite stale and I would like to verify some things here

2023-04-26 16:46 UTC, closed without merging