ENT-6893: First cut of telemetry integration.
corda/corda pull request #7247
Opened 2022-09-29 14:59 UTC by adelel1

First cut of telemetry integration.

2022-09-29 15:26 UTC, relyafi reviewed
A few comments, some notary specific, some not.

We may also need to think a bit more in future about adding notary specific spans within the uniqueness provider.

2022-09-29 15:26 UTC, relyafi commented on core/src/main/kotlin/net/corda/core/flows/FinalityFlow.kt
> +            }
This pattern seems to be being used repeatedly throughout many files, adding a lot of repetitive boilerplate code. I wonder if it would make sense to instead provide a function which takes a block of code to execute in the telemetry service. In this case, something like:

```suggestion
            serviceHub.telemetryService.span("recordTransactions", flowLogic = this) {
                logger.info("Recording transaction locally.")
                serviceHub.recordTransactions(statesToRecord, listOf(notarised))
                logger.info("Recorded transaction locally successfully.")
            }
            return notarised
```

2022-09-29 15:26 UTC, relyafi commented on core/src/main/kotlin/net/corda/core/flows/FinalityFlow.kt
> +                return notarised
I guess having this return here isn't harmful as the finally blocks will run anyway, but it doesn't look very good. Wouldn't it be cleaner to continue to have this as the last line of the function?

Strictly speaking it's only really part of the `notariseAndRecord`, not `recordTransactions` span anyway.

2022-09-29 15:26 UTC, relyafi commented on core/src/main/kotlin/net/corda/core/flows/FinalityFlow.kt
> +            val recordingTelemetryId = serviceHub.telemetryService.startSpan("recordTransactions", flowLogic = this)
The names given for the start span events seem to be specific to the function being called. I'm not convinced this is scalable, because we may get duplicate function names in different classes, which may then inadvertently map to the same span name. Would it be clearer to pass a fully qualified package name before the function name?

2022-09-29 15:26 UTC, relyafi commented on core/src/main/kotlin/net/corda/core/internal/notary/NotaryServiceFlow.kt
> +            val telemetryId = serviceHub.telemetryService.startSpan("commitInputStates", flowLogic = this)
This is fine in isolation - it will give you a span for each unique call to this. But it feels like we're missing valuable information here, which is a client supplied correlation id. From the notary perspective, it would be good if we were able to detect retries of this flow for a given initiating notarisation request, ideally across different notary workers.

2022-10-04 13:44 UTC, adelel1 commented on core/src/main/kotlin/net/corda/core/flows/FinalityFlow.kt
> +            }
Done. Yeah, I agree, had originally thought about this and tried initially to use a normal lambda but quasar was reporting un-instrumented methods when suspending. However I've now used inline lambda which works fine.

2022-10-11 16:09 UTC, adelel1 commented on core/src/main/kotlin/net/corda/core/flows/FinalityFlow.kt
> +                return notarised
Ok, yes, fixed.

2022-10-11 16:09 UTC, adelel1 commented on core/src/main/kotlin/net/corda/core/flows/FinalityFlow.kt
> +            val recordingTelemetryId = serviceHub.telemetryService.startSpan("recordTransactions", flowLogic = this)
Fixed. Updated to add fully qualified package name.

2022-10-11 16:16 UTC, adelel1 commented on core/src/main/kotlin/net/corda/core/internal/notary/NotaryServiceFlow.kt
> +            val telemetryId = serviceHub.telemetryService.startSpan("commitInputStates", flowLogic = this)
There is an existing rpc api, startFlowWithClientId. If this rpc is called I attach the client id to each span. There is also a new rpc api I added startFlowWithExternalId which also adds an external id to each span. The existing clientid api has additional implications which may not be wanted - hence i added the additional op.

Was there some other correlation id you wanted adding?
Flow and subflows are wrapped in a span, and certain other functions. If you let me know what else you want wrapped in a span, or the correlation id, i can add this in.

2022-10-12 14:09 UTC, relyafi commented on core/src/main/kotlin/net/corda/core/internal/notary/NotaryServiceFlow.kt
> +            val telemetryId = serviceHub.telemetryService.startSpan("commitInputStates", flowLogic = this)
Interesting, I wasn't aware of this functionality. I suspect what we could do is enhance the notarisation client flow so that it sends the (client corda node) flow id as a client or external id over when it requests notarisation to the notary worker. So it may be that we could achieve what we want using this functionality.

Would be good to have a chat at some point regarding the nuances of using client id vs external id. But I'm happy to drop this for now, sounds like we need a spike ticket notary side to investigate further if and when we want to add this.

2022-10-12 14:13 UTC, relyafi approved these changes, later dismissed
LGTM (mostly reviewed from Notary perspective)

2022-10-17 10:26 UTC, rick-r3 requested changes
I would walk back the `externalId` stuff (don't really want to change the API) and see if you can reuse the `externalTrace`.  But otherwise better to support opentelemetry on the client.

Are we able to get the telemetry stuff off of the public API some more ?  What's the tricky bit there?  Using it from system flows?  Happy to discuss.

2022-10-17 10:26 UTC, rick-r3 commented on build.gradle
> +    ext.opentelemetry_java_agent_version = constants.getProperty("opentelemetryJavaAgentVersion")
Very small thing, but would like to see consistency of `ext.open_telemetry` vs. `ext.opentelemetry` and `openTelemetry` vs. `opentelemetry` between these two lines.

2022-10-17 10:26 UTC, rick-r3 commented on .ci/api-current.txt
> -  public <init>(net.corda.core.context.InvocationOrigin, net.corda.core.context.Trace, net.corda.core.context.Actor, net.corda.core.context.Trace, net.corda.core.context.Actor, java.util.List<?>, Str
We should discuss these "deletes"

2022-10-17 10:26 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/messaging/CordaRPCOps.kt
> +    fun <T> startFlowDynamicWithExternalId(externalId: String, logicType: Class<out FlowLogic<T>>, vararg args: Any?): FlowHandle<T>
Not sure I like this idea.  I would expect if we want to pass in open telemetry stuff it would seamlessly come in over RPC protocol.  Let's discuss.

2022-10-17 10:26 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/context/InvocationContext.kt
> +    val clientId: String? = null,
Need to be covered by kdocs.

2022-10-17 10:26 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/context/InvocationContext.kt
> +    val clientId: String? = null,
See later comment about `externalId`.

2022-10-17 10:26 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/flows/FinalityFlow.kt
> +        serviceHub.telemetryService.span("${this::class.java.name}#notariseAndRecord", flowLogic = this) {
I wonder if we really need to add these or if the `subFlow` and `recordTransactions` being instrumented would be enough?

2022-10-17 10:26 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/flows/FlowLogic.kt
> +            return stateMachine.suspend(request, maySkipCheckpoint = false)[this]!!.checkPayloadIs(receiveType)
Does suspending inside the `span` call work?

2022-10-17 10:26 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/internal/cordapp/CordappImpl.kt
> +                telemetryComponents = emptyList(),
Need to get my head around what these are.

2022-10-17 10:26 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/internal/notary/NotaryServiceFlow.kt
> +            serviceHub.telemetryService.span("${this::class.java.name}#call:commitInputStates", flowLogic = this) {
Just wondering how much we should show the internal workings of the notary as span data.  Not sure.

2022-10-17 10:26 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/node/ServiceHub.kt
> +     * Return the singleton instance of the given Corda telemetry component type. This is a class implemnets TelemetryComponent
typo: implements

2022-10-17 10:26 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/node/ServiceHub.kt
> +    val telemetryService: TelemetryService
wondering why public

2022-10-17 10:26 UTC, rick-r3 commented on node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
> +        val loadedTelemetryComponents = cordappLoader.cordapps.flatMap { it.telemetryComponents }.filterNot {
Worth declaring the type of this collection.  Have to drill way down to figure out these are classes.

2022-10-17 10:26 UTC, rick-r3 commented on node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
> +    fun <T : TelemetryComponent> installTelemetryComponent(telemetryComponentClass: Class<T>): T {
Is the return type used?  Worth maybe having this as return type `Unit` as this method isn't the kind that returns something.  It installs stuff into `cordappTelemetryComponents` it seems.

2022-10-17 10:26 UTC, rick-r3 commented on node/src/main/kotlin/net/corda/node/internal/CordaRPCOpsImpl.kt
> +    private fun InvocationContext.withExternalId(externalId: String) = copy(externalId = externalId)
See comments elsewhere about `externalId`

2022-10-17 10:26 UTC, rick-r3 commented on node/src/main/kotlin/net/corda/node/services/config/NodeConfigurationImpl.kt
> +        val telemetry = TelemetryConfiguration(openTelemetryEnabled = true, simpleLogTelemetryEnabled = false, spanStartEndEventsEnabled = true)
Is this a good default?  Does open telemetry require something to be on the class path to enable it fully, or will this default to having telemetry on always?

2022-10-17 10:26 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/context/InvocationContext.kt
> +    val clientId: String? = null,
Actually I think there might be something we can use on here already rather than `externalId`.  `externalTrace` looks roughly what is required.  Not quite as much user control but I think we should go down that path than adding a new id and APIs to the platform.

2022-10-17 10:27 UTC, rick-r3 commented on .ci/api-current.txt
> -  public <init>(net.corda.core.context.InvocationOrigin, net.corda.core.context.Trace, net.corda.core.context.Actor, net.corda.core.context.Trace, net.corda.core.context.Actor, java.util.List<?>, Str
I guess if we walk back externalId, there's no change?

2022-10-25 16:53 UTC, adelel1 commented
> I would walk back the `externalId` stuff (don't really want to change the API) and see if you can reuse the `externalTrace`. But otherwise better to support opentelemetry on the client.
> 
> Are we able to get the telemetry stuff off of the public API some more ? What's the tricky bit there? Using it from system flows? Happy to discuss.

ExternalId stuff removed. 
Telemetry now only exposes the following on the public api...

interface TelemetryService {
    fun getOpenTelemetry(): OpenTelemetry?
}

Where openTelemetry is io.opentelemetry.api.OpenTelemetry, so if flows which to interact with telemetry, i.e. create their own spans or add baggage, they do so via the opentelemetry api.

2022-10-25 16:54 UTC, adelel1 commented on build.gradle
> +    ext.opentelemetry_java_agent_version = constants.getProperty("opentelemetryJavaAgentVersion")
Done. java_agent_version removed.

2022-10-25 16:55 UTC, adelel1 commented on .ci/api-current.txt
> -  public <init>(net.corda.core.context.InvocationOrigin, net.corda.core.context.Trace, net.corda.core.context.Actor, net.corda.core.context.Trace, net.corda.core.context.Actor, java.util.List<?>, Str
Yes, no change now to api-current.txt.

2022-10-25 16:56 UTC, adelel1 commented on core/src/main/kotlin/net/corda/core/messaging/CordaRPCOps.kt
> +    fun <T> startFlowDynamicWithExternalId(externalId: String, logicType: Class<out FlowLogic<T>>, vararg args: Any?): FlowHandle<T>
Yes, this operation now removed.

2022-10-25 16:56 UTC, adelel1 commented on core/src/main/kotlin/net/corda/core/context/InvocationContext.kt
> +    val clientId: String? = null,
external id removed.

2022-10-25 16:58 UTC, adelel1 commented on core/src/main/kotlin/net/corda/core/flows/FinalityFlow.kt
> +        serviceHub.telemetryService.span("${this::class.java.name}#notariseAndRecord", flowLogic = this) {
For now its left in, but yeah, up to us to decide what we want. Maybe @relyafi has a view as well.

2022-10-25 16:59 UTC, adelel1 commented on core/src/main/kotlin/net/corda/core/node/ServiceHub.kt
> +    val telemetryService: TelemetryService
If a flow wants to do their own telemetry stuff, they use this to get the opentelemetry handle.

2022-10-25 16:59 UTC, adelel1 commented on node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
> +        val loadedTelemetryComponents = cordappLoader.cordapps.flatMap { it.telemetryComponents }.filterNot {
Done.

2022-10-25 16:59 UTC, adelel1 commented on node/src/main/kotlin/net/corda/node/internal/AbstractNode.kt
> +    fun <T : TelemetryComponent> installTelemetryComponent(telemetryComponentClass: Class<T>): T {
Yes, done.

2022-10-25 17:00 UTC, adelel1 commented on node/src/main/kotlin/net/corda/node/internal/CordaRPCOpsImpl.kt
> +    private fun InvocationContext.withExternalId(externalId: String) = copy(externalId = externalId)
Removed.

2022-10-25 17:04 UTC, relyafi commented on core/src/main/kotlin/net/corda/core/flows/FinalityFlow.kt
> +        serviceHub.telemetryService.span("${this::class.java.name}#notariseAndRecord", flowLogic = this) {
Hmm, fair point. The only value I can see in keeping it, is it would let you (indirectly) determine whether it was an issuance transaction or not, because the time taken by `notariseAndRecord` would be roughly equal to `recordTransactions` for issuance, since the subflow wouldn't run.

Not sure how valuable that really is though.

2022-10-25 17:04 UTC, adelel1 commented on node/src/main/kotlin/net/corda/node/services/config/NodeConfigurationImpl.kt
> +        val telemetry = TelemetryConfiguration(openTelemetryEnabled = true, simpleLogTelemetryEnabled = false, spanStartEndEventsEnabled = true)
Yes, to first bit. OpenTelemetry requires either the corda jar to be started with the open telemetry agent. Or it requires the open telemetry driver (part of this project), to be included in the drivers directory. The open telemetry driver uses the open telemetry sdk. So given the user actually has to do something to get opentelemetry running then didn't seem right to also have them set a configuration flag. So unless they do the above actions they wont get telemetry.

2022-10-25 17:24 UTC, adelel1 commented on core/src/main/kotlin/net/corda/core/flows/FlowLogic.kt
> +            return stateMachine.suspend(request, maySkipCheckpoint = false)[this]!!.checkPayloadIs(receiveType)
Only works because that span call is actually an inline lambda, otherwise it caused quasar to balk.

2022-10-25 17:26 UTC, adelel1 commented on core/src/main/kotlin/net/corda/core/internal/cordapp/CordappImpl.kt
> +                telemetryComponents = emptyList(),
Basically to enable testing. i.e. allows me to insert in my own telemetry components into the Telemetry Service, as part of a CorDapp.

2022-10-28 09:43 UTC, rick-r3 reviewed
I still think there's problems with stuff being removed from `api-current.txt`.  If we can at least get to the point where it is only methods where last param is `DefaultConstructorMarker` that seem to be removed we will be in a better place.

2022-10-28 09:43 UTC, rick-r3 commented on .ci/api-current.txt
> -  public <init>(net.corda.core.context.InvocationOrigin, net.corda.core.context.Trace, net.corda.core.context.Actor, net.corda.core.context.Trace, net.corda.core.context.Actor, java.util.List<?>, Str
I think technically we have to preserve the API here.

2022-10-28 09:43 UTC, rick-r3 commented on .ci/api-current.txt
> -  public final net.corda.core.context.InvocationContext copy(net.corda.core.context.InvocationOrigin, net.corda.core.context.Trace, net.corda.core.context.Actor, net.corda.core.context.Trace, net.cor
and here

2022-10-28 09:43 UTC, rick-r3 commented on .ci/api-current.txt
> +  public <init>(java.time.Duration, int, boolean, java.time.Duration, int, int, java.time.Duration, double, int, int, java.time.Duration, boolean)
and here

2022-10-28 09:43 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/node/ServiceHub.kt
> +    /**
Would this not be better put onto `TelemetryService` ?

2022-10-28 09:43 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/node/ServiceHub.kt
> +    val telemetryService: TelemetryService
okay.

2022-10-28 09:43 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/node/ServiceHub.kt
> +    val telemetryService: TelemetryService
But I note that everywhere the `OpenTelemetryHandle` is returned we actually return `null`?  Am I looking at it wrong.  I presume it should return something?

I wonder actually if we should delete the `OpenTelemetryHandle` type entirely and have those methods look like:

`fun <T> getOpenTelemetry(openTelemetryClass: Class<T>): T?`

so the user specifies the opentelemetry class and we just try and cast to it ?

2022-10-28 09:43 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/internal/telemetry/OpenTelemetryComponent.kt
> +    val spans = ConcurrentHashMap<UUID, SpanInfo>()
How confident are you that spans don't leak when a flow exits / errors?

2022-10-28 09:45 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/node/ServiceHub.kt
> +    /**
Sorry, that comment is one line too high up and looks mad here.  But look at line 197 !!

2022-10-28 11:27 UTC, adelel1 commented on core/src/main/kotlin/net/corda/core/internal/telemetry/OpenTelemetryComponent.kt
> +    val spans = ConcurrentHashMap<UUID, SpanInfo>()
> How confident are you that spans don't leak when a flow exits / errors?

The flows are wrapped by an inline lambda (span and spanForFlow) defined in TelemetryServiceImpl. There is a finally block wrapping the flow block that does the endSpan. So should be no leaks.

2022-10-28 11:31 UTC, adelel1 commented on core/src/main/kotlin/net/corda/core/node/ServiceHub.kt
> +    /**
Probably not, these relate to the telemetry components which have come from a CorDapp. Currently its possible to define your own telemetry components within a CorDapp. This functionality is currently used for testing.

2022-10-28 11:33 UTC, adelel1 commented on .ci/api-current.txt
> -  public <init>(net.corda.core.context.InvocationOrigin, net.corda.core.context.Trace, net.corda.core.context.Actor, net.corda.core.context.Trace, net.corda.core.context.Actor, java.util.List<?>, Str
Yes, all api changes done.  Yes, there is a single method left where last param is DefaultConstructorMarker. This is for CordaRPCClientConfiguration

2022-10-28 11:34 UTC, adelel1 commented on .ci/api-current.txt
> -  public final net.corda.core.context.InvocationContext copy(net.corda.core.context.InvocationOrigin, net.corda.core.context.Trace, net.corda.core.context.Actor, net.corda.core.context.Trace, net.cor
Done.

2022-10-28 11:34 UTC, adelel1 commented on .ci/api-current.txt
> +  public <init>(java.time.Duration, int, boolean, java.time.Duration, int, int, java.time.Duration, double, int, int, java.time.Duration, boolean)
This is as is, relates to CordaRPCClientConfiguration.

2022-10-28 11:50 UTC, adelel1 commented on core/src/main/kotlin/net/corda/core/node/ServiceHub.kt
> +    val telemetryService: TelemetryService
Yeah, ok, would like to fix this up in a subsequent PR. As also need to test spans are propagated properly as well, when created by user via the OT api this returns.

2022-10-28 13:04 UTC, rick-r3 approved these changes

2022-10-28 13:41 UTC, merged