ENT-6914 JDK11 compatibility preview
corda/corda pull request #7261
Opened 2022-11-07 14:20 UTC by arshadm

👮🏻👮🏻👮🏻 !!!! DESCRIBE YOUR CHANGES HERE !!!! DO NOT FORGET !!!! 👮🏻👮🏻👮🏻
Added Jenkinsfile to preview JDK 11 snapshots in corda-dev to the feature branch.

# PR Checklist:

- [ ] Have you run the unit, integration and smoke tests as described [here](https://docs.r3.com/en/platform/corda/4.8/open-source/testing.html)?
- [ ] If you added public APIs, did you write the JavaDocs/kdocs?
- [ ] If the changes are of interest to application developers, have you added them to the changelog, and potentially the [release notes](https://docs.corda.net/head/release-notes.html) (`https://docs.r3.com/en/platform/corda/4.8/open-source/release-notes.html`)?
- [ ] If you are contributing for the first time, please read the [contributor agreement](https://docs.r3.com/en/platform/corda/4.8/open-source/contributing.html) now and add a comment to this pull request stating that your PR is in accordance with the [Developer's Certificate of Origin](https://docs.r3.com/en/platform/corda/4.8/open-source/contributing.html#merging-the-changes-back-into-corda).

Thanks for your code, it's appreciated! :)

2022-11-07 18:04 UTC, adelel1 approved these changes, later dismissed

2022-11-07 18:11 UTC, chrisr3 commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
> +                        JDK1_2_CLASS_FILE_FORMAT_MAJOR_VERSION..JDK11_CLASS_FILE_FORMAT_MAJOR_VERSION)
This doesn't make sense, unless you have already ditched the DJVM.

The DJVM sandbox _**must**_ use Java 8, which is why this test exists.

2022-11-07 18:15 UTC, chrisr3 commented on core-deterministic/testing/verifier/build.gradle
> +    name addArchiveAppendix(jar.baseName)
`baseName` is deprecated, and has been replaced with `archiveBaseName`.

2022-11-07 18:21 UTC, chrisr3 commented on client/jackson/build.gradle
> +    name addArchiveAppendix(jar.baseName)
Whatever `addArchiveAppendix()` does, it should accept `Provider<String>` and `map` it to another `Provider<String>` so that this can become:
```
name addArvhiveAppendix(jar.archiveBaseName)
```
or possibly
```
name addArchiveAppendix( jar.flatMap { it.archiveBaseName }
```
if
```
def jar = tasks.named('jar', Jar)
```

2022-11-07 18:31 UTC, chrisr3 requested changes, later dismissed
Either fix the check for ensuring contract verification uses Java 8, or rip out the DJVM. Because your current approach is inconsistent.

2022-11-08 09:47 UTC, chrisr3 commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
> +                        JDK1_2_CLASS_FILE_FORMAT_MAJOR_VERSION..JDK11_CLASS_FILE_FORMAT_MAJOR_VERSION)
The filter was _explicitly added_ (by @adelel1) to prevent Java 9+ bytecode entering the backchain, and this was done for the sake of the DJVM which will never be able to handle Java 9+ bytecode.

Updating it to prevent Java 12+ bytecode entering the backchain is _**meaningless**_.

I would rather you removed the DJVM entirely rather than killing it by slow poison. Because the DJVM can _never_ be enabled once Java 9+ bytecode enters the backchain.

2022-11-10 11:18 UTC, arshadm commented on core-deterministic/testing/verifier/build.gradle
> +    name addArchiveAppendix(jar.baseName)
Does not appear to work in Gradle 5.6.4. I tried to use archiveBaseName in the serialization-djvm project which actually sets the value in the jar {...} task using archiveBaseName, but accessing in the publish task only works if I use jar.baseName

2022-11-10 14:25 UTC, adelel1 approved these changes

2022-11-10 14:26 UTC, arshadm commented on client/jackson/build.gradle
> +    name addArchiveAppendix(jar.baseName)
Need to rethink this approach to adding the archive appendix, will look at this in parallel with the Cord Ent build.

2022-11-10 14:30 UTC, merged