ENT-9875: Added new network parameters
corda/corda pull request #7398
Opened 2023-06-21 16:58 UTC by tomstark99

- Added `transactionRecoveryPeriod`
- Added `confidentialIdentityPreGenerationPeriod`

These new parameters are currently set to be nullable meaning they can be ignored, and the duration if not specified will be null rather than, e.g., 0. This currently allows for nothing changing/breaking in the node-api

_Note: if these params can stay as nullable, then the deprecated constructor might not even be needed (since the existing one will still work), and needs to be discussed._

2023-06-26 18:17 UTC, colljos requested changes
Recommend adding some tests to associated `NetworkParametersTest`.

2023-06-26 18:20 UTC, colljos commented on core/src/main/kotlin/net/corda/core/node/NetworkParameters.kt
> + * @property confidentialIdentityPreGenerationPeriod Time period in days for when Confidential Identities keys were last backed up. The
"period in days" => drop "days"?
As the type is a Duration you can pass in other Duration specifications (e.g period in hours might be useful).

2023-07-04 09:26 UTC, colljos approved these changes, later dismissed
LGTM!

2023-07-07 08:27 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/node/NetworkParameters.kt
> + * @property recoveryMaximumBackupInterval Time period for how far back transactions will be recovered. The assumption is that
`recoveryMaximumBackupInterval` is a default that will be used by the recovery flows to set how far back in time to consider for recovery.  The expectation is that a node will restore to a database backup no older than this, by default, when attempting recovery.  It can be overridden by specifying an override to the flow.  It will also be overridden if the setting per-node in the node configuration is specified.  An override to the flow takes priority in terms of overrides.

2023-07-07 08:27 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/node/NetworkParameters.kt
> + * @property confidentialIdentityMaximumBackupInterval Time period for when Confidential Identities keys were last backed up. The
`confidentialIdentityMaximumBackupInterval` is the minimum age of a generated confidential identity before it can be used, by default, unless overridden in the node configuration or a more recent database backup is indicated via RPC / shell.   It is optional in both network parameters and node configuration and if no value is set for either, is assumed to be zero (open to negotiation.... )

However, that description suggests the name is wrong.

`confidentialIdentityMinimumBackupInterval` would be better.

2023-07-14 08:51 UTC, rick-r3 approved these changes

2023-07-14 10:58 UTC, adelel1 approved these changes

2023-07-14 11:02 UTC, merged