ENT-9876: WIP
corda/corda pull request #7423
Opened 2023-07-14 16:31 UTC by shamsasari

2023-07-19 17:34 UTC, colljos requested changes
A few small items ... otherwise looks good!

2023-07-19 17:34 UTC, colljos commented on node/src/main/kotlin/net/corda/node/services/persistence/DBEncryptionService.kt
> +    private fun createKek(ourIdentity: Party, keyId: UUID): Key {
```suggestion
    private fun createKey(ourIdentity: Party, keyId: UUID): Key {
```

2023-07-19 17:34 UTC, colljos commented on core-tests/src/test/kotlin/net/corda/coretests/flows/FinalityFlowTests.kt
> +                    "from ${DBTransactionStorage.DBTransaction::class.java.name} where txId = :transactionId",
Switched to using JPA syntax.
I wonder why this worked before using native db field name?

2023-07-19 17:34 UTC, colljos commented on node-api/src/main/kotlin/net/corda/nodeapi/internal/crypto/Encryption.kt
> +     * An optional [authenticatedData] bytes can also be provided which will be authenticated alongside the ciphertext but not encrypted.
Would we use this for example to store/share the Sender distribution record **timestamp** with the receiver?

2023-07-19 17:34 UTC, colljos commented on node/src/main/kotlin/net/corda/node/services/persistence/DBTransactionStorageLedgerRecovery.kt
> +            encryptionService.encrypt(metadata.distributionList.serialize().bytes)
This is using AMQP serialisation right?
Rick preferred a lightweight on-the-wire representation (hence the simple setializer class)

2023-07-20 09:07 UTC, shamsasari commented on node-api/src/main/kotlin/net/corda/nodeapi/internal/crypto/Encryption.kt
> +     * An optional [authenticatedData] bytes can also be provided which will be authenticated alongside the ciphertext but not encrypted.
That's right.

2023-07-20 09:09 UTC, shamsasari commented on node/src/main/kotlin/net/corda/node/services/persistence/DBEncryptionService.kt
> +    private fun createKek(ourIdentity: Party, keyId: UUID): Key {
This is not actually a typo! KEK stands for key encryption key. I can add that to method comments.

2023-07-20 09:10 UTC, shamsasari commented on node/src/main/kotlin/net/corda/node/services/persistence/DBTransactionStorageLedgerRecovery.kt
> +            encryptionService.encrypt(metadata.distributionList.serialize().bytes)
OK, I did wonder why we were doing that. I can do if that's still the case.

2023-07-21 09:27 UTC, colljos commented on node/src/main/kotlin/net/corda/node/services/persistence/DBEncryptionService.kt
> +    private fun createKek(ourIdentity: Party, keyId: UUID): Key {
maybe capitalise KEK so it doesn't look like a typo ;-)

2023-07-21 15:02 UTC, rick-r3 commented on node/src/main/kotlin/net/corda/node/services/persistence/DBTransactionStorageLedgerRecovery.kt
> +            encryptionService.encrypt(metadata.distributionList.serialize().bytes)
Yes.  There are going to be a lot of distribution records, and I wanted to make them as small as possible in terms of incremental storage foot print.  The structure of them is very simple, so not too problematic.  Side note: we probably will have to look at the Archiving tool to make sure it archives distribution records too, or have some clean up processing at some point.

This was also the motivation for having converted each peer into an integer (Long).  It takes up much less space than the X500 name.  i.e. better to normalise it from an RDBMS perspective. Ideally we would have used a sequence number vs. X500 name, which it would have been nice if the network map had taken care of, but we ended up with a crude hash to make it reproducible, but in the back of my mind (and hopefully a JIRA) was to re-visit this mechanism. A sequence number issued locally is vulnerable to loss (e.g. with database loss) for any new member arriving, so deterministic hash is better, but need to be wary of the collision prospects.  I know we could expand it to a SecureHash to avoid collision but has 4x storage cost.  Maybe would just have to pay it.

Before we worry about that further, what does AES do to the storage size of the binary data stored on the receiver side?

Ideally we should try and minimise the storage space required for these records, but still need encryption and with no realistic chance of collision if hashing the X500 name for size reasons.  Side note: I know SecureHash of X500 name cannot collide, as it is used for the Artemis queue names in the P2P layer, so if it did collide, it already would be a problem.

2023-07-21 15:20 UTC, shamsasari commented on node/src/main/kotlin/net/corda/node/services/persistence/DBTransactionStorageLedgerRecovery.kt
> +            encryptionService.encrypt(metadata.distributionList.serialize().bytes)
I'll implement the hand-rolled serialisation of the dist list. Do you want the participant hashing code reverted back as well and represented as longs instead of X.500 in this PR? Representing them as SHA256 hashes should be a separate ticket anyway.

2023-07-21 15:27 UTC, rick-r3 commented on node/src/main/kotlin/net/corda/node/services/persistence/DBTransactionStorageLedgerRecovery.kt
> +            encryptionService.encrypt(metadata.distributionList.serialize().bytes)
Yes, let's revert them to longs in this PR.

2023-07-25 14:01 UTC, shamsasari commented
The hashing code has been reverted, and the new `senderRecordedTimestamp` field has been incorporated into the AES-GCM encryption as the tamperproof authenticated additional data.

2023-07-25 17:03 UTC, colljos commented
LTGM - will test it on a branch with the LedgerRecovery flow to see if all continues working as expected.

2023-07-25 17:03 UTC, colljos submitted a review, later dismissed

2023-07-27 12:45 UTC, shamsasari commented
Finally, the PR is green.

2023-07-31 09:34 UTC, shamsasari commented
Ready for review @rick-r3 and @adelel1

2023-07-31 12:26 UTC, rick-r3 commented on node/src/main/kotlin/net/corda/node/services/persistence/AesDbEncryptionService.kt
> +        buffer.put(1)  // Version tag
Should this be a `const` ?

2023-07-31 15:44 UTC, shamsasari commented on node/src/main/kotlin/net/corda/node/services/persistence/AesDbEncryptionService.kt
> +        buffer.put(1)  // Version tag
I guess it can be.

2023-08-07 12:50 UTC, adelel1 commented on node/src/main/kotlin/net/corda/node/services/persistence/AesDbEncryptionService.kt
> +        buffer.putUUID(keyId)
This keyId is stored in the clear here. 
The key id and node identity is used as key material to create the Secret Key in the createKEK function.
Wondering if there is any possibility the secret key can be derived if you know the key id and node identity. Does the SecretKeySpec create some random key based on the input key material?

2023-08-07 13:22 UTC, shamsasari commented on node/src/main/kotlin/net/corda/node/services/persistence/AesDbEncryptionService.kt
> +        buffer.putUUID(keyId)
No, `createKEK` creates a deterministic KEK using the publicly available X.500 name and key ID. So anyone who receives ciphertext created from this encryption service (e.g. the dist list recipient) will be able to create the KEK. However, that doesn't matter as the KEK isn't used to encrypt the dist list. An attacker would need access to the AES keys stored in the node's db to be able to decrypt the dist list. But if it has access to the db, then it has access to all the node's tx data anyway, and so decrypting the dist list does not give them any extra information. This is why I've documented this service should only be used to encrypt data that's already stored plaintext in the node.

The only purpose of the KEK is to obfuscate the persisted AES keys. That can also be done by doing a simple XOR, which would have the advantage of not being a real encryption key and thus causing people to think it's a key to be kept secret.

2023-08-08 13:23 UTC, adelel1 approved these changes, later dismissed
LGTM

2023-08-17 13:41 UTC, shamsasari commented
@rick-r3 and @colljos please take another look. The code is now up-to-date with respect to https://github.com/corda/corda/pull/7445.

2023-08-18 07:48 UTC, colljos commented
> @rick-r3 and @colljos please take another look. The code is now up-to-date with respect to #7445.

Thanks @shamsasari .
I have been testing and fixing issues on a follow-up PR: https://github.com/corda/corda/pull/7446

2023-08-18 08:52 UTC, shamsasari commented
@rick-r3 good to merge?

2023-08-22 09:56 UTC, adelel1 approved these changes

2023-08-22 10:14 UTC, merged