ENT-6914 - Updated project to build with Gradle 7.6, Kotlin 1.8 and JDK 17
corda/corda pull request #7482
Opened 2023-09-05 10:06 UTC by arshadm

This PR upgrades Corda OS to build with Gradle 7.6, Kotlin 1.8 and JDK 17.

Major changes in this PR:

    1. JDK17 JCE Provider now has built-in support for eddsas, corda uses
       the bouncycastle (i2p) implementation. This PR removes the conflicting
       algorithms from the built-in JCE provider.
    
    2. JavaScript scripting has been removed from the JDK, the corda log4j config was using
       scripting to conditionally output additional diagnostic info if the MDC
       was populated. This PR has removed the scripting.
    
    3. The artifactory plug-ins used are now deprecated, this PR has removed them
       and uses the same code as Corda 5 for publishing to artifactory.
    
    4. Javadoc generation has been modified to use the latest dokka plug-ins.
    
    5. Gradle 7.6 has implemented an incredibly annoying change where transitive
       dependencies are not put on the compile classpath, so that they have to be
       explicitly added as dependencies to projects.
    
    6. Mockito has been updated, which sadly meant that quite a few source files
       have to changes to use the new (org.mockito.kotlin) package name. This makes
       this PR appear much larger than it is.
    
    7. A number of tests have been marked as ignored to get a green, broadly they fall
       into 3 classes.

       The first is related to crypto keypair tests, it appears some logic
       in the JDK prefers to use the SunJCE implementation and we prefer to use
       bouncycastle. I believe this issue can be fixed with better test setup.
    
       The second group is related to our use of a method called "uncheckedCast(..)",
       the purpose of this method was to get rid of the annoying unchecked cast compiler
       warning that would otherwise exist. It looks like the Kotlin 1.9 compiler type
       inference differs and at runtime sometimes the type it infers is "Void" which causes
       an exception at runtime. The simplest solution is to use an explicit cast instead of
       unchecked cast, Corda 5 have removed unchecked cast from their codebase.
    
       The third class are a number of ActiveMQ tests which appear to have a memory leak somewhere.

# PR Checklist:

- [x] Have you run the unit, integration and smoke tests as described [here](https://docs.r3.com/en/platform/corda/4.8/open-source/testing.html)?
- [-] If you added public APIs, did you write the JavaDocs/kdocs?
- [-] If the changes are of interest to application developers, have you added them to the changelog, and potentially the [release notes](https://docs.corda.net/head/release-notes.html) (`https://docs.r3.com/en/platform/corda/4.8/open-source/release-notes.html`)?
- [x] If you are contributing for the first time, please read the [contributor agreement](https://docs.r3.com/en/platform/corda/4.8/open-source/contributing.html) now and add a comment to this pull request stating that your PR is in accordance with the [Developer's Certificate of Origin](https://docs.r3.com/en/platform/corda/4.8/open-source/contributing.html#merging-the-changes-back-into-corda).

Thanks for your code, it's appreciated! :)

2023-09-15 09:00 UTC, shamsasari commented
Can you target the 4.12 branch

2023-10-10 16:26 UTC, shamsasari requested changes
A couple of things:

- The description incorrectly mentions Kotlin 1.9.
- Are all the ignored tests tracked in JIRA somewhere? We don't want any miss any accidently when trying to enable them.
- There's now no need to do any Java 11 checks. You should probably search for usages of `SystemUtils` to find them all.
- Is there a reason you're still calling `uncheckedCast` even though it doesn't work?
- There's also quite a few files which have been cleaned up (e.g. empty line at EOF) but otherwise have no changes related to this upgrade. You may want to revert all of them to reduce the size of this PR.
- Make the `core` dependency in `node-api` an `api` one. That will also remove the need to define `core` when you already have `node-api`.

2023-10-10 16:26 UTC, shamsasari commented on .ci/dev/nightly-regression/Jenkinsfile
> +        JAVA_HOME = "/usr/lib/jvm/java-17-amazon-corretto"
Does this need to be an environment variable? Perhaps @ronanbrowne or someone from the build team can opine?

2023-10-10 16:26 UTC, shamsasari commented on .ci/dev/pr-code-checks/Jenkinsfile
> +                 * TODO JDK17: Re-enable warnings as errors
Can you create a JIRA ticket to track this and reference the ticket here as well.

2023-10-10 16:26 UTC, shamsasari commented on build.gradle
> +//        classpath "org.jetbrains.kotlin:kotlin-noarg:$kotlin_version"
I presume you will address this as this PR is currently draft

2023-10-10 16:26 UTC, shamsasari commented on build.gradle
> +    ext.versionSuffix = "202309-01"
This needs reverting?

2023-10-10 16:26 UTC, shamsasari commented on build.gradle
> +targetCompatibility = VERSION_11
Is this needed if it's already defined in the `allprojects` block below?

2023-10-10 16:26 UTC, shamsasari commented on build.gradle
> +//            ex.append = false
Delete if not needed

2023-10-10 16:26 UTC, shamsasari commented on client/jackson/build.gradle
> +    implementation project(':core')
This should be `api` configuration, since this module relies on classes from `core` in its public API. https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_recognizing_dependencies

2023-10-10 16:26 UTC, shamsasari commented on client/jackson/build.gradle
>          exclude module: "jackson-databind"
Technically `jackson-databind` should also be an `api` dependency as well. But not sure why we're excluding it here. So probably best to leave as is, unless you know why.

2023-10-10 16:26 UTC, shamsasari commented on client/jackson/build.gradle
> +
You can remove the duplication by adding this block in the `allprojects` block in the root build.gradle.

2023-10-10 16:26 UTC, shamsasari commented on client/jackson/src/test/kotlin/net/corda/client/jackson/JacksonSupportTest.kt
> +    @Ignore("TODO JDK17: Fixme")
Are we tracking all the ignored tests somewhere?

2023-10-10 16:26 UTC, shamsasari commented on client/jfx/build.gradle
> +    version = "11.0.2"
Do we know that this version works with Java 17? 

In fact, do we even need this module? Seems like its a hangover from the Bank of Corda demo of eons ago. @rick-r3?

2023-10-10 16:26 UTC, shamsasari commented on client/rpc/build.gradle
> +    implementation project(':node-api')
Define `core` as an `api` dependency in `node-api` (since it exposes `core` classes in its public API), and remove the `core` declaration here.

2023-10-10 16:26 UTC, shamsasari commented on build.gradle
> +            '--add-opens', 'java.base/java.util.concurrent=ALL-UNNAMED', '--add-opens', 'java.sql/java.sql=ALL-UNNAMED'
Minor point, but can you have each `add-opens` on its own line, so that it's clear to see all the modules

2023-10-10 16:26 UTC, shamsasari commented on core-tests/build.gradle
> +    }
Shouldn't this be defined inside `allprojects` in the root build.gradle?

2023-10-10 16:26 UTC, shamsasari commented on core-tests/src/test/kotlin/net/corda/coretests/node/VaultUpdateTests.kt
> +        val emptyUpdate = Vault.Update(emptySet<StateAndRef<*>>(), emptySet(), type = Vault.UpdateType.GENERAL, references = emptySet())
Interesting that the Kotlin compiler has regressed in its type inference!

2023-10-10 16:26 UTC, shamsasari commented on core/src/main/kotlin/net/corda/core/concurrent/ConcurrencyUtils.kt
> +fun <V, W> firstOf(futures: Array<out CordaFuture<out V>>, log: Logger, handler: (CordaFuture<out V>) -> W): CordaFuture<W> {
It's clear from the original intention that these two were meant to be internal and not part of the public API. However, the use of `internal` didn't achieve that, and we have these two in the API. These two aren't actually used, so I'm of the opinion that we should remove them. WDYT @rick-r3?

... or you revert these two back and we ignore this discussion...

2023-10-10 16:26 UTC, shamsasari commented on core/src/main/kotlin/net/corda/core/flows/LedgerRecoverFlow.kt
You seem to have pulled in some ledger recovery changes. Best to revert these changes.

2023-10-10 16:26 UTC, shamsasari commented on core/src/main/kotlin/net/corda/core/internal/ClassLoadingUtils.kt
> +            }
What's going on here? The Java version will always be at least 11 since the compile target is now 17.

2023-10-10 16:26 UTC, shamsasari commented on core/src/main/kotlin/net/corda/core/internal/InternalUtils.kt
> +                // uncheckedCast(it.get(null))
This TODO is probably not worth having. The cast is simple enough.

2023-10-10 16:26 UTC, shamsasari commented on core/src/main/kotlin/net/corda/core/internal/concurrent/CordaFutureImpl.kt
> +class CordaFutureImpl<V>(private val impl: CompletableFuture<V> = CompletableFuture()) : Future<V> by impl, OpenFuture<V> {
Do we need to have the `internal` removed? If only to reduce the size of this PR.

2023-10-10 16:26 UTC, shamsasari commented on core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
> +    fun toWireTransactionWithContext(
Please revert this, and the one below. You are introducing internal code to the public API.

2023-10-10 16:26 UTC, shamsasari commented on core/src/main/kotlin/net/corda/core/utilities/KotlinUtils.kt
> +fun interface SerializableLambda2<S, T, R> : (S, T) -> R, Serializable
Can you move this into InternalUtils.kt as `KotlinUtils` is part of the public API.

2023-10-10 16:26 UTC, shamsasari commented on core/src/main/kotlin/net/corda/core/utilities/Try.kt
> +
Revert empty line

2023-10-10 16:26 UTC, shamsasari commented on core/src/test/kotlin/net/corda/core/internal/InternalUtilsTest.kt
> +        val a: Array<String> = Stream.of("one", "two").toTypedArray() as Array<String>
The cast should not be necessary. What's going on?

2023-10-10 16:26 UTC, shamsasari commented on experimental/corda-utils/build.gradle
> +    implementation project(':core')
See previous comment

2023-10-10 16:26 UTC, shamsasari commented on experimental/netparams/build.gradle
> +    implementation project(':core')
ditto

2023-10-10 16:26 UTC, shamsasari commented on finance/contracts/build.gradle
> +    cordaProvided project(':core')
Will users need to replace `cordaCompile` with this in their CorDapps?

2023-10-10 16:26 UTC, shamsasari commented on gradle.properties
> +json_api_version=1.1.4
Do these need to be defined here, and not in constants.properties?

2023-10-10 16:26 UTC, shamsasari commented on node-api/build.gradle
> +    implementation project(":core")
This should be `api`

2023-10-10 16:26 UTC, shamsasari commented on node-api/build.gradle
> +    implementation "org.apache.activemq:artemis-commons:${artemis_version}"
Also this, as `SimpleString` is exposed in this module

2023-10-10 16:26 UTC, shamsasari commented on node-api/build.gradle
> +    implementation "io.reactivex:rxjava:$rxjava_version"
And this as well

2023-10-10 16:26 UTC, shamsasari commented on node-api/build.gradle
> +    implementation "io.reactivex:rxjava:$rxjava_version"
This is duplicated, along with some others as well

2023-10-10 16:26 UTC, shamsasari commented on node-api/build.gradle
> +    api "javax.persistence:javax.persistence-api:2.2"
This isn't exposed in this module I don't think

2023-10-10 16:26 UTC, shamsasari commented on node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/kryo/DefaultKryoCustomizer.kt
> +            //fieldSerializerConfig.cachedFieldNameStrategy = FieldSerializer.CachedFieldNameStrategy.EXTENDED
Delete?

2023-10-10 16:26 UTC, shamsasari commented on node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/kryo/Kryo.kt
> +    private val delegate: Serializer<Throwable> = uncheckedCast(SerializerFactory.ReflectionSerializerFactory.newSerializer(kryo, FieldSerializer::class.java, type)) as Serializer<Throwable>
`uncheckedCast` isn't needed, no?

2023-10-10 16:26 UTC, shamsasari commented on node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/kryo/KryoTests.kt
> +        if (SystemUtils.isJavaVersionAtLeast(JavaVersion.JAVA_11))
Likewise, the Java version will be at least 17 now

2023-10-10 16:26 UTC, shamsasari commented on node/capsule/build.gradle
> +    implementation "com.typesafe:config:$typesafe_config_version"
Did this need to change? It was `compileOnly`, which still exists.

2023-10-10 16:26 UTC, shamsasari commented on node/capsule/build.gradle
> +    // We only need this dependency to implementation our Caplet against.
Is this change to the comment correct, since the `capsule` dependency below is still `compileOnly`?

2023-10-10 16:26 UTC, shamsasari commented on node/capsule/src/main/java/CordaCaplet.java
> +                "--add-opens=java.base/java.security.cert=ALL-UNNAMED",
This is inside a `isAtLeastJavaVersion11()` condition, which shouldn't be needed now

2023-10-10 16:26 UTC, shamsasari commented on node/src/integration-test/kotlin/net/corda/node/NodeRPCTests.kt
> +    private val CLASSIFIER = ""
You can just delete this

2023-10-10 16:26 UTC, shamsasari commented on node/src/integration-test/kotlin/net/corda/node/flows/FlowEntityManagerTest.kt
> +        Assume.assumeTrue(!SystemUtils.isJavaVersionAtLeast(JavaVersion.JAVA_11))
This entire assumption can now be removed

2023-10-10 16:26 UTC, shamsasari commented on node/src/main/kotlin/net/corda/node/internal/DataSourceFactory.kt
>          LoggerFactory.getLogger(javaClass).debug("Applying H2 fix.") // See CORDA-924.
You can remove this entire `init` block

2023-10-10 16:26 UTC, shamsasari commented on node/src/main/kotlin/net/corda/node/services/persistence/AbstractPartyDescriptor.kt
> +                return uncheckedCast(toString(value)) as X?
Ditto, `uncheckedCast` shouldn't be needed now

2023-10-10 16:26 UTC, shamsasari commented on node/src/main/kotlin/net/corda/node/services/statemachine/SingleThreadedStateMachineManager.kt
> +            is FlowState.Paused -> { /* AXM TODO */ }
I would leave this as an empty block. Otherwise you're implying there's something to fix here.

2023-10-10 16:26 UTC, shamsasari commented on node/src/test/kotlin/net/corda/node/internal/NodeTest.kt
> +        assertTrue(SystemUtils.IS_JAVA_1_8 || SystemUtils.isJavaVersionAtLeast(JavaVersion.JAVA_11))
We can get rid of this test!

2023-10-10 16:26 UTC, shamsasari commented on node/src/test/kotlin/net/corda/node/internal/cordapp/JarScanningCordappLoaderTest.kt
> -        val jar = JarScanningCordappLoaderTest::class.java.getResource("/workflowClassAtVersion55.jar")!!
We can delete these two jars as well.

2023-10-10 16:26 UTC, shamsasari commented on node/src/test/kotlin/net/corda/node/migration/IdentityServiceToStringShortMigrationTest.kt
> +            assertThat(groupedByNameIdentities[it]?.size!!, greaterThan(1))
No point having the`?` if doing `!!` as well

2023-10-10 16:26 UTC, shamsasari commented on node/src/test/kotlin/net/corda/node/services/vault/VaultQueryJoinTest.kt
> +            Assume.assumeTrue(!SystemUtils.isJavaVersionAtLeast(JavaVersion.JAVA_11))
This needs to become another ignored test, which we try to fix along with the others. Otherwise, this will never run.

2023-10-10 16:26 UTC, shamsasari commented on opentelemetry/build.gradle
> +//    id 'corda.common-publishing'
delete?

2023-10-10 16:26 UTC, shamsasari commented on samples/cordapp-configuration/build.gradle
> +    targetPlatformVersion corda_platform_version.toInteger()
@adelel1 @rick-r3 We need to update the 4.12 Gradle plugin to default the CorDapp's target platform version to 4.12.

2023-10-10 16:26 UTC, shamsasari commented on samples/cordapp-configuration/src/main/resources/log4j2.xml
> +        <Property name="log_path">build/logs</Property>
Whilst this rename is nice, it's one more file that's changed in a large PR

2023-10-10 16:26 UTC, shamsasari commented on samples/cordapp-configuration/build.gradle
> +    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
Is this also something all CorDapps will now need to do? If so then this is also something the Corda plugin should do for the user.

2023-10-10 16:26 UTC, shamsasari commented on samples/irs-demo/web/build.gradle
> +//    realBower {
I presume it's not working, and it's not straightforward to fix? @rick-r3 is it still worth keeping the IRS demo after all these years?

2023-10-10 16:26 UTC, shamsasari commented on samples/simm-valuation-demo/contracts-states/build.gradle
> +//    shrinkArtifacts file: sign.outputJars.singleFile, name: project.name, type: 'jar', extension: 'jar', classifier: 'tiny', builtBy: sign
delete?

2023-10-10 16:26 UTC, shamsasari commented on samples/simm-valuation-demo/src/integration-test/kotlin/net/corda/vega/SimmValuationTest.kt
> +    @Ignore("TODO JDK17: Fixme - Stage 2")
@adelel1 is it worth fixing the SIMM valuation demo now?

2023-10-10 16:26 UTC, shamsasari commented on settings.gradle
> +//include 'tools:demobench'
What's the issue with demobench?

2023-10-10 16:26 UTC, shamsasari commented on tools/explorer/src/main/kotlin/net/corda/explorer/views/cordapps/cash/NewTransaction.kt
> +        val notariesNotNullBinding = Bindings.createBooleanBinding({ notaries.isNotEmpty() }, *arrayOf(notaries))
Isn't just passing in `notaries` on its own sufficient?

2023-10-10 16:26 UTC, shamsasari commented on tools/explorer/src/main/kotlin/net/corda/explorer/views/cordapps/cash/NewTransaction.kt
> +                }, *arrayOf(currencyChoiceBox.valueProperty(), issuerChoiceBox.valueProperty())))
likewise, you can pass in the two boxes directly.

2023-10-10 16:26 UTC, shamsasari commented on tools/explorer/src/main/kotlin/net/corda/explorer/views/Settings.kt
> +//                .map { if (!it) FontAwesomeIconView(FontAwesomeIcon.TIMES) else FontAwesomeIconView(FontAwesomeIcon.EDIT) })
Why is this commented out? There is a `map` extension function.

2023-10-10 16:26 UTC, shamsasari commented on tools/explorer/src/main/kotlin/net/corda/explorer/views/SearchField.kt
> +    }, *arrayOf<Observable>(textField.textProperty(), searchCategory.valueProperty())), "filteredData")
ditto

2023-10-10 16:26 UTC, shamsasari commented on tools/explorer/src/main/kotlin/net/corda/explorer/views/Network.kt
> +            }, *arrayOf(mapPane.widthProperty(), mapPane.heightProperty()))
ditto

2023-10-10 16:26 UTC, shamsasari commented on testing/node-driver/src/integration-test/kotlin/net/corda/testing/node/MockNetworkIntegrationTests.kt
> +        )
I think you need add these open modules to `startJavaProcess` to remove the duplication

2023-10-11 09:29 UTC, shamsasari commented
Also, G1 is now the default GC in Java 17, so the `-XX:+UseG1GC` VM flag can be removed from the codebase.

2023-10-16 10:20 UTC, shamsasari commented on build.gradle
> +targetCompatibility = VERSION_11
This should be 17

2023-10-16 10:20 UTC, shamsasari commented on build.gradle
> +    targetCompatibility = VERSION_11
likewise

2023-10-16 10:21 UTC, shamsasari commented on build.gradle
> +            jvmTarget = VERSION_11
likewise

2023-10-17 13:40 UTC, arshadm commented on .ci/dev/nightly-regression/Jenkinsfile
> +        JAVA_HOME = "/usr/lib/jvm/java-17-amazon-corretto"
Yes, it does. The node has a couple of versions of Java installed and this is the way you select which one to use.

2023-10-17 13:43 UTC, arshadm commented on .ci/dev/pr-code-checks/Jenkinsfile
> +                 * TODO JDK17: Re-enable warnings as errors
Created 2 JIRA tickets one for OS and one for Ent 
https://r3-cev.atlassian.net/browse/ENT-10343
https://r3-cev.atlassian.net/browse/ENT-10344

2023-10-17 13:46 UTC, arshadm commented on build.gradle
> +//        classpath "org.jetbrains.kotlin:kotlin-noarg:$kotlin_version"
yes, done.

2023-10-17 13:49 UTC, arshadm commented on build.gradle
> +targetCompatibility = VERSION_11
Good question. This already exists in the 4.11 branch, not newly added.

2023-10-17 13:50 UTC, arshadm commented on tools/explorer/src/main/kotlin/net/corda/explorer/views/cordapps/cash/NewTransaction.kt
> +                }, *arrayOf(currencyChoiceBox.valueProperty(), issuerChoiceBox.valueProperty())))
Trying to avoid making too many changes. I was going to create a post merge ticket for cleanup and fixing of warnings, etc. But can do so if you think it's worth doing now.

2023-10-17 13:54 UTC, arshadm commented on tools/explorer/src/main/kotlin/net/corda/explorer/views/Settings.kt
> +//                .map { if (!it) FontAwesomeIconView(FontAwesomeIcon.TIMES) else FontAwesomeIconView(FontAwesomeIcon.EDIT) })
Kotlin 1.9 doesn't like it, and there wasn't an easy fix. I suspect it's a combination of the version of JavaFX in JDK17 and how we use map. 

Created JIRA ticket: https://r3-cev.atlassian.net/browse/ENT-10984

2023-10-17 13:55 UTC, arshadm commented on tools/explorer/src/main/kotlin/net/corda/explorer/views/SearchField.kt
> +    }, *arrayOf<Observable>(textField.textProperty(), searchCategory.valueProperty())), "filteredData")
Code changes not essential to be done later.

2023-10-17 13:55 UTC, arshadm commented on tools/explorer/src/main/kotlin/net/corda/explorer/views/Network.kt
> +            }, *arrayOf(mapPane.widthProperty(), mapPane.heightProperty()))
Code changes not essential to be done later.

2023-10-17 13:57 UTC, arshadm commented on testing/node-driver/src/integration-test/kotlin/net/corda/testing/node/MockNetworkIntegrationTests.kt
> +        )
Can do, but this is more flexible as startJavaProcess just takes the jvmArgs. Also allows us to customise what modules we open rather than a fixed set.

2023-10-17 14:01 UTC, arshadm commented on build.gradle
> +targetCompatibility = VERSION_11
This needs investigation/testing. When we began the JDK17 upgrade, Chris Rankin suggested we stick with JDK11 bytecode because quasar didn't support JDK17 bytecode. 

I suggest we stick with JDK11 for the moment, and upgrade to JDK21 once we have that working.

2023-10-17 14:02 UTC, arshadm commented on build.gradle
> +    targetCompatibility = VERSION_11
As above comment re quasar.

2023-10-17 14:02 UTC, arshadm commented on build.gradle
> +            jvmTarget = VERSION_11
As above comment re quasar.

2023-10-17 14:03 UTC, arshadm commented on build.gradle
> +//        classpath "org.jetbrains.kotlin:kotlin-noarg:$kotlin_version"
Done.

2023-10-17 14:04 UTC, arshadm commented on build.gradle
> +    ext.versionSuffix = "202309-01"
Yes, when we merge to the main 4.12 branch. At the moment it's handy to be able to give Jakub a defined version for QA (the underlying issue is that his tests need Corda OS, Corda Ent and Corda Shell to be the same version and using a git id in the version means it can't be the same).

2023-10-18 10:25 UTC, adelel1 commented on .ci/dev/pr-code-checks/Jenkinsfile
> +        JAVA_HOME = "/usr/lib/jvm/java-17-amazon-corretto"
Should we be using Java 17 zulu?

2023-10-18 10:29 UTC, adelel1 commented on build.gradle
>  import static org.gradle.api.JavaVersion.VERSION_11
Should now be VERSION_17?

2023-10-18 10:40 UTC, adelel1 commented on build.gradle
> +//    executionData = files(subprojects.jacocoTestReport.executionData)
Remove, if not needed.

2023-10-18 11:38 UTC, adelel1 commented on core-tests/src/test/kotlin/net/corda/coretests/flows/FlowExternalOperationTest.kt
> +            val x = { 10 }
Not clear to me why this line is here?

2023-10-18 11:58 UTC, adelel1 commented on core/src/main/kotlin/net/corda/core/crypto/CordaSecurityProvider.kt
> +        super.getService("UNDEFINED", "UNDEFINED")
Can you raise a Jira for this, and update Jira with explanation. Would need to fix/get to the bottom of this.

2023-10-18 15:24 UTC, adelel1 commented on core/src/main/kotlin/net/corda/core/crypto/internal/ProviderMap.kt
> +    val sunEC = Security.getProvider("SunEC")
Can you raise Jira on this.Is BC algo's still needed?

2023-10-18 15:31 UTC, adelel1 commented on core/src/main/kotlin/net/corda/core/internal/concurrent/CordaFutureImpl.kt
> +    fun <W> thenImpl(log: Logger, callback: (CordaFuture<V>) -> W) {
Whats the reason internal was removed? Can it be reverted. Same qu for other "internal" throughout document

2023-10-18 15:32 UTC, adelel1 commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
> +import net.corda.core.internal.JDK11_CLASS_FILE_FORMAT_MAJOR_VERSION
Which version do we want to support?

2023-10-18 15:40 UTC, adelel1 commented on detekt-baseline.xml
> +    <ID>TopLevelPropertyNaming:ConcurrencyUtils.kt$@VisibleForTesting const val shortCircuitedTaskFailedMessage = "Short-circuited task failed:"</ID>
Why do you need this here?

2023-10-18 16:13 UTC, adelel1 commented on docker/src/docker/DockerfileAL
> +    JVM_ARGS="-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap " \
Why is G1GC removed?

2023-10-18 16:15 UTC, adelel1 commented on experimental/nodeinfo/build.gradle
> +    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
Can't this be a top level default strategy.

2023-10-18 16:37 UTC, adelel1 commented on node-api/src/main/kotlin/net/corda/nodeapi/internal/bridging/AMQPBridgeManager.kt
> +            val runnable = @DontInstrument {
Why not instrument?

2023-10-18 16:52 UTC, adelel1 commented on node/src/integration-test/kotlin/net/corda/node/services/statemachine/FlowHospitalTest.kt
>              }
No change in this file?

2023-10-18 17:03 UTC, adelel1 commented on node/src/test/kotlin/net/corda/notary/experimental/raft/RaftTransactionCommitLogTests.kt
> +}
No change?

2023-10-19 11:59 UTC, adelel1 commented on opentelemetry/opentelemetry-driver/build.gradle
> +        shadow(MavenPublication) { publication ->
Did the shadow here due to okhttp usage in open telemetry core clashed with our usage. Should not be necessary anymore.

2023-10-19 12:08 UTC, adelel1 commented on samples/cordapp-configuration/build.gradle
> +    targetPlatformVersion corda_platform_version.toInteger()
ENT-10995

2023-10-19 12:20 UTC, adelel1 commented on samples/simm-valuation-demo/src/integration-test/kotlin/net/corda/vega/SimmValuationTest.kt
> +    @Ignore("TODO JDK17: Fixme - Stage 2")
I think its worth investigating what the issue is. i.e. Is this something customer cordapps may hit. If the issue is some specific problem with the demo or its dependencies we can then see if we want to fix.

2023-10-19 12:29 UTC, adelel1 commented on testing/node-driver/build.gradle
> +//tasks.named('javadocJar', Jar) {
delete?

2023-10-19 16:24 UTC, adelel1 commented on testing/test-utils/src/main/kotlin/net/corda/testing/internal/FlowStackSnapshot.kt
> +        private const val QUASAR_0_8_INSTRUMENTED_CLASS_NAME = "co.paralleluniverse.fibers.suspend.Instrumented"
I presume quasar 9 uses same classname as quasar 8. Maybe a diff name, 8+ ?

2023-10-19 16:44 UTC, adelel1 commented on tools/explorer/src/main/kotlin/net/corda/explorer/views/Network.kt
> +            }, *arrayOf(mapPane.widthProperty(), mapPane.heightProperty()))
Needs a TODO JDK17 or Jira

2023-10-19 16:48 UTC, adelel1 commented on tools/explorer/src/main/kotlin/net/corda/explorer/views/cordapps/cash/NewTransaction.kt
> +                }, *arrayOf(currencyChoiceBox.valueProperty(), issuerChoiceBox.valueProperty())))
or raise Jira

2023-10-20 10:52 UTC, arshadm commented on tools/explorer/src/main/kotlin/net/corda/explorer/views/cordapps/cash/NewTransaction.kt
> +                }, *arrayOf(currencyChoiceBox.valueProperty(), issuerChoiceBox.valueProperty())))
Creates JIRA ticket - https://r3-cev.atlassian.net/browse/ENT-10997

2023-10-20 10:54 UTC, arshadm commented on .ci/dev/pr-code-checks/Jenkinsfile
> +        JAVA_HOME = "/usr/lib/jvm/java-17-amazon-corretto"
The build team only support Corretto (we also used Corretto for JDK8 builds on Jenkins too). Not sure about a constant can ask @ronanbrowne

2023-10-20 10:55 UTC, arshadm commented on build.gradle
>  import static org.gradle.api.JavaVersion.VERSION_11
The build for 4.12-HC01 is still JVM 11 because of quasar. I don't believe Kotlin supports anything above that at the moment anyway.

2023-10-20 10:56 UTC, arshadm commented on build.gradle
> +//    executionData = files(subprojects.jacocoTestReport.executionData)
We need proper code coverage support have raised this ticker for that - https://r3-cev.atlassian.net/browse/ENT-10372

2023-10-20 10:57 UTC, arshadm commented on core-tests/src/test/kotlin/net/corda/coretests/flows/FlowExternalOperationTest.kt
> +            val x = { 10 }
Removed.  Was debugging some issues with Kotlin lambdas.

2023-10-20 10:59 UTC, arshadm commented on core/src/main/kotlin/net/corda/core/crypto/CordaSecurityProvider.kt
> +        super.getService("UNDEFINED", "UNDEFINED")
Raised JIRA - https://r3-cev.atlassian.net/browse/ENT-10998

2023-10-20 11:02 UTC, arshadm commented on core/src/main/kotlin/net/corda/core/crypto/internal/ProviderMap.kt
> +    val sunEC = Security.getProvider("SunEC")
https://r3-cev.atlassian.net/browse/ENT-11101

2023-10-20 11:03 UTC, arshadm commented on core/src/main/kotlin/net/corda/core/internal/concurrent/CordaFutureImpl.kt
> +    fun <W> thenImpl(log: Logger, callback: (CordaFuture<V>) -> W) {
These function are used from Corda Ent core test code, Kotlin 1.2 seemed ok to allow usage so long as the package name was same. Kotlin 1.8/1.9 doesn't allow this across Jars.

2023-10-20 11:05 UTC, arshadm commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
> +import net.corda.core.internal.JDK11_CLASS_FILE_FORMAT_MAJOR_VERSION
Right now the tested version of quasar support JDK 11. I believe Corda 5 support JDK 17 bytecode so I think we might be safe to upgrade but needs testing. I think we should do this work as part of upgrading to JDK 21.

2023-10-20 11:06 UTC, arshadm commented on detekt-baseline.xml
> +    <ID>TopLevelPropertyNaming:ConcurrencyUtils.kt$@VisibleForTesting const val shortCircuitedTaskFailedMessage = "Short-circuited task failed:"</ID>
detekt warning, normally we add these to bypass them if we're not going to fix.

2023-10-20 11:07 UTC, arshadm commented on experimental/nodeinfo/build.gradle
> +    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
Possibly, but it only seems to be needed in a few places. Probably we need to investigate why it's needed at all, but not sure if it's worth the effort.

2023-10-20 11:08 UTC, arshadm commented on node-api/src/main/kotlin/net/corda/nodeapi/internal/bridging/AMQPBridgeManager.kt
> +            val runnable = @DontInstrument {
Uses raw locking/waiting not supported by quasar. Chris Rankin suggested this as the fix.

2023-10-20 11:09 UTC, arshadm commented on node/src/test/kotlin/net/corda/notary/experimental/raft/RaftTransactionCommitLogTests.kt
> +}
Undone

2023-10-20 11:12 UTC, arshadm commented on testing/node-driver/build.gradle
> +//tasks.named('javadocJar', Jar) {
done

2023-10-20 11:15 UTC, arshadm commented on testing/test-utils/src/main/kotlin/net/corda/testing/internal/FlowStackSnapshot.kt
> +        private const val QUASAR_0_8_INSTRUMENTED_CLASS_NAME = "co.paralleluniverse.fibers.suspend.Instrumented"
Yes, the class name changed. This code taken from corda 5 which Chris Rankin wrote. He did it so that it would compile with JDK 8/JDK 11/17. Given that we don't support JDK 8 anymore we can simplify this. Raised this JIRA to fix it - https://r3-cev.atlassian.net/browse/ENT-11000

2023-10-20 13:20 UTC, adelel1 submitted a review, later dismissed
Approving for merge in on following basis:
For significant issues a Jira has been raised.
For all other comments, these will be reviewed and addressed. i..e will use this PR to review them.

2023-10-23 08:56 UTC, shamsasari commented on .ci/api-current.txt
@adelel1 @rick-r3 Do we need to a JIRA to look into the API file changes. The removal of the type parameters could lead to us missing API changes. Arshad said it was due to a change in ClassGraph.

2023-10-23 08:58 UTC, shamsasari commented on build.gradle
> +targetCompatibility = VERSION_11
Is there a JIRA for this?

2023-10-23 08:59 UTC, shamsasari commented on build.gradle
> +    ext.versionSuffix = "202309-01"
Can you revert this in preparation for merging.

2023-10-23 09:00 UTC, rick-r3 reviewed
First set of comments.  Got to 111 files of 349.

2023-10-23 09:00 UTC, rick-r3 commented on Jenkinsfile
> +        JAVA_HOME="/usr/lib/jvm/java-17-amazon-corretto"
I wonder if there is a way for all the places we set this to use a common include file or something?  If we change the JVM in the future (e.g. Java 21) there's a lot of updating to do.  File a JIRA to look into it?

2023-10-23 09:00 UTC, rick-r3 commented on build.gradle
>  import static org.gradle.api.JavaVersion.VERSION_11
Quasar 0.7.x is J8, 0.8.x is J11 and 0.9.x is J17.  Since we are using 0.9, we should be good with J17.

2023-10-23 09:00 UTC, rick-r3 commented on build.gradle
> +            '--add-opens', 'java.base/java.util.concurrent=ALL-UNNAMED', '--add-opens', 'java.sql/java.sql=ALL-UNNAMED'
Are we going to need all these `add-opens` when running the command line tools?  If so, we probably need wrapper scripts for all of them - or a wrapper script that can be given a jar filename and then does the right JVM options.  i.e. anything that doesn't use Capsule.

2023-10-23 09:00 UTC, rick-r3 commented on build.gradle
> +targetCompatibility = VERSION_11
Upgrade to J17 ?

2023-10-23 09:00 UTC, rick-r3 commented on client/jackson/build.gradle
>          exclude module: "jackson-databind"
The original exclusion I presume was because we had split the Kotlin Jackson module version to be distinct from the rest of Jackson.  This was because we had to keep the Kotlin helpers version frozen and aligned with our version of Kotlin, whilst upgrading the reset of Jackson to fix reported vulnerabilities.  Whilst we can presumably temporarily align them (perhaps), I would expect a similar issue to happen again when the Jackson folks upgrade the version of kotlin they depend on in patch releases (unless they go more disciplined).  So I assume we should keep this, if the "rest of Jackson" that the Kotlin helpers depend on is just "jackson-databind".

2023-10-23 09:00 UTC, rick-r3 commented on client/jackson/src/test/kotlin/net/corda/client/jackson/JacksonSupportTest.kt
> +    @Ignore("TODO JDK17: Fixme")
If we have a common format like this that would be useful to help track them down.

2023-10-23 09:00 UTC, rick-r3 commented on client/jfx/build.gradle
> +    version = "11.0.2"
There might be an opportunity here.  I don't recall what demos we do or don't have any more.  Do we have something that depends on this?

(If we do, we _could_ make a decision to delete it - or save unlink and revisit).

2023-10-23 09:00 UTC, rick-r3 commented on constants.properties
>  jacksonVersion=2.13.5
We will probably want to come back and have another pass at refreshing these dependencies.  A lot of this stuff is held back for compatibility and it is likely an opportunity to bring more of it up-to-date

2023-10-23 09:00 UTC, rick-r3 commented on core-tests/src/test/kotlin/net/corda/coretests/flows/AbstractFlowExternalOperationTest.kt
> +                Strand.sleep(1000)
Why did this need changing?  Hard for me to tell if this is significant or not.

2023-10-23 09:00 UTC, rick-r3 commented on core-tests/src/test/kotlin/net/corda/coretests/flows/CollectSignaturesFlowTests.kt
> +@Ignore("TODO JDK17: class cast exception")
There are quite a lot of tests with class cast exception it seems.  Do we have a stack trace for it?  I'm wondering how much of a concern it is.

2023-10-23 09:00 UTC, rick-r3 commented on core-tests/src/test/kotlin/net/corda/coretests/flows/ContractUpgradeFlowTest.kt
> +@Ignore("TODO JDK17: class cart exception")
cart -> cast

2023-10-23 09:00 UTC, rick-r3 commented on core-tests/src/test/kotlin/net/corda/coretests/flows/FinalityFlowTests.kt
> +@Ignore("TODO JDK17: class cart exception")
cart -> cast

2023-10-23 09:00 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/concurrent/ConcurrencyUtils.kt
> +fun <V, W> firstOf(futures: Array<out CordaFuture<out V>>, log: Logger, handler: (CordaFuture<out V>) -> W): CordaFuture<W> {
If they are not used, remove.


@adelel1 JIRA

https://r3-cev.atlassian.net/browse/ENT-11111

2023-10-23 09:00 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/crypto/CordaSecurityProvider.kt
> +        super.getService("UNDEFINED", "UNDEFINED")
I think there is an argument (I hear) for getting rid of our implementations of secure random.  They were to bypass entropy supply issues in the cloud, but I have heard anecdotally that the JDK has fixed the issues.

2023-10-23 09:00 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/internal/InternalUtils.kt
> +                // uncheckedCast(it.get(null))
Ah... I wonder if that is the cause of other class cast exceptions?  i.e. wrong inferred type in `uncheckedCast()`.  I guess you probably know from the stack traces of other broken tests.

2023-10-23 09:00 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/internal/concurrent/CordaFutureImpl.kt
> +    fun <W> thenImpl(log: Logger, callback: (CordaFuture<V>) -> W) {
Got it.

In this case we are in an `internal` package so the intent that this is internal is maintained.

2023-10-23 09:00 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
> +import net.corda.core.internal.JDK11_CLASS_FILE_FORMAT_MAJOR_VERSION
The Quasar version is okay with J17.  J21 is another matter....

2023-10-23 09:00 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
> +    fun toWireTransactionWithContext(
Are we doing this because it is accessed across JARs as mentioned elsewhere?  

We should retain the `CordaInternal` annotation on these at the very least.  Need to have a thing about if there is another solution.

https://r3-cev.atlassian.net/browse/ENT-11070

2023-10-23 09:00 UTC, rick-r3 commented on core/src/main/kotlin/net/corda/core/utilities/KotlinUtils.kt
> +fun interface SerializableLambda2<S, T, R> : (S, T) -> R, Serializable
I think I saw this being used when calling public API (`await`)?  Which would mean we need it on the API.

2023-10-23 09:04 UTC, shamsasari commented on core/src/main/kotlin/net/corda/core/concurrent/ConcurrencyUtils.kt
> +fun <V, W> firstOf(futures: Array<out CordaFuture<out V>>, log: Logger, handler: (CordaFuture<out V>) -> W): CordaFuture<W> {
Please revert or delete

2023-10-23 09:07 UTC, shamsasari commented on core/src/main/kotlin/net/corda/core/internal/ClassLoadingUtils.kt
> +            }
Can you remove the Java 11 check.

2023-10-23 09:08 UTC, shamsasari commented on core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
> +    fun toWireTransactionWithContext(
Please revert or annotate with `@CordaInternal`

2023-10-23 09:09 UTC, shamsasari commented on core/src/main/kotlin/net/corda/core/utilities/KotlinUtils.kt
> +fun interface SerializableLambda2<S, T, R> : (S, T) -> R, Serializable
This needs to be moved.

2023-10-23 09:10 UTC, shamsasari commented on core/src/test/java/net/corda/core/internal/X509EdDSAEngineTest.java
> +    @Ignore
Can annotate this as the same as you've done with all the other ignored tests, so that we don't lose this when we do a search all in the code base.

2023-10-23 09:16 UTC, shamsasari commented on node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/kryo/DefaultKryoCustomizer.kt
> +            //fieldSerializerConfig.cachedFieldNameStrategy = FieldSerializer.CachedFieldNameStrategy.EXTENDED
Commented out code needs to be deleted or JIRAs created

2023-10-23 09:17 UTC, shamsasari commented on node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/kryo/KryoTests.kt
> +        if (SystemUtils.isJavaVersionAtLeast(JavaVersion.JAVA_11))
Remove if statement

2023-10-23 09:18 UTC, shamsasari commented on node/capsule/src/main/java/CordaCaplet.java
> +                "--add-opens=java.base/java.security.cert=ALL-UNNAMED",
Delete `isAtLeastJavaVersion11()` check

2023-10-23 09:22 UTC, shamsasari commented on node/src/main/kotlin/net/corda/node/internal/Node.kt
>                      val update = getJavaUpdateVersion(SystemUtils.JAVA_VERSION) // To filter out cases like 1.8.0_202-ea
This Java 8 check needs to go

2023-10-23 09:26 UTC, shamsasari commented on samples/irs-demo/web/build.gradle
> +//    realBower {
JIRA ticket

2023-10-23 09:28 UTC, shamsasari commented on settings.gradle
> +//include 'tools:demobench'
JIRA

2023-10-23 09:30 UTC, shamsasari commented on testing/node-driver/src/integration-test/kotlin/net/corda/testing/node/MockNetworkIntegrationTests.kt
> +        )
You should consider them as default values then, since the default classpath is the corda node one

2023-10-23 09:32 UTC, shamsasari commented on testing/test-utils/src/test/kotlin/net/corda/testing/core/JarSignatureCollectorTest.kt
> +        return if (SystemUtils.isJavaVersionAtLeast(JavaVersion.JAVA_11))
Delete check

2023-10-23 10:01 UTC, shamsasari commented on config/dev/log4j2.xml
> +        <Property name="console_log_level">${sys:consoleLogLevel:-error}</Property>
The properties defined by `sys:` are taking values from the sytem properties, which are set by the node before the logging is initialised. I suggest you just revert these changes.

2023-10-23 11:07 UTC, rick-r3 reviewed
Up to 187 of 349

2023-10-23 11:07 UTC, rick-r3 commented on finance/contracts/build.gradle
> +    cordaProvided project(':core')
Yeah, I think the new version of the gradle plugin - that already exists - has some (necessary) changes.

2023-10-23 11:07 UTC, rick-r3 commented on gradle.properties
> +json_api_version=1.1.4
Is that Kotlin version correct?  Thought we were 1.9 ?

@adelel1 Done (Updated to 1.9)

2023-10-23 15:22 UTC, rick-r3 reviewed
Got to the end!

2023-10-23 15:22 UTC, rick-r3 commented on node/src/main/kotlin/net/corda/node/services/statemachine/SingleThreadedStateMachineManager.kt
> +            is FlowState.Paused -> { /* AXM TODO */ }
Is the compiler forcing you do this?  I assume an unhandled `when` used to throw some kind of exception, so presume it would be okay to throw here.

2023-10-23 15:22 UTC, rick-r3 commented on samples/irs-demo/web/build.gradle
> +//    realBower {
Something makes me think we had already "unplugged" this from the top level project?  If so, maybe we delete it.

I think it is possible we could rationalise some of these demos that pull in a lot of dependencies we don't necessarily want to reduce the maintenance burden.

2023-11-01 09:30 UTC, arshadm commented on build.gradle
> +    ext.versionSuffix = "202309-01"
Done

2023-11-01 09:37 UTC, arshadm commented on testing/node-driver/src/integration-test/kotlin/net/corda/testing/node/MockNetworkIntegrationTests.kt
> +        )
Create a JIRA ticket to look into this - https://r3-cev.atlassian.net/browse/ENT-11065

2023-11-01 09:40 UTC, arshadm commented on build.gradle
> +targetCompatibility = VERSION_11
Create JIRA - https://r3-cev.atlassian.net/browse/ENT-11066

2023-11-01 09:43 UTC, arshadm commented on opentelemetry/opentelemetry-driver/build.gradle
> +        shadow(MavenPublication) { publication ->
The shadow plugin is used to build final artifact (see shadowJar definition in the build file)

2023-11-01 09:47 UTC, arshadm commented on Jenkinsfile
> +        JAVA_HOME="/usr/lib/jvm/java-17-amazon-corretto"
Raised this JIRA - https://r3-cev.atlassian.net/browse/ENT-11067

2023-11-01 09:51 UTC, arshadm commented on constants.properties
>  jacksonVersion=2.13.5
I upgraded to the latest when this change was done, but yes we can probably revisit before release because I believe it was the JDK 8 that was stopping us from upgrading.

2023-11-01 09:52 UTC, arshadm commented on core-tests/src/test/kotlin/net/corda/coretests/flows/AbstractFlowExternalOperationTest.kt
> +                Strand.sleep(1000)
Quasar 0.9.0 really doesn't like blocking code. The Strand is a wrapper that is intelligent enough to use Thread.sleep if we are on a native thread, and use a quasar friendly sleep if we are on a fiber.

2023-11-01 09:54 UTC, arshadm commented on core-tests/src/test/kotlin/net/corda/coretests/flows/ContractUpgradeFlowTest.kt
> +@Ignore("TODO JDK17: class cart exception")
fixed typo

2023-11-01 09:55 UTC, arshadm commented on core-tests/src/test/kotlin/net/corda/coretests/flows/FinalityFlowTests.kt
> +@Ignore("TODO JDK17: class cart exception")
fixed typo

2023-11-01 09:57 UTC, arshadm commented on build.gradle
>  import static org.gradle.api.JavaVersion.VERSION_11
This still needs testing. But yes, ideally we want to upgrade to JDK 21. We now have a JIRA ticket for this.

2023-11-01 10:00 UTC, arshadm commented on core-tests/src/test/kotlin/net/corda/coretests/flows/CollectSignaturesFlowTests.kt
> +@Ignore("TODO JDK17: class cast exception")
They are serious, and we need to remove all uses of uncheckCast(..), raised this JIRA for it - https://r3-cev.atlassian.net/browse/ENT-11069

2023-11-01 10:14 UTC, arshadm commented on node/src/main/kotlin/net/corda/node/internal/Node.kt
>                      val update = getJavaUpdateVersion(SystemUtils.JAVA_VERSION) // To filter out cases like 1.8.0_202-ea
Created this JIRA for it - https://r3-cev.atlassian.net/browse/ENT-11071

2023-11-01 10:16 UTC, arshadm commented on testing/test-utils/src/test/kotlin/net/corda/testing/core/JarSignatureCollectorTest.kt
> +        return if (SystemUtils.isJavaVersionAtLeast(JavaVersion.JAVA_11))
Done

2023-11-01 12:44 UTC, adelel1 commented on build.gradle
> +//            ex.append = false
TODO

2023-11-01 12:44 UTC, adelel1 commented on client/jackson/build.gradle
> +    implementation project(':core')
JIRA

2023-11-01 12:45 UTC, adelel1 commented on client/jackson/build.gradle
>          exclude module: "jackson-databind"
JIRA - But will probably leave this as is.

2023-11-01 12:45 UTC, adelel1 commented on client/jackson/build.gradle
> +
TODO

2023-11-01 12:46 UTC, adelel1 commented on client/jackson/src/test/kotlin/net/corda/client/jackson/JacksonSupportTest.kt
> +    @Ignore("TODO JDK17: Fixme")
Yes, this is the common format, JIRAs that start with TODO JDK17:

2023-11-01 12:46 UTC, adelel1 commented on client/jfx/build.gradle
> +    version = "11.0.2"
JIRA

2023-11-01 12:47 UTC, adelel1 commented on client/rpc/build.gradle
> +    implementation project(':node-api')
JIRA

2023-11-01 12:48 UTC, adelel1 commented on build.gradle
> +            '--add-opens', 'java.base/java.util.concurrent=ALL-UNNAMED', '--add-opens', 'java.sql/java.sql=ALL-UNNAMED'
JIRA update tools / anything standalone.

2023-11-01 12:49 UTC, adelel1 commented on core-tests/build.gradle
> +    }
JIRA

2023-11-01 12:49 UTC, adelel1 commented on core-tests/src/test/kotlin/net/corda/coretests/node/VaultUpdateTests.kt
> +        val emptyUpdate = Vault.Update(emptySet<StateAndRef<*>>(), emptySet(), type = Vault.UpdateType.GENERAL, references = emptySet())
JIRA

2023-11-01 12:50 UTC, adelel1 commented on core/src/main/kotlin/net/corda/core/concurrent/ConcurrencyUtils.kt
> +fun <V, W> firstOf(futures: Array<out CordaFuture<out V>>, log: Logger, handler: (CordaFuture<out V>) -> W): CordaFuture<W> {
TODO

2023-11-01 12:51 UTC, adelel1 commented on core/src/main/kotlin/net/corda/core/flows/LedgerRecoverFlow.kt
This is fine. 4.12 is keeping up to date with latest 4.11.

2023-11-01 12:59 UTC, adelel1 commented on core/src/main/kotlin/net/corda/core/internal/ClassLoadingUtils.kt
> +            }
JIRA

2023-11-01 12:59 UTC, adelel1 commented on core/src/main/kotlin/net/corda/core/internal/InternalUtils.kt
> +                // uncheckedCast(it.get(null))
JIRA

2023-11-01 13:00 UTC, adelel1 commented on core/src/main/kotlin/net/corda/core/internal/concurrent/CordaFutureImpl.kt
> +class CordaFutureImpl<V>(private val impl: CompletableFuture<V> = CompletableFuture()) : Future<V> by impl, OpenFuture<V> {
JIRA

2023-11-01 13:00 UTC, adelel1 commented on core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
> +    fun toWireTransactionWithContext(
JIRA

2023-11-01 13:01 UTC, adelel1 commented on core/src/main/kotlin/net/corda/core/utilities/KotlinUtils.kt
> +fun interface SerializableLambda2<S, T, R> : (S, T) -> R, Serializable
JIRA

2023-11-01 13:02 UTC, adelel1 commented on core/src/main/kotlin/net/corda/core/utilities/Try.kt
> +
TODO

2023-11-01 13:02 UTC, adelel1 commented on core/src/test/kotlin/net/corda/core/internal/InternalUtilsTest.kt
> +        val a: Array<String> = Stream.of("one", "two").toTypedArray() as Array<String>
JIRA

2023-11-01 13:03 UTC, adelel1 commented on experimental/corda-utils/build.gradle
> +    implementation project(':core')
JIRA

2023-11-01 13:04 UTC, adelel1 commented on experimental/netparams/build.gradle
> +    implementation project(':core')
JIRA

2023-11-01 13:05 UTC, adelel1 commented on finance/contracts/build.gradle
> +    cordaProvided project(':core')
Doc will say need to use gradle 5.1 with associated doc.

2023-11-01 13:06 UTC, adelel1 commented on node-api/build.gradle
> +    implementation project(":core")
JIRA

2023-11-01 13:07 UTC, adelel1 commented on node-api/build.gradle
> +    implementation "org.apache.activemq:artemis-commons:${artemis_version}"
JIRA

2023-11-01 13:07 UTC, adelel1 commented on node-api/build.gradle
> +    implementation "io.reactivex:rxjava:$rxjava_version"
JIRA

2023-11-01 13:08 UTC, adelel1 commented on node-api/build.gradle
> +    implementation "io.reactivex:rxjava:$rxjava_version"
TODO

2023-11-01 13:08 UTC, adelel1 commented on node-api/build.gradle
> +    api "javax.persistence:javax.persistence-api:2.2"
TODO

2023-11-01 13:09 UTC, adelel1 commented on node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/kryo/DefaultKryoCustomizer.kt
> +            //fieldSerializerConfig.cachedFieldNameStrategy = FieldSerializer.CachedFieldNameStrategy.EXTENDED
TODO

2023-11-01 13:09 UTC, adelel1 commented on node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/kryo/Kryo.kt
> +    private val delegate: Serializer<Throwable> = uncheckedCast(SerializerFactory.ReflectionSerializerFactory.newSerializer(kryo, FieldSerializer::class.java, type)) as Serializer<Throwable>
TODO

2023-11-01 13:10 UTC, adelel1 commented on node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/kryo/KryoTests.kt
> +        if (SystemUtils.isJavaVersionAtLeast(JavaVersion.JAVA_11))
JIRA

2023-11-01 13:11 UTC, adelel1 commented on node/capsule/build.gradle
> +    implementation "com.typesafe:config:$typesafe_config_version"
TODO

2023-11-01 13:12 UTC, adelel1 commented on node/capsule/build.gradle
> +    // We only need this dependency to implementation our Caplet against.
TODO

2023-11-01 13:12 UTC, adelel1 commented on node/capsule/src/main/java/CordaCaplet.java
> +                "--add-opens=java.base/java.security.cert=ALL-UNNAMED",
JIRA

2023-11-01 13:12 UTC, adelel1 commented on node/src/integration-test/kotlin/net/corda/node/NodeRPCTests.kt
> +    private val CLASSIFIER = ""
TODO

2023-11-01 13:14 UTC, adelel1 commented on node/src/integration-test/kotlin/net/corda/node/flows/FlowEntityManagerTest.kt
> +        Assume.assumeTrue(!SystemUtils.isJavaVersionAtLeast(JavaVersion.JAVA_11))
TODO

2023-11-01 13:14 UTC, adelel1 commented on node/src/main/kotlin/net/corda/node/internal/DataSourceFactory.kt
>          LoggerFactory.getLogger(javaClass).debug("Applying H2 fix.") // See CORDA-924.
JIRA

2023-11-01 13:15 UTC, adelel1 commented on node/src/main/kotlin/net/corda/node/services/persistence/AbstractPartyDescriptor.kt
> +                return uncheckedCast(toString(value)) as X?
JIRA

2023-11-01 13:16 UTC, adelel1 commented on node/src/main/kotlin/net/corda/node/services/statemachine/SingleThreadedStateMachineManager.kt
> +            is FlowState.Paused -> { /* AXM TODO */ }
JIRA

2023-11-01 13:16 UTC, adelel1 commented on node/src/test/kotlin/net/corda/node/internal/NodeTest.kt
> +        assertTrue(SystemUtils.IS_JAVA_1_8 || SystemUtils.isJavaVersionAtLeast(JavaVersion.JAVA_11))
TODO

2023-11-01 13:17 UTC, adelel1 commented on node/src/test/kotlin/net/corda/node/internal/cordapp/JarScanningCordappLoaderTest.kt
> -        val jar = JarScanningCordappLoaderTest::class.java.getResource("/workflowClassAtVersion55.jar")!!
JIRA

2023-11-01 13:18 UTC, adelel1 commented on node/src/test/kotlin/net/corda/node/migration/IdentityServiceToStringShortMigrationTest.kt
> +            assertThat(groupedByNameIdentities[it]?.size!!, greaterThan(1))
TODO

2023-11-01 13:18 UTC, adelel1 commented on node/src/test/kotlin/net/corda/node/services/vault/VaultQueryJoinTest.kt
> +            Assume.assumeTrue(!SystemUtils.isJavaVersionAtLeast(JavaVersion.JAVA_11))
TODO

2023-11-01 13:19 UTC, adelel1 commented on opentelemetry/build.gradle
> +//    id 'corda.common-publishing'
TODO

2023-11-01 13:22 UTC, adelel1 commented on samples/cordapp-configuration/src/main/resources/log4j2.xml
> +        <Property name="log_path">build/logs</Property>
Changed to make property names consistent.

2023-11-01 13:22 UTC, adelel1 commented on samples/cordapp-configuration/build.gradle
> +    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
JIRA

2023-11-01 13:24 UTC, adelel1 commented on samples/irs-demo/web/build.gradle
> +//    realBower {
@adelel1 to add JIRA

2023-11-01 13:24 UTC, adelel1 commented on samples/simm-valuation-demo/contracts-states/build.gradle
> +//    shrinkArtifacts file: sign.outputJars.singleFile, name: project.name, type: 'jar', extension: 'jar', classifier: 'tiny', builtBy: sign
TODO

2023-11-01 13:25 UTC, adelel1 commented on samples/simm-valuation-demo/src/integration-test/kotlin/net/corda/vega/SimmValuationTest.kt
> +    @Ignore("TODO JDK17: Fixme - Stage 2")
JIRA

2023-11-01 13:26 UTC, adelel1 commented on tools/explorer/src/main/kotlin/net/corda/explorer/views/cordapps/cash/NewTransaction.kt
> +        val notariesNotNullBinding = Bindings.createBooleanBinding({ notaries.isNotEmpty() }, *arrayOf(notaries))
TODO

2023-11-01 13:28 UTC, adelel1 commented on build.gradle
>  import static org.gradle.api.JavaVersion.VERSION_11
JIRA

2023-11-01 13:31 UTC, adelel1 commented on core/src/main/kotlin/net/corda/core/crypto/CordaSecurityProvider.kt
> +        super.getService("UNDEFINED", "UNDEFINED")
JIRA

2023-11-01 13:33 UTC, adelel1 commented on core/src/main/kotlin/net/corda/core/internal/concurrent/CordaFutureImpl.kt
> +    fun <W> thenImpl(log: Logger, callback: (CordaFuture<V>) -> W) {
JIRA Dont we need to add in CordaInternal annotation here.

2023-11-01 13:34 UTC, adelel1 commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
> +import net.corda.core.internal.JDK11_CLASS_FILE_FORMAT_MAJOR_VERSION
JIRA

2023-11-01 13:36 UTC, adelel1 commented on experimental/nodeinfo/build.gradle
> +    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
JIRA

2023-11-01 13:38 UTC, adelel1 commented on node-api/src/main/kotlin/net/corda/nodeapi/internal/bridging/AMQPBridgeManager.kt
> +            val runnable = @DontInstrument {
JIRA

2023-11-01 13:39 UTC, adelel1 commented on node/src/integration-test/kotlin/net/corda/node/services/statemachine/FlowHospitalTest.kt
>              }
TODO

2023-11-01 13:40 UTC, adelel1 commented on opentelemetry/opentelemetry-driver/build.gradle
> +        shadow(MavenPublication) { publication ->
JIRA

2023-11-01 13:41 UTC, adelel1 commented on .ci/api-current.txt
JIRA

2023-11-01 13:45 UTC, adelel1 commented on constants.properties
>  jacksonVersion=2.13.5
JIRA

2023-11-01 13:47 UTC, adelel1 commented on core-tests/src/test/kotlin/net/corda/coretests/flows/AbstractFlowExternalOperationTest.kt
> +                Strand.sleep(1000)
JIRA

2023-11-01 13:49 UTC, adelel1 commented on core/src/test/java/net/corda/core/internal/X509EdDSAEngineTest.java
> +    @Ignore
Done

2023-11-02 14:31 UTC, arshadm commented on build.gradle
> +//            ex.append = false
JIRA - Enable full code coverage reporting - https://r3-cev.atlassian.net/browse/ENT-11080

2023-11-02 14:32 UTC, arshadm commented on client/jackson/build.gradle
> +    implementation project(':core')
https://r3-cev.atlassian.net/browse/ENT-11081

2023-11-02 14:34 UTC, arshadm commented on client/jackson/build.gradle
>          exclude module: "jackson-databind"
https://r3-cev.atlassian.net/browse/ENT-11082

2023-11-02 14:42 UTC, arshadm commented on client/jackson/build.gradle
> +
Done

2023-11-02 14:43 UTC, arshadm commented on client/jfx/build.gradle
> +    version = "11.0.2"
https://r3-cev.atlassian.net/browse/ENT-11083

2023-11-02 14:43 UTC, arshadm commented on client/rpc/build.gradle
> +    implementation project(':node-api')
https://r3-cev.atlassian.net/browse/ENT-11081

2023-11-02 14:45 UTC, arshadm commented on build.gradle
> +            '--add-opens', 'java.base/java.util.concurrent=ALL-UNNAMED', '--add-opens', 'java.sql/java.sql=ALL-UNNAMED'
https://r3-cev.atlassian.net/browse/ENT-11084

2023-11-02 14:46 UTC, arshadm commented on core-tests/build.gradle
> +    }
https://r3-cev.atlassian.net/browse/ENT-11085

2023-11-02 14:47 UTC, arshadm commented on core-tests/src/test/kotlin/net/corda/coretests/node/VaultUpdateTests.kt
> +        val emptyUpdate = Vault.Update(emptySet<StateAndRef<*>>(), emptySet(), type = Vault.UpdateType.GENERAL, references = emptySet())
https://r3-cev.atlassian.net/browse/ENT-11086

2023-11-02 14:49 UTC, arshadm commented on core/src/main/kotlin/net/corda/core/concurrent/ConcurrencyUtils.kt
> +fun <V, W> firstOf(futures: Array<out CordaFuture<out V>>, log: Logger, handler: (CordaFuture<out V>) -> W): CordaFuture<W> {
https://r3-cev.atlassian.net/browse/ENT-11087

2023-11-02 14:50 UTC, arshadm commented on core/src/main/kotlin/net/corda/core/internal/ClassLoadingUtils.kt
> +            }
https://r3-cev.atlassian.net/browse/ENT-11090

2023-11-02 14:52 UTC, arshadm commented on core/src/main/kotlin/net/corda/core/internal/InternalUtils.kt
> +                // uncheckedCast(it.get(null))
https://r3-cev.atlassian.net/browse/ENT-11069

2023-11-02 14:53 UTC, arshadm commented on core/src/main/kotlin/net/corda/core/internal/concurrent/CordaFutureImpl.kt
> +class CordaFutureImpl<V>(private val impl: CompletableFuture<V> = CompletableFuture()) : Future<V> by impl, OpenFuture<V> {
https://r3-cev.atlassian.net/browse/ENT-11087

2023-11-02 14:53 UTC, arshadm commented on core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
> +    fun toWireTransactionWithContext(
https://r3-cev.atlassian.net/browse/ENT-11087

2023-11-02 14:54 UTC, arshadm commented on core/src/main/kotlin/net/corda/core/utilities/KotlinUtils.kt
> +fun interface SerializableLambda2<S, T, R> : (S, T) -> R, Serializable
https://r3-cev.atlassian.net/browse/ENT-11087

2023-11-02 14:56 UTC, arshadm commented on core/src/main/kotlin/net/corda/core/utilities/Try.kt
> +
Done

2023-11-02 15:01 UTC, arshadm commented on core/src/test/kotlin/net/corda/core/internal/InternalUtilsTest.kt
> +        val a: Array<String> = Stream.of("one", "two").toTypedArray() as Array<String>
https://r3-cev.atlassian.net/browse/ENT-11086

2023-11-02 15:01 UTC, arshadm commented on experimental/corda-utils/build.gradle
> +    implementation project(':core')
https://r3-cev.atlassian.net/browse/ENT-11081

2023-11-02 15:02 UTC, arshadm commented on experimental/netparams/build.gradle
> +    implementation project(':core')
https://r3-cev.atlassian.net/browse/ENT-11081

2023-11-02 15:02 UTC, arshadm commented on gradle.properties
> +json_api_version=1.1.4
Done.

2023-11-02 15:03 UTC, arshadm commented on node-api/build.gradle
> +    implementation project(":core")
https://r3-cev.atlassian.net/browse/ENT-11081

2023-11-02 15:04 UTC, arshadm commented on node-api/build.gradle
> +    implementation "org.apache.activemq:artemis-commons:${artemis_version}"
https://r3-cev.atlassian.net/browse/ENT-11092

2023-11-02 15:05 UTC, arshadm commented on node-api/build.gradle
> +    implementation "io.reactivex:rxjava:$rxjava_version"
https://r3-cev.atlassian.net/browse/ENT-11081

2023-11-02 15:06 UTC, arshadm commented on node-api/build.gradle
> +    implementation "io.reactivex:rxjava:$rxjava_version"
Done

2023-11-02 15:06 UTC, arshadm commented on node-api/build.gradle
> +    api "javax.persistence:javax.persistence-api:2.2"
DOne

2023-11-02 15:07 UTC, arshadm commented on node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/kryo/Kryo.kt
> +    private val delegate: Serializer<Throwable> = uncheckedCast(SerializerFactory.ReflectionSerializerFactory.newSerializer(kryo, FieldSerializer::class.java, type)) as Serializer<Throwable>
Done

2023-11-02 15:07 UTC, arshadm commented on node-api/src/test/kotlin/net/corda/nodeapi/internal/serialization/kryo/KryoTests.kt
> +        if (SystemUtils.isJavaVersionAtLeast(JavaVersion.JAVA_11))
https://r3-cev.atlassian.net/browse/ENT-11090

2023-11-02 15:08 UTC, arshadm commented on node/capsule/build.gradle
> +    implementation "com.typesafe:config:$typesafe_config_version"
Done

2023-11-02 15:09 UTC, arshadm commented on node/capsule/build.gradle
> +    // We only need this dependency to implementation our Caplet against.
Done

2023-11-02 15:09 UTC, arshadm commented on node/capsule/src/main/java/CordaCaplet.java
> +                "--add-opens=java.base/java.security.cert=ALL-UNNAMED",
https://r3-cev.atlassian.net/browse/ENT-11090

2023-11-02 15:10 UTC, arshadm commented on node/src/integration-test/kotlin/net/corda/node/NodeRPCTests.kt
> +    private val CLASSIFIER = ""
Done

2023-11-02 15:16 UTC, arshadm commented on node/src/integration-test/kotlin/net/corda/node/flows/FlowEntityManagerTest.kt
> +        Assume.assumeTrue(!SystemUtils.isJavaVersionAtLeast(JavaVersion.JAVA_11))
Done

2023-11-02 15:19 UTC, arshadm commented on node/src/main/kotlin/net/corda/node/internal/DataSourceFactory.kt
>          LoggerFactory.getLogger(javaClass).debug("Applying H2 fix.") // See CORDA-924.
https://r3-cev.atlassian.net/browse/ENT-11093

2023-11-02 15:20 UTC, arshadm commented on node/src/main/kotlin/net/corda/node/services/persistence/AbstractPartyDescriptor.kt
> +                return uncheckedCast(toString(value)) as X?
https://r3-cev.atlassian.net/browse/ENT-11069

2023-11-02 15:22 UTC, arshadm commented on node/src/main/kotlin/net/corda/node/services/statemachine/SingleThreadedStateMachineManager.kt
> +            is FlowState.Paused -> { /* AXM TODO */ }
https://r3-cev.atlassian.net/browse/ENT-11094

2023-11-02 15:22 UTC, arshadm commented on node/src/test/kotlin/net/corda/node/internal/NodeTest.kt
> +        assertTrue(SystemUtils.IS_JAVA_1_8 || SystemUtils.isJavaVersionAtLeast(JavaVersion.JAVA_11))
https://r3-cev.atlassian.net/browse/ENT-11090

2023-11-02 15:25 UTC, arshadm commented on node/src/test/kotlin/net/corda/node/internal/cordapp/JarScanningCordappLoaderTest.kt
> -        val jar = JarScanningCordappLoaderTest::class.java.getResource("/workflowClassAtVersion55.jar")!!
https://r3-cev.atlassian.net/browse/ENT-11095

2023-11-02 15:26 UTC, arshadm commented on node/src/test/kotlin/net/corda/node/migration/IdentityServiceToStringShortMigrationTest.kt
> +            assertThat(groupedByNameIdentities[it]?.size!!, greaterThan(1))
Needed due to Kotlin type inference.

2023-11-02 15:27 UTC, arshadm commented on node/src/test/kotlin/net/corda/node/services/vault/VaultQueryJoinTest.kt
> +            Assume.assumeTrue(!SystemUtils.isJavaVersionAtLeast(JavaVersion.JAVA_11))
Done

2023-11-02 15:28 UTC, arshadm commented on opentelemetry/build.gradle
> +//    id 'corda.common-publishing'
Done

2023-11-02 15:29 UTC, arshadm commented on samples/cordapp-configuration/build.gradle
> +    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
https://r3-cev.atlassian.net/browse/ENT-11096

2023-11-02 15:31 UTC, arshadm commented on samples/simm-valuation-demo/contracts-states/build.gradle
> +//    shrinkArtifacts file: sign.outputJars.singleFile, name: project.name, type: 'jar', extension: 'jar', classifier: 'tiny', builtBy: sign
https://r3-cev.atlassian.net/browse/ENT-11097

2023-11-02 15:32 UTC, arshadm commented on samples/simm-valuation-demo/src/integration-test/kotlin/net/corda/vega/SimmValuationTest.kt
> +    @Ignore("TODO JDK17: Fixme - Stage 2")
https://r3-cev.atlassian.net/browse/ENT-11097

2023-11-02 15:33 UTC, arshadm commented on settings.gradle
> +//include 'tools:demobench'
https://r3-cev.atlassian.net/browse/ENT-11098

2023-11-02 15:36 UTC, arshadm commented on build.gradle
>  import static org.gradle.api.JavaVersion.VERSION_11
https://r3-cev.atlassian.net/browse/ENT-11099

2023-11-02 15:37 UTC, arshadm commented on core/src/main/kotlin/net/corda/core/crypto/CordaSecurityProvider.kt
> +        super.getService("UNDEFINED", "UNDEFINED")
https://r3-cev.atlassian.net/browse/ENT-11100

2023-11-02 15:40 UTC, arshadm commented on core/src/main/kotlin/net/corda/core/internal/concurrent/CordaFutureImpl.kt
> +    fun <W> thenImpl(log: Logger, callback: (CordaFuture<V>) -> W) {
https://r3-cev.atlassian.net/browse/ENT-11070

2023-11-02 15:41 UTC, arshadm commented on core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt
> +import net.corda.core.internal.JDK11_CLASS_FILE_FORMAT_MAJOR_VERSION
https://r3-cev.atlassian.net/browse/ENT-11099

2023-11-02 15:42 UTC, arshadm commented on experimental/nodeinfo/build.gradle
> +    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
https://r3-cev.atlassian.net/browse/ENT-11096

2023-11-02 15:43 UTC, arshadm commented on node-api/src/main/kotlin/net/corda/nodeapi/internal/bridging/AMQPBridgeManager.kt
> +            val runnable = @DontInstrument {
https://r3-cev.atlassian.net/browse/ENT-11102

2023-11-02 15:44 UTC, arshadm commented on node/src/integration-test/kotlin/net/corda/node/services/statemachine/FlowHospitalTest.kt
>              }
Done

2023-11-02 15:45 UTC, arshadm commented on opentelemetry/opentelemetry-driver/build.gradle
> +        shadow(MavenPublication) { publication ->
https://r3-cev.atlassian.net/browse/ENT-11103

2023-11-02 15:47 UTC, arshadm commented on testing/test-utils/src/main/kotlin/net/corda/testing/internal/FlowStackSnapshot.kt
> +        private const val QUASAR_0_8_INSTRUMENTED_CLASS_NAME = "co.paralleluniverse.fibers.suspend.Instrumented"
https://r3-cev.atlassian.net/browse/ENT-11099

2023-11-02 15:48 UTC, arshadm commented on .ci/api-current.txt
https://r3-cev.atlassian.net/browse/ENT-11104

2023-11-02 15:49 UTC, arshadm commented on Jenkinsfile
> +        JAVA_HOME="/usr/lib/jvm/java-17-amazon-corretto"
https://r3-cev.atlassian.net/browse/ENT-11105

2023-11-02 15:51 UTC, arshadm commented on constants.properties
>  jacksonVersion=2.13.5
https://r3-cev.atlassian.net/browse/ENT-11106

2023-11-02 15:52 UTC, arshadm commented on core-tests/src/test/kotlin/net/corda/coretests/flows/AbstractFlowExternalOperationTest.kt
> +                Strand.sleep(1000)
https://r3-cev.atlassian.net/browse/ENT-11102

2023-11-02 17:50 UTC, shamsasari commented on core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
> +    fun toWireTransactionWithContext(
I think there's something wrong here. For one, the JIRA ticket is about unused APIs, but this method is very much used. Further, I still can't see how this needs to be made public. I checked your ENT branch to see if you're calling it from there, but that's not the case. From what I can see, this doesn't need the `internal` removed.

2023-11-03 10:59 UTC, shamsasari commented on core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
> +    fun toLedgerTransactionWithContext(services: ServicesForResolution, serializationContext: SerializationContext): LedgerTransaction {
Please annotate with with `@CordaInternal`.

2023-11-03 11:02 UTC, shamsasari commented on core/src/test/java/net/corda/core/internal/X509EdDSAEngineTest.java
> +//    private X509Key toX509Key(EdDSAPublicKey publicKey) throws IOException, InvalidKeyException {
I feel very uncomfortable with all this commented out code. What's the JIRA ticket please?

2023-11-03 12:01 UTC, adelel1 commented on samples/irs-demo/web/build.gradle
> +//    realBower {
https://r3-cev.atlassian.net/browse/ENT-11109

2023-11-03 12:13 UTC, adelel1 commented on core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
> +    fun toLedgerTransactionWithContext(services: ServicesForResolution, serializationContext: SerializationContext): LedgerTransaction {
https://r3-cev.atlassian.net/browse/ENT-11070

2023-11-03 13:09 UTC, adelel1 commented on core/src/test/java/net/corda/core/internal/X509EdDSAEngineTest.java
> +//    private X509Key toX509Key(EdDSAPublicKey publicKey) throws IOException, InvalidKeyException {
https://r3-cev.atlassian.net/browse/ENT-11112

2023-11-03 13:41 UTC, shamsasari commented on core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
> +    fun toWireTransactionWithContext(
I'll address this in my PR

2023-11-03 13:41 UTC, shamsasari commented on core/src/main/kotlin/net/corda/core/transactions/TransactionBuilder.kt
> +    fun toLedgerTransactionWithContext(services: ServicesForResolution, serializationContext: SerializationContext): LedgerTransaction {
I've resolved this in my PR

2023-11-03 13:42 UTC, shamsasari approved these changes, later dismissed

2023-11-06 12:51 UTC, shamsasari approved these changes

2023-11-06 13:10 UTC, merged