ENT-6914 Fixes after audit of 4.11/4.12 release branches after merge
corda/corda pull request #7570
Opened 2023-11-10 10:49 UTC by arshadm

👮🏻👮🏻👮🏻 !!!! DESCRIBE YOUR CHANGES HERE !!!! DO NOT FORGET !!!! 👮🏻👮🏻👮🏻

# PR Checklist:

- [ ] Have you run the unit, integration and smoke tests as described [here](https://docs.r3.com/en/platform/corda/4.8/open-source/testing.html)?
- [ ] If you added public APIs, did you write the JavaDocs/kdocs?
- [ ] If the changes are of interest to application developers, have you added them to the changelog, and potentially the [release notes](https://docs.corda.net/head/release-notes.html) (`https://docs.r3.com/en/platform/corda/4.8/open-source/release-notes.html`)?
- [ ] If you are contributing for the first time, please read the [contributor agreement](https://docs.r3.com/en/platform/corda/4.8/open-source/contributing.html) now and add a comment to this pull request stating that your PR is in accordance with the [Developer's Certificate of Origin](https://docs.r3.com/en/platform/corda/4.8/open-source/contributing.html#merging-the-changes-back-into-corda).

Thanks for your code, it's appreciated! :)

2023-11-13 10:20 UTC, adelel1 approved these changes

2023-11-13 10:22 UTC, adelel1 commented on tools/checkpoint-agent/src/main/kotlin/net/corda/tools/CheckpointAgent.kt
> +                // TODO JDK17: Exhaustive checking, unhandled case
Why remove the log.info ?

2023-12-18 15:24 UTC, shamsasari requested changes
It doesn't look like this PR is needed anymore.

2023-12-18 15:43 UTC, arshadm commented on tools/checkpoint-agent/src/main/kotlin/net/corda/tools/CheckpointAgent.kt
> +                // TODO JDK17: Exhaustive checking, unhandled case
Added TODO instead, so that we can check whether any genuine fix is required. The old behaviour of Kotlin was fall-thru.

2023-12-18 15:44 UTC, arshadm commented
@shamsasari @colljos I think the refactor of the tests was not rebased correctly. So I think we still need this PR to carry through the work from 4.11

2023-12-18 15:51 UTC, shamsasari commented
> @shamsasari @colljos I think the refactor of the tests was not rebased correctly. So I think we still need this PR to carry through the work from 4.11

The `X509EdDSAEngine` tests are already fixed and so no longer need the `@Ignore` and the tests are already removed from `DBTransactionStorageLedgerRecoveryTests`

2023-12-18 15:52 UTC, shamsasari commented
You have merge conflicts anyway, so fixing those will show what's left anyway.

2023-12-18 15:53 UTC, arshadm commented
ok, will close. The only reason for creating this PR was the test re-factor.

2023-12-18 15:53 UTC, closed without merging