ENT-11113 Updating test case for accessing modifier as per JDK17 compatibility
corda/corda pull request #7647
Opened 2024-01-15 09:57 UTC by balwantkothari

ENT-11113 Updating test case for accessing modifier as per JDK17 compatibility

2024-01-16 09:24 UTC, shamsasari requested changes

2024-01-16 09:24 UTC, shamsasari commented on node/src/test/kotlin/net/corda/node/services/config/ConfigHelperTests.kt
>      fun `bad keys are ignored and warned for`() {
Can I say that I don't like how this test was originally written? First using reflection to override the final modifier on the static logger and then setting up a mock on in its place?? 🤯 

Anyway, @balwantkothari, if you remove this mock logger code, then the expected message is logged to the stdout. A better solution, one that won't require this reflection hack, is to override the stdout with  `System.setOut` and assert on the captured logs that way, as explained [here](https://stackoverflow.com/a/1119559/3318571).

2024-01-17 18:51 UTC, balwantkothari commented on node/src/test/kotlin/net/corda/node/services/config/ConfigHelperTests.kt
>      fun `bad keys are ignored and warned for`() {
Have updated code to remove mock and used sys out content to verify the output

2024-01-17 18:57 UTC, shamsasari requested changes
some cleanup

2024-01-17 18:57 UTC, shamsasari commented on node/build.gradle
> +    jvmArgs(['--add-opens', 'java.base/java.lang.reflect=ALL-UNNAMED', '--add-opens', 'java.base/java.util=ALL-UNNAMED'])
You can revert this now.

2024-01-17 18:57 UTC, shamsasari commented on node/src/test/kotlin/net/corda/node/services/config/ConfigHelperTests.kt
> +        val errContent = ByteArrayOutputStream()
Since you're only looking in stdout, there's no need to overrwrite stderr.

2024-01-17 18:57 UTC, shamsasari commented on node/src/test/kotlin/net/corda/node/services/config/ConfigHelperTests.kt
> +        System.setOut(originalOut);
Reset stdout in a finally block

2024-01-17 19:06 UTC, balwantkothari commented on node/build.gradle
> +    jvmArgs(['--add-opens', 'java.base/java.lang.reflect=ALL-UNNAMED', '--add-opens', 'java.base/java.util=ALL-UNNAMED'])
updated

2024-01-17 19:06 UTC, balwantkothari commented on node/src/test/kotlin/net/corda/node/services/config/ConfigHelperTests.kt
> +        System.setOut(originalOut);
Done.

2024-01-18 06:59 UTC, balwantkothari commented on node/src/test/kotlin/net/corda/node/services/config/ConfigHelperTests.kt
> +        val errContent = ByteArrayOutputStream()
done.

2024-01-18 09:04 UTC, shamsasari approved these changes
Looks good

2024-01-18 12:24 UTC, merged